### ISSUE TITLE
Sentinel for Spring Cloud Gateway supports cluster flow control?

### ISSUE THREAD

**Issue by gtihubxw** [alibaba/Sentinel#1001]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Sentinel for Spring Cloud Gateway supports cluster flow control

### Describe what you expected to happen

Sentinel for Spring Cloud Gateway supports cluster flow control

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, the gateway-specified cluster flow control (aka. `GatewayFlowRule`) is not supported yet, but you could leverage the normal cluster flow rule (`FlowRule`) and parameter flow rule.

**Comment by gtihubxw** [comment]
thanks ,and do you have a schedule for this feature?

**Comment by sczyh30** [comment]
It's not scheduled yet. Discussions and contributions are welcomed.
