### ISSUE TITLE
look for what touch off the Exception

### ISSUE THREAD

**Issue by Assassin199108** [alibaba/Sentinel#1005]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
My degrade rule has three points with the same key，the DegradeException happen to three of one point , and when i try catch this exception,i knew what BlockException it is, but I don't know what grade touch off this exception

### Describe what you expected to happen
when i try catch this exception , i want know what grade touch off

### How to reproduce it (as minimally and precisely as possible)

1. just one key setting up more than one grade
2. and touch off blockexception
3. 

### Tell us your environment
test

### Anything else we need to know?
i want to log this exception touch off and trance debug it

**Comment by sczyh30** [comment]
You may get the triggered `DegradeRule` via `BlockException#getRule` method.

**Comment by Assassin199108** [comment]
> You may get the triggered `DegradeRule` via `BlockException#getRule` method.

oh, what version has getRule method, maybe my version is too low

**Comment by sczyh30** [comment]
> > You may get the triggered `DegradeRule` via `BlockException#getRule` method.
> 
> oh, what version has getRule method, maybe my version is too low

since 1.4.2
