### ISSUE TITLE
Sentinel dashboard-1.6.3 UI shows problems and issues by time period

### ISSUE THREAD

**Issue by qinxingnet** [alibaba/Sentinel#1006]
![image](https://user-images.githubusercontent.com/4750020/63422747-9302e380-c43d-11e9-9c89-edcda414c2b7.png)

**Comment by zhaoyuguang** [comment]
@qinxingnet  For question `1.Sentinel dashboard-1.6.3 UI显示不全问题`. 
How do you want to it show?

**Comment by qinxingnet** [comment]
> @qinxingnet For question `1.Sentinel dashboard-1.6.3 UI显示不全问题`.
> How do you want to it show?

1.Sentinel dashboard-1.6.3 UI显示不全问题
2.目前的流控可否支持类似corn表达式,用于类似于秒杀活动生效的作法 ?
3.权限同nocos一样.可否支持域控和自定义outh或UAC用户管理服务?
