### ISSUE TITLE
version 1.6.3  the jar file not match source file, how to get source file and compile ?

### ISSUE THREAD

**Issue by maxiaolong** [alibaba/Sentinel#1016]
sentinel-core-1.6.3.jar

![QQ截图20190826165125](https://user-images.githubusercontent.com/11644095/63678428-cf5d8780-c821-11e9-99bf-7418699ff5d8.png)

1.6.3 source code not found this class file

**Comment by shenzhou-6** [comment]
class ResourceTypeConstants since 1.70.... so not exist 1.6.3..............

if get 1.6.3 source .checkout branch release-1.6

**Comment by sczyh30** [comment]
These classes will be merged to master soon (as part of 1.7.0 but actually released in 1.6.3 earlier)
