### ISSUE TITLE
Push gateway rules to zookeeper datasource

### ISSUE THREAD

**Issue by lkxiaolou** [alibaba/Sentinel#1021]

**Comment by lkxiaolou** [comment]
found the same #992

**Comment by sczyh30** [comment]
If you're going to publish the gateway rules to ZooKeeper you'll need to refactor the dashboard. See https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#Push模式

For push-based data-source, it's not recommended to push rules via the `WritableDataSource` in the client side.

**Comment by lkxiaolou** [comment]
> If you're going to publish the gateway rules to ZooKeeper you'll need to refactor the dashboard. See [https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#Push模式](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel#Push%E6%A8%A1%E5%BC%8F)
> 
> For push-based data-source, it's not recommended to push rules via the `WritableDataSource` in the client side.

Not only gateway rules, should publish api-definitions with zookeeper ?

**Comment by lkxiaolou** [comment]
@sczyh30 And there is an another question, does the dashboard can deploy in cluster mode? If yes, how to watch the InMemoryRuleRepository change events? If no, how to guarantee dashboard high availability ?

**Comment by linlinisme** [comment]
> @sczyh30 And there is an another question, does the dashboard can deploy in cluster mode? If yes, how to watch the InMemoryRuleRepository change events? If no, how to guarantee dashboard high availability ?

@lkxiaolou  the dashboard and sentinel-core 's relationship seems like the redis-client and redis-server. People always ask how  to guarantee redis-server high availability, but seems rarely ask how to guarantee redis-client high availability, haha.

**Comment by lkxiaolou** [comment]
> > @sczyh30 And there is an another question, does the dashboard can deploy in cluster mode? If yes, how to watch the InMemoryRuleRepository change events? If no, how to guarantee dashboard high availability ?
> 
> @lkxiaolou the dashboard and sentinel-core 's relationship seems like the redis-client and redis-server. People always ask how to guarantee redis-server high availability, but seems rarely ask how to guarantee redis-client high availability, haha.

I want to deploy many applications with sentinel-core and one sentinel-dashboard in cluster mode

**Comment by sczyh30** [comment]
> > > @sczyh30 And there is an another question, does the dashboard can deploy in cluster mode? If yes, how to watch the InMemoryRuleRepository change events? If no, how to guarantee dashboard high availability ?
> > 
> > 
> > @lkxiaolou the dashboard and sentinel-core 's relationship seems like the redis-client and redis-server. People always ask how to guarantee redis-server high availability, but seems rarely ask how to guarantee redis-client high availability, haha.
> 
> I want to deploy many applications with sentinel-core and one sentinel-dashboard in cluster mode

You may refer to #363
