### ISSUE TITLE
Sentinel 1.6.3 + apollo Cannot resolve reference to bean 'sentinel-json-gw-flow-converter'

### ISSUE THREAD

**Issue by zcjhwl** [alibaba/Sentinel#1026]
Sentinel integration Apollo configuration cloud gateway 

## Issue Description
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ds5-sentinel-apollo-datasource': Cannot resolve reference to bean 'sentinel-json-gw-flow-converter' while setting bean property 'converter'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'sentinel-json-gw-flow-converter' available

### Describe what happened (or what feature you want)
spring.cloud.sentinel.datasource.ds.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds.apollo.flow-rules-key = flow.rules
spring.cloud.sentinel.datasource.ds.apollo.rule-type = flow

spring.cloud.sentinel.datasource.ds1.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds1.apollo.flow-rules-key = degrade.rules
spring.cloud.sentinel.datasource.ds1.apollo.rule-type = degrade

spring.cloud.sentinel.datasource.ds2.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds2.apollo.flow-rules-key = param_flow.rules
spring.cloud.sentinel.datasource.ds2.apollo.rule-type = param_flow

spring.cloud.sentinel.datasource.ds3.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds3.apollo.flow-rules-key = system.rules
spring.cloud.sentinel.datasource.ds3.apollo.rule-type = system

spring.cloud.sentinel.datasource.ds4.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds4.apollo.flow-rules-key = authority.rules
spring.cloud.sentinel.datasource.ds4.apollo.rule-type = authority

spring.cloud.sentinel.datasource.ds5.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds5.apollo.flow-rules-key = gw_flow.rules
spring.cloud.sentinel.datasource.ds5.apollo.rule-type = gw_flow

spring.cloud.sentinel.datasource.ds6.apollo.namespace-name = sentinel
spring.cloud.sentinel.datasource.ds6.apollo.flow-rules-key = gw_api_group.rules
spring.cloud.sentinel.datasource.ds6.apollo.rule-type = gw_api_group

**Comment by zcjhwl** [comment]
help thanks

**Comment by sczyh30** [comment]
Which `spring-cloud-alibaba-sentinel` version are you using?

cc @fangjian0423

**Comment by cdfive** [comment]
[https://github.com/alibaba/spring-cloud-alibaba/releases](https://github.com/alibaba/spring-cloud-alibaba/releases)
It seems that need to use version of `1.5.0.RELEASE` or above, suggest using latest version.

**Comment by sczyh30** [comment]
@zcjhwl Any feedback?

**Comment by sczyh30** [comment]
Closing this issue due to no feedback.
