### ISSUE TITLE
SimpleHttpHeartbeatSender InetSocketAddress

### ISSUE THREAD

**Issue by yuweibo** [alibaba/Sentinel#1030]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

deploy sentinel dashboard console to another machine,service node will lost,never send heartbeat to dashboard unless reboot

### Describe what you expected to happen

deploy sentinel console to any machine

### How to reproduce it (as minimally and precisely as possible)

1. deploy dashboard console
2. start service node,this service will display on dashboard console
3. stop dashboard console and start on another machine

### Tell us your environment

csp.sentinel.dashboard.server param set dns instead ip

### Anything else we need to know?

nothing

**Comment by jasonjoo2010** [comment]
hi, @yuweibo 

You can try this PR(#926 ) to see whether it still use the old address forever.
