### ISSUE TITLE
I think there is something wrong with InMemoryMetricsRepository

### ISSUE THREAD

**Issue by shepherdviolet** [alibaba/Sentinel#1031]
Today we are doing some testing. We found that only 1-3 minutes of data can be displayed in the real-time monitoring page (实时监控页). Especially when stress testing, only the last minute can be displayed. But the document shows that this page can display the last five minutes.

So I read the source code, I think this logic was originally designed to display the last five minutes, until the [PR #488](https://github.com/alibaba/Sentinel/pull/488) merged.

I am not sure that this PR have some problems, maybe the contributor has some reasonable considerations. But it does evict data earlier, before 5 minutes elapsed.

Class 'InMemoryMetricsRepository' uses ConcurrentLinkedHashMap to store metric data, and set capacity to MAX_METRIC_LIVE_TIME_MS (5 minutes), than define the weight of each element as 'currentTime - sampleTime'. I don't think this can achieve logic that only keeps the data for 5 minutes. The 'weight' should not be used like this. 

In this case, older data is heavier and takes up more space. If the timestamp of element is exactly equal to 'currentTime - 1000 * 60 * 5' , its weight is equal to MAX_METRIC_LIVE_TIME_MS. Fortunately, the weight is only calculated when the element is added. XD.
If the data is pulled from the client in a timely manner, the problem will be less serious.

The weight of each element is equal to one time unit (1000ms ?), will it be better? Although it will take up a lot of memory...

**Comment by shepherdviolet** [comment]
Today, we provide our own optimized version, for reference only. we rewrites InMemoryMetricsRepository (-28%) and MetricFetcher (-35%). Two measures can reduce memory consumption by 63%. And can store 5 minutes of data correctly. But there is a problem with this implementation. The time unit of the statistical sample must be seconds. So just for reference! I am not considering doing PR for the time being.

Our commit: 
https://github.com/shepherdviolet/Sentinel/commit/f2f7c2d5b7d08230fb37198674fc3caec3934d77

Memory usage comparison==============================================

When dashboard first start--------------------------------------------------------------------

Eden Space:
   used     = 28319160 (27.00725555419922MB)
PS Old Generation
   used     = 27016016 (25.764480590820312MB)

After stress testing (Before optimization, Official version 1.6.3)-----------------------------

Eden Space:
   used     = 18968336 (18.089614868164062MB)
PS Old Generation
   used     = 494753768 (471.8339614868164MB)

num     #instances         #bytes  class name
----------------------------------------------
   1:       1405179      137317560  [C
   2:       1342167       96636024  com.alibaba.csp.sentinel.dashboard.datasource.entity.MetricEntity
   3:       1342167       42949344  com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8$Node
   4:       1342167       42949344  com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$Node
   5:       1403866       33692784  java.lang.String
   6:       1342486       32219664  java.util.Date
   7:       1342428       32218272  java.lang.Long
   8:       1342167       32212008  com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$WeightedValue
   9:        778274       12452384  java.util.concurrent.atomic.AtomicReference
  10:          6033       12373904  [Lcom.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8$Node;

After stress testing (After optimization, Our optimized versrion)-----------------------------

Eden Space:
   used     = 21602440 (20.60169219970703MB)
PS Old Generation
   used     = 212671792 (202.8196258544922MB)

num     #instances         #bytes  class name
----------------------------------------------
   1:       1510283      108740376  com.alibaba.csp.sentinel.dashboard.datasource.entity.MetricEntity
   2:         15819       44006112  [Ljava.lang.Object;
   3:       1510630       36255120  java.util.Date
   4:         69149        9089640  [C
   5:         67846        1628304  java.lang.String
   6:         39527        1264864  java.util.concurrent.ConcurrentHashMap$Node
   7:          5366        1149296  [B
   8:         12151        1069288  java.lang.reflect.Method
   9:          8793         975448  java.lang.Class
  10:         12094         483760  java.util.LinkedHashMap$Entry

=================================================

MetricEntity's' field 'resource' takes up a lot of memory, but in fact the strings are duplicates and can be solved with String#intern. ConcurrentLinkedHashMap is powerful, but it is too cumbersome to store statistics.

**Comment by linlinisme** [comment]
> Today, we provide our own optimized version, for reference only. we rewrites InMemoryMetricsRepository (-28%) and MetricFetcher (-35%). Two measures can reduce memory consumption by 63%. And can store 5 minutes of data correctly. But there is a problem with this implementation. The time unit of the statistical sample must be seconds. So just for reference! I am not considering doing PR for the time being.
> 
> Our commit:
> [shepherdviolet@f2f7c2d](https://github.com/shepherdviolet/Sentinel/commit/f2f7c2d5b7d08230fb37198674fc3caec3934d77)
> 
> # Memory usage comparison
> ## When dashboard first start
> Eden Space:
> used = 28319160 (27.00725555419922MB)
> PS Old Generation
> used = 27016016 (25.764480590820312MB)
> 
> ## After stress testing (Before optimization, Official version 1.6.3)
> Eden Space:
> used = 18968336 (18.089614868164062MB)
> PS Old Generation
> used = 494753768 (471.8339614868164MB)
> 
> num instances bytes class name
> 1: 1405179 137317560 [C
> 2: 1342167 96636024 com.alibaba.csp.sentinel.dashboard.datasource.entity.MetricEntity
> 3: 1342167 42949344 com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8$Node
> 4: 1342167 42949344 com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$Node
> 5: 1403866 33692784 java.lang.String
> 6: 1342486 32219664 java.util.Date
> 7: 1342428 32218272 java.lang.Long
> 8: 1342167 32212008 com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$WeightedValue
> 9: 778274 12452384 java.util.concurrent.atomic.AtomicReference
> 10: 6033 12373904 [Lcom.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8$Node;
> 
> ## After stress testing (After optimization, Our optimized versrion)
> Eden Space:
> used = 21602440 (20.60169219970703MB)
> PS Old Generation
> used = 212671792 (202.8196258544922MB)
> 
> num instances bytes class name
> 1: 1510283 108740376 com.alibaba.csp.sentinel.dashboard.datasource.entity.MetricEntity
> 2: 15819 44006112 [Ljava.lang.Object;
> 3: 1510630 36255120 java.util.Date
> 4: 69149 9089640 [C
> 5: 67846 1628304 java.lang.String
> 6: 39527 1264864 java.util.concurrent.ConcurrentHashMap$Node
> 7: 5366 1149296 [B
> 8: 12151 1069288 java.lang.reflect.Method
> 9: 8793 975448 java.lang.Class
> 10: 12094 483760 java.util.LinkedHashMap$Entry
> 
> # P.S.
> MetricEntity's' field 'resource' takes up a lot of memory, but in fact the strings are duplicates and can be solved with String#intern. ConcurrentLinkedHashMap is powerful, but it is too cumbersome to store statistics.

Good proposal !    
And I also want to put forward my own suggestions.

- Should we still need `AtomicReferenceArray` here? 
` private Map<String, Map<String, AtomicReferenceArray<MetricEntity>>> allMetrics = new ConcurrentHashMap<>();`
the `com.alibaba.csp.sentinel.dashboard.repository.metric.InMemoryMetricsRepository#save`
had make the update operate is  thread-safe.  May be  `MetricEntity[] `  can make this proposal more perfect :). What do you think @sczyh30 ?

**Comment by ben-manes** [comment]
Is there a good reason [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap) was used in Sentinel? It was designed for Java 5, led to Guava's cache, and both are superseded by [Caffeine](https://github.com/ben-manes/caffeine). It may not be relevant for this issue, but please consider migrating.

**Comment by sczyh30** [comment]
> Is there a good reason [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap) was used in Sentinel? It was designed for Java 5, led to Guava's cache, and both are superseded by [Caffeine](https://github.com/ben-manes/caffeine). It may not be relevant for this issue, but please consider migrating.

The [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap) was used because the previous version of Sentinel requires compatibility with JDK 1.6. As the dashboard is designed for JDK 1.8+ we could migrate to Caffeine.

**Comment by linlinisme** [comment]
if set  MAX_METRIC_LIVE_TIME_MS = (1+2+3+....+ 1000 * 60 * 5 - 1), Could this problem be solved temporarily?

**Comment by jasonjoo2010** [comment]
Resolved in #1319 and welcome to try again to see if it will happen again.

**Comment by shepherdviolet** [comment]
> Resolved in #1319 and welcome to try again to see if it will happen again.

Appreciated it
