### ISSUE TITLE
The configured gateway current limit is not in effect

### ISSUE THREAD

**Issue by 1346735074** [alibaba/Sentinel#1036]
The configured gateway current limit is not in effect.
springcloud zuul
![image](https://user-images.githubusercontent.com/36881032/64329542-08f07880-d002-11e9-8d46-bf5c3c2af836.png)
![image](https://user-images.githubusercontent.com/36881032/64329562-10178680-d002-11e9-97d9-c46b3418a92d.png)
Access is still available after configuration.
Normal application configuration works.

**Comment by 1346735074** [comment]
@sczyh30 Please help me look at it.

**Comment by 1346735074** [comment]
```
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
    </dependency>
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    </dependency>
```

**Comment by 1346735074** [comment]
```
# sentinel dashboard
spring.cloud.sentinel.transport.dashboard=${SENTINEL_DASHBOARD:10.1.1.99:31001}
feign.sentinel.enabled=true
```

**Comment by sczyh30** [comment]
The `GatewayFlowRule` only takes effect for gateway routes or customized API groups. You may have to disable the Sentinel web filter, see https://github.com/alibaba/spring-cloud-alibaba/issues/821

**Comment by fangjian0423** [comment]
And you could refer Sentinel [Zuul Example](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-zuul-example).

**Comment by 1346735074** [comment]
@fangjian0423 It has been solved. Thank you.
