### ISSUE TITLE
The gateway pulls the rules from the nacos data source, the sentinel console rules are not displayed, but the rules take effect

### ISSUE THREAD

**Issue by wang271724646** [alibaba/Sentinel#1037]
## **从nacos拉取规则普通应用在sentinel控制台可以看到规则，但是网关看不到**。

我实验几次日志打印都是正确的，并且规则都生效，唯一发现不同的是:
网关的日志
**INFO [DynamicSentinelProperty]
INFO [FlowRuleManager] Flow rules loaded: {}
INFO App name resolved: cloud-gateway**
普通应用的日志
**INFO App name resolved: cloud-client-two
INFO [DynamicSentinelProperty]
INFO [FlowRuleManager] Flow rules loaded: {}**
他们日志打印的顺序不同，网关是先加载规则。
不知道是否和这个有关系，望解答，谢谢！

**Comment by cdfive** [comment]
Visit [http://ip:port/getRules?type=flow](http://client_ip:client_port/getRules?type=flow) to see whether flow rules are loaded on the client side.

The ip and port is client side's, e.g. localhost:8719

**Comment by wang271724646** [comment]
> Visit [http://ip:port/getRules?type=flow](http://client_ip:client_port/getRules?type=flow) to see whether flow rules are loaded on the client side.
> 
> The ip and port is client side's, e.g. localhost:8719

我看了是有值的，昨天弄得时候网关限流从nacos拉下来的规则是生效的，但是控制台不显示。
这是网关的规则
[{"clusterMode":false,"controlBehavior":0,"count":2.0,"grade":1,"limitApp":"default","maxQueueingTimeMs":500,"resource":"cloud-client-two","strategy":0,"warmUpPeriodSec":10}]
这是应用的规则
[{"clusterMode":false,"controlBehavior":0,"count":3.0,"grade":1,"limitApp":"default","maxQueueingTimeMs":500,"resource":"/getClient2Data2","strategy":0,"warmUpPeriodSec":10},{"clusterMode":false,"controlBehavior":0,"count":3.0,"grade":1,"limitApp":"default","maxQueueingTimeMs":500,"resource":"/getClient2Data","strategy":0,"warmUpPeriodSec":10}]
都是有值的，应用在sentinel控制台可以显示规则，网关显示不了，但规则生效。

**Comment by cdfive** [comment]
对了，网关应用需要加上VM参数`-Dcsp.sentinel.app.type=1`标记应用为 API Gateway 类型，
跟普通应用不一样，配置的是网关流控规则，不是普通流控规则。

客户端api：
获取网关流控规则 http://ip:port/gateway/getRules
获取api分组           http://ip:port/gateway/getApiDefinitions

参考：[https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台](https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台)

**Comment by wang271724646** [comment]
> 对了，网关应用需要加上VM参数`-Dcsp.sentinel.app.type=1`标记应用为 API Gateway 类型，
> 跟普通应用不一样，配置的是网关流控规则，不是普通流控规则。
> 
> 客户端api：
> 获取网关流控规则 http://ip:port/gateway/getRules
> 获取api分组 http://ip:port/gateway/getApiDefinitions
> 
> 参考：[https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0)

我是用的spring-cloud-alibaba-dependencies引的这个整合的，那个参数可以不写。
 http://ip:port/getRules?type=flow这个可以看到从nacos拉下来的规则。
 http://ip:port/gateway/getRules 这个地址是个空[]

**Comment by cdfive** [comment]
> 这是网关的规则
[{"clusterMode":false,"controlBehavior":0,"count":2.0,"grade":1,"limitApp":"default","maxQueueingTimeMs":500,"resource":"cloud-client-two","strategy":0,"warmUpPeriodSec":10}]

看这个json格式是**普通流控规则**类型的，网关应用需要配置**网关流控规则**才行。

参考：[https://github.com/alibaba/Sentinel/wiki/网关限流](https://github.com/alibaba/Sentinel/wiki/网关限流)

**Comment by wang271724646** [comment]
是的，确实对不上，我自己在控制台加了一条限流规则
[{"burst":0,"controlBehavior":0,"count":555555.0,"grade":1,"intervalSec":1,"maxQueueingTimeoutMs":500,"resource":"cloud-client-two","resourceMode":0}]是这样的。
但是我在nacos配置的确实是网关的流控
[
    {
        "resource": "cloud-client-two",
        "resourceMode": 0,
        "grade": 1,
        "count": 2,
        "intervalSec": 1,
        "controlBehavior": 0,
        "burst": 0
    }
]
并且规则确实生效了。
 http://ip:port/gateway/getRules  这个路径能看到我的控制台新加的规则
 http://ip:port/getRules?type=flow 这个路径能看到我网关的规则，但是是普通流控的规则，他只是取到了我配置的一些参数，像resourceMode,burst都取不到。

现在这个现象是我从nacos拉网关的流控配置，他当成普通流控来解析，规则生效了，但是控制台显示得匹配网关流控规则，导致我现在不显示。

**Comment by wang271724646** [comment]
> > 这是网关的规则
> > [{"clusterMode":false,"controlBehavior":0,"count":2.0,"grade":1,"limitApp":"default","maxQueueingTimeMs":500,"resource":"cloud-client-two","strategy":0,"warmUpPeriodSec":10}]
> 
> 看这个json格式是**普通流控规则**类型的，网关应用需要配置**网关流控规则**才行。
> 
> 参考：[https://github.com/alibaba/Sentinel/wiki/网关限流](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81)

是的，确实对不上，我自己在控制台加了一条限流规则
[{"burst":0,"controlBehavior":0,"count":555555.0,"grade":1,"intervalSec":1,"maxQueueingTimeoutMs":500,"resource":"cloud-client-two","resourceMode":0}]是这样的。
但是我在**nacos配置**的确实是网关的流控
**[
{
"resource": "cloud-client-two",
"resourceMode": 0,
"grade": 1,
"count": 2,
"intervalSec": 1,
"controlBehavior": 0,
"burst": 0
}
]**
并且规则确实生效了。
http://ip:port/gateway/getRules 这个路径能看到我的**控制台新加的规则**
http://ip:port/getRules?type=flow 这个路径能看到我**网关的规则**，但是是**普通流控的规则**，他只是取到了我配置的一些参数，像resourceMode,burst都取不到。

**现在这个现象是我从nacos拉网关的流控配置，他当成普通流控来解析，规则生效了，但是控制台显示得匹配网关流控规则，导致我现在不显示。**

**Comment by cdfive** [comment]
是用的`NacosDataSource`对吗？
```java
ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
                source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
                }));
FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
```
如果代码是这样，会加载到普通流控规则里。

需要用`GatewayRuleManager`来加载，才会加载到网关流控规则。
```java
ReadableDataSource<String, List<GatewayFlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
                source -> JSON.parseObject(source, new TypeReference<List<GatewayFlowRule>>() {
                }));
FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
```

**Comment by wang271724646** [comment]
> 是用的`NacosDataSource`对吗？
> 
> ```java
> ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
>                 }));
> FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```
> 
> 如果代码是这样，会加载到普通流控规则里。
> 
> 需要用`GatewayFlowRule`，并用`GatewayRuleManager`来加载，才会加载到网关流控规则。
> 
> ```java
> ReadableDataSource<String, List<GatewayFlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<GatewayFlowRule>>() {
>                 }));
> GatewayRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```
`cloud:
    sentinel:
      enabled: true #自动化配置是否生效
      transport:
        dashboard: localhost:8080 #Sentinel控制台地址
        heartbeat-interval-ms: 1000 #应用与Sentinel控制台的心跳间隔时间
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
            server-addr: http://10.5.94.32:8848`
我现在是这样在application.yaml配置的。
您说的这样配置我没配置过，参数是@Value拿application.yaml的值吗?
不太懂这样配置，请您说下 ，谢谢。

**Comment by wang271724646** [comment]
感谢，我觉得是这个问题了，但是我是在配置文件中配置的
```
cloud:
    sentinel:
      enabled: true #自动化配置是否生效
      transport:
        dashboard: localhost:8080 #Sentinel控制台地址
        heartbeat-interval-ms: 1000 #应用与Sentinel控制台的心跳间隔时间
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
            server-addr: http://10.5.94.32:8848
```
不知道您这个怎么配置，写一个配置类吗，参数怎么取，从配置文件中取吗。

**Comment by wang271724646** [comment]
> 是用的`NacosDataSource`对吗？
> 
> ```java
> ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
>                 }));
> FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```
> 
> 如果代码是这样，会加载到普通流控规则里。
> 
> 需要用`GatewayFlowRule`，并用`GatewayRuleManager`来加载，才会加载到网关流控规则。
> 
> ```java
> ReadableDataSource<String, List<GatewayFlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<GatewayFlowRule>>() {
>                 }));
> GatewayRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```
感谢，我觉得是这个问题了，但是我是在配置文件中配置的

cloud:
    sentinel:
      enabled: true #自动化配置是否生效
      transport:
        dashboard: localhost:8080 #Sentinel控制台地址
        heartbeat-interval-ms: 1000 #应用与Sentinel控制台的心跳间隔时间
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
            server-addr: http://10.5.94.32:8848
不知道您这个怎么配置，写一个配置类吗，参数怎么取，从配置文件中取吗。

**Comment by wang271724646** [comment]
> 是用的`NacosDataSource`对吗？
> 
> ```java
> ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
>                 }));
> FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```
> 
> 如果代码是这样，会加载到普通流控规则里。
> 
> 需要用`GatewayFlowRule`，并用`GatewayRuleManager`来加载，才会加载到网关流控规则。
> 
> ```java
> ReadableDataSource<String, List<GatewayFlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
>                 source -> JSON.parseObject(source, new TypeReference<List<GatewayFlowRule>>() {
>                 }));
> GatewayRuleManager.register2Property(flowRuleDataSource.getProperty());
> ```

感谢，我觉得是这个问题了，但是我是在配置文件中配置的

```
cloud:
    sentinel:
      enabled: true #自动化配置是否生效
      transport:
        dashboard: localhost:8080 #Sentinel控制台地址
        heartbeat-interval-ms: 1000 #应用与Sentinel控制台的心跳间隔时间
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
            server-addr: http://10.5.94.32:8848
```
不知道您这个怎么配置，写一个配置类吗，参数怎么取，从配置文件中取吗。

**Comment by cdfive** [comment]
好像是rule-type的配置有问题，flow是普通流控规则，试试：
`rule-type: gw-flow`

SCA里有sentinel网关的demo，可以参考哈：
https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-spring-cloud-gateway-example

**Comment by wang271724646** [comment]
改成`rule-type: gw-flow`后好了。感谢大佬！！！

**Comment by wang271724646** [comment]
> 好像是rule-type的配置有问题，flow是普通流控规则，试试：
> `rule-type: gw-flow`
> 
> SCA里有sentinel网关的demo，可以参考哈：
> https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-spring-cloud-gateway-example

改成
`rule-type: gw-flow`
后好了。感谢大佬！！！

**Comment by sczyh30** [comment]
👍

**Comment by CaiCaiXian** [comment]
http://ip:port/gateway/getRules为[]，但是已经配置了gw-flow了，依然无法读取到nacos中的配置，但是有限流的效果，求帮助
