### ISSUE TITLE
Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos.rule-type' to com.alibaba.cloud.sentinel.datasource.RuleType

### ISSUE THREAD

**Issue by LEEFFEE** [alibaba/Sentinel#1048]
## Issue Description

Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos.rule-type' to com.alibaba.cloud.sentinel.datasource.RuleType:

    Property: spring.cloud.sentinel.datasource.flow.nacos.ruletype
    Value: flow
    Origin: class path resource [bootstrap.properties]:26:54
    Reason: 2

Action:

### Describe what happened (or what feature you want)

```
  Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[in-gateway:192.168.182.1:8080] 2019-09-18 19:32:06.847 ERROR 19732 [main] org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos.rule-type' to com.alibaba.cloud.sentinel.datasource.RuleType:

    Property: spring.cloud.sentinel.datasource.flow.nacos.ruletype
    Value: flow
    Origin: class path resource [bootstrap.properties]:26:54
    Reason: 2

Action:

Update your application's configuration
```

### How to reproduce it (as minimally and precisely as possible)

1. sentinel使用nacos作持久化时，导致项目无法启动

### Tell us your environment
sentinel version is 1.6.3

**Comment by sczyh30** [comment]
Could you please provide your `application.properties` file and your Spring Cloud Alibaba version?

cc @fangjian0423

**Comment by LEEFFEE** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>

**Comment by LEEFFEE** [comment]
** <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>**

**Comment by fangjian0423** [comment]
@LEEFFEE Refer [this example](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-graduation-modification).

**Comment by LEEFFEE** [comment]
I did exactly the same thing and still had the same problem!!!!!!!!

**Comment by fangjian0423** [comment]
Maybe the problem of jdk version? Refer https://github.com/alibaba/spring-cloud-alibaba/issues/759.

**Comment by LEEFFEE** [comment]
my old java version is "1.8.0_25" ,  When I change to Java version 1.8.0_92, it starts normally
But our production environment user Java version 1.8.0_25. What should I do? Please help me !

**Comment by fangjian0423** [comment]
Try to do it with `InitFunc` SPI to replace `spring.cloud.sentinel.datasource.**` configuration items., refer https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%B3%A8%E5%86%8C%E6%95%B0%E6%8D%AE%E6%BA%90.

**Comment by sczyh30** [comment]
> Maybe the problem of jdk version? Related with [alibaba/spring-cloud-alibaba#759](https://github.com/alibaba/spring-cloud-alibaba/issues/759).

It seems weird. Can we add a note for this in the document?

**Comment by fangjian0423** [comment]
yes, i added it in the [DataSource section](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#%E5%8A%A8%E6%80%81%E6%95%B0%E6%8D%AE%E6%BA%90%E6%94%AF%E6%8C%81) in Spring Cloud Alibaba Sentinel wiki.

We will continue to focus on this issue.
