### ISSUE TITLE
Some suggestions about config properties file in Sentinel

### ISSUE THREAD

**Issue by pengminxuan** [alibaba/Sentinel#105]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
目前文档中说明配置文件只能存放在"${user_home}/logs/csp/${project.name}.properties",也就是日志文件的存放目录.操作上不方便,清理日志的时候也有可能误删配置文件.

### Describe what you expected to happen
我希望能够在工程目录中支持配置文件 ,springboot的application.properties文件中也能进行sentinel的配置.

**Comment by sczyh30** [comment]
Duplicate with #64 and #62. Thanks for your suggestion, we'll make enhancement in 0.2.0.

For Spring Boot / Spring Cloud, you can refer to [Sentinel Spring Cloud Starter](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/readme-zh.md) for some configurations.

**Comment by sczyh30** [comment]
This will be resolved in #804 (perhaps with 1.7.0 release).

If you're using Spring Boot/Spring Cloud, you could leverage Spring Cloud Alibaba to support configuring via `application.properties`: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Sentinel#more
