### ISSUE TITLE
Why BlockException should be defined as a check exception

### ISSUE THREAD

**Issue by huangxfchn** [alibaba/Sentinel#1064]
1, Why BlockException should be defined as a check exception?

2, When using `@SentinelResource` annotation, because the facet `SentinelResourceAspect` throws a check exception, but the actual method does not define a check exception, so the dynamic proxy will throw `java.lang.reflect.UndeclaredThrowableException`, but actually we hope captured the `com.alibaba.csp.sentinel.slots.block.BlockException`.
```
@GetMapping("/testFlow")
@SentinelResource("testFlow")
public Response testFlowRule() {
    // do something
    return Response.buildSuccessResponse();
}
```

3, it seems that there is no good solution, unless the `BlockException` is replaced by a non-check exception.

**Comment by kaizi2009** [comment]
Method of capturing BlockException :
https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj

**Comment by huangxfchn** [comment]
> Method of capturing BlockException when using annotations:
> https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj

I see. But, if a check exception is thrown inside a dynamic proxy, the caller will catch an unexpected exception, such as an `UndeclaredThrowableException`. Why not `RuntimeException`?

**Comment by sczyh30** [comment]
The original `BlockException` is defined as a checked exception because developers should handle the blocked event explicitly.
