### ISSUE TITLE
Caused by: java.lang.RuntimeException: Serialized class com.alibaba.csp.sentinel.slots.block.flow.FlowRule must implement java.io.Serializable

### ISSUE THREAD

**Issue by tcxurun** [alibaba/Sentinel#1065]
采用Dubbo集成Sentinel，资源是在Provider端，Consumer端调用，限流后进行压测报这个错误
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to send response: Response [id=1338, version=2.0.0, status=20, event=false, error=null, result=RpcResult [result=null, exception=java.lang.reflect.UndeclaredThrowableException]], cause: java.lang.RuntimeException: Serialized class com.alibaba.csp.sentinel.slots.block.flow.FlowRule must implement java.io.Serializable
 Java field: protected com.alibaba.csp.sentinel.slots.block.AbstractRule com.alibaba.csp.sentinel.slots.block.BlockException.rule
 Java field: private java.lang.Throwable java.lang.reflect.UndeclaredThrowableException.undeclaredThrowable
java.lang.RuntimeException: Serialized class com.alibaba.csp.sentinel.slots.block.flow.FlowRule must implement java.io.Serializable
 Java field: protected com.alibaba.csp.sentinel.slots.block.AbstractRule com.alibaba.csp.sentinel.slots.block.BlockException.rule
 Java field: private java.lang.Throwable java.lang.reflect.UndeclaredThrowableException.undeclaredThrowable

**Comment by jasonjoo2010** [comment]
The root cause is the provider didn't deal with the `BlockException` while `BlockException` is not designed to be transmitted in RPC environment.

If you want to customize the fallback in provider side you can use `DubboFallbackRegistry. setProviderFallback()`.

This issue is related to #1017

**Comment by wzg923** [comment]
Describe problem:
com.alibaba:dubbo:2.6.9
com.alibaba.csp:sentinel-dubbo-adapter:1.8.0
problem code

```
com.alibaba.csp.sentinel.adapter.dubbo.fallback.DefaultDubboFallback
public class DefaultDubboFallback implements DubboFallback {
    @Override
    public Result handle(Invoker<?> invoker, Invocation invocation, BlockException ex) {
        // Just wrap and throw the exception.
        throw new SentinelRpcException(ex);
    }
}
```
should change to :

```
public class DefaultDubboFallback implements DubboFallback {

    @Override
    public Result handle(Invoker<?> invoker, Invocation invocation, BlockException ex) {
        // Just wrap the exception.
        RpcResult result = new RpcResult();
        result.setException(ex.toRuntimeException());
        return result;
    }
}
```

**Comment by sczyh30** [comment]
@wzg923 Would you like to submit a PR to fix it?

**Comment by wzg923** [comment]
> @wzg923 Would you like to submit a PR to fix it?

It's my pleasure, but I don't have the permission to push or create a new git branch

**Comment by sczyh30** [comment]
> > @wzg923 Would you like to submit a PR to fix it?
> 
> It's my pleasure, but I don't have the permission to push or create a new git branch

You may refet to https://github.com/alibaba/Sentinel/wiki/开源贡献指南
