### ISSUE TITLE
The postProcessAfterInitialization of the SentinelBeanPostProcessor class needs to handle the case where the BeanName is empty, causing the quart task to hang.

### ISSUE THREAD

**Issue by superzjcy** [alibaba/Sentinel#1076]
![image](https://user-images.githubusercontent.com/6803617/66465408-62414100-eab3-11e9-8ecf-b03e2db307b6.png)

**Comment by sczyh30** [comment]
cc @fangjian0423

**Comment by fangjian0423** [comment]
@superzjcy could you pls create a pr to fix it? 

https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelBeanPostProcessor.java#L183

**Comment by sczyh30** [comment]
Any feedback?

**Comment by sczyh30** [comment]
Refer #1156

**Comment by superzjcy** [comment]
could u pls fix the bug, thanks a lot @fangjian0423.
