### ISSUE TITLE
Flow control rule update API is invalid

### ISSUE THREAD

**Issue by tangmin823** [alibaba/Sentinel#1080]
FlowRule rule = new FlowRule();
        rule.setResource("zzjj_sms");
        rule.setGrade(FLOW_GRADE_QPS);
        rule.setCount(20);
        qPSflowRules.add(rule);
FlowRuleManager.loadRules(qPSflowRules);  //这一行要拿掉，下面的loadRules才生效

FlowRule _rule = new FlowRule();
        _rule.setResource("zzjj_sms1");
        _rule.setGrade(FLOW_GRADE_QPS);
        _rule.setCount(20);
qPSflowRules.add(rule);
FlowRuleManager.loadRules(qPSflowRules); //上面的loadRules执行过，这行执行更新无效，看规则还是上面旧的？

测试下来，结果和api功能描述不一致
/**
     * Load {@link FlowRule}s, former rules will be replaced.
     *
     * @param rules new rules to load.
     */
    public static void loadRules(List<FlowRule> rules) {

如果要更新规则，到底怎么处理，是什么api接口？

**Comment by tangmin823** [comment]
No one reply? I'm here!

**Comment by sczyh30** [comment]
The second `qPSflowRules.add(rule)` is incorrect, which should be `_rule`. You may try `FlowRuleManager.loadRules(Arrays.asList(_rule))`.

**Comment by tangmin823** [comment]
![image](https://user-images.githubusercontent.com/13765160/66734732-cb9bc800-ee96-11e9-9fd8-b0c641fd031a.png)
Now I've debugged the program. There are two rule sets, but there's only one rule that loads successfully.

**Comment by tangmin823** [comment]
![image](https://user-images.githubusercontent.com/13765160/66736059-c93b6d00-ee9a-11e9-884d-9f22ce730e5e.png)
Now I've debugged the program. There are two rule sets, but there's only one rule that loads successfully.

**Comment by tangmin823** [comment]
@sczyh30 pls help!
