### ISSUE TITLE
The Sentinel console was unable to click the gateway integrated API management button

### ISSUE THREAD

**Issue by Zyuxing** [alibaba/Sentinel#1086]
![image](https://user-images.githubusercontent.com/34876708/66813123-c73ee000-ef66-11e9-991e-cd14ba3f7fcb.png)
![image](https://user-images.githubusercontent.com/34876708/66813129-cb6afd80-ef66-11e9-86ab-ff5929273ab9.png)
我使用gateway集成到Sentinel，访问量有了，但是Sentinel控制台页面上的请求链路和API管理无法点击，点击了没反应，没有对应的界面

**Comment by sczyh30** [comment]
强制刷新下页面；如果还存在问题，打开开发者模式看下前端有什么错误。

**Comment by Zyuxing** [comment]
> 强制刷新下页面；如果还存在问题，打开开发者模式看下前端有什么错误。

谢谢，我换了浏览器，已经好了，已知在搜狗浏览器上面无法点击请求链路和API管理按钮，谷歌浏览器可以。开发者模式无错误
