### ISSUE TITLE
可以做到当前线程超过 rt值，自动降级吗？

### ISSUE THREAD

**Issue by Paul0523** [alibaba/Sentinel#1092]
如题，目前看到的是熔断降级的策略，但是当前线程超过rt 值后仍会继续执行，导致调用超时。有没有办法当前线程超过 rt 阈值后降级？

**Comment by xiejin90314** [comment]
sentinel服务没法知道你每个接口的降级策略吧,感觉还是需要你自己实现一个自己的降级处理方式

**Comment by xiejin90314** [comment]
> 如题，目前看到的是熔断降级的策略，但是当前线程超过rt 值后仍会继续执行，导致调用超时。有没有办法当前线程超过 rt 阈值后降级？

https://github.com/alibaba/Sentinel/issues/1092#issue-508190747
111

**Comment by wavesZh** [comment]
当前线程？是[异步调用](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E6%96%B9%E5%BC%8F%E4%BA%94%E5%BC%82%E6%AD%A5%E8%B0%83%E7%94%A8%E6%94%AF%E6%8C%81) 吗？ @Paul0523

**Comment by jasonjoo2010** [comment]
Thread is a common component.
You can specify the timeout when invoking other api.
