### ISSUE TITLE
Is there any ways to hide some resources in dashboard?

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/Sentinel#1099]
For example, a method of Controller:

```java
@GetMapping("/aa")
@SentinelResource("aa")
public String aa(int b, int a) {
	return "Hello test";
}
```

Resource "aa" and Resource "/aa" will display in sentinel dashboard, is there any ways to hide "aa" or "/aa" resource?

**Comment by sczyh30** [comment]
Currently, it's not supported to control the resource display in the dashboard.

In fact, it's not recommended to add the `@SentinelResource` to the controller handler methods when the service has already introduced the Web adapter.

**Comment by fangjian0423** [comment]
cool
