### ISSUE TITLE
ClusetNodeBuilderSlot 是否为拼写错误

### ISSUE THREAD

**Issue by zhibo6** [alibaba/Sentinel#1101]
在文档：https://github.com/alibaba/Sentinel/wiki/Flow-Control中存在 ClusterNodeBuilderSlot、ClusetNodeBuilderSlot，请确认是否为拼写错误。

---

There are clusternodebuilderslot and clusetnodebuilderslot in the document: https://github.com/alibaba/sentinel/wiki/flow-control. Please confirm whether they are spelling errors.

**Comment by sczyh30** [comment]
I've fixed it. Thanks for reporting :)
