### ISSUE TITLE
文中的 entery name 是否存在拼写错误。应为 entry name

### ISSUE THREAD

**Issue by zhibo6** [alibaba/Sentinel#1102]
wiki地址：https://github.com/alibaba/Sentinel/wiki/How-it-works
文中的 entery name 是否存在拼写错误。应为 entry name

---

Each DefaultNode is identified by both the resource id and **entery name.** In other words, one resource id may have multiple default nodes distinguished by the **entery names** declared in ContextUtil.enter(name)

**Comment by sczyh30** [comment]
I've fixed it. Thanks for contributing!
