### ISSUE TITLE
Is there a bug in FlowRuleUtil.checkClusterField()?

### ISSUE THREAD

**Issue by wangybgit** [alibaba/Sentinel#1103]
## Issue Description

Type: *bug report* 

Look at the method:
> 
    private static boolean checkClusterField(/*@NonNull*/ FlowRule rule) {
        if (!rule.isClusterMode()) {
            return true;
        }
        ClusterFlowConfig clusterConfig = rule.getClusterConfig();
        if (clusterConfig == null) {
            return false;
        }
        if (!validClusterRuleId(clusterConfig.getFlowId())) {
            return false;
        }
        if (!isWindowConfigValid(clusterConfig.getSampleCount(), clusterConfig.getWindowIntervalMs())) {
            return false;
        }
        switch (rule.getStrategy()) {
            case ClusterRuleConstant.FLOW_CLUSTER_STRATEGY_NORMAL:
                return true;
            default:
                return false;
        }
    }

The method of switch (rule.getStrategy())  try to check the **rule.getStrategy()**,and the Case Statement uses ClusterRuleConstant.FLOW_CLUSTER_STRATEGY_NORMAL,is it correct?
I think the method of checkClusterField() is used to check **ClusterConfig**,so,the switch  statement should be used to check the **clusterConfig.getStrategy()**,right?

#sentinel version:1.7.0-SNAPSHOT

**Comment by sczyh30** [comment]
Yes, it's indeed a bug. Would you like to contribute a PR to fix it? You may refer to the instruction here: https://github.com/alibaba/Sentinel/wiki/%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97

**Comment by wangybgit** [comment]
> Yes, it's indeed a bug. Would you like to contribute a PR to fix it? You may refer to the instruction here: https://github.com/alibaba/Sentinel/wiki/%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97

ok，my pleasure.I will privide a PR to fix it right away.
