### ISSUE TITLE
When sentinel is integrated with feign, a call error occurs if the interface is application/json

### ISSUE THREAD

**Issue by qiaojiang2** [alibaba/Sentinel#1107]
I'm using feign to call a dependency interface defined as

 "@requestmapping ("/decrypt")
Public ResponseResult decryptNotifyMsg(@requestbody OrderMsgReqDto OrderMsgReqDto);"

An error occurs when the call is made. If I change the configuration to "feign.sentinel.enabled=false", that's fine.

if I use this definition, I'll be fine
@RequestMapping(value = "/internal/pay/checkNotify", method = RequestMethod.POST) boolean checkNotify(@RequestParam(value = "paymentId") String paymentId, @RequestParam(value = "tradeNo") String tradeNo, @RequestParam(value = "status") int status, @RequestParam(value = "platform") String platform, @RequestParam(value = "platformtag") String platformtag, @RequestParam(value = "tradeTime") String tradeTime, @RequestParam(value = "notifyOrignMsg") String notifyOrignMsg, @RequestParam(value = "tradeStatus") String tradeStatus);

**Comment by sczyh30** [comment]
Please provide more information (e.g. the error message, the dependency you're using).

**Comment by kaizi2009** [comment]
@sczyh30 In spring-cloud-alibaba-sentinel , see  https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeignAutoConfiguration.java

**Comment by sczyh30** [comment]
Any feedback?
