### ISSUE TITLE
getServletPath() always returns empty when matching URL in Zuul API gateway flow control

### ISSUE THREAD

**Issue by fusc2018** [alibaba/Sentinel#1109]
Issue Description: context.getRequest().getServletPath() always empty

type: bug

Class :PrefixRoutePathMatcher.class

Method: test

Content:

```java
    @Override
    public boolean test(RequestContext context) {
        String path = context.getRequest().getServletPath();
        if (canMatch) {
            return pathMatcher.match(pattern, path);
        }
        return false;
    }
```

### How to reproduce it (as minimally and precisely as possible)

```java
  @Override
    public boolean test(RequestContext context) {
        String path = context.getRequest().getRequestURI();
        if (canMatch) {
            return pathMatcher.match(pattern, path);
        }
        return false;
    }
```

**Comment by sczyh30** [comment]
Could you please give more information (e.g. the path you're visiting, and maybe your Zuul Servlet config)?

**Comment by fusc2018** [comment]
First of all, the zuul version I used is 2.1.1.
ZuulServletConfig configuration is as follows

zuul:
  servlet-path: /
  ignore-security-headers: false

The sentinel introduced by pom is as follows
               <dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-zuul-adapter</artifactId>
			<version>1.6.0</version>
		</dependency>

###################################
SentinelConfig  is as follows

@Configuration
public class SentinelZuulConfig {

    @Bean
    public SentinelZuulPreFilter sentinelZuulPreFilter(){
        return new SentinelZuulPreFilter(0);
    }

    @Bean
    public SentinelZuulPostFilter sentinelZuulPostFilter(){
        return new SentinelZuulPostFilter(4);
    }

    @Bean
    public SentinelZuulErrorFilter sentinelZuulErrorFilter(){
        return new SentinelZuulErrorFilter();
    }
}

##########################################

GatewayApiRuleConfig 

@Configuration
public class GatewayRulerConfig {
    private static final int URL_MATCH_STRATEGY_EXACT = 0;
    private static final int URL_MATCH_STRATEGY_PREFIX = 1;
    private static final int URL_MATCH_STRATEGY_REGEX = 2;

    @PostConstruct
    public void init(){
        initCustomizedApis();
        initGatewayRules();

    }


    private void initCustomizedApis() {
        Set<ApiDefinition> definitions = new HashSet<>();
        ApiDefinition api1 = new ApiDefinition("baobao_api")
                .setPredicateItems(new HashSet<ApiPredicateItem>() {{
                    add(new ApiPathPredicateItem().setPattern("/uaa/admin/usermanage/**")
                            .setMatchStrategy(URL_MATCH_STRATEGY_PREFIX));
                }});
        definitions.add(api1);
        GatewayApiDefinitionManager.loadApiDefinitions(definitions);
    }

    private void initGatewayRules() {
        Set<GatewayFlowRule> rules = new HashSet<>();
        rules.add(new GatewayFlowRule("baobao_api")
                .setResourceMode(SentinelGatewayConstants.RESOURCE_MODE_CUSTOM_API_NAME)
                .setCount(1)
                .setIntervalSec(1)
        );

        GatewayRuleManager.loadRules(rules);
    }
    
}
##################################################


The address I visited is http://poserp-dev.800best.com/uaa/admin/usermanage/searchUser

But can't trigger current limit

#############################################
Tracking source code found that  context.getRequest().getServletPath()  is always empty, so it can't match URI

package com.alibaba.csp.sentinel.adapter.gateway.zuul.api.route;

import com.alibaba.csp.sentinel.util.AssertUtil;
import com.alibaba.csp.sentinel.util.function.Predicate;
import com.netflix.zuul.context.RequestContext;
import org.springframework.util.AntPathMatcher;
import org.springframework.util.PathMatcher;

public class PrefixRoutePathMatcher implements Predicate<RequestContext> {
    private final String pattern;
    private final PathMatcher pathMatcher;
    private final boolean canMatch;

    public PrefixRoutePathMatcher(String pattern) {
        AssertUtil.assertNotBlank(pattern, "pattern cannot be blank");
        this.pattern = pattern;
        this.pathMatcher = new AntPathMatcher();
        this.canMatch = this.pathMatcher.isPattern(pattern);
    }

    public boolean test(RequestContext context) {
 
  //path is always empty
        String path = context.getRequest().getServletPath();

        return this.canMatch ? this.pathMatcher.match(this.pattern, path) : false;
    }

    public String getPattern() {
        return this.pattern;
    }
}

**Comment by fusc2018** [comment]
This seems to be related to the ServletPath I configured, but I just want to match my defined pattern based on the access address prefix.

**Comment by sczyh30** [comment]
Usually using the default `servlet-path` is enough (for matching the exact URL). However, we might need to handle the circumstances when `getServletPath()` returns empty (maybe we need to use `getPathInfo()` for fallback (or better solutions).

**Comment by sczyh30** [comment]
For reference:

- https://stackoverflow.com/questions/4140448/difference-between-and-in-servlet-mapping-url-pattern
- https://stackoverflow.com/questions/4278083/how-to-get-request-uri-without-context-path
- https://bluxte.net/musings/2006/03/29/servletpath-and-pathinfo-servlet-api-weirdness/
- https://agiletribe.wordpress.com/2016/02/23/httpservletrequest-path-decoding/

Moreover, we may need to define whether the "context path prefix" should be included in our path (to check). If so, maybe we can just leverage `request.getRequestURI()`.

**Comment by fusc2018** [comment]
I just want to use sentinel on the gateway, so there is no context path

**Comment by sczyh30** [comment]
> I just want to use sentinel on the gateway, so there is no context path

For your scenario that's enough, but we need to handle more general scenarios.

Besides, you might not need to set `servlet-path: /`, as Spring will register a general `ZuulController`, which will delegate all your requests (from `DispatcherServlet`) to `ZuulServlet`.

**Comment by fusc2018** [comment]
Thank you, it really is like that

**Comment by wavesZh** [comment]
@fusc2018 sentinel-zuul-adapter only support Zuul 1.x but you use Zuul 2.x.

**Comment by sczyh30** [comment]
> @fusc2018 sentinel-zuul-adapter only support Zuul 1.x but you use Zuul 2.x.

I think he was meaning Spring Cloud Zuul 2.x.

**Comment by hangxyGit** [comment]
@sczyh30  I want to finish this issue

**Comment by sczyh30** [comment]
> @sczyh30 I want to finish this issue

Looking forward to your contribution!

**Comment by JiangZian** [comment]
@sczyh30 I want to finish this issue

**Comment by jasonjoo2010** [comment]
Close via #1605
