### ISSUE TITLE
Add Sentinel MyBatis adapter module

### ISSUE THREAD

**Issue by kaizi2009** [alibaba/Sentinel#1113]
# Why we need it?
Database needs sentinel, because:

1. In most cases, the bottleneck of the system is the database.
2. Although there are web or rpc sentinel, but some unimportant requests occupy database resources, we should give priority to the access of important data.
# Database limiting flow param
1. We can determine the current limiting parameters of the database by pressure measurement.
2. **If possible in the future, can be artificial intelligence, adjust the current limiting parameters through the load of the database.**

**Comment by kaizi2009** [comment]
> The issue description was not updated? :)
> 
> Maybe we could leverage the plugin mechanism (`org.apache.ibatis.plugin.Interceptor`) of MyBatis. Contributions are welcomed!
I've updated the issue.
Yes, can use `org.apache.ibatis.plugin.Interceptor`, I'm experimenting.

**Comment by kaizi2009** [comment]
I have a dream, AI for sentinel.

**Comment by sczyh30** [comment]
> I have a dream, AI for sentinel.

We're exploring more "intelligent" adaptive flow control like #1003 and #1007. Discussions are welcomed!
