### ISSUE TITLE
dubbo-sentinel-support  can't work well when consumer and producer in async model

### ISSUE THREAD

**Issue by CodingSinger** [alibaba/Sentinel#1114]
processing may not finish when an asynchronous call returns, trace the result can't finished is meaningless.

**Comment by CodingSinger** [comment]
英文不太好，所以就用中文了，请谅解~
目前dubbo-sentinel-support模块 https://github.com/apache/dubbo-sentinel-support 不支持dubbo的异步调用，要实现对异步调用的记录需要存储每一次调用的AsyncEntry对象，以便于在真正异步处理结束的回调中进行拿到对应的AsyncEntry处理，目前看了下，并没有好的办法能存储每一次AsyncEntry，初步想法是在插件侧自己维护一个`Map<Invocation,Entry>`来进行存储。如果大家有更好的想法，欢迎下面给出建议。
感谢!

**Comment by jasonjoo2010** [comment]
> 英文不太好，所以就用中文了，请谅解~
> 目前dubbo-sentinel-support模块 https://github.com/apache/dubbo-sentinel-support 不支持dubbo的异步调用，要实现对异步调用的记录需要存储每一次调用的AsyncEntry对象，以便于在真正异步处理结束的回调中进行拿到对应的AsyncEntry处理，目前看了下，并没有好的办法能存储每一次AsyncEntry，初步想法是在插件侧自己维护一个`Map<Invocation,Entry>`来进行存储。如果大家有更好的想法，欢迎下面给出建议。
> 感谢!

You can try `RpcContext.getContext().set(SENTINEL_CTX, ctx)`.
Pay attention that you should call RpcContext.getContext() BEFORE the procedure entering asynchronous step or you may get the wrong context.

**Comment by jasonjoo2010** [comment]
And welcome contribute your first PR to Sentinel.

Affected folder including `sentinel-dubbo-adapter` and `sentinel-apache-dubbo-adapter`

**Comment by CodingSinger** [comment]
> > 英文不太好，所以就用中文了，请谅解~
> > 目前dubbo-sentinel-support模块 https://github.com/apache/dubbo-sentinel-support 不支持dubbo的异步调用，要实现对异步调用的记录需要存储每一次调用的AsyncEntry对象，以便于在真正异步处理结束的回调中进行拿到对应的AsyncEntry处理，目前看了下，并没有好的办法能存储每一次AsyncEntry，初步想法是在插件侧自己维护一个`Map<Invocation,Entry>`来进行存储。如果大家有更好的想法，欢迎下面给出建议。
> > 感谢!
> 
> You can try `RpcContext.getContext().set(SENTINEL_CTX, ctx)`.
> Pay attention that you should call RpcContext.getContext() BEFORE the procedure entering asynchronous step or you may get the wrong context.

感谢你的建议，但是按照我对RpcContext的理解，这是根据ThreadLocal实现的，所以RpcContext是和Thread绑定的，但是响应结束的回调和请求开始的回调可能并不是在一个线程，通过RpcContext的get到的可能并不是之前该请求set进去的。

**Comment by jasonjoo2010** [comment]
> > > 英文不太好，所以就用中文了，请谅解~
> > > 目前dubbo-sentinel-support模块 https://github.com/apache/dubbo-sentinel-support 不支持dubbo的异步调用，要实现对异步调用的记录需要存储每一次调用的AsyncEntry对象，以便于在真正异步处理结束的回调中进行拿到对应的AsyncEntry处理，目前看了下，并没有好的办法能存储每一次AsyncEntry，初步想法是在插件侧自己维护一个`Map<Invocation,Entry>`来进行存储。如果大家有更好的想法，欢迎下面给出建议。
> > > 感谢!
> > 
> > 
> > You can try `RpcContext.getContext().set(SENTINEL_CTX, ctx)`.
> > Pay attention that you should call RpcContext.getContext() BEFORE the procedure entering asynchronous step or you may get the wrong context.
> 
> 感谢你的建议，但是按照我对RpcContext的理解，这是根据ThreadLocal实现的，所以RpcContext是和Thread绑定的，但是响应结束的回调和请求开始的回调可能并不是在一个线程，通过RpcContext的get到的可能并不是之前该请求set进去的。

Nope. For synchronized invocation context is just in threadlocal collection. But for asynchronous request the context will be fetch into `AsyncContext` and will be restored when it was finished and then invokes the related callback procedures.

**Comment by CodingSinger** [comment]
我知道你的意思了，当我们用RpcContext来存储sentinel相关的对象的时候，我们还是需要一个地方来存储RpcContext呀

**Comment by CodingSinger** [comment]
已经提交了mr https://github.com/apache/dubbo-sentinel-support/pull/2

**Comment by sczyh30** [comment]
Since https://github.com/apache/dubbo-sentinel-support does not have CI configured, could you please also submit a PR to this repo? Related modules: `sentinel-adapter/sentinel-apache-dubbo-adapter` and `sentinel-adapter/sentinel-dubbo-adapter`.

**Comment by CodingSinger** [comment]
> Since https://github.com/apache/dubbo-sentinel-support does not have CI configured, could you please also submit a PR to this repo? Related modules: `sentinel-adapter/sentinel-apache-dubbo-adapter` and `sentinel-adapter/sentinel-dubbo-adapter`.
ok

**Comment by CodingSinger** [comment]
@sczyh30 已经提交mr了，在dubbo2.7以下的版本对于异步的支持并不友好，所以`sentinel-adapter/sentinel-dubbo-adapter`没有修改。

**Comment by sczyh30** [comment]
👍
