### ISSUE TITLE
Push rules from dashboard to Redis, Spring Boot 2.x + Sentinel

### ISSUE THREAD

**Issue by GitHubcaowei** [alibaba/Sentinel#1116]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.9.RELEASE</version>
    </parent>
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.2.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-redis</artifactId>
            <version>1.6.3</version>
        </dependency>
       <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>5.2.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.3.0.RELEASE</version>
        </dependency>
pom.xml相关依赖如上，使用springboot2.1.9集成sentinel，可以注册到控制台，但是使用redis无法同步规则到控制台，使用springboot1.5.6则可以，请问是什么原因？jar冲突吗？谢谢

#

**Comment by sczyh30** [comment]
Is there any error message?

**Comment by GitHubcaowei** [comment]
> Is there any error message?
idea的后台没错误信息
![image](https://user-images.githubusercontent.com/35019319/67548690-02929900-f735-11e9-80cb-ba624fde6855.png)
springboot启动的时候调用上图中loadrules，没报错，redis中也有数据，但是sentinel-dashboard里的流量规则看不到数据

**Comment by sczyh30** [comment]
Please check your `~/logs/csp/sentinel-record.log.xxx` log of your application side and see whether there are error messages.

**Comment by GitHubcaowei** [comment]
![image](https://user-images.githubusercontent.com/35019319/67558185-18aa5480-f749-11e9-95cb-a56fe99fb018.png)
![image](https://user-images.githubusercontent.com/35019319/67558227-2e1f7e80-f749-11e9-8616-fc71916670f0.png)
你好，通过日志看到resource=null，但是代码里面赋值了，这可能是什么情况导致的？

**Comment by sczyh30** [comment]
> ![image](https://user-images.githubusercontent.com/35019319/67558185-18aa5480-f749-11e9-95cb-a56fe99fb018.png)
> ![image](https://user-images.githubusercontent.com/35019319/67558227-2e1f7e80-f749-11e9-8616-fc71916670f0.png)
> 你好，通过日志看到resource=null，但是代码里面赋值了，这可能是什么情况导致的？

fastjson 版本太低，检查下版本，尽可能升到新版本。

**Comment by sczyh30** [comment]
Has this been resolved?

**Comment by GitHubcaowei** [comment]
> Has this been resolved?

我上周五解决了，发现确实是fastjson版本太低了，谢谢。另外问一下，这种推模式，支持从控制台修改规则，然后同步到redis中吗？因为我从控制台修改规则保存的时候，我看cmd里面报invalid type
![image](https://user-images.githubusercontent.com/35019319/67649249-3a871f80-f973-11e9-9400-f3a4a9c8b8ff.png)

**Comment by power315cn** [comment]
> > Has this been resolved?
> 
> 我上周五解决了，发现确实是fastjson版本太低了，谢谢。另外问一下，这种推模式，支持从控制台修改规则，然后同步到redis中吗？因为我从控制台修改规则保存的时候，我看cmd里面报invalid type
> ![image](https://user-images.githubusercontent.com/35019319/67649249-3a871f80-f973-11e9-9400-f3a4a9c8b8ff.png)

请问修改控制台规则，同步到redis的功能，你实现了吗？能否请教。

**Comment by sczyh30** [comment]
You may refer to the document [here](https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#push模式) to refactor the dashboard and support pushing rules to Redis.

But the "invalid type" error seems weird. Any more error messages, or parameters for `setRule` command?

**Comment by sczyh30** [comment]
Also refer to: https://github.com/alibaba/spring-cloud-alibaba/issues/1152
