### ISSUE TITLE
Data loss when desynchronizing json data of Set<ApiDefinition>

### ISSUE THREAD

**Issue by fusc2018** [alibaba/Sentinel#1119]
this is myparser :   Converter<String, Set<ApiDefinition>> apiparser = source -> JSON.parseObject(source,new TypeReference<Set\<ApiDefinition\>>() {});

and json string is ：
    [{"apiName":"usersearch_api","predicateItems":[{"pattern":"/uaa/admin/usermanage/searchUser/**","matchStrategy":1}]}]

But when I deserialize this json, the value is like this：
[https://i.ibb.co/30qJTpc/TIM-20191028104058.png]()

**Comment by fusc2018** [comment]
ApiPredicateItem is a interface,so it can't be deserialize

public class ApiDefinition {
    private String apiName;
    private Set<ApiPredicateItem> predicateItems;

    public ApiDefinition() {
    }

**Comment by sczyh30** [comment]
You may refer the code to handle it: https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayApiDefinitionGroupCommandHandler.java#L80

**Comment by fusc2018** [comment]
Yes, I have solved it.

**Comment by dcy421** [comment]
你好 请问你这个是怎么解决的

**Comment by ameizi** [comment]
好坑啊
