### ISSUE TITLE
网关限流是否支持Nacos配置数据源？

### ISSUE THREAD

**Issue by jorrellz** [alibaba/Sentinel#1120]
比如gateway 版本是
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-gateway</artifactId>
         <version>2.0.0.RELEASE</version>
</dependency>
```

试了一下没有生效

**Comment by fusc2018** [comment]
试试加上这个参数csp.sentinel.app.type=1

**Comment by jorrellz** [comment]
@fusc2018  这个参数有加的

**Comment by sczyh30** [comment]
Please provide more information (e.g. your dependencies related to Sentinel or Spring Cloud Alibaba, your configuration, and the `~/logs/csp/sentinel-record.log` content).

**Comment by xingyy1990** [comment]
目前好像不支持

**Comment by hanFirework** [comment]
1.6.3版本开始是已经支持了的，我目前就在做spring-cloud-gateway添加sentinel。wiki这里有介绍
[https://github.com/alibaba/Sentinel/wiki/网关限流](https://github.com/alibaba/Sentinel/wiki/网关限流)
另外有官方demo：[sentinel-demo-spring-cloud-gateway](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-spring-cloud-gateway)

**Comment by hanFirework** [comment]
至于你说的网关限流配置nacos数据源，如果你在普通项目sentinel限流时候配置过nacos，网关也是一样的。
1.6.3提供了DynamicRuleProvider接口和DynamicRuleProvider接口，用来做配置nacos、Apollo、zk的。
区别在于改造sentinel-dashboard的时候，普通项目限流要改造为使用com.alibaba.csp.sentinel.dashboard.controller.v2.FlowControllerV2(需要修改js里的部分内容)并且修改两个属性DynamicRuleProvider和DynamicRuleProvider的实现为nacos的(test/com.alibaba.csp.sentinel.dashboard.rule.nacos包下有已经实现好的)，而网关使用的是com.alibaba.csp.sentinel.dashboard.controller.gateway.GatewayApiController和com.alibaba.csp.sentinel.dashboard.controller.gateway.GatewayFlowRuleController需要自己改造controller为类似FlowControllerV2的形式 使用上述两个接口的实现。

**Comment by panlin586** [comment]
> 至于你说的网关限流配置nacos数据源，如果你在普通项目sentinel限流时候配置过nacos，网关也是一样的。
> 1.6.3提供了DynamicRuleProvider接口和DynamicRuleProvider接口，用来做配置nacos、Apollo、zk的。
> 区别在于改造sentinel-dashboard的时候，普通项目限流要改造为使用com.alibaba.csp.sentinel.dashboard.controller.v2.FlowControllerV2(需要修改js里的部分内容)并且修改两个属性DynamicRuleProvider和DynamicRuleProvider的实现为nacos的(test/com.alibaba.csp.sentinel.dashboard.rule.nacos包下有已经实现好的)，而网关使用的是com.alibaba.csp.sentinel.dashboard.controller.gateway.GatewayApiController和com.alibaba.csp.sentinel.dashboard.controller.gateway.GatewayFlowRuleController需要自己改造controller为类似FlowControllerV2的形式 使用上述两个接口的实现。
你好 请问你改造好了？ 我能参考一下吗？
