### ISSUE TITLE
Customize the statistic window length of exception-ratio circuit breaking

### ISSUE THREAD

**Issue by JinxLbj** [alibaba/Sentinel#1121]
能不能将每秒错误率降级改为每分钟错误率降级呢，因为有的时候网络抖动导致一秒内错误率过高导致降级策略触发

**Comment by sczyh30** [comment]
Hi, this is not supported till now. We're working on more flexible statistic window for different DegradeRules. Discussions are welcomed!

**Comment by JinxLbj** [comment]
> Hi, this is not supported till now. We're working on more flexible statistic window for different DegradeRules. Discussions are welcomed!

Thanks for your reply，I'm looking forward to the future.

**Comment by sczyh30** [comment]
Refer: #263 and #308
