### ISSUE TITLE
The ids of Class InMemApiDefinitionStore after the sentinel-dashboard restart are not updated to the maximum value in the persistence

### ISSUE THREAD

**Issue by fusc2018** [alibaba/Sentinel#1122]
this is my apis in apollo

{
        "apiName": "usersearch",
        "app": "gateway",
        "gmtCreate": 1572318746623,
        "gmtModified": 1572318746623,
        "id": 8,
        "ip": "10.67.146.103",
        "port": 8719,
        "predicateItems": [
            {
                "matchStrategy": 2,
                "pattern": "/uaa/admin/usermanage/searchUser/**"
            }
        ]
    },
    {
        "apiName": "erp",
        "app": "gateway",
        "gmtCreate": 1572318799749,
        "gmtModified": 1572318799749,
        "id": 9,
        "ip": "10.67.146.103",
        "port": 8719,
        "predicateItems": [
            {
                "matchStrategy": 0,
                "pattern": "/uaa/admin/orgRole/pageQueryRoleList"
            }
        ]
    }

I am trying to add an api grouping

But id is 1 is not 10

[
    {
        "apiName": "efwefwef",
        "app": "gateway",
        "gmtCreate": 1572318899501,
        "gmtModified": 1572318899501,
        "id": 1,
        "ip": "10.67.146.103",
        "port": 8719,
        "predicateItems": [
            {
                "matchStrategy": 0,
                "pattern": "/ewfwefwef"
            }
        ]
    },
    {
        "apiName": "usersearch",
        "app": "gateway",
        "gmtCreate": 1572318746623,
        "gmtModified": 1572318746623,
        "id": 8,
        "ip": "10.67.146.103",
        "port": 8719,
        "predicateItems": [
            {
                "matchStrategy": 2,
                "pattern": "/uaa/admin/usermanage/searchUser/**"
            }
        ]
    },
    {
        "apiName": "erp",
        "app": "gateway",
        "gmtCreate": 1572318799749,
        "gmtModified": 1572318799749,
        "id": 9,
        "ip": "10.67.146.103",
        "port": 8719,
        "predicateItems": [
            {
                "matchStrategy": 0,
                "pattern": "/uaa/admin/orgRole/pageQueryRoleList"
            }
        ]
    }
]

**Comment by sczyh30** [comment]
Related to #777
