### ISSUE TITLE
Invalid rule-type when using Zuul with Spring Cloud Alibaba Sentinel and Apollo data-source

### ISSUE THREAD

**Issue by kingskylar** [alibaba/Sentinel#1123]
版本号：sentinel-zuul-adapter   1.6.3
                 spring-cloud-alibaba-sentinel-gateway 2.1.0.RELEASE
                 spring-cloud-starter-alibaba-sentinel    0.2.2.RELEASE
                 jdk   1.8.0_231

zuul网关拉取Apollo配置规则时报错：
Failed to bind properties under 'spring.cloud.sentinel.datasource.ds6.apollo.rule-type' to org.springframework.cloud.alibaba.sentinel.datasource.RuleType:

    Property: spring.cloud.sentinel.datasource.ds6.apollo.rule-type
    Value: gw-flow
    Origin: "spring.cloud.sentinel.datasource.ds6.apollo.rule-type" from property source "ApolloBootstrapPropertySources"
    Reason: failed to convert java.lang.String to @javax.validation.constraints.NotNull org.springframework.cloud.alibaba.sentinel.datasource.RuleType

Action:

Update your application's configuration. The following values are valid:

    AUTHORITY
    DEGRADE
    FLOW
    PARAM_FLOW
    SYSTEM

Apollo配置参数：
spring.cloud.sentinel.datasource.ds6.apollo.namespace-name = DepartmentName.sentinel
spring.cloud.sentinel.datasource.ds6.apollo.rule-type = gw-flow
spring.cloud.sentinel.datasource.ds6.apollo.flow-rules-key = ${spring.application.name}-${spring.cloud.sentinel.datasource.ds6.apollo.rule-type}

另外sentinel-dashboard里面识别不出应用为网关，在idea里面直接加了启动参数-Dcsp.sentinel.app.type=1
配置项也加了:csp.sentinel.app.type=1

**Comment by fusc2018** [comment]
刚完成了sentinel zuul apollo的适配,可以加我QQ：1039735980

**Comment by sczyh30** [comment]
You have to update your `spring-cloud-starter-alibaba-sentinel` dependency to the latest version. See the [version description for Spring Cloud Alibaba](https://github.com/alibaba/spring-cloud-alibaba/wiki/版本说明).

And please make sure you're using the latest dashboard (1.6.3).
