### ISSUE TITLE
WARNING [TokenClientHandler] Client ping failed

### ISSUE THREAD

**Issue by zjq123456** [alibaba/Sentinel#1125]
Why frequent connection fails ?

![image](https://user-images.githubusercontent.com/14069938/67776519-600f4880-fa9b-11e9-8655-0e0353ae86d8.png)
![image](https://user-images.githubusercontent.com/14069938/67776589-7a492680-fa9b-11e9-8e31-8f71e66732f3.png)

**Comment by sczyh30** [comment]
Please check the following logs and see whether there are error messages:

- `~/logs/csp/sentinel-record.log` in both side
- `~/logs/csp/sentinel-cluster-client.log` in token client side
