### ISSUE TITLE
spring-cloud-alibaba2.1,sentinel1.6.3版本流控链路不起作用

### ISSUE THREAD

**Issue by hzqiyongpan** [alibaba/Sentinel#1126]
![图片](https://user-images.githubusercontent.com/4659635/67825988-0b54e780-fb06-11e9-85db-2d3f9f67ccd5.png)
![图片](https://user-images.githubusercontent.com/4659635/67826033-27f11f80-fb06-11e9-998a-4f0ca95d44b9.png)

**Comment by sczyh30** [comment]
Hi, you may refer to #1024.

**Comment by hzqiyongpan** [comment]
已解决
