### ISSUE TITLE
Which SlotChainBuilder is used is unpredictable, depends on order of resource loading

### ISSUE THREAD

**Issue by xiazuojie** [alibaba/Sentinel#1128]
## Issue Description
Which _com.alibaba.csp.sentinel.slotchain.SlotChainBuilder_ to use can be specified by creating a resource file _resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder_.
However, _sentinel-core_ already ships its own file that uses _com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder_.
If an user provides his own resource file, we have multiple files (_resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder_) in classpath. Which one actually gets used depends on which resource file is loaded first, which is unpredictable and may cause unexpected issues.

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
If a user provides a _resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder_, it may not get used because sentinel-core already ships one.

### Describe what you expected to happen
Which _SlotChainBuilder_ is used can be specified in a predictable way, maybe a system property.
If there are multiple specifications, raise an error with detailed message on how to specify which one to use.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

From Alibaba with love

**Comment by sczyh30** [comment]
Actually it seems not a good design to make `SlotChainBuilder` as the SPI and load the first-encountered implementation. We may need a more flexible mechanism like #411 (though compatibility should be considered).

**Comment by sczyh30** [comment]
Resolved in Sentinel 1.7.2 via #411
