### ISSUE TITLE
使用Nginx代理sentinel-dashboard时无法正常访问

### ISSUE THREAD

**Issue by oldmanl** [alibaba/Sentinel#1131]
nginx配置如下：
```
location /sentinel/ {
      proxy_pass http://127.0.0.1:8080/;
  }
```
浏览器访问: http://localhost/sentinel/
![image](https://user-images.githubusercontent.com/19261985/67925424-49c5d180-fbee-11e9-9dc1-12cd871bc003.png)
登录时也无法正确访问到接口地址：
![image](https://user-images.githubusercontent.com/19261985/67925472-72e66200-fbee-11e9-9a9a-8ea7a0089b99.png)
看起来像是没有带上前缀/sentinel，请问是我的nginx配置问题吗，麻烦解答下

sentinel-dashboard版本1.6.3

**Comment by sczyh30** [comment]
This might be related to your Nginx configuration. You may refer to Nginx document and check your configuration.
