### ISSUE TITLE
Duplicate instances in the machine list when deploy multiple services to Tomcat container

### ISSUE THREAD

**Issue by hitfire** [alibaba/Sentinel#1132]
## Issue Description

我在同一个tomcat中部署了四个服务，但是Sentinel控制台-机器列表中显示了11个实例，局域网ip相同，端口不同。请问这是什么原因导致的？
![image](https://user-images.githubusercontent.com/22113766/67996656-459bc180-fc8b-11e9-847c-986fd13b6978.png)

### Tell us your environment
tomcat: v9.0
Sentinel: v1.6.2
Spring Boot: v2
tomcat启动参数配置： -Dproject.name=webapi -Dcsp.sentinel.dashboard.server=10.1.32.1:5900 -Dcsp.sentinel.log.use.pid=true

**Comment by hitfire** [comment]
问题原因找到，但还没找到好的解决办法：
原因：tomcat的webapps目录下，每次更新服务，会先删除xxx.war，此时服务停了但在Sentinel控制台的实例中并不会消失，再上传新的同名war又会出现一个新的实例。这样就会多很多无意义的节点，重启tomcat才能正常。

**Comment by jasonjoo2010** [comment]
生产环境中关闭hot deploy，每次同步完文件后重启实例，同步文件不建议同步war包（无法做到增量同步），建议在部署服务器上直接解包并增量同步。

`Hot Deploy` should be turned off in production and  it's better to unpack the `war` file before deployment thus can enable incremental distribution.
