### ISSUE TITLE
FlowPropertyListener中规则的更新是否应该用整体替换而不是先clear再putAll

### ISSUE THREAD

**Issue by gaohanghbut** [alibaba/Sentinel#1141]
## Issue Description

如下图，在FlowPropertyListener类的configUpdate方法中，先执行了flowRules.clear()清除了已有的数据，然后再调用putAll方法，如果在这个中间有请求过来做规则的判断，则原来的规则就没了，这是不是个问题？应该创建一个新的ConcurrentHashMap替换掉原来的
![image](https://user-images.githubusercontent.com/6317379/68290905-ba279380-00c3-11ea-90fc-deebb0968f91.png)

版本：1.6.3

**Comment by sczyh30** [comment]
This has been improved via https://github.com/alibaba/Sentinel/commit/36b162cc70b7c77525b6d3effbdc5efbdcdc2f7b
