### ISSUE TITLE
sentinel console fail to connect

### ISSUE THREAD

**Issue by keweiLv** [alibaba/Sentinel#1143]
Why does the jar package of sentinel console always fail to connect, which makes the console unavailable   like this `java.net.ConnectException: Connection refused: no further information`。
The version is the latest one on the official website. It has been compiled

**Comment by sczyh30** [comment]
Did the exception occur frequently? Please check whether the network between the dashboard and your services is accessible.

**Comment by keweiLv** [comment]
> Did the exception occur frequently? Please check whether the network between the dashboard and your services is accessible.

I don't know why, it is very unstable, it will be normal after restarting the computer.
