### ISSUE TITLE
SystemRule CPU usage and load in Docker

### ISSUE THREAD

**Issue by lkxiaolou** [alibaba/Sentinel#1146]
docker中获取的cpu load 和 cpu useage都是宿主机的数据，如果按这个来降级是有问题的，这个问题在sentinel中有没有好的解决方案？

**Comment by jasonjoo2010** [comment]
You can try to upgrade JVM to version 10.

容器资源的支持是从JVM 10开始的

**Comment by jasonjoo2010** [comment]
Close due to #1204 

It has been fixed without further more JVM requirements.
