### ISSUE TITLE
401 error after login in the dashboard

### ISSUE THREAD

**Issue by zouchuqu** [alibaba/Sentinel#1149]
版本1.6.2 ，控制台登录时一直报401错误，然后没法登录，是我使用哪里不对吗？

1.下载jar包
2.启动jar包
3.用户名和密码都是 sentinel

**Comment by jasonjoo2010** [comment]
If you enter the default pair of username/password and login successfully but still get 401 error in following accesses you can try to check the datetime setting of system both on dashboard node and local system.

如果输入了默认用户名密码登录时并未报错但依然在后续的访问中提示了401错误，那么可以先检查一下dashboard主机和本机的日期时间设置是否正确。

**Comment by zouchuqu** [comment]
When you log in with the default username and password, a 401 error will be reported, as will restarting the computer.
![1573174311(1)](https://user-images.githubusercontent.com/13944662/68481053-27c4f280-0271-11ea-9e1d-154c0f16f043.png)

**Comment by sczyh30** [comment]
> When you log in with the default username and password, a 401 error will be reported, as will restarting the computer.
> ![1573174311(1)](https://user-images.githubusercontent.com/13944662/68481053-27c4f280-0271-11ea-9e1d-154c0f16f043.png)

What did the `/auth` api return?

**Comment by zouchuqu** [comment]
1./auth api response: 
{"success":true,"code":0,"msg":"success","data":{"id":"sentinel","nickName":"sentinel","superUser":true,"loginName":"sentinel"}}

2. /app/briefinfos.json api response:
This request has no response data available.


![1573259205(1)](https://user-images.githubusercontent.com/13944662/68519356-71dac200-02cb-11ea-8343-593a5cc6e3b5.png)

**Comment by sczyh30** [comment]
Has this been resolved?

**Comment by zouchuqu** [comment]
It's not  resolve yet. I tested it on another computer and it's working. I guess it's my computer configuration. I don't have time to debug.

**Comment by sczyh30** [comment]
It's weird. Have you tried to clear the cache of your web browser?

**Comment by zouchuqu** [comment]
It has been tried, but it still doesn't work.

**Comment by cdfive** [comment]
Try using incognito mode of Chrome, click Ctrl+Shift+N(Windows) or Command+Shift+N(Mac OS) to open a new window.
Besides, if login in successfully, a session object will be stored in Local Storage, and you can find it in application tab, which is on the right side of the network tab.
Maybe you need clear it and try again.

**Comment by sczyh30** [comment]
Any feedback? Are there any special configurations on your server side (e.g. regarding server session)?
