### ISSUE TITLE
是否支持多网卡

### ISSUE THREAD

**Issue by yugj** [alibaba/Sentinel#1150]
## Issue Description
生产环境存在多网卡，发现sentinel 机器列表里面的实例用到了管理IP，并不是我们业务IP（多网卡场景区分了业务和管理IP）
sentinel client 启动的时候能否指定或忽略特定的IP？
Type:  *feature request*

### Tell us your environment
sentinel 1.6.3 with zuul 1.x

**Comment by sczyh30** [comment]
You could set the expected client IP via the `-Dcsp.sentinel.heartbeat.client.ip` system property. See #246 for more information.

**Comment by yugj** [comment]
感谢，文档有描述，看走眼了

**Comment by pstree** [comment]
spring.cloud.inetutils.preferred-networks=172.   没有这样的参数支持多网卡吗
