### ISSUE TITLE
Support limit by parampter key

### ISSUE THREAD

**Issue by kaizi2009** [alibaba/Sentinel#1158]
In some cases, the parameters have no order, need limit by parampter key.

**Comment by sczyh30** [comment]
Do you mean [parameter flow control](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-parameter-flow-control)?

**Comment by kaizi2009** [comment]
Yes. for example: 
`Long userId = 12;`
`ParamFlowRule rule = new ParamFlowRule(RESOURCE_KEY)`
    `.setParam(""userId, userId, 5);`

**Comment by sczyh30** [comment]
Could you please give a concrete example and illustrate what to achieve?

**Comment by sczyh30** [comment]
Closing this issue due to no further feedback.
