### ISSUE TITLE
sentinel 与nacos 双向同步，只能改源码吗

### ISSUE THREAD

**Issue by helei-mianyang** [alibaba/Sentinel#1159]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Yes, you may refer to:

- [How to use Sentinel in production](https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#push模式)
- [Rule provider demos for Sentinel dashboard](https://github.com/alibaba/Sentinel/tree/master/sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/rule)
