### ISSUE TITLE
Suggestion: support alarming rules for "slow/extremely slow" resources

### ISSUE THREAD

**Issue by 457049726** [alibaba/Sentinel#1160]
有一种这样的业务场景：业务系统大部分时间运行正常，但是在某些特定的时间段，某些特定的接口因某些未知的原因，导致系统响应速度下降，从而导致业务延迟，但是这种延迟仅仅是影响用户体验度，给用户带来了不好情绪，但还不至于出现业务异常（比如：pos机消费中，刷卡后虽然正常扣费了，但是偶尔出现pos机打印小票单据延迟的情况）。
     如果需要针对这种延迟的接口调用进行监控，我希望可以通过在 sentinel 框架配置一些规则来实现（这种延时并没有出现业务异常，仅仅是“慢”）。
  目前sentinel的规则主要有“限流规则（FlowRule）”、“降级规则（DegradeRule）”、“黑白名单规则（AuthorityRule）”，但是这些规则中，每一种规则被触发都可能会导致业务异常（业务被阻止）。我的思路是，再设计一个单纯做监控之类的规则（比如：“缓慢监控规则（SlowMonitorRule）”，通过在规则中配置“缓慢”或“非常慢”的时间阈值，当业务处理时间超过这个阈值就被认定为”缓慢“或”非常慢“从而触发监控），一旦这种规则被触发，虽然业务还是会正常进行，但是这笔业务会被监控起来（比如将业务参数等信息输出到日志）。为了更好的处理这些监控信息，也可以考虑在“实时监控”模块中，加入对这些监控信息的统计，比如把它加入到“秒级日志”中。目前实时监控的秒级日志数据中，包含“每秒请求过数”、“每秒拦截个数”、“每秒通过个数”，如果再来一个“每秒缓慢/非常慢个数”那就更完美了。。。

**Comment by jasonjoo2010** [comment]
这个实际上是监控系统的事情，并不是流控系统的事情。我知道目前Dashboard提供了一些类似监控系统的功能，但实际上跟监控系统是两码事，往这方面强化可能有更多工作要做，可能有些偏离了项目主题（过重）


It's the responsibility of monitor system/component but not flow guarding system. `Dashboard` provides some basic metrics collecting just like kind of simple monitor feature but Sentinel is a totally different thing compared to monitor system (like falcon, prometheus, etc). It's possible to provide ability transferring data to them but there will be far more works to do as a monitor system which also may cause sentinel be too heavy.

**Comment by 457049726** [comment]
> 
> 
> 这个实际上是监控系统的事情，并不是流控系统的事情。我知道目前Dashboard提供了一些类似监控系统的功能，但实际上跟监控系统是两码事，往这方面强化可能有更多工作要做，可能有些偏离了项目主题（过重）
> 
> It's the responsibility of monitor system/component but not flow guarding system. `Dashboard` provides some basic metrics collecting just like kind of simple monitor feature but Sentinel is a totally different thing compared to monitor system (like falcon, prometheus, etc). It's possible to provide ability transferring data to them but there will be far more works to do as a monitor system which also may cause sentinel be too heavy.

     我觉得这个框架里面，既然通过“实时监控”模块，提供了“秒级日志”，我认为“秒级日志”可以成为外部第三方监控系统的数据源，为监控系统进行工作提供数据依据。对于sentinel框架本身来说，监控这方面的强化也可以不自己做，但是可提供一些这方面的扩展，让我们自定义“秒级日志”的内容（比如通过自定义秒级日志增加“每秒缓慢请求数”）。
     为了实现这个功能，我尝试过参考 StatisticSlot 类自己写一个 SlowMonitorSlot 类，并通过扩展 DefaultSlotChainBuilder 类，把这个 slot 挂到SlotChain链的最后，在  SlowMonitorSlot 实现 exit() 方法，在里面对资源处理时间进行判断（判断当前时间与Entry实体中的 createTime值的时间差），自己也参考 FlowRule、FlowRuleManager等类写了一个 SlowRule 类用来定义 缓慢规则。这样做，确实可以判断资源是否缓慢，还可以通过日志记录下这个资源处理详细信息，但是在用 Metric 进行每秒缓慢数统计的时候卡住了。Metric 接口里面没有支持这方面的方法，它的实现类 ArrayMetric 类也没有这方面的方法。当然，我可以自己整一个Metric 的实现类，模仿 ArrayMetric 采用滑动时间窗口来行统计，但是在写“秒级日志”的时候好像又卡住了，估计得跟原来的“秒级日志”文件(类似app-3518-metrics.log.2018-06-22.1)分开，自已再整个类似“秒级日志”的文件塞到sentinel的日志目录里，感觉这样很别扭，整了两个秒级日志文件出来，读数读取接口又要扩展，而且 自己写的 Metric 的实现类 怎么嵌入到框架面，还需要研究。我觉得最好的办法是把  Metric 接口开放出来，支持自定义扩展，比如通过 spi 机制，像扩展 DefaultSlotChainBuilder  一样。当然，既然 Metric 接口支持 spi扩展，那干脆把 Entry 抽象类也开放出来，整一个 Map 之类的附加属性让我们塞一些自定义数据进去，这样更爽了。。。。。

**Comment by 457049726** [comment]
> 
> 
> 这个实际上是监控系统的事情，并不是流控系统的事情。我知道目前Dashboard提供了一些类似监控系统的功能，但实际上跟监控系统是两码事，往这方面强化可能有更多工作要做，可能有些偏离了项目主题（过重）
> 
> It's the responsibility of monitor system/component but not flow guarding system. `Dashboard` provides some basic metrics collecting just like kind of simple monitor feature but Sentinel is a totally different thing compared to monitor system (like falcon, prometheus, etc). It's possible to provide ability transferring data to them but there will be far more works to do as a monitor system which also may cause sentinel be too heavy.

我觉得这个框架里面，既然通过“实时监控”模块，提供了“秒级日志”，我认为“秒级日志”可以成为外部第三方监控系统的数据源，为监控系统进行工作提供数据依据。对于sentinel框架本身来说，监控这方面的强化也可以不自己做，但是可提供一些这方面的扩展，让我们自定义“秒级日志”的内容（比如通过自定义秒级日志增加“每秒缓慢请求数”）。
为了实现这个功能，我尝试过参考 StatisticSlot 类自己写一个 SlowMonitorSlot 类，并通过扩展 DefaultSlotChainBuilder 类，把这个 slot 挂到SlotChain链的最后，在 SlowMonitorSlot 实现 exit() 方法，在里面对资源处理时间进行判断（判断当前时间与Entry实体中的 createTime值的时间差），自己也参考 FlowRule、FlowRuleManager等类写了一个 SlowRule 类用来定义 缓慢规则。这样做，确实可以判断资源是否缓慢，还可以通过日志记录下这个资源处理详细信息，但是在用 Metric 进行每秒缓慢数统计的时候卡住了。Metric 接口里面没有支持这方面的方法，它的实现类 ArrayMetric 类也没有这方面的方法。当然，我可以自己整一个Metric 的实现类，模仿 ArrayMetric 采用滑动时间窗口来行统计，但是在写“秒级日志”的时候好像又卡住了，估计得跟原来的“秒级日志”文件(类似app-3518-metrics.log.2018-06-22.1)分开，自已再整个类似“秒级日志”的文件塞到sentinel的日志目录里，感觉这样很别扭，整了两个秒级日志文件出来，读数读取接口又要扩展，而且 自己写的 Metric 的实现类 怎么嵌入到框架面，还需要研究。我觉得最好的办法是把 Metric 接口开放出来，支持自定义扩展，比如通过 spi 机制，像扩展 DefaultSlotChainBuilder 一样。当然，既然 Metric 接口支持 spi扩展，那干脆把 Entry 抽象类也开放出来，整一个 Map 之类的附加属性让我们塞一些自定义数据进去，这样更爽了。。。。。

**Comment by jasonjoo2010** [comment]
For general monitor system there may be additional metrics like `max concurrent`, `max response time`, `failure count`, or just you mentioned, `slow queries/requests` to be clustered. But it may turn to be more complicated and too heavy for general purpose. I can say which one is better making `SphU.enter/exit` SPI supported comparing to extending metric clustering to enable them, or just implementing them under specific framework which would cooperate with Sentinel rules dynamically.

But let's get down to the metric of `slow queries`.
Slow can be depended on various factors. Different thresholds for different functions, pure counts per time unit, percentage, etc. Though it sounds reasonable they still can be transformed into `average response time`(especially for percentage) and `semaphore` like unfinished request count . If you want more complicated you can implement the threshold dynamically according to the distributed RT in single time unit and cut the steep segment as the slow threshold or for simpler take the N*RT as the threshold. 
But you see it's a bit too early to define it as a kind of general demand. Compared to decide how to support it how to implement it is better.

**Comment by jasonjoo2010** [comment]
对于监控功能强化来说，还缺失数个比较重要的如最大并发数、最大响应时间、失败数等指标，并且有些可能得看具体的环境和框架会略有不同。“慢查询/请求”的定义本身也有数个方式，比如阈值可变的绝对数、单位时间内数量比例等，并且这些大多情况下这些亦会间接地影响平均响应时间、线程数上的变化，以及还可考虑慢请求从单位时间内请求响应时间在分布上的动态分离，或者简化为数倍的平均响应时间。

所以这些谈通用性还有些早，现阶段如果能抽出客观的必要or普适场景，再很好地去实现和解决才是最重要的。

当然，代表个人观点

**Comment by linlinisme** [comment]
我觉得sentinel目前或者将来是可以考虑一下监控功能方面的扩展和优化。监控和流控是紧密相关的，监控功能的丰富化和粒度的细化可以给使用者设置流控规则时更多有价值的参考数据，并且可以得到更好的反馈。两者相辅相成。从用户的使用角度，如果在sentinel上可以同时一站式使用流控和监控功能，用户体验将会好很多，甚至可以减少搭建监控系统的运维成本。

不过目前sentinel当以流控为主，如果将来要扩展出专业精细的监控功能。最好可以做成可配置化，或者打包成独立的model部分。与流控核心部分隔离，让使用者自行配置和引入。

另外回到具体问题：新增“缓慢/非常慢”之类的预警监控规则。
按照我的个人理解不需要改动 slot chain的核心逻辑。Sentinel已经对提供了SPI形式的监控数据扩展入口 `com.alibaba.csp.sentinel.metric.extension.MetricExtensionProvider` 自定义告警监控之类完全可以通过这种方式实现。

**Comment by linlinisme** [comment]
I think sentinel can consider expansion and optimization of monitoring functions now or in the future. Monitoring and flow control are closely related. The enrichment of monitoring functions and the granularity of granularity can give users more valuable reference data when setting flow control rules, and can get better feedback. The two complement each other. From the user's point of view, if the flow control and monitoring functions can be used at the same time on the sentinel, the user experience will be much better, and the operation and maintenance cost of the monitoring system can be reduced.

However, the current sentinel is mainly based on flow control, if you want to expand the professional fine monitoring function in the future. It's best to make it configurable or package it into a separate model part. It is isolated from the core of the flow control and allows the user to configure and introduce it.

Also return to the specific question: add an early warning monitoring rule such as "slow / very slow".
According to my personal understanding, there is no need to change the core logic of the slot chain. Sentinel has already provided the SPI form of monitoring data extension entry `com.alibaba.csp.sentinel.metric.extension.MetricExtensionProvider`  something of Custom alarm monitoring  can be achieved in this way.

**Comment by 457049726** [comment]
> 
> 
> 我觉得sentinel目前或者将来是可以考虑一下监控功能方面的扩展和优化。监控和流控是紧密相关的，监控功能的丰富化和粒度的细化可以给使用者设置流控规则时更多有价值的参考数据，并且可以得到更好的反馈。两者相辅相成。从用户的使用角度，如果在sentinel上可以同时一站式使用流控和监控功能，用户体验将会好很多，甚至可以减少搭建监控系统的运维成本。
> 
> 不过目前sentinel当以流控为主，如果将来要扩展出专业精细的监控功能。最好可以做成可配置化，或者打包成独立的model部分。与流控核心部分隔离，让使用者自行配置和引入。
> 
> 另外回到具体问题：新增“缓慢/非常慢”之类的预警监控规则。
> 按照我的个人理解不需要改动 slot chain的核心逻辑。Sentinel已经提供了SPI形式的监控数据扩展入口 `com.alibaba.csp.sentinel.metric.extension.MetricExtensionProvider` 自定义告警监控之类完全可以通过这种方式实现。

“缓慢监控与统计”相关功能我已经通过spi扩展自行实现。我决定对sentinel进行进一步扩展，在不改变 sentinel 现有源代码的基础上，通过 spi机制对本框架进行扩充，增加专门的监控相关的功能，将流控与监控结合起来，作为一个可选组件提供出来，如果大家除了流控之外，还有监控相关需求的话，可以采用这个扩展，目前正在设计之中。

**Comment by sczyh30** [comment]
Nice, you may submit a PR to add your extension to the [Awesome Sentinel](https://github.com/alibaba/Sentinel/blob/master/doc/awesome-sentinel.md).
