### ISSUE TITLE
@SentinelResource 熔断错误没有返回。bug

### ISSUE THREAD

**Issue by HPxianliru** [alibaba/Sentinel#1161]
@SentinelResource注解没有加 blockHandler 使用blockHandlerClass 替代。

 @SentinelResource(
            value = "client/log/save",
            blockHandlerClass = DiscoveryClientControllerBackHandler.class,
            fallbackClass = DiscoveryClientControllerFallBackHandler.class
    )

发现后台日志打印 
com.alibaba.csp.sentinel.slots.block.flow.FlowException: null

前端显示
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Nov 16 22:43:32 CST 2019
There was an unexpected error (type=Internal Server Error, status=500).
No message available

不是DiscoveryClientControllerBackHandler设定好的内容。

debug 发现代码 

![image](https://user-images.githubusercontent.com/28264086/68994883-bb766e80-08c2-11ea-8c8f-8a06c3d3ed0a.png)

![image](https://user-images.githubusercontent.com/28264086/68994877-aef21600-08c2-11ea-8098-39e63a43d028.png)

继续跳转到 handleFallback 处理类上

![image](https://user-images.githubusercontent.com/28264086/68994904-ea8ce000-08c2-11ea-8ac9-1e13d3be2fb4.png)
也是同样的问题。

![image](https://user-images.githubusercontent.com/28264086/68994958-76067100-08c3-11ea-8372-7b5e5db0c40c.png)

同样直接返回null 

以下是我的版本信息
spring cloud alibaba 版本  2.1.0.RELEASE
spring cloud 版本 Greenwich.RELEASE
spring boot 版本 2.1.7.RELEASE

sentinel 版本 是1.6.3

**Comment by sczyh30** [comment]
仔细看下文档，blockHandlerClass 要搭配 blockHandler 用的，用于指定 blockHandler 函数所在的类：https://github.com/alibaba/Sentinel/wiki/注解支持#sentinelresource-注解

**Comment by HPxianliru** [comment]
辛苦
