### ISSUE TITLE
Dashboard server address not configured

### ISSUE THREAD

**Issue by goudai** [alibaba/Sentinel#1164]
![image](https://user-images.githubusercontent.com/16605628/69038914-d281a180-0a25-11ea-9093-d6fa7eca020f.png)

![image](https://user-images.githubusercontent.com/16605628/69038922-d8778280-0a25-11ea-8710-269a4821d5cb.png)

**Comment by goudai** [comment]
当我使用`-Dcsp.sentinel.dashboard.server=127.0.0.1:8718 -Dcsp.sentinel.api.port=8740` 命令行传递参数时他将生效，我的spring boot 版本是`2.2.1.RELEASE`，spring cloud的版本是`Hoxton.RC2`

**Comment by fangjian0423** [comment]
pls degrade your spring boot, spring cloud version to 2.1.x, Greenwich.

Spring Cloud Alibaba now not release 2.2.0.RELEASE to adapt Spring Cloud Hoxton.

**Comment by goudai** [comment]
OK~
