### ISSUE TITLE
How to use parameter flow control with SCA Sentinel Feign adapter?

### ISSUE THREAD

**Issue by yangzailai** [alibaba/Sentinel#1166]
可以在feign中使用热点参数限流么？热点参数怎么传递。 

官方文档 ===============
手动通过 API 修改比较直观，可以通过以下几个 API 修改不同的规则：

FlowRuleManager.loadRules(List<FlowRule> rules); // 修改流控规则
DegradeRuleManager.loadRules(List<DegradeRule> rules); // 修改降级规则

===============

热点参数规则不支持动态修改么？控制台有添加热点规则的按钮，在项目中编码 count =2 正常，但是在控制台配置并没有动态修改规则；

**Comment by sczyh30** [comment]
> How to use parameter flow control in Feign adapter?

The args of your Feign interface methods have been passed as parameters to Sentinel, so you could add parameter flow rules for the expected param index.

Related API: https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-parameter-flow-control
