### ISSUE TITLE
Application does not appear in the dashboard 1.7.0

### ISSUE THREAD

**Issue by hadoop835** [alibaba/Sentinel#1175]
pom.xml
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.7.0</version>
        </dependency>
启动参数
 -Dproject.name=test  -Dcsp.sentinel.dashboard.server=127.0.0.1:8088
![image](https://user-images.githubusercontent.com/8055054/69324371-48367900-0c83-11ea-92e4-a6e5c35c6c50.png)

**Comment by sczyh30** [comment]
Please check according to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ).

**Comment by sczyh30** [comment]
Has this been resolved?
