### ISSUE TITLE
sentinel1.6.3集成spring-cloud-gateway无效

### ISSUE THREAD

**Issue by swppt** [alibaba/Sentinel#1176]
sentinel1.6.3集成spring-cloud-gateway流控不生效
无论是在base_route还是请求url上设置阈值都不生效
![image](https://user-images.githubusercontent.com/1203744/69327552-add93400-0c88-11ea-9f92-c7bcafbb2181.png)
![image](https://user-images.githubusercontent.com/1203744/69327632-cc3f2f80-0c88-11ea-834e-13abf2c583d0.png)
![image](https://user-images.githubusercontent.com/1203744/69327664-d8c38800-0c88-11ea-8cf7-2ab4449ef68e.png)
![image](https://user-images.githubusercontent.com/1203744/69327712-ea0c9480-0c88-11ea-9d09-30c7bdce92ed.png)
![image](https://user-images.githubusercontent.com/1203744/69327764-027caf00-0c89-11ea-8196-ad2f2eacaae1.png)

**Comment by sczyh30** [comment]
Please check the `~/logs/csp/sentinel-record.log.xxx` log and see whether the actual slot chain builder is the `GatewaySlotChainBuilder`.

Besides, gateway flow control takes effect for routes or customized API, not the URL (it should be disabled). You may upgrade to the latest Spring Cloud Alibaba version.

**Comment by sczyh30** [comment]
And you may refer to [the document](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#spring-cloud-gateway) to check whether you've configured correctly. You could also use [`spring-cloud-alibaba-sentinel-gateway`](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-%E6%94%AF%E6%8C%81).

**Comment by kdlqbz2020** [comment]
sentinel1.6.3集成spring-cloud-gateway，网关的熔断降级能设置到接口级别吗？我测试了只能到服务级别。
