### ISSUE TITLE
Missing spring-web in spring-cloud-starter-alibaba-sentinel?

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#1178]
sentinel1.6.2
使用了spring-cloud-starter-alibaba-sentinel:2.1.0.RELEASE
問題是這樣的,突然某天升級了代碼,發現無法正常接入sentinel
測試過後用-D參數可以正常接入,但是用SpringBoot的properties文件方式無法接入
後面我對比了一下我的包依賴
我的項目包中用到了rabbitMQ,用了spring的依賴,但是我把這個包下的spring-web排除了
<dependency>
            <groupId>org.springframework.amqp</groupId>
            <artifactId>spring-rabbit</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
反而導致了sentinel無法正常連接到控制臺.
我把這個包去排除去掉了,必須引入spring-web就可以正常properties文件連接到控制臺.
請幫忙看看是否是包依賴衝突.

**Comment by cookiejoo** [comment]
一个现象是AppNameUtil
public static void resolveAppName() {
        String app = System.getProperty(APP_NAME);
如果不引入spring-web包这里获取不到值,=null,如果引入了spring-web包可以获取到project.name
        // use -Dproject.name first
        if (!isEmpty(app)) {
            appName = app;
            return;
        }

        // parse sun.java.command property
获取不到值则这里是Application启动类的全名
        String command = System.getProperty(SUN_JAVA_COMMAND);
        if (isEmpty(command)) {
            return;
        }

**Comment by sczyh30** [comment]
Refer: https://github.com/alibaba/spring-cloud-alibaba/issues/1074
