### ISSUE TITLE
什么时候Sentinel可以集成网关的功能啊！

### ISSUE THREAD

**Issue by 2738671** [alibaba/Sentinel#1180]
实现全部国产，把 Gateway主要的路由功能代替了。我现在就是用Sentinel当熔断工具，用Gateway当网关。但是还是希望贵方能推出自己的Gateway插件，实现nacos-dubbo-Sentinel-Gateway整条链路

**Comment by sczyh30** [comment]
Currently Sentinel works as the resilience component, providing [flow control ability for API gateways](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81). We might extend more functionalities later :)
