### ISSUE TITLE
AuthorityRule context.getOrigin() is null by consumer project

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#1182]
I have a question.
I use this AuthorityRule to protection my dubbo Service of project .
but another project not use sentinel and never import sentinel dubbo adapter.
so in my project debug point method AuthorityRuleChecker - passCheck:

```
class AuthorityRuleChecker {
static boolean passCheck(AuthorityRule rule, Context context) {
        String requester = context.getOrigin();
        // Empty origin or empty limitApp will pass.
        if (**StringUtil.isEmpty(requester)** || StringUtil.isEmpty(rule.getLimitApp())) {
            return true;
        }
}
```

I find this  requester values is null. because that {getOrigin} is from the dubbo Attachment {dubboApplication}
dubbo jar never use this Attachment.
so i must be  import sentinel dubbo adapter in another project to get {dubboApplication}.
Otherwise, it will not be used all the AuthorityRule
```
public static final String SENTINEL_DUBBO_APPLICATION_KEY = "dubboApplication";
    public static String getApplication(Invocation invocation, String defaultValue) {
        if (invocation == null || invocation.getAttachments() == null) {
            throw new IllegalArgumentException("Bad invocation instance");
        }
        return invocation.getAttachment(SENTINEL_DUBBO_APPLICATION_KEY, defaultValue);
    }
}
```
中文意思是:为什么要用dubboApplication这个属性来获取dubbo name,如果客户端没有引入sentinel的dubbo适配包,这里永远为空,加上判断,永远进不去AuthorityRuleChecker 这段逻辑.
我认为应该去的StringUtil.isEmpty(requester),否则会漏掉其他没有适配到的包.因为不一定每个项目都会引入这个包.所以配置了黑白名单,还是有其他系统能调用到服务端接口的.

这一点想请教一下这样设计的目的是为什么呢?盼复,Thanks♪(･ω･)ﾉ

**Comment by jasonjoo2010** [comment]
This adapter in my opinion is just one of the possible implementations and only for the pairs integrated sentinel-dubbo-adapter.

For those consumers which we don't want introduce the adapter we could fill the attachment by ourselves(follow the principle) or we can feel free to implement a totally new one.

**Comment by cookiejoo** [comment]
> This adapter in my opinion is just one of the possible implementations and only for the pairs integrated sentinel-dubbo-adapter.
> 
> For those consumers which we don't want introduce the adapter we could fill the attachment by ourselves(follow the principle) or we can feel free to implement a totally new one.

But for Provide,I just cover rule of my config,if this requester is null then i want return the Exception.
As for customers,you need to implement the dubbo adapter and set attachment.
Isn't it?

**Comment by jasonjoo2010** [comment]
> > This adapter in my opinion is just one of the possible implementations and only for the pairs integrated sentinel-dubbo-adapter.
> > For those consumers which we don't want introduce the adapter we could fill the attachment by ourselves(follow the principle) or we can feel free to implement a totally new one.
> 
> But for Provide,I just cover rule of my config,if this requester is null then i want return the Exception.
> As for customers,you need to implement the dubbo adapter and set attachment.
> Isn't it?

Exactly.
You can integrate it on both of them (provider & consumer side), integrate it on provider side and set it manually on consumer side, or just reimplement a new one.

Adapters are more of customized scenarios. You may feel free to copy, modify, generate a new one on private repository(nexus) or your own branch in public repository.

**Comment by cookiejoo** [comment]
> > > This adapter in my opinion is just one of the possible implementations and only for the pairs integrated sentinel-dubbo-adapter.
> > > For those consumers which we don't want introduce the adapter we could fill the attachment by ourselves(follow the principle) or we can feel free to implement a totally new one.
> > 
> > 
> > But for Provide,I just cover rule of my config,if this requester is null then i want return the Exception.
> > As for customers,you need to implement the dubbo adapter and set attachment.
> > Isn't it?
> 
> Exactly.
> You can integrate it on both of them (provider & consumer side), integrate it on provider side and set it manually on consumer side, or just reimplement a new one.
> 
> Adapters are more of customized scenarios. You may feel free to copy, modify, generate a new one on private repository(nexus) or your own branch in public repository.

oh!I know what you mean. Thanks♪(･ω･)ﾉ

**Comment by jasonjoo2010** [comment]
> > > > This adapter in my opinion is just one of the possible implementations and only for the pairs integrated sentinel-dubbo-adapter.
> > > > For those consumers which we don't want introduce the adapter we could fill the attachment by ourselves(follow the principle) or we can feel free to implement a totally new one.
> > > 
> > > 
> > > But for Provide,I just cover rule of my config,if this requester is null then i want return the Exception.
> > > As for customers,you need to implement the dubbo adapter and set attachment.
> > > Isn't it?
> > 
> > 
> > Exactly.
> > You can integrate it on both of them (provider & consumer side), integrate it on provider side and set it manually on consumer side, or just reimplement a new one.
> > Adapters are more of customized scenarios. You may feel free to copy, modify, generate a new one on private repository(nexus) or your own branch in public repository.
> 
> oh!I know what you mean. Thanks♪(･ω･)ﾉ

Glad to help 😄
