### ISSUE TITLE
Tracer.trace(ex) NPE in Context.getCurNode when context size exceeds the limit

### ISSUE THREAD

**Issue by nicky1** [alibaba/Sentinel#1184]
## Issue Description

Type: bug report
java.lang.NullPointerException: null\n\tat com.alibaba.csp.sentinel.context.Context.getCurNode(Context.java:112) ~[sentinel-core-1.4.0.jar!/:1.4.0]\n\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:45) ~[sentinel-core-1.4.0.jar!/:1.4.0]\n\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:32)

### Tell us your environment
spring boot 2.0.0.RELEASE, sentinel  0.2.1.RELEASE

**Comment by sczyh30** [comment]
You'll need to call `Tracer.trace(ex)` within the context of your resource entry. Or you could update to the latest version and call `Tracer.traceEntry(ex, entry)`.

---

`Tracer.trace(ex)` 必须在 `SphU.entry(xxx)` 成功之后且 exit 之前调用。也可以升级到最新版本然后调用 `Tracer.trace(ex, entry)` 指定 entry 记录异常。

**Comment by nicky1** [comment]
你好，我没有主动调用过 Tracer.trace(ex) 方法，在kibana日志监控中看到的异常，所以很奇怪。
非常感谢你的回复。

**Comment by sczyh30** [comment]
Could you please provide the full exception stack to see where the invocation occurs?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by nicky1** [comment]
1.sorry，这几天都没怎么看邮件，我把详细的日志贴出来

 UT005023: Exception handling request to /

/xxxxxxxx/请求路径\\n\\njava.lang.NullPointerException: null\\n\\tat com.alibaba.csp.sentinel.context.Context.getCurNode(Context.java:112) ~[sentinel-core-1.4.0.jar!/:1.4.0]\\n\\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:45) ~[sentinel-core-1.4.0.jar!/:1.4.0]\\n\\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:32) ~[sentinel-core-1.4.0.jar!/:1.4.0]\\n\\tat com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter(CommonFilter.java:95) ~[sentinel-web-servlet-1.4.0.jar!/:na]\\n\\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.handlers.GracefulShutdownHandler.handleRequest(GracefulShutdownHandler.java:69) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:336) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]\\n\\tat java.lang.Thread.run(Thread.java:748)

**Comment by nicky1** [comment]
spring-cloud-starter-alibaba-sentinel:0.2.1.RELEASE
spring-boot-starter-parent:2.0.0.RELEASE

**Comment by sczyh30** [comment]
代码中有没有其它的自定义埋点（手动调 `SphU.entry(xxx)`）？

---

Is there any customized Sentinel entry (i.e. `SphU.entry(xxx)`)?

**Comment by nicky1** [comment]
你好：
有的
1.使用到了 漏桶方式的限流策略
  1.1 设置规则：
            
     `private static void initPaceFlowRule(long schoolId, int count) {
        List<FlowRule> rules = Lists.newArrayList();
        FlowRule rule1 = new FlowRule();
        rule1.setResource(String.format(Constant.LIMIT_FLOW_KEY, schoolId));
        rule1.setCount(count);
        rule1.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule1.setLimitApp("default");
        /*
         * CONTROL_BEHAVIOR_RATE_LIMITER means requests more than threshold will be queueing in the queue,
         * until the queueing time is more than {@link FlowRule#maxQueueingTimeMs}, the requests will be rejected.
         */
        rule1.setControlBehavior(RuleConstant.CONTROL_BEHAVIOR_RATE_LIMITER);
        rule1.setMaxQueueingTimeMs(700);

        rules.add(rule1);
        FlowRuleManager.loadRules(rules);
    }`

  1.2 判断是否限流
      `String key = String.format(Constant.LIMIT_FLOW_KEY, schoolId);
        Entry entry = null;
        try {
            entry = SphU.entry(key, EntryType.IN);
            token = Constant.DEFAULT_TOKEN;
        } catch (BlockException e) {
            log.error("block:" +
                    now + " one request pass");
            unHandInNum = examCorrectManager.getUnHandInNum(examId, schoolId);
        } finally {
            if (null != entry) {
                entry.exit();
                long cost = TimeUtil.currentTimeMillis() - startTime;
                log.info("pass:" +
                        now + " one request pass, cost " + cost + " ms");
            }
        }`

**Comment by nicky1** [comment]
大概猜测下原因：
1.在没有接入sentinel前， 同一个问题报的错都被 undertow 捕获了
  引入 sentinel 后，报错都是在 com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter

2.不知道什么会走到 sentinel的 filter 中？

**Comment by luoxn28** [comment]
@nicky1 
应该是sentinel的common filter是作为undertow中filter链最后节点的，这样业务代码报异常首先会被sentinel filter捕获。

**Comment by sczyh30** [comment]
Yes, if current context is a `NullContext` then `Tracer.trace(ex)` for the NullContext will cause NPE. It's actually a bug. We might need to exclude the `NullContext` or check whether `curNode` is null here:

https://github.com/alibaba/Sentinel/blob/b13684887306af1012ea9d99ae4567895f3968d3/sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java#L60-L66

Contributions are welcomed!

**Comment by cdfive** [comment]
@sczyh30 
I found that the **NPE** is in `Context#getCurNode` method, the `curEntry` is null when `NullContext` instance.

May I add a check in `Context#getCurNode` when `curEntry` is null return null? Since the constructor of `Context` doesn't initialize `curEntry`, its null until we call `setCurEntry` method,
and the `getLastNode` method has null check for `curEntry`.

Then does it need to exclude the `NullContext` in `Tracer`.
Both checked, is it better?

**Comment by sczyh30** [comment]
> @sczyh30
> I found that the **NPE** is in `Context#getCurNode` method, the `curEntry` is null when `NullContext` instance.
> 
> May I add a check in `Context#getCurNode` when `curEntry` is null return null? Since the constructor of `Context` doesn't initialize `curEntry`, its null until we call `setCurEntry` method,
> and the `getLastNode` method has null check for `curEntry`.
> 
> Then does it need to exclude the `NullContext` in `Tracer`.
> Both checked, is it better?

Good suggestion. It's better to add checking logic in both places.
