### ISSUE TITLE
AHAS console error while using zuul2 adapter

### ISSUE THREAD

**Issue by locuslin** [alibaba/Sentinel#1186]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
AHAS console js error while using sentinel zuul2 adapter.
The url is `https://ahas.console.aliyun.com/#/SystemGuardGw?regionId=cn-hangzhou&_k=exs177&isi=`
see the picture blow.
![图片](https://user-images.githubusercontent.com/8586425/70125774-7a4bd000-16b2-11ea-8a08-f0d62827b6ec.png)

It's ok to use "应用流控" and failed while using "网关流控",and works well in the detail page.
It happens very often and  works by chance .

Main difference between the data returned by "https://ahas.console.aliyun.com/data/api.json?action=SentinelListTopNAppsSummaryMetricOfAppType" shown in the pic,missing the property of "clientVersion".
![图片](https://user-images.githubusercontent.com/8586425/70126552-41145f80-16b4-11ea-8630-c722e2b39ae5.png)

Part of  log in ~/csp/sentinel-record.log.2019-12-04.0 .
 
![图片](https://user-images.githubusercontent.com/8586425/70126812-ba13b700-16b4-11ea-99d0-ab5b82adbf66.png)

### Describe what you expected to happen
The console show the correct list of applications. 

### How to reproduce it (as minimally and precisely as possible)
using https://github.com/alibaba/Sentinel/pull/1138 and add ahas-sentinel-client ,tried 1.5.0 and 1.3.5.

### Tell us your environment
jdk 1.8
Sentinel-core 1.7.0
 ahas-sentinel-client 1.5.0 /1.3.5
aliyun ecs vpc

Firefox 71.0 /Chrome/78.0.3904.99 
### Anything else we need to know?

I can upload the full log if needed.

**Comment by sczyh30** [comment]
It seems that the `machineCount` of your app is zero. Could you please check whether there are any error messages in your `sentinel-record.log`?

**Comment by locuslin** [comment]
> 
> 
> It seems that the `machineCount` of your app is zero. Could you please check whether there are any error messages in your `sentinel-record.log`?


There is no error in `sentinel-record.log`.Here is the detail.


> [vale@xxxx csp]$ grep ERROR sentinel-record.log.2019-12-04.0 | wc -l
> 0
> [vale@xxxx csp]$ grep WARN sentinel-record.log.2019-12-04.0 | wc -l
> 78
> [vale@xxxx csp]$ grep error sentinel-record.log.2019-12-04.0 | grep WARN | wc -l
> 23
> [vale@xxxx csp]$ grep error sentinel-record.log.2019-12-04.0 | wc -l
> 46
> [vale@xxxx csp]$ grep error sentinel-record.log.2019-12-04.0
> 2019-12-04 11:33:50.584 WARNING [HeartbeatSender] Send heartbeat error
> java.lang.RuntimeException: Response{requestId='null', code=500, success=false, result=null, error='aid: 0c92fc869f3d0645425033edcff76be4, msg: agw rpc exception [code: 8001, message: rpc timeout]'}

And the data shown in the detail page seems exactly correct.
![图片](https://user-images.githubusercontent.com/8586425/70198062-b762a180-1748-11ea-9595-b0aff10b28bb.png)


And the console page works well in this morning .The data returned by  `https://ahas.console.aliyun.com/data/api.json?action=SentinelListTopNAppsSummaryMetricOfAppType` changed normal .
![图片](https://user-images.githubusercontent.com/8586425/70198227-3d7ee800-1749-11ea-9fa2-54e6c295b475.png)

**Comment by locuslin** [comment]
The console turned out ok now.
