### ISSUE TITLE
Question: The meaning of onSubscribe when request is blocked

### ISSUE THREAD

**Issue by wavesZh** [alibaba/Sentinel#1187]
The use of [that](https://github.com/alibaba/Sentinel/blob/086a6b0370c41ad73c0904d3ff726e2334bec96b/sentinel-adapter/sentinel-reactor-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/reactor/SentinelReactorSubscriber.java#L101) ? 
In my opinion，that is redundant.

**Comment by sczyh30** [comment]
See [the reactive stream specification](https://github.com/reactive-streams/reactive-streams-jvm#1.9) §1.9:

> `Publisher.subscribe` MUST call `onSubscribe` on the provided `Subscriber` prior to any other signals to that `Subscriber` and MUST [return normally](#term_return_normally), except when the provided `Subscriber` is `null` in which case it MUST throw a `java.lang.NullPointerException` to the caller, for all other situations the only legal way to signal failure (or reject the `Subscriber`) is by calling `onError` (after calling `onSubscribe`).

Every reactive operator should follow the specification.
