### ISSUE TITLE
Support configuring project.name via the properties file

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1191]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Since [1.7.0](https://github.com/alibaba/Sentinel/releases/tag/1.7.0), Sentinel has supported configuration via the properties file (except the `project.name` property). The `project.name` property is not supported due to the legacy logic (compatible with the legacy default path `~/logs/csp/${appName}.properties`), which is rarely used. So we may deprecate the legacy logic in the next few versions and then support configuring `project.name` via the properties file.

Further discussions are welcomed!

**Comment by sczyh30** [comment]
Also refer to #804

**Comment by wavesZh** [comment]
I will finish it

**Comment by sczyh30** [comment]
Good. Compatibility and implicit class dependency should be considered carefully.
