### ISSUE TITLE
Can SentinelZuulPreFilter support URL-level gateway flow control?

### ISSUE THREAD

**Issue by binecy** [alibaba/Sentinel#1193]
请教一下，我们在使用zuul+sentinel，发现SentinelZuulPreFilte只能对proxyId或 API 分组进行限流，如果要对每个url限流就需要为每个url建立一个api分组，请问可以默认对url限流吗，就是使用proxyId检查规则后再使用url检查规则

**Comment by sczyh30** [comment]
URL-level flow control is not supported in gateway flow control, as it might bring too many URL resources. Could you please illustrate your scenario of URL-level gateway flow control?

**Comment by binecy** [comment]
我们的做法是为每个url添加一个FlowRule，这样的隔离性最好，但没有使用ParamFlowRule，因为暂时没有这样需求。
你说的过多的resources，是担心过多滑动窗口导致内存方面吗

**Comment by sczyh30** [comment]
Yes, too many URLs may bring hazardous memory footprint. Maybe you could implement your own filter and only extract necessary URLs as Sentinel resources.
