### ISSUE TITLE
Support Eureka data source

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1197]
## Issue Description

Type: *feature request*

### Describe what feature you want

Support Eureka data source.

**Comment by complone** [comment]
@sczyh30 Hello, I want to contribute dynamic rule source extension support for Eureka

**Comment by sczyh30** [comment]
Nice, looking forward to your PR~

**Comment by sczyh30** [comment]
Hi, any progress? :)

**Comment by complone** [comment]
> Hi, any progress? :)


I've been too busy these days, looking at the dynamic rules code related to spring-config. Prepare yourself to test these days

**Comment by sczyh30** [comment]
@complone Hi, any progress about it?

**Comment by Garlichead** [comment]
Can i claim?

**Comment by sczyh30** [comment]
Contributions are welcomed!

**Comment by Garlichead** [comment]
What is your time requirement?
