### ISSUE TITLE
blockHandler question

### ISSUE THREAD

**Issue by tanjiancheng** [alibaba/Sentinel#1198]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
框架是spring-boot2.2.2，我使用SentinelResource的注解然后添加流控规则资源名为hello的时候，程序能正常进入helloHandler，代码如下
```
    @RequestMapping("/hello")
    @SentinelResource(value= "hello", blockHandler = "helloHandler", fallback = "helloFallback")
    public String hello() {
        return "abc";
    }

    public String helloHandler(BlockException ex) {
        System.out.println("hello block");
        return "block";
    }

    public String helloFallback() {
        System.out.println("hello fallback");
        return "fallback";
    }
```
可是当我修改SentinelResource的value为/hello的时候，意图是想要保持SentinelResource的名字跟RequestMapping的名字一致，流控规则资源名为/hello，发现流控有时候进入helloHandler，有时候提示Blocked by Sentinel (flow limiting)，这个SentinelResource注解的value为什么带有/的时候回产生这种情况？
```
@RequestMapping("/hello")
    @SentinelResource(value= "/hello", blockHandler = "helloHandler", fallback = "helloFallback")
    public String hello() {
        return "abc";
    }

    public String helloHandler(BlockException ex) {
        System.out.println("hello block");
        return "block";
    }

    public String helloFallback() {
        System.out.println("hello fallback");
        return "fallback";
    }
```
![image](https://user-images.githubusercontent.com/7401570/70764215-d63ce580-1d91-11ea-8c94-98cdfe4c9998.png)

有时候正常进入handler
![image](https://user-images.githubusercontent.com/7401570/70764262-fff60c80-1d91-11ea-9710-6d05139dedef.png)

有时候返回默认流控提示页
![image](https://user-images.githubusercontent.com/7401570/70764286-113f1900-1d92-11ea-84fb-8bf05ea9ec8d.png)

### Tell us your environment
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.2.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.xsjweb</groupId>
    <artifactId>sentinel-spring-boot-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>sentinel-spring-boot-app</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>RELEASE</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.62</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.9.0.RELEASE</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```
### Anything else we need to know?
 我想知道是不是SentinelResource注解value不支持/xxx的形式，因为如果配置非/xxx的格式的话，面板实时监控有2个，分别为/hello,hello，感觉有点冗余
![image](https://user-images.githubusercontent.com/7401570/70764512-c1ad1d00-1d92-11ea-897d-f5e6209411d7.png)

**Comment by tanjiancheng** [comment]
你好，有人可以解答下吗？

**Comment by sczyh30** [comment]
`/hello` 这种资源名是 [Sentinel Web 适配](https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-适配)自动生成的，同样可以配置自定义限流处理逻辑（参考对应文档）。一般不建议 controller 上面注解与 Web 适配混用。

**Comment by tanjiancheng** [comment]
> 。一般不建议 controller 上面注解与 Web 适配混用

所以配置/hello有时候正常进入blockHandler，有时候提示Blocked by Sentinel (flow limiting)这个是什么原因导致的？

**Comment by cdfive** [comment]
pom里依赖了`spring-cloud-starter-alibaba-sentinel`，
`spring-cloud-starter-alibaba-sentinel`为了方便地使用，引入了`sentinel-annotation-aspectj`和`sentinel-web-servlet`。

```
@RequestMapping("/hello")
@SentinelResource(value= "/hello", blockHandler = "helloHandler", fallback = "helloFallback")
public String hello() {
     return "abc";
}
```
两个/hello，这样`sentinel-web-servlet`适配和`@SentinelResource`就是相同的资源名，相当于经过了Sentinel处理了2次，所以有时被`@SentinelResource`拦截到进blockHandler，有时被`sentinel-web-servlet`适配拦截到提示Blocked by Sentinel (flow limiting)。

Blocked by Sentinel (flow limiting)是`sentinel-web-servlet`适配默认的限流提示信息，参考上面@szyh30发的wiki文档。

可以考虑设置`spring.cloud.sentinel.filter.enabled=false`或者去掉`@SentinelResource`。

**Comment by tanjiancheng** [comment]
> pom里依赖了`spring-cloud-starter-alibaba-sentinel`，
> `spring-cloud-starter-alibaba-sentinel`为了方便地使用，引入了`sentinel-annotation-aspectj`和`sentinel-web-servlet`。
> 
> ```
> @RequestMapping("/hello")
> @SentinelResource(value= "/hello", blockHandler = "helloHandler", fallback = "helloFallback")
> public String hello() {
>      return "abc";
> }
> ```
> 
> 两个/hello，这样`sentinel-web-servlet`适配和`@SentinelResource`就是相同的资源名，相当于经过了Sentinel处理了2次，所以有时被`@SentinelResource`拦截到进blockHandler，有时被`sentinel-web-servlet`适配拦截到提示Blocked by Sentinel (flow limiting)。
> 
> Blocked by Sentinel (flow limiting)是`sentinel-web-servlet`适配默认的限流提示信息，参考上面@szyh30发的wiki文档。
> 
> 可以考虑设置`spring.cloud.sentinel.filter.enabled=false`或者去掉`@SentinelResource`。

好的，明白了，非常感谢你的回答，回答得很详细
