### ISSUE TITLE
CtSph一处注释错误

### ISSUE THREAD

**Issue by lihongkun** [alibaba/Sentinel#12]
CtSph 类, 第91行  , Means processor size exceeds {@link Constants.MAX_ENTRY_SIZE} . 感觉是遗留代码

**Comment by sczyh30** [comment]
此处的意思见 [CtSph#L118](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/CtSph.java#L118).
