### ISSUE TITLE
mvn clean package exception

### ISSUE THREAD

**Issue by q821863269** [alibaba/Sentinel#1201]
Time: 2019-12-14 11:52:00

1. git clone https://github.com/alibaba/Sentinel.git
2. mvn clean package

Problem:
![J)`FY5%1G95@E$NQ}( %2(0](https://user-images.githubusercontent.com/37721392/70843154-b3313500-1e68-11ea-9ea6-14c162854880.png)

**Comment by sczyh30** [comment]
It's not an error. It might be hanging at the test cases of the Consul data source, which would fetch the embedded Consul first (the network might be slow). You could skip the test directly.

**Comment by q821863269** [comment]
> It's not an error. It might be hanging at the test cases of the Consul data source, which would fetch the embedded Consul first (the network might be slow). You could skip the test directly.

Ok, I see
