### ISSUE TITLE
开启sentinel 熔断功能;SentinelInvocationHandler 类在代理FeignClient方法怎么对业务异常进行排除处理;

### ISSUE THREAD

**Issue by cqu20141693** [alibaba/Sentinel#1202]
现在我们准备是用sentinel 熔断的功能;但是开启后;默认对所有的异常走了fallback, 但是业务异常想单独抛出处理
![image](https://user-images.githubusercontent.com/16770705/70872743-23fd5c00-1fe5-11ea-98bc-47268e7881e8.png)

**Comment by Foredoomed** [comment]
试一下exceptionsToIgnore

**Comment by cqu20141693** [comment]
已经到找方法了;使用feign fallbackFactory  处理业务异常

**Comment by DevilsYQ** [comment]
如果用 feign的fallbackFactory的话,业务异常还是进过Tracer的异常统计吧..?
