### ISSUE TITLE
dubbo2.7 incompatible

### ISSUE THREAD

**Issue by a364176773** [alibaba/Sentinel#1203]
## Issue Description

The package name wrong

### Describe what happened (or what feature you want)

`java.lang.NoSuchMethodError: com.alibaba.dubbo.rpc.RpcContext.setAttachment(Ljava/lang/String;Ljava/lang/String;)Lcom/alibaba/dubbo/rpc/RpcContext;`

### How to reproduce it (as minimally and precisely as possible)

1. dubbo2.7
2. sentinel-dubbo-adapter 1.7.0
3. spring boot
4. statrt poject
5.call on api
### Tell us your environment
jdk1.8
windows

### Anything else we need to know?
this is wrong:
`com.alibaba.dubbo.rpc.RpcContext.setAttachment`
correct:
org.apache.dubbo.rpc.RpcContext
or do it like this:
```
 try {
Class.forName("org.apache.dubbo.rpc.RpcContext");
         } catch (Exception e) {
         }
```
To determine which one to use?

**Comment by sczyh30** [comment]
Please use `sentinel-apache-dubbo-adapter` instead for Dubbo 2.7.x. See [the document](https://github.com/alibaba/Sentinel/wiki/Adapters-to-Popular-Framework#dubbo).
