### ISSUE TITLE
Env static init Suggestion

### ISSUE THREAD

**Issue by lkxiaolou** [alibaba/Sentinel#1205]
https://github.com/alibaba/Sentinel/blob/00dbb5ca3e1ee6cc3e516efdd7ca4176887cca54/sentinel-core/src/main/java/com/alibaba/csp/sentinel/Env.java#L36

Do init in the static code will block the normal request because Env class load not completely, request will block until class loaded, if do some connections in the init function, such as connecting zookeeper,it will case bad performance , I think it should use an Async static init function or other better way.

**Comment by sczyh30** [comment]
Actually async or sync initialization depends on the `InitFunc` implementation. For most time-cost `InitFunc` they should be asynchronous (e.g. the InitFunc for CommandCenter).
