### ISSUE TITLE
网关流控面板支持面板数据修改同步到nacos吗？

### ISSUE THREAD

**Issue by tanjiancheng** [alibaba/Sentinel#1209]
## Issue Description
我搭建了nacos和sentinel dashboard，使用sentinel-datasource-nacos可以做到在nacos修改gateway的流控规则同步到dashboard面板并生效。但是在nacos编辑json数据的方式不是很直观，我想在sentinel dashboard面板直接增加流控规则可以同步到nacos上并客户端生效，目前看了GatewayFlowRuleController这块好像没有抽象出来可以实现（ps：测试过非网关模式使可以互通的）
Type: *feature request*

### Describe what happened (or what feature you want)
面板修改规则自动同步到nacos并使客户端规则自动刷新，有什么方式可以实现吗，大神们麻烦指点一下

![image](https://user-images.githubusercontent.com/7401570/71143910-2f57be00-2257-11ea-9cba-b9bc795867c0.png)

**Comment by sczyh30** [comment]
You could refactor the controller by yourself according to the pattern of `FlowControllerV2`. Contributions are welcomed.

**Comment by tanjiancheng** [comment]
> You could refactor the controller by yourself according to the pattern of `FlowControllerV2`. Contributions are welcomed.

ok,thanks,I will try this,after finish I will put my link of that here

**Comment by tanjiancheng** [comment]
> You could refactor the controller by yourself according to the pattern of `FlowControllerV2`. Contributions are welcomed.

Here is sentinel dashboard and gateway model relate with nacos，maybe help people in need

[阿里sentinel后台面板规则（包括gateway模式）持久化-推模式（nacos），基于版本v1.7.0改造](https://github.com/tanjiancheng/alibaba-sentinel-dashboard-nacos)

**Comment by sczyh30** [comment]
Nice. Would you like to submit a PR to add your blog post to the [Awesome Sentinel](https://github.com/sentinel-group/sentinel-awesome)?

**Comment by tanjiancheng** [comment]
> Nice. Would you like to submit a PR to add your blog post to the [Awesome Sentinel](https://github.com/sentinel-group/sentinel-awesome)?

It's my pleasur，I will try to do that later when my blog finish

**Comment by ChrisLeejing** [comment]
> > Nice. Would you like to submit a PR to add your blog post to the [Awesome Sentinel](https://github.com/sentinel-group/sentinel-awesome)?
> 
> It's my pleasur，I will try to do that later when my blog finish

Hello, hava you submit a PR with "push the updated gateway rules to nacos"?

**Comment by ricardo0624** [comment]
为啥大家都是中国人,汉语都不错,非要在这里讲英语呢?图什么
