### ISSUE TITLE
Sentinel目前只有一个全局开关控制规则的启用和禁用，是否提供基于单条规则的控制开关

### ISSUE THREAD

**Issue by zhbron** [alibaba/Sentinel#1211]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

Sentinel 目前只有一个全局开关控制规则的启用和禁用，是否提供基于单条规则的控制开关？

Does Sentinel provide enable and disable switch for the single rule？

**Comment by sczyh30** [comment]
You may refer to the solution described in #798.
