### ISSUE TITLE
Sentinel 链路流控模式失效

### ISSUE THREAD

**Issue by xinmingguo-hm** [alibaba/Sentinel#1213]
我现在使用的是 spring-cloud-alibaba 2.1.0.RELEASE版本, 控制台用的是1.7.1版本,目前遇到的问题是流控规则-流控模式-链路模式不生效
I am using spring cloud Alibaba version 2.1.0.release, and the console version 1.7.1. The current problem is that the flow control rule flow control mode link mode is not effective

code:
![Snipaste_2019-12-20_18-09-04](https://user-images.githubusercontent.com/59084912/71247618-0f59f480-2354-11ea-8c5d-5e8ccc271f97.png)

configure:
![Snipaste_2019-12-20_18-04-54](https://user-images.githubusercontent.com/59084912/71247258-55fb1f00-2353-11ea-8672-8c33956c0ab1.png)

![Snipaste_2019-12-20_18-06-31](https://user-images.githubusercontent.com/59084912/71247330-7b882880-2353-11ea-960a-096c13ed3bfb.png)

在这种配置下,目前message1和message2 都限制失败
In this configuration, the current message1 and message2 restrictions fail

**Comment by sczyh30** [comment]
Since 1.6.3, the web CommonFilter would unify the web entrance context, so the entrance flow control does not take effect. Sentinel 1.7.0 (~SCA 2.1.1.RELEASE) introduced an init parameter for the CommonFilter: `WEB_CONTEXT_UNIFY`, to control the context. You could set it to `false` when adding the FilterRegistration.

https://github.com/alibaba/Sentinel/blob/0e110c68ea15f13f67c5c756c7efeac2ba99aa44/sentinel-adapter/sentinel-web-servlet/src/main/java/com/alibaba/csp/sentinel/adapter/servlet/CommonFilter.java#L56-L63

See also #1024 for the background.

---

从 1.6.3 版本开始，Sentinel Web filter 默认收敛所有 URL 的入口 context，因此链路限流不生效。1.7.0 版本开始（对应 SCA 2.1.1.RELEASE)，我们在 CommonFilter 引入了 `WEB_CONTEXT_UNIFY` 这个 init parameter，用于控制是否收敛 context。将其配置为 `false` 即可根据不同的 URL 进行链路限流。

**Comment by xinmingguo-hm** [comment]
可不可以这样理解:1.6.3 版本无法使用链路限流,1.7.0之后,可以通过配置开启链路限流?

**Comment by yinhao19941211** [comment]
`import com.alibaba.csp.sentinel.adapter.servlet.CommonFilter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FilterContextConfig {


    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        // 入口资源关闭聚合
        registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
        registration.setName("sentinelFilter");
        registration.setOrder(1);
        return registration;
    }

}`

**Comment by yinhao19941211** [comment]
添加一个配置类即可：
```
import com.alibaba.csp.sentinel.adapter.servlet.CommonFilter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FilterContextConfig {


    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        // 入口资源关闭聚合
        registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
        registration.setName("sentinelFilter");
        registration.setOrder(1);
        return registration;
    }

}
```

**Comment by yinhao19941211** [comment]
1. 配置文件中关闭sentinel的CommonFilter实例化`spring.cloud.sentinel.filter.enabled=false`
2. 添加一个配置类，自己构建CommonFilter实例
```
import com.alibaba.csp.sentinel.adapter.servlet.CommonFilter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FilterContextConfig {

    /**
     * 手动注入Sentinel的过滤器，关闭Sentinel注入CommonFilter实例，修改配置文件中的 spring.cloud.sentinel.filter.enabled=false
     * 入口资源聚合问题：https://github.com/alibaba/Sentinel/issues/1024 或 https://github.com/alibaba/Sentinel/issues/1213
     * 入口资源聚合问题解决：https://github.com/alibaba/Sentinel/pull/1111
     */
    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        // 入口资源关闭聚合
        registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
        registration.setName("sentinelFilter");
        registration.setOrder(1);
        return registration;
    }

}
```

**Comment by sczyh30** [comment]
It will be supported to configure this in Spring config file with Spring Cloud Alibaba Sentinel. The relevant issue: https://github.com/alibaba/spring-cloud-alibaba/issues/1138

**Comment by xinmingguo-hm** [comment]
配置了, 好使的, 多谢各位大神的支持.

**Comment by 18050012583** [comment]
设置了还是不生效呀。

**Comment by 18050012583** [comment]
public class SentinelProperties {
    private boolean eager = false;
    private boolean enabled = true;
    private String blockPage;
    private Map<String, DataSourcePropertiesConfiguration> datasource;
    private SentinelProperties.Transport transport;
    private SentinelProperties.Metric metric;
    private SentinelProperties.Servlet servlet;
    private SentinelProperties.Filter filter;
    private SentinelProperties.Flow flow;
    private SentinelProperties.Log log;
    private Boolean httpMethodSpecify;
}
spring cloud alibaba 2.2.1版本的SentinelProperties配置里面都没有web-context-unify这个属性啊，请问怎么生效的。 @xinmingguo-hm @sczyh30

**Comment by 2863416607** [comment]
我用了spring.cloud.sentinel.web-context-unify=false 但是还是没有用

**Comment by fuyukang** [comment]
> 我用了spring.cloud.sentinel.web-context-unify=false 但是还是没有用
        <!--引入 sentinel-web-servlet坐标，再添加spring.cloud.sentinel.web-context-unify=false就生效了->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-web-servlet</artifactId>
            <version>1.7.0</version>
        </dependency>

**Comment by Strong-bb** [comment]
总结下 　1.7.0 版本开始（对应Spring Cloud Alibaba的2.1.1.RELEASE) 需要新增依赖
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-web-servlet</artifactId>
        </dependency>
配置spring.cloud.sentinel.web-context-unify=false

新增配置   CommonFilter就在上面的依赖里
`@Configuration
public class FilterContextConfig {
    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        // 入口资源关闭聚合
        registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
        registration.setName("sentinelFilter");
        registration.setOrder(1);
        return registration;
    }
}`

**Comment by DanBrwon** [comment]
2.2.1.RELEASE
<groupId>com.alibaba.cloud</groupId>
<artifactId>spring-cloud-alibaba-dependencies</artifactId>
在这个版本中如何解决

@Configuration
public class FilterContextConfig {
    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        // 入口资源关闭聚合
        registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
        registration.setName("sentinelFilter");
        registration.setOrder(1);
        return registration;
    }
}
加入以上是好用了，但是影响到了 implements BlockExceptionHandler 重写的异常处理

**Comment by wynwy** [comment]
你们发现没有，配置
@configuration
public class FilterContextConfig {
@bean
public FilterRegistrationBean sentinelFilterRegistration() {
FilterRegistrationBean registration = new FilterRegistrationBean();
registration.setFilter(new CommonFilter());
registration.addUrlPatterns("/*");
// 入口资源关闭聚合
registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY, "false");
registration.setName("sentinelFilter");
registration.setOrder(1);
return registration;
}
}
这样虽然链路限流可以了，但是又有新的问题，一个是影响全局异常，另外最坑的就是统计次数的时候会统计两次，比如我限流的qps设置成1的话直接就无法访问了被BlockExceptionHandler处理了，设置成2的话每秒只能通过一次，也就是说你的qps也设置成原先的两倍才行，有没有别的解决办法

**Comment by wynwy** [comment]
可以了，把官方的filter关闭即可

**Comment by jianhao990611** [comment]
自己构建CommonFilter实例后发现授权规则无法使用

**Comment by 0b1to** [comment]
修改配置文件中的 spring.cloud.sentinel.filter.enabled=false，spring.cloud.sentinel.web-context-unify=false

**Comment by bluede2017** [comment]
总结：

使用的时候，链路模式不起作用

我的版本：
```
<boot.version>2.2.6.RELEASE</boot.version>
<spring-cloud.version>Hoxton.SR3</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
spring.cloud.sentinel.web-context-unify=false  找不到这个属性，也没有找不到CommonFilter类
```

解决方法1：升版本
```
<boot.version>2.3.12.RELEASE</boot.version>
<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>
使用的时候，链路模式起作用了
spring.cloud.sentinel.web-context-unify=false  可以找到这个属性，也可以找到CommonFilter类
```

解决方式2：加入sentinel-web-servlet依赖（没试，楼上说是可以的）
	<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-web-servlet</artifactId>
        </dependency>

**Comment by LillyChen** [comment]
依赖
spring-cloud-starter-alibaba-sentinel   2021.0.1.0 
sentinel-web-servlet   1.8.3
配置了FilterContextConfig 类
修改配置文件中的 spring.cloud.sentinel.filter.enabled=false，spring.cloud.sentinel.web-context-unify=false
链路模式还是不生效
