### ISSUE TITLE
sentinel控制台机器地址IP非本机IP,无法读取写入规则

### ISSUE THREAD

**Issue by BoGeManger** [alibaba/Sentinel#1214]
控制台日志：Failed to fetch metric from <http://169.254.98.37:8719/metric?startTime=1576926157000&endTime=1576926163000&refetch=false> (ConnectionException: Connection refused)

**Comment by pstree** [comment]
多网卡也不支持 . spring.cloud.inetutils.preferred-networks=172.

**Comment by pstree** [comment]
多网卡也不支持 . 没有使用spring.cloud 这样的配置  ,  spring.cloud.inetutils.preferred-networks=172.
