### ISSUE TITLE
zuul的集群流控文档

### ISSUE THREAD

**Issue by zackzhangzz** [alibaba/Sentinel#1215]
看了网关文档，集群文档，有集群流控文档么

**Comment by sczyh30** [comment]
Refer: #981

**Comment by zackzhangzz** [comment]
好的，谢谢。有zuul-adapter使用nacos的文档么

**Comment by sczyh30** [comment]
You may create your NacosDataSource instance and register via the `GatewayRuleManager.register2Property(property)` method.
