### ISSUE TITLE
com.alibaba.csp.sentinel.slotchain.SlotChainProvider#newSlotChain 问题

### ISSUE THREAD

**Issue by hellojd2018** [alibaba/Sentinel#1216]
## Issue Description

接入 Zuul 网关限流

```    
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>1.5.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
            <version>1.5.1.RELEASE</version>
        </dependency>
```

调用`SpiLoader.loadFirstInstanceOrDefault(SlotChainBuilder.class, DefaultSlotChainBuilder.class)`，
返回`HotParamSlotChainBuilder`，而不是`GatewaySlotChainBuilder`, 这导致网关限流规则无效。

确认一下，为什么会出现这个问题？而且怎么解决加载顺序问题？

开发环境

idea 2018+spring boot 版本 1.5.10-RELEASE

**Comment by sczyh30** [comment]
It's related to the order of dependencies. You may rearrange the order of dependencies and be sure the `sentinel-spring-cloud-gateway-adapter` is in the first place.

Actually this is not a good design to make `SlotChainBuilder` as the SPI and load the first-encountered implementation. We may need #411 (though compatibility should be considered).
