### ISSUE TITLE
Sentinel控制台添加限流规则失败，添加规则后无法界面没有数据

### ISSUE THREAD

**Issue by BoGeManger** [alibaba/Sentinel#1217]
Spring Cloud环境下引入spring-cloud-starter-alibaba-sentinel，并且做好相关配置
![1577169584(1)](https://user-images.githubusercontent.com/32759078/71398592-df646700-265b-11ea-9b79-22c575b3a48d.jpg)

试过docker也有同样的问题，本机IP的调用接口控制台返回setRules: success，但控制台页面均没有显示，也没有达到限流效果，但接口调用后实时监控，簇点链路都是有数据出现的，机器列表也显示机器健康，其他页面都是空的，无法限流及保存限流规则。
![1577169786(1)](https://user-images.githubusercontent.com/32759078/71398774-80ebb880-265c-11ea-9455-39472b81b98d.jpg)

**Comment by sczyh30** [comment]
Please refer to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81%E5%90%8E%E7%9C%8B%E4%B8%8D%E5%88%B0) to check whether your fastjson version is too low.

**Comment by BoGeManger** [comment]
非常感谢，就是fastjson包的问题
