### ISSUE TITLE
项目集群部署了两个实例,发送一个请求,dashboard怎么显示通过2个请求??

### ISSUE THREAD

**Issue by pengqingsong123** [alibaba/Sentinel#1220]
一、版本信息

Setinel 1.7版本

二.描述
 我是用zookeeper的push方式构建的dashboard,我让一个资源的QPS设置为2[集群],然后发送一个请求,sentinel dashboard上的实时监控里面的曲线怎么显示允许通过的是2呢???
我一秒发送2个请求,sentinel dashboard上的实时监控里面的曲线怎么显示允许通过的是4.
我一秒发送4个请求,sentinel dashboard上的实时监控里面的曲线怎么显示允许通过的是4.拒绝为2

怎么dashborad的监控的数值是实际请求的乘以2呢??????

**Comment by sczyh30** [comment]
See [the document](https://github.com/alibaba/Sentinel/wiki/%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9):

> 若需要在单台机器上运行相同服务的多个实例，则需要加入 -Dcsp.sentinel.log.use.pid=true 来保证不同实例日志的独立性，否则控制台监控计算可能会多出对应的倍数。
