### ISSUE TITLE
If the resource is called recursively, the number of threads and QPS are double-counted

### ISSUE THREAD

**Issue by zuoqi1993125** [alibaba/Sentinel#1221]
## Issue Description

If the resource is called recursively, the number of threads and QPS are double-counted

### Describe what you expected to happen
I think a single thread should only be evaluated once
### How to reproduce it (as minimally and precisely as possible)

```java
 @Test
    public void flow(){
        initFlowQpsRule();
        Entry entry = null;
// 务必保证finally会被执行
        try {
            // 资源名可使用任意有业务语义的字符串
            entry = SphU.entry("zuoqi");
            // 被保护的业务逻辑
            // do something...
            System.out.println(entry.getCurNode().curThreadNum());
            int i = atomicInteger.incrementAndGet();
            if(i == 10){
                return;
            }
            flow();
        } catch (BlockException e1) {
            // 资源访问阻止，被限流或被降级
            // 进行相应的处理操作
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
    }
```

### Tell us your environment

jdk1.8
sentinel 1.7.0

**Comment by sczyh30** [comment]
Every time you call `SphU.entry(xxx)`, it will be recorded, regardless of the invocation chain. If only single record is needed, you need to wrap `SphU.entry(xxx)` out of the loop call or recursive call, like this:

```java
try (Entry e = SphU.entry("xxx")) {
  // do your recursive invocation
} catch (BlockException e) {
 // handle the block exception here
}
```

---

每次调用 `SphU.entry(xxx)` 都会进行统计，而与当前调用链路无关；若希望只统计一次，可以把 `SphU.entry(xxx)` 包在循环调用或递归调用前面
