### ISSUE TITLE
sentinel-dashboard 能否以maven 依赖的形式引入到spring boot 项目中

### ISSUE THREAD

**Issue by Ikki-Dai** [alibaba/Sentinel#1225]
## sentinel-dashboard 能否以maven 依赖的形式引入到spring boot 项目中

Type: *feature request*

### Describe what happened (or what feature you want)
```xml
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel-dashboard</artifactId>
        </dependency>
```

### Describe what you expected to happen
 以maven 依赖的形式使用sentinel dashboard, 方便定制使用其他组件,
 比如 通过eureka 发现集群, 比如通过添加redis 的相关依赖判断 使用redis 推送限流规则
或者判断是否有Apoll 依赖
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
N/A

### Anything else we need to know?

N/A

**Comment by sczyh30** [comment]
You may refer #1453.
