### ISSUE TITLE
not show favorite button on alibaba.com

### ISSUE THREAD

**Issue by stone89son** [alibaba/Sentinel#1227]
Sometimes your website doesn't show your favorite button
On all platforms:
Windows 10, Window 7, Ubuntu 18, Firefox and chrome
, I don't understand why I can't find support directly on the website,
![Screenshot from 2019-12-26 22-33-54](https://user-images.githubusercontent.com/6795515/71478095-25265880-2831-11ea-9a92-3a6b58d17675.png)

**Comment by sczyh30** [comment]
Hi, you may contact the customer service. This repo is for Sentinel, the flow control component :)
