### ISSUE TITLE
sentinel控制台设置接口授权之后不生效

### ISSUE THREAD

**Issue by 418545106** [alibaba/Sentinel#1228]
我在sentinel上设置了授权规则
![image](https://user-images.githubusercontent.com/29942834/71510095-a1b84600-28c8-11ea-8908-2e76c05a1271.png)
之后使用浏览器访问，这个授权的黑名单并没有生效
![image](https://user-images.githubusercontent.com/29942834/71510114-b7c60680-28c8-11ea-8ee1-e0a0530d5c88.png)
我的代码是这样的
`@RestController
public class Function1 {

    private final Logger logger = LoggerFactory.getLogger(Function1.class);

    private static final String GET_SOURCE = "getSource";

    @GetMapping("hello")
    @SentinelResource(value="hello",entryType = EntryType.IN,blockHandler = "blockHandlerForGet")
    public Msg get(@RequestParam("origin") String origin){
        ContextUtil.enter("hello",origin);
        ContextUtil.exit();
        return Msg.success(origin);
    }

    public Msg blockHandlerForGet(@RequestParam("origin") String origin, BlockException ex) {

        return Msg.fail();
    }
}`

**Comment by cdfive** [comment]
使用了`SentinelResource`，配置了Spring-Aop吗
簇点链路菜单中，能否看到名称为/hello的资源
[https://github.com/alibaba/Sentinel/wiki/注解支持#spring-aop](https://github.com/alibaba/Sentinel/wiki/注解支持#spring-aop)

**Comment by 418545106** [comment]
![image](https://user-images.githubusercontent.com/29942834/71565092-d0f7ce80-2ae5-11ea-8768-90f33e40ce4a.png)
控制台中看得见链路
`
@Configuration
public class SentinelAspectConfiguration {

    @Bean
    public SentinelResourceAspect sentinelResourceAspect() {
        return new SentinelResourceAspect();
    }
}
`
并且也配置了该配置项，可是在创建了对aaa的黑名单后还是无效

**Comment by sczyh30** [comment]
Context 设置需要在进入埋点前才生效，因此如果需要的话应该在流量入口处调用 `ContextUtil.enter(contextName, origin`)。若引入了 Web filter，则需要根据 Web 适配的配置来自定义 origin 解析逻辑：https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-servlet

也可以参考 FAQ 相关内容：https://github.com/alibaba/Sentinel/wiki/FAQ
