### ISSUE TITLE
资源名称是否支持通配符的情况

### ISSUE THREAD

**Issue by aqqwiyth** [alibaba/Sentinel#123]
自定义模式下初始化

        FlowRule rule1 = new FlowRule();
        rule1.setResource("/user/**");  
        rule1.setResource("com.xxx.*");  
        rule1.setCount(20);
        rule1.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule1.setLimitApp("abc"); 

AbstractDubboFilter中 获取resourceName

      public static String getApplication(Invocation invocation, String defaultValue) {
        if (invocation == null || invocation.getAttachments() == null) {
            throw new IllegalArgumentException("Bad invocation instance");
        }
        return invocation.getAttachment(DUBBO_APPLICATION_KEY, defaultValue);
    }
   

比如rest / dubbo 中接口数量比较大, 枚举出来比较困难, 尤其是新增一个接口的时候可能会遗漏

**Comment by sczyh30** [comment]
Currently resource name pattern matching is not supported, see #66 for reasons. We may support global rules in later versions.
