### ISSUE TITLE
我请教一下1.7.1版本的sentinel-dashboard 启动起来把自己监控上了

### ISSUE THREAD

**Issue by YinYongTao** [alibaba/Sentinel#1230]
![图片](https://user-images.githubusercontent.com/26930834/71608348-93fe0b80-2bbb-11ea-8b39-7415535bbf9c.png)
按教程 java -Dserver.port=8080 \
-Dcsp.sentinel.dashboard.server=localhost:8080 \
-jar sentinel-dashboard-1.7.1.jar 
启动 sentinel-dashboard-1.7.1.jar 未接入其他服务前自己先被监控上了，好像不太对，不知道如何解决

**Comment by quanquan-dane** [comment]
@YinYongTao 您好，请问你这个问题如何解决得？
