### ISSUE TITLE
[Feature] Integration module for Quarkus

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1233]
## Issue Description

Type: *feature request*

### Describe what feature you want

Add integration module for [Quarkus](https://quarkus.io/). We may need to pay attention to whether Sentinel could be compiled under the GraalVM native-image. Discussions and contributions are welcomed!

**Comment by zhaoyuguang** [comment]
I wanna try finish it

**Comment by sczyh30** [comment]
> I wanna try finish it

Hi, any progress?

**Comment by sczyh30** [comment]
Resolved via #1541, #1542 and #1543 by @seasidesky

**Comment by sczyh30** [comment]
@seasidesky Would you like to write a blog post to introduce Quarkus adapter and publish it to Sentinel website (both English and Chinese are okay)?
