### ISSUE TITLE
sentinel-dashboard 里面发送setRules的命令请求里面的参数接收不到，改成get请求就可以接收到参数

### ISSUE THREAD

**Issue by tj771889579** [alibaba/Sentinel#1236]
SentinelApiClient类的executeCommand(String app, String ip, int port, String api, Map<String, String> params, boolean useHttpPost)方法 

sentinel依赖
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.1.1.RELEASE</version>
 </dependency>

**Comment by jasonjoo2010** [comment]
这个需要补充下app端集成的sentinel-transport* 版本和dashboard版本进一步排查

**Comment by tj771889579** [comment]
dashboard引用的parent版本:sentinel-parent 1.7.2-SNAPSHOT    sentinel-transport-simple-http版本 1.7.0

**Comment by sczyh30** [comment]
See [the document](https://github.com/alibaba/Sentinel/wiki/%E6%8E%A7%E5%88%B6%E5%8F%B0#62-%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81):

> 若通过控制台推送规则时出现 invalid type 或 empty type 的错误，请确保 transport 模块版本与 core 模块版本保持一致；若控制台版本 >= 1.7.1，请将接入端的相关依赖也升级至 1.7.1 及以上版本。

**Comment by tj771889579** [comment]
感谢，问题已解决。
spring-cloud-starter-alibaba-sentinel当前maven中央仓库https://mvnrepository.com最新版本为2.1.1.RELEASE，集成的transport 模块版本与 core 模块版本均为1.7.0，与最新的dashboard版本1.7.2不兼容，希望能够升级spring-cloud-starter-alibaba-sentinel的版本以支持最新的控制台推送规则接口

**Comment by jasonjoo2010** [comment]
不过这个backward不兼容是什么鬼。。。。。我们很久没升级了

**Comment by sczyh30** [comment]
Maybe related to #1207

**Comment by jasonjoo2010** [comment]
> Maybe related to #1207

Oh I see and find an unconformity:

`DEFAULT_CHARSET.name()`(Get) vs `Consts.UTF_8`(Post)

**Comment by sczyh30** [comment]
> Be honest i have not test the newest dashboard to old core library (Be precise we still use an alternated version based on 1.5.x). And it's relevant what the rule/input contains so it will be solved at once if a demo/data/scenario was provided. Do you have one?

_Originally posted by @jasonjoo2010 in https://github.com/alibaba/Sentinel/issues/1253#issuecomment-574618108_

It's easy to reproduce: just use the latest dashboard and publish rules (via HTTP) to the services with Sentinel < 1.7.1, then the dashboard will report "invalid type" or "empty type" error.

The `HttpEventTask` in old version mishandled the parsing logic of `Content-Type` header. When the Content-type header carries charset information (e.g. `Content-type: application/json; charset=utf-8`), it won't recognize it as valid.

**Comment by jasonjoo2010** [comment]
> > Be honest i have not test the newest dashboard to old core library (Be precise we still use an alternated version based on 1.5.x). And it's relevant what the rule/input contains so it will be solved at once if a demo/data/scenario was provided. Do you have one?
> 
> _Originally posted by @jasonjoo2010 in [#1253 (comment)](https://github.com/alibaba/Sentinel/issues/1253#issuecomment-574618108)_
> 
> It's easy to reproduce: just use the latest dashboard and publish rules (via HTTP) to the services with Sentinel < 1.7.1, then the dashboard will report "invalid type" or "empty type" error.
> 
> The `HttpEventTask` in old version mishandled the parsing logic of `Content-Type` header. When the Content-type header carries charset information (e.g. `Content-type: application/json; charset=utf-8`), it won't recognize it as valid.

Oh wait, the new dashboard began to use `JSON` format POST request? I just remember that they should only support key-value pair (form-encoded) in previous versions.

**Comment by sczyh30** [comment]
It's only an example to describe the issue. Actually we only support `application/x-www-form-urlencoded` :)

**Comment by jasonjoo2010** [comment]
> It's only an example to describe the issue. Actually we only support `application/x-www-form-urlencoded` :)

Oh i see. So i will check it later and update in this issue. It seems like we can get a way getting it fixed both side only excluding version `1.7.1`. We can revoke it on github and other places if so.

**Comment by sczyh30** [comment]
Actually #1207 did the correct things, so maybe we could just update the dashboard and add compatible handling logic for Sentinel SDK <= 1.7.0?

**Comment by jasonjoo2010** [comment]
> Actually #1207 did the correct things, so maybe we could just update the dashboard and add compatible handling logic for Sentinel SDK <= 1.7.0?

After reading some documents and references(RFC[1] and w3c[2]) but find that any properties after `;` is not supported by `x-www-form-urlencoded`. And indeed some libraries (Actually not all of them) will append it. So i think both side should be improved to avoid possible issue in future.

[1] Mime types: https://tools.ietf.org/html/rfc6838
[2] W3C: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#application-x-www-form-urlencoded-encoding-algorithm

**Comment by sczyh30** [comment]
> > Actually #1207 did the correct things, so maybe we could just update the dashboard and add compatible handling logic for Sentinel SDK <= 1.7.0?
> 
> After reading some documents and references(RFC[1] and w3c[2]) but find that any properties after `;` is not supported by `x-www-form-urlencoded`. And indeed some libraries (Actually not all of them) will append it. So i think both side should be improved to avoid possible issue in future.
> 
> [1] Mime types: https://tools.ietf.org/html/rfc6838
> [2] W3C: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#application-x-www-form-urlencoded-encoding-algorithm

If so, we could make it consistent with the RFC, but we need to improve the code to support UTF-8 characters so that it could fix #943.

**Comment by jasonjoo2010** [comment]
> > > Actually #1207 did the correct things, so maybe we could just update the dashboard and add compatible handling logic for Sentinel SDK <= 1.7.0?
> > 
> > 
> > After reading some documents and references(RFC[1] and w3c[2]) but find that any properties after `;` is not supported by `x-www-form-urlencoded`. And indeed some libraries (Actually not all of them) will append it. So i think both side should be improved to avoid possible issue in future.
> > [1] Mime types: https://tools.ietf.org/html/rfc6838
> > [2] W3C: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#application-x-www-form-urlencoded-encoding-algorithm
> 
> If so, we could make it consistent with the RFC, but we need to improve the code to support UTF-8 characters so that it could fix #943.

But i am confused about that it shouldn't work correctly even dashboard-1.7.1 vs. transport-simple-http-1.7.1 if new dashboard will send request with `Content-Type: x-www-form-urlencoed; charset=UTF-8` because of:

https://github.com/alibaba/Sentinel/blob/master/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java#L120

And i will deal with the version compatibility in another PR for `SentinelApiClient` in dashboard

**Comment by sczyh30** [comment]
> > If so, we could make it consistent with the RFC, but we need to improve the code to support UTF-8 characters so that it could fix #943.
> 
> But i am confused about that it shouldn't work correctly even dashboard-1.7.1 vs. transport-simple-http-1.7.1 if new dashboard will send request with `Content-Type: x-www-form-urlencoed; charset=UTF-8` because of:
> 
> https://github.com/alibaba/Sentinel/blob/master/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java#L120
> 
> And i will deal with the version compatibility in another PR for `SentinelApiClient` in dashboard

In 1.7.1 the charset suffix has been trimmed:

https://github.com/alibaba/Sentinel/blob/b13684887306af1012ea9d99ae4567895f3968d3/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java#L116-L119

**Comment by jasonjoo2010** [comment]
> > > If so, we could make it consistent with the RFC, but we need to improve the code to support UTF-8 characters so that it could fix #943.
> > 
> > 
> > But i am confused about that it shouldn't work correctly even dashboard-1.7.1 vs. transport-simple-http-1.7.1 if new dashboard will send request with `Content-Type: x-www-form-urlencoed; charset=UTF-8` because of:
> > https://github.com/alibaba/Sentinel/blob/master/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java#L120
> > And i will deal with the version compatibility in another PR for `SentinelApiClient` in dashboard
> 
> In 1.7.1 the charset suffix has been trimmed:
> 
> https://github.com/alibaba/Sentinel/blob/b13684887306af1012ea9d99ae4567895f3968d3/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java#L116-L119

Ok i see and the PR on transport module has been updated.
And the PR on SentinelApiClient will deal with it older than `1.7.1` (exclusive)

**Comment by sczyh30** [comment]
Fixed the compatibility via #1260
