### ISSUE TITLE
Hardcoded file separator

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/Sentinel#1239]
https://github.com/alibaba/Sentinel/blob/fe23d5c11f2e14ab8da72aa26490e74d4f7eddf3/sentinel-demo/sentinel-demo-dynamic-file-rule/src/main/java/com/alibaba/csp/sentinel/demo/file/rule/FileDataSourceInit.java#L50

The path split symbol problem is different for different operating systems. Hard-coded file separators should not be used. Instead, use a platform-independent API provided by the language library,such as java.io.File.separator or java.lang.System.getProperty("file.separator")

**Comment by sczyh30** [comment]
This can be improved. Contributions are welcomed!
