### ISSUE TITLE
怎么进行流控规则的设置，使得在10分钟内最多容许一次请求

### ISSUE THREAD

**Issue by skyail** [alibaba/Sentinel#1243]
现在的流控规则中，QPS单位是秒，也就是1秒内最多容许多少个请求。但是我们要设置的时间长度比较长，要求10分钟内只能有一次请求，下次请求要等10分钟之后，这种情况要怎么去设置流控规则呢？谢谢。

**Comment by MrXionGe** [comment]
Sentinel的流控看起来是做不了吧。
我觉得10分钟一次更偏向于业务层面的限制，而Sentinel的流控偏向于技术层面的限制。
你说的这个问题，在接口层结合redis处理一下，也不是很麻烦的。
