### ISSUE TITLE
Sentinel v1.7.1 dashboard "invalid type" error when updating flow rules

### ISSUE THREAD

**Issue by dai19470** [alibaba/Sentinel#1244]
## Issue Description

从release中下载的1.7.1版本的sentinel-dashboard.jar 启动登录后,访问一个http,修改流控规则报错

### 下面是页面截图
![image](https://user-images.githubusercontent.com/21135250/72135912-7e11f700-33c2-11ea-8abb-1cfb046959c1.png)

###下面是jdk版本
jdk:1.8.0_112

**Comment by sczyh30** [comment]
Plz refer to: https://github.com/alibaba/Sentinel/issues/1236#issuecomment-571900430
