### ISSUE TITLE
@SentinelResource annotation support setting origin

### ISSUE THREAD

**Issue by lazyfighter** [alibaba/Sentinel#1248]
user can special this for traffic from different application

`@SentinelResource` 支持配置流控应用（调用来源）

**Comment by sczyh30** [comment]
Could you please illustrate your question or requirement according to the issue template?

**Comment by sczyh30** [comment]
Do you mean flow control by different origins (callers) when using `@SentinelResource` annotation?

**Comment by lazyfighter** [comment]
yes

**Comment by sczyh30** [comment]
Hard-coding origin makes no sense. You may refer to https://github.com/alibaba/Sentinel/issues/1228#issuecomment-574468197
