### ISSUE TITLE
Sentinel push rules to Nacos

### ISSUE THREAD

**Issue by JayeShen** [alibaba/Sentinel#1249]
dubbo+springboot+sentinel+nacos这种架构如何完成sentinel持久化到nacos

**Comment by sczyh30** [comment]
Please refer to the following articles:

- https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel
- https://github.com/alibaba/Sentinel/wiki/动态规则扩展

There are also some implementations by community developers. You may also refer to [Awesome Sentinel](https://github.com/alibaba/Sentinel/blob/master/doc/awesome-sentinel.md).

**Comment by JayeShen** [comment]
Thank you very much. I have read these documents and solved my problem. I will continue to build on the architecture of dubbo+nacos+sentinel.



674644165@qq.com
 
From: Eric Zhao
Date: 2020-01-15 10:15
To: alibaba/Sentinel
CC: JayeShen; Author
Subject: Re: [alibaba/Sentinel] Sentinel push rules to Nacos (#1249)
Please refer to the following articles:
https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel
https://github.com/alibaba/Sentinel/wiki/动态规则扩展
There are also some implementations by community developers. You may also refer to Awesome Sentinel.
