### ISSUE TITLE
Can downgrading rules be applied to clusters

### ISSUE THREAD

**Issue by stalary** [alibaba/Sentinel#1250]
# Issue Description
feature request

### Describe what happened (or what feature you want)
I used k8s to deploy the service, I had to reconfigure the downgrade rule with each update

### Describe what you expected to happen
Can downgrading rules be applied to clusters

### Tell us your environment
1.7.1

**Comment by sczyh30** [comment]
Do you mean publish rules to all instances of your cluster? You may refer to [the data-source document](https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration).

**Comment by stalary** [comment]
> Do you mean publish rules to all instances of your cluster? You may refer to [the data-source document](https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration).

thanks

**Comment by stalary** [comment]
Can the dashboard support degraded configuration via zookeeper, nacos.

**Comment by sczyh30** [comment]
You may refer to [this article](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel) to refactor the dashboard.
