### ISSUE TITLE
中文介绍wiki中的笔误更正

### ISSUE THREAD

**Issue by Pengfei-Lu** [alibaba/Sentinel#1251]
https://github.com/alibaba/Sentinel/wiki/%E4%BB%8B%E7%BB%8D

中文介绍wiki中存在以下笔误，可以更正一下。

![image](https://user-images.githubusercontent.com/7485400/72318957-b70ade00-36d8-11ea-898a-3bd780dab4f3.png)

**Comment by sczyh30** [comment]
Fixed. Thanks for reporting!
