### ISSUE TITLE
TimeUtil.currentTimeMillis() 返回0的问题

### ISSUE THREAD

**Issue by chinadeng** [alibaba/Sentinel#1264]
@Test
    public  void test() throws InterruptedException {
        int i=0;
        while (i<100){

            System.out.println(TimeUtil.currentTimeMillis());
            Thread.sleep(1000);
        }
    }

在jdk 8 下 返回 一致是0

**Comment by sczyh30** [comment]
That's weird. Please check whether your test class extends [`AbstractTimeBasedTest`](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/test/AbstractTimeBasedTest.java) class, where the `TimeUtil.currentTimeMillis()` method is mocked.

**Comment by sczyh30** [comment]
Any feedback?
