### ISSUE TITLE
Doc/Wiki issue - Link

### ISSUE THREAD

**Issue by nianjiang** [alibaba/Sentinel#1266]
### Issue Description
 *bug report*
The Datasource link error is blank on this wiki:
https://github.com/alibaba/Sentinel/wiki/How-to-Use#integrate-with-rule-repositories

### Describe what happened (or what feature you want)
The Datasource link is blank， see link below：
![image](https://user-images.githubusercontent.com/21122161/72899622-5b3bf700-3d61-11ea-86b0-36199f64e821.png)

### Describe what you expected to happen
The link should be:
https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-datasource-extension/src/main/java/com/alibaba/csp/sentinel/datasource/AbstractDataSource.java

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
I've fixed it. Thanks for reporting!
