### ISSUE TITLE
com.alibaba.csp.sentinel.dashboard.client.CommandFailedException: invalid type

### ISSUE THREAD

**Issue by a120610114** [alibaba/Sentinel#1268]
我在采用springboot 集成sentinel控制台的时候，想在控制台动态修改规则的时候出现com.alibaba.csp.sentinel.dashboard.client.CommandFailedException: invalid type错误；
client端服务配置如下：
![image](https://user-images.githubusercontent.com/26463863/73136903-ca7d5800-408d-11ea-91ce-9c4ea5543b5f.png)
![image](https://user-images.githubusercontent.com/26463863/73136905-d0733900-408d-11ea-9261-d34f2a023935.png)
![image](https://user-images.githubusercontent.com/26463863/73136906-d49f5680-408d-11ea-8a69-f1b861289aab.png)

在修改请求时的截图为：
![image](https://user-images.githubusercontent.com/26463863/73136913-e97bea00-408d-11ea-99ef-578d892ba795.png)
日志zhon中也没有特别的语句就只有说  invalid type

**Comment by jasonjoo2010** [comment]
Please make sure that the application integrates sentinel-core-1.7.1 if you use the newest dashboard. This issue will be resolved in next release(Which has already been merged). 

Please refer to #1260 

请确认应用端使用的是最新版sentinel，以配合最新版的dashboard。下一版本的dashboard将解决这个问题（目前已合并）。

**Comment by a120610114** [comment]
已经是最新的了，但是还是一样的报错
![image](https://user-images.githubusercontent.com/26463863/73157242-66a17080-411b-11ea-9926-420f464c3a63.png)

**Comment by a120610114** [comment]
![image](https://user-images.githubusercontent.com/26463863/73157346-a7998500-411b-11ea-9a6a-12851687501a.png)
全部都是1.7以上了

**Comment by jasonjoo2010** [comment]
> ![image](https://user-images.githubusercontent.com/26463863/73157346-a7998500-411b-11ea-9a6a-12851687501a.png)
> 全部都是1.7以上了

需要统一为最新的1.7.1
或使用老的dashboard，不过看你目前的版本，建议全部为1.7.1

**Comment by jasonjoo2010** [comment]
> ![image](https://user-images.githubusercontent.com/26463863/73157346-a7998500-411b-11ea-9a6a-12851687501a.png)
> 全部都是1.7以上了

至于为什么1.7.0的core有问题，参见 #1255

**Comment by sczyh30** [comment]
用 dependencyManagement 统一一下版本，参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#其它)
