### ISSUE TITLE
After the console cooperates with Apollo, the console modification rule does not take effect

### ISSUE THREAD

**Issue by a120610114** [alibaba/Sentinel#1269]
Why do I use sentinel console with Apollo to modify the rules dynamically in the console? Only modification in Apollo will take effect

**Comment by sczyh30** [comment]
You may refer to these documents:

- [在生产环境中使用 Sentinel (CN)](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel)
- [Dynamic Rule Configuration](https://github.com/alibaba/Sentinel/wiki/Dynamic-Rule-Configuration)
