### ISSUE TITLE
comment in a demo class not match

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#127]
The FlowThreadDemo class in sentinel-demo-basic project:
I found the print description is the opposite, in first line of main method.
`
System.out.println(
   "MethodA will call methodB. After running for a while, methodB becomes slow, "
    + "which make methodA also becomes slow ");
`

`
if (seconds == 40) {
    System.out.println("method B is running much faster; more requests are allowed to pass");
    methodBRunningTime = 20;
}
`

Actuallly, MethodB becomes faster. 

ps: It's a really nice demo for learning and observation.

**Comment by sczyh30** [comment]
Thanks for reporting! Fixed it.
