### ISSUE TITLE
关于网关上整合了限流组件，对于微服务如何实现降级处理

### ISSUE THREAD

**Issue by witchang** [alibaba/Sentinel#1270]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
You could add degrade rules for the API gateway route or customized API groups.

**Comment by witchang** [comment]
配了降级规则，资源名用的是routeID，但是没有实现降级效果；我直接用sentinelResource定义了一个资源，降级成功


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Eric Zhao <notifications@github.com&gt;
发送时间: 2020年2月3日 14:50
收件人: alibaba/Sentinel <Sentinel@noreply.github.com&gt;
抄送: witchang <2930864981@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/Sentinel] 关于网关上整合了限流组件，对于微服务如何实现降级处理 (#1270)




You could add degrade rules for the API gateway route or customized API groups.

**Comment by jianzh5** [comment]
> 配了降级规则，资源名用的是routeID，但是没有实现降级效果；我直接用sentinelResource定义了一个资源，降级成功 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Eric Zhao <notifications@github.com&gt; 发送时间: 2020年2月3日 14:50 收件人: alibaba/Sentinel <Sentinel@noreply.github.com&gt; 抄送: witchang <2930864981@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[alibaba/Sentinel] 关于网关上整合了限流组件，对于微服务如何实现降级处理 (#1270) You could add degrade rules for the API gateway route or customized API groups. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也是遇到了这样的问题，网关层的限流不生效，但是后端微服务的限流却生效！

**Comment by sczyh30** [comment]
> 我也是遇到了这样的问题，网关层的限流不生效，但是后端微服务的限流却生效！

You may check whether it's related to #1305 and #1306
