### ISSUE TITLE
关于通过Sentinel控制台对规则的修改同步回Nacos Config中的功能？

### ISSUE THREAD

**Issue by dujunchen** [alibaba/Sentinel#1272]
目前最新版本的Sentinel控制台貌似不具备修改后的规则配置同步修改Nacos Config，是吗？后续是否会有这个功能的开发计划呢？如果在Sentinel控制台上可视化方式修改规则不能持久化到配置中心的话，那生产上Sentinel控制台的功能是不是略显鸡肋了？请教各位大佬

**Comment by sczyh30** [comment]
可以参考：[在生产环境中使用 Sentinel](https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel)

**Comment by dujunchen** [comment]
问题解决了，参考博客http://www.itmuch.com/spring-cloud-alibaba/sentinel-rules-persistence-push-mode-using-nacos/#%E5%9B%9B%E3%80%81Sentinel%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%94%B9%E9%80%A0

**Comment by J-Orange** [comment]
mark一下

**Comment by sunqb** [comment]
mark2
