### ISSUE TITLE
In the sentinel-dubbo-filter, Please add an annotation to get the resource name

### ISSUE THREAD

**Issue by leilei2018** [alibaba/Sentinel#1274]
目前SentinelDubboProviderFilter和SentinelDubboConsumerFilter获取方法的资源名称是DubboUtils#getResourceName
即根据方法名的签名去设置，可不可以添加一个@SentinelResourceName，来直接设置。

 `public static String getResourceName(Invoker<?> invoker, Invocation invocation, Boolean useGroupAndVersion) {
        StringBuilder buf = new StringBuilder(64);
        String interfaceResource = useGroupAndVersion ? invoker.getUrl().getColonSeparatedKey() : invoker.getInterface().getName();
        buf.append(interfaceResource)
            .append(":")
            .append(invocation.getMethodName())
            .append("(");
        boolean isFirst = true;
        for (Class<?> clazz : invocation.getParameterTypes()) {
            if (!isFirst) {
                buf.append(",");
            }
            buf.append(clazz.getName());
            isFirst = false;
        }
        buf.append(")");
        return buf.toString();
    }`

**Comment by cdfive** [comment]
使用注解的话，可以在代码里设置资源名称，但这样对代码有侵入性了。
各有利弊，看具体场景。

有单独的注解支持`@SentinelResource`
参考wiki文档：
[https://github.com/alibaba/Sentinel/wiki/注解支持](https://github.com/alibaba/Sentinel/wiki/注解支持)

**Comment by sczyh30** [comment]
@leilei2018 You may customize your own Dubbo adapter based on the official adapter :)

Or we can add support to register a resource name extractor that generates the resource name from Dubbo `Invocation` object.

**Comment by leilei2018** [comment]
> 
> 
> @leilei2018 You may customize your own Dubbo adapter based on the official adapter :)
> 
> Or we can add support to register a resource name extractor that generates the resource name from Dubbo `Invocation` object.

Well said,i agree
