### ISSUE TITLE
Dashboard real-time monitoring no data

### ISSUE THREAD

**Issue by stalary** [alibaba/Sentinel#1277]
## Issue Description
1.7.1 Dashboard real-time monitoring has no data when I use the 1.7.0 version of the client, but 1.6.3 has data.

### Describe what you expected to happen
Dashboard real-time monitoring has data

### Tell us your environment
1.7.1 dashboard

client: com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2.1.1.RELEASE

### Anything else we need to know?
com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2.1.0.RELEASE is normal, but 2.1.1 is not

**Comment by sczyh30** [comment]
Please check according to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查).

**Comment by sczyh30** [comment]
Any feedback?
