### ISSUE TITLE
sentinel-apache-dubbo-adapter 1.7.1 does not work for Dubbo 2.7.1

### ISSUE THREAD

**Issue by Anthony-Dong** [alibaba/Sentinel#1280]
`com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboConsumerFilter` 和`com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboProviderFilter` , 我测试这俩Filter根本没有实例化, 我maven加入依赖, 然后downloadsource. 也出现一堆报错, 不知道啥原因 . 但是降级到了1.7.0就好了, 最近在看sentinel都是1.7.1 , 但是这个dubbo限流的版本只能使用1.7.0 . 希望尽快解决版本问题.

**Comment by sczyh30** [comment]
Please provide more information (e.g. your Dubbo version, the error message in `~/logs/csp/sentinel-record.log`) according to the issue template.

**Comment by Anthony-Dong** [comment]
dubbo version : `2.7.1` , Netty version: `4.1.31.Final` . 我测试的是sentinel1.7.1-SNAPSHOT中提供的Demo. 不过本地的sentinel版本全部是1.7.1,但是flowlimit无效. 必须将sentinel-apache-dubbo-adapter降到1.7.0

**Comment by sczyh30** [comment]
sentinel-apache-dubbo-adapter 1.7.1 only supports Dubbo 2.7.2+. See #1124 for previous discussions.
