### ISSUE TITLE
sentinel-web-servlet适配器未能统计到异常数量

### ISSUE THREAD

**Issue by Alterzhang** [alibaba/Sentinel#1281]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
在项目中有全局异常处理的情况下sentinel-web-servlet适配器没有统计到相关异常数量

### How to reproduce it (as minimally and precisely as possible)

1. 在应用中发生异常时全局异常处理已经处理，web-servlet适配器未能捕获到相关异常

**Comment by xue8** [comment]
Try to throw the exception in the global handler.

**Comment by sczyh30** [comment]
If you've caught and handled the exception in your global exception handler, the Sentinel web filter will not receive the exception. You may need to `Tracer.trace(ex)` manually (under Sentinel entry context).

**Comment by guojing762** [comment]
朋友 你不处理的业务异常会自动监控统计吗?为撒我这边统计不到啊 .比如10/0  这样的业务代码 sentinel监控数据异常数 一直为0,能否有时间探讨一下,可以加我一下吗?
