### ISSUE TITLE
client连接不上sentinel-dashboard

### ISSUE THREAD

**Issue by hepyu** [alibaba/Sentinel#1285]
我使用的是sentinel最新release版本：1.7.1。

现象是，8719端口无法启动，

执行InitExecutor.doInit();报错：
ERROR: AHAS init fail, ahas.license is needed

**Comment by hepyu** [comment]
@Override
    public void init() throws Exception {
        if (!ahasInitSuccess.get()) {
            return;   **//这里就直接返回了，怎么可以忽略ahas呢？我并不用它。**
        }
        // do not print stack trace when logger not found for ACM.
        LogLog.setQuietMode(true);
        // Set current process configuration id.
        MachineUtils.setCurrentProcessConfigurationId(clientInfoService.getAid());

        SentinelAcmDataSourceService acmDataSourceService = new SentinelAcmDataSourceService(clientInfoService);
        acmDataSourceService.initAcmDataSource();
        initSentinel();
    }

**Comment by hepyu** [comment]
把ahas-sentinel-client引用注释掉就可以了，否则会自动连ahas。

**Comment by sczyh30** [comment]
引入 AHAS 依赖默认连接 AHAS 控制台。接入文档参考：https://help.aliyun.com/document_detail/131232.html
