### ISSUE TITLE
Is this branch dashboard/en still updated in near future?

### ISSUE THREAD

**Issue by yuan-dong-li** [alibaba/Sentinel#1286]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

The branch dashboard/en is not updated since 18 months ago.

### Describe what you expected to happen

We are looking for up-to-date version of dashboard in English.

### How to reproduce it (as minimally and precisely as possible)

I don't find latest dashboard 1.6.3 supports English UI by default.

### Tell us your environment

Testing

**Comment by sczyh30** [comment]
The latest version is 1.3.0-en. We may update the English dashboard later.

Also refer to #1267 and #180
