### ISSUE TITLE
API gateway flow control ApiDefinition parse failed

### ISSUE THREAD

**Issue by dcy421** [alibaba/Sentinel#1289]
这是在代码中获取配置截图
![image](https://user-images.githubusercontent.com/20309960/74602228-75a78d00-50e1-11ea-8f2d-2e08a3a421a0.png)

这是nacos的配置信息
![image](https://user-images.githubusercontent.com/20309960/74602230-7b04d780-50e1-11ea-9759-26556109d3e1.png)

无法获取到predicateItems的信息？

**Comment by dcy421** [comment]
使用如下方式就可以
![image](https://user-images.githubusercontent.com/20309960/74602251-b6070b00-50e1-11ea-82fb-4b533ddb3382.png)

**Comment by dcy421** [comment]
版本
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.7.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
            <version>1.7.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.csp</groupId>
                    <artifactId>sentinel-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.alibaba.csp</groupId>
                    <artifactId>sentinel-parameter-flow-control</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>1.7.1</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-parameter-flow-control</artifactId>
            <version>1.7.1</version>
        </dependency>

**Comment by dcy421** [comment]
![image](https://user-images.githubusercontent.com/20309960/74602371-afc55e80-50e2-11ea-8921-dcddd21a5907.png)

**Comment by sczyh30** [comment]
参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) 及 `~/logs/csp/sentinel-record.log` 判断是否有加载到规则。

**Comment by dcy421** [comment]
![image](https://user-images.githubusercontent.com/20309960/74616447-be535a80-5162-11ea-9e5f-00c35d59853e.png)
![image](https://user-images.githubusercontent.com/20309960/74616455-cb704980-5162-11ea-94e1-4b0a0c245b2a.png)
![image](https://user-images.githubusercontent.com/20309960/74616465-d7f4a200-5162-11ea-9272-937167c78b0a.png)

你好 在所有的日志中以及得到nacos配置中心的心里了  但是在NacosDataSource类中，NacosDataSource.this.parser.convert(configInfo); 此方法中无法解析对应的对象，导致注册失败。

失败代码：
ReadableDataSource<String, Set<ApiDefinition>> apiDefinitionDataSource = new NacosDataSource<>(remoteAddress, "DEFAULT_GROUP", "api.json",
                source -> JSON.parseObject(source, new TypeReference<Set<ApiDefinition>>() {
                }));
        GatewayApiDefinitionManager.register2Property(apiDefinitionDataSource.getProperty());

**Comment by sczyh30** [comment]
Maybe related to #1119. You may refer to the solution in https://github.com/alibaba/Sentinel/issues/1119#issuecomment-547391231

**Comment by dcy421** [comment]
已解决 谢谢

**Comment by ameizi** [comment]
好坑
