### ISSUE TITLE
Gateway flow is not displayed in the dashboard

### ISSUE THREAD

**Issue by joeyjoker** [alibaba/Sentinel#1290]
Issue Description

Gateway flow is not displayed in the dashboard, but rules are work fine.

### How to reproduce it (as minimally and precisely as possible)

1. Config gateway flow in the application.yml by using nacos as datasource
2. start apps.
3. gateway flow is not displayed in the dashboard, but rules are work.

application.yml ->
spring:
  application:
    name: gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8099
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: gateway-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
      zuul:
        order:
          pre: 10000
          post: 1000
          error: -1
      filter:
        enabled: false 

rules in the nacos config ->
[
  {
  "resource": "user",
  "resourceMode": 0,
  "grade": 1,
  "count": 1,
  "intervalSec": 1,
  "controlBehavior": 0,
  "burst": 0,
  "paramItem": {
    "parseStrategy": 0
    }
  },
  {
    "resource": "httpbin_route",
    "count": 0,
    "paramItem": {
      "parseStrategy": 3,
      "fieldName": "name"
    }
  }
]

### Tell us your environment
spring boot 2.0.2.RELEASE
spring cloud Finchley.RC2
spring clound alibaba 2.0.1.RELEASE

dependency:
<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
<artifactId>sentinel-datasource-nacos</artifactId>
<artifactId>sentinel-zuul-adapter</artifactId>
 <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>

### Anything else we need to know?
Note. when call the open api http://localhost:8719/gateway/getApiDefinitions and http://localhost:8719/getRules?type=flow are both empty array.

**Comment by cdfive** [comment]
To get gateway rule, try this open api:
[http://localhost:8719/gateway/getRules](http://localhost:8719/gateway/getRules)

And maybe you need to add the `zuul` dependency explicitly.
```xml
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
  <version>2.0.0.RC2</version>
</dependency>
```

**Comment by sczyh30** [comment]
Also refer https://github.com/alibaba/Sentinel/issues/1262#issuecomment-576968262

**Comment by joeyjoker** [comment]
> To get gateway rule, try this open api:
> http://localhost:8719/gateway/getRules
> 
> And maybe you need to add the `zuul` dependency explicitly.
> 
> ```
> <dependency>
>   <groupId>org.springframework.cloud</groupId>
>   <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
>   <version>2.0.0.RC2</version>
> </dependency>
> ```

I have added the zuul dependency and called http://localhost:8719/gateway/getRules api also result empty array.

**Comment by joeyjoker** [comment]
> Also refer [#1262 (comment)](https://github.com/alibaba/Sentinel/issues/1262#issuecomment-576968262)

@sczyh30 hi, I have checked [#1262 (comment)](https://github.com/alibaba/Sentinel/issues/1262#issuecomment-576968262)
I have added spring-cloud-alibaba-sentinel-gateway dependency and added VM property -Dcsp.sentinel.app.type=1
![企业微信截图_15819894947458](https://user-images.githubusercontent.com/16460728/74696158-8535eb80-5231-11ea-997f-b5a394c9464d.png)

**Comment by joeyjoker** [comment]
![aaa](https://user-images.githubusercontent.com/16460728/74696316-14430380-5232-11ea-9f13-71ab766198e4.png)

**Comment by sczyh30** [comment]
Could you please view the latest log of your gateway in `~/logs/csp/sentinel-record.log.xxx` and check whether there are some problems?

**Comment by joeyjoker** [comment]
> Could you please view the latest log of your gateway in `~/logs/csp/sentinel-record.log.xxx` and check whether there are some problems?

@sczyh30 i found NPE in the sentinel-record.log.
2020-02-18 09:39:20.196 WARNING [SimpleHttpHeartbeatSender] Failed to send heartbeat to hosts.url.sentinel/127.0.0.1:8099 : 
java.lang.NullPointerException
	at com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender.sendHeartbeat(SimpleHttpHeartbeatSender.java:73)
	at com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc$1.run(HeartbeatSenderInitFunc.java:91)

Note. my start up command java -Dserver.port=8099 -Dcsp.sentinel.dashboard.server=localhost:8099 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.7.0.jar

**Comment by joeyjoker** [comment]
@sczyh30 i restart sentinel dashboard and it works.
![bbb](https://user-images.githubusercontent.com/16460728/74696811-d941cf80-5233-11ea-9073-e4c86e806bf7.png)

thank you for your help.
Could u help check the exception in the sentinel-record.log

**Comment by cdfive** [comment]
[https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-zuul-example](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-zuul-example)
