### ISSUE TITLE
请问sentinel-dashboard修改动态数据源为Apollo后，在控制台创建流控规则后，客户端请求接口限流失效，控制台也没报错

### ISSUE THREAD

**Issue by mycode2** [alibaba/Sentinel#1291]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you provide more information according to the issue template?

**Comment by mycode2** [comment]
这是sentinel控制台发布到Apollo上的配置，客户端的配置是
##Sentinel 控制台地址
spring.cloud.sentinel.transport.dashboard=localhost:8080
##客户端监控API的端口
#spring.cloud.sentinel.transport.port=8719
spring.cloud.sentinel.transport.client-ip=192.168.***.***
但是访问客户端的接口限流不生效

**Comment by sczyh30** [comment]
Please check according to the [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ).
