### ISSUE TITLE
General loggers support out-of-box

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#1295]
## Issue Description

Feature request: Should general loggers such as slf4j, logback, log4j2, log4j, or even console, file be supported as out-of-box modules in favor of the new feature of SPI support has been introduced? 

Please refer to #1265 

### Describe what you expected to happen

- [x] sentinel-logging-extension-slf4j (#1339)
- ~~sentinel-logging-extension-logback (#1340)~~

And more... Contributions are welcomed!

**Comment by sczyh30** [comment]
Closing this issue as we've already had [sentinel-logging-slf4j](https://github.com/alibaba/Sentinel/tree/master/sentinel-logging/sentinel-logging-slf4j) since 1.7.2.
