### ISSUE TITLE
 Can't link to the dashboard

### ISSUE THREAD

**Issue by chenshun00** [alibaba/Sentinel#130]
## Issue Description
According to the documentation, the dashboard is started normally. then i start a springboot project ,i find it can't link to the console.

I have read the documentation of the console more than twice 😭 

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
According to the normal situation described in the documentation, the machine list should have `2 machines` . But the result shows that there is `only one`

### How to reproduce it (as minimally and precisely as possible)

Start dashbord

```
➜  csp lsof -i:8080
COMMAND     PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    17762 chenshun  128u  IPv6 0x69b2675bbea1cab9      0t0  TCP localhost:65130->localhost:http-alt (CLOSE_WAIT)
java      18999 chenshun   80u  IPv6 0x69b2675bb4b21d39      0t0  TCP *:http-alt (LISTEN)
➜  csp ps -ef | grep java | grep 18999
  501 18999 18604   0 10:03上午 ttys001    9:00.94 /usr/bin/java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar
```

2. Add dependency to pom.xml 

```
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>0.1.1</version>
        </dependency>
```

3. Atart other springboot project

```
 java -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=springboot -Dcsp.sentinel.api.port=12345  -jar springboot-0.0.1-SNAPSHOT.jar 
```

4. Active client by curl

```
 curl -d 'name=1&age=11' 'http://127.0.0.1:10068/hello'
```

5. Result 

```
➜  csp lsof -i:12345
➜  csp
```

### Tell us your environment
os : `uname -a`
```
Darwin tes.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

java : `java -version`
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by chenshun00** [comment]
log
```
➜  csp lsof -i:10068
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    23991 chenshun   28u  IPv6 0x69b2675bc75004f9      0t0  TCP *:10068 (LISTEN)
➜  csp cat record.log.pid23991.2018-09-06
2018-09-06 14:50:35 app name resolved: springboot
➜  csp
```

**Comment by sczyh30** [comment]
Hi, are there any errors shown in your `${user.home}/logs/csp/record.log` and `metricStat.log.pidxxx` file for your Spring Boot application (not for Dashboard)? If successful, the corresponding `metricStat.log` will show the port of command center.

**Comment by sczyh30** [comment]
And what integration are you using (e.g. Sentinel Web Servlet Filter or Sentinel Dubbo Adapter or Spring Cloud Sentinel Starter)?

**Comment by chenshun00** [comment]
Unfortunately, there are no more log files
```
➜  csp ll metricStat*
-rw-r--r--  1 chenshun  staff   182K  9  6 15:14 metricStat.log.pid18999.2018-09-06
-rw-r--r--  1 chenshun  staff     0B  9  6 15:14 metricStat.log.pid18999.2018-09-06.lck
➜  csp
```

**Comment by chenshun00** [comment]
hi , not anything , just and the dependency

**Comment by sczyh30** [comment]
You need to add corresponding dependency to enable integration with Sentinel for frameworks and libraries. For example, you can refer to [Spring Cloud Sentinel Starter](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/readme-zh.md) for integrations with Spring Boot/Spring Cloud.

**Comment by chenshun00** [comment]
👍 i have fix it  , like this

```
@Configuration
public class SentinelAspectjConfiguration {
    @Bean
    public SentinelResourceAspect sentinelResourceAspect() {
        return new SentinelResourceAspect();
    }
}
```

add  `annotation     @SentinelResource("hello")` to resource , There is a `10 second delay`

**Comment by sczyh30** [comment]
You can also manually wrap with `SphU.entry(xxx)`, see [here](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E5%AE%9A%E4%B9%89%E8%B5%84%E6%BA%90).
