### ISSUE TITLE
Dubbo部署Sentinel客户端问题咨询

### ISSUE THREAD

**Issue by momoco530** [alibaba/Sentinel#1300]
在业务侧引入了Sentinel的客户端jar包，如下
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-core</artifactId>
			<version>1.6.3</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-dubbo-adapter</artifactId>
			<version>1.6.3</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-transport-simple-http</artifactId>
			<version>1.6.3</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-parameter-flow-control</artifactId>
			<version>1.6.3</version>
		</dependency>
启动时使用参数如下
-Dproject.name=docker-demo -Dcsp.sentinel.dashboard.server=192.168.137.135:8089

启动后调用服务，dashboard上不显示任何信息
还缺少什么配置么?

**Comment by sczyh30** [comment]
Please refer to the FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ

**Comment by nihao12358** [comment]
> Please refer to the FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ

没有解决
