### ISSUE TITLE
1.7.1 dashboard publish flow rule CommandFailedException: invalid type

### ISSUE THREAD

**Issue by zhangkun25** [alibaba/Sentinel#1301]
1.7.1的源码下载到本地启动后，新增流控规则，填写完成后点击新增，报错不能新增，具体出错代码为

com.alibaba.csp.sentinel.dashboard.controller.FlowControllerV1#publishRules

publishRules(entity.getApp(), entity.getIp(), entity.getPort()).get(5000, TimeUnit.MILLISECONDS);

**Comment by sczyh30** [comment]
Please provide more information (e.g. the error message).

**Comment by zhangkun25** [comment]
com.alibaba.csp.sentinel.dashboard.client.CommandFailedException: invalid type

**Comment by zhangkun25** [comment]
org.apache.http.impl.nio.client.CloseableHttpAsyncClient#execute(org.apache.http.client.methods.HttpUriRequest, org.apache.http.protocol.HttpContext, org.apache.http.concurrent.FutureCallback<org.apache.http.HttpResponse>){
      target = determineTarget(request);//报错语句，提示source code dose not match the bytecode
}

**Comment by sczyh30** [comment]
Refer: #1244 and #1236

**Comment by sczyh30** [comment]
You may try the dashboard in `master` branch.
