### ISSUE TITLE
在swarm环境下部署集群降级服务，出现Client注册到token server的IP非容器本身IP的问题

### ISSUE THREAD

**Issue by kanghouchao** [alibaba/Sentinel#1302]
## Issue Description
我个人的demo代码放在[这里](https://github.com/kanghouchao/devops)

我参照官方文档，搭建了一个demo，在README中大致说明了启动服务的步骤

我打算在我的devops-client-web模块中使用集群流控，参照官方样例代码在[SentinelAspectConfiguration](https://github.com/kanghouchao/devops/blob/master/devops-client/devops-client-web/src/main/java/com/kanghouchao/study/devops/client/config/SentinelAspectConfiguration.java)类配置了集群服务端的相关连接信息

启动服务后访问token-server对应的地址：/cluster/server/info
`
{"port":11111,"appName":"app","connection":[{"connectedCount":2,"connectionSet":[{"address":"10.0.9.48:47602","host":"10.0.9.48"},{"address":"10.0.9.46:52554","host":"10.0.9.46"}],"namespace":"devops-client"},{"connectedCount":0,"connectionSet":[],"namespace":"default"}],"transport":{"idleSeconds":600,"port":11111},"requestLimitData":[{"maxAllowedQps":30000.0,"namespace":"devops-client","currentQps":0.0},{"maxAllowedQps":30000.0,"namespace":"default","currentQps":0.0}],"namespaceSet":["devops-client","default"],"embedded":false,"flow":{"exceedCount":1.0,"intervalMs":1000,"maxAllowedQps":30000.0,"maxOccupyRatio":1.0,"namespace":"default","sampleCount":10}}`

问题是：此Json信息中的Client的IP和实际的IP不一致，上述Json中的IP为物理机中docker 的负载均衡IP

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 需要搭建一个docker镜像仓库用于存储构建的镜像
2. 执行脚本顺序init.sh -> build-push.sh -> stack-devops.sh
3. compose文件是devops-compose.yml

### Tell us your environment
本地电脑是ubuntu19
其中跑了三台centos虚拟机，搭建的swarm集群

**Comment by kanghouchao** [comment]
集群降级的token-server 采用的是单独部署模式

**Comment by liangyuanpeng** [comment]
这是docker swarm下的一个问题, 在 docker swarm中重写了IP,所以在业务代码中获取到的IP都是docker swarm中的容器IP, 如果想获取真实IP思路是这样的：  

在 docker swarm外加一层代理, 例如nginx的配置:    

```
location / {
        proxy_pass http://gateway:9011;
        proxy_set_header  Host   $host;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size  100m;
        #root   /usr/share/nginx/html;
        #index  index.html index.htm;
    }
```    
而后在业务代码中通过 header `` X-Real-IP``来获取真实IP  

具体情况可见swarm的issue [Unable to retrieve user's IP address in docker swarm mode](https://github.com/moby/moby/issues/25526)
