### ISSUE TITLE
使用nacos配置限流规则，类型为gw-flow，规则生效但控制台显示异常

### ISSUE THREAD

**Issue by billytomato** [alibaba/Sentinel#1305]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
问题现象同#1262（my problem is like #1262）
已添加gateway依赖（has added the spring-cloud-alibaba-sentinel-gateway dependency）

### how I fixed
当添加主动注册时spring.cloud.sentinel.eager=true，问题出现，控制台不能显示为gateway（when I added spring.cloud.sentinel.eager=true ,the problem happened，the  sentinel dashboard does not display my Service as gateway）
去掉时，sentinel显示正常（when I remove that，the sentinel dashboard display my Service as gateway）

**Comment by fangjian0423** [comment]
related https://github.com/alibaba/spring-cloud-alibaba/issues/875.
