### ISSUE TITLE
Slot Chain 加载顺序问题导致网关限流规则不生效

### ISSUE THREAD

**Issue by stelin** [alibaba/Sentinel#1306]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

spring cloud 2.2.0 对接 sentinel 1.7.1，限流功能无效

### Describe what you expected to happen

spring cloud 2.2.0 对接 sentinel 1.7.1，能正常限制请求流量

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by stelin** [comment]
```
for (T instance : serviceLoader) {
                if (instance.getClass() != defaultClass) {
                    return instance;
                }
            }
```

查了下好像是这里没有始化网关的

**Comment by cdfive** [comment]
Sentinel网关限流规则会转换为热点规则，看上去是依赖项少了。
检查下项目的依赖项里是否有`sentinel-parameter-flow-control`模块。

如果使用SCA的`spring-cloud-alibaba-sentinel-gateway`，因为它同时集成了zuul和spring cloud gateway，这两个依赖是可选的(optional)，需要使用方显示地加上依赖。如使用spring cloud gateway，加上依赖`spring-cloud-starter-gateway`。

**Comment by sczyh30** [comment]
具体加载到了哪个 slot chain？贴一下所有引的 Spring Cloud Alibaba 和 Sentinel 相关的依赖。

**Comment by stelin** [comment]
已经定位问题，临时接了下，问题是SPI加多个载顺序问题

**Comment by chenhan999** [comment]
Hi 请教一下 集成spring cloud gateway之后，流控规则是如何持久化呢？

**Comment by dlhf** [comment]
流控规则持久化，我看了下，应该是和之前一样的，继续加DynamicRuleProvider DynamicRulePublisher，改GatewayApiController，GatewayFlowRuleController

**Comment by chenhan999** [comment]
> 流控规则持久化，我看了下，应该是和之前一样的，继续加DynamicRuleProvider DynamicRulePublisher，改GatewayApiController，GatewayFlowRuleController

在2个controller中都没有发现DynamicRuleProvider  、DynamicRulePublisher 相关的引用呢

**Comment by chenhan999** [comment]
> 流控规则持久化，我看了下，应该是和之前一样的，继续加DynamicRuleProvider DynamicRulePublisher，改GatewayApiController，GatewayFlowRuleController

浏览了一下，是需要自己改造一个类似FlowControllerV2 的GatewayFlowRuleControllerV2类是吧？请问下，您那边之前有改造过吗，方便提供一份吗？

**Comment by dlhf** [comment]
@chenhan999 https://gitee.com/dlhf/phoenix/tree/master/soft/Sentinel-1.7.1/sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/controller/gateway

**Comment by tanaduus** [comment]
> 已经定位问题，临时接了下，问题是SPI加多个载顺序问题，钉钉上面详细回复了

请问怎么解决的。难道要等下个版本么

**Comment by tanaduus** [comment]
> > 已经定位问题，临时接了下，问题是SPI加多个载顺序问题，钉钉上面详细回复了
> 
> 请问怎么解决的。难道要等下个版本么

CtSph的chainMap是包隔离的。无法从外部添加一个GatewayFlowSlot。。。

**Comment by tanaduus** [comment]
我在自己的项目META-INF/services里面加了一个自己的SlotChainBuilder(复制于GatewaySlotChainBuilder)，期待ServiceLoader的迭代顺序能早于HotParamSlotChainBuilder，结果果然成功了，网关流控也生效了。不过我的办法还是很怪异，希望有最新的版本修正这个问题。

**Comment by sczyh30** [comment]
Refer #411 and #1308. Closing this issue as it will be improved in 1.7.2.
