### ISSUE TITLE
关于自定义限流处理逻辑中的坑

### ISSUE THREAD

**Issue by lijhua** [alibaba/Sentinel#131]
在wiki中有这样一句描述

**【自定义限流触发后，默认的处理逻辑是抛出异常。 如果需要自定义处理逻辑，填写@SentinelResource注解的blockHandler和blockHandlerClass属性，指定后会去blockHandlerClass类里找对应的blockHandler静态方法】**

但是这里并没有说明这个自定义静态方法的返回值类型与原始方法(originMethod)返回值之间的关系，坑就在这里，而且给的demo里正好就是这个坑，在sentinel-example中，hello方法的返回值是String类型，而自定义处理类ExceptionUtil中的静态方法blockHandler返回void，所以调试过程中发现，会抛出下面的异常信息

**【Cannot find static method [blockHandler] in class [org.springframework.cloud.alibaba.cloud.examples.ExceptionUtil] with parameters [class com.alibaba.csp.sentinel.slots.block.BlockException]】**

定位这个异常信息，发现在SentinelResourceAspect这个类的
```java
private Method findMethod(boolean mustStatic, Class<?> clazz, String name, Class<?> returnType,
                              Class<?>... parameterTypes)
```
方法返回null，经过跟踪，定位原因在returnType.isAssignableFrom(method.getReturnType()) 这个判断
这个isAssignableFrom是一个native方法，个人理解，只有a,b两个对象具有父子继承类或者接口关系或者二者完全相同的情况下才返回true吧，也就是说自定义异常处理方法的返回值和原始方法的返回值要么是父子关系，要么是同类型，不知道个人理解的是否正确，希望wiki中能把这个问题修改过来

**Comment by lijhua** [comment]
@sczyh30  The link to the  wiki in my description :

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/readme-zh.md

It should be updated

**Comment by sczyh30** [comment]
Thanks for reporting! We'll update the document for it soon.
