### ISSUE TITLE
sentinel-dashboard1.7.1机器健康状态不对

### ISSUE THREAD

**Issue by wensuliang** [alibaba/Sentinel#1312]
1.实时监控和链路数据正常
2.看日志没有连接不上的报错
3.机器上测试网络连接通的
![image](https://user-images.githubusercontent.com/8373762/75756457-a9361880-5d6b-11ea-9996-2a96c556a290.png)

**Comment by sczyh30** [comment]
这个控制台字段看起来对不上，像是很老的版本了，试一下最新版本。

**Comment by wensuliang** [comment]
是版本的问题 控制台页面缓存比较乱 某些页面是新的 某些页面是老的
