### ISSUE TITLE
Spring-Cloud-Alibaba-Sentinel config "web-context-unify " properties doesn't work，URL取消收敛设置无效，导致链路流控无效

### ISSUE THREAD

**Issue by cmygit** [alibaba/Sentinel#1313]
## Issue Description

Type: **bug report**

### Describe what happened
**According to** #1213
![image](https://user-images.githubusercontent.com/29950541/75761865-c02d3880-5d74-11ea-8f24-e851240ea1a2.png)

**It doesn't work,the urls still unify.** 
![image](https://user-images.githubusercontent.com/29950541/75762808-3ed6a580-5d76-11ea-8e4c-206c8576c748.png)

**My config** 
![image](https://user-images.githubusercontent.com/29950541/75761181-96274680-5d73-11ea-9e1a-3046447dbf95.png)

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/29950541/75762808-3ed6a580-5d76-11ea-8e4c-206c8576c748.png)

### Tell us your environment
**@SentinelResource("common")**
![image](https://user-images.githubusercontent.com/29950541/75761383-f3bb9300-5d73-11ea-882c-f4f6a5a6a621.png)

**test endpoint**
![image](https://user-images.githubusercontent.com/29950541/75761495-26658b80-5d74-11ea-81fe-ad3448e60ba0.png)

**sca version is 2.1.1.RELEASE**
![image](https://user-images.githubusercontent.com/29950541/75761582-47c67780-5d74-11ea-9cb9-fe664e8cb68e.png)

**sentinel dashboard version is 1.7.1**
![image](https://user-images.githubusercontent.com/29950541/75763165-ce7c5400-5d76-11ea-88f4-a97fd2ec6f10.png)

**spring config,application.yml**
![image](https://user-images.githubusercontent.com/29950541/75761181-96274680-5d73-11ea-9e1a-3046447dbf95.png)

**Comment by sczyh30** [comment]
This parameter is not supported in v2.1.1.RELEASE. You may refer to https://github.com/alibaba/Sentinel/issues/1213#issuecomment-568361428

**Comment by sczyh30** [comment]
Actually the newer versions do not support it as well, because it has not been supported yet in [sentinel-spring-webmvc-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter). Refer #1314

**Comment by sczyh30** [comment]
This has been supported in #1328 by @cdfive. This will also be supported in Spring Cloud Alibaba later. @fangjian0423

**Comment by sczyh30** [comment]
Resolved via https://github.com/alibaba/spring-cloud-alibaba/pull/1433
