### ISSUE TITLE
Java version to build?

### ISSUE THREAD

**Issue by olof-nord** [alibaba/Sentinel#1315]
## Java version question

*feature request*

### Describe what happened (or what feature you want)
When building sentinel-core with Java 1.7 as specified in the sentinel-parent POM and the readme, some dependencies fails as they depend on Java 1.8.

### Describe what you expected to happen
That the build would not fail.

### How to reproduce it (as minimally and precisely as possible)

1. checkout Sentinel repository
2. Set java version to 1.7
3. Run `mvn clean install`

### Tell us your environment
`mvn -v`

Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_241, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

**Comment by olof-nord** [comment]
absolutely.

`mvn -v`:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.7.0_80, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```

It fails at `sentinel-datasource-redis`.

[log.txt](https://github.com/alibaba/Sentinel/files/4288156/log.txt)

**Comment by sczyh30** [comment]
Hi, though the fundamental modules of Sentinel (e.g. core, transport-common) are targeted on JDK 1.7, there are some modules (some adapter modules, dashboard, demo) that require JDK 1.8. So if you're building the whole project, you have to build it with JDK 1.8, but the compiled jars of the fundamental modules are still for 1.7.

**Comment by jasonjoo2010** [comment]
> absolutely.
> 
> `mvn -v`:
> 
> ```
> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
> Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
> Java version: 1.7.0_80, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre
> Default locale: de_DE, platform encoding: UTF-8
> OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
> ```
> 
> It fails at `sentinel-datasource-redis`.
> 
> [log.txt](https://github.com/alibaba/Sentinel/files/4288156/log.txt)

I have check related modules and found several modules may require java8 because they depend on some new libraries(`lettuce-core` in your case).

So some modules are based on java7 and others are based on java8 or newer. You can decide your own project's setting according to which ones you have introduced.

**Comment by olof-nord** [comment]
I created a pull request as to clarify that Java 8 is the required Java version.
