### ISSUE TITLE
疑问 关于如果url路径为/order/test1 在sentinel 中无法显示  只有路径为 /xxx  这种单层路径才会显示

### ISSUE THREAD

**Issue by donblack01** [alibaba/Sentinel#1318]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
疑问 关于如果url路径为/order/test1 在sentinel 中无法显示  只有路径为 /xxx  这种单层路径才会显示
我google过  没找到有同类问题的人
### Describe what you expected to happen
![I8K%J4ELXQTY`95PMB5 S}O](https://user-images.githubusercontent.com/21120018/75966785-dae2e700-5f05-11ea-9c05-f23832080bbd.png)

![GNDCYC6OS}1B)P4EGHRU8Z7](https://user-images.githubusercontent.com/21120018/75963288-2abeaf80-5f00-11ea-9a17-5d038afc3b1e.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
java环境 为 jdk 11
![GNDCYC6OS}1B)P4EGHRU8Z7](https://user-images.githubusercontent.com/21120018/75966699-b8e96480-5f05-11ea-94dd-78066b64e2cd.png)

**Comment by sczyh30** [comment]
请确保对应的 URL 有被访问过，簇点链路页面 只能看到访问过的埋点。

**Comment by donblack01** [comment]
> 请确保对应的 URL 有被访问过，簇点链路页面 只能看到访问过的埋点。

我已经找到解决办法了 算是  2.2版本的一个bug 吧
spring:
  cloud:
    sentinel:
      filter:
        url-patterns: /**

已经有人提交 pull request 并且通过
