### ISSUE TITLE
控制台服务列表和文档完善问题

### ISSUE THREAD

**Issue by zhaowenlei** [alibaba/Sentinel#132]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 控制台服务列表，服务显示不够准确，有的服务已经退出，但是列表还是显示
2. spring dubbo 项目接入控制台，不光是引入两个jar包和jvm加参数，还要调用InitExecutor.doInit();此方法，希望文档完善再文档里面
3.

**Comment by sczyh30** [comment]
Duplicate with #133, closing this.
