### ISSUE TITLE
Nginx反向代理Sentinel后，接口直接访问到域名根目录，响应404

### ISSUE THREAD

**Issue by MyAlic** [alibaba/Sentinel#1327]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MyAlic** [comment]
静态文件使用相对路径导致这个问题

**Comment by sczyh30** [comment]
Could you please illustrate how to reproduce the problem?

**Comment by chengleqi** [comment]
这个问题解决了吗 我也是反向代理失败

**Comment by designer-framework** [comment]
没有解决，我是代理了两层才出现的问题。如果是代理一层应该没问题的。他强制跳转到当前项目路径，而不是代理两层后的路径。解决办法的话，我想应该是在前端代码的请求路径上加一个统一的代理前缀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chengleqi <notifications@github.com&gt;
发送时间: 2020年5月6日 11:22
收件人: alibaba/Sentinel <Sentinel@noreply.github.com&gt;
抄送: Designer <742743697@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/Sentinel] Nginx反向代理Sentinel后，接口直接访问到域名根目录，响应404 (#1327)
