### ISSUE TITLE
How to do flow control when the amount of resource entries exceed 6000?

### ISSUE THREAD

**Issue by fishno7** [alibaba/Sentinel#1329]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
1. 网关系统，存在限流资源可能超过6000的情况，如何处理

**Comment by sczyh30** [comment]
It's highly not recommended to have too many resources, as it will bring enormous memory footprint. You may need to unify the resource name by yourself. If you're using gateway flow control, please note that it **does not work for URL resources**.
