### ISSUE TITLE
控制台服务列表，服务显示不够准确，文档不够清晰

### ISSUE THREAD

**Issue by zhaowenlei** [alibaba/Sentinel#133]
1. 控制台服务列表，服务显示不够准确，有的服务已经退出，但是列表还是显示
2. spring dubbo 项目接入控制台，不光是引入两个jar包和jvm加参数，还要调用InitExecutor.doInit();此方法，希望文档完善再文档里面

**Comment by sczyh30** [comment]
For 1, machine will be marked as *disconnected* in machine page when there is no heartbeat received for 5 min, but the application will not be removed from the list as users may want to see history data.

For 2, you don't have to call `InitExecutor.doInit()` manually. See [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#sentinel-核心功能相关).
