### ISSUE TITLE
Can not get real client IP in the gateway adapter

### ISSUE THREAD

**Issue by yufan022** [alibaba/Sentinel#1331]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
In the gateway adapter can not get a real client IP.
![image](https://user-images.githubusercontent.com/30121694/76401356-b7fc7b00-63bc-11ea-89b4-8d48ea771eb3.png)

When I choose client ip to limit gateway rate, i review the code like this:
![image](https://user-images.githubusercontent.com/30121694/76399110-0ad43380-63b9-11ea-8430-3799487c577d.png)

There use `exchange.getRequest().getRemoteAddress();` to get client address.
If the request comes from a reverse proxy, this method can not get a real client IP.
How can i get the real client address from the request header 'X-Forwarded-For'?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
You may leverage the `Header` request item to extract the IP from `X-Forwarded-For` header.

Please also note that the gateway flow rule does not take effect for normal Web URL resources.

**Comment by yufan022** [comment]
> You may leverage the `Header` request item to extract the IP from `X-Forwarded-For` header.

 I mean the gateway-adapter not suport get client IP by X-Forwarded-For?

> Please also note that the gateway flow rule does not take effect for normal Web URL resources.

I will use API group.

**Comment by sczyh30** [comment]
> I mean the gateway-adapter not support get client IP by X-Forwarded-For?

Not yet, but this can be improved. Discussions and contributions are welcomed.

> It's only work to URL Route?

The gateway flow rules work for routes (defined in gateway properties) and customzied API groups (defined in Sentinel) only.
