### ISSUE TITLE
MetricNode/LongAdder memory footprint when Sentinel dependencies are introduced but no rules

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/Sentinel#1332]
![image](https://user-images.githubusercontent.com/15973635/76400801-e037aa00-63bb-11ea-9955-bda5d133e5fe.png)

![image](https://user-images.githubusercontent.com/15973635/76400836-ea59a880-63bb-11ea-9e23-84ca2842e5b5.png)
您好，关于这两个类占用内存问题：
先说下问题背景：我们有一个服务是没有使用Sentinel功能，只做了pom的引用，为了以后使用，引用版本：
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
			<version>0.2.1.RELEASE</version>

麻烦帮忙分析一下。只引用不使用也会有有内存开销么

**Comment by cdfive** [comment]
Try add this in applicaton.properties:
`spring.cloud.sentinel.enabled=false`
By deault is true, which will enable Sentinel functions.

**Comment by chenqwwq** [comment]
请问这个问题是解决了吗 我们只引入了依赖 但并没有做配置，线上的MetricNode和LongAdder就炸了

**Comment by xiangyang-gao** [comment]
> 请问这个问题是解决了吗我们只约会了依赖但并没有做配置，线上的MetricNode和LongAdder就炸了

spring.cloud.sentinel.enabled=false
