### ISSUE TITLE
Could not read rules correctly when using zookeeper as data source on provider

### ISSUE THREAD

**Issue by suiywah** [alibaba/Sentinel#1333]
## Issue Description
Our program is using dubbo as rpc framework and  zookeepr as datasource  of flow rules. We set flow rules from dashborad and zookeeper datasource read changes immediately. Sadly, load config info is uncorrectly.

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Here is part exception info:
```
com.alibaba.fastjson.JSONException: expect '[', but error, pos 1, column 2....
    at com.alibab.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParse.java:704)
    ...   
    at com.alibab.csp.sentinel.DataSourceInit.lambda$init$0(DataSourceInit.java:75)
    at com.alibab.csp.sentinel.datasource.AbstractDatasource.loadConfig(AbstractDatasource.java:48)
    at com.alibab.csp.sentinel.datasource.AbstractDatasource.loadConfig(AbstractDatasource.java:44)
    at com.alibab.csp.sentinel.datasource.zookeeper.ZookeeperDataSource$1.nodeChanged(ZookeeperDatasource.java:112)
    ...
```
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Sentinel core version: 1.7.0
Sentinel-dashboard version: 1.7.1
Deployed on Redhat Linux Server 6.9
Java SE build 1.8.0_171-b11

**Comment by cdfive** [comment]
The rules in config info should be **json array**,  surrounded by [], like this:
```json
[
    {
        "limitApp":"default",
        "resource":"aaa",
        "grade":1,
        "count":100,
        "strategy":0
    },
    {
        "limitApp":"default",
        "resource":"bbb",
        "grade":1,
        "count":100,
        "strategy":0
    }
]
```

**Comment by suiywah** [comment]
> The rules in config info should be **json array**, surrounded by [], like this:
> 
> ```json
> [
>     {
>         "limitApp":"default",
>         "resource":"aaa",
>         "grade":1,
>         "count":100,
>         "strategy":0
>     },
>     {
>         "limitApp":"default",
>         "resource":"bbb",
>         "grade":1,
>         "count":100,
>         "strategy":0
>     }
> ]
> ```

The original rules is json array, but there are some bytes was added to front of rule byte sequence after it detected by zookeeper client.
As I debuged the code of sentinel `ZookeeperDatasource.java#readSource()`,  my idea told me that is AtomicReference type.

**Comment by jasonjoo2010** [comment]
So what kind of content did you got in that block before deserializing?

**Comment by suiywah** [comment]
> So what kind of content did you got in that block before deserializing?

Just is the instance of `org.apache.curator.framework.recipes.cache.ChildData` commonly and `childData#getData()` method returned byte array. 
The `child Data#getData()` should return byte array if every thing is correct, and, it's actually is a array, but it's not deserializable because that the byte array I got is an object's instance deserialized instead of sting object's instance.

**Comment by cdfive** [comment]
As @jasonjoo2010 mentioned, could you please show the json string before deserializing,
Is it possible that there are special symbols in the middle or around?

**Comment by suiywah** [comment]
Thanks you guys care about this issue. I figured it out that we use other zookeeper client framework has private serializer and deserializer instead apache curator. That framework serialized our flow rules and I use apache curator to deserializing, so that is point why I could not got correct flow rules on my app.
