### ISSUE TITLE
Add slf4j extension module for Sentinel logger SPI

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1339]
## Issue Description

Umbrella issue: #1295 

Type: *feature request*

### Describe what happened (or what feature you want)

Add slf4j extension module (`sentinel-logging-extension-slf4j` in `sentinel-extension`) for [Sentinel logger SPI](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/Logger.java). We may refer to [the sample](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-log-logback) and https://github.com/alibaba/Sentinel/issues/757#issuecomment-599323263

Contributions are welcomed!

**Comment by wavesZh** [comment]
I want ！

**Comment by jasonjoo2010** [comment]
It can be closed and feature request has been met in #1344 .
