### ISSUE TITLE
Add logback extension module for Sentinel logger SPI

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1340]
## Issue Description

Umbrella issue: #1295 

Type: *feature request*

### Describe what happened (or what feature you want)

Add logback extension module (`sentinel-logging-extension-logback` in `sentinel-extension`) for [Sentinel logger SPI](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/Logger.java). We may refer to [the logback sample](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-log-logback) and https://github.com/alibaba/Sentinel/issues/757#issuecomment-599323263

Contributions are welcomed!

**Comment by zhaoyuguang** [comment]
I wanna try to finish it

**Comment by jasonjoo2010** [comment]
> I wanna try to finish it

Good to hear that.
And please pay attention to recent changes which will be merged: #1355 
You may rebase to the newest code before submitting.

**Comment by sczyh30** [comment]
As it's rare to use the loggers of the logging framework directly (without slf4j), I think this issue is no longer necessary and can be closed. Please reopen the issue if needed :)

Thanks for your contribution! @zhaoyuguang
