### ISSUE TITLE
Improve standard output content in LogBase

### ISSUE THREAD

**Issue by 457049726** [alibaba/Sentinel#1348]
强列建议去掉 LogBase 类中的 System.out.println()
否则每次项目启动时，会在控制台输出类似以下两行代码：

INFO: log base dir is: C:\Users\Administrator\logs\csp\
INFO: log name use pid is: false

这对公司新手来说，是非常致命的，让公司员工误以为日志目录变了，log4j 的日志目录配置不生效了。。。

以上两行日志是从 com.alibaba.csp.sentinel.log.LogBase 中的静太代码快中 init() 方法打印出来的，具体代码如下：

static {
        try {
            init();
        } catch (Throwable t) {
            t.printStackTrace();
            System.exit(-1);
        }
    }

    private static void init() {
        // first use -D, then use user home.
        String logDir = System.getProperty(LOG_DIR);

        if (logDir == null || logDir.isEmpty()) {
            logDir = System.getProperty(USER_HOME);
            logDir = addSeparator(logDir) + DIR_NAME + File.separator;
        }
        logDir = addSeparator(logDir);
        File dir = new File(logDir);
        if (!dir.exists()) {
            if (!dir.mkdirs()) {
                System.err.println("ERROR: create log base dir error: " + logDir);
            }
        }
        // logBaseDir must end with File.separator
        logBaseDir = logDir;
        System.out.println("INFO: log base dir is: " + logBaseDir);

        String usePid = System.getProperty(LOG_NAME_USE_PID, "");
        logNameUsePid = "true".equalsIgnoreCase(usePid);
        System.out.println("INFO: log name use pid is: " + logNameUsePid);
    }

最后，吐槽一下，我大天朝好像墙掉了 github.com网站，害得我为了提交这个 issues，特意拿了一台 海外云服务器做跳板上来提交，望采纳。。。

**Comment by sczyh30** [comment]
Thanks for your suggestion. The output is necessary for users to know the actual log dir of Sentinel, but we could improve the information to make it clear. Maybe `INFO: Sentinel log base directory is: xxx` is better?
