### ISSUE TITLE
怎样控制这个单位时间呢？

### ISSUE THREAD

**Issue by aBreaking** [alibaba/Sentinel#135]
你好！
注意到，Sentinel的流控、熔断策略都是针对**1秒**内的异常比、流量数进行控制。
但是有一个问题，流控还好一点；对于服务的异常比，这个1s的时间会不会有点太短了。
就单位时间内的异常比来说，在实际中（就笔者所遇到的一些情况），更多的情况都是针对30秒或者60秒之内，该服务出错数超过N次，才将该服务隔离。之前使用Hystrix能达到这样的效果。
所以，我想知道。在Sentinel中，那个位置能控制单位时间呢？
源码还没有细看，所以，想请教一下，目前我主要想修改一下异常比超过阈值后即服务降级，这个单位时间。可以在代码的哪些地方可以进行控制。
谢谢！

**Comment by sczyh30** [comment]
Duplicate with #141.
