### ISSUE TITLE
sentinel 添加流控规则不显示的问题

### ISSUE THREAD

**Issue by Alvinnlee** [alibaba/Sentinel#1354]
控制台添加流控规则后的流控规则没有显示，也没有生效。但是dashboard后台日志显示
INFO 19076 — [nio-8080-exec-7] c.a.c.s.d.client.SentinelApiClient : setRules: success已经成功了。

spring cloud alibaba：2.1.1.RELEASE
sentinel：1.7.0

**Comment by sczyh30** [comment]
Refer: #1349

**Comment by Alvinnlee** [comment]
谢谢  解决了
