### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 0.2.0.BUILD-SNAPSHOT通过Sentinel 控制台添加的动态规则成功了, 然后获取规则获取不到？

### ISSUE THREAD

**Issue by coolsnow77** [alibaba/Sentinel#136]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

通过Sentinel 控制台添加动态限流规则，在控制台左侧获取不到规则。
![image](https://user-images.githubusercontent.com/8206517/45210326-d82c1500-b2c1-11e8-8f07-a0e84620c368.png)

![image](https://user-images.githubusercontent.com/8206517/45209953-e6c5fc80-b2c0-11e8-8731-45681eab339c.png)

### Describe what you expected to happen
可以通过流控规则看到刚才添加的动态规则。

### How to reproduce it (as minimally and precisely as possible)

1. 点击Sentinel 控制台->簇点链路-> 流控添加规则
2. 
3. 

### Tell us your environment
1.jdk1.8
2.springboot2.0 环境. 
3.spring-cloud-starter-alibaba-sentinel - 0.2.0.BUILD-SNAPSHOT

**Comment by zhaowenlei** [comment]
我也是，使用的zookeeper 推模式，页面显示添加上了，但是去zookeeper里面根本没保存上，应用一重启就没有了，请问大佬们这是怎么回事啊？

**Comment by zhaowenlei** [comment]
private void listenRules()  {
        final String remoteAddress = "127.0.0.1:2181";
        final String path = "/Sentinel-Demo/SYSTEM-CODE-DEMO-FLOW";
        final String degradePath = "/Sentinel-Demo2/SYSTEM-CODE-DEMO-DEGRADE";

        DataSource<String, List<DegradeRule>> degradeRuleDataSource = new ZookeeperDataSource<>(remoteAddress, degradePath,
                source -> JSON.parseObject(source, new TypeReference<List<DegradeRule>>() {}));
        DegradeRuleManager.register2Property(degradeRuleDataSource.getProperty());
    }

**Comment by sczyh30** [comment]
@coolsnow77 Is there any Sentinel data source configured in your application? Please `curl localhost:port/getRules?type=flow` in your application local to see if the rule modification took effect.

**Comment by zhaowenlei** [comment]
@sczyh30 
![image](https://user-images.githubusercontent.com/10518580/45215748-f9e0c880-b2d0-11e8-8847-8b3811a33ab7.png)

**Comment by zhaowenlei** [comment]
@sczyh30 我应用里面基本没什么配置啊，就是按着你们的demo来弄的，添加了如下图的方法
![image](https://user-images.githubusercontent.com/10518580/45216077-ef72fe80-b2d1-11e8-9a19-176142f55aea.png)

jvm 参数：-Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=fooPre1

我的应用只添加了这些，您帮我看下，有什么问题吗？

**Comment by sczyh30** [comment]
@zhaowenlei Replied to you in #138.

**Comment by MrSummer33** [comment]
我也遇到过这个原因，跟代码进去发现是com.alibab.fastjson>的版本的原因;</br>低版本会导致 ***rule对象的resource字段为null*** , 导致NPE。</br> 解决 ：将版本升级到 ***1.2.49*** 即可。</br>
![image](https://user-images.githubusercontent.com/21139900/45251742-dde73080-b37d-11e8-8f85-c8bebf25b37f.png)

**Comment by sczyh30** [comment]
Yes, the fastjson version in your own dependency should match the version in Sentinel, or error may occur.

**Comment by coolsnow77** [comment]
@sczyh30,  我没有配置Sentinel data source, 我使用curl命令测试: 得到[], 
![image](https://user-images.githubusercontent.com/8206517/45271380-2b2be500-b4d9-11e8-8f76-5298e173cfa9.png)

**Comment by coolsnow77** [comment]
@sczyh30 , 我升级了一下fastjson 到1.2.49 可以看到规则了。@MrSummer33 多谢, much thks. 
![image](https://user-images.githubusercontent.com/8206517/45275854-a26d7300-b4f1-11e8-8bd2-8eb3bdfd0297.png)
![image](https://user-images.githubusercontent.com/8206517/45275864-adc09e80-b4f1-11e8-9dc4-b3461ecdd06e.png)
