### ISSUE TITLE
控制台无法接入springcloud gateway api

### ISSUE THREAD

**Issue by sc2885112** [alibaba/Sentinel#1362]
## Issue Description
控制台无法接入我本机springcloud gateway网关服务

### pom.xml

``` xml

 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.5.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.9</version>
        </dependency>
```

###  java配置

```java
@Configuration
public class GatewayConfiguration {

    private final List<ViewResolver> viewResolvers;
    private final ServerCodecConfigurer serverCodecConfigurer;

    public GatewayConfiguration(ObjectProvider<List<ViewResolver>> viewResolversProvider,
                                ServerCodecConfigurer serverCodecConfigurer) {
        this.viewResolvers = viewResolversProvider.getIfAvailable(Collections::emptyList);
        this.serverCodecConfigurer = serverCodecConfigurer;
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public SentinelGatewayBlockExceptionHandler sentinelGatewayBlockExceptionHandler() {
        // Register the block exception handler for Spring Cloud Gateway.
        return new SentinelGatewayBlockExceptionHandler(viewResolvers, serverCodecConfigurer);
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public GlobalFilter sentinelGatewayFilter() {
        return new SentinelGatewayFilter();
    }

    @PostConstruct
    public void doInit() {
        initCustomizedApis();
        initGatewayRules();
    }

    private void initCustomizedApis() {
        Set<ApiDefinition> definitions = new HashSet<>();
        ApiDefinition api1 = new ApiDefinition("some_customized_api")
                .setPredicateItems(new HashSet<ApiPredicateItem>() {{
//                    add(new ApiPathPredicateItem().setPattern("/ahas"));
                    add(new ApiPathPredicateItem().setPattern("/service-decision-manage/**")
                            .setMatchStrategy(SentinelGatewayConstants.URL_MATCH_STRATEGY_PREFIX));
                }});
        ApiDefinition api2 = new ApiDefinition("another_customized_api")
                .setPredicateItems(new HashSet<ApiPredicateItem>() {{
                    add(new ApiPathPredicateItem().setPattern("/**")
                            .setMatchStrategy(SentinelGatewayConstants.URL_MATCH_STRATEGY_PREFIX));
                }});
        definitions.add(api1);
        definitions.add(api2);
        GatewayApiDefinitionManager.loadApiDefinitions(definitions);
    }

    private void initGatewayRules() {
        Set<GatewayFlowRule> rules = new HashSet<>();
        rules.add(new GatewayFlowRule("some_customized_api")
                .setResourceMode(SentinelGatewayConstants.RESOURCE_MODE_CUSTOM_API_NAME)
                .setCount(5)
                .setIntervalSec(1)
                .setParamItem(new GatewayParamFlowItem()
                        .setParseStrategy(SentinelGatewayConstants.PARAM_PARSE_STRATEGY_URL_PARAM)
                        .setFieldName("pnnnnn")
                )
        );
        GatewayRuleManager.loadRules(rules);
    }
}
```

### 启动参数
> java -Dcsp.sentinel.api.port=7979 -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.7.1.jar

csp.sentinel.api.port 我感觉这个启动参数没用，因为当我启动之后，我在控制台只能看到本地7981的端口，这和你们官方文档上说的默认端口8719也是不一致的

![GCNsRe.jpg](https://s1.ax1x.com/2020/03/27/GCNsRe.jpg)

### Tell us your environment

macos catalina 10.15

### 联系方式
> 827455172@qq.com

### 希望能帮助我解决一下 ，谢谢

**Comment by cdfive** [comment]
因为`-Dcsp.sentinel.api.port=7979`命令行指定了这个参数项，表示应用端的Sentinel传输端口为7979，就不会使用默认端口8719了。
在控制台看到的是端口号是7981，估计是你指定的**7979**端口**已被其它程序占用**，如果端口被占用Sentinel会尝试端口号加1，直到找到一个可用的端口。

网关应用接入控制台，启动参数还需要增加：`-Dcsp.sentinel.app.type=1`，用于标识它为网关应用。

具体可以参考文档：
[https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台](https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台)

**Comment by sc2885112** [comment]
> 因为`-Dcsp.sentinel.api.port=7979`命令行指定了这个参数项，表示应用端的Sentinel传输端口为7979，就不会使用
> 交换端口8719了。在控制台看到的是端口号是7981，估计是您指定的**7979**端口**已被其他程序占用**，如果端口被占用Sentinel会尝试端口号加1，直到找到一个可用的端口。
> 
> 网关应用收件人控制台，启动参数还需要增加：`-Dcsp.sentinel.app.type=1`，用于标识它为网关应用。
> 
> 具体可以参考文档：[https](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0) :
> [//github.com/alibaba/Sentinel/wiki/网关限流＃网关流控控制台](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0)

我按照你的提示，做了些修改，现在我的gateway 网关服务的端口是 7979 ，sentinel控制台的的通信端口未设置，就是默认的8719，我确定8719这个端口没有被使用，同时我又在yml配置文件中添加了如下配置，可还是在控制台页面看不到自定义的规则

``` yml
spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
server:
  port: 7979
```
我希望从源码中得到一点线索，但是我也并没有找到哪些默认的api 如（/metric/queryTopResourceMetric.json）是在哪里进行的配置

**Comment by sc2885112** [comment]
> 因为`-Dcsp.sentinel.api.port=7979`命令行指定了这个参数项，表示应用端的Sentinel传输端口为7979，就不会使用默认端口8719了。
> 在控制台看到的是端口号是7981，估计是你指定的**7979**端口**已被其它程序占用**，如果端口被占用Sentinel会尝试端口号加1，直到找到一个可用的端口。
> 
> 网关应用接入控制台，启动参数还需要增加：`-Dcsp.sentinel.app.type=1`，用于标识它为网关应用。
> 
> 具体可以参考文档：
> [https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81#%E7%BD%91%E5%85%B3%E6%B5%81%E6%8E%A7%E6%8E%A7%E5%88%B6%E5%8F%B0)
> [https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5)

非常感谢你的回答，当我过了一会刷新了一下页面之后，发现我的服务已经正常显示在了控制台，现在他们已经正常协同工作了！
