### ISSUE TITLE
Nginx proxy Sentinel,static resource can't load

### ISSUE THREAD

**Issue by shengmingYu** [alibaba/Sentinel#1364]
## Issue Description
1.my nginx conf :
![image](https://user-images.githubusercontent.com/31875813/77759773-4127d900-7070-11ea-8548-743d429451e4.png)
2.result:
![image](https://user-images.githubusercontent.com/31875813/77759838-61579800-7070-11ea-88aa-1b8721df6fd5.png)
![image](https://user-images.githubusercontent.com/31875813/77759889-7502fe80-7070-11ea-8d5d-c2aafe7593d6.png)
![image](https://user-images.githubusercontent.com/31875813/77761220-a8df2380-7072-11ea-8a3a-0fb9af233e85.png)

I thisk something went wrong with the relative path

Type: *bug report* or *feature request*
bug report

### Tell us your environment
jdk1.8.。Nginx，sentinel-dashboard-1.7.1.jar

**Comment by ai-hes** [comment]
It is your nginx configuration problem, no matter with Sentinel。 just change your nginx.conf is ok

**Comment by shengmingYu** [comment]
> It is your nginx configuration problem, no matter with Sentinel。 just change your nginx.conf is ok

so,How should I configure

**Comment by Garlichead** [comment]
use nginx proxy sentinel, this scenes is solve what problem?
