### ISSUE TITLE
 Sentinel dashboard设置流控后参数，流控规则页面不显示

### ISSUE THREAD

**Issue by chenglin321** [alibaba/Sentinel#1369]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

 Sentinel dashboard设置流控

### Describe what you expected to happen
step1:
![image](https://user-images.githubusercontent.com/3918176/77971691-eddcb180-7321-11ea-8b3e-e47b53246ab3.png)
step2:
![image](https://user-images.githubusercontent.com/3918176/77971707-f7feb000-7321-11ea-9713-0f0a201b2752.png)

 Sentinel dashboard设置流控后参数，流控规则页面不显示

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
192.168.1.245为本机ip，dashboard与client在同一台机器，dashboard 端口是8000
Sentinel  client已启动，
Sentinel  client启动参数，-Dcsp.sentinel.heartbeat.client.ip=192.168.1.245 -Dcsp.sentinel.dashboard.server=localhost:8000 -Dproject.name=wx-tomcat-sentinel
Sentinel  client 是tomcat7，jdk8,spring4.x,springmvc
Sentinel  client 
pom.xml
	
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-spring-webmvc-adapter</artifactId>
			<version>1.7.1</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-transport-simple-http</artifactId>
			<version>1.7.1</version>
		</dependency>

spring-mvc.xml

 <mvc:interceptors>
        <mvc:interceptor>
            <mvc:mapping path="/**"/>
            <bean class="com.alibaba.csp.sentinel.adapter.spring.webmvc.SentinelWebInterceptor" />
        </mvc:interceptor>
    </mvc:interceptors>

dashboard启动参数
java -Dserver.port=8000      -jar sentinel-dashboard-1.7.1.jar

**Comment by cdfive** [comment]
Check the version of `fastjson` in your project, and may upgrade to new version.
```xml
<dependency>
  <groupId>com.alibaba</groupId>
  <artifactId>fastjson</artifactId>
  <version>1.2.62</version>
</dependency>
```
Related to #1349 
Also refer to [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ)

**Comment by jasonjoo2010** [comment]
If due to fastjson it's also related to #736, #742

**Comment by jasonjoo2010** [comment]
Maybe we should really do some kinds of acceptable, strong check on it

**Comment by chenglin321** [comment]
> Check the version of `fastjson` in your project, and may upgrade to new version.
> 
> ```
> <dependency>
>   <groupId>com.alibaba</groupId>
>   <artifactId>fastjson</artifactId>
>   <version>1.2.62</version>
> </dependency>
> ```
> 
> Related to #1349
> Also refer to [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ)

之前的fastjson是fastjson-1.1.39，换成 1.2.62就ok了。
