### ISSUE TITLE
Rules loaded but seems not working

### ISSUE THREAD

**Issue by zephyrli** [alibaba/Sentinel#1371]
## Issue Description
I've met a problem. This is the situation: I've set up a flow rule with sentinel-dashboard, and from the sentinel-record.log, it is sure that the application have loaded the rules. Here is the log:

![image](https://user-images.githubusercontent.com/5013049/77997308-c0175d00-7361-11ea-814a-f83ddb458080.png)
 

### What happened 
And the resource with annotation can be found in page "簇点链路"
![image](https://user-images.githubusercontent.com/5013049/77997512-1f756d00-7362-11ea-9bb5-fc534da053c2.png)
but the QPS in this page is always 0, which is not correct, and there is nothing in realtime monitoring page. The rules are not working though they're loaded, requests are not blocked at all. There are metric logs in  metrics.log.

My application is a Spring Boot one. And I've tried to reproduce the problem based on the demo project sentinel-demo-annotation-spring-aop but failed. 

### Environment
It's a local test in Mac OS X.

Could I get some help here?

**Comment by zephyrli** [comment]
It turned out to be a component scan issue. 

Now the @SentinelResource annotation works well in Controller level, but still doesn't work in Service level. No data in "簇点链路” page or "实时监控" page， and requests are not blocked.

**Comment by zephyrli** [comment]
It turns out to be a proxy issue. Because I have a inner call of the target method in Service, which does not use proxy, annotation can't work in this situation unless proxy exposed.

**Comment by sczyh30** [comment]
Related to #349
