### ISSUE TITLE
ContextUtil.enter方法的origin参数和SphU.entry()方法的args参数在并发时，值不一致

### ISSUE THREAD

**Issue by iloveuhaha** [alibaba/Sentinel#1373]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
sentinel.version=1.7.0
![问题详细说明](https://user-images.githubusercontent.com/1266996/78208936-39d15700-74d8-11ea-9a31-6907f255115d.png)

**Comment by iloveuhaha** [comment]
[ApiController.txt](https://github.com/alibaba/Sentinel/files/4418823/ApiController.txt)

**Comment by iloveuhaha** [comment]
[HttpTest.txt](https://github.com/alibaba/Sentinel/files/4418847/HttpTest.txt)

**Comment by sczyh30** [comment]
入口处 `ContextUtil.enter(xxx)` 和 `ContextUtil.exit()` 也必须配对，否则之前的上下文不会被清理，新的请求仍然会挂在之前的 context 下。参考 [此处文档](https://github.com/alibaba/Sentinel/wiki/如何使用#上下文工具类-contextutil)

**Comment by iloveuhaha** [comment]
> 入口处 `ContextUtil.enter(xxx)` 和 `ContextUtil.exit()` 也必须配对，否则之前的上下文不会被清理，新的请求仍然会挂在之前的 context 下。参考 [此处文档](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E4%B8%8A%E4%B8%8B%E6%96%87%E5%B7%A5%E5%85%B7%E7%B1%BB-contextutil)

谢谢，正是这样。
