### ISSUE TITLE
熔断降级规则可以持久化到nacos中吗？

### ISSUE THREAD

**Issue by liuzhengyang888** [alibaba/Sentinel#1375]
## Issue Description
可以像下方限流规则持久化到nacos中吗？
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/27286005/78218984-47dfa180-74f1-11ea-95c8-3c52a6fbcf4a.png)

**Comment by cdfive** [comment]
可以的，应用中引入依赖`sentinel-datasource-nacos`，然后再Nacos界面上设置规则即可。

参考：[https://github.com/alibaba/Sentinel/wiki/动态规则扩展#推模式使用-nacos-配置规则](https://github.com/alibaba/Sentinel/wiki/动态规则扩展#推模式使用-nacos-配置规则)

如果使用控制台修改规则并需要持久化到Nacos目前需要参考[控制台文档](https://github.com/alibaba/Sentinel/wiki/控制台#62-规则推送)改造。

**Comment by sczyh30** [comment]
If you're using Spring Cloud Alibaba Sentinel, you may also refer to https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#动态数据源支持
