### ISSUE TITLE
SpringBoot 如何接入Sentinel？直接引入Sentinel Starter失效

### ISSUE THREAD

**Issue by MrSummer33** [alibaba/Sentinel#139]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MrSummer33** [comment]
我用的是Spring cloud，并非Spring-cloud-alibaba

**Comment by sczyh30** [comment]
If you are using Spring Cloud, you can use Spring Cloud Sentinel Starter for integrations. See the [tutorial](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/readme-zh.md).

**Comment by CarpenterLee** [comment]
If you don't want to introduce the starter dependency, the follow step will help you: 
1. introduce `sentinel-web-servlet` dependency
```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-web-servlet</artifactId>
    <version>x.y.z</version>
</dependency>
```
2. Config `CommonFilter` as the web filter. For spring boot, we can config as follow:
```java
@Bean
public FilterRegistrationBean sentinelFilterRegistration() {
    FilterRegistrationBean registration = new FilterRegistrationBean();
    registration.setFilter(new CommonFilter());
    registration.addUrlPatterns("/*");
    registration.addInitParameter("paramName", "paramValue");
    registration.setName("sentinelFilter");
    registration.setOrder(1);

    return registration;
}
```

See [WebConfig](https://github.com/alibaba/Sentinel/blob/master/sentinel-dashboard/src/main/java/com/taobao/csp/sentinel/dashboard/config/WebConfig.java) as example.
