### ISSUE TITLE
从1.7.1 开始 UrlBlockHandler 接口被删除了吗

### ISSUE THREAD

**Issue by YuizhiCode** [alibaba/Sentinel#1393]
从1.7.1 UrlBlockHandler 接口被删除了吗
有新的接口代替吗，等待回复

**Comment by sczyh30** [comment]
The `UrlBlockHandler` was not changed. If you're using `sentinel-spring-webmvc-adapter`, you may refer to: https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter

**Comment by YuizhiCode** [comment]
> 在`UrlBlockHandler`没有改变。如果您使用`sentinel-spring-webmvc-adapter`，则可以参考：[https](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter) : [//github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter)

感谢

**Comment by pencilso** [comment]
经测试，在1.8.1版本上，即使添加spring-webmvc-adapter里的配置也无效，最后翻源码的时候翻到一个解决方案，如下所示：
```java
    @PostConstruct
    public void initUrlBlockHandler() throws JsonProcessingException {
        this.ERROR_BLOCKED_LIMITING = JsonUtils.objectToJson(new Result<>(false, "限流异常"));
        WebCallbackManager.setUrlBlockHandler((request, response, ex) -> {
            response.setHeader("Content-Type", "application/json;charset=UTF-8");
            response.getWriter().write(ERROR_BLOCKED_LIMITING);
        });
    }
```

**Comment by 741082214** [comment]
用这个 BlockExceptionHandler

**Comment by miozus** [comment]
Sentinel version 1.8.0 (which not exists `WebCallbackManager`)

❌ incorrected demonstration

addInterceptors

![image](https://user-images.githubusercontent.com/35659194/160745594-1fa0cfd1-2a73-4959-9e6a-532ad6d2c53e.png)

Not Exists field cause of SentinelWebMvcConfig does not exist `blockExceptionHandler`  which belongs to its father Object （BaseWebMvcConfig）.

```java
public class SentinelWebMvcConfig extends BaseWebMvcConfig {

    public static final String DEFAULT_REQUEST_ATTRIBUTE_NAME = "$$sentinel_spring_web_entry_attr";

    /**
     * Specify the URL cleaner that unifies the URL resources.
     */
    private UrlCleaner urlCleaner;

    /**
     * Specify whether the URL resource name should contain the HTTP method prefix (e.g. {@code POST:}).
     */
    private boolean httpMethodSpecify;

    /**
     * Specify whether unify web context(i.e. use the default context name), and is true by default.
     *
     * @since 1.7.2
     */
    private boolean webContextUnify = true;

//...
```

✅ correct demonstation

override interface

```java

/**
 * 秒杀块异常处理程序
 *
 * @author Miozus
 * @date 2022/03/30
 */
@Configuration
public class SeckillBlockExceptionHandler implements BlockExceptionHandler {
    @Override
    public void handle(HttpServletRequest request, HttpServletResponse response, BlockException e) throws Exception {
        R error = R.error(BizCodeEnum.TOO_MANY_REQUESTS);
        response.setHeader("Content-Type", "application/json;charset=UTF-8");
        response.getWriter().write(JSONUtil.toJsonStr(error));
    }
}
```

the document I have read and testted:


> The `UrlBlockHandler` was not changed. If you're using `sentinel-spring-webmvc-adapter`, you may refer to: https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter
