### ISSUE TITLE
my application or Sentinel system logout each other.

### ISSUE THREAD

**Issue by wangjuqing** [alibaba/Sentinel#1397]
My application use shiro, and add  the Sentinel now, they can start up successfully,But when i click the Sentinel system,My application logout, or when i click My application ,the Sentinel system logout.
So what should i do?
sentinel-dashboard-1.7.1

**Comment by sczyh30** [comment]
Maybe related to #1434

**Comment by wangjuqing** [comment]
springboot内置的tomcat会生成一个名称为JSESSIONID的cookie name，如果不做修改，两个web服务的cookie name是相同的所以会彼此覆盖，所以需要去修改springboot内置tomcat的cookie name让两个项目的cookie name不同。server.servlet.session.cookie.name
