### ISSUE TITLE
Gateway 整合 Sentinel 采用 Nacos 作为流控配置持久化，从Nacos上读取流控配置，网关限流与配置不符

### ISSUE THREAD

**Issue by zhanyifan1997** [alibaba/Sentinel#1398]
## Issue Description
When I use sentinel to integrate with spring cloud gateway for current limiting and persist the flow control rules in nacos, when I start the gateway and microservice for testing, the interval configuration configured on nacos does not take effect. For example, I set only 1 request to pass in 10 seconds, but the test result is 1 request in 1 second. It seems that the configuration pulled from nacos is converted to GatewayFlowRule and the time interval becomes 1, which is not 10 seconds of nacos configuration
### the problem demo
[When using memory to store limit rules](https://ipfs.spectrumrpc.cn/ipfs/Qma2bSXesAE6R6wT4ghWfNmTcFyJyyvY8hoB5ZU4LgLN8D)
[When using nacos to store limit rules](http://ipfs.spectrumrpc.cn/ipfs/QmejFfhr9R3HBj1i8NXPAA1L7n5iTv3JYWJ6vAcT72AS6Z)
## My Environment
Spring Boot : 2.2.2.RELEASE
Spring Cloud : Hoxton.SR1
Spring Cloud Alibaba : 2.1.0.RELEASE
Sentinel： 1.7.2 以及 1.7.0 均尝试过
JDK : 1.8
## How to reproduce it
  1. import sentinel，sentinel-gateway，nacos-discovery，sentinel-datasource-nacos dependency in gateway module
  2. import nacos-discovery，starter-web dependency  in MicroService module
  3. add one rule in nacos like this
`[
    {
        "app":"sentinel-gateway",
        "burst":0,
        "controlBehavior":0,
        "count":1,
        "gmtCreate":1586674936282,
        "gmtModified":1586675781653,
        "grade":1,
        "id":1,
        "interval":10,
        "intervalUnit":0,
        "ip":"192.168.228.33",
        "port":8722,
        "resource":"payment_route",
        "resourceMode":0
    }
]`
   4. then run the gateway and microservice for testing
## The Bug was happened in
the SentinelConvert.convertRule () method，ruleStr converted to GatewayFlowRule, the intervalSec is not the same as the configuration on nacos， Causes flow control rules to be wrong, resulting in a mismatch of the above rules
see the image [http://ipfs.spectrumrpc.cn/ipfs/QmYDJyGEAFVgLYMcQLzyy23cu8ZigyrVAFJt1ZUwcrgAXD](http://ipfs.spectrumrpc.cn/ipfs/QmYDJyGEAFVgLYMcQLzyy23cu8ZigyrVAFJt1ZUwcrgAXD)

**Comment by sczyh30** [comment]
The field of statistic interval should be `intervalSec`. See https://github.com/alibaba/Sentinel/wiki/网关限流

**Comment by zhanyifan1997** [comment]
Why do I use the following code to publish GatewayFlowRule to nacos, the field on nacos is interval, not intervalSec?
`public class GatewayFlowRulesNacosPublisher implements DynamicRulePublisher<List<GatewayFlowRuleEntity>> {
    @Autowired
    private ConfigService configService;
    @Autowired
    private Converter<List<GatewayFlowRuleEntity>, String> converter;

    @Override
    public void publish(String app, List<GatewayFlowRuleEntity> rules) throws Exception {
        AssertUtil.notEmpty(app, "app name cannot be empty");
        if (rules == null) {
            return;
        }
        configService.publishConfig(app + NacosConfigUtil.GATEWAY_FLOW_DATA_ID_POSTFIX,
                NacosConfigUtil.GROUP_ID, converter.convert(rules));
    }
}`

**Comment by wavesZh** [comment]
@zhanyifan1997  `GatewayFlowRule` and `GatewayFlowRuleEntity` are different!
You should use `GatewayFlowRuleEntity#toGatewayFlowRule` to convert to `GatewayFlowRule` first, then convert to json string.

**Comment by zhanyifan1997** [comment]
so publish to nacos is GatewayFlowRule convert to json string, not GatewayFlowRuleEntity convert to json string?

**Comment by wavesZh** [comment]
Of course!  It's already indicated in your picture: http://ipfs.spectrumrpc.cn/ipfs/QmYDJyGEAFVgLYMcQLzyy23cu8ZigyrVAFJt1ZUwcrgAXD <http://ipfs.spectrumrpc.cn/ipfs/QmYDJyGEAFVgLYMcQLzyy23cu8ZigyrVAFJt1ZUwcrgAXD>. ruleStr from Nacos convert to GatewayFlowRule, so you should publish string for GatewayFlowRule

**Comment by zhanyifan1997** [comment]
But in the official case(sentinel-dashboard\src\test\java\com\alibaba\csp\sentinel\dashboard\rule\nacos\FlowRuleNacosPublisher.java), publish FlowRule to nacos,using FlowRuleEntity, may mislead other users. . .

**Comment by cdfive** [comment]
> But in the official case(sentinel-dashboard\src\test\java\com\alibaba\csp\sentinel\dashboard\rule\nacos\FlowRuleNacosPublisher.java), publish FlowRule to nacos,using FlowRuleEntity, may mislead other users. . .

This is normal `FlowRule`, not `GatewayFlowRule`, and `GatewayFlowRule` is different from `FlowRule`.

The `GatewayFlowRuleEntity` is used for dashboard, we may select time value and unit on the web UI of dashboard, that's why `Long interval`, `Integer intervalUnit` is designed in `GatewayFlowRuleEntity`, which is different from `intervalSec` in `GatewayFlowRule`.

**Comment by billytomato** [comment]
网关在nacos上的配置项是这样的

[
    {
        "resource": "quickstart_route",
        "grade": 1,
        "count": 1500,
        "strategy": 0,
        "controlBehavior": 0,
        "clusterMode": false
    }
]

**Comment by whd120130** [comment]
TokenServer 从Nacos中获取网关流控规则时获取不到，只能获取对应的FlowRule 不能获取GatewayFlowRule 规则！

**Comment by wavesZh** [comment]
> TokenServer 从Nacos中获取网关流控规则时获取不到，只能获取对应的FlowRule 不能获取GatewayFlowRule 规则！

https://github.com/alibaba/Sentinel/issues/1320 暂不支持集群网关流控

**Comment by sczyh30** [comment]
> But in the official case(sentinel-dashboard\src\test\java\com\alibaba\csp\sentinel\dashboard\rule\nacos\FlowRuleNacosPublisher.java), publish FlowRule to nacos,using FlowRuleEntity, may mislead other users. . .

This could be improved. See #1257
