### ISSUE TITLE
Does Zuul 2.x gateway adapter in 1.7.2 support cluster flow control?

### ISSUE THREAD

**Issue by anningzhu** [alibaba/Sentinel#1399]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
The gateway cluster flow control (for `GatewayFlowRule`) is not supported, but you could leverage the normal cluster flow rule and parameter flow rule.
