### ISSUE TITLE
Some code against the Alibaba Java Coding Guidelines

### ISSUE THREAD

**Issue by jarvisxiong** [alibaba/Sentinel#14]
https://github.com/alibaba/Sentinel/blob/2f8a818d20b1bb72cc4d72c38a2cd7822ffdc25a/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/controller/WarmUpController.java#L149
阿里插件提示，需long型常量大写L结尾，避免混淆。

**Comment by sczyh30** [comment]
We'll fix this for the legacy code. Thanks for reporting!
