### ISSUE TITLE
建议增加LocalDataSource，支持从本地文件读取规则

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/Sentinel#140]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by yfh0918** [comment]
有filewritabledatasource支持本地文件保存规则，具体可以参考demo

**Comment by sczyh30** [comment]
Local file is supported in Sentinel data source extension. For readable data source, you can use `FileRefreshableDataSource`. For writable data source, you can use `FileWritableDataSource` (since 0.2.0).
