### ISSUE TITLE
Can MetricEntity data be collected according to rules？

### ISSUE THREAD

**Issue by liauraljl** [alibaba/Sentinel#1404]
## Issue Description
Is the MetricEntity collected by dashdoard classified according to rules? When the same resource is configured with flow rule, degrade rule and param-flow rule at the same time, we want to distinguish different rules to display Metric data

Type: *bug report* or *feature request*
feature request

### Describe what you expected to happen
When the same resource is configured with flow rule, degrade rule and param-flow rule at the same time, we want to distinguish different rules to display Metric data

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
It's not planned yet. You may need to refactor the core statistics (by rule, rather by resource) and the dashboard.
