### ISSUE TITLE
建议使用Jackson替换fastjson

### ISSUE THREAD

**Issue by brucewuu520** [alibaba/Sentinel#1406]
建议使用Jackson替换fastjson

**Comment by sczyh30** [comment]
Actually we don't restrict the JSON library. You may use your own rule parsers when creating data sources.

**Comment by woshioosm** [comment]
同样建议替换掉fastjson    sentinel的transport-common 中是强关联fastjson的

**Comment by sczyh30** [comment]
Refer #1522
