### ISSUE TITLE
更新实时监控文档

### ISSUE THREAD

**Issue by WongTheo** [alibaba/Sentinel#1407]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

[实时监控](https://github.com/alibaba/Sentinel/wiki/%E5%AE%9E%E6%97%B6%E7%9B%91%E6%8E%A7)

该文档中*资源的秒级日志* 章节对日志格式的描述已过期

index | 例子 | 说明
-- | -- | --
1 | 1529573107000 | 时间戳
2 | 2018-06-21 17:25:07 | 日期
3 | sayHello(java.lang.String,long) | 资源名称
4 | 10 | 每秒通过的资源请求个数
5 | 3601 | 每秒资源被拦截的个数
6 | 10 | 每秒完成调用的资源个数，包括正常结束和异常结束的情况
7 | 0 | 每秒资源的异常个数
8 | 2 | 资源平均响应时间（ms）

查阅``` com.alibaba.csp.sentinel.node.metric.MetricNode#toFatString()```源码，在1.5.0版本以后，新增了三个字段 occupiedPassQps|concurrency|classification

```java
    public String toFatString() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        StringBuilder sb = new StringBuilder(32);
        sb.delete(0, sb.length());
        sb.append(getTimestamp()).append("|");
        sb.append(df.format(new Date(getTimestamp()))).append("|");
        String legalName = getResource().replaceAll("\\|", "_");
        sb.append(legalName).append("|");
        sb.append(getPassQps()).append("|");
        sb.append(getBlockQps()).append("|");
        sb.append(getSuccessQps()).append("|");
        sb.append(getExceptionQps()).append("|");
        sb.append(getRt()).append("|");
        sb.append(getOccupiedPassQps()).append("|"); //1.5.0新增
        sb.append(concurrency).append("|"); //1.7.0新增
        sb.append(classification); //1.7.0新增
        sb.append('\n');
        return sb.toString();
    }
```

### Describe what you expected to happen

文档应增加日志中这三个字段的描述
occupiedPassQps
concurrency
classification

**Comment by sczyh30** [comment]
We've polished the content. Thanks for your suggestion.
