### ISSUE TITLE
NPE on Context.getCurNode() of SentinelReactorSubscriber#hookOnError

### ISSUE THREAD

**Issue by liurongwei** [alibaba/Sentinel#1410]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
`

  | j.l.NullPointerException: null 	at c.a.c.s.c.Context.getCurNode(Context.java:112) 	at c.a.c.s.Tracer.traceContext(Tracer.java:84) 	at c.a.c.s.a.r.SentinelReactorSubscriber.hookOnError(SentinelReactorSubscriber.java:150) 	at c.a.c.s.a.r.InheritableBaseSubscriber.onError(InheritableBaseSubscriber.java:176) 	... 119 common frames omitted 	Suppressed: o.s.c.g.s.NotFoundException: 503 SERVICE_UNAVAILABLE "Unable to find instance for platform-usedcar-mvc" 		at o.s.c.g.s.NotFoundException.create(NotFoundException.java:46) 		at o.s.c.g.f.LoadBalancerClientFilter.filter(LoadBalancerClientFilter.java:86) 		at o.s.c.g.h.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138) 		at o.s.c.g.f.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) 		at o.s.c.g.h.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118) 		at r.c.p.MonoDefer.subscribe(MonoDefer.java:44) 		... 109 common frames omitted Wrapped by: r.c.Exceptions$BubblingException: java.lang.NullPointerException 	at r.core.Exceptions.bubble(Exceptions.java:170) 	at r.c.p.Operators.onErrorDropped(Operators.java:521) 	at c.a.c.s.a.r.InheritableBaseSubscriber.onError(InheritableBaseSubscriber.java:179) 	at c.a.c.s.a.r.SentinelReactorSubscriber.onError(SentinelReactorSubscriber.java:37) 	at r.c.p.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) 	at r.c.p.Operators$MonoSubscriber.onError(Operators.java:1671) 	at r.c.p.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:235) 	at r.c.p.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) 	at r.c.p.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251) 	at r.c.p.Operators$MonoSubscriber.onError(Operators.java:1671) 	at r.c.p.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:235) 	at r.c.p.Operators.error(Operators.java:182) 	at r.c.p.MonoDefer.subscribe(MonoDefer.java:48) 	at r.c.p.MonoDefer.subscribe(MonoDefer.java:52) 	at r.c.publisher.Mono.subscribe(Mono.java:4105)
-- | --

`

### How to reproduce it (as minimally and precisely as possible)

1.  on test env didn't occurs the exception, but on prd env with 100w a days request , it happens continuously .

### Tell us your environment
jdk 1.8 spring cloud gateway 2.2.1, sentinel , nacos 1.7.2

**Comment by sczyh30** [comment]
You may check whether it's related to #1184

**Comment by sczyh30** [comment]
Any feedback?
