### ISSUE TITLE
sentinel 流控模式下关联和链路问题

### ISSUE THREAD

**Issue by linkai0001** [alibaba/Sentinel#1411]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

最新版本的 sentinel 中(sentinel 控制台 1.7.2, spring cloud  alibaba 2.2.1.RELEASE), 流控规则中的流控模式, 关联和链路都出现问题。
备注：(尝试配置spring.cloud.sentinel.web-context-unify=false,未有效果)

问题如下, 
1. 在流控模式的关联选项中,我配置了资源名为 /test01,流控模式的选项为关联 ,关联资源为  /test02, QPS下的单机阈值为1, 在 /test02 资源一直占用着QPS的情况下, /test01 的资源依然可以被访问(无限流效果)
2. 在流控模式的链路选项中, 配置了两处资源(/test01,/test02) 指向了 @SentinelResource("test") 修饰的函数, 正常来说, 簇点链路中应该是 /test01->test 和  /test02->test 模式,并未出现该效果

这几个问题在未来什么版本下可以得到修复

In the latest version of sentinel (sentinel console 1.7.2, spring cloud alibaba 2.2.1.RELEASE), there are problems with the flow control mode, association and link in the flow control rules.
Remarks: (Try to configure spring.cloud.sentinel.web-context-unify = false, no effect)

Questions are as follows, 
1. In the flow control mode association option, I configured the resource name as /test01, the flow control mode option is association, the associated resource is /test02, the single machine threshold under QPS is 1, and the /test02 resource has always occupied QPS Next, the resources of /test01 can still be accessed (infinite streaming effect)

2. In the link option of flow control mode, two resources (/test01, /test02) are configured to point to the function modified by @SentinelResource ("test"). Normally, the cluster point link should be /test01-> test and /test02-> test mode, the effect does not appear

In what future versions will these problems be fixed

**Comment by sczyh30** [comment]
For 2, please refer to #1313

**Comment by wsj1028** [comment]
这个问题关闭了？  解决了？

**Comment by jasonjoo2010** [comment]
这个似乎应该是sca的问题？建议在sca项目提出

**Comment by 18050012583** [comment]
@linkai0001 请问解决了吗。看配置都没有这个属性web-context-unify。
