### ISSUE TITLE
关闭springboot 但tomcat不关闭的情况下，Sentinel的监听服务（8719）还在运行。

### ISSUE THREAD

**Issue by zhangxuzhuang** [alibaba/Sentinel#1414]
关闭springboot 但tomcat不关闭的情况下，Sentinel的监听服务（8719）还在运行，
下次启动，因为8719端口被占用，所以会启动8720端口，这样就会有两个端口运行监听服务

**Comment by cdfive** [comment]
是怎么关闭springboot的呢？一般关闭应用tomcat也关闭了呀

**Comment by zhangxuzhuang** [comment]
利用 Springboot的spring-boot-starter-actuator，可以实现Shutdown springboot。
如果部署到weblogic上，也是停掉Springboot 项目后，Sentinel的监听服务（8719）依旧存在。

**Comment by cdfive** [comment]
找到原因了，通过`/shutdown`的endpoint关闭应用时，因为Sentinel监听服务里有两个`ExecutorService`，里面的线程并未完全销毁，导致应用进程依然存活，监听服务依旧还在。

在应用里定义一个`listener`监听`SpringContext`关闭事件，里面通过`CommandCenter#stop`停止Sentinel监听服务试试：
```java
@Component
public class ApplicationShutDownListener implements ApplicationListener<ContextClosedEvent> {

    private static final Logger LOGGER = LoggerFactory.getLogger(ApplicationShutDownListener.class);

    @Override
    public void onApplicationEvent(ContextClosedEvent contextClosedEvent) {
        try {
            LOGGER.info("spring context closed, stop sentinel commend center");
            CommandCenterProvider.getCommandCenter().stop();
        } catch (Exception e) {
            LOGGER.error("stop sentinel commend center error", e);
        }
    }
}
```

参考issue：[https://github.com/alibaba/Sentinel/issues/345](https://github.com/alibaba/Sentinel/issues/345)

参考资料：
springboot通过shutdown进程依然存活的问题：[https://www.jianshu.com/p/7f76b8e1b6b8](https://www.jianshu.com/p/7f76b8e1b6b8)

**Comment by sczyh30** [comment]
Also related to https://github.com/alibaba/spring-cloud-alibaba/issues/222

**Comment by dengkj** [comment]
> 找到原因了，通过`/shutdown`的endpoint关闭应用时，因为Sentinel监听服务里有两个`ExecutorService`，里面的线程并未完全销毁，导致应用进程依然存活，监听服务依旧还在。
> 
> 在应用里定义一个`listener`监听`SpringContext`关闭事件，里面通过`CommandCenter#stop`停止Sentinel监听服务试试：
> 
> ```java
> @Component
> public class ApplicationShutDownListener implements ApplicationListener<ContextClosedEvent> {
> 
>     private static final Logger LOGGER = LoggerFactory.getLogger(ApplicationShutDownListener.class);
> 
>     @Override
>     public void onApplicationEvent(ContextClosedEvent contextClosedEvent) {
>         try {
>             LOGGER.info("spring context closed, stop sentinel commend center");
>             CommandCenterProvider.getCommandCenter().stop();
>         } catch (Exception e) {
>             LOGGER.error("stop sentinel commend center error", e);
>         }
>     }
> }
> ```
> 
> 参考issue：#345
> 
> 参考资料：
> springboot通过shutdown进程依然存活的问题：https://www.jianshu.com/p/7f76b8e1b6b8

解决了，谢谢
