### ISSUE TITLE
为什么sentinel控制台不提供持久化

### ISSUE THREAD

**Issue by rocksnaillm** [alibaba/Sentinel#1415]
为什么sentinel控制台不提供持久化规则，实现持久化必须引入其他组件，感觉好麻烦,后续会考虑在sentinel控制台实现持久化吗

**Comment by sczyh30** [comment]
Sentinel dashboard works as a sample for illustrating the features of Sentinel. The community will improve the dashboard continuously. For use-in-production, you may refer to: https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel
