### ISSUE TITLE
8719端口对应的新的IP如何接入?

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#1423]
你好,我们公司的域名只能一个端口对应一个端口
比如dashboard-server端口启动的时候是8080
那么我们申请的端口只能申请80映射8080
但是上报api的端口是8719
这样的话就没办法把数据给上报上去了,只能注册应用,鏃点链路是无法显示的

我看api参数只能指定端口8719,我这边又只能申请新的域名去用80解析8719
这样的情况可否有办法解决?让客户端把数据正常上报
因为我们没办法设置一个域名用80解析多个端口.谢谢

**Comment by jasonjoo2010** [comment]
客户端不是主动上报，而是被动拉取的机制，这种情况下如果一定需要主动上报，这里需要在客户端处进行定制开发。

另外不知道你这个是不是基于容器，如果基于容器，可以考虑增加内部nginx把对应的8719接口通过nginx做本地转发，对外只暴露同一个端口。

**Comment by cookiejoo** [comment]
> 客户端不是主动上报，而是被动拉取的机制，这种情况下如果一定需要主动上报，这里需要在客户端处进行定制开发。
> 
> 另外不知道你这个是不是基于容器，如果基于容器，可以考虑增加内部nginx把对应的8719接口通过nginx做本地转发，对外只暴露同一个端口。

感谢回答,我还以为是我客户端主动上报的,我们的机器不互通,服务端是不允许访问我那台机器的,所以得部署到其他有权限的机器上去
我以为是我客户端主动上报的,所以想通过一个域名直接分发.
感谢解惑

**Comment by jasonjoo2010** [comment]
是的，相当于application又启动了一个简单的8719端口的http服务器
