### ISSUE TITLE
1.7.1 embedded mode no failover when token server is down

### ISSUE THREAD

**Issue by MrcodingZ** [alibaba/Sentinel#1425]
1.7.1版本通过控制台配置tokenServer与tokenClient，集群流控规则可以正常运行。当tokenServer所在应用被异常关闭时，通过控制台看到自主指定的tokenServer还是原来已经被异常关闭的server。连接全部失效，退回单机限流模式。

**Comment by sczyh30** [comment]
We haven't provided failover and scheduling mechanism yet. You may refer to #346 and refactor by yourself.
