### ISSUE TITLE
sentinel是否有权限控制？

### ISSUE THREAD

**Issue by MrSummer33** [alibaba/Sentinel#143]
希望能够对dashboard有权限控制，请问是否有开箱即用的模块？

**Comment by sczyh30** [comment]
Hi, we won't provide authorization support in Sentinel Dashboard. You have to modify the dashboard to add your own auth logic.

**Comment by sczyh30** [comment]
Also see #142

**Comment by sczyh30** [comment]
This will be supported in 1.6.0 with a simple login page (thanks to @cdfive ). See #659 for details.
