### ISSUE TITLE
控制台自动剔除失联机器 Auto-removal for deprecated K8s pod instances in Sentinel dashboard

### ISSUE THREAD

**Issue by zhangxuebao** [alibaba/Sentinel#1432]
你好，使用K8S 部署tomcat，pod 重新创建后，失联，能问下有什么方法可以配置，自动删除，或者K8S 有好的方法？
Hello, use k8s to deploy Tomcat. After the pod is recreated, the connection is lost. Can you ask me what methods can be configured, deleted automatically, or k8s has a good way?

![image](https://user-images.githubusercontent.com/27907749/80298316-99f8a780-87bd-11ea-9cf0-853da17b3e3f.png)
感谢

**Comment by sczyh30** [comment]
It's supported via the property `sentinel.dashboard.autoRemoveMachineMillis`. You may refer to https://github.com/alibaba/Sentinel/wiki/控制台#控制台配置项
