### ISSUE TITLE
同一个域名下，SENTINEL管理后台与项目后台出现COOKIES冲突

### ISSUE THREAD

**Issue by volts88** [alibaba/Sentinel#1434]
问题描述：
       在同一个域名下，不同端口后，登录项目后台时，跟登录SENTINEL后台出现COOKIES冲突，出现页面登录后，在正常操作的情况下，再登录SENTINEL后台监控时，这个时间项目后台需要重新登录，再点击SENTINEL后台管理时，也是需要重新登录。
 期望：
       在同一个域名下，登录不同的项目时，通过SENTINEL后台监控管理时，双方不影响正常登录。
解决方案：
     方法一：在SENTINEL项目配置中，增加以下：server.servlet.session.cookie.name=sentinel，以便于同个域名下不同端口时出现的COOKIES冲突。
    方法二：在文档中，明确告诉使用者，说明存在以上问题，让使用者自己在项目中配置：server.servlet.session.cookie.name=XXXX.

**Comment by sczyh30** [comment]
Thanks for reporting. Fancy a PR to fix it?

**Comment by liuweiGit** [comment]
commit to branch
