### ISSUE TITLE
为什么用非线程安全的HashMap，而不是ConcurrentHashMap?

### ISSUE THREAD

**Issue by MrSummer33** [alibaba/Sentinel#144]
看源码发现很少直接使用ConcurrentHashMap而是通过 ***上锁+copyAndWrite*** 的通过HashMap,来保障线程安全
此处为何不直接使用ConcurrentHashMap？
![image](https://user-images.githubusercontent.com/21139900/45358774-1ea0ad00-b5fd-11e8-83e2-ed93862593b5.png)

**Comment by CarpenterLee** [comment]
The `chainMap` here will only change at the very beginning of the application's start, then it will be stable. So we use *Copy on Write Map* to get higher concurrency performance.

**Comment by MoneyHacker** [comment]
但这个地方，每次chain==null时，不都得加锁判断么？

**Comment by jianbo2018** [comment]
> The `chainMap` here will only change at the very beginning of the application's start, then it will be stable. So we use _Copy on Write Map_ to get higher concurrency performance.

是否多此一举？cmap早就不用分段锁了，所以cmap在读上的并发性能和hashmap是一个量级的吧？
