### ISSUE TITLE
流控中链路配置无效

### ISSUE THREAD

**Issue by alex-he-ops** [alibaba/Sentinel#1440]
我定义了一个请求如下
@GetMapping("/test-a")
    public String testA(){
        testService.doSomething("test");
        return "test-a";
    }
其中 testService 如下(使用了SentinelResource注解)
@SentinelResource("doSomething")
    @Override
    public void doSomething(String str) {
        log.info("do somthing" + str);
    }

在sentinel控制台 为 doSomething资源定义流控规则时 使用如下配置：
阈值类型: QPS 
阈值为: 1 
流控模式: 链路 
入口资源: /test-a 
流控效果: 快速失败

此时对test-a 进行快速多次访问 并没有快速失败 

我使用的 相关依赖如下 
SpringBoot 2.2.6.RELEASE（2.2.2版本同）
SpringCloud Hoxton.SR4
sentinel 1.7.0(1.7.2同)
SpringCloudAlibaba 2.1.0

何种原因可能造成上述错误，还是我的流控规则定义有不合理之处？

**Comment by Ryze-Zhao** [comment]
同问

**Comment by qq502361472** [comment]
我的问题和你一样,求解啊

**Comment by xuepiao10000** [comment]
> 
> 
> 我的问题和你一样,求解啊

具体原因我忘记了，好像是各种相关依赖的版本有问题，可以尝试更新的版本试试。
