### ISSUE TITLE
Question: API Gateway Flow Control

### ISSUE THREAD

**Issue by nitin302** [alibaba/Sentinel#1448]
I'm using the latest version available 1.7.2 with zuul2 and it works as expected.

- I've tested a simple endpoint with Zuul2.
- Attached it to the sentinel dashboard.
- Tried a few flow control rules.

Have a few questions:
1. I see the thresholds (like QPS) given are **per instance**? Is there any way to add **cluster flow control** with zuul2 without the need for envoy? For example, **rate limit per minute** taking into account all the instances in the cluster?

2. In scaling to production with sentinel, Is this below correct? 

a) Use a datasource for rules like zookeeper (is it possible to use postgres?) which provides HA and also supports dynamic push configuration with the dashboard. 
b) The metrics are being pulled by the dashboard server in real time and is stored only for the last 5 minutes, Hence, the disk size should be large enough to handle all those metrics. For the dashboard server what is your recommendation on the below:

- What is the recommended instance size, how can we cluster? What is the limit a single dashboard node can handle?
- What is your recommendation on how to estimate disk size?
- Is it recommended to use one dashboard per microservice?
- How can we scale dashboard?

3. Is there a way to define a custom parameter with which we can flow control, like for example, authenticated username?

4. 1.7.2 has support for dashboard only in chinese, I can see open PRs where a English version is being scoped, but is it on track for release?

**Comment by nitin302** [comment]
Also, Is there a way to add rules for all machines at the same time, I see it per machine level in the UI.

**Comment by sczyh30** [comment]
> 1. I see the thresholds (like QPS) given are per instance? Is there any way to add cluster flow control with zuul2 without the need for envoy? For example, rate limit per minute taking into account all the instances in the cluster?

Cluster flow control for Zuul API gateway has not been supported yet.

For 2, one dashboard may handle about 500 instances. You may need to refactor and scale the dashboard to afford more real-time metrics storage.

> 3. Is there a way to define a custom parameter with which we can flow control, like for example, authenticated username?

You may refer to [parameter flow control](https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-parameter-flow-control/README.md), which supports flow control by parameters.

> 4. 1.7.2 has support for dashboard only in chinese, I can see open PRs where a English version is being scoped, but is it on track for release?

The latest dashboard in English is [1.3.0](https://github.com/alibaba/Sentinel/wiki/Dashboard#2-start-the-dashboard). We may update the English dashboard as soon as 1.8.0 has been released.
