### ISSUE TITLE
Dashbord 升级 登录信息兼容性 bug

### ISSUE THREAD

**Issue by kynightyk** [alibaba/Sentinel#1449]
启动1.7.1版的sentinel后，使用谷歌浏览器访问登录页面时，未显示登录页面，而是直接登录进去了，但sentinel的版本未显示出来，而使用火狐时却是正常的。

**Comment by cdfive** [comment]
直接登录进去是不是可能是缓存？
在chrome里按F12，点上面的console tab看看里面有没有js报错信息，
在network tab里把disable cache勾选，Ctrl+F5刷新浏览器试试。

**Comment by kynightyk** [comment]
js里有报错，错误信息是SyntaxError: Unexpected token o in JSON at position 1，我的network tab里disable cache一直是勾选的。

**Comment by cdfive** [comment]
`SyntaxError: Unexpected token o in JSON at position 1`一般js报错console有详细信息，哪个js哪一行，可以再找一下。推测有可能浏览器端会话信息没完全清除。
在Application tab里把Local  Storage、Session Storage、Cookies里的东西右键-clear，
然后再刷新页面试试。

**Comment by kynightyk** [comment]
谢谢，解决了,是Local Storage里有一个用户登录了(可能是匿名用户)，可是使用1.7.1版后，我启动后从未登录进去过，为啥会有用户登录进去，可以大致的说一下会是什么原因导致的嘛？

**Comment by cdfive** [comment]
服务端session超时时间默认是30分钟，Local Storage是浏览器端的，它没有超时时间，有可能因为之前登录过但没有在界面上点退出Local Storage没有清除掉。推测是这个原因，有可能这是个bug，还不是很确定。如果以后又出现了麻烦再看下哈，看有没有明确复现步骤。

**Comment by kynightyk** [comment]
好的，谢谢。如果后续重新出现了这个问题，我尽量把复现步骤找出来。

**Comment by cdfive** [comment]
找到原因了：
1.6.0版本控制台增加了登录页，当时localStorage存储的值是Object对象，1.7.0版本新增了通过配置参数-Dauth.enabled=false 免登录功能，localStorage值改为了json对象存储，如果老版本浏览器没有点退出登录，然后升级控制台第一次访问页面会出现这个问题。

在浏览器控制台通过Application tab里把Local Storage清除后，以后应该不会出现该问题了。

不容易复现，之前版本兼容性确实没考虑周全，争取下个版本优化下修复这个问题哈！
