### ISSUE TITLE
为什么不像Hystrix使用线程池做隔离级别呢

### ISSUE THREAD

**Issue by 550932785** [alibaba/Sentinel#1450]
为什么不像Hystrix使用线程池做隔离级别呢

我是个菜鸟，之前听我们老师讲课说到Hystrix有很多好处，比如不会卡死tomcat线程，比如超时了可以直接返回，不用去管线程池里的线程具体的返回结果是什么样的，我们老师当时说但凡走网络都建议使用线程池来作为隔离级别，线程池适用范围可以达到99%，所以想咨询您这边一下为啥放弃了使用线程池而使用信号量来作为隔离级别呢。 谢谢 麻烦解答下

**Comment by wavesZh** [comment]
[熔断降级设计理念](https://github.com/alibaba/Sentinel/wiki/%E4%B8%BB%E9%A1%B5#%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7%E8%AE%BE%E8%AE%A1%E7%90%86%E5%BF%B5)

**Comment by cdfive** [comment]
参考：[https://github.com/alibaba/Sentinel/wiki/Sentinel-与-Hystrix-的对比](https://github.com/alibaba/Sentinel/wiki/Sentinel-与-Hystrix-的对比)
