### ISSUE TITLE
这里为啥要用yield没看懂，直接走下一次while循环会有什么问题么

### ISSUE THREAD

**Issue by asasas234** [alibaba/Sentinel#1451]
![image](https://user-images.githubusercontent.com/4795442/80957689-42e67880-8e36-11ea-9762-019862e67fac.png)

**Comment by jasonjoo2010** [comment]
Maybe that will be fine if no yield here but if you arrived here there may be a strict race existed. So a `yield` is more gentle for window creating-refetching.

个人认为不用yield理论上不会有问题，因为yield本身也未必一定会有延时（导致出让处理器），但逻辑如果走到这里，往往代表了出现严格意义上的并发，那么做yield有助于减少不必要的处理器高速缓存失效和重试，并且有利于重排运行优化性能。

**Comment by asasas234** [comment]
> Maybe that will be fine if no yield here but if you arrived here there may be a strict race existed. So a `yield` is more gentle for window creating-refetching.
> 
> 个人认为不用yield理论上不会有问题，因为yield本身也未必一定会有延时（导致出让处理器），但逻辑如果走到这里，往往代表了出现严格意义上的并发，那么做yield有助于减少不必要的处理器高速缓存失效和重试，并且有利于重排运行优化性能。

大佬关于最后1句，有助于减少不必要的处理器高速缓存失效和重试，并且有利于重排运行优化性能。我没太理解和这个有什么关系，有相关的资料推荐么，我了解学习一下

**Comment by jasonjoo2010** [comment]
> > Maybe that will be fine if no yield here but if you arrived here there may be a strict race existed. So a `yield` is more gentle for window creating-refetching.
> > 个人认为不用yield理论上不会有问题，因为yield本身也未必一定会有延时（导致出让处理器），但逻辑如果走到这里，往往代表了出现严格意义上的并发，那么做yield有助于减少不必要的处理器高速缓存失效和重试，并且有利于重排运行优化性能。
> 
> 大佬关于最后1句，有助于减少不必要的处理器高速缓存失效和重试，并且有利于重排运行优化性能。我没太理解和这个有什么关系，有相关的资料推荐么，我了解学习一下

单核心下，yield可以在有并发且已有线程抢先的情况下显式地出让一下调度权限，让竞争线程完成关键指令块从而让自己的重试更有效率；
多核心下，yield则在这个基础上，防止了L1/L2的频繁失效带来的指令周期浪费

Reference:
[1] Thread Scheduling https://www.iitk.ac.in/esc101/05Aug/tutorial/essential/threads/priority.html
[2] Round-robin scheduling https://en.wikipedia.org/wiki/Round-robin_scheduling
[3] Scheduling https://en.wikipedia.org/wiki/Scheduling_(computing)

**Comment by asasas234** [comment]
> https://en.wikipedia.org/wiki/Scheduling_(computing)

感谢回答
