### ISSUE TITLE
Parameter flow control does not take effect for customized entity object

### ISSUE THREAD

**Issue by StruggleAlex** [alibaba/Sentinel#1459]
版本1.7.1，使用热点参数限流，传入的是实体对象无法限流， `CacheMap<Object, AtomicLong> tokenCounters = metric == null ? null : metric.getRuleTokenCounter(rule);` 获取tokenCounters.get(value) 为空，无法获取令牌，对象参数相同的，ConcurrentLinkedHashMapWrapper中获取的map参数都是相同的
![image](https://user-images.githubusercontent.com/34027896/81265456-b6c29400-9075-11ea-898c-63693c083fdd.png)

**Comment by sczyh30** [comment]
传入的 value 和 map 上面的 value 值是否 hashCode 相同？

**Comment by StruggleAlex** [comment]
做过测试，hashCode也是一致的

**Comment by StruggleAlex** [comment]
@sczyh30 实体里面有个变量是空字符串，我在方法中set它为null了。导致最终map保存的时候null，查询的时候是用空字符查询的。我想问一下，执行 ` tokenCounters.putIfAbsent(value, new AtomicLong(maxCount - acquireCount));` 这个方法的时候，value中的那个变量还是”“，为什么第二次请求的时候发现tokencounters中的map中变量值变为null了
