### ISSUE TITLE
Flow control for REST pattern

### ISSUE THREAD

**Issue by ArdenCHan** [alibaba/Sentinel#1460]
## Issue Description
后台没有加@SentinelResource(value = "hello")
但是我要限流@GetMapping(value = "/hello/{hello}")
在UI界面只能加 /hello/xxx 流控 ，不能流控 /hello/*

### How to reproduce it (as minimally and precisely as possible)

1. 后台没有加@SentinelResource(value = "hello")
2. 限流@GetMapping(value = "/hello/{hello}")
3. 随便访问一个/hello/xxx
4. 添加QPS流控
5. 访问其他的 /hello/xxxx

### Tell us your environment
1.7.0

**Comment by sczyh30** [comment]
You may use [Spring Web interceptor](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter) instead.
