### ISSUE TITLE
Dashboard no metric data

### ISSUE THREAD

**Issue by 1657486787** [alibaba/Sentinel#1461]
应用加如了sentinel控制台，但在控制台上不显示信息：
1.应用加的配置如下：
spring:
  application:
    name: /mk-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
2.控制台截图如下：
![image](https://user-images.githubusercontent.com/44360272/81291834-20a26400-909d-11ea-973b-930598b09fd6.png)

**Comment by sczyh30** [comment]
Please check according to the FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ
