### ISSUE TITLE
Support setting class-level defaultFallback for annotation extension

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1464]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Support setting class-level defaultFallback for all resources declared by `@SentinelResource` annotation in the class, so that users don't have to set fallback for each resource respectively. For example:

```java
// All annotation resources in this class will use the default fallback if not set.
@SentinelResource(defaultFallback = "doFallback", fallbackClass = GlobalFallback.class)
public class FooService {

  @SentinelResource
  public Result doSomething(Foo foo) { /*...*/ }

  @SentinelResource
  public Result sayHello(String name) { /*...*/ }
}
```

Note that only `defaultFallback` can be supported due to the restriction of method signature. Contributions are welcomed!

**Comment by zhaoyuguang** [comment]
I will finished it ⛽️

**Comment by zhaoyuguang** [comment]
大佬们 为了在cglib或其他情况 很好兼容性的获取类注解 需要使用AnnotationUtils
引入spring-core 看dubbo写个org.apache.dubbo.config.spring.util.AnnotationUtils也是一样呢
你们怎么看呀？
