### ISSUE TITLE
Improve representation of document

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#147]
## Issue Description

Type: *feature request (document improvement)*

### Describe what happened (or what feature you want)

Until now, the document of Sentinel is put in GitHub Wiki. There are some drawbacks:

- It does not support document for different versions, so users cannot refer to the document for pervious version.
- When users find typos or incorrect content, they can only open an issue, but cannot send a PR to Wiki to fix it.

So we need to improve representation of document (e.g. put the document in the repo directly, then use GitBook or other render engine to generate the document page).

**Comment by tigerMoon** [comment]
how about [Github Pages](https://pages.github.com/)  ?

**Comment by sczyh30** [comment]
We'll use [Docsite](https://github.com/txd-team/docsite) to generate and render the document page (the website of Sentinel): https://github.com/sentinel-group/sentinel-website

**Comment by sczyh30** [comment]
The website has been released here: https://sentinelguard.io/
