### ISSUE TITLE
Support customized origin parser in Dubbo adapter

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1476]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Support customized origin parser in Dubbo provider filter.

**Comment by Garlichead** [comment]
you mean is customer slot chan? 
is support.
like here:
![image](https://user-images.githubusercontent.com/45086633/81912221-df600600-9600-11ea-92c6-ba9801cb4f6a.png)

**Comment by Garlichead** [comment]
Can i claim?

**Comment by DogBaoBao** [comment]
I can do this

**Comment by sczyh30** [comment]
Looking forward to your PR!

**Comment by Garlichead** [comment]
me or ?

**Comment by sczyh30** [comment]
Quick bird picks the PR :)

**Comment by sczyh30** [comment]
This has been resolved for Dubbo 2.6.x adapter via #1555 by @DogBaoBao. PRs for [2.7.x adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-apache-dubbo-adapter) are welcomed!
