### ISSUE TITLE
How to set max allowed response time for a concrete interface?

### ISSUE THREAD

**Issue by yyt6200** [alibaba/Sentinel#1479]
查阅资料，Hystrix 可以支持定义超时时间到具体的某个接口,Sentinel针对这种问题有什么好的解决方案么

**Comment by Garlichead** [comment]
sentinel 好像是可以到应用 比如 A应用消费500QPS B应用消费300QPS 也可以整体消费800QPS.

**Comment by yyt6200** [comment]
感谢回复，不是这个需求。是有些服务接口响应时间比较长，比如上传文件。sentinel似乎不能像hystrix那样指定到某个接口的超时时间

**Comment by Garlichead** [comment]
Sorry, sentinel 熔断这块的处理机制我还不是很熟悉 但是我后续会持续跟进的.
目前我跟进滑动窗口限流的源码中 没有注意到处理超时这块 sentinel 只是将对应的流量进行block控制 对接口的调用似乎做得处理很少 
那这种场景下 不是丧志了hystrix对接口超时的特性了？ 您有没有更过这块实现的源码了？

**Comment by sczyh30** [comment]
Sentinel 支持的熔断降级粒度可以是服务、接口、方法维度，同时支持自定义埋点。参考：

- https://github.com/alibaba/Sentinel/wiki/Guideline:-从-Hystrix-迁移到-Sentinel
- https://github.com/alibaba/Sentinel/wiki/熔断降级
