### ISSUE TITLE
使用配置中心作为规则存储,从dashboard到配置中心不完善

### ISSUE THREAD

**Issue by hexw** [alibaba/Sentinel#1481]
使用配置中心作为规则存储,从dashboard到配置中心不完善,只有一个流控的例子,需要自己手动实现,其他流控,能否做成可配置的

**Comment by sczyh30** [comment]
You may refer https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#Push模式 for refactoring the dashboard. You may also refer to #1453.
