### ISSUE TITLE
Metrics of Sentinel Cost a lot of Memery

### ISSUE THREAD

**Issue by srctar** [alibaba/Sentinel#1484]
# Issue Description
We use sentinel for Flow and Burn, all dependes on **Resource**。

Yesterday，a team of us build a lot of resource(*Just for differentiate it`s dependency ip、method*),  about 3000 resource, cost 6G memery。

It make alot of FGC, even oom。Just because of InMemoryMetricsRepository.java store metrics for 5 minutes， I slow it down to 20s， did nothing， I can just delete their app to ensure our service。

I want to copy these memery to redis， but if same thing happend， 20G is not OK, so, such as https://github.com/alibaba/Sentinel/issues/217 this issue，can sentinel-dashboard query metrics only where the dashboard is open？ Or other way.

英文不佳， 请阅读中文：
贝壳现在有大量的服务在使用Sentinel做熔断限流。 但是有的业务方， 因为依赖方的不稳定性， 却又是强依赖的关系， 针对依赖方的每个ip、每个接口都构造了Sentinel Resource， 一下子把Sentinel Resource膨胀到了3000多个。

Sentinel Dashboard展示图， 源于服务端定时任务向每个客户端查询（集群里的每台dashboard机器都会这么做）。 
客户端少倒罢了， 客户端一多， dashboard IO、线程池就吃紧。 同时，维系长达5分钟的图表，在大量客户端的情况下， 如果客户端使用不当， 例如制造了大量的**Sentinel Resource**，内存是非常吃紧的。
我们昨天因为这个缘故， 先是将堆内存扩容到6G， 管了2小时，然后又大量FGC， 心力交瘁。

对此， 期望dashboard可以考虑下不要将图表存储在内存（目前我们有考虑存redis， 但是面对这种业务方的使用方式，依旧没有从根本上解决问题）。 

### Describe what happened (or what feature you want)
about 3000+(total) sentinel resource make metrics cost 6G + menery。 A lot of FGC, even OOM。

英文不佳， 请阅读中文：
业务方创造了远超期望的sentinel resource， 因为图表一直在向客户端拉QPS之内的， 直接把服务端差点搞崩了。

期望不要将图表存内存， 我觉得图表这种东西， 一般都会搭配监控来看， 比如我就看grandfa或者cat。 Sentinel将图表存磁盘、或者每次都从客户端查， 好像也无碍监控观看。

### Describe what you expected to happen
可以试试每次都从客户端查， 或者将数据存在磁盘

### How to reproduce it (as minimally and precisely as possible)
--

### Tell us your environment
我们是贝壳(ke.com)的预案平台， 基于Sentinel实现了熔断、限流功能。 目前覆盖了大量的贝壳的服务。
dashboard用得不多， 规则配置什么的都独立了。 昨天因为有业务方突然增加了大量的sentinel resource， 突发dashboard 大量 FGC, 才注意到这个问题。 
我们只是简单的针对dashboard做了集群化改造， 别的就什么都没有做了。
### Anything else we need to know?
如果有幸的话， 辛苦关注下哟~

**Comment by sczyh30** [comment]
生产环境建议根据需求 自行改造控制台进行监控数据持久化，或者直接使用云上控制台：https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel

**Comment by Garlichead** [comment]
期待后续的处理思路

**Comment by srctar** [comment]
> 期待后续的处理思路

大佬不愿意做， 只有自己实现了。 dashboard的设计思路很不错， 直接整成磁盘存也没啥毛病。 我就用磁盘来存了， 还可以把监控时间延长。
