### ISSUE TITLE
JVM crashed when trying to start sentinel-dashboard.jar

### ISSUE THREAD

**Issue by yinqingsen** [alibaba/Sentinel#1488]
## Issue Description
运行sentinel  启动成功 一访问就失败
Type: bug report

### Describe what happened (or what feature you want)

执行 java -jar sentinel-dashboard-1.7.0.jar  出现下面的异常

### Describe what you expected to happen

异常信息：

```
# Problematic frame:
# C  [SteinwayMSVCRT.dll+0x14200]
```

### How to reproduce it (as minimally and precisely as possible)

第一次异常：

```
# Problematic frame:
# C  [SteinwayMSVCRT.dll+0x14195]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
```

增加 参数 -XX:+CreateMinidumpOnCrash

failed to write core dump. Minidumps are not enabled by default on client versions of Windows
这行错误没了 
但是还是一访问就挂

### Tell us your environment
1. jdk 版本1.8 

### Anything else we need to know?

完整 错误消息

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006b764200, pid=440, tid=0x000000000000308c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_241-b07) (build 1.8.0_241-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.241-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [SteinwayMSVCRT.dll+0x14200]
#
# Core dump written. Default location: D:\Program\alibabaSential\hs_err_pid440.mdmp
#
# An error report file with more information is saved as:
# D:\Program\alibabaSential\hs_err_pid440.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See
```

**Comment by sczyh30** [comment]
Could you please provide more detailed error information?

**Comment by cdfive** [comment]
You may check the error log file `D:\Program\alibabaSential\hs_err_pid440.log`, which may provide more detail information.
