### ISSUE TITLE
当我在Kubernetes集群部署Sentinel时，关于健康检查出现的问题

### ISSUE THREAD

**Issue by bbqtk** [alibaba/Sentinel#1494]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
应用的健康检查 总是 DOWN 。经过观察 出现 "sentinel":{"status":"DOWN","details":{"dataSource":{},"enabled":true,"dashboard":{"description":"sentinel:8858 can't be connected","status":"DOWN"}}
但是我的确能在Sentinel-dashboard中观察到我的应用，并且它是正常的。但是因为健康检查的原因 导致Kubenetes的livenessProbe/readinessProbe都失败了。应用出现无限重启。
只有当我请求过一次应用后，健康检查才会变为 UP。
我现在的解决方法是 设置 management.health.sentinel.enabled=false 关闭Sentinel相关健康检查。

### Describe what you expected to happen
我希望只要能够在第一次应用健康检查中出现 UP ，或者能否告知我 ，为什么要设计成这种模式。

### How to reproduce it (as minimally and precisely as possible)

1. Sentinel version 1.7.0-1.7.2    SpringBoot 2.2.5 SpringCloud Hoxton.SR3
<img width="424" alt="截屏2020-05-21下午1 07 41" src="https://user-images.githubusercontent.com/19991733/82525485-12a41700-9b64-11ea-94ee-325a90ef77e1.png">

**Comment by sczyh30** [comment]
It's related to Spring Cloud Alibaba. You may ask in https://github.com/alibaba/spring-cloud-alibaba/issues
cc @fangjian0423

**Comment by cdfive** [comment]
可以参考这个PR [https://github.com/alibaba/spring-cloud-alibaba/pull/671](https://github.com/alibaba/spring-cloud-alibaba/pull/671)

Sentinel健康检查包含：检查控制台(Dashboard)和数据源(DataSource)的是否正常。
设计逻辑如下：
1. 检查控制台
  （1) 如果没有配置控制台地址，则在明细里标记dashbord状态为UNKNOWN，描述信息为`dashboard 
  isn't configured`
  （2) 如果配置了控制台地址，则通过`heartbeatSender#sendHeartbeat`向控制台发送一条心跳信息，
  如果发送成功，则在明细里标记dashbord状态为UP; 如果失败则在明细里标记dashbord为DOWN，描述信息为`控制台地址 can't be connected`
2. 检查数据源
  获取所有配置的数据源，对每个类型的数据源通过`AbstractDataSource#loadConfig`加载一次数据，如果没有任何异常(即表示从数据源读取数据正常)，则在明细里标记该数据源状态为UP，如果出现异常则在明细里标记该数据源为DOWN

如果控制台和数据源状态有一个为DOWN，则Sentinel的健康状态为DOWN，反之为UP。

可以排查下控制台检查失败的原因，即为啥发送心跳失败，在Sentienl-record日志里看看。
推测有可能跟Spring容器里Bean以及Sentinel(是否eager)加载顺序有关。

当时提了PR，本机简单自测了下看没问题。因为平常在公司里都是做业务开发，没有啥机会在项目中实践，比如生产环境部署、容器化环境等等，其他情况没能考虑到，非常抱歉因为健康检查的原因给你使用上带来了困扰。

这里有个issue讨论健康检查的设计 [https://github.com/alibaba/spring-cloud-alibaba/issues/842](https://github.com/alibaba/spring-cloud-alibaba/issues/842)
其中有提到，控制台状态不应影响整个Sentinel的健康状态。

issue里作者有建议两种方式：
1. 状态永远是UP，但Dashbord那一段展示是否可连接
2. 额外添加一个配置，控制是否检查Dashboard是否可连接的状态，并且默认应该设置为false

之前设计是因为考虑到，既然配置了控制台地址，那么检查跟控制台是否连通，好像也符合逻辑，这样能及时发现哪些应用跟控制台连接有问题。

个人觉得上面两种建议也挺不错，希望能改进和完善它，看看哪种更好呢？
@bbqtk @sczyh30 @fangjian0423

**Comment by bbqtk** [comment]
@cdfive @sczyh30 非常感谢两位帮助我！我查看了spring-cloud-alibaba中涉及的相关issue https://github.com/alibaba/spring-cloud-alibaba/issues/842 我赞同他的想法。在查阅相关源码后 ，设置 spring.cloud.sentinel.eager=true 后 ，我的问题解决了。
<img width="652" alt="截屏2020-05-22上午11 24 09" src="https://user-images.githubusercontent.com/19991733/82628216-dc779d80-9c1e-11ea-8f46-7804e6259dd3.png">

**Comment by bbqtk** [comment]
@cdfive 赞同您的想法。如果控制台连接出现问题 ，控制台状态改为 OUT_OF_SERVICE ，但并不会影响应用的正常服务。设置 spring.cloud.sentinel.eager=true 或者 management.health.sentinel.enabled=false 可暂时解决该问题

**Comment by sczyh30** [comment]
Also cc @alibaba/spring_cloud_alibaba_team @yuhuangbin

**Comment by qixiaobo** [comment]
> 可以参考这个PR [alibaba/spring-cloud-alibaba#671](https://github.com/alibaba/spring-cloud-alibaba/pull/671)
> 
> Sentinel健康检查包含：检查控制台(Dashboard)和数据源(DataSource)是否正常。
> 设计逻辑如下：
> 
> 1. 检查控制台
>    （1) 如果没有配置控制台地址，则在明细里标记dashbord状态为UNKNOWN，描述信息为`dashboard    isn't configured`
>    （2) 如果配置了控制台地址，则通过`heartbeatSender#sendHeartbeat`向控制台发送一条心跳信息，
>    如果发送成功，则在明细里标记dashbord状态为UP; 如果失败则在明细里标记dashbord为DOWN，描述信息为`控制台地址 can't be connected`
> 2. 检查数据源
>    获取所有配置的数据源，对每个类型的数据源通过`AbstractDataSource#loadConfig`加载一次数据，如果没有任何异常(即表示从数据源读取数据正常)，则在明细里标记该数据源状态为UP，如果出现异常则在明细里标记该数据源为DOWN
> 
> 如果控制台和数据源状态有一个为DOWN，则Sentinel的健康状态为DOWN，反之为UP。
> 
> 可以排查下控制台检查失败的原因，即为啥发送心跳失败，在Sentienl-record日志里看看。
> 推测有可能跟Spring容器里Bean以及Sentinel(是否eager)加载顺序有关。
> 
> 当时提了PR，本机简单自测了下看没问题。平常在公司里都是做业务开发，没有啥机会在项目中实践，比如生产环境部署、容器化环境等等，其他情况没能考虑到，非常抱歉因为健康检查的原因给你使用上带来了困扰。
> 
> 这里有个issue讨论健康检查的设计 [alibaba/spring-cloud-alibaba#842](https://github.com/alibaba/spring-cloud-alibaba/issues/842)
> 其中有提到，控制台状态不应影响整个Sentinel的健康状态。
> 
> issue里作者有建议两种方式：
> 
> 1. 状态永远是UP，但Dashbord那一段展示是否可连接
> 2. 额外添加一个配置，控制是否检查Dashboard是否可连接的状态，并且默认应该设置为false
> 
> 之前设计是因为考虑到，既然配置了控制台地址，那么检查跟控制台是否连通，好像也符合逻辑，这样能及时发现哪些应用跟控制台连接有问题。建议里状态保持UP，通过明细的`connectable`属性也能指示当前控制台是否可连。
> 
> 个人觉得上面两种建议也挺不错，希望能改进和完善它，看看哪种更好呢？
> @bbqtk @sczyh30 @fangjian0423
> 
> 刚才发现`org.springframework.boot.actuate.health.Status`类里，有4个常量值：
> `UNKNOWN`,`UP`,`DOWN`,`OUT_OF_SERVICE`
> 如果控制台连接有问题，是否可以考虑用`OUT_OF_SERVICE`

不可以哦 out_of_service是会标记状态码500的
参考 https://github.com/keerthi11/Spring/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/HealthMvcEndpoint.java#L89
目前只有OK和UNKNOWN是实质上的200状态码（符合k8s的就绪）
https://github.com/alibaba/spring-cloud-alibaba/pull/1586
其实起不来倒不打紧【研发人员会介入调查】 反而是用的过程中出现了问题就麻烦了 突然就绪探针将pod从upstram全部摘除 导致大量502 引发线上事故

**Comment by cdfive** [comment]
@qixiaobo 感谢实践经验分享！
> 目前只有OK和UNKNOWN是实质上的200状态码（符合k8s的就绪）

赞同PR#L150里builder.down()改为builder.unknown()。
有个小疑问是里面的detailMap它的状态也需要改为Status.UNKNOWN吗？如果外面build是unknown，里面是down有没有影响？
如果没有影响是否语义上跟更好

**Comment by qixiaobo** [comment]
> @qixiaobo 感谢实践经验分享！
> 
> > 目前只有OK和UNKNOWN是实质上的200状态码（符合k8s的就绪）
> 
> 赞同PR#L150里builder.down()改为builder.unknown()。
> 有个小疑问是里面的detailMap它的状态也需要改为Status.UNKNOWN吗？如果外面builder是unknown，里面是down有没有影响？
> 如果没有影响是否语义上会更好

无影响 但是这样会造成理解上的二义性 在测试用例里面会一会UNKNOWN和DOWN.getCode()来回判断 造成理解上的不便
其实最好的是springboot支持一个新的语义【类似于可降级】此时不需要采取UNKNOWN的语义 不过这样代价较高（某种意义上来说UNKNOWN也是合理的 假设sentinel-dashboard超时 这边给个DOWN也有点奇妙）

**Comment by fireflyhoo** [comment]
这么坑爹啊 ▄█▀█●
