### ISSUE TITLE
📢Alibaba Summer of Code 2020-Sentinel

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1497]
Welcome to the open-source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summertime to participate in the open-source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
-  Get a scholarship from Alibaba;
- Obtain an open-source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open-source project!

## Our Mentor

- Eric Zhao (@sczyh30), Sentinel project maintainer

## Apply Now!

Idea list (feel free to submit new ideas): 

- Overview: https://github.com/alibaba/Sentinel/wiki/ASoC-Idea-List#asoc-2020-idea-list
- https://github.com/alibaba/Sentinel/labels/ASoC2020
- https://github.com/alibaba/sentinel-golang/labels/ASoC2020

You can click on this link to apply directly:

- Chinese: https://developer.aliyun.com/topic/summerofcode2020
- English: https://www.alibabacloud.com/campaign/summerofcode2020

![image](https://user-images.githubusercontent.com/9434884/82532505-1c357b00-9b74-11ea-8606-5d222847df78.png)

## Timeline⏳

![image](https://user-images.githubusercontent.com/9434884/82532491-1049b900-9b74-11ea-9a91-7dab46aa10d2.png)

## Contact us!

Gitter: https://gitter.im/alibaba/Sentinel

**Comment by yunfeiyanggzq** [comment]
ASOC is  great, I will work hard for it。

**Comment by sczyh30** [comment]
> ASOC is great, I will work hard for it。

Feel free to submit a proposal regarding the ideas you'd like to work for (not restricted to listed ideas above).

**Comment by sczyh30** [comment]
Idea list overview (not restricted to these ideas): https://github.com/alibaba/Sentinel/wiki/ASoC-Idea-List#asoc-2020-idea-list

**Comment by Pratham31** [comment]
Hello Sir!,
Greetings of the day.
I would love to work on Sentinel polyglot implementation (C++/Go/Rust/Node.js) idea. But can you explain a small overview of it because it's my first time in open source projects and I will work hard for it, please help @sczyh30 .

**Comment by sczyh30** [comment]
For all potential ASoC applicants: the deadline of proposal submission is June 30th. Don't forget to prepare your resume, proposal as well as the demo that can show your ability regarding your ideas.

**Comment by sczyh30** [comment]
- ASoC 2020 中期总结（自适应流控）by @mastertiller: #1641 
- ASoC 2020 中期总结（集群并发流控）by @yunfeiyanggzq: #1639

**Comment by sczyh30** [comment]
- ASoC 2020 final summary (Q-learning adaptive flow control) by @mastertiller: #1704
- ASoC 2020 final summary (distributed concurrency limiting) by @yunfeiyanggzq: #1697

Thanks for our two excellent students!
