### ISSUE TITLE
Sentinel Dashboard jar in maven

### ISSUE THREAD

**Issue by menqiuchen1017** [alibaba/Sentinel#1498]
为什么阿里云和maven官网上Dashboard只有0.1.0和0.1.1，sentinel其它组件的最新版本都1.7.x了。
sentinel-dashboard停止更新了吗？

**Comment by sczyh30** [comment]
Sentinel dashboard is not published to Maven anymore. You may download the dashboard in https://github.com/alibaba/Sentinel/releases

**Comment by menqiuchen1017** [comment]
请问为什么不会更新maven了？出于什么原因呢？谢谢

**Comment by menqiuchen1017** [comment]
> Sentinel dashboard is not published to Maven anymore. You may download the dashboard in https://github.com/alibaba/Sentinel/releases
请问为什么不会持续更新maven了？出于什么原因呢？谢谢
ps:我们公司内网软件仓库只能从maven上拉取开源jar
