### ISSUE TITLE
System rule does not take effect

### ISSUE THREAD

**Issue by dragon-yuan** [alibaba/Sentinel#1499]
## Issue Description
bug report

### Describe what happened (or what feature you want)
System role no effect. Maybe I used it wrong, how can I use it correctly 

### Describe what you expected to happen
![](https://img-dragon-blog.oss-cn-beijing.aliyuncs.com/github/issue/20200522165944.jpg)
![](https://img-dragon-blog.oss-cn-beijing.aliyuncs.com/github/issue/20200522165959.jpg)
[{"app":"sharks-dubbo-cart","avgRt":-1,"gmtCreate":1590060540962,"gmtModified":1590135816265,"highestCpuUsage":0.1,"highestSystemLoad":-1.0,"id":7,"ip":"10.155.30.235","maxThread":-1,"port":8719,"qps":-1.0},{"app":"sharks-dubbo-cart","avgRt":-1,"gmtCreate":1590135764265,"gmtModified":1590137579548,"highestCpuUsage":-1.0,"highestSystemLoad":-1.0,"id":8,"ip":"10.155.30.235","maxThread":-1,"port":8719,"qps":1.0}]

### How to reproduce it (as minimally and precisely as possible)
Local debugging

### Tell us your environment
sentinel version 1.7.0
nacos version 1.1.4
dubbo version 2.5.7

**Comment by sczyh30** [comment]
Please ensure your customized resource was defined as "inbound traffic" (provided `EntryType.IN` when wrapping with `SphU.entry(xxx, trafficType)`).

**Comment by dragon-yuan** [comment]
```
public void threadLimit() {
        ExecutorService executorService = new ThreadPoolExecutor(10, 10, 1000, TimeUnit.MILLISECONDS,
                new LinkedBlockingDeque(), new ThreadFactoryBuilder().setNameFormat("package-task-%d").build());
        for (int i = 0; i < 10; i++) {
            executorService.submit(new MyThread());
            try {
                // Thread.sleep(3000);
            } catch (Exception e) {
            }
        }

        for (int i = 0; i < threadCount; i++) {
            Thread entryThread = new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        Entry entry = null;
                        try {
                            entry = SphU.entry("system-test", EntryType.IN);
                            pass.incrementAndGet();
                            try {
                                TimeUnit.MILLISECONDS.sleep(20);
                            } catch (InterruptedException e) {
                            }
                        } catch (BlockException e1) {
                            System.out.println("[systen] has been protected! Time = " + System.currentTimeMillis());
                            block.incrementAndGet();
                            try {
                                TimeUnit.MILLISECONDS.sleep(20);
                            } catch (InterruptedException e) {
                            }
                        } finally {
                            total.incrementAndGet();
                            if (entry != null) {
                                entry.exit();
                            }
                        }
                    }
                }
            });
            entryThread.setName("working-thread");
            entryThread.start();
        }
    }
```

**Comment by sczyh30** [comment]
I've tested with your code snippet and it did take effect. Maybe you may check your rules and logs.
