### ISSUE TITLE
spring cloud alibaba Sentinel integrated spring cloud gateway dynamic current limiting problem

### ISSUE THREAD

**Issue by hb18218411653** [alibaba/Sentinel#1503]
<!-Here is for bug reports and feature requests ONLY!

If you're looking for help, please check our mail list and the Gitter room.

Please try to use English to describe your issue, or at least provide a snippet of English translation.
->

## Issue Description

Type: * bug report * or * feature request *

spring cloud gateway fuse downgrade current limiting

### Describe what happened (or what feature you want)
I want to know whether the fuse downgrade and current limiting rules for gateway routing are loaded through GatewayApiDefinitionManager and GatewayRuleManager. Where is this part of the configuration maintained in the console, or do I need to implement the console maintenance function myself?

### Tell us your environment
linux, springboot, spring cloud gateway

### Anything else we need to know?

**Comment by cdfive** [comment]
Refer to: 
[https://github.com/alibaba/Sentinel/wiki/网关限流](https://github.com/alibaba/Sentinel/wiki/网关限流)
[https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-支持](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-支持)

**Comment by sczyh30** [comment]
For circuit breaking you may set normal `DegradeRule` to your gateway route or customized API group.
