### ISSUE TITLE
Sentinel gateway flow cluster mode?

### ISSUE THREAD

**Issue by AnoYuan** [alibaba/Sentinel#1505]
请问sentinel gateway flow 有没有集群模式

**Comment by AnoYuan** [comment]
例如我在spring cloud gateway上使用sentinel的GatewayRuleManager，GatewayFlowRule
由于我gateway要部署多个，所以sentinel-gateway需要有集群模式支持，请问目前支持这个功能吗

**Comment by sczyh30** [comment]
It's not supported yet. You may use cluster FlowRule instead.

**Comment by Nirvana2047** [comment]
Hi,For "Sentinel gateway flow cluster mode",Is there any support now? If not, what version is expected to add relevant features
