### ISSUE TITLE
@SentinelResource  按照官方文档配置之后，通过gateway访问接口，被限流后自定义限流异常不生效

### ISSUE THREAD

**Issue by Lucas-MorningStar** [alibaba/Sentinel#1506]
自定义限流：
![image](https://user-images.githubusercontent.com/33246833/82893070-103a2680-9f83-11ea-9740-3d1406546cb5.png)
![image](https://user-images.githubusercontent.com/33246833/82893114-1e884280-9f83-11ea-94fe-22d162711229.png)

接口请求效果：
![image](https://user-images.githubusercontent.com/33246833/82892964-eed93a80-9f82-11ea-8fac-8be6d1bbaf9b.png)

**Comment by cdfive** [comment]
`sentinel-web-servlet`或`sentinel-spring-webmvc-adapter`适配默认会提示这个信息`Blocked by Sentinel (flow limiting)`。
看上去是注解未生效，检查是否成功配置了`Spring AOP`或者`AspectJ`。

参考：
[https://github.com/alibaba/Sentinel/wiki/注解支持#spring-aop](https://github.com/alibaba/Sentinel/wiki/注解支持#spring-aop)
[https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-适配](https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-适配)

**Comment by sczyh30** [comment]
Refer #1198

**Comment by Lucas-MorningStar** [comment]
感谢！！！



---原始邮件---
发件人: "cdfive"<notifications@github.com&gt;
发送时间: 2020年5月31日(周日) 晚上10:29
收件人: "alibaba/Sentinel"<Sentinel@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Lucas-MorningStar"<1335529700@qq.com&gt;;
主题: Re: [alibaba/Sentinel] @SentinelResource  按照官方文档配置之后，通过gateway访问接口，被限流后自定义限流异常不生效 (#1506)




 
sentinel-web-servlet或sentinel-spring-webmvc-adapter适配默认会提示这个信息Blocked by Sentinel (flow limiting)。
 看上去是注解未生效，检查是否成功配置了Spring AOP或者AspectJ。
 
参考：
 https://github.com/alibaba/Sentinel/wiki/注解支持#spring-aop
 https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-适配
