### ISSUE TITLE
Support Dubbo generic invocation? Dubbo 泛化调用是否支持限流？

### ISSUE THREAD

**Issue by shuohao** [alibaba/Sentinel#1509]
![image](https://user-images.githubusercontent.com/4637107/82994276-759a2000-a034-11ea-8e1f-ddc01d2eef10.png)

**Comment by sczyh30** [comment]
You may leverage [parameter flow control](https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-parameter-flow-control/README.md) to set different threshold for different services, or use customized entry resource.
