### ISSUE TITLE
根据应用来源限流，控制台不支持展示区分来源的流量信息

### ISSUE THREAD

**Issue by yangyiweigege** [alibaba/Sentinel#1512]
当dubbo根据 调用来源限流的时候  sentinel-dashboard 上 只有总的流量展示。并没有 对应的来源 的流量展示。。。这里能否在sentinel-core包里 做下改造。。把带有来源信息的流量 也输出在监控的持久化日志中。。。resource以调用的来源应用名前缀区分。。。这样子 sentinel-dashboard也能展示出对应的监控。

**Comment by sczyh30** [comment]
Good idea, but this might bring additional resource footprint (the metric log will be very large). Any ideas to improve it?

**Comment by yangyiweigege** [comment]
> Good idea, but this might bring additional resource footprint (the metric log will be very large). Any ideas to improve it?

我看了你们的源代码。originNode中已经存储了来源以及流量。只是没有持久化到日志。。。我觉得一般来源只是针对dubbo的提供者。日志数量也还好吧。。

**Comment by sczyh30** [comment]
It could be enormous if the amount of origins is large. You may refactor the adapter by yourself if really needed.

**Comment by HoweChen** [comment]
Same request here, looking forward to it really.
