### ISSUE TITLE
sentinel 规则优先级 怎么才能根据api作为最高优先级，比如一个服务user_service定义的规则，如果服务中包括的api /user/login 定义了规则就安/user/login定义的来执行

### ISSUE THREAD

**Issue by jiuli** [alibaba/Sentinel#1513]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please illustrate the detail of your scenario?

**Comment by sczyh30** [comment]
Closing the issue due to no feedback.
