### ISSUE TITLE
spring-cloud-alibaba-sentinel-datasource Nacos 1.2.1 need username/password attribute

### ISSUE THREAD

**Issue by small-steps** [alibaba/Sentinel#1517]
sentinel 存储规则到 nacos v1.2.1 (需要用户名密码)，spring-cloud-alibaba-sentinel-datasource 当前客户端最新版本中没有用户名密码配置项，想问下如果要用1.2.1(需要鉴权)的nacos 要怎么配置

**Comment by cdfive** [comment]
May refer to [https://github.com/alibaba/spring-cloud-alibaba/issues/1350](https://github.com/alibaba/spring-cloud-alibaba/issues/1350)
