### ISSUE TITLE
Will enabling safeMode of fastjson affect Sentinel?

### ISSUE THREAD

**Issue by ilaotan** [alibaba/Sentinel#1518]
如题，我们现在考虑开启safeMode，但是不知道是否影响sentinel的相关功能？

**Comment by cdfive** [comment]
Refer to:
[https://help.aliyun.com/noticelist/articleid/1060343604.html](https://help.aliyun.com/noticelist/articleid/1060343604.html)
[https://github.com/alibaba/fastjson/wiki/fastjson_safemode](https://github.com/alibaba/fastjson/wiki/fastjson_safemode)
[https://github.com/alibaba/fastjson/wiki/security_update_20200601](https://github.com/alibaba/fastjson/wiki/security_update_20200601)

According to the document, the support for `safeMode` is to completely disabled `autoType`,
and the `autoType` seems disabled by default.

```java
System.out.println(ParserConfig.getGlobalInstance().isAutoTypeSupport());
```
Using this to view whether it's enable.

The `autoType` feature seems using like this:
```json
{
"@type":"com.demo.dto.A",
"name":"zhangsan",
"age":"18"
}
```
Sentinel doesn't use the generic json convert, so I think it has no impact.
It'll be careful if try it in the test environment first.
