### ISSUE TITLE
控制台设置或修改规则后，规则被清空，没有报错

### ISSUE THREAD

**Issue by jukejuke** [alibaba/Sentinel#1519]
![image](https://user-images.githubusercontent.com/13484429/83517775-0fb60880-a50c-11ea-8b93-0ed8c4d54984.png)
控制台设置或修改规则后，规则被清空，没有报错,提示成功
springmvc 环境

**Comment by jukejuke** [comment]
![image](https://user-images.githubusercontent.com/13484429/83518012-75a29000-a50c-11ea-9669-ffb456b0c1de.png)

![image](https://user-images.githubusercontent.com/13484429/83517995-6f141880-a50c-11ea-9dfb-0b47b0300dcd.png)

**Comment by cdfive** [comment]
Refer to [https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到](https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到)
May check the version of `fastjson` in your application.

**Comment by sczyh30** [comment]
Any feedback? @jukejuke
