### ISSUE TITLE
https://github.com/alibaba/Sentinel/wiki/System-Protection is broken

### ISSUE THREAD

**Issue by lokeshmadan** [alibaba/Sentinel#1521]
## Issue Description
https://github.com/alibaba/Sentinel/wiki/System-Protection is broken. 

Type: *bug report* 

### Describe what happened (or what feature you want)
When navigating through https://github.com/alibaba/Sentinel/wiki/How-to-Use#api-2 clicking on System Protection to get more detailed wiki, seems like https://github.com/alibaba/Sentinel/wiki/System-Protection is broken and it;s redirecting to https://github.com/alibaba/Sentinel/wiki

### How to reproduce it (as minimally and precisely as possible)

1.  Navigate to https://github.com/alibaba/Sentinel/wiki/How-to-Use#api-2
2. Click on System Protection
3. 

### Tell us your environment

Using Firefox 76.0.1 (64-bit)

**Comment by sczyh30** [comment]
Fixed to https://github.com/alibaba/Sentinel/wiki/Adaptive-System-Protection
Thanks for reporting!
