### ISSUE TITLE
集群限流token client netty请求正常，服务端能接收到消息，  client无法接收到server端返回的消息

### ISSUE THREAD

**Issue by maxiaolong** [alibaba/Sentinel#1527]
client端抛出request timeout异常

**Comment by maxiaolong** [comment]
version: 1.7.0

**Comment by yunfeiyanggzq** [comment]
话说这个是在什么场景下发生的？

**Comment by sczyh30** [comment]
Please check whether your network env is unstable. You may also refer to the [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#sentinel-集群限流相关) to check relevant logs.
