### ISSUE TITLE
控制台小问题

### ISSUE THREAD

**Issue by wanhuhou** [alibaba/Sentinel#153]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
控制台设置规则失败提示 失败!没有提示信息，并且日志也需要安日期分开，日志的量增长很快，到最后要手动删除，希望改进下 省的使用者自己去配置了

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Resolved in #202.
