### ISSUE TITLE
添加sentinel之后 项目的默认返回数据格式从json变成xml了 怎么搞？

### ISSUE THREAD

**Issue by lyh19940304** [alibaba/Sentinel#1537]
web项目之前接口都是正常返回json串  添加了sentinel之后 所有的接口返回都变成了xml  如图
![Issure](https://user-images.githubusercontent.com/57309231/84159658-e4995f00-aa9f-11ea-9edc-592887efa45e.png)
当然了  添加 produces={"application/json"} 之后就可以了  但是不想每个接口都加这么个东西哦  太折磨人了。

**Comment by cdfive** [comment]
Try exclude `com.fasterxml.jackson.dataformat` in the depenency of sentinel starer.
```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    <version>2.2.1.RELEASE</version>
    <exclusions>
        <exclusion>
            <artifactId>jackson-dataformat-xml</artifactId>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

Maybe `com.fasterxml.jackson.dataformat` optional is better. 
cc @fangjian0423  @sczyh30

**Comment by sczyh30** [comment]
cc @alibaba/spring_cloud_alibaba_team

**Comment by sczyh30** [comment]
@lyh19940304 Any feedback?

**Comment by loncool** [comment]
是啊。。 怎么处理？？？

**Comment by lyh19940304** [comment]
> Try exclude `com.fasterxml.jackson.dataformat` in the depenency of sentinel starer.
> 
> ```
> <dependency>
>     <groupId>com.alibaba.cloud</groupId>
>     <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
>     <version>2.2.1.RELEASE</version>
>     <exclusions>
>         <exclusion>
>             <artifactId>jackson-dataformat-xml</artifactId>
>             <groupId>com.fasterxml.jackson.dataformat</groupId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```
> 
> Maybe `com.fasterxml.jackson.dataformat` optional is better.
> cc @fangjian0423 @sczyh30

3Q 搞定

**Comment by lyh19940304** [comment]
> Try exclude `com.fasterxml.jackson.dataformat` in the depenency of sentinel starer.
> 
> ```
> <dependency>
>     <groupId>com.alibaba.cloud</groupId>
>     <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
>     <version>2.2.1.RELEASE</version>
>     <exclusions>
>         <exclusion>
>             <artifactId>jackson-dataformat-xml</artifactId>
>             <groupId>com.fasterxml.jackson.dataformat</groupId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```
> 
> Maybe `com.fasterxml.jackson.dataformat` optional is better.
> cc @fangjian0423 @sczyh30

3Q 搞定

**Comment by sczyh30** [comment]
Also refer https://github.com/alibaba/spring-cloud-alibaba/issues/1544
