### ISSUE TITLE
sentinel控制台和被集成的springboot项目跨机器如何实现

### ISSUE THREAD

**Issue by Ariel827** [alibaba/Sentinel#1546]
根据wiki上的提示做了springboot项目集成sentinel Dashboard，并且他们同时在本地(127.0.0.1)上启动，是没有问题的  
但是，当集成的sentinel Dashboard在另一台机器上(如：10.24.1.5:8080)，同样的配置参数会导致机器列表正确-实时监控与簇点链路均不会显示任何信息(无论发送多少次请求)，请问如何解决呢

**Comment by sczyh30** [comment]
参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查)，检查下网络是否双向连通。

**Comment by Ariel827** [comment]
了解了，dashboard和项目不可跨局域网实现
