### ISSUE TITLE
sentinel 如何实现动态url流控

### ISSUE THREAD

**Issue by WChCh** [alibaba/Sentinel#1548]
hi，大家好！
我目前打算使用sentinel，但是不知道sentinel如何支持动态url，比如我的url为：localhost:8080/api/{project}/{group}，{project}和{group}为动态变量，我要对这些变量组成的API分别单独做流程。请问大家我如何实现呢？

**Comment by cdfive** [comment]
You may refer to `sentinel-spring-webmvc-adapter`.
* doc: [https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter)
* demo: [https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-spring-webmvc](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-spring-webmvc)

**Comment by WChCh** [comment]
thx, I have a try!
