### ISSUE TITLE
mvn test failed, charset problem

### ISSUE THREAD

**Issue by xiby** [alibaba/Sentinel#1549]
## Issue Description

bug report

### Describe what happened (or what feature you want)

when running 
```bash
mvn test
```
to run all test cases in powershell of Windows 10, it failed when running cases in file com.alibaba.csp.sentinel.transport.command.http.HttpEventTaskTest.java, and here are some pictures about the failure:
![image](https://user-images.githubusercontent.com/19930925/84669481-7ea54f80-af57-11ea-9cb0-eefc4d804dfb.png)
 
### Describe what you expected to happen

When run
```bash
mvn test
```
all test cases should success.

### How to reproduce it (as minimally and precisely as possible)

1. enter the root directory of Sentinel
2. run command mvn test

### Tell us your environment

os: Windows 10
maven version: 3.6.3

### Anything else we need to know?

As the hint information indicates, maybe it should blame to the charset. After some search, I found that add 
```xml
<argLine>-Dfile.encoding</argLine>
```
property in root pom.xml of plugin maven-surefire-plugin, as follow
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- CircleCI build workaround -->
                    <argLine>@{argLine} -Xms1024m -Xmx2048m</argLine>
                    <argLine>-Dfile.encoding</argLine>
                    <useSystemClassLoader>false</useSystemClassLoader>
                </configuration>
</plugin>
```
After added this, all test cases can be passed.

**Comment by sczyh30** [comment]
We may add `-Dfile.encoding=UTF-8` to JVM args of maven-surefire-plugin. Would you like to submit a PR to fix it?

**Comment by xiby** [comment]
> We may add `-Dfile.encoding=UTF-8` to JVM args of maven-surefire-plugin. Would you like to submit a PR to fix it?

OK, I will fix it, and forget my typo :P
