### ISSUE TITLE
Can I set a max timeout time?

### ISSUE THREAD

**Issue by destinym** [alibaba/Sentinel#155]
## Issue Description

feature request

### Describe what happened (or what feature you want)
I want to set a value (max timeout time), when the server handle request time  beyond this value, Sentinel will failover.

### Describe what you expected to happen
Maybe server has some bugs, and some requests is so slowly(And not frequently used). 
Then we need to wait 5 times call this method, can trigger failover.
It may block other request.

**Comment by CarpenterLee** [comment]
Degrade rule can satisfy your requirements. Refer [熔断降级](https://github.com/alibaba/Sentinel/wiki/%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7) to learn more.

**Comment by sczyh30** [comment]
Hi, Sentinel cannot "cut down" your slow hanging requests directly. All it can do is to degrade when response time of several recent requests exceeds the threshold.
