### ISSUE TITLE
transport module SimpleHttpClient 400 but no any logs

### ISSUE THREAD

**Issue by mobile664042** [alibaba/Sentinel#1551]
sentinel及sentinel控制台版本：1.6.3
假设项目demo接入sentinel控制台，如果demo所在服务器并不能连接到sentinel控制台，demo并没有任何错误日志(cat /home/ordinaryUser/logs/csp/sentinel-record.log.2020-06-16.0, 项目日志中也没有)， 给排查问题带来很大难度。

最后通过arthas监听发现是网络连接不通400（watch com.alibaba.csp.sentinel.transport.heartbeat.client.SimpleHttpClient request returnObj）, 后面改成外网ip才可以正常访问到sentinel控制台(之前是填的内网ip，暂不知道为什么)

![image](https://user-images.githubusercontent.com/1433479/84730714-8dc4e580-afc9-11ea-86c7-3d9d2c92fbb9.png)

**Comment by sczyh30** [comment]
This has been improved in #1303. You may upgrade to the latest version.
