### ISSUE TITLE
spring-cloud-alibaba-sentinel 2.2+ web adapter ErrorEntryFreeException when visiting view by forward:/xxx

### ISSUE THREAD

**Issue by sevens66** [alibaba/Sentinel#1552]
spring-cloud-alibaba-dependencies :  2.2.1
spring-boot-dependencies : 2.2.8.RELEASE

## Issue Description

*bug report*

### Describe what happened (or what feature you want)

采用demo里面的最小化功能。WebMvcConfigurer添加

```java
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/").setViewName("forward:/static/index.html");
        registry.addViewController("/favicon.ico").setViewName("forward:/static/favicon.ico");
        registry.addViewController("/index.html").setViewName("forward:/static/index.html");

    }
```

或者加一个重定向controller

```java
@Controller
 public class Test2Controller {

    @GetMapping("/bb/test2")
    public String hello() {
        return "forward:/template";
    }
}
```

访问  所有带重定向的连接如 /index.html 或 /bb/test2，均会报告ErrorEntryFreeException

```
com.alibaba.csp.sentinel.ErrorEntryFreeException: The order of entry exit can't be paired with the order of entry, current entry in context: </template>, but expected: </bb/test2>
 ```

### Describe what you expected to happen
直接访问/static/index.html  或者  /template 正常

### How to reproduce it (as minimally and precisely as possible)

此功能在
spring-cloud-alibaba-dependencies.version版本 2.1.0.RELEASE
sentinel 版本1.6.3
下正常

经测试，spring-cloud-alibaba 版本2.2以上均有问题

### Tell us your environment
win7    
java8

**Comment by sczyh30** [comment]
Maybe related to #1531, #1482

**Comment by sevens66** [comment]
#1531
