### ISSUE TITLE
FlowSlot 秒级的qps限流是否 可能会出现百分之50的丢失情况

### ISSUE THREAD

**Issue by cruedfish** [alibaba/Sentinel#1553]
## Issue Description

FlowSlot 通过秒级的qps判定该次请求是否通过，使用的是两个500ms的窗口，有可能会出现 从0到1.1s 的时候 ，第一个时间窗口计数却已经被清空的情况（也就是0到0.5s的计数已经被清空）

**Comment by yangyiweigege** [comment]
滑动窗口限流。统计的是最近一秒。并非固定一秒。

**Comment by sczyh30** [comment]
You may choose appropriate bucket amount (sampleCount) for your scenario.
