### ISSUE TITLE
Sentinel large memory footprint, too many LongAdder

### ISSUE THREAD

**Issue by phiepi** [alibaba/Sentinel#1557]
单机配置了18条规则，但是dump内存发现sentinel有很多对象？
![image](https://user-images.githubusercontent.com/30173106/84998047-e63ee300-b181-11ea-9a32-0917330ea64e.png)
还有一个记录日志的一些对象是java.lang.ref.Finalizer 不可回收的，
![image](https://user-images.githubusercontent.com/30173106/84997617-66187d80-b181-11ea-9658-60b940787ea5.png)

**Comment by sczyh30** [comment]
Please check whether the amount of resources is large (display via `/tree` command).

**Comment by sczyh30** [comment]
Any feedback?
