### ISSUE TITLE
Parameter 2 of method sentinelDataSourceHandler in com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration required a single bean, but 2 were found

### ISSUE THREAD

**Issue by Ariel827** [alibaba/Sentinel#1558]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method sentinelDataSourceHandler in com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration required a single bean, but 2 were found:
	- dubboScanBasePackagesPropertyResolver: defined by method 'dubboScanBasePackagesPropertyResolver' in class path resource [org/apache/dubbo/spring/boot/autoconfigure/DubboRelaxedBinding2AutoConfiguration.class]
	- environment: a programmatically registered singleton

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
--------------------------------------------------------------------------------------------------
这种问题如何解决呢

**Comment by sczyh30** [comment]
You may check whether there are incompatible dependencies. You may also ask in https://github.com/alibaba/spring-cloud-alibaba

**Comment by Ariel827** [comment]
由于dubbo版本导致，使用版本2.7.0会有这个问题，修改为2.7..7问题得到解决
2.7.7 fix it.
