### ISSUE TITLE
com.alibaba.csp.sentinel.init.InitFunc可否支持分环境加载

### ISSUE THREAD

**Issue by Ariel827** [alibaba/Sentinel#1560]
我们因为环境的问题，分开持久化了，生产环境持久到了apollo,测试环境持久化到了zookeeper,当客户端从配置中心读取规则时，是否可以分环境加载不同的init()函数

**Comment by sczyh30** [comment]
这个直接在InitFunc里面自己区分即可。

**Comment by cdfive** [comment]
几个思路供参考：
* maven插件打包时区分环境，不同环境打包不同的类

* 在InitFunc里面读取不同环境配置：比如ZookeeperInitFunc在有zk配置时才执行或者XxxInitFunc根据环境加载不同的数据源
