### ISSUE TITLE
How to share the same web server port with user's application for transport module?

### ISSUE THREAD

**Issue by dai19470** [alibaba/Sentinel#1565]
springboot项目集成使用sentinel后部署到docker容器里.但是docker对外只提供一个端口给web使用.请教一下.在不对外提供端口的情况下(默认8719),dashboard和使用sentinel的客户端怎么保持心跳?

**Comment by cdfive** [comment]
目前使用了sentinel的应用端是通过独立的HTTP端口(默认8719)和dashboard交互的，因为应用端可能没有使用spring/springboot，也可能不是web应用。如果使用了springboot web，想仅使用一个端口，目前是不支持的。

是否需要共用一个web端口以及如何支持欢迎一起讨论哈~
cc @sczyh30 @jasonjoo2010

**Comment by dai19470** [comment]
您好,我的解决方案是共用一个web端口:
1. 不使用sentinel-tranport下面的模块.自己增加定时任务向dashboard的路径/registry/machine 发送数据,配置ip和port为springboot(sentinel应用端)web的ip和端口,
![image](https://user-images.githubusercontent.com/21135250/85945319-97f2c680-b96f-11ea-98d4-0651cd63796e.png)

2. 参照sentinel-transport-common下com.alibaba.csp.sentinel.command.handler.一一对应在springboot的项目(sentinel应用端口)增加controller.如下图
![image](https://user-images.githubusercontent.com/21135250/85945274-43e7e200-b96f-11ea-85ae-6d99ffd3b410.png)
![image](https://user-images.githubusercontent.com/21135250/85945394-09327980-b970-11ea-97b7-c94cea6dfee3.png)

**Comment by jasonjoo2010** [comment]
If it really matters i have another idea that,

0. Introduce a new configuration defining the prefix of path to hook in, for instance, `transport-prefix`
1. Introduce new module, for instance, `sentinel-transport-springboot`, intercepting into springboot
2. Introduce new module, for instance, `sentinel-transport-servlet`, providing SentinelTransportServlet to register
3. Other frameworks adaption.

Follow the sentinel way: Introduce what you want and you have.

**Comment by dai19470** [comment]
@jasonjoo2010  Yeah! i used like your idea :
![image](https://user-images.githubusercontent.com/21135250/86220548-54d66480-bbb6-11ea-889c-a207ea40c1d7.png)
 my code  is based on official Sentinel for  secondary development, and has a big different with the official code,so if share my code that  is of small significance(我的代码时基于官方代码二次开发的,和官方代码差别很大,所以贡献出来没有多大意义,可以的话联系我提供一个通用的,为sentinel贡献一份力量)

**Comment by jasonjoo2010** [comment]
@sczyh30 @cdfive   so what do you think about it?

If it's worthy we should make it agile because here's a nearly completed implementation of them.

**Comment by shenbaoyong** [comment]
I have a idea, I create a new module named sentinel-transport-spring-mvc, implements tow interfaces of spring-mvc(SentinelApiHandlerAdapter-HandlerAdapter SentinelApiHandlerMapping-HandlerMapping), mapping the api of dashboard want to visit to SentinelApiHandler(CommandHandler). In this way, we no need update the existing module.
（我有一个想法，我新加了一个模块sentinel-transport-spring-mvc,实现spring-mvc里面的HandlerAdapter和HandlerMapping，把控制台需要访问的接口映射到CommandHandler。这样不需要改动已有的模块，CommandHandler的逻辑也不需要重新实现一遍）

**Comment by cdfive** [comment]
@shenbaoyong Good idea! It really solved the problem.
