### ISSUE TITLE
Prometheus metrics extension need a tag to distinguish [IN] from [OUT]

### ISSUE THREAD

**Issue by Billzaifei** [alibaba/Sentinel#1566]
Issue Description
Type: feature request

Describe what happened (or what feature you want)
For the below interface, I used it to export prometheus metrics.
com.alibaba.csp.sentinel.metric.extension.MetricExtension

Take the method[addPass(String resource, int n, Object... args)] for example.
I want to distinguish [in] type from [out] type using it as the prometheus tag. #provider[in]/consumer[out]

So I think I need a feature replacing the input String parameter[resource] with the below class type:

com.alibaba.csp.sentinel.slotchain.ResourceWrapper

**Comment by sczyh30** [comment]
#1665 provides a temporary (and compatible) solution. The MetricExtension SPI will be refactored in upcoming 1.8.x+ version.
