### ISSUE TITLE
Sentinel Dash board 多控制台部署和主从问题

### ISSUE THREAD

**Issue by todyhuang** [alibaba/Sentinel#1567]
## Issue Description

请问dash board 控制台可以部署多个吗或者有dashboard主从或者集群模式?
现在情况是一台dashboard挂了，限流就失去作用了。
如果启动多个dash board,dash board之间也没办法通信。。。

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
Dashboard is optional for application which Integrated with Sentinel.
If dashboard is down, we can't connect with application with dashboard UI
, but the flow controll will still take effect(If the flow rules exists in the memory of application).

#241 and #363 have more discussions about deploying dashboard.

**Comment by bjo2008cnx** [comment]
开源版本的MetricFetcher只将metric数据保存在内存在，但是实际工程中落地时， 一般会对metrics数据进行持久化.  在生产环境中， 虽然Dashboard挂掉不影响限流功能的使用，但是MetricFetcher不能工作会丢失metric数据。而且，每个Dashboard中的MetricFetcher 进行fetchAll的操作，如果部署了多个Dashboard，存在metric数据重复和负载均衡问题。

**Comment by yangyiweigege** [comment]
挂了并不会影响限流 只是没监控。高可用可以这么搞。通过zk实现主备切换，自己二次开发。

**Comment by todyhuang** [comment]
哦，你的意思是DASHBOARD，如果上面做了配置，通知到每个服务的SENTINEL客户端，然后客户端做保存flow rules.所有的限留客户端自己完成。  但是如果想针对一个接口启用SENTINEL 集群模式 ， 客户端与客户端之间也会进行通信。 DASHBOARD只是动态把FLOW RULES通知给客户端而已？

**Comment by sczyh30** [comment]
控制台目前不支持横向扩展，需要自行进行改造。Refer: https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel

**Comment by diaomaoblue** [comment]
插眼
