### ISSUE TITLE
Problem feedback

### ISSUE THREAD

**Issue by pengzhengfa** [alibaba/Sentinel#1568]
This framework seems to consume more bandwidth when compiling. The following progress bar does not show that I compile other frameworks very quickly. This is not a problem of the network, but of the framework itself
<img width="904" alt="1" src="https://user-images.githubusercontent.com/33858082/85522310-0e25bf00-b638-11ea-9af2-9c6b5f361b7c.png">

**Comment by sczyh30** [comment]
Could you please identify which step is slow?

**Comment by pengzhengfa** [comment]
@sczyh30 I'm not sure yet. I'll check first. If there is any result, I'll take a screenshot and comment here

**Comment by sczyh30** [comment]
Any feedback?
