### ISSUE TITLE
降级DEGRADE_GRADE_EXCEPTION_RATIO，设置的是每秒异常比例，能否支持任意统计窗口时长

### ISSUE THREAD

**Issue by qys-code** [alibaba/Sentinel#1569]
针对小流量的，降级规则配置，有每秒异常比例，能否增加每个时间窗口的异常比列配置

**Comment by sczyh30** [comment]
Could you please illustrate your demand?

**Comment by qys-code** [comment]
> Could you please illustrate your demand?
我们有一些小流量的支付渠道接口，想做降级熔断下线操作，但目前熔断规则配置里，有每秒的异常比例，但我们量小，每秒可能就只有一个请求，所以不太好配置，想改成每5分钟或者10分钟的异常比例，这样可以吗

**Comment by sczyh30** [comment]
This will be supported via #1490.
