### ISSUE TITLE
Sentinel与Hystrix对比wiki中信号量隔离部分描述不清晰

### ISSUE THREAD

**Issue by jakiewang** [alibaba/Sentinel#157]
[wiki](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E4%B8%8E-Hystrix-%E7%9A%84%E5%AF%B9%E6%AF%94)中有这样一段：
> Hystrix 的信号量隔离限制对某个资源调用的并发数。这样的隔离非常轻量级，仅限制对某个资源调用的并发数，而不是显式地去创建线程池，所以 overhead 比较小，但是效果不错。但缺点是无法对慢调用自动进行降级，只能等待客户端自己超时，因此仍然可能会出现级联阻塞的情况。

实际上，Hystrix在信号量隔离模式下，也是支持自动“熔断”的，熔断原理同线程池隔离，并不会出现级联阻塞的情况。最后一句要成立的话，是否要加上一些前提条件？

**Comment by sczyh30** [comment]
熔断只是针对将来的调用。此处指的是，信号量隔离模式下，对于正在进行的慢调用，只能等待它自己超时失败（如 client 自己的超时策略），无法强制“掐掉”它。并且 Hystrix 的熔断是基于异常比率的，因此只有大量超时失败后才能触发熔断。Sentinel 结合基于 RT 的熔断机制可以缓解这个问题。
