### ISSUE TITLE
Cannot read rules on nacos?

### ISSUE THREAD

**Issue by cielswift** [alibaba/Sentinel#1570]
Sentinel vesion 1.7.2
jdk version 1.8
nacos version 1.3

      datasource: 
        c1:
          nacos: 
            server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
            namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68 
            dataId: sentinel-dev
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

        c2:
          file: 
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow

![image](https://user-images.githubusercontent.com/42295829/85854603-43bcda80-b7e7-11ea-91e6-6452baa98681.png)

**Comment by cdfive** [comment]
Have you used `spring-cloud-starter-alibaba-sentinel` and which version. It provide yml configuration support.

**Comment by cielswift** [comment]
Change sentinel-dev to yaml format?

**Comment by cielswift** [comment]
c2 can be read, c1 cannot be read

**Comment by sczyh30** [comment]
Please check `~/logs/csp/sentinel-record.log.xxx`.
