### ISSUE TITLE
save rules to nacos/apoll/zookeeper misuse entity

### ISSUE THREAD

**Issue by fengsmith** [alibaba/Sentinel#1571]
![image](https://user-images.githubusercontent.com/6457270/85964427-3e7cad00-b9ec-11ea-8e6a-21b626dc8b63.png)
![image](https://user-images.githubusercontent.com/6457270/85964495-7126a580-b9ec-11ea-8bec-0b271e650de3.png)

When save to nacos json serialized with FlowRuleEntity, but when  deserialize to object which used entity is FlowRule .

Because these two entities have almost the same filed name, so it works. But when I followed this demo to change Authority rule , it did not work, because AuthorityRuleEntity and AuthorityRuleEntity have no common filed names, so it did not work.

So I hope serializing and deserializing both used FlowRule not FlowRuleEntity.

**Comment by sczyh30** [comment]
Related to #1257
