### ISSUE TITLE
Upgrade nacos-client version to 1.3.0 in sentinel-datasource-nacos

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1574]
## Issue Description

Type: *dependency update*

### Describe what happened (or what feature you want)

Upgrade nacos-client version to 1.3.0 in `sentinel-datasource-nacos`.

**Comment by RGaius** [comment]
Only need to upgrade the version in pom？

**Comment by sczyh30** [comment]
> Only need to upgrade the version in pom？

You may also need to do regression tests to verify the dependency update.

**Comment by RGaius** [comment]
> > Only need to upgrade the version in pom？
> 
> You may also need to do regression tests to verify the dependency update.

Ok, i will finish it

**Comment by sczyh30** [comment]
Resolved via #1576
