### ISSUE TITLE
中文文档备注描述错误

### ISSUE THREAD

**Issue by sunqiuxiang** [alibaba/Sentinel#1578]
https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7%E8%A7%84%E5%88%99-degraderule
![image](https://user-images.githubusercontent.com/26270865/86214401-b9d98c80-bbad-11ea-975c-8d5936bf5005.png)
限流规则的作用对象应改为降级规则的作用对象

**Comment by sczyh30** [comment]
We've fixed it. Thanks for reporting!
