### ISSUE TITLE
confused with branches

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#158]
## Issue Description

I just know here is for bug report or feature request only but where is the **MAILING LIST**?
I dug the **WIKI** several times but didn't find it.

So here is my problem:

1. **PR #156**  
When will it be merged to master? is there any plan?
2. **Branch 0.1.2**  
I am confused when having checked the commits history that the branch  '0.1.2' is so far from or nearly the same from master (full of cherry-picks?)

**Comment by sczyh30** [comment]
Hi, for discussion you can go to:

- [Gitter Room](https://gitter.im/alibaba/Sentinel)
- [DingTalk Group (more active)](https://github.com/alibaba/Sentinel/wiki/%E4%BB%8B%E7%BB%8D#%E8%B4%A1%E7%8C%AE)
- [Google Group](https://groups.google.com/forum/#!forum/sentinel-users)

For your question:

- The PR #156 will be merged to `master` soon. We'll publish 0.2.0 this week.
- 0.1.2 is a bug-fix version, including bug fixes picked from `master`.

**Comment by jasonjoo2010** [comment]
@sczyh30 

Thank you for response.  
I will mainly follow master then.
