### ISSUE TITLE
Sentinel 向 stdout 输出未格式化日志

### ISSUE THREAD

**Issue by Devifish** [alibaba/Sentinel#1582]
![image](https://user-images.githubusercontent.com/26357254/86423641-e824ac80-bd12-11ea-90e5-755eb5cb3bd4.png)

项目在引入 spring-boot-starter-actuator 依赖后 导致 Sentinel 向控制台输出未格式化日志（已排查该日志由Sentinel输出），  去除该依赖恢复正常，非统一格式日志非常扎眼，强迫症用户实在无法忍受。

使用版本： spring-cloud-starter-alibaba-sentinel:2.2.1.RELEASE

**Comment by cdfive** [comment]
输出非格式化日志具体是指？有截图或者日志信息么

**Comment by Devifish** [comment]
> 输出非格式化日志具体是指？有截图或者日志信息么

![image](https://user-images.githubusercontent.com/26357254/86426494-718bad00-bd1a-11ea-8645-588d2d17f02d.png)
输出部分如图
该日志由 `LogBase` 的 `loadProperties()`方法直接使用控制台输出，查看日志体验实在不太友好

**Comment by sczyh30** [comment]
This can be improved later. Contributions are welcomed.
