### ISSUE TITLE
客户端连接Sentinel Dashboard长连接不刷新问题

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#1583]
版本:1.6.3
问题:我有很多个应用已经连接到Sentinel,用的是域名+LVS -> 具体IP.
Sentinel换了机房,需要申请新的LVS去挂载新的IP,老的LVS下线并且域名挂载新LVS完毕后,到客户端发现客户端的日志一直有心跳报错,显示域名解析到的LVS还是老LVS,没有隔一断时间尝试连接和感知新LVS的功能.
如果想要快速解决,得客户端重启应用才行.

想问的是这种场景有没有快速解决方案?因为我也不清楚SimpleHttpClient这个类长连接什么时候才能自动刷新连接,或许如果不重启就不会刷新的情况.

所以求助各位大神看看有没有办法不让客户端重启就能刷新连接.
谢谢

**Comment by sczyh30** [comment]
SimpleHttpClient 非长连接设计。

**Comment by jasonjoo2010** [comment]
客户端是短连接，你碰到的这个情况，应该是jvm的域名解析或主机的域名解析缓存所致，可以参考以下两个参数：

```shell
-Dnetworkaddress.cache.ttl=60
-Dnetworkaddress.cache.negative.ttl=10
```

**Comment by qixiaobo** [comment]
> 客户端是短连接，你碰到的这个情况，应该是jvm的域名解析或主机的域名解析缓存所致，可以参考以下两个参数：
> 
> ```shell
> -Dnetworkaddress.cache.ttl=60
> -Dnetworkaddress.cache.negative.ttl=10
> ```

不对哦 这块是sentinel-dashboard的问题 代码中显式的使用了`InetSocketAddress`

`private List<InetSocketAddress> getDefaultConsoleIps() {
        List<InetSocketAddress> newAddrs = new ArrayList<InetSocketAddress>();
        try {
            String ipsStr = TransportConfig.getConsoleServer();
            if (StringUtil.isEmpty(ipsStr)) {
                RecordLog.warn("[SimpleHttpHeartbeatSender] Dashboard server address not configured");
                return newAddrs;
            }

            for (String ipPortStr : ipsStr.split(",")) {
                if (ipPortStr.trim().length() == 0) {
                    continue;
                }
                if (ipPortStr.startsWith("http://")) {
                    ipPortStr = ipPortStr.trim().substring(7);
                }
                String[] ipPort = ipPortStr.trim().split(":");
                int port = 80;
                if (ipPort.length > 1) {
                    port = Integer.parseInt(ipPort[1].trim());
                }
                newAddrs.add(new InetSocketAddress(ipPort[0].trim(), port));
            }
        } catch (Exception ex) {
            RecordLog.warn("[SimpleHeartbeatSender] Parse dashboard list failed, current address list: " + newAddrs, ex);
            ex.printStackTrace();
        }
        return newAddrs;
    }`
这段代码在初始化的时候其实解析了域名ip 并且之后不再解析 所以导致当域名更换了ip之后一直无法获取
其实影响可能很大（如果k8s用了healthCheck做rediness探针的话 将有可能导致线上应用全部摘除）

**Comment by jasonjoo2010** [comment]
> 这段代码在初始化的时候其实解析了域名ip 并且之后不再解析 所以导致当域名更换了ip之后一直无法获取
> 其实影响可能很大（如果k8s用了healthCheck做rediness探针的话 将有可能导致线上应用全部摘除）

噢噢噢，没仔细审题，我以为你指的是Application端，Dashboard端那么的确是有这个问题，因为一开始是基于IP:PORT方式来指定的，这里可以考虑下解决方案。

@sczyh30 

这里貌似有两个解决方法，要么简单地采用`InetSocketAddress.createUnresolved`，要么直接使用字符串地址，any idea?

**Comment by qixiaobo** [comment]
> > 这段代码在初始化的时候其实解析了域名ip 并且之后不再解析 所以导致当域名更换了ip之后一直无法获取
> > 其实影响可能很大（如果k8s用了healthCheck做rediness探针的话 将有可能导致线上应用全部摘除）
> 
> 噢噢噢，没仔细审题，我以为你指的是Application端，Dashboard端那么的确是有这个问题，因为一开始是基于IP:PORT方式来指定的，这里可以考虑下解决方案。
> 
> @sczyh30
> 
> 这里貌似有两个解决方法，要么简单地采用`InetSocketAddress.createUnresolved`，要么直接使用字符串地址，any idea?
就是application端哦 application做定时上报到dashboard的时候由于长期持有了InetSocketAddress导致的 
我觉得没必要长期持有 InetSocketAddress 这样将导致域名无法感知变更
使用String 可能更加合理

**Comment by qixiaobo** [comment]
@sczyh30 maybe reopen?

**Comment by jasonjoo2010** [comment]
> 我觉得没必要长期持有 InetSocketAddress 这样将导致域名无法感知变更
> 使用String 可能更加合理
> 不过现在改动最小的应当是不要直接new 使用 `createUnresolved`是不错的选择
> 
> @jasonjoo2010 make a pr?

A new PR later. Thanks for reporting and explaining patiently.

**Comment by sczyh30** [comment]
@qixiaobo Contributions are welcomed!

**Comment by qixiaobo** [comment]
> @qixiaobo Contributions are welcomed!

@jasonjoo2010 may make a new PR soon!

I think @cookiejoo 'd better change title to avoid misleading. No long connection!

**Comment by jasonjoo2010** [comment]
@qixiaobo @cookiejoo 

我仔细看了下issue和描述，发现还是我一开始理解的那样
这个问题从1.7.2起已经被解决掉了，具体的PR见 #926 ，所以推荐升级解决该问题

**Comment by cookiejoo** [comment]
> @qixiaobo @cookiejoo
> 
> 我仔细看了下issue和描述，发现还是我一开始理解的那样
> 这个问题从1.7.2起已经被解决掉了，具体的PR见 #926 ，所以推荐升级解决该问题

感谢你的分析,我已准备更新到1.7.2

**Comment by qixiaobo** [comment]
> @qixiaobo @cookiejoo
> 
> 我仔细看了下issue和描述，发现还是我一开始理解的那样
> 这个问题从1.7.2起已经被解决掉了，具体的PR见 #926 ，所以推荐升级解决该问题
You're right! But the analysis was right.I think the release note should mention this https://github.com/alibaba/Sentinel/releases

**Comment by jasonjoo2010** [comment]
> @qixiaobo @cookiejoo
> 
> 我仔细看了下issue和描述，发现还是我一开始理解的那样
> 这个问题从1.7.2起已经被解决掉了，具体的PR见 #926 ，所以推荐升级解决该问题
> You're right! But the analysis was right.I think the release note should mention this https://github.com/alibaba/Sentinel/releases

Yes. Maybe @sczyh30 and I didn't do that due to such kind of issue. I think it should be mentioned now in release notes of 1.7.2.

**Comment by jasonjoo2010** [comment]
Notes has been updated.

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/89746182-ed7fce80-daea-11ea-9275-fe0477ba2e98.png)
I saw about this, thanks for updating release note

**Comment by qixiaobo** [comment]
Related to  cache issue, we met another sentinel problem while k8s health check error.
It's terrible https://github.com/alibaba/spring-cloud-alibaba/pull/1586 https://github.com/alibaba/Sentinel/issues/1494
I think it's very dangerous

**Comment by jasonjoo2010** [comment]
> Related to cache issue, we met another sentinel problem while k8s health check error.
> It's terrible [alibaba/spring-cloud-alibaba#1586](https://github.com/alibaba/spring-cloud-alibaba/pull/1586) #1494
> I think it's very dangerous

It's mainly issuing to kind of implementation which SCA(spring-cloud-alibaba) does. So it's better to solve it in the  implementation.

Certainly the maintainers are  different between SCA and Sentinel but i will put my concern on it and provide necessary help. Please kindly let me know if anything issued back.

**Comment by qixiaobo** [comment]
> > Related to cache issue, we met another sentinel problem while k8s health check error.
> > It's terrible [alibaba/spring-cloud-alibaba#1586](https://github.com/alibaba/spring-cloud-alibaba/pull/1586) #1494
> > I think it's very dangerous
> 
> It's mainly issuing to kind of implementation which SCA(spring-cloud-alibaba) does. So it's better to solve it in the implementation.
> 
> Certainly the maintainers are different between SCA and Sentinel but i will put my concern on it and provide necessary help. Please kindly let me know if anything issued back.

Of course~ I also made a PR for this. I think 'down' status is very serious. So I will never put this status to 'sentinel dashboard not connected' this scene. It may break our k8s cluster network traffic.

**Comment by mbrezovsky** [comment]
+1

Any update?

**Comment by qixiaobo** [comment]
> +1
> 
> Any update?

You need update your sentinel version at least 1.7.2

**Comment by cookiejoo** [comment]
ok，thank you for you time

**Comment by qixiaobo** [comment]
> ok，thank you for you time

My pleasure
