### ISSUE TITLE
Sentinel dashboard data is stored in memory, which is not reliable

### ISSUE THREAD

**Issue by apple987** [alibaba/Sentinel#1585]
hi! the default sentinel dashboard ,based on version 1.7.2, I modified the storage in Nacos. I feel whether the official website can add the configuration based dynamic writing method to the later version to support Nacos, Apollo, zookeeper and redis for easy use

**Comment by kyiln** [comment]
同问，而且好像只可以做流控持久化。不知道api分组可以持久化不，我在官文没看到，或许是我看漏了。还是需要我们自己去做开发实现

**Comment by sczyh30** [comment]
> hi! the default sentinel dashboard ,based on version 1.7.2, I modified the storage in Nacos. I feel whether the official website can add the configuration based dynamic writing method to the later version to support Nacos, Apollo, zookeeper and redis for easy use

You may refer #1453
