### ISSUE TITLE
sentinel dashboard 不支持nacos命名空间吗

### ISSUE THREAD

**Issue by aabc1123** [alibaba/Sentinel#1586]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Maybe you could put Nacos namespace into the properties via the constructor:

https://github.com/alibaba/Sentinel/blob/5e1a44366303920589b171cf08c9278bb1671094/sentinel-extension/sentinel-datasource-nacos/src/main/java/com/alibaba/csp/sentinel/datasource/nacos/NacosDataSource.java#L83-L84
