### ISSUE TITLE
gateway cannot concat with sentinel-dashboard?where the code sentinel springCloud starter load the dashboard register action?

### ISSUE THREAD

**Issue by apple987** [alibaba/Sentinel#1594]
Run the console remotely and print the registration machine information. However, for the gateway project, the dashboard has never received the registration machine information printed by the console. Other projects can receive the registered machine information of gateway. When springboot and dashboard deploy the same machine, they can receive the registration information of gateway on the dashboard, but they can't be read remotely. What is the reason ?

dashboard控制台
![image](https://user-images.githubusercontent.com/21330215/87140680-7c26e300-c2d4-11ea-8a37-d35bc832650d.png)
源码改动
![image](https://user-images.githubusercontent.com/21330215/87140787-a24c8300-c2d4-11ea-954c-1b2a40ef9230.png)
![image](https://user-images.githubusercontent.com/21330215/87140815-aaa4be00-c2d4-11ea-8ba8-a5fd9adc2df2.png)

![image](https://user-images.githubusercontent.com/21330215/87140951-e2136a80-c2d4-11ea-8c19-903555856b5d.png)
![image](https://user-images.githubusercontent.com/21330215/87140987-ed669600-c2d4-11ea-8a1d-44a12380dcd8.png)
![image](https://user-images.githubusercontent.com/21330215/87141015-f8b9c180-c2d4-11ea-8929-c452aff07945.png)

**Comment by cdfive** [comment]
Which version of sentinel? You may check the log info in `sentinel-record.log` file.
Refer to [https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查)

**Comment by sczyh30** [comment]
Any feedback? @apple987
