### ISSUE TITLE
sentinel-dashboard + nacos Login authentication

### ISSUE THREAD

**Issue by qwerplf** [alibaba/Sentinel#1595]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

When sentinel-dashboard + nacos is persisted, because nacos uses version 1.3.0, this version has login authentication function. Because I don't know java, I don't know where to write the account and password in the source code? Should all configuration related to nacos be written in the NacosConfig file?
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
sentinel-dashboard 1.7.2
nacos 1.3.0

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/23162792/87141736-176c8800-c2d6-11ea-94f4-7f37e9a5cf5b.png)

**Comment by sczyh30** [comment]
For the raw Nacos API you may refer to the document of Nacos.
