### ISSUE TITLE
Sentinel控制台中新增规则，却没有同步到Nacos，建议datasource中增加这个功能

### ISSUE THREAD

**Issue by Chan513** [alibaba/Sentinel#1597]
如题，项目中引入Sentinel及sentinel-datasource-nacos，在Sentinel控制台新增规则，但是服务却没有同步配置至nacos中。建议在sentinel-datasource-nacos中加入此功能，或者在Sentinel控制台中增加一键持久化（能根据资源名持久化----只更改该资源的规则，也能根据应用名持久化----更改应用下所有规则）。

**Comment by sczyh30** [comment]
Refer #1511
