### ISSUE TITLE
Functional endpoint needs to be supported in WebFluxAdapter

### ISSUE THREAD

**Issue by lawulu** [alibaba/Sentinel#1600]
## Issue Description

使用Router configuration方式配置Endpoint时候，不起作用。应该是因为只实现了WebFilter

### Describe what happened (or what feature you want)
希望支持Router的方式

### Tell us your environment
sentinel-spring-webflux-adapter 1.6.3

**Comment by sczyh30** [comment]
Do you mean support for `HandlerFunction`? Contributions are welcomed!

**Comment by liqiangz** [comment]
I will finished this issue.

**Comment by sczyh30** [comment]
> I will solve this issue.

Look forward to your PR!

**Comment by liqiangz** [comment]
I find it works when using RouterFunction on a Spring application context.  I will add test case.
