### ISSUE TITLE
希望控制台机器列表优化

### ISSUE THREAD

**Issue by lovegames** [alibaba/Sentinel#1603]
## Issue Description
由于是用docker部署,每次都会有一堆失联的机器,强迫症
希望能够优化控制台机器列表管理批量删除功能
![image](https://user-images.githubusercontent.com/33571601/87508861-da700f00-c6a2-11ea-9916-38a9eb343ace.png)

### Describe what you expected to happen
有个批量删除功能,或者直接清除失联的机器

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
控制台支持配置过期自动删除的，可以参考 https://github.com/alibaba/Sentinel/wiki/控制台#控制台配置项

**Comment by lovegames** [comment]
谢谢,我看下

**Comment by cdfive** [comment]
Also refer to #1540 and #1432.
