### ISSUE TITLE
Spring Cloud gateway 整合Sentines 做限流时持久化到Redis不生效

### ISSUE THREAD

**Issue by wangmingweikong** [alibaba/Sentinel#1611]
我在使用Spring Cloud 整合Sentines做限流时，想把规则数据存到Redis中，Sentines官方文档是支持持久化到Redis的，但是我按照官方文档继承AbstractDataSource接口后，不知道该如何调用这个类。

在启动Spring Cloud项目时，应该如何传入Redis Config 参数和redis 的ruleKey,以及如何让我重写的这个类起作用呢？

**Comment by wangmingweikong** [comment]
不用重写AbstractDataSource类，只需要创建一个项目启动类，并使用默认的实现类即可：
`package cn.com.bobfintechgateway.sentinel;
 
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import com.alibaba.csp.sentinel.datasource.Converter;
import com.alibaba.csp.sentinel.datasource.ReadableDataSource;
import com.alibaba.csp.sentinel.datasource.redis.RedisDataSource;
import com.alibaba.csp.sentinel.datasource.redis.config.RedisConnectionConfig;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRule;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
 
/**
 * @project: 北银金科
 * @description: 客户端在启动时初始化Redis中规则
 * @version 1.0.0
 * @errorcode
 *            错误码: 错误描述
 * @author
 *         <li>2020-07-17 guopengfei@bobfintech.com.cn Create 1.0
 * @copyright ©2019-2020 北银金科，版权所有。
 */
@Component
public class RedisDataSourceConfig implements ApplicationRunner {
    private static final Logger log = LoggerFactory.getLogger(RedisDataSourceConfig.class);
 
    @Value("${spring.redis.host}")
    public String redisHost;
 
    @Value("${spring.redis.port}")
    public int redisPort;
 
    @Value("${spring.redis.password}")
    public String redisPass;
    
    @Value("${spring.redis.database}")
    public Integer database;
 
    //限流规则key前缀
    public final String RULE_FLOW = "sentinel_rule_flow_";
    public final String RULE_FLOW_CHANNEL = "sentinel_rule_flow_channel";
 
    //降级规则key前缀
    // public final String RULE_DEGRADE = "sentinel_rule_degrade_";
    // public final String RULE_DEGRADE_CHANNEL = "sentinel_rule_degrade_channel";
 
    //系统规则key前缀
    // public final String RULE_SYSTEM = "sentinel_rule_system_";
    // public final String RULE_SYSTEM_CHANNEL = "sentinel_rule_system_channel";
 
    /**
     * ApplicationRunner
     * 该接口的方法会在服务启动之后被立即执行
     * 主要用来做一些初始化的工作
     * 但是该方法的运行是在SpringApplication.run(…​) 执行完毕之前执行
     */
    @Override
    public void run(ApplicationArguments args) {
        log.info("执行sentinel规则初始化 start >>>>>>>>>>>>>");
        RedisConnectionConfig config = RedisConnectionConfig.builder().withHost(redisHost).withPort(redisPort)
            .withPassword(redisPass).withDatabase(database).build();
        Converter<String, List<FlowRule>> parser = source -> JSON.parseObject(source,
            new TypeReference<List<FlowRule>>()
        {});
        
        ReadableDataSource<String, List<FlowRule>> redisDataSource = new RedisDataSource<>(config, RULE_FLOW,
            RULE_FLOW_CHANNEL, parser);
        FlowRuleManager.register2Property(redisDataSource.getProperty());
        log.info("执行sentinel规则初始化 end >>>>>>>>>>>>>");
 
        // Converter<String, List<DegradeRule>> parserDegrade = source -> JSON.parseObject(source,
        // new TypeReference<List<DegradeRule>>() {
        // });
        // ReadableDataSource<String, List<DegradeRule>> redisDataSourceDegrade = new
        // RedisDataSource<>(config, RULE_DEGRADE + SentinelConfig.getAppName(),
        // RULE_DEGRADE_CHANNEL, parserDegrade);
        // DegradeRuleManager.register2Property(redisDataSourceDegrade.getProperty());
 
        // Converter<String, List<SystemRule>> parserSystem = source -> JSON.parseObject(source, new
        // TypeReference<List<SystemRule>>() {
        // });
        // ReadableDataSource<String, List<SystemRule>> redisDataSourceSystem = new
        // RedisDataSource<>(config, RULE_SYSTEM + SentinelConfig.getAppName(), RULE_SYSTEM_CHANNEL,
        // parserSystem);
        // SystemRuleManager.register2Property(redisDataSourceSystem.getProperty());
        log.info(">>>>>>>>>执行sentinel规则初始化 end。。。");
    }
    
}`

**Comment by 593769290** [comment]
这个问题可以解决吗？

**Comment by keybersan** [comment]
我改为拉取模式后也没有效过；我的做法是在sentinel-dashboard 加两个接口，然后client 启动时候去调这两个接口，让服务端主动推送过来（当然我还加了延迟，让client与server通信后才发起请求）。
