### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 2.2.1 包引入后 json格式中的int被转换成了string

### ISSUE THREAD

**Issue by heppytt** [alibaba/Sentinel#1612]
版本 spring-cloud-starter-alibaba-sentinel 2.2.1
之前我的项目里面用的是spring-cloud-starter-netflix-hystrix 想替换成spring-cloud-starter-alibaba-sentinel 替换之后
我用RestTemplate去请求外部项目的服务，项目里面返回的对象code变成了string 。我们之前定义的code是int类型。然后我还原之后就变好了。请问是什么原因导致的啊？

**Comment by sczyh30** [comment]
Could you please provide a demo project that can reproduce the problem?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by sczyh30** [comment]
You may try the latest version of Spring Cloud Alibaba Sentinel.
