### ISSUE TITLE
Sentinel和微服务是不是不能部署在不同网段？

### ISSUE THREAD

**Issue by jast90** [alibaba/Sentinel#1613]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please describe your environment?

**Comment by yugj** [comment]
权限能通就好，如果不能，名字会改为 同网段分布式系统的流量防卫兵
