### ISSUE TITLE
sentinel FlowControllerV1 和  FlowControllerV2 有什么区别？

### ISSUE THREAD

**Issue by wangmingweikong** [alibaba/Sentinel#1616]
我想修改Sentinel dashboard 项目，以能够使用Redis作为持久化的数据源，我是在FlowControllerV2中注入了Redis的推送和拉取的依赖，但是在dashboard 上添加规则，并没有缓存到Redis中，调试时才发现，添加规则并没有进入FlowControllerV2.apiQueryMachineRules方法，而是进入了FlowControllerV1.apiQueryMachineRules方法

**Comment by cdfive** [comment]
FlowControllerV1是应用节点维度的流控规则保存,基于`InMemoryRuleRepositoryAdapter`实现的内存存储。
FlowControllerV2是以应用维度的处理，基于`DynamicRuleProvider`,`DynamicRulePublisher`接口实现规则的取和存。
使用FlowControllerV2需要修改前端页面：
`修改前端路由配置（sidebar.html 流控规则路由从 dashboard.flowV1 改成 dashboard.flow`

dashboard.flowV1和dashboard.flow是在/webapp/resources/app/scripts/app.js里指定的，分别对应FlowControllerV1和FlowControllerV2.

参考文档：
[https://github.com/alibaba/Sentinel/wiki/Sentinel-控制台（集群流控管理）#规则配置](https://github.com/alibaba/Sentinel/wiki/Sentinel-控制台（集群流控管理）#规则配置)
[https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#push模式](https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel#push模式)
