### ISSUE TITLE
maven仓库提供的sentinel-1.6.3版本的jar与源码不一致

### ISSUE THREAD

**Issue by kldwz** [alibaba/Sentinel#1619]
公司选择sentinel-1.6.3代码进行开发，初始jar用的是maven官网提供的1.6.3版本的jar。以下是阿里提供的sentinel-dubbo-adapter-1.6.3 jar 中 SentinelDubboProviderFilter.invoke方法部分代码
`     
interfaceEntry = SphU.entry(interfaceName, 2, EntryType.IN);
methodEntry = SphU.entry(resourceName, 2, EntryType.IN, invocation
          .getArguments());
`

而源码中该代码为：
`
interfaceEntry = SphU.entry(interfaceName, EntryType.IN);
methodEntry = SphU.entry(resourceName, EntryType.IN, 1, invocation.getArguments());
`
差异还是比较明显的，导致我们在进行二次开发时，打包报错。
排查了一下，**发现maven提供的1.6.3的jar应该是使用1.7.0的源码进行编译的**。

**Comment by sczyh30** [comment]
Maybe some newer methods in `SphU` were carried in 1.6.3. It's recommended to use 1.7.x (the latest is 1.7.2).
