### ISSUE TITLE
Sentinel 集群流控 客户端指定token server

### ISSUE THREAD

**Issue by yugj** [alibaba/Sentinel#1622]
# Sentinel 集群流控 客户端指定token server

## Issue Description

Type: *question*

### Describe what happened (or what feature you want)

1，启动Token Server（独立模式），集成nacos  

2，启动Sentinel dashboard，集成nacos   

3，启动2个client 接入Sentinel dashboard  

【集群流控控制台】【新增Token Server配置】，【外部指定机器】选择当前客户端节点  

**问题描述：**

当我关闭所有client，【Sentinel dashboard】【集群流控】里面的配置就消失了，这个**集群流控配置貌似只在新增TokenServer保存的时候推送到各个节点client，并没有做持久化**，导致需要在重启client后重新配置

### Describe what you expected to happen

项目通过k8s管理，应用节点不是固定部署，可能存在节点漂移情况，期望能够在应用启动的时候，根据项目里面的配置指定token server自动指定固定的token server

目前我通过如下方式**指定**规定的token server，然而控制台上 client的【集群流控】并没有增加配置，Token Server 【连接详情】也没看到有连接过来

```java
ClusterClientAssignConfig clientAssignConfig = new ClusterClientAssignConfig("localhost",18730);
        SentinelProperty<ClusterClientAssignConfig> property = new DynamicSentinelProperty<ClusterClientAssignConfig>(clientAssignConfig);
        ClusterClientConfigManager.registerServerAssignProperty(property);
```

**启动时候连接token server请问我这边哪里出错了吗，谁能给点建议**

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Sentinel 1.6.3

edit:
Sentinel 1.6.3  

已经按[控制台集群流控管理](https://github.com/alibaba/Sentinel/wiki/Sentinel-控制台（集群流控管理）)接nacos数据源

**测试代码**：

Token Server 代码在 https://github.com/yugj/ratelimit-demo/tree/master/sentinel-cluster-server

Client端代码在：https://github.com/yugj/ratelimit-demo/tree/master/sentinel-mvc-server

### Anything else we need to know?

**Comment by sczyh30** [comment]
You may refer to the demo: https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-cluster/sentinel-demo-cluster-embedded

**Comment by yugj** [comment]
> You may refer to the demo: https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-cluster/sentinel-demo-cluster-embedded

这个demo并没有提供启动指定token server方式，看demo貌似是预先配置源方式维护token server，节点漂移场景，更希望能够直接指定token server节点

**Comment by yugj** [comment]
求问解决方案

**Comment by yugj** [comment]
求解决方案 +1

**Comment by sczyh30** [comment]
> > You may refer to the demo: https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-cluster/sentinel-demo-cluster-embedded
> 
> 这个demo并没有提供启动指定token server方式，看demo貌似是预先配置源方式维护token server，节点漂移场景，更希望能够直接指定token server节点

You may leverage `ClusterClientConfigManager.applyNewAssignConfig(xxx)` (when the state is token client).

**Comment by yugj** [comment]
没成功，放弃了，继续基于之前redisson搞下了

**Comment by xixily** [comment]
我最近在使用集群限流的时候也遇到类似的问题：
1、token server 正常注册规则（ClusterFlowRuleManager.setPropertySupplier(namespace -> redisDataSource.getProperty());），也启动端口成功；
2、token client 也正常注册：`initDynamicRuleProperty` `initClientConfigProperty` `initClientServerAssignProperty`;
3、测试client获取token的时候不能正确获得token（api模式TokenService和嵌入模式SphU.entry(flowId）都不行）；
4、调试发现客户端并没有正常初始化好（com.alibaba.csp.sentinel.cluster.client.NettyTransportClient#sendRequest 丢ClusterErrorMessages.CLIENT_NOT_READY错误）；
5、参照[sentinel-cluster-embedded](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-cluster/sentinel-demo-cluster-embedded)没有得到很好的结论，文档上面细节可能还需要完善下，继续调试中···

**Comment by henuhaigang** [comment]
有没有比较好的机遇redisDataSource的tokenserver alone模式的示例或者文档，资料太少了

**Comment by SeekYao** [comment]
> 没成功，放弃了，继续基于之前redisson搞下了

sentinel这官方的东西，无论是文档，还是demo都非常拉胯，跟shardingsphere竞争国内最烂开源框架，满地是坑，全得自己解决。

既然要依仗springcloud alibaba，做一流产品，为什么要做成半桶水？不如别做。

**Comment by 18986251003** [comment]
> 
@sczyh30 
麻烦大神们指导下，alone模式下指定了token server后dashbord上 client的【集群流控】并没有增加配置，Token Server 【连接详情】也没看到有连接过来。我的方式如下：
 //硬编码方式连token server
        ClusterClientAssignConfig clientAssignConfig = new ClusterClientAssignConfig(tokenServerHost,tokenServerPort);
        ClusterClientConfigManager.applyNewAssignConfig(clientAssignConfig);
        SentinelProperty<ClusterClientAssignConfig> property = new DynamicSentinelProperty<ClusterClientAssignConfig>(clientAssignConfig);
        ClusterClientConfigManager.registerServerAssignProperty(property);
