### ISSUE TITLE
控制台中默认显示5分钟的数据，怎样调整为显示10分钟？

### ISSUE THREAD

**Issue by 593769290** [alibaba/Sentinel#1624]
控制台中默认显示5分钟的数据，怎样调整为显示10分钟？

**Comment by 593769290** [comment]
package com.alibaba.csp.sentinel.dashboard.repository.metric;

public class InMemoryMetricsRepository implements MetricsRepository<MetricEntity> {

    private static final long MAX_METRIC_LIVE_TIME_MS = 1000 * 60 * 5;

**Comment by sczyh30** [comment]
You may adjust `MAX_METRIC_LIVE_TIME_MS ` to achieve this. It's recommended to store the metric data by yourself in production: https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel
