### ISSUE TITLE
[feature request]集群流控有没有实时监测

### ISSUE THREAD

**Issue by yunfeiyanggzq** [alibaba/Sentinel#1626]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

集群流控的各个集群资源qps实时监测没有找到，是不是没有开发这个功能，只看到了一个总览
![图片](https://user-images.githubusercontent.com/43897640/88277329-21997800-cd13-11ea-87bf-ad758616950f.png)
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
实时监控页面针对所有资源埋点，无需针对集群流控单独开发。
