### ISSUE TITLE
在对RestFul请求中，对于{value}类型的请求如何限流

### ISSUE THREAD

**Issue by guo218215** [alibaba/Sentinel#1627]
对于RestFul风格的请求中，URL会携带参数，此时Sentinel在创建DefaultNode时根据url来创建。对于
“POST:path/context/{value}” 的情况 此时会根据数据量的不同而创建多个node. 这种情况如何进行限流
![image](https://user-images.githubusercontent.com/16859655/88357523-25261100-cd9e-11ea-8308-0cb75e49cfa2.png)

**Comment by sczyh30** [comment]
Actually you may leverage https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter

**Comment by cdfive** [comment]
Also relate to #1074 which is solved by `sentinel-spring-webmvc-adapter`, and see #286 for more discussions.

**Comment by sczyh30** [comment]
@cdfive Maybe we could improve [the adapter document](https://github.com/alibaba/Sentinel/wiki/主流框架的适配) later and recommend `sentinel-spring-webmvc-adapter` first.
