### ISSUE TITLE
[feature request]使用dashboard不能将集群规则同步到ClusterFlowRuleManager中

### ISSUE THREAD

**Issue by yunfeiyanggzq** [alibaba/Sentinel#1628]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

使用dashboard不能将集群规则同步到ClusterFlowRuleManager中，需要将这个规则同步一下
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/wiki/Sentinel-控制台（集群流控管理）
