### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 2.2.1.RELEASE introduced jackson-dataformat-xml

### ISSUE THREAD

**Issue by Paul101432** [alibaba/Sentinel#1630]
com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:
2.2.1.RELEASE跟 
2.2.0.RELEASE
变化好大 
居然加了 jackson-dataformat-xml???  搞得项目启动全变成xml返回值
我们fastjson不香嘛

**Comment by cdfive** [comment]
This has been improved in 2.2.2.RELEASE version of spring-cloud-starter-alibaba-sentinel.
See [https://github.com/alibaba/spring-cloud-alibaba/pull/1546](https://github.com/alibaba/spring-cloud-alibaba/pull/1546)
Also refer to #1537
