### ISSUE TITLE
seata1.3.0 无法连接 nacos1.3.1

### ISSUE THREAD

**Issue by longxiaonan** [alibaba/Sentinel#1633]
seata sever使用nacos作为注册和配置中心 

启动nacos1.3.1或者不启动nacos都报错：
com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:486)

应该是连接不上获取不到driverClass导致的

当我启动nacos1.2.0的时候，再启动seata1.3.0则正常

**Comment by sczyh30** [comment]
Hi, please ask in Seata repo :)
