### ISSUE TITLE
从 Hystrix 迁移到 Sentinel withExecutionTimeoutInMilliseconds参数迁移有好的解决方案？

### ISSUE THREAD

**Issue by mm23504570** [alibaba/Sentinel#1636]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
在使用spring cloud openfeign的时候，我们常常会使用单个的FeignClient定义很多的mapping，但是spring cloud feign本身只支持feignClient级别的超时，不支持mapping级别的超时. 所以我们通常会结合Hystrix来定义单个mapping的超时.  但是切换到Sentinel后，我们无法对单个feignClient的mapping做超时处理了。针对这个问题，迁移时有什么好的方法吗？

``` java
public class FooServiceCommand extends HystrixCommand<String> {

    protected FooServiceCommand(HystrixCommandGroupKey group) {
        super(Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("OtherGroup"))
            // command key
            .andCommandKey(HystrixCommandKey.Factory.asKey("fooService"))
            .andCommandPropertiesDefaults(HystrixCommandProperties.Setter()
                .withExecutionTimeoutInMilliseconds(500) // 这句无法迁移
                .withCircuitBreakerRequestVolumeThreshold(5)
                .withCircuitBreakerErrorThresholdPercentage(50)
                .withCircuitBreakerSleepWindowInMilliseconds(10000)
            ));
    }

    @Override
    protected String run() throws Exception {
        return "some_result";
    }
}
```

这个问题不在feign里面也会出现，因为都有这种超时中断的场景.

**Comment by jasonjoo2010** [comment]
这个的本质因素是因为Hystrix可以做物理线程池的方式进行隔离，而Sentinel则基于信号量做隔离，Sentinel更轻量、更解耦，超时设置我认为应该回归到框架/类库本身去做设置。

至于client对象本身，参考httpclient/asynchttpclient等实现，client本身是轻量级的对象，所以如果纯基于client来做超时，一般是按client做设置，不同的配置组合定义不同的client（未必一定重用），并且从文档来看，通过hystrix的线程池模型来做超时等效，实际上跟设置连接本身的超时也是完全不一样的性质。

**Comment by mm23504570** [comment]
OK，那只能让client支持对应的超时设置了，不过这个给平滑迁移带来了很多困难，需要从框架层编码支持的  @jasonjoo2010

**Comment by jasonjoo2010** [comment]
> OK，那只能让client支持对应的超时设置了，不过这个给平滑迁移带来了很多困难，需要从框架层编码支持的 @jasonjoo2010

这个作为一个独立的限流组件来说，配置超时这个实在是有些超出超时范围（因为需要介入到具体的“请求”），更何况其实你给出的示例在hystrix中配置的这个所谓timeout也不是针对client的timeout，这个其实是不推荐使用的，会造成系统资源的浪费和追求一致性逻辑的问题，建议还是分组client直接在传输层解决掉
