### ISSUE TITLE
[feature request]服务熔断后手动恢复

### ISSUE THREAD

**Issue by aBreaking** [alibaba/Sentinel#164]
## Issue Description
服务熔断后，被阻塞，那么需要等待timeWindow时间后服务才会自动恢复。在我本地项目中，需要一个新的功能，能够实现服务手动服务。
##Describe how you did it
大致思路为，degradeRule添加一个新的方法，用于重置cut（即将cut置为false），还得需要将ResetTask任务手动给停掉，下次还能正常启动。

##Special notes for reviews
可参考我与本地esb项目整合后的框架：[Sentinel-esb](https://github.com/aBreaking/sentinel-esb)

**Comment by sczyh30** [comment]
Hi, this might not be a good idea as we should provide automatic circuit breaking and recover strategy rather than manually management.
