### ISSUE TITLE
sentinel 与 nacos交互问题

### ISSUE THREAD

**Issue by Xunzhuo** [alibaba/Sentinel#1642]
Sentinel控制台中新增规则，却没有同步到Nacos，项目中引入Sentinel及sentinel-datasource-nacos，在Sentinel控制台新增规则，但是服务却没有同步配置至nacos中。sentinel-datasource-nacos中是否应该加入此功能，或者在Sentinel控制台中增加一键持久化？

**Comment by sstong123** [comment]
同问，在Sentinel控制台中新删改限流规则，都没有同步到Nacos。配置方法如下：
`datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow`
另外：Sentinel到Nacos的持久化配置，是不是应该在Sentinel配置文件里配而不应该在微服务的配置文件里配比较好？
