### ISSUE TITLE
alibaba sentinel包将返回的json为List集合的转成了集合中的一个对象，导致数据丢失

### ISSUE THREAD

**Issue by zhouxiaoge** [alibaba/Sentinel#1644]
当导入com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2.2.1.RELEASE时，导致springboot的controller返回结果不正确
如：1、当返回结果未List<User>集合时，加入sentinel后之后返回一个User对象而不是List<User>集合
2、sntinel还会导致swagger2无法使用

**Comment by sczyh30** [comment]
Could you please illustrate your problem according to the issue template?

**Comment by sczyh30** [comment]
Could you please also submit an issue here: https://github.com/alibaba/spring-cloud-alibaba/issues
cc @alibaba/spring_cloud_alibaba_team @yuhuangbin

**Comment by sczyh30** [comment]
Closing this due to no feedback. You may upgrade spring-cloud-alibaba to the latest version after 2.2.2.RELEASE has been released.
