### ISSUE TITLE
请教：如何根据用户等级来限流？

### ISSUE THREAD

**Issue by diypyh** [alibaba/Sentinel#1646]
比如有以下需求：

VIP1：
20次/秒，50次/分钟，100次/天
VIP2：
50次/秒，100次/分钟，300次/天
VIP3：
100次/秒，300次/分钟，1000次/天
..........

可以动态根据用户的等级来限流吗？

**Comment by jasonjoo2010** [comment]
Sentinel关注于系统负载的保护和异常处理，而非基于业务意义上的配额实现，这里建议采用诸如基于redis/redis-cluster的配额管理

**Comment by diypyh** [comment]
> Sentinel关注于系统负载的保护和异常处理，而非基于业务意义上的配额实现，这里建议采用诸如基于redis/redis-cluster的配额管理

明白了，感谢回答
