### ISSUE TITLE
字符串判断有误

### ISSUE THREAD

**Issue by ChixianGen** [alibaba/Sentinel#1647]
`com.alibaba.cloud.sentinel.datasource.config.RedisDataSourceProperties`类中检查配置方法`preCheck`判断`masterId`有误；
源码如下：
`		if (!StringUtils.isEmpty(masterId) && StringUtils.isEmpty(masterId)) {
			throw new IllegalArgumentException(
					"RedisDataSource  sentinel model，masterId can not be empty");
		}`

**Comment by sczyh30** [comment]
https://github.com/alibaba/spring-cloud-alibaba/blob/899b7b4fe07603ec8ffa8a5207739c2585e6afa7/spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/RedisDataSourceProperties.java#L96-L99

Thanks for reporting. It's a bug in `spring-cloud-alibaba-sentinel-datasource`. Would you like to submit a PR to fix it?

**Comment by ChixianGen** [comment]
This bug is too obvious. It should be caused by careless developers. You can fix it officially

**Comment by sczyh30** [comment]
You may open an issue in the repo of spring-cloud-alibaba.

**Comment by ChixianGen** [comment]
OK
