### ISSUE TITLE
关于rocketmq demo问题

### ISSUE THREAD

**Issue by smipo** [alibaba/Sentinel#1651]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在运行SyncProducer和PullConsumerDemo程序时，抛出异常，但是运行并未结束。
以下分别两个类运行的截图
![image](https://user-images.githubusercontent.com/53416128/89841408-66dbf780-dba5-11ea-8a30-e9449cea7ed3.png)

![image](https://user-images.githubusercontent.com/53416128/89841451-807d3f00-dba5-11ea-86fb-6797b956c397.png)

### Describe what you expected to happen
希望deno运行异常时，正常结束程序

### Tell us your environment
master分支

**Comment by sczyh30** [comment]
You may submit a PR to improve this.

**Comment by PeineLiang** [comment]
> You may submit a PR to improve this.

I want to solve it, please assign to me.

**Comment by sczyh30** [comment]
> > You may submit a PR to improve this.
> 
> I want to solve it, please assign to me.

Any progress?

**Comment by PeineLiang** [comment]
> > > You may submit a PR to improve this.
> > 
> > 
> > I want to solve it, please assign to me.
> 
> Any progress?

I saw the issue had not been assigned to me, so I didn't do anything, and now i submit a PR, please review it.
