### ISSUE TITLE
关于如何贡献社区文档

### ISSUE THREAD

**Issue by yunfeiyanggzq** [alibaba/Sentinel#1656]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
现在的社区文档主要使用wiki，一般的贡献者贡献文档实在不方便

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
+1 for this.
Related to #147

**Comment by yunfeiyanggzq** [comment]
> 
> 
> +1 for this.
> Related to #147

Thanks! I understand
