### ISSUE TITLE
GatewaySlotChainBuilder无法被调用

### ISSUE THREAD

**Issue by sqgzy** [alibaba/Sentinel#1668]
现象：
如果com.alibaba.csp:sentinel-parameter-flow-control在com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway之前被加载，则SpiLoader.loadFirstInstanceOrDefault会返回符合要求的第一个值，也就是HotParamSlotChainBuilder，那么GatewaySlotChainBuilder无法被调用，网关流控不能正常执行。

版本：
com.alibaba.csp:sentinel-core:1.7.1
com.alibaba.csp:sentinel-parameter-flow-control:1.7.1
com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway:2.2.1.RELEASE

**Comment by sczyh30** [comment]
See #1306

**Comment by sczyh30** [comment]
You may upgrade all your Sentinel dependencies to 1.7.2.
