### ISSUE TITLE
Sentinel控制台,热点限流界面无高级选项

### ISSUE THREAD

**Issue by ymvkujn** [alibaba/Sentinel#1669]
使用最新的 sentinel-dashboard 1.8.0-SNAPSHOT
## Issue Description
从"簇点链路"界面点击"热点"限流, 热点限流界面无"高级选项"
### Tell us your environment
Mac Os 本地环境
### Anything else we need to know?

![1](https://user-images.githubusercontent.com/29377121/90144313-42546b00-ddb1-11ea-8a05-87095661a07e.jpg)

**Comment by sczyh30** [comment]
先创建规则，编辑的时候就有了。
