### ISSUE TITLE
Data source of cluster flow rules | 如何配置集群限流规则动态数据源及控制台推送?

### ISSUE THREAD

**Issue by fllife** [alibaba/Sentinel#1670]
## Issue Description

Type: *bug report* or *feature request*
*feature request*
### Describe what happened (or what feature you want)
I config flow rule in cluster mode， and i have 2 applications， one is token server， orther is token client。
but after i config in cluster，i find flow rule return `NO_RULE_EXISTS`，rules is empty in class `DefaultTokenService`
```java
    @Override
    public TokenResult requestToken(Long ruleId, int acquireCount, boolean prioritized) {
        if (notValidRequest(ruleId, acquireCount)) {
            return badRequest();
        }
        // The rule should be valid.
        FlowRule rule = ClusterFlowRuleManager.getFlowRuleById(ruleId);
        if (rule == null) {
            return new TokenResult(TokenResultStatus.NO_RULE_EXISTS);
        }

        return ClusterFlowChecker.acquireClusterToken(rule, acquireCount, prioritized);
    }
```

### Describe what you expected to happen
i do not know what error i do

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by yunfeiyanggzq** [comment]
你需要吧本地的flowManager和集群的flowManager都注册在同一个nacos规则上，都需要注册

**Comment by fllife** [comment]
> Any feedback? @fllife
我想问的是集群限流，如何配置规则？ 现在配置中心用的zk，但是即使dashboard勾选集群模式后（并指定了token server），通过调试配置规则仍然保存在FlowRuleManager，而不是ClusterFlowRuleManager。导致集群规则失效

**Comment by sczyh30** [comment]
控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。

**Comment by fllife** [comment]
> 控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。

修改了sidebar.html页面的版本，想问下对dashbord什么时候会调用client端的ModifyClusterFlowRulesCommandHandler（cluster/server/modifyFlowRules）接口， 在dashbord中没找到这个操作对应controller。 难道是我用的版本不匹配，我用的版本:   sentinel-dashbord:1.7.2 和 com.alibaba.cloud:spring-cloud-alibaba-dependencies:1.5.1.RELEASE

**Comment by sczyh30** [comment]
> > 控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。
> 
> 修改了sidebar.html页面的版本，想问下对dashbord什么时候会调用client端的ModifyClusterFlowRulesCommandHandler（cluster/server/modifyFlowRules）接口， 在dashbord中没找到这个操作对应controller。 难道是我用的版本不匹配，我用的版本: sentinel-dashbord:1.7.2 和 com.alibaba.cloud:spring-cloud-alibaba-dependencies:1.5.1.RELEASE

控制台不会调用 `cluster/server/modifyFlowRules`，修改集群规则 都走数据源。

**Comment by wufan1993** [comment]
> > 控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。
> 
> 修改了sidebar.html页面的版本，想问下对dashbord什么时候会调用client端的ModifyClusterFlowRulesCommandHandler（cluster/server/modifyFlowRules）接口， 在dashbord中没找到这个操作对应controller。 难道是我用的版本不匹配，我用的版本: sentinel-dashbord:1.7.2 和 com.alibaba.cloud:spring-cloud-alibaba-dependencies:1.5.1.RELEASE

我想改造一下api让它支持集群模式，请问有什么方案么

**Comment by fllife** [comment]
> > > 控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。
> > 
> > 
> > 修改了sidebar.html页面的版本，想问下对dashbord什么时候会调用client端的ModifyClusterFlowRulesCommandHandler（cluster/server/modifyFlowRules）接口， 在dashbord中没找到这个操作对应controller。 难道是我用的版本不匹配，我用的版本: sentinel-dashbord:1.7.2 和 com.alibaba.cloud:spring-cloud-alibaba-dependencies:1.5.1.RELEASE
> 
> 我想改造一下api让它支持集群模式，请问有什么方案么

dashbord 增加 controller，将配置的集群规则转发给ModifyClusterFlowRulesCommandHandler

**Comment by wufan1993** [comment]
> > > > 控制台配置规则 必须经改造后推配置中心（`/v2/flow` 页面）。HTTP 方式直接推送 不支持集群模式。
> > > 
> > > 
> > > 修改了sidebar.html页面的版本，想问下对dashbord什么时候会调用client端的ModifyClusterFlowRulesCommandHandler（cluster/server/modifyFlowRules）接口， 在dashbord中没找到这个操作对应controller。 难道是我用的版本不匹配，我用的版本: sentinel-dashbord:1.7.2 和 com.alibaba.cloud:spring-cloud-alibaba-dependencies:1.5.1.RELEASE
> > 
> > 
> > 我想改造一下api让它支持集群模式，请问有什么方案么
> 
> dashbord 增加 controller，将配置的集群规则转发给ModifyClusterFlowRulesCommandHandler

感谢指导，我已经完成了集群规则的转发功能，并支持了客户端重启的规则初始化功能，目前看来没有什么问题
