### ISSUE TITLE
控制台页面请求后台服务地址能否增加类似server.servlet.context-path这样的统一前缀

### ISSUE THREAD

**Issue by LvLaoTou** [alibaba/Sentinel#1671]
我现在的情况是sentinel-dashboard我部署在内网，因为某些原因我不能使用内网地址访问管理页面，所以我需要将页面通过nginx暴露在公网，然后通过公网操作管理页面。我现在遇到的问题是因为管理页面请求后台服务地址没有统一前缀，我不知道怎么为nginx配置路由规则，我的nginx不止管理这一个服务，所以我想将sentinel-dashboard暴露在公网使用我应该怎么做

**Comment by John-Chan** [comment]
nginx配一个虚拟主机,全部转发到内网的nacos，例子

`/etc/nginx/conf.d/nacos.conf`

```nginx
server {
    listen 80;
    server_name nacos.my-domain.com;

    location / {
       proxy_pass http://127.0.0.1:8848;
       proxy_connect_timeout 15s;
       proxy_send_timeout 15s;
       proxy_read_timeout 15s;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by LvLaoTou** [comment]
> nginx配一个虚拟主机，全部转发到内网的前哨仪表板，示例
> 
> `/etc/nginx/conf.d/sentinel-dashboard.conf`
> 
> ```nginx
> 服务器 {
>      听 80 ;
>     server_name sentinel-dashboard.my-domain.com;
> 
>     位置 / {
>         proxy_pass http://127.0.0.1:8718;
>        proxy_connect_timeout  15秒 ;
>        proxy_send_timeout  15s ;
>        proxy_read_timeout  15秒 ;
>        proxy_set_header X-Real-IP $ remote_addr ;
>        proxy_set_header X-Forwarded-For $ proxy_add_x_forwarded_for ;
>     }
> }
> ```

我的nginx不止管理这一个服务，所以我不能配置 / 来转发全部请求到sentinel-dashboard后台，sentinel-dashboard页面到后台的请求有没有什么规则能让我配置nginx只转发sentinel-dashboard页面的请求到后台

**Comment by LiujunjieALiling** [comment]
@LvLaoTou  可以试试将sentinel-dashboard模块的application.properties文件中增加一个servlet-context-path参数（ 值随便起个名字区分 ）

**Comment by LvLaoTou** [comment]
> @LvLaoTou 可以试试将sentinel-dashboard模块的application.properties文件中增加一个servlet-context-path参数（ 值随便起个名字区分 ）

试过了 不行的，我看了页面发出的请求路径中是没有的，所以我认为只是后台服务添加servlet-context-path是不行的

**Comment by LiujunjieALiling** [comment]
@LvLaoTou 前端要跟着一起改造呀

**Comment by LvLaoTou** [comment]
> @LvLaoTou 前端要跟着一起改造呀，理论上是行的，就是一个BS系统

**Comment by LvLaoTou** [comment]
> > @LvLaoTou 前端要跟着一起改造呀，理论上是行的，就是一个BS系统

前端没找到统一增加路径的地方，如果每个请求去改的话太麻烦了，现在我已经改方案了，通过调整网络还是基于内网访问

**Comment by LvLaoTou** [comment]
> > @LvLaoTou 前端要跟着一起改造呀，理论上是行的，就是一个BS系统

感谢您的指点，这个问题我就先关闭了
