### ISSUE TITLE
sentinel监控数据页面没10s刷新一次，我怎么关掉

### ISSUE THREAD

**Issue by 1204709592** [alibaba/Sentinel#1676]
sentinel监控数据页面没10s刷新一次，这个定时刷新机制，请问在源码哪里，我找了几个地方改了值都不行，想关掉或者调大时间

**Comment by JiangZian** [comment]
> sentinel监控数据页面没10s刷新一次，这个定时刷新机制，请问在源码哪里，我找了几个地方改了值都不行，想关掉或者调大时间

Are you talking about background refreshes for sentinel-dashboard?？

**Comment by sczyh30** [comment]
Any feedback?
