### ISSUE TITLE
sentinel监控数据持久化到influxDB，然后做了压测，监控页面过会就提示内存溢出

### ISSUE THREAD

**Issue by 1204709592** [alibaba/Sentinel#1677]
sentinel监控数据持久化到influxDB，然后做了压测，监控页面过会就提示内存溢出，我觉得数据过多，而且每十秒监控页面会自动刷新一次，请问有什么好的解决办法吗

**Comment by sczyh30** [comment]
可以参考社区已有的 issue/PR 及文章，结合自己的场景、量级 针对性地做一些改造。
