### ISSUE TITLE
contribute javadoc to a method in Sentinel/sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/java/com/alibaba/csp/sentinel/cluster/server/envoy/rls/rule/EnvoySentinelRuleConverter.java 

### ISSUE THREAD

**Issue by 129124** [alibaba/Sentinel#1683]
## Issue Description

Hi there, when I was reading the code of the function "public static long generateFlowId(String key)" in Sentinel/sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/java/com/alibaba/csp/sentinel/cluster/server/envoy/rls/rule/EnvoySentinelRuleConverter.java,
 I found it has no Javadoc. I would like to contribute by adding “returns the value of the given key. @param key". Can you check if this is correct?

**Comment by sczyh30** [comment]
Closing this issue as it seems like a robot and the content does not make sense.
