### ISSUE TITLE
dubbox 2.8.4 cannot find in dashboard

### ISSUE THREAD

**Issue by WangLei-lang** [alibaba/Sentinel#1691]
issue:
How com.alibaba.dubbo 2.8.4 version support？

description:
“sentinel-dubbo-adapter” Sub project，dubbo version update.
sub project testcase running is ok.
sentinel-dashboard console unable to refresh dubbo provider.
What to do next？

Thx.

**Comment by sczyh30** [comment]
Dubbo does not have 2.8.4 version.
Refer https://github.com/alibaba/Sentinel/wiki/FAQ regarding dashboard.

**Comment by cdfive** [comment]
2.8.4 may be dubbox, the dubbox has been merged into dubbo since 2.6.0, you may try or refer to `sentinel-dubbo-adapter`.

**Comment by sczyh30** [comment]
@WangLei-lang Any feedback?

**Comment by WangLei-lang** [comment]
If dubbox is supported, What steps are needed?
step 1：pom file Reference dubbox.
step 2：”sentinel-dubbo-adapter“ sub project replace package.
step 3：running mvn test, prompt success.
step 4：mvn install, pack jar.
step 5：test application start-up.

issue:
sentinel-dashboard console unable to refresh dubbo provider？

Thx.

**Comment by sczyh30** [comment]
Please check your config and logs according to https://github.com/alibaba/Sentinel/wiki/FAQ
