### ISSUE TITLE
1.8熔断降级 最小数设置不生效,一直为5

### ISSUE THREAD

**Issue by breezewindlw** [alibaba/Sentinel#1693]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please illustrate your problem according to the issue template?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by sczyh30** [comment]
Closing this issue due to no further feedback.
