### ISSUE TITLE
实时监控空白，规则链路均可用，服务器时间一致

### ISSUE THREAD

**Issue by engimatic** [alibaba/Sentinel#1694]
Issue Description
Type: bug report

Describe what happened (or what feature you want)
1. 所有服务的簇点链路均可见
2. 所有服务的规则均可下发
3. 实时监控空白，没有对应的metric日志

How to reproduce it (as minimally and precisely as possible)
所有服务启动，可以下发规则，可以看到链路监控，服务器时间一致，但是实时监控空白

Tell us your environment
jdk1.8.0_231
com.alibaba.cloud  2.1.0.RELEASE
starter-parent  2.1.0.RELEASE
sentinel: 1.6.3

### Anything else we need to know?
![image](https://user-images.githubusercontent.com/14733591/91270730-b298be80-e7ab-11ea-9774-104e43f0f188.png)
![image](https://user-images.githubusercontent.com/14733591/91270761-bdebea00-e7ab-11ea-8882-deadc44bceda.png)

**Comment by engimatic** [comment]
网络问题

**Comment by 15652309089** [comment]
> 网络问题

你好！我遇到的问题跟你一样的，你回答说网络问题，具体是什么情况呢？
我是本地的springcloud gateway对接sentinel-dashboard啊，这还能有什么网络问题呢？
