### ISSUE TITLE
当前的Sentinel只提供了流控规则的nacos持久化的方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则 的都未实现 后续实现的计划么?

### ISSUE THREAD

**Issue by fireflyhoo** [alibaba/Sentinel#1696]
## Issue Description

当前的Sentinel只提供了流控规则的nacos持久化的方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则 的都未实现 后续实现的计划么还是要我们自己实现? 然后是否可以更新一下wiki文档, 整个文档看起来各种跳转链接, 对新手非常的不友好.

**Comment by fireflyhoo** [comment]
有人不?>>>??

**Comment by JiangZian** [comment]
现在大多都是自己实现，这一块还在演进中

**Comment by fireflyhoo** [comment]
项目已经四年了呀, 准备几年后可以出来呢?

**Comment by FantaXI** [comment]
持久化热点规则出现的问题：
新增一个热点规则时，传来的json数据不能转换成com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowRule

收到的json(即图中的ruleStr):
```
{"app":"sentinel","gmtModified":1598930162707,"port":8723,"ip":"192.168.0.190","rule":{"burstCount":0,"clusterConfig":{"fallbackToLocalWhenFail":true,"sampleCount":10,"thresholdType":0,"windowIntervalMs":1000},"clusterMode":false,"controlBehavior":0,"count":1.0,"durationInSec":1,"grade":1,"limitApp":"default","maxQueueingTimeMs":0,"paramFlowItemList":[],"paramIdx":0,"resource":"a"},"id":18,"gmtCreate":1598930162707}
```

![image](https://user-images.githubusercontent.com/44300551/91800406-7e197c80-ec5b-11ea-81f1-af842542522f.png)

readValue执行后得到的Object：
![image](https://user-images.githubusercontent.com/44300551/91800519-b02ade80-ec5b-11ea-822c-6df354ffea5f.png)


控制台是模仿源码中的nacos流控规则改造的

publisher：
![image](https://user-images.githubusercontent.com/44300551/91800718-144da280-ec5c-11ea-89e5-5ff712d6016f.png)

controller
![image](https://user-images.githubusercontent.com/44300551/91800836-5545b700-ec5c-11ea-9b58-ad589bea6ad7.png)


个人觉得原因是ParamFlowRule 和 ParamFlowRuleEntity 结构不一致导致的。希望可以得到解决的方法

**Comment by sczyh30** [comment]
可以参考社区现有的 PR 及 Awesome Sentinel 中的相关实现。
