### ISSUE TITLE
Sentinel 控制台需要集群部署吗?

### ISSUE THREAD

**Issue by Timi8080** [alibaba/Sentinel#1698]
目前只会下载个jar然后启动, 这样单节点的部署。
没有找到Sentinal集群部署的办法, 跪求大佬们给资料; 
或者说Sentinal就根本不存在集群部署的说法?

**Comment by cdfive** [comment]
控制台jar目前是单实例部署。控制台比较轻量，如果挂了不影响应用端限流。
参考：#1567
