### ISSUE TITLE
在使用sentinel中遇到的问题

### ISSUE THREAD

**Issue by xiongtaohxl** [alibaba/Sentinel#1699]
1.sentinel-dashboard部署在服务器端，本地连接sentinel会报Failed to fetch metric from <http://192.168.2.1:8719/metric?startTime=1598519475000&endTime=1598519481000&
refetch=false> (ConnectionException: Connection timed out)
2.sentinel-持久化到nacos操作比较繁琐，能不能在sentinel-dashboard界面上配置的时候进行持久化
3.sentinel没看到集群方案，这倒不是大问题，个人感觉可以用nginx做集群映射一个地址出去就行

**Comment by cdfive** [comment]
1可以用telnet命令看看dashboard和应用端能否ping通
2是个挺实用的建议，涉及到界面和后台的改动，需要社区一起来设计和完善它

**Comment by xiongtaohxl** [comment]
看了一下源码，sentinel的规则数据之前是存在内存中的，持久化一下就可以了，不知道之前存内存基于什么样的考虑，不知道如何能加入社区，看是否方便加一下QQ方便沟通，我的QQ:465428430



---原始邮件---
发件人: "cdfive"<notifications@github.com&gt;
发送时间: 2020年8月30日(周日) 下午5:19
收件人: "alibaba/Sentinel"<Sentinel@noreply.github.com&gt;;
抄送: "xiongtaohxl"<465428430@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alibaba/Sentinel] 在使用sentinel中遇到的问题 (#1699)




 
1可以用telnet命令看看dashboard和应用端能否ping通
 2是个挺实用的建议，涉及到界面和后台的改动，需要社区一起来设计和完善它

**Comment by sczyh30** [comment]
You may refer to existing PRs regarding dashboard :)
