### ISSUE TITLE
控制台树目录中应该区分服务的在线状态和离线状态

### ISSUE THREAD

**Issue by 1423302537** [alibaba/Sentinel#17]
控制台树目录中应该区分服务的在线状态和离线状态，目前没区分，进程停了和正在运行的进程是一样的状态，不方便识别

**Comment by jz0630** [comment]
# 代码学习心得
1. 接入控制台的服务，定期上报心跳给控制台，间隔时间可设定，默认5秒，simple-http默认10秒
2. 服务节点5分钟没有上报心跳，会被判定离线

# 控制台优化
在目录树服务名称右侧，增加（健康数/总数）信息，如果健康数为0，则不现实该服务

# 讨论点
* 是否需要增加开关，确定健康数为0的服务，是否要显示？
* 是否要增加配置，修改5分钟离线判定？

**Comment by sczyh30** [comment]
Resolved in #376
