### ISSUE TITLE
com.alibaba.csp.sentinel.util.TimeUtil high CPU usage

### ISSUE THREAD

**Issue by wenit** [alibaba/Sentinel#1702]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

com.alibaba.csp.sentinel.util.TimeUtil 中死循环，占用了50%左右的cpu

代码如下：

``` java
static {
        currentTimeMillis = System.currentTimeMillis();
        Thread daemon = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    currentTimeMillis = System.currentTimeMillis();
                    try {
                        TimeUnit.MILLISECONDS.sleep(1);
                    } catch (Throwable e) {

                    }
                }
            }
        });
        daemon.setDaemon(true);
        daemon.setName("sentinel-time-tick-thread");
        daemon.start();
    }
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

sentinel版本1.7.1

redhat7.4

jdk1.8

**Comment by jasonjoo2010** [comment]
Is it necessary to improve TimeUtil as self adjustable model? @sczyh30 

Kind of initial thought:

<img width="765" alt="Screen Shot 2020-09-14 at 23 55 49" src="https://user-images.githubusercontent.com/17573073/93108903-fa916e00-f6e5-11ea-9d69-e531c353565f.png">
