### ISSUE TITLE
NettyTransportClient.getCurrentId is not threadsafe

### ISSUE THREAD

**Issue by John-Chan** [alibaba/Sentinel#1705]
## Issue Description

Type: *bug report* 

`NettyTransportClient.getCurrentId`

```java
    private int getCurrentId() {
        if (idGenerator.get() > MAX_ID) {
            idGenerator.set(0);
        }
        return idGenerator.incrementAndGet();
    }
```

个人理解这个ID应该是用于协议纠错，`getCurrentId`的目的是为了循环产生ID，且在循环周期内不重复，即生成ID为`1,2,3 ... -> MAX -> 1,2,3 ...`。

### Describe what happened (or what feature you want)

当前的实现，由于MAX ->  MIN 的过程不是一个原子操作，生成的ID可能会出现`1,2,3 ... -> MAX -> 1,1,2,3 ...`的情况。

**Comment by liqiangz** [comment]
是有这种情况，这里的 `set(0)` , 改成  `compareAndSet(currentId, 0)`,  应该就能避免并发修改了

**Comment by jasonjoo2010** [comment]
hi, @liqiangz @John-Chan 

Would you want to contribute on it?

**Comment by John-Chan** [comment]
> hi, @liqiangz @John-Chan
> 
> Would you want to contribute on it?

OK，I will PR for this issue
