### ISSUE TITLE
com.alibaba.csp.sentinel.slots.statistic.base.Window对象过多，怀疑是内存泄漏

### ISSUE THREAD

**Issue by log4leo** [alibaba/Sentinel#171]
![image](https://user-images.githubusercontent.com/2976620/46734066-bbba3880-ccc4-11e8-9412-8ec8e8c018e4.png)

com.alibaba.csp.sentinel.slots.statistic.base.Window对象和com.alibaba.csp.sentinel.slots.statistic.base.LongAdder对象过多，后者达到了3G之大，怀疑是内存泄漏

**Comment by sczyh30** [comment]
请问你们的应用使用了哪些整合，服务接口和 API 数目大概是多少，是否使用了按调用方限流？

---

How many entries / contexts is in your application? Did you use flow control by origin?

**Comment by log4leo** [comment]
> 请问你们的应用使用了哪些整合，服务接口和 API 数目大概是多少，是否使用了按调用方限流？
> 
> How many entries / contexts is in your application? Did you use flow control by origin?

使用了System限流和接口qps限流，接口qps限流只配置了两个接口，没有使用按调用方限流

**Comment by sczyh30** [comment]
根据提供的堆内存信息，没有看到 LongAdder 并发争用的相关占用（`com.alibaba.csp.sentinel.slots.statistic.base.Striped64$Cell`），而且 Window 数量反常的多，推测 origin 数目过多导致。这是 6000 entries，no origin，16 线程不断跑满的时候的情况：

![image](https://user-images.githubusercontent.com/9434884/46736461-b57b8a80-cccb-11e8-9b77-37f0df6e7791.png)

请问你们的应用使用了哪些整合（如 Web, Dubbo）？大约有多少个服务接口，API 数目（不是配置了哪些规则）？有没有自定义埋点（直接通过 `SphU.entry(xxx)`）？是否有修改过 sampleCount 和 flowInterval？

**Comment by log4leo** [comment]
> 根据提供的堆内存信息，没有看到 LongAdder 并发争用的相关占用（`com.alibaba.csp.sentinel.slots.statistic.base.Striped64$Cell`），而且 Window 数量反常的多，推测 origin 数目过多导致。这是 6000 entries，no origin，16 线程不断跑满的时候的情况：
> 
> ![image](https://user-images.githubusercontent.com/9434884/46736461-b57b8a80-cccb-11e8-9b77-37f0df6e7791.png)
> 
> 请问你们的应用使用了哪些整合（如 Web, Dubbo）？大约有多少个服务接口，API 数目（不是配置了哪些规则）？有没有自定义埋点（直接通过 `SphU.entry(xxx)`）？是否有修改过 sampleCount 和 flowInterval？

整合了Web和Dubbo，Dubbo的接口，服务加起来200个左右，没有自定义埋点，没有修改过是否有修改过 sampleCount 和 flowInterval。
不过有个点是我们整合了ACM（阿里云的diamond）来做规则的持久化和动态修改

**Comment by sczyh30** [comment]
可以在监控页面挑几个频繁调用的 Dubbo 服务，在对应机器上通过 Sentinel Transport API 看一下 origin 数目：`curl ip:port/origin?id=资源名称`

**Comment by CarpenterLee** [comment]
> 可以在监控页面挑几个频繁调用的 Dubbo 服务，在对应机器上通过 Sentinel Transport API 看一下 origin 数目：`curl ip:port/origin?id=资源名称`

我们怀疑是origin统计过多导致的，可以通过如下方式确认：
1. 首选去“簇点链路”页面选择某个资源名字；
2. 去“机器列表”页面选择一台机器，记住IP和port；
3. 通过curl命令查看资源上关联的origin个数：
```
curl 'ip:port/origin?id=资源名称' 
```
如果数量巨大，则说明origin数量太多了。

**Comment by log4leo** [comment]
<img width="753" alt="2018-10-11 9 08 04" src="https://user-images.githubusercontent.com/2976620/46774490-3b7feb80-cd35-11e8-9798-5ac2d881d159.png">

似乎没有取到数据

**Comment by log4leo** [comment]
尝试了几个不同的dubbo服务返回的都是和截图一样的情况

**Comment by sczyh30** [comment]
请在**能复现问题**的机器上执行 `jmap -histo pid | grep StatisticNode` 看一下 `StatisticNode` 的数量

**Comment by jasonjoo2010** [comment]
jstat -gcutil [pid] 的结果也贴下吧

**Comment by log4leo** [comment]
@sczyh30 @CarpenterLee  看起来不是StaticNode过多的问题

**Comment by sczyh30** [comment]
可否给一下 StatisticNode、DefaultNode、ClusterNode、EntranceNode 的数量，或者完整的堆分布文件？另外使用的 Sentinel 是哪个版本？

**Comment by log4leo** [comment]
<img width="1380" alt="2018-10-22 10 32 32" src="https://user-images.githubusercontent.com/2976620/47298516-9b866400-d64a-11e8-8bbc-151fd0338286.png">

MetricNode数量有点多

**Comment by grindwheel** [comment]
> <img alt="2018-10-22 10 32 32" width="1380" src="https://user-images.githubusercontent.com/2976620/47298516-9b866400-d64a-11e8-8bbc-151fd0338286.png">
> 
> MetricNode数量有点多

最后有解决了吗

**Comment by grindwheel** [comment]
@log4leo  请问最后的结论是什么呢，我这边正在调研中，也想集成到我们现有的应用中，但怕有坑，影响线上的业务

**Comment by sczyh30** [comment]
> <img alt="2018-10-22 10 32 32" width="1380" src="https://user-images.githubusercontent.com/2976620/47298516-9b866400-d64a-11e8-8bbc-151fd0338286.png">
> 
> MetricNode数量有点多

`MetricNode` 主要会在以下情况下生成：

- 每秒打印 metric 日志时，会生成所有资源的 MetricNode，但很快会被 GC
- Sentinel 控制台从 Sentinel 客户端拉取监控数据时，Sentinel 会从本地监控日志重建 MetricNode，format 以后回传给 Sentinel 控制台；如果查看监控非常频繁，可能会导致 MetricNode 比较多，但是也会被 GC

生产环境建议自行持久化存储监控数据，控制台直接从存储中拉取、聚合。

---

`MetricNode` is generated when:

- Every second Sentinel outputs metric log
- Sentinel Dashboard pulls metrics data from Sentinel transport API server

**Comment by log4leo** [comment]
@sczyh30 
我是自己在sentinel控制台里持久化了监控数据
控制台不会查看地非常频繁。

**Comment by sczyh30** [comment]
Any further discussion?

**Comment by wuwen5** [comment]
@log4leo 请问下 这个问题如何解决的呢？

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/82977000-268fc300-a013-11ea-84a2-c1f47c107277.png)
You can see It may be gc friendly ，but also cause a large cpu usage（FGC may consume a lot of cpu）

**Comment by StivenYang** [comment]
最后的结论是什么呢
