### ISSUE TITLE
springmvc接入sentinel对资源做限流不生效

### ISSUE THREAD

**Issue by lijiawei111** [alibaba/Sentinel#1713]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
sentinel Dashboard配置了限流规则如下：
![image](https://user-images.githubusercontent.com/30065573/92067681-7979d300-edd7-11ea-8fb9-95e5abe19e06.png)
但资源QPS如下，没有启到限流作用
![image](https://user-images.githubusercontent.com/30065573/92067625-5a7b4100-edd7-11ea-96ca-4edaefc19993.png)

环境和配置：
pom配置：
```
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-web-servlet</artifactId>
            <version>1.7.2</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.7.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.alibaba.csp/sentinel-spring-webmvc-adapter -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-webmvc-adapter</artifactId>
            <version>1.7.2</version>
        </dependency>
```
dispatcher配置：
```
  <mvc:interceptors>
        <mvc:interceptor>
            <mvc:mapping path="/**"/>
                <bean class="com.alibaba.csp.sentinel.adapter.spring.webmvc.SentinelWebInterceptor" />
        </mvc:interceptor>
    </mvc:interceptors>
```

启动参数：
```
-Dsentinel.nacos.groupId=SENTINEL_GROUP 
-Dsentinel.nacos.dataId=****
-Dsentinel.nacos.server.address=*** 
-Dproject.name=*** 
-Dcsp.sentinel.api.port=**
```
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
限流规则是存到Nacos里吗，那样的应用端需要使用对应的nacos-datasource。
可通过机器列表里查看ip和port，访问http://ip:port/getRules?type=flow看看应用端是否成功接收到规则。

**Comment by sczyh30** [comment]
You may refer to https://github.com/alibaba/Sentinel/wiki/FAQ to check relevant logs.

**Comment by sczyh30** [comment]
Any further feedback? @lijiawei111
