### ISSUE TITLE
1.8版本 ，关于熔断降级功能建议--支持异常类型过滤并不统计

### ISSUE THREAD

**Issue by sunqinbo** [alibaba/Sentinel#1714]
## 建议描述

> 降级功能中的异常比例 默认是记录全部程序异常，是否可以支持对不关心的异常进行过滤

**Comment by sczyh30** [comment]
It's already supported since 1.6.1. You may set the ignore list via `Tracer.setExceptionsToIgnore(arr)` method. Since 1.8.0 you may even set a predicate function (via `Tracer.setExceptionPredicate(p)`) to filter it.
