### ISSUE TITLE
converter can not convert rules because source is empty

### ISSUE THREAD

**Issue by ankeway** [alibaba/Sentinel#1716]
console continuous printing WARN log "converter can not convert rules because source is empty" 
if no configuration rules

com.alibaba.cloud.sentinel.datasource.converter.SentinelConverter.convert(String)
if (StringUtils.isEmpty(source)) {
   log.warn("converter can not convert rules because source is empty");
   return ruleCollection;
}

com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(S)
public T loadConfig(S conf) throws Exception {
        T value = parser.convert(conf);
        return value;
}

com.alibaba.cloud.sentinel.endpoint.SentinelHealthIndicator.doHealthCheck(Builder)
try {
   dataSource.loadConfig();
   ........
}

**Comment by sczyh30** [comment]
You may submit a PR to improve this in spring-cloud-alibaba repo.
