### ISSUE TITLE
Just a quick question, what does the word SphU stand for?

### ISSUE THREAD

**Issue by marvin263** [alibaba/Sentinel#1718]
As the title said, could anyone explain what the word SphU stands for? I'm just curious about it, and I saw the same doubt on zhihu https://www.zhihu.com/question/419639106, which has never been answered there

**Comment by sczyh30** [comment]
Refer #489

**Comment by xgxizz** [comment]
> As the title said, could anyone explain what the word SphU stands for? I'm just curious about it, and I saw the same doubt on zhihu https://www.zhihu.com/question/419639106, which has never been answered there

I also want to know what's the mean of CtSph ! hahaha.
