### ISSUE TITLE
Code comment documentation error

### ISSUE THREAD

**Issue by JiangZian** [alibaba/Sentinel#1720]
Type: bug report

### Describe what happened (or what feature you want)
Code comment documentation error. I found this while browsing through the code

### Describe what you expected to happen
I will now go back and fix these three errors

![111](https://user-images.githubusercontent.com/24679521/92585082-156b7900-f2c7-11ea-8a84-abe0298493d4.png)

**Comment by sczyh30** [comment]
Resolved in #1721
