### ISSUE TITLE
Demo中并发线程数阈值设置的是20，为什么执行结果会出现activeThread:20+的输出

### ISSUE THREAD

**Issue by xgxizz** [alibaba/Sentinel#1722]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
当我在本地运行FlowQpsDemo.java这个demo的时候，在控制台输出的结果中包含activeThread:20+的数据，按我的理解这种情况不应该发生呀，都应在是20以内的线程数，请赐教，谢谢。
when I run the demo in the link 'https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/flow/FlowQpsDemo.java',the outputin the console contains "activeThread:20+".what my question is why there are some 20+ outputs,not all within 20?

### Describe what you expected to happen
all the outputs are within 20.

### How to reproduce it (as minimally and precisely as possible)
you can run the demo in the link 'https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/flow/FlowQpsDemo.java' .

Looking forward to your reply,thanks very much!

**Comment by sczyh30** [comment]
Yes, it's not strictly accurate. See #59 and #76 for more information.

**Comment by xgxizz** [comment]
> Yes, it's not strictly accurate. See #59 and #76 for more information.

thanks!

**Comment by sczyh30** [comment]
Discussions and contributions are welcomed!
