### ISSUE TITLE
sentinel 如果是路由配置那种直接跳转的网关资源，进行熔断配置不生效

### ISSUE THREAD

**Issue by q1711300651** [alibaba/Sentinel#1725]
![image](https://user-images.githubusercontent.com/18044506/92836029-85d0e200-f40e-11ea-95b7-f5f96f81af03.png)

![image](https://user-images.githubusercontent.com/18044506/92836104-9e40fc80-f40e-11ea-83c6-e8b4bd51b6cc.png)
如果资源对应服务断点或者设置休眠，熔断未生效

**Comment by q1711300651** [comment]
如果资源对应服务关闭，熔断降级会生效

**Comment by sczyh30** [comment]
描述的具体些？什么配置，在什么条件下不生效。

**Comment by q1711300651** [comment]
使用csp版本1.7.0没有此问题，使用1.8.0会出现此问题
