### ISSUE TITLE
Packaging failure

### ISSUE THREAD

**Issue by developers-youcong** [alibaba/Sentinel#1728]
## Issue Description

Type: *bug*

### Describe what happened (or what feature you want)

I use the following command to package:

mvn clean package -Dmaven.test.skip=true

error info:

[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:test-compile (default) on project sentinel-grpc-adapter: prot
oc did not exit cleanly. Review output for more information. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :sentinel-grpc-adapter

### Describe what you expected to happen
Packaging success , Let me deploy to Linux

### Tell us your environment
1.8.0-SNAPSHOT

**Comment by cdfive** [comment]
Does your folder path has chinese name?
You may refer to #897

**Comment by developers-youcong** [comment]
![image](https://user-images.githubusercontent.com/45055576/92989140-83e94a80-f504-11ea-95a8-b14a1db8ae97.png)
Thank you very much. The problem has been solved. It was because of the Chinese path.
