### ISSUE TITLE
Sentinel 是否支持 RocketMQ 场景的限流和监控？

### ISSUE THREAD

**Issue by itlidaye** [alibaba/Sentinel#1731]
是否可以支持不是web应用的限流即监控？

**Comment by jasonjoo2010** [comment]
可以支持的，可以采用对应的适配或手动集成调用。

参考：
https://github.com/alibaba/Sentinel/wiki/主流框架的适配

**Comment by itlidaye** [comment]
手动集成调用  怎么统计吞吐量？

**Comment by jasonjoo2010** [comment]
> 手动集成调用 怎么统计吞吐量？

您想用在什么场景呢

**Comment by itlidaye** [comment]
统计rocketmq 消费数量及性能

**Comment by jasonjoo2010** [comment]
> 统计rocketmq 消费数量及性能

只统计吗？是否涉及降级和限流呢

**Comment by itlidaye** [comment]
目前只是统计，后面可能会用到

**Comment by jasonjoo2010** [comment]
> 目前只是统计，后面可能会用到

您可以先参考这里的rocketmq部分：
https://github.com/alibaba/Sentinel/wiki/主流框架的适配#apache-rocketmq

**Comment by itlidaye** [comment]
参考这部分是否还需要 自己实现 CommandHandler的业务

**Comment by jasonjoo2010** [comment]
> 参考这部分是否还需要 自己实现 CommandHandler的业务

做server-side的流控吗
这块的话，需要看broker如何扩展，这个目前只能从实际的场景中来做，想要从集群侧来做的话，要么采用隔一层做一层转发器，要么直接对broker进行扩展

**Comment by itlidaye** [comment]
显示 qps 需要自己CommandHandler的业务吗？

**Comment by itlidaye** [comment]
显示 qps 需要自己CommandHandler的业务吗？

**Comment by jasonjoo2010** [comment]
> 显示 qps 需要自己CommandHandler的业务吗？

不需要，这个只是看在哪个环节介入和集成。
如果正常的在client端做集成（使用者视角），那么可以继承出一个自定义的client，例如挂在发布消息方法内，进行sentinel的触发，发布成功后做exit，可以用producer group来做资源；
如果是站在消息集群视角，那这个就要复杂一点，往往需要引入一个中间层或是修改、增强集群组件来实现类似的功能。

所以这个还是得看实际的需求和场景来决定是用流控降级组件还是其它的方案来做。

**Comment by itlidaye** [comment]
好的谢谢，我先研究一下

**Comment by jasonjoo2010** [comment]
Close due to no further question.

有问题欢迎继续讨论:)
