### ISSUE TITLE
NodeSelectorSlot类中，向map中加入新的DefaultNode时，为什么不是直接通过put方法向map中添加？出于什么考虑？

### ISSUE THREAD

**Issue by xgxizz** [alibaba/Sentinel#1733]
## Issue Description

Type: *feature request*
Thank you for your attention，I have a question to ask.
the code is following:
`private volatile Map<String, DefaultNode> map = new HashMap<String, DefaultNode>(10);
public void entry(Context context, ResourceWrapper resourceWrapper, Object obj, int count, boolean prioritized, Object... args)
        throws Throwable {
        DefaultNode node = map.get(context.getName());
        if (node == null) {
            synchronized (this) {
                node = map.get(context.getName());
                if (node == null) {
                    node = new DefaultNode(resourceWrapper, null);
                    HashMap<String, DefaultNode> cacheMap = new HashMap<String, DefaultNode>(map.size());
                    cacheMap.putAll(map);
                    cacheMap.put(context.getName(), node);
                    map = cacheMap;
                }
                // Build invocation tree
                ((DefaultNode)context.getLastNode()).addChild(node);
            }
        }
        context.setCurNode(node);
        fireEntry(context, resourceWrapper, node, count, prioritized, args);
    }
`
When `node == null`, we will new a {@link DefaultNode} and add to `map`.Your mathod is building an object named cacheMap first,and than assigning it to map.Why not put the node to map directly as follow: `map.put(context.getName(), node);`,What are the considerations？
当 node == null 的时候，我们通过新建一个DefaultNode加入到map中，代码中的方法是先定义一个cacheMap对象，然后将map原有的值以及新建的node加入到cacheMap中。为什么不直接通过map.put(context.getName(), node);将node加入到map呢，是出于什么考虑才这样做的？

**Comment by liqiangz** [comment]
为了线程安全，使用了 copy on write

**Comment by sczyh30** [comment]
Yes it's a COW implementation (useful for scenarios where read operations >> write operations)

**Comment by felton321** [comment]
我看到代码里几乎所有的map都是COW，而没有使用ConcurrentHashMap,是因为经过测试，高并发场景下用时间换空间的COW性能更好，所以都没用ConCurrentHashMap是吗？

**Comment by felton321** [comment]
**The longer the application runs, the more stable this mapping will
     * become. so we don't concurrent map but a lock. as this lock only happens
     * at the very beginning while concurrent map will hold the lock all the time**
    直到我看到了这句话。。。原来如此
