### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by tain198127** [alibaba/Sentinel#1735]
## feature request

*feature request*

code ref：
com.alibaba.csp.sentinel.property.DynamicSentinelProperty#updateValue 

```
 RecordLog.info("[DynamicSentinelProperty] Config will be updated to: " + newValue, new Object[0]);

```
the newValue will invoke toString() method，__each time__. This might be cause performance degradation.

### feature request

In my humble opinion,  could add a statement before it, like 
```
if (logger.enableInfo())
```
sometimes, people could disable info level log, and toString() method will not be invoked. That is, I hope this method more higher efficiency
### Tell us your environment
version:1.8.0
system:mbp

**Comment by jasonjoo2010** [comment]
You're right. It's a legacy problem and now logging layer support the placeholder `{}` by which temporary objects can be avoided.

And how about fire a PR on it?
