### ISSUE TITLE
java: 程序包com.alibaba.csp.sentinel.adapter.grpc.gen不存在

### ISSUE THREAD

**Issue by jovi521** [alibaba/Sentinel#1743]
## Issue Description

Type:1.8.1-SNAPSHOT版本Test里面程序包不存在

**Comment by jasonjoo2010** [comment]
这个东西是打包时通过maven插件生成的

eclipse或其它ide导入项目应该能自动调用插件来生成

**Comment by sczyh30** [comment]
These stub classes are generated by `protoc-gen-grpc-java` plugin during the "test-compile" period, so you can execute `mvn clean test` to generate the classes (located in `target/generated-test-sources/protobuf`, can be automatically identified by IDEA).

**Comment by fxzzq** [comment]
java: 程序包com.alibaba.csp.sentinel.log不存在
