### ISSUE TITLE
sentinel-dashboard 在执行 mvn clean package 的时候报错没法继续执行，有大神能帮我指点一下吗，谢谢

### ISSUE THREAD

**Issue by FrankWasHello** [alibaba/Sentinel#1747]
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.alibaba.csp:sentinel-dashboard >-----------------
[INFO] Building sentinel-dashboard 1.8.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.alibaba.csp:sentinel-core:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.csp:sentinel-web-servlet:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.csp:sentinel-transport-simple-http:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.csp:sentinel-parameter-flow-control:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.csp:sentinel-api-gateway-adapter-common:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.csp:sentinel-datasource-nacos:jar:1.8.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.829 s
[INFO] Finished at: 2020-09-18T15:09:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sentinel-dashboard: Could not resolve dependencies for project com.alibaba.csp:sentinel-dashboard:jar:1.8.1-SNAPSHOT: The following artifacts could not be resolved: com.alibaba.csp:sentinel-core:jar:1.8.1-SNAPSHOT, com.alibaba.csp:sentinel-web-servlet:jar:1.8.1-SNAPSHOT, com.alibaba.csp:sentinel-transport-simple-http:jar:1.8.1-SNAPSHOT, com.alibaba.csp:sentinel-parameter-flow-control:jar:1.8.1-SNAPSHOT, com.alibaba.csp:sentinel-api-gateway-adapter-common:jar:1.8.1-SNAPSHOT, com.alibaba.csp:sentinel-datasource-nacos:jar:1.8.1-SNAPSHOT: Could not find artifact com.alibaba.csp:sentinel-core:jar:1.8.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jasonjoo2010** [comment]
找不到关联依赖，因为你是在子目录做的编译工作。

要么回到根目录，执行

```shell
mvn clean package -pl .,sentinel-dashboard -am
```

要么在子目录，把分支切到一个已发布的分支，比如1.8.0的分支

**Comment by FrankWasHello** [comment]
好的，谢谢指点

**Comment by jasonjoo2010** [comment]
如果有进一步的问题，请继续回复

**Comment by FrankWasHello** [comment]
OK
