### ISSUE TITLE
sentinel1.7.1控制台配置熔断降级问题

### ISSUE THREAD

**Issue by literatureandyou** [alibaba/Sentinel#1748]
## 使用sentinel1.7.1控制台配置熔断降级，发觉配置了熔断降级没有生效，不知道啥原因？
![image](https://user-images.githubusercontent.com/39126967/93582133-a253b800-f9d4-11ea-99d7-44e0cc14c06e.png)

**Comment by sczyh30** [comment]
熔断降级特性请使用最新的 1.8.0 版本，详情请参考文档：https://github.com/alibaba/Sentinel/wiki/熔断降级
