### ISSUE TITLE
Support Redis cluster in Redis data-source extension

### ISSUE THREAD

**Issue by TinChi0818** [alibaba/Sentinel#1749]
## Issue Description
在Redis单机模式下，sentinel可以工作。在Redis集群模式下，报错host is empty。
文档中仅有单机、哨兵模式如何构建：
![image](https://user-images.githubusercontent.com/33739928/93583183-12af0900-f9d6-11ea-9c40-e91e14d642f5.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
jdk1.8

**Comment by sczyh30** [comment]
Hi, Redis cluster is not supported yet in Redis data-source. Contributions are welcomed!

**Comment by liqiangz** [comment]
I will solve this issue.

**Comment by TinChi0818** [comment]
thanks------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;liqiangz&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月19日(星期六) 晚上7:24
收件人:&nbsp;&quot;alibaba/Sentinel&quot;<Sentinel@noreply.github.com&gt;;
抄送:&nbsp;&quot;TinChi0818&quot;<798130689@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/Sentinel] Support Redis cluster in Redis data-source extension (#1749)

**Comment by TinChi0818** [comment]
ok------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Eric&amp;nbsp;Zhao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月18日(星期五) 晚上7:34
收件人:&nbsp;&quot;alibaba/Sentinel&quot;<Sentinel@noreply.github.com&gt;;
抄送:&nbsp;&quot;TinChi0818&quot;<798130689@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/Sentinel] Sentinel整合Redis数据源（集群模式），RedisConnectionConfig如何构建？ (#1749)
