### ISSUE TITLE
web层，进来前如何进行limitApp全局设定？ 版本：spring-cloud-alibaba：2.2.1

### ISSUE THREAD

**Issue by codelearner1024** [alibaba/Sentinel#1750]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
我这边想在请求进入web层之前将limitApp根据request中信息进行特定设置，貌似不起作用？
我这边使用的spring-cloud-alibaba V2.2.1.
使用过filter处理，但是出现了乱跳的情况，一会返回：
`{
    "code": -1,
    "msg": "调用过于频繁！！！"
}`

一会又返回默认响应：
`（Blocked by Sentinel (flow limiting)）`

对应的过滤器代码如下：

`package com.wsn.openapi.dsb.filter;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebFilter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.annotation.Order;

import com.alibaba.csp.sentinel.Entry;
import com.alibaba.csp.sentinel.EntryType;
import com.alibaba.csp.sentinel.SphU;
import com.alibaba.csp.sentinel.context.ContextUtil;
import com.alibaba.csp.sentinel.slots.block.BlockException;
import com.alibaba.csp.sentinel.slots.block.authority.AuthorityException;
import com.alibaba.csp.sentinel.slots.block.flow.FlowException;
import com.wsn.openapi.common.util.StreamUtil;

/**
 * sentinel 限流统一过滤器
 *@Author:WWG
 *@date:2020年9月16日
 *@Version:1.0
 */
@Order(1)
@WebFilter(urlPatterns = "/*",filterName = "sentinelAuthorityFilter")
public class SentinelAuthorityFilter implements Filter {
    
    private static final Logger LOGGER = LoggerFactory.getLogger(SentinelAuthorityFilter.class);

    @Value("${server.servlet.context-path}")
    private String contextPath;
    
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest hSRequest = (HttpServletRequest)request;
        HttpServletResponse hSResponse = (HttpServletResponse)response;

        // sentinel 设置限流入口appId
        String appId = hSRequest.getHeader("appId");
        // sentinel 目前是真的粗，一个白名单，你orgin为null、为空，居然能够直接通过拦截 因此下方做一下适配
        appId = appId == null ? "errorAppId" : appId;
//        appId = appId == null ? "ZCSSB" : appId;
        // contextName 由自己定义，关键能唯一标识某一个方法 ，该过滤器为web 过滤器，因此，可以uri作为上下文名称
        String contextName = hSRequest.getRequestURI();
        ContextUtil.enter(contextName, appId);

        // 资源名
        String resource = contextName.replaceFirst(contextPath, "");

        Entry entry = null;
        try {
            entry = SphU.entry(resource, EntryType.IN);
            chain.doFilter(request, response);
        } catch (AuthorityException e) {
            LOGGER.error("非法调用者，已拦截！！！");
            StreamUtil.writeResponse(hSResponse, "请停止发送请求，您的信息已被追踪！！！");
        }catch (FlowException e) {
            LOGGER.error("warning  达到流量警戒线！！！");
            StreamUtil.writeResponse(hSResponse, "调用过于频繁！！！");
        } catch (BlockException e) {
            StreamUtil.writeResponse(hSResponse, "当前繁忙，请稍后再试！");
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
        ContextUtil.exit();
    }
}
`

**Comment by codelearner1024** [comment]
已解决

**Comment by hlcen66** [comment]
> 已解决

怎么解决的？
