### ISSUE TITLE
nacos持久化的方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则这些什么时候能实现？

### ISSUE THREAD

**Issue by design365** [alibaba/Sentinel#1759]
sentinel控制台都1.8了，到现在nacos持久化的方案也没完整解决方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则 的都未实现 ， 生产中也不敢用sentinel，这么一个好产品因为dashboard给耽误了实属不应该啊。

**Comment by design365** [comment]
其实sentinel-dashboard不支持nacos的降级规则 ,热点参数限流规则 ,系统规则 ,授权规则设置，等于名存实亡，搞不懂官方为啥不考虑这个问题。

**Comment by fireflyhoo** [comment]
用阿里云服务,可用解决你这个问题

**Comment by design365** [comment]
> 用阿里云服务,可用解决你这个问题

@fireflyhoo 跨机房去请求阿里云的云服务 这也不妥啊，难道这些开源的最终都得购买阿里云的？

**Comment by JemGeek** [comment]
+1，强烈建议加入此功能。

**Comment by jasonjoo2010** [comment]
深度定制是留给使用者去做的， dashboard目前只是一个主要面向演示、功能示例的工具。

如果初期没有对应的资源投入/不需要深度定制，可考虑通过transport模块，在app端同时集成read/write双向datasource，这样可以简单的通过dashboard经由transport通道进行写1发N的架构，这个组合架构下，datasource就与dashboard解耦了。

**Comment by design365** [comment]
> 深度定制是留给使用者去做的， dashboard目前只是一个主要面向演示、功能示例的工具。
> 
> 如果初期没有对应的资源投入/不需要深度定制，可考虑通过transport模块，在app端同时集成read/write双向datasource，这样可以简单的通过dashboard经由transport通道进行写1发N的架构，这个组合架构下，datasource就与dashboard解耦了。

其实不是留给使用者去做的，因为所有限流配置都在dashboard，相当于这里是中枢系统，这么重要的一个功能不做 ，就没法用sentinel了。

**Comment by zh69183787** [comment]
支持，大场内部其实都实现了，控制台管理下发的完整一套了，希望能尽快的打通支持

**Comment by design365** [comment]
@uzdz 是的，目前都1.8还不支持，不知道是不是让大家都去买阿里云的这部分收费项目。这是非常坑的一个地方。

**Comment by code81192** [comment]
使用nacos作为数据源的持久化规则配置可以参考我这篇文章[《Sentinel配置信息持久化与自定义熔断降级处理逻辑》](https://juejin.im/post/6890342340104454158)。里面Sentinel配置持久化与动态规则配置 1.8版本已经支持了降级等规则的持久化。

**Comment by rainy0714** [comment]
持久化到nacos这个网上一些教程，可以自己实现，我都是自己改造了源码才能用于生产的

**Comment by AlexMasonQi** [comment]
除了这个规则持久化问题外Sentinel还有一个很大的问题，就是Dashboard的Web页面和后台Java代码没有彻底分开，因此建议官方做成前后分离的那种模式，这样在生产环境中可以直接将Dashboard部署在Nginx里，否则生产环境还需要另起一个端口用于访问Dashboard，这在生产环境是不被允许的（安全问题），现在的1.8版本还是和Dashboard后台Java代码放在一起前后不分离，使用Nginx无法做对应转发（详见https://github.com/alibaba/Sentinel/issues/1131）这个问题也阻止了Dashboard在生产环境中的使用。

**Comment by kinggggg** [comment]
基于Sentinel release-1.7 源码修改了将限流规则持久化到Nacos中. 不得不说Sentinel的版本可真不敢恭维, 在版本的问题上踩了很多坑. 至于其他规则的持久化(类似保存到Nacos中, ZK中等)貌似网上的资料比较少, 是不是自己看源码来修改了?

**Comment by code81192** [comment]
你好！
没有修改源码，只是做配置，可以点链接查看我的文章



laibingf_dev@outlook.com
 
发件人： zeek
发送时间： 2020-12-29 18:45
收件人： alibaba/Sentinel
抄送： code81192; Comment
主题： Re: [alibaba/Sentinel] nacos持久化的方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则这些什么时候能实现？ (#1759)
基于Sentinel release-1.7 源码修改了将限流规则持久化到Nacos中. 不得不说Sentinel的版本可真不敢恭维, 在版本的问题上踩了很多坑. 至于其他规则的持久化(类似保存到Nacos中, ZK中等)貌似网上的资料比较少, 是不是自己看源码来修改了?

**Comment by kinggggg** [comment]
> 你好！ 没有修改源码，只是做配置，可以点链接查看我的文章 laibingf_dev@outlook.com 发件人： zeek 发送时间： 2020-12-29 18:45 收件人： alibaba/Sentinel 抄送： code81192; Comment 主题： Re: [alibaba/Sentinel] nacos持久化的方案, 降级规则 ,热点参数限流规则 ,系统规则 ,授权规则这些什么时候能实现？ (#1759) 基于Sentinel release-1.7 源码修改了将限流规则持久化到Nacos中. 不得不说Sentinel的版本可真不敢恭维, 在版本的问题上踩了很多坑. 至于其他规则的持久化(类似保存到Nacos中, ZK中等)貌似网上的资料比较少, 是不是自己看源码来修改了? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

首先十分感谢你文章, 看了那篇文章和相关的文章后, 收获很大. 但是你的那种不修改源码只做配置的方式感觉不是很直观, 因此需要在Nacos中编辑Json格式的规则数据. 因此, 最直观的方式是, 在Sentinel Dashboard中针对特定的API增加规则, 然后将该规则同步到Nacos中, 并且此时如果在Nacos中修改了相应的规则后(你的配置方式), 这些修改又会同步回Sentinel Dashboard.

**Comment by fireflyhoo** [comment]
就感觉是缺少个靠谱的 配置中心， 然后 一旦监控中心挂了 还会影响到 actuator 的监控检查， 哎用任何开源的组件都要进行细致的测试， 差点就坑到自己了

**Comment by fengjx** [comment]
我 fork 了一个版本，支持了所有配置持久化到 apollo，不改动官方源码，方便滚动升级，支持 docker。大家可以看看。

https://github.com/fengjx/Sentinel/wiki
