### ISSUE TITLE
1.8.0版本的熔断中 error_count 不进入half-open 状态

### ISSUE THREAD

**Issue by yanfeiLee** [alibaba/Sentinel#1766]
## Issue Description

Type: *bug report* or *feature request*
bug report：half-open 异常

### Describe what happened (or what feature you want)
在单位统计时间(1min) 后，请求超过设定数，异常数超过设定数时，在指定时间后，不会进half-open 状态，即使正确请求到来，
熔断器仍处于熔断状态，知道1min 后，才恢复正常

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Spring Cloud  Hoxton.SR1
Spring Boot 2.2.2.RELEASE

**Comment by sczyh30** [comment]
Could you please check whether your actual Sentinel version is 1.8.0? And could you please check your logs of degrade rules in `~/logs/csp/sentinel-record.log`?

**Comment by sczyh30** [comment]
@yanfeiLee Any feedback?
