### ISSUE TITLE
When slowRatioThreshold equals 1.0，requests will never be blocked

### ISSUE THREAD

**Issue by xierunzi** [alibaba/Sentinel#1769]
在慢调用比例策略的降级规则中，把比例阈值设置为1，我发现所有的请求都不会被降级了。
源码是这样写的
if (currentRatio > maxSlowRequestRatio) {
            transformToOpen(currentRatio);
        }
我不太清楚这属不属于一个bug，因为我自己的理解是阈值设置为1时，只要在一个窗口内的所有请求都超过了最大RT，那么资源就会被降级。
不知是我的理解有误还是确实阈值为1时不符合预期。

**Comment by sczyh30** [comment]
Would you like to submit a PR to improve it?

**Comment by xierunzi** [comment]
> Would you like to submit a PR to improve it?

sure.
