### ISSUE TITLE
Configure fallback logic for Dubbo services in the dashboard

### ISSUE THREAD

**Issue by waveng** [alibaba/Sentinel#177]
通过注解的方式可以设置 fallback ，但通过dubbo filter 方式，无法设置 fallback，只能通过 DubboFallback 接口设置全局的 fallback。服务降级可否添加控制台设置 fallback ？就如 dubbo 的 mock 一样配置一样，我希望为每一个接口都可以设置 fallback ，而不是全局的fallback ？

**Comment by sczyh30** [comment]
Good idea, but it's tricky to design a general pattern for the fallback for different services. Discussions are welcomed!
