### ISSUE TITLE
Why do we need to compare memory addresses in DynamicSentinelProperty?

### ISSUE THREAD

**Issue by Bryce-huang** [alibaba/Sentinel#1771]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

Why do we need to compare memory addresses here? Can you tell me the reason? This will make it impossible to reuse the original bean, thank you.

com.alibaba.csp.sentinel.property.DynamicSentinelProperty.java
```java

    private boolean isEqual(T oldValue, T newValue) {
        if (oldValue == null && newValue == null) {
            return true;
        } else {
            return oldValue == null ? false : oldValue.equals(newValue);
        }
    }
```

### Tell us your environment

jdk 11
### Anything else we need to know?

source code

**Comment by jasonjoo2010** [comment]
Hi, Bryce

I guess what you really mean is not the piece of code you showed in your description but the `equals()` method in implementations like `FlowRule.java:189`. Right?

If so you'd better to explain more to let others know the reason it need to be cached and reused. In most cases it's not a scenario frequently create/destroy and press gc heavily.

**Comment by Bryce-huang** [comment]
In my case, I need to modify the rules dynamically, but only a part of the data needs to be modified.  For example, adjust the traffic size, delete rules, and add new rules.  So I need to manage the life cycle of the rules, but I found that sentinel does not support very well.  Do you have any best practices for this?  thank you for your reply

**Comment by jasonjoo2010** [comment]
> In my case, I need to modify the rules dynamically, but only a part of the data needs to be modified. For example, adjust the traffic size, delete rules, and add new rules. So I need to manage the life cycle of the rules, but I found that sentinel does not support very well. Do you have any best practices for this? thank you for your reply

Hi, Bryce

To manage `life cycle` of rules there should always be a `cloning` happened, no matter inner or outer(by caller).
In this case I suggest that you can manage the life cycle in your own way while do extra cloning when performing updating. Thus, `outer` way.

**Comment by Bryce-huang** [comment]
Thank you for your reply, but I still have a few questions here, how does the sentinel cluster rate limit achieve server-side high availability? Does the server support multiple instances? If multiple instances are supported, how to synchronize data between multiple instances?

**Comment by jasonjoo2010** [comment]
> Thank you for your reply, but I still have a few questions here, how does the sentinel cluster rate limit achieve server-side high availability? Does the server support multiple instances? If multiple instances are supported, how to synchronize data between multiple instances?

Hi, Bryce

The simplest way to be HA in cluster mode is to initialize multiple instances, for instance A, B and C, and use keepalived / proxy / etc. to make only one instance active at the same time. When it failed switch to another one and HA is achieved. Surely better to use same IP address in this process.

**Comment by jasonjoo2010** [comment]
Close due to no new response. Please feel free to reopen it if there was any further question.
