### ISSUE TITLE
1.8 网关应用下，在请求链路下点击降级，点击新增前端判断不对，还是用的旧的判断方法

### ISSUE THREAD

**Issue by cugftp** [alibaba/Sentinel#1774]
![image](https://user-images.githubusercontent.com/32768479/94568079-a918df80-029e-11eb-93c1-18e9a38628ed.png)
![image](https://user-images.githubusercontent.com/32768479/94568138-ba61ec00-029e-11eb-9a22-0c5ce99a84a8.png)

**Comment by cugftp** [comment]
1.7版本时，前端构造对象时，会设置一个默认参数statIntervalMs: 1000 当前版本没有设置......
我排查了一天

**Comment by sczyh30** [comment]
It should not happen. You may clear the cache of your browser and refresh the page.
