### ISSUE TITLE
控制台1.8.0版本，接入端 Sentinel 1.7.x，熔断降级慢调用比例阈值设置无效

### ISSUE THREAD

**Issue by githubzsy** [alibaba/Sentinel#1777]
## Issue Description
*bug report*

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
降级规则-比例阈值设定无效，设置为0.5全变成1了

### Describe what you expected to happen
是bug吗？

### How to reproduce it (as minimally and precisely as possible)
详细可以查看上传的gif图片

### Tell us your environment
Sentinel 服务端是1.8版本
客户端是1.7.1版本
![image](https://user-images.githubusercontent.com/38803299/94991163-c659f080-05b3-11eb-859a-f321f21f1a4c.png)

### Anything else we need to know?
[
![比例阈值设置无效](https://user-images.githubusercontent.com/38803299/94983158-9b02e180-0572-11eb-99a5-0bd17a73e50b.gif)
](url)

**Comment by githubzsy** [comment]
另外，重启之后为什么降级的设置界面和之前不一样了？
![image](https://user-images.githubusercontent.com/38803299/94986158-ffcc3500-058e-11eb-8e31-f58c3a4bb933.png)

**Comment by sczyh30** [comment]
最新版本控制台熔断降级配置适用于 Sentinel 1.8.0 及以上版本的熔断降级特性，建议升级下版本。

**Comment by githubzsy** [comment]
> 最新版本控制台熔断降级配置适用于 Sentinel 1.8.0 及以上版本的熔断降级特性，建议升级下版本。

好的

**Comment by XuZhenWei** [comment]
> 
解决了吗？我用的1.81的版本配置了熔断降级，生效了一次，过了熔断时长后再试就不生效了。
