### ISSUE TITLE
控制台看不到接入的 API gateway

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/Sentinel#1780]
# 版本
- **springcloud**: Greenwich.SR2
- **sentinel**: 1.6.3
- **sentinel dashboard**: 1.6.3
- **springcloud alibaba**: 2.1.0.RELEASE
# 问题描述
我尝试根据[文档](https://github.com/alibaba/Sentinel/wiki/%E7%BD%91%E5%85%B3%E9%99%90%E6%B5%81)创建工程，并启动，但是发现sentinel dashboard 并没有对应的服务
# 我想要的帮助
我想要找到，sentinel 如何把服务信息注册到 sentinel dashboard 的，可否具体提供下对应类的，全类名，我自己debug

**Comment by sczyh30** [comment]
可以参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) 里面的指示进行排查。

**Comment by new1943** [comment]
我也出现了。。看到API 管理。

**Comment by xiaorendetian** [comment]
1、check the param sentinel.app.type = 1
2、only when there is a request, dashboard then can find it

**Comment by new1943** [comment]
I just remove eager config. The dashboard can show API manage menu.
But Route rate limit config is not enabled
