### ISSUE TITLE
Nacos 持久化问题

### ISSUE THREAD

**Issue by SunShinechenxi** [alibaba/Sentinel#1786]
2020-10-09 23:00:04.803 ERROR 1380 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.ds1.nacos' to com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties:

    Reason: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.String'. Check configuration for 'groupId'

Action:

Update your application's configuration

**Comment by SunShinechenxi** [comment]
Sentinel 1.8version 版本 ，jdk 1.8.0.26 和0.19都试过了

**Comment by whaty** [comment]
解决了吗？我这里也是

**Comment by whaty** [comment]
hello，在你的pom里面添加如下：
``
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
``

**Comment by SunShinechenxi** [comment]
感谢您的帮助 ，根据您的反馈 我的问题 已经得到解决了 。共同努力

**Comment by sczyh30** [comment]
> 感谢您的帮助 ，根据您的反馈 我的问题 已经得到解决了 。共同努力

Could you please illustrate your solution here?

**Comment by SunShinechenxi** [comment]
添加 验证类 validation   并 配置 nacos 账号密码 
![image](https://user-images.githubusercontent.com/35024555/96391740-68045300-11ec-11eb-9bee-c8d08077efc2.png)

**Comment by dovedong** [comment]
我遇到了相同的问题，项目中依赖了hibernate-validator, 通过maven查看依赖，有两个版本 5.3.6，和 6.2.3，看感觉上去最终依赖的是6.2.3，但实际却并非如此。只要exclude hibernate-validator 5.3.6即可。
