### ISSUE TITLE
com.alibaba.csp.sentinel.dashboard.client.CommandFailedException: invalid type

### ISSUE THREAD

**Issue by aaaaaa1** [alibaba/Sentinel#1789]
下载1.7.1源码运行dashboard服务，访问控制台保存错：
![image](https://user-images.githubusercontent.com/5926342/95651187-1b998300-0b1b-11eb-899b-4ebe7b802e9a.png)

请问该怎么解决呢？我用1.8的源码正常

**Comment by sczyh30** [comment]
参考 https://github.com/alibaba/Sentinel/wiki/控制台

> 注：若通过控制台推送规则时出现 invalid type 或 empty type 的错误，请确保 transport 模块版本与 core 模块版本保持一致；若控制台版本 >= 1.7.1，请将接入端的相关依赖也升级至 1.7.1 及以上版本。

**Comment by sczyh30** [comment]
Any feedback?
