### ISSUE TITLE
控制台部署在国内，应用在国外，对性能影响大吗。两个网络环境有一定延迟

### ISSUE THREAD

**Issue by dayuange123** [alibaba/Sentinel#1790]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jasonjoo2010** [comment]
控制台本身不影响可用性、性能

**Comment by sczyh30** [comment]
网络环境仅影响推送速度/监控拉取，不影响 Sentinel 本身功能。
