### ISSUE TITLE
logger SPI不支持所有的log自定义格式化

### ISSUE THREAD

**Issue by Sanit1** [alibaba/Sentinel#1793]
## Issue Description

你好，单机服务目前想要简单的使用下sentinel进行限流，但是目前sentinel产生的log不符合我那边要求。
log目录虽然可以自定义，我也尝试了你们sentinel-demo-log-logback这个demo但是我发现只能对RecordLog、CommandCenterLog主动生成的log自定义，但是还是会产生没法自定义的log文件

### Describe what happened (or what feature you want)

com-alibaba-csp-sentinel-demo-log-logback-TestSentinel-metrics.log.2020-10-13
com-alibaba-csp-sentinel-demo-log-logback-TestSentinel-metrics.log.2020-10-13.idx
sentinel-block.log

这三个log文件无法自定义

### Describe what you expected to happen

metrics log跟block log 可以自定义

### How to reproduce it (as minimally and precisely as possible)

运行sentinel-demo-log-logback
执行测试代码

```
public static void main(String ... args) {
        initFlowRules();
        while (true) {
            Entry entry = null;
            try {
                entry = SphU.entry("HelloWorld");
                /*您的业务逻辑 - 开始*/
                System.out.println("hello world");
                /*您的业务逻辑 - 结束*/
            } catch (BlockException e1) {
                /*流控逻辑处理 - 开始*/
                System.out.println("block!");
                /*流控逻辑处理 - 结束*/
            } finally {
                if (entry != null) {
                    entry.exit();
                }
            }
        }
    }
    private static void initFlowRules(){
        List<FlowRule> rules = new ArrayList<>();
        FlowRule rule = new FlowRule();
        rule.setResource("HelloWorld");
        rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule.setCount(20);
        rules.add(rule);
        FlowRuleManager.loadRules(rules);
    }
```

### Tell us your environment

jdk1.8.0_211

**Comment by sczyh30** [comment]
可否描述一下什么场景需要定制 metric log 和 block log？这些日志都有固定的解析格式

**Comment by Sanit1** [comment]
> 可否描述一下什么场景需要定制 metric log 和 block log？这些日志都有固定的解析格式

公司规定log在统一的目录 然后那个目录里的文件使用logstash 跟 filebeat采集处理log 所以需要自定义

**Comment by wangliweicc** [comment]
block log 可以通过在责任链中添加一个logSlot 自定义输出：
@SpiOrder(-8001)
public class XxLogSlot extends AbstractLinkedProcessorSlot<DefaultNode> {

    @Override
    public void entry(Context context, ResourceWrapper resourceWrapper, DefaultNode obj, int count, boolean prioritized, Object... args)
        throws Throwable {
        try {
            fireEntry(context, resourceWrapper, obj, count, prioritized, args);
        } catch (BlockException e) {
            // 按自己需要格式输出日志
            Logger logger = LoggerFactory.getLogger(this.getClass());
            logger.info(resourceWrapper.getName() + "," + e.getClass().getSimpleName() + "," + e.getRuleLimitApp() + "," + 
            context.getOrigin() + "," + count);
            throw e;
        } catch (Throwable e) {
            RecordLog.warn("Unexpected entry exception", e);
        }

    }

    @Override
    public void exit(Context context, ResourceWrapper resourceWrapper, int count, Object... args) {
        try {
            fireExit(context, resourceWrapper, count, args);
        } catch (Throwable e) {
            RecordLog.warn("Unexpected entry exit exception", e);
        }
    }
}
最后 /resources/META-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot 中加入XxLogSlot
