### ISSUE TITLE
Adaptor中提供的 sentinel-web-filter的实现 导致sentinel占用内存特别多

### ISSUE THREAD

**Issue by yaoyuandota** [alibaba/Sentinel#1797]
（1）sentinel-web-filter默认的实现，没有考虑user/{id} 这种场景，虽然Map<ResourceName, Slot> 有最大6000个限制，但是user/1 ,user/2 。。。。。。user/6000 这种uri很容易让map满，建议在cleaner中提供springmvc处理带参uri的实现。可以减少内存使用。
（2）在HasStatisticSlot中会处理各种node，。。。。。 导致LongAdder特别多（延迟创建的），建议能后判断一下 资源名下是否配置了规则， 配置了再增加ClusterNode和DefaultNode和Origin。这样能减少内存使用

**Comment by sczyh30** [comment]
Hi, for (1) you may use [sentinel-spring-webmvc-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter) or Spring Cloud Alibaba Sentinel, which provides better support for REST APIs.

For 2, we may need to get the monitoring data before adding rules, but it's a good idea. Maybe we could provide a "memory-saving" mode. You may submit a new issue for tis. Discussions and contributions are welcomed!
