### ISSUE TITLE
如何给控制台配置访问前缀？

### ISSUE THREAD

**Issue by JavaApes** [alibaba/Sentinel#1804]
## 问题

Type:  *feature request*

我将sentinel接入了 springcloud，并通过nginx配置了反向代理来访问sentinel 控制台。
在控制台中，可以看到应用、簇点链路，但是实时监控页面没有数据：

![image](https://user-images.githubusercontent.com/59696744/96417207-9cdfcc80-1223-11eb-962b-9abe68ea61fd.png)

然后我进入簇点链路页面，发现 QPS 等数据都是0

![image](https://user-images.githubusercontent.com/59696744/96417358-c26cd600-1223-11eb-9ae1-55fcd4ef047c.png)

接着我尝试创建流控规则，发现请求的路径不对，我配置的nginx 代理的路径前缀被丢掉了：

![image](https://user-images.githubusercontent.com/59696744/96417528-fb0caf80-1223-11eb-832c-882508aa2342.png)

实际请求路径应该是：xxx.com/sentinel/app/xxx 这样的形式，而在这里，其中的 /sentinel 前缀丢失了。

![image](https://user-images.githubusercontent.com/59696744/96417802-66ef1800-1224-11eb-9b10-8b9817abfe88.png)

我在问题列表没有找到我这个问题的相关解决方案，想请教下，这种情况应该如何解决？

**Comment by jasonjoo2010** [comment]
目前dashboard的静态部分，并不支持任意子目录部署的方式，建议在不改动的情况下，使用独立域名部署。

**Comment by JavaApes** [comment]
> 目前dashboard的静态部分，并不支持任意子目录部署的方式，建议在不改动的情况下，使用独立域名部署。

好的，我试下

**Comment by JavaApes** [comment]
> > 目前dashboard的静态部分，并不支持任意子目录部署的方式，建议在不改动的情况下，使用独立域名部署。
> 
> 好的，我试下

可以了。感谢！

**Comment by jasonjoo2010** [comment]
任何问题，请继续提issue/继续回复
