### ISSUE TITLE
目前官方是否只支持流控规则动态配置，不支持降级规则、热点规则动态配置？

### ISSUE THREAD

**Issue by uzdz** [alibaba/Sentinel#1805]
目前按照官方wiki修改的dashboard只支持了流控规则动态配置。请问是这样的吗？需要开发自己集成降级规则、热点规则的动态配置吗？

**Comment by uzdz** [comment]
#1759

**Comment by code81192** [comment]
使用nacos作为数据源的持久化规则配置可以参考我这篇文章《Sentinel配置信息持久化与自定义熔断降级处理逻辑》。里面Sentinel配置持久化与动态规则配置 1.8版本已经支持了降级等规则的持久化。

**Comment by code81192** [comment]
使用nacos作为数据源的持久化规则配置可以参考我这篇文章[《Sentinel配置信息持久化与自定义熔断降级处理逻辑》](https://juejin.im/post/6890342340104454158)。里面Sentinel配置持久化与动态规则配置 1.8版本已经支持了降级等规则的持久化。
