### ISSUE TITLE
Sentinel部署到Linux不能访问界面

### ISSUE THREAD

**Issue by developers-youcong** [alibaba/Sentinel#1806]
## Issue Description

Sentinel部署到Linux不能访问界面，控制台正常打印出对应的信息，如图所示:
![image](https://user-images.githubusercontent.com/45055576/96427322-fac6e100-1230-11eb-8f01-0553868285ba.png)

### Describe what you expected to happen

我希望能够界面访问并登录成功

### Tell us your environment
Linux:CentOS7.8
Java:1.8
SpringCloud:Hoxton.SR4

**Comment by sczyh30** [comment]
从日志上看你把 dashboard 页面的端口设成 8718 了，检查下端口访问的是否正确。

**Comment by developers-youcong** [comment]
问题已解决。初步判断应该是我将防火墙设置错误导致的。

**Comment by developers-youcong** [comment]
感谢
