### ISSUE TITLE
集群限流 单机均摊 在TokenServer不可用时单机qps不正确

### ISSUE THREAD

**Issue by daiwenlong** [alibaba/Sentinel#1808]
![image](https://user-images.githubusercontent.com/30766058/96669407-c0c02100-138f-11eb-9089-c3fb225aaa2a.png)

启动两个client，向其中一台发起请求
![image](https://user-images.githubusercontent.com/30766058/96669547-07158000-1390-11eb-89c7-b0a08c4153b6.png)

预期 在TokenServer不可用时单机qps应该为15 
![image](https://user-images.githubusercontent.com/30766058/96669641-35935b00-1390-11eb-9a6d-54653672bc56.png)

测试结果qps为30

如何解决？

**Comment by Jayice-zjw** [comment]
补充一下
用开发者模式看了看，好像根本就没传cluster相关的字段？
这是分别勾选和不勾选集群模式发出来的两个请求，并没有传"clusterMode"字段
![I}62C8_DI{O2W5 FJNT1PDR](https://user-images.githubusercontent.com/49588871/98110520-2ce76c80-1eda-11eb-9458-b6eeb88989f2.png)
![C581V`AR DAU@2$Q3$SGP}O](https://user-images.githubusercontent.com/49588871/98110558-3a045b80-1eda-11eb-83a2-13b61b6c3a29.png)
所以，返回的response中的clusterMode也始终为false....
查看了下前端js，好像也确实没有相关字段
![)5CS0W0YA5 NKUR8SP~QWKI](https://user-images.githubusercontent.com/49588871/98110861-b5fea380-1eda-11eb-86bf-ca443642d182.png)
所以这里的勾选应该是啥也没选上？

**Comment by sczyh30** [comment]
集群流控规则只支持在 v2 页面（`/v2/flow`) 结合数据源配置。
