### ISSUE TITLE
Dashboard 启动后浏览器访问不了

### ISSUE THREAD

**Issue by huankai** [alibaba/Sentinel#1810]
使用Chrome 浏览器访问页面一片空白, 报错信息如下: 
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=sentinelDashboardApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3DsentinelDashboardApp%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A24%3A186%0A%20%20%20%20at%20b%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A23%3A251)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A23%3A494%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A38%3A117%0A%20%20%20%20at%20n%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A7%3A333)%0A%20%20%20%20at%20g%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A37%3A488)%0A%20%20%20%20at%20eb%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A41%3A249)%0A%20%20%20%20at%20c%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A19%3A463)%0A%20%20%20%20at%20yc%20(http%3A%2F%2Flocalhost%3A8080%2Flib%2Fjs%2Fangular.min.js%3A20%3A274)

**Comment by cdfive** [comment]
Chrome里按F12打开开发者工具，在Network的tab里勾选Disable cache，再刷新页面试试呢

**Comment by sczyh30** [comment]
Any feedback?
