### ISSUE TITLE
ErrorEntryFreeException: The order of entry exit can't be paired with the order of entry, current entry in context

### ISSUE THREAD

**Issue by wencyGit** [alibaba/Sentinel#1811]
- Sentinel 版本1.8
- 在Sentinel 控制台没有任何配置
- 项目版本如下

![image](https://user-images.githubusercontent.com/21151964/96818231-a8193f00-1453-11eb-8b0a-52d66b09d375.png)
- 报错如下

![image](https://user-images.githubusercontent.com/21151964/96818115-6a1c1b00-1453-11eb-804c-75df634a9ab6.png)

- 以下是我的demo

[cloud-sentinel-test.zip](https://github.com/alibaba/Sentinel/files/5419730/cloud-sentinel-test.zip)

**Comment by cdfive** [comment]
Your demo use spring-cloud-starter-alibaba-sentinel 2.1.2.RELEASE of spring-cloud-alibaba, which use sentinel 1.7.1, not 1.8.
Maybe you can upgrade to the latest version. Refer to #1533 #1482 for more discussions.
