### ISSUE TITLE
spring-cloud-alibaba-sentinel 2.2.1版本与spring-cloud-starter-gateway整合时，流控规则无效

### ISSUE THREAD

**Issue by cherish123** [alibaba/Sentinel#1812]
## Issue Description

Type: *bug report* or *feature request*
bug report

### Describe what happened (or what feature you want)
spring-cloud-alibaba-sentinel 2.2.1 with spring-cloud-starter-gateway,the rule dosen't work

### Describe what you expected to happen

when qps up 1,the request should be blocked by Sentinel
### How to reproduce it (as minimally and precisely as possible)
set qps 1,the rule can be seen in the dashboard,but it can't work

### Tell us your environment
<java.version>1.8</java.version>
<springboot.version>2.2.5.RELEASE</springboot.version>
<springcloud.version>Hoxton.SR3</springcloud.version>
<springcloudalibabaversion>2.2.1.RELEASE</version>

**Comment by cherish123** [comment]
![image](https://user-images.githubusercontent.com/15699957/96821556-bdde3280-145a-11eb-967b-2ab4be5ba622.png)

**Comment by sczyh30** [comment]
You may upgrade Spring Cloud Alibaba Sentinel to the latest version.

**Comment by ycd12345** [comment]
I meet the exactly same problem

**Comment by bohbohman** [comment]
I meet the exactly same problem, you need  set flow-control dependency
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-parameter-flow-control</artifactId>
</dependency>
