### ISSUE TITLE
Expose jmx endpoint for sentinel

### ISSUE THREAD

**Issue by qixiaobo** [alibaba/Sentinel#1814]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
jmx support for sentinel metrics

so  we can use prometheus jmx_exporter to collect metric
also jmx is standard to manage our java bean.

>>>Java Management Extensions (JMX) was introduced in J2SE 5.0 release. It provides an architecture to manage resources dynamically at runtime. JMX is used mostly in enterprise applications to make the system configurable or to get the state of application at any point of time.

**Comment by sczyh30** [comment]
Good idea. Discussion and contributions are welcomed!

**Comment by brothelul** [comment]
I will try to add this feature.

**Comment by sczyh30** [comment]
> I will try to add this feature.

Look forward to your PR~
