### ISSUE TITLE
1.8.0版本中，sentinel新增降级规则返回404。已检查过dashboard和server版本都是1.8.0

### ISSUE THREAD

**Issue by UniqueDavidQian** [alibaba/Sentinel#1817]

**Comment by steveoyung** [comment]
is there more error logs ?

**Comment by x519286925** [comment]
https://github.com/alibaba/spring-cloud-alibaba/issues/759
可以看一下文档，希望对你有帮助
![image](https://user-images.githubusercontent.com/32434890/97655063-32d6eb00-1a9f-11eb-88d0-5d46344cdbdb.png)

**Comment by UniqueDavidQian** [comment]
> [alibaba/spring-cloud-alibaba#759](https://github.com/alibaba/spring-cloud-alibaba/issues/759)
> 可以看一下文档，希望对你有帮助
> ![image](https://user-images.githubusercontent.com/32434890/97655063-32d6eb00-1a9f-11eb-88d0-5d46344cdbdb.png)

我用的是java11，不知可否

**Comment by x519286925** [comment]
> > [alibaba / spring-cloud-alibaba＃759](https://github.com/alibaba/spring-cloud-alibaba/issues/759)
> > 可以看一下文档，希望对你有帮助
> > ![图片](https://user-images.githubusercontent.com/32434890/97655063-32d6eb00-1a9f-11eb-88d0-5d46344cdbdb.png)
> 
> 我用的是java11，不知可否
![image](https://user-images.githubusercontent.com/32434890/97695382-e90df500-1ade-11eb-848a-e495b70cc119.png)

这两天我也刚好有空研究一下，确实是jdk版本的原因。应该是nacos的一个jdk兼容问题。我换了 1.8.0_2XX以下版本确实可以了。
![image](https://user-images.githubusercontent.com/32434890/97695449-0642c380-1adf-11eb-9e78-ffa624af83a0.png)

**Comment by sczyh30** [comment]
Any other feedback?

**Comment by UniqueDavidQian** [comment]
> Any other feedback?

oh，I used Sentinel1.7.2 before，and I used  Sentinel1.8.0 later，I found that I have to clear the browser cache.
