### ISSUE TITLE
通过sentinel-dashboard操作gateway降级规则问题

### ISSUE THREAD

**Issue by cherish123** [alibaba/Sentinel#1818]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
1.直接在请求链路增加降级规则时，弹框统计窗口时长需大于0
![image](https://user-images.githubusercontent.com/15699957/97138546-6cec7800-1793-11eb-895e-8a160f376933.png)

2.在降级规则那边设置降级规则后，降级不起作用

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
         <parent>
               <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-starter-parent</artifactId>
              <version>2.2.5.RELEASE</version>
               <relativePath/> 
       </parent>

          <java.version>1.8</java.version>

           <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.3.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by sczyh30** [comment]
For 1, you may need to clear the cache of your browser.
For 2, could you please illustrate your rules and your Sentinel version?

**Comment by HuiBear** [comment]
我也碰到这个问题，在降级的表单中，没有统计窗口时长这个参数设置，所以想问一下，这块统计窗口时长是根据其它参数算出来，还是要设置的？？？

**Comment by zl530380** [comment]
对于2，也遇到不能降级 sentinel 1.8.0  通过网关降级规则 异常数和异常比例 不能降级 [{"app":"ctgaba-app-gateway","count":0.1,"gmtCreate":1607685842400,"gmtModified":1607685842400,"grade":1,"id":1,"ip":"","limitApp":"default","minRequestAmount":1,"port":18721,"resource":"ctgaba-app-content-biz","statIntervalMs":1000,"timeWindow":1}]

**Comment by sczyh30** [comment]
对于 API gateway 目前不支持针对 4xx、5xx 等状态码记为错误（仅针对异常记录错误）。可以在这里讨论下完善的方案：#1842
