### ISSUE TITLE
“降级规则”配置支持应用维度推送

### ISSUE THREAD

**Issue by dslztx** [alibaba/Sentinel#1819]
“降级规则”配置不支持应用维度方式吗？有这个开发的打算吗？

**Comment by sczyh30** [comment]
可否简单描述下场景？

**Comment by dslztx** [comment]
> 可否简单描述下场景？

流控规则 不是支持应用维度模式吗？可以配置整个应用的流控规则，写入ZK，Nacos，Apollo，那能支持下降级规则的应用维度配置方式吗？而不是单节点的

**Comment by dslztx** [comment]
或者是不是直接推荐用Nacos直接配置的方式，而不是让Sentinel控制台去推送？

**Comment by sczyh30** [comment]
可以直接接数据源，Sentinel 控制台进行相应改造。
