### ISSUE TITLE
注解方式实现限流demo测试方法参数未和异常捕捉方法参数一致。导致限流不能被Handler和fallback处理。

### ISSUE THREAD

**Issue by Resswagger** [alibaba/Sentinel#1821]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
可否详细描述下，配以例子

**Comment by JiangZian** [comment]
Can you describe it in detail

**Comment by Resswagger** [comment]
> 可否详细描述下，配以例子

https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81
中文文档里面的TestService这个test()方法的参数列表没有和Fallback函数一样。该处代码有误。
public class TestService {

    // 对应的 `handleException` 函数需要位于 `ExceptionUtil` 类中，并且必须为 static 函数.
    @SentinelResource(value = "test", blockHandler = "handleException", blockHandlerClass = {ExceptionUtil.class})
    public void test() {
        System.out.println("Test");
    }

    // 原函数
    @SentinelResource(value = "hello", blockHandler = "exceptionHandler", fallback = "helloFallback")
    public String hello(long s) {
        return String.format("Hello at %d", s);
    }
    
    // Fallback 函数，函数签名与原函数一致或加一个 Throwable 类型的参数.
    public String helloFallback(long s) {
        return String.format("Halooooo %d", s);
    }

    // Block 异常处理函数，参数最后多一个 BlockException，其余与原函数一致.
    public String exceptionHandler(long s, BlockException ex) {
        // Do some log here.
        ex.printStackTrace();
        return "Oops, error occurred at " + s;
    }
}

**Comment by sczyh30** [comment]
第一个 `test` 的例子的目的是演示 blockHandler 在其它类时的配置 (blockHandlerClass)，独立于 `hello` 的示例。这里放在最前面容易导致误解，已进行调整。
