### ISSUE TITLE
[BUG]Overrunning test `FlowRuleManagerTest.testLoadAndGetRules`

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#1822]
## Issue Description

In the previous PR #1783 there was an issued test case that had a thread that may overrun its lifecycle.  This would cause an obstruction in the following cases.

### Describe what happened (or what feature you want)

Test cases became unstable.

### Describe what you expected to happen

All related resources and processes should be limited in the case.

### How to reproduce it (as minimally and precisely as possible)

In integration tests in travis-ci.

### Anything else we need to know?

No.

**Comment by sczyh30** [comment]
Resolved in #1823
