### ISSUE TITLE
1.8版本 控制台启动不了？是不是只能用内网ip

### ISSUE THREAD

**Issue by 65725738** [alibaba/Sentinel#1827]
本地用localhost可以启动控制台。我装到一台linux服务器上面。配置公网ip启动可以，但是不能访问。也没防火墙。这个是什么原因？

**Comment by 65725738** [comment]
*/
@Component
public class ExceptionHandlerPage implements UrlBlockHandler {
    @Override
    public void blocked(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, BlockException e) throws IOException {
        // BlockException 异常接口，其子类为Sentinel五种规则异常的实现类
        // AuthorityException 授权异常
        // DegradeException 降级异常
        // FlowException 限流异常
        // ParamFlowException 参数限流异常
        // SystemBlockException 系统负载异常
        ResponseData data = new ResponseData();
        if (e instanceof FlowException) {
            data = new ResponseData(-1, "接口被限流了。");
        } else if (e instanceof DegradeException) {
            data = new ResponseData(-2, "接口被降级了。");
        }
 
        httpServletResponse.setContentType("application/json;charset=utf-8");
        httpServletResponse.getWriter().write(JSON.toJSONString(data));
    }
}

这个1.8就没有UrlBlockHandler 接口了。这个用什么替代了？

**Comment by 65725738** [comment]
BlockExceptionHandler变成这个了。为什么要删除呀，disable一下。兼容要考虑呀

**Comment by sczyh30** [comment]
> 本地用localhost可以启动控制台。我装到一台linux服务器上面。配置公网ip启动可以，但是不能访问。也没防火墙。这个是什么原因？

Refer #1830
