### ISSUE TITLE
Sentinel 1.7.1 在阿里云上部署了Sentinel，本地部署测试代码啊，为什么无法查询到实时监控，流控规则也没有

### ISSUE THREAD

**Issue by longquan99** [alibaba/Sentinel#1830]
在阿里云上部署了Sentinel，本地部署测试代码啊，阿里云的8719，8720，8089端口都开放了，监控的项目名称可以显示出来,无法查询到实时监控， 簇点链路也没有
![图片](https://user-images.githubusercontent.com/37918902/97575976-865a2200-1a28-11eb-8576-45e2a78684f3.png)

在本地部署一套Sentinel ，实时监控和 簇点链路都能正常查看
在网上查了一下，有人说是因为本地和阿里云的时间不一样，但是如果只是时间不一致，流控规则应该能看到，但是我这个连 簇点链路都没有，估计不是时间的原因

**Comment by jasonjoo2010** [comment]
点到［机器列表］里看看注册上来的ip是什么，然后在dashboard上ping一下对应的地址看看网络通不通

不要跨网部署，除非你知道在做什么

**Comment by longquan99** [comment]
我是想部署一个验证环境，不想在本地运行sentinel，ping机器列表的网址果然不行，我的IP是本地网络IP,必须有公网IP才行

**Comment by guoxu252220** [comment]
我也是这个问题，不知道为什么

**Comment by jasonjoo2010** [comment]
@longquan99 @guoxu252220 

因为控制台需要与应用节点在网络上双向互通，所以需要实际部署的环境达到双向互通，且应用上报正确的ip。

这个一般是建议dashboard与实际的应用在同一网络环境，而不是搞集中化
