### ISSUE TITLE
how to use sentinel or how to use aspectj on a j2se application without spring?

### ISSUE THREAD

**Issue by zhangqing132155** [alibaba/Sentinel#1835]
Any one can help me?
because it is an old enterprise application based on j2se,so it never planed to migrate to spring.
now my problem is how to use sentinel or how to use aspectj on a j2se application without spring?
show me the code if it is possible.

**Comment by zhangqing132155** [comment]
or just tell me it's not possible to work without spring,and why.

**Comment by jasonjoo2010** [comment]
You can refer to https://www.eclipse.org/aspectj/doc/released/progguide/examples.html for examples integrating manually.

**Comment by zhangqing132155** [comment]
> You can refer to https://www.eclipse.org/aspectj/doc/released/progguide/examples.html for examples integrating manually.
how to use aspectj is written in page "https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81#aspectj".
it says like that"
AspectJ
若您的应用直接使用了 AspectJ，那么您需要在 aop.xml 文件中引入对应的 Aspect：
<aspects>
    <aspect name="com.alibaba.csp.sentinel.annotation.aspectj.SentinelResourceAspect"/>
</aspects>"

the problem is i don't know where is the aop.xml and what pattern is it.

**Comment by jasonjoo2010** [comment]
> > You can refer to https://www.eclipse.org/aspectj/doc/released/progguide/examples.html for examples integrating manually.
> > how to use aspectj is written in page "https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81#aspectj".
> > it says like that"
> > AspectJ
> > 若您的应用直接使用了 AspectJ，那么您需要在 aop.xml 文件中引入对应的 Aspect：
> 
> "
> the problem is i don't know where is the aop.xml and what pattern is it.

You can refer `aop.xml` in [here](https://github.com/yoloho/enhanced-data/tree/master/enhanced-data-cache#aopxml)

**Comment by jasonjoo2010** [comment]
Close due to no further response.
