### ISSUE TITLE
关于大流量下MetricNode过多求教：可否降低日志落盘频率

### ISSUE THREAD

**Issue by renxinlin** [alibaba/Sentinel#1843]
SCHEDULER.scheduleAtFixedRate(new MetricTimerListener(), 0, 1, TimeUnit.SECONDS);
这里定时器的时间能否配置化;降低下执行频率

List<MetricNode> nodesOfEverySecond = rollingCounterInMinute.details();
// 未使用
rollingCounterInMinute.detailsOnCondition(timePredicate);
这里的timePredicate是指窗口开始时间吗？ 能否弄成配置化

执行器的频率如果小于窗口的时间,收集度量信息到磁盘的效果与现在的是否相同？

**Comment by brothelul** [comment]
the same question: #1867

**Comment by sczyh30** [comment]
Resolved via #1919 (released in 1.8.1)
