### ISSUE TITLE
找不到UrlBlockHandler接口，是否已经更新源码，如果更新源码，请同时更新文档

### ISSUE THREAD

**Issue by UniqueDavidQian** [alibaba/Sentinel#1846]

**Comment by JiangZian** [comment]
Can you elaborate on the problems you have encountered

**Comment by UniqueDavidQian** [comment]
> Can you elaborate on the problems you have encountered

![image](https://user-images.githubusercontent.com/40854898/98774240-91984f00-2425-11eb-952a-4f171c97cfb5.png)

**Comment by UniqueDavidQian** [comment]
> Can you elaborate on the problems you have encountered
上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)

**Comment by JiangZian** [comment]
> > Can you elaborate on the problems you have encountered
> > 上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
> > ![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)
> 
> 不知道你是否能看到图片，我把图片的内容粘贴出来
> ····························································································································································
> 限流处理逻辑：默认情况下，当请求被限流时会返回默认的提示页面 Blocked by Sentinel (flow limiting)。您也可以通过 JVM 参数 -Dcsp.sentinel.web.servlet.block.page 或代码中调用 WebServletConfig.setBlockPage(blockPage) 方法设定自定义的跳转 URL，当请求被限流时会自动跳转至设定好的 URL。同样您也可以实现 UrlBlockHandler 接口并编写定制化的限流处理逻辑，然后将其注册至 WebCallbackManager 中。
> ····························································································································································
> public class SentinelConfig implements UrlBlockHandler{
> 
> }
> ····························································································································································
> 提示cannet resolve symbol 'UrlBlockHandler'，我确定Sentinel本身已经生效，我已测试过流控功能

com/alibaba/csp/sentinel/adapter/servlet/callback/UrlBlockHandler   ?This class in Sentinel\sentinel-adapter

**Comment by UniqueDavidQian** [comment]
> > > Can you elaborate on the problems you have encountered
> > > 上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
> > > ![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)
> > 
> > 
> > 不知道你是否能看到图片，我把图片的内容粘贴出来
> > ····························································································································································
> > 限流处理逻辑：默认情况下，当请求被限流时会返回默认的提示页面 Blocked by Sentinel (flow limiting)。您也可以通过 JVM 参数 -Dcsp.sentinel.web.servlet.block.page 或代码中调用 WebServletConfig.setBlockPage(blockPage) 方法设定自定义的跳转 URL，当请求被限流时会自动跳转至设定好的 URL。同样您也可以实现 UrlBlockHandler 接口并编写定制化的限流处理逻辑，然后将其注册至 WebCallbackManager 中。
> > ····························································································································································
> > public class SentinelConfig implements UrlBlockHandler{
> > }
> > ····························································································································································
> > 提示cannet resolve symbol 'UrlBlockHandler'，我确定Sentinel本身已经生效，我已测试过流控功能
> 
> com/alibaba/csp/sentinel/adapter/servlet/callback/UrlBlockHandler ?This class in Sentinel\sentinel-adapter

需要引入额外的依赖包吗，我在这个依赖包里没有发现
<dependency>
       <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>

**Comment by JiangZian** [comment]
> > > > Can you elaborate on the problems you have encountered
> > > > 上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
> > > > ![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)
> > > 
> > > 
> > > 不知道你是否能看到图片，我把图片的内容粘贴出来
> > > ····························································································································································
> > > 限流处理逻辑：默认情况下，当请求被限流时会返回默认的提示页面 Blocked by Sentinel (flow limiting)。您也可以通过 JVM 参数 -Dcsp.sentinel.web.servlet.block.page 或代码中调用 WebServletConfig.setBlockPage(blockPage) 方法设定自定义的跳转 URL，当请求被限流时会自动跳转至设定好的 URL。同样您也可以实现 UrlBlockHandler 接口并编写定制化的限流处理逻辑，然后将其注册至 WebCallbackManager 中。
> > > ····························································································································································
> > > public class SentinelConfig implements UrlBlockHandler{
> > > }
> > > ····························································································································································
> > > 提示cannet resolve symbol 'UrlBlockHandler'，我确定Sentinel本身已经生效，我已测试过流控功能
> > 
> > 
> > com/alibaba/csp/sentinel/adapter/servlet/callback/UrlBlockHandler ?This class in Sentinel\sentinel-adapter
> 
> 需要引入额外的依赖包吗，我在这个依赖包里没有发现
> 
> com.alibaba.cloud
> spring-cloud-starter-alibaba-sentinel
I suggest you look at the source code for the "sentinel-adapter/sentinel-web-servlet" with a sample demo for viewing

**Comment by UniqueDavidQian** [comment]
> > > > > Can you elaborate on the problems you have encountered
> > > > > 上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
> > > > > ![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)
> > > > 
> > > > 
> > > > 不知道你是否能看到图片，我把图片的内容粘贴出来
> > > > ····························································································································································
> > > > 限流处理逻辑：默认情况下，当请求被限流时会返回默认的提示页面 Blocked by Sentinel (flow limiting)。您也可以通过 JVM 参数 -Dcsp.sentinel.web.servlet.block.page 或代码中调用 WebServletConfig.setBlockPage(blockPage) 方法设定自定义的跳转 URL，当请求被限流时会自动跳转至设定好的 URL。同样您也可以实现 UrlBlockHandler 接口并编写定制化的限流处理逻辑，然后将其注册至 WebCallbackManager 中。
> > > > ····························································································································································
> > > > public class SentinelConfig implements UrlBlockHandler{
> > > > }
> > > > ····························································································································································
> > > > 提示cannet resolve symbol 'UrlBlockHandler'，我确定Sentinel本身已经生效，我已测试过流控功能
> > > 
> > > 
> > > com/alibaba/csp/sentinel/adapter/servlet/callback/UrlBlockHandler ?This class in Sentinel\sentinel-adapter
> > 
> > 
> > 需要引入额外的依赖包吗，我在这个依赖包里没有发现
> > com.alibaba.cloud
> > spring-cloud-starter-alibaba-sentinel
> > I suggest you look at the source code for the "sentinel-adapter/sentinel-web-servlet" with a sample demo for viewing

OK,thank you very much!

**Comment by JiangZian** [comment]
> > > > > > Can you elaborate on the problems you have encountered
> > > > > > 上面是我从Spring Cloud Alibaba Sentinel官网看到的Wiki，下面是我自己的代码，引入的依赖包是基于Sentinel 1.7.1的
> > > > > > ![微信图片_20201111135508](https://user-images.githubusercontent.com/40854898/98774413-ec31ab00-2425-11eb-8416-7a87e2fc784f.png)
> > > > > 
> > > > > 
> > > > > 不知道你是否能看到图片，我把图片的内容粘贴出来
> > > > > ····························································································································································
> > > > > 限流处理逻辑：默认情况下，当请求被限流时会返回默认的提示页面 Blocked by Sentinel (flow limiting)。您也可以通过 JVM 参数 -Dcsp.sentinel.web.servlet.block.page 或代码中调用 WebServletConfig.setBlockPage(blockPage) 方法设定自定义的跳转 URL，当请求被限流时会自动跳转至设定好的 URL。同样您也可以实现 UrlBlockHandler 接口并编写定制化的限流处理逻辑，然后将其注册至 WebCallbackManager 中。
> > > > > ····························································································································································
> > > > > public class SentinelConfig implements UrlBlockHandler{
> > > > > }
> > > > > ····························································································································································
> > > > > 提示cannet resolve symbol 'UrlBlockHandler'，我确定Sentinel本身已经生效，我已测试过流控功能
> > > > 
> > > > 
> > > > com/alibaba/csp/sentinel/adapter/servlet/callback/UrlBlockHandler ?This class in Sentinel\sentinel-adapter
> > > 
> > > 
> > > 需要引入额外的依赖包吗，我在这个依赖包里没有发现
> > > com.alibaba.cloud
> > > spring-cloud-starter-alibaba-sentinel
> > > I suggest you look at the source code for the "sentinel-adapter/sentinel-web-servlet" with a sample demo for viewing
> 
> OK,thank you very much!

Don't mention it, the source code should answer your questions

**Comment by UniqueDavidQian** [comment]
下载了源码，大概看了看，Sentinel1.7.2支持使用ControllerAdvice来捕获BlockException，于是，如果不想每个流控方法都写blockHandler，可以这么做

@SentinelResource(value = "test_sentinel")
public CommonResponse findById(Integer id) {
    //operations
}

@RestControllerAdvice
public class GlobalExceptionHandler { 
    @ExceptionHandler(value = Exception.class)
    public CommonResponse handleException(Exception e) {
        String msg = "捕获到异常";
        if(e instanceof FlowException) {
            msg = "流控了";
        } else if(e instanceof DegradeException)  {
            msg = "熔断了";
        } else if(e instanceof ParamFlowException){
            msg = "热点控制";
        } else if(e instanceof SystemBlockException) {
            msg = "系统规则控制";
        } else  if(e instanceof AuthorityException){
            msg = "授权控制";
        }
        return new CommonResponse(500, msg, null);
    }
}
