### ISSUE TITLE
sentinel整合apollo等配置中心时，如何支持动态添加应用

### ISSUE THREAD

**Issue by zjun123123** [alibaba/Sentinel#1847]
在用sentinel 1.8最新版本，用apollo做持久化规则时，需改造sentinel.dashboard控制台代码 , 
 参考 ApolloDataSourceDemo的代码 如下。appId,namespaceName ,flowRuleKey  等应用信息如何动态传入，因为我可能有很多不同的应用，以及将来的应用需要接入控制台和apollo，sentinel控制台如何动态添加应用规则而不用每次都重启控制台，这如何改造呢？

    private static void loadRules() {
        String appId = "sentinel-demo";
        String apolloMetaServerAddress = "http://localhost:8080";
        System.setProperty("app.id", appId);
        System.setProperty("apollo.meta", apolloMetaServerAddress);
        String namespaceName = "application";
        String flowRuleKey = "flowRules";
        String defaultFlowRules = "[]";
        ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new ApolloDataSource<>(namespaceName,
            flowRuleKey, defaultFlowRules, source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
        }));
        FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
    }

**Comment by zjun123123** [comment]
理解错误，已解决

**Comment by JunjieBian** [comment]
@zjun123123 这个能说下解决方案吗？我也有这个困惑
