### ISSUE TITLE
dashboard显示不出来

### ISSUE THREAD

**Issue by nihao12358** [alibaba/Sentinel#1850]
![image](https://user-images.githubusercontent.com/5662431/98913838-e4940400-2502-11eb-99f3-1c72ff685395.png)

已经运行了，就是刷不出应用来
![image](https://user-images.githubusercontent.com/5662431/98913807-d6de7e80-2502-11eb-9171-978244a63e71.png)

![image](https://user-images.githubusercontent.com/5662431/98913931-fd9cb500-2502-11eb-8a35-52ac64eb50f2.png)

在线等！！！

**Comment by xuande** [comment]
应用至少被访问一次的才会有数据，默认不会加载应用列表

**Comment by nihao12358** [comment]
> 应用至少被访问一次的才会有数据，默认不会加载应用列表

是的，

**Comment by nihao12358** [comment]
已经正常显示

**Comment by JiangZian** [comment]
> 已经正常显示

最好还是有一个存储库比较好

**Comment by nihao12358** [comment]
老是刷不出数据，非人性的，不好用
