### ISSUE TITLE
sentinel有没有聚合功能和指定部分接口监控？

### ISSUE THREAD

**Issue by nihao12358** [alibaba/Sentinel#1852]
问题描述：
**1、sentinel有没有聚合功能、因为是放在网关api接口Controller上，由于是restful风格，url的参数可能会有变化**
如：

![image](https://user-images.githubusercontent.com/5662431/99041804-93e5df00-25c6-11eb-81d1-b8224451e9f1.png)

`/apis/client/v1/addresses/distributionRules/{code}`
能不能所有这些接口都聚合在一起统计，而不是分开？

2、指定部分接口监控、各个模块的接口都统一在api上了，如果sentinel放到api模块上，那就所有接口的数据都在sentinel dashboard显示了，这对sentinel dashboard性能有没有影响，其实不需要对整个项目都监控，只是想监控几个访问频率比较高的接口，并对其限流和降级操作，其他接口没有什么压力的接口，不需要关心。。

**Comment by jasonjoo2010** [comment]
参考： https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-servlet

里面有关于url clean相关的内容

**Comment by sczyh30** [comment]
For 1, you may use https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter instead, which could extract the API pattern automatically.
