### ISSUE TITLE
关于sentinel 1.8.0 和nacos 1.3.1的持久化后规则全部失效问题

### ISSUE THREAD

**Issue by qukefan1995** [alibaba/Sentinel#1853]
sentinel规则持久化到nacos，改造了sentinel控制台， 可以在nacos控制修改rule.json并同步至sentinel，也可以在sentinel的簇点链路及其他页面配置并同步至nacos，  设置了自定义的groupId及namespace，双向同步持久化都是没问题，但是持久化的规则在客户端中一直未生效，导致无法进行限流、降级、热点规则等。 使用的是nacos1.3.1和sentinel1.8.0， 客户端依赖了sentinel-datasource-nacos 1.8.0版本，且配置了spring.cloud.sentinel.datasource, 客户端启动时通过NacosDataSource已经获取到规则了，但是通过sentinelSource注解绑定资源后，规则一直未生效

**Comment by sczyh30** [comment]
You may refer to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) to check the relevant logs.
