### ISSUE TITLE
sentinel-dashboard的web界面不支持sso

### ISSUE THREAD

**Issue by sundong1982** [alibaba/Sentinel#1854]
k8s或其他集群环境下都需要负载切换后再登录。

**Comment by sczyh30** [comment]
Could you please illustrate your question?

**Comment by sundong1982** [comment]
直接用最简单的方式部署3个节点的sentinel-dashboard.jar，前面放一个负载均衡器，就能发现这个问题

**Comment by jasonjoo2010** [comment]
是的，dashboard不支持集群部署。
