### ISSUE TITLE
一个SentinelResource是否可以根据里面的逻辑做相互隔离

### ISSUE THREAD

**Issue by lik0914** [alibaba/Sentinel#1858]
我们业务中定义了SentinelResource一个资源，这个资源可以根据不同的场景配置不同的第三方URL。

比如请求的第三方URL，A，由于超时的之类的问题，被降级了，那么第三方接口，B，通过这个资源请求的时候，也会受到影响。

这种情况下，怎么处理呢

**Comment by sczyh30** [comment]
You may use different resource name here.
