### ISSUE TITLE
context-path导致的问题

### ISSUE THREAD

**Issue by helloyaoge** [alibaba/Sentinel#1862]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/12529019/99374686-cca2f280-28fd-11eb-80bb-f07476f40e22.png)

java -Dsentinel.dashboard.auth.username=admin -Dsentinel.dashboard.auth.password=123456 -Dserver.port=8050 -Dcsp.sentinel.dashboard.server=localhost:8050 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar

这个是我的启动命令，启动之后登陆页面的首页图片加载有问题。账号设置了，但是不生效。
还有一个问题是，通一个jar mac上面运行有context-path . Linux 环境运行没有context-path 什么原因呢

### Describe what you expected to happen
我这边需要nginx 做反向代理的

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by yujun505646964** [comment]
其实配置了context-path也没用，因为js里面的请求路径写死的uri,用nginx做反响代理，没法统一一个路由，暴力点的方法给全部js的请求uri上加上统一前缀/sentinel，参考nacos（不懂前端，不知道有其他简单的方案没）

**Comment by jasonjoo2010** [comment]
这个问题在这个pr已解决，下个版本即可发布，可以提前使用（拉master编译dashboard）

https://github.com/alibaba/Sentinel/pull/1851

**Comment by jasonjoo2010** [comment]
Close due to no further responses.
Please feel free to reopen it and drop more replies if necessary.
