### ISSUE TITLE
Dashboard应写好持久化代码

### ISSUE THREAD

**Issue by lly835** [alibaba/Sentinel#1863]
https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E5%9C%A8%E6%8E%A7%E5%88%B6%E5%8F%B0%E9%85%8D%E7%BD%AE%E7%9A%84%E8%A7%84%E5%88%99%E5%AD%98%E5%9C%A8%E5%93%AA%E9%87%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BA%94%E7%94%A8%E9%87%8D%E5%90%AF%E8%A7%84%E5%88%99%E5%B0%B1%E6%B6%88%E5%A4%B1%E4%BA%86

A: push 模式的数据源（如配置中心）都是只读的。对于配置中心类型的数据源（如 ZooKeeper），我们推荐在推送规则时直接推送至配置中心，然后配置中心再自动推送至所有的客户端（即 Dashboard -> Config Center -> Sentinel DataSource -> Sentinel），目前需要自行改造控制台。可以参见：在生产环境中使用 Sentinel 控制台。

自行改造控制台，有难度，改不好会出错的。建议官方把持久化功能写进去，开发者只需要配置持久化类型即可。

**Comment by lly835** [comment]
我看有人已经提了pr  https://github.com/alibaba/Sentinel/pull/1711
为什么不管了

**Comment by sczyh30** [comment]
You may help to review the corresponding PR.
