### ISSUE TITLE
Add downgrade to encounter js alerting errors

### ISSUE THREAD

**Issue by HuiBear** [alibaba/Sentinel#1864]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

sentinel version:1.8.1 

contribute gateway and sentinel, want to add downgrade(降级) rules. js alert content to prevent submit

![1605668747(1)](https://user-images.githubusercontent.com/23185576/99478249-07a13680-298f-11eb-93a4-5211937ee926.jpg)

### Tell us your environment
OS: win10
ide: idea

**Comment by sczyh30** [comment]
Please clear cache of your browser. And #1781 will add support for configuring statInterval.
