### ISSUE TITLE
The priority of local/cluster flow rules | 配置单机和集群限流规则的哪个生效

### ISSUE THREAD

**Issue by Moonergfp** [alibaba/Sentinel#1866]
wiki集群限流模块写的流量不均时，集群限流情况下会被单机限制。但是看代码com.alibaba.csp.sentinel.slots.block.flow.FlowRuleChecker#checkFlow这块，是遍历所有规则fast failed。代码跟wiki描述矛盾呐，如果是单机限流数<集群限流数，流量不均时依然可能会被单机限而导致达不到想要的集群限流效果。
![image](https://user-images.githubusercontent.com/12962780/99617636-ad6da780-2a5a-11eb-9961-fd8a1d4f00a3.png)

**Comment by sczyh30** [comment]
The rules were sorted with `FlowRuleComparator` so the local flow rules will be checked first.

---

单机规则和集群规则同时配置时，单机规则会先进行 check。
