### ISSUE TITLE
Support setting flush interval of the metric log via SentinelConfig property

### ISSUE THREAD

**Issue by yaoyuandota** [alibaba/Sentinel#1867]
您好，我们公司使用sentinel做限流监控，不过metric功能和dashborad有自己的体系，发现metric功能会占用大量内存
180个资源，MetricNode就占用了200M， 虽然这个MetricNode可以gc掉，但是对与我们来说是浪费了。
请问下是不是 重新写下 FlowRuleManager 删除sentinel-metrics-record-task这个定时任务是最方便关闭metric功能的方式

**Comment by sczyh30** [comment]
We may add an attribute `csp.sentinel.metric.flush.interval` to control the flush interval of the metric log. When the interval = 0, the metric log task will not be started (thus disabled). Discussions and contributions are welcomed!

**Comment by brothelul** [comment]
I will try to add the attribute to support the custom interval of metric. need we also support the custom time unit ?
![image](https://user-images.githubusercontent.com/25661357/102683841-c1015f00-420e-11eb-8b34-8926bdb06968.png)
@sczyh30

**Comment by sczyh30** [comment]
Resolved via #1919 (released in 1.8.1)

**Comment by brucelwl** [comment]
> We may add an attribute `csp.sentinel.metric.flush.interval` to control the flush interval of the metric log. When the interval = 0, the metric log task will not be started (thus disabled). Discussions and contributions are welcomed!

加上这个属性之后是不是意味着统计数据会丢失?
