### ISSUE TITLE
tomcat下的两个应用怎么显示在一块了？

### ISSUE THREAD

**Issue by wghdir** [alibaba/Sentinel#1869]
开发的时候idea上跑两个应用，可以按应用名分开，
![image](https://user-images.githubusercontent.com/19346934/99752234-e707e680-2b1e-11eb-8f57-090a2e8cce49.png)
但是发布成war后部署到tomcat上就显示一个应用名了，数量是2.还要怎么设置？
![image](https://user-images.githubusercontent.com/19346934/99751847-0baf8e80-2b1e-11eb-941d-6083cde69c32.png)

**Comment by sczyh30** [comment]
看看部署时的 project.name 启动参数，确保两个应用启动参数 appName 对应各自应用名。
