### ISSUE TITLE
注解方式埋点 基于异常比率的降级场景下无法熔断的问题

### ISSUE THREAD

**Issue by yulinfu-design** [alibaba/Sentinel#1873]
版本是1.8

![image](https://user-images.githubusercontent.com/74909486/99960002-fdd06680-2dc6-11eb-893d-5fce874eafdf.png)
sentinel的基于异常率进行熔断的场景下，需要获取entry.getError()来进行数据统计。
但是在sentinel的切面中出现异常是并没有将这个信息传入进来，从而导致无法获取异常数，进而导致无法进行熔断，代码如下图
![image](https://user-images.githubusercontent.com/74909486/99960433-af6f9780-2dc7-11eb-84a7-314a7cbad0b7.png)

解决方案，在catch中将异常传入到entry中去
![image](https://user-images.githubusercontent.com/74909486/99960542-e180f980-2dc7-11eb-9866-7cc59f1963b3.png)

**Comment by sczyh30** [comment]
`traceException` will record the exceptions. Refer:

https://github.com/alibaba/Sentinel/blob/7920243deca3d86451061a652b77608134c429a0/sentinel-extension/sentinel-annotation-aspectj/src/main/java/com/alibaba/csp/sentinel/annotation/aspectj/AbstractSentinelAspectSupport.java#L44-L53
