### ISSUE TITLE
sentinel整合apollo,关于app.id

### ISSUE THREAD

**Issue by zjun123123** [alibaba/Sentinel#1876]
sentinel整合apollo,做持久化规则时:
如果有多个应用做限流，那么每个应用的APP.ID都需要和sentinel.dash-board里面的APP.ID设置成一致，才能持久化吧？
那么这样有个问题，我的应用在apollo里面定义的其它业务参数，是不是也要和sentinel.dash-board里面的APP.ID一致？
这样会导致所有应用的业务参数配置，都放在同一个APP.ID下？

**Comment by shenbaoyong** [comment]
每个业务应用以及sentinel-dash-board都有各自的appId，自己用自己的，业务参数配置保存在自己的私有空间下(比方说application)，在sentinel-dash-board的appId下新建一个公共空间，公共空间下保存所有业务应用的限流规则等，每个业务app除了能访问到自己私有空间的配置以外也可以访问别的app的公共空间配置    [Apollo-Namespace](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)
