### ISSUE TITLE
spring gateway 整合Sentinel 限流。并使用Sentinel控制台。如何设置文件存储？

### ISSUE THREAD

**Issue by 65725738** [alibaba/Sentinel#1878]
spring gateway 整合Sentinel 限流。并使用Sentinel控制台。如何设置文件存储？
类似于Sentinel  使用FilePersistence持久化。  如何持久化spring gateway的设置。
直接使用 普通的限流持久化 不行呀。

**Comment by HuiBear** [comment]
可以用配置中心做为持久化存放地方

**Comment by sczyh30** [comment]
It's more recommended to leverage dynamic config center. You may leverage data-source integrations of Spring Cloud Alibaba Sentinel (gw-flow type).
