### ISSUE TITLE
chrome out of memory

### ISSUE THREAD

**Issue by zhangkai253** [alibaba/Sentinel#1879]
你好，使用sentinel1.8.0版本，时间稍微长一些后会导致浏览器页面崩溃（out of memory）。跟踪了下问题，应该是g2导致的。所以想问下，sentinelV1.8.0版本使用的是什么版本的g2？

**Comment by sczyh30** [comment]
Maybe 3.4.10. Refer #527

**Comment by sczyh30** [comment]
Hi, any feedback?

**Comment by zhangkai253** [comment]
the bug still exists, you can reoccur the bug just stay the realtime monitor page a longer time.

**Comment by sczyh30** [comment]
Would you like to submit a PR to fix it?

**Comment by zhangkai253** [comment]
Sure， I'll submit the PR

**Comment by zhangkai253** [comment]
I have submitted the PR, https://github.com/alibaba/Sentinel/pull/1905
