### ISSUE TITLE
springcloud gateway整合sentinel，簇点链路只显示sentinel_gateway_context

### ISSUE THREAD

**Issue by chensp0668** [alibaba/Sentinel#1882]
[

## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
springcloud gateway整合sentinel，簇点链路只显示sentinel_gateway_context，是否可以现在具体API
![image](https://user-images.githubusercontent.com/3975296/100975043-572f5700-3578-11eb-8cf6-c94444bd8598.png)

compile('com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2.2.3.RELEASE')
compile('com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway:2.2.3.RELEASE')
springboot版本2.3.3.RELEASE
springcloud版本Hoxton.SR8

### Describe what you expected to happen
sentinel_gateway_context显示是的微服务的context，是否可以显示详细微服务请求的API？

### How to reproduce it (as minimally and precisely as possible)

1. 请求微服务网关地址：http://127.0.0.1:8762/workflow-services/test,簇点链路只显示sentinel_gateway_context为workflow-services,不显示test更加细粒度api。

2. 
3.

**Comment by sczyh30** [comment]
网关限流统计仅针对 route 维度或控制台配置的自定义 API 分组维度，不细化到具体 URL。可以参考下网关限流文档。

**Comment by chensp0668** [comment]
> 网关限流统计仅针对 route 维度或控制台配置的自定义 API 分组维度，不细化到具体 URL。可以参考下网关限流文档。

谢谢大佬回复
