### ISSUE TITLE
GatewaySentinel PullMode持久化

### ISSUE THREAD

**Issue by Master-Jack** [alibaba/Sentinel#1883]
这是Flow持久化之后的JSON文件内容
[{"burst":0,"controlBehavior":0,"count":1.0,"grade":1,"intervalSec":1,"maxQueueingTimeoutMs":500,"paramItem":{"index":0,"matchStrategy":0,"parseStrategy":0},"resource":"xxx-order-server","resourceMode":1}]
对应的控制台
![image](https://user-images.githubusercontent.com/50773190/100977998-bdb67400-357c-11eb-8970-418d5c108c4b.png)

这是API持久化之后的JSON文件内容
[{"apiName":"jack-order-server","predicateItems":[{"matchStrategy":1,"pattern":"/order/orderPay/findById"},{"matchStrategy":1,"pattern":"/order/orderPay/findAll"}]}]
![image](https://user-images.githubusercontent.com/50773190/100978131-ec344f00-357c-11eb-8d9f-4d5ebc504f8e.png)

1. 使用针对请求属性的限流不起作用
2. Api持久化之后控制台看不到匹配模式和匹配串

**Comment by Master-Jack** [comment]
![Snipaste_2020-12-03_15-36-43](https://user-images.githubusercontent.com/50773190/100978460-62d14c80-357d-11eb-9fff-fdf6c0d072f1.png)

**Comment by Master-Jack** [comment]
sentinel 2.2.0  控制台1.7.0

**Comment by Master-Jack** [comment]
![image](https://user-images.githubusercontent.com/50773190/100994572-b057b480-3591-11eb-9298-61bb2b27d3b8.png)

控制台编辑API 分组管理之后重复发送请求改变GatewayApiMatcherManager API_MATCHER_MAP，第一次为正常，第二次为空覆盖规则，致使限流失效

**Comment by Master-Jack** [comment]
Set<ApiDefinition> apiDefinitions = JSON.parseObject(source, new TypeReference<Set<ApiDefinition>>() {
            });
怎么把 ApiDefinition的ApiPredicateItem指定为子类ApiPathPredicateItem？

**Comment by sczyh30** [comment]
> Set apiDefinitions = JSON.parseObject(source, new TypeReference<Set>() {
> });
> 怎么把 ApiDefinition的ApiPredicateItem指定为子类ApiPathPredicateItem？

Refer:

https://github.com/alibaba/Sentinel/blob/6f7d4d09e2082381c7e11d02d82fecce5e9984a0/sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayApiDefinitionGroupCommandHandler.java#L80-L96
