### ISSUE TITLE
sentinel1.7.1版本熔断降级RT支持statIntervalMs和slowRatioThreshold

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/Sentinel#1885]
根据官方Wiki：sentinel熔断降级规则中statIntervalMs和slowRatioThreshold是1.8版本引入的；但是在sentinel1.7客户端新建熔断降级规则并且选择RT模式时，显示了比例阈值（应该不显示的），而且新建规则失败：
![aaa](https://user-images.githubusercontent.com/33769220/101454184-81638900-396b-11eb-9260-116c74b8eda7.png)
![bbb](https://user-images.githubusercontent.com/33769220/101454243-99d3a380-396b-11eb-8dda-5751508be816.png)

**Comment by sczyh30** [comment]
1.7.x 版本的控制台没有这些配置项。另外使用熔断降级特性强烈建议升级至最新 1.8.x 版本。

**Comment by HelloHaiNG** [comment]
> 1.7.x 版本的控制台没有这些配置项。另外使用熔断降级特性强烈建议升级至最新 1.8.x 版本。

好的，明白了
