### ISSUE TITLE
为什么cluster/server/modifyFlowRules 这个http请求代码中无任何地方调用?导致全部的限流都走单机限流

### ISSUE THREAD

**Issue by zwyqz** [alibaba/Sentinel#1891]
![image](https://user-images.githubusercontent.com/4454612/101613439-b98bca00-3a46-11eb-973c-0ced4043b8c6.png)

**Comment by sczyh30** [comment]
控制台集群流控相关功能需自行改造控制台对接动态数据源并通过 `/v2/flow` 进行应用规则推送管理，参考下相关文档。

**Comment by zwyqz** [comment]
有没有例子?
