### ISSUE TITLE
NPE when update ParamFlowRule before the resource has been requested once

### ISSUE THREAD

**Issue by MrCoderYu** [alibaba/Sentinel#1895]
Type: *bug report*

### Describe what happened (or what feature you want)
when update ParamFlowRule with ParamFlowRuleManager.loadRules()
if one of the resource has not bean requested before(there is no metric found),then NPE occurs
the code is here:[ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule);]

### Describe what you expected to happen
judge if the metric is null or not...

### How to reproduce it (as minimally and precisely as possible)

1. init a api resource with ParamRuleManager
2. update that before that has been requested

### Tell us your environment
1.8.0

**Comment by brothelul** [comment]
we just need to judge if the resource has metric before we clear it to avoid the NPE when we update the param flow rule. below is place which the NPE  happened。
![image](https://user-images.githubusercontent.com/25661357/102203247-4df0a380-3f03-11eb-82ad-032db55b1714.png)

@i want to resolve it@
@MrCoderYu

**Comment by sczyh30** [comment]
Contributions are welcomed!
