### ISSUE TITLE
Report a security vulnerability in sentinel

### ISSUE THREAD

**Issue by threedr3am** [alibaba/Sentinel#1898]
Hello, I’m threedram. I found a security vulnerability in the sentinel-dashboard of the alibaba open source current-limiting fuse component sentinel. The details of the related vulnerabilities have been sent to sczyh16@gmail.com

你好，我是threedram，我发现了alibaba开源限流熔断组件sentinel的sentinel-dashboard存在安全漏洞，相关漏洞详情已发送至sczyh16@gmail.com

best regards,
threedr3am

**Comment by sczyh30** [comment]
We'll make progress on fixing it. Thanks for reporting!
