### ISSUE TITLE
How to change the display language of the dashboard to English?

### ISSUE THREAD

**Issue by xiaoyi-app** [alibaba/Sentinel#1899]
控制台怎么显示成英文的
其他国家的同事要使用

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/wiki/Dashboard:

> You can download the latest Sentinel Dashboard jar from the release page. For the English version, you could refer to https://github.com/alibaba/Sentinel/releases/tag/1.3.0.
