### ISSUE TITLE
控制台新增流控规则，流控应用 模块不够清晰，可否做成下拉列表

### ISSUE THREAD

**Issue by tigerMoon** [alibaba/Sentinel#190]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)
流控应用，对应的是limitApp, 这个地方应该填入的信息不是很明确，（defalut/other/还是其他origin）

### Describe what you expected to happen
做成下拉列表 或者更清晰的方式

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

![40d82a06-cee2-4171-9cf9-ca2794f8a8a2](https://user-images.githubusercontent.com/9305625/47196702-6c46cd00-d394-11e8-9ffa-fea57330bac6.png)

**Comment by sczyh30** [comment]
Hi, there is already a placeholder in the text-input and a hover-hint in the label. For listing the origins, this need extra information about origins from applications, so it should be well-considered.
