### ISSUE TITLE
在网上搜了半天没有交流群。我建了个QQ群，大家一起交流下吧

### ISSUE THREAD

**Issue by 799983050** [alibaba/Sentinel#1912]
点击链接加入群聊【 alibaba/Sentinel交流群】：https://jq.qq.com/?_wv=1027&k=O7p1CTyH

群号码：672976099

![图片](https://user-images.githubusercontent.com/45658355/102464151-f8450400-4086-11eb-9730-5531b4ff706d.png)

**Comment by JiangZian** [comment]
你在首页拉到最下面 可以看到
31076969

**Comment by 799983050** [comment]
@JiangZian 你发的这个不是啊？
![Uploading 图片.png…]()

**Comment by sczyh30** [comment]
Sentinel 官方群均为钉钉群：
Sentinel 开源3群：31076969

**Comment by sczyh30** [comment]
Here is for issue tracking. Please open a discussion in https://github.com/alibaba/Sentinel/discussions if needed.

**Comment by ilovedumplings** [comment]
> 

没有啊??搜不到啊
