### ISSUE TITLE
sentinel-dashboard规则持久化到zk得问题

### ISSUE THREAD

**Issue by 799983050** [alibaba/Sentinel#1913]
sentinel-dashboard和客户端（java_web项目，dubbo2.6.0版本） 已把对应得zk持久化改造完成。
这是我客户端得代码
![图片](https://user-images.githubusercontent.com/45658355/102468964-24fc1a00-408d-11eb-992a-7a3d7c904777.png)

请问：客户端除了引入以下俩jar，还需要引入sentinel-transport-simple-http依赖吗？
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-dubbo-adapter</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-zookeeper</artifactId>
            <version>1.8.0</version>
        </dependency>

现在问题是：
1：如果不引入sentinel-transport-simple-http依赖，sentinel-dashboard发现不了我的机器和dubbo服务调用接口。
2：如果引入了，sentinel-dashboard就会显示我的机器和dubbo服务调用接口，然后创建得规则也会到对应得zk节点下，但是我感觉走的还是内存得模式。因为我客户端重启后，虽然sentinel-dashboard会显示我设置得规则，但是不生效，需要手动打开编辑保存一下，规则才会生效。请问是什么原因啊

**Comment by 799983050** [comment]
dubbo+zk得规则持久化好像不好使了。现在是使用得Push 模式+原始模式，结合使用得[大哭]。虽然能做到持久化了，但是项目重启后，得的触发往内存推送下规则

**Comment by cdfive** [comment]
sentinel-transport-simple-http依赖需要引入，用于dashboard和客户端交互，包括机器发现、流量监控等。
因为首先需要机器发现，然后才能对该机器节点设置限流规则。

> 虽然sentinel-dashboard会显示我设置得规则，但是不生效，需要手动打开编辑保存一下，规则才会生效

现在dashboard创建的规则已创建到对应的zk节点下，那么需要看客户端是否引入了`sentinel-datasource-zookeeper`，
并且正确初始化了`ZookeeperDataSource`。

**Comment by sczyh30** [comment]
Any further feedback?
