### ISSUE TITLE
Incorrect comment in FlowRuleComparator

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1914]
## Issue Description

Type: *document report*

### Describe what happened (or what feature you want)

Incorrect comment in FlowRuleComparator:

https://github.com/alibaba/Sentinel/blob/82826fa8865197998080625747a9333943915ee8/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleComparator.java#L30-L39

Actually, the local flow rules are prioritized (which will be checked first).

**Comment by brothelul** [comment]
I will try to fix it.
