### ISSUE TITLE
[Sentinel 与 Hystrix 的对比] 关于熔断降级的疑问

### ISSUE THREAD

**Issue by tigerMoon** [alibaba/Sentinel#192]
## Issue Description

Type: *question* 

### Describe what happened (or what feature you want)
[Sentinel 与 Hystrix 的对比](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E4%B8%8E-Hystrix-%E7%9A%84%E5%AF%B9%E6%AF%94) 的wiki中提到

> Hystrix 的信号量隔离限制对某个资源调用的并发数。这样的隔离非常轻量级，仅限制对某个资源调用的并发数，而不是显式地去创建线程池，所以 overhead 比较小，但是效果不错。但缺点是无法对慢调用自动进行降级，只能等待客户端自己超时，因此仍然可能会出现级联阻塞的情况。Sentinel 可以通过并发线程数模式的流量控制来提供信号量隔离的功能。并且结合基于响应时间的熔断降级模式，可以在不稳定资源的平均响应时间比较高的时候自动降级，防止过多的慢调用占满并发数，影响整个系统。

Hystrix 在1.4.5 版本之后对信号量机制也增加了超时检测功能，所以超时数量多了之后也会自动发生熔断，个人觉得类似Sentinel提供的熔断功能。

### Describe what you expected to happen
这个部分文档描述是否应该加上版本信息，更加准确一些

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by grindwheel** [comment]
文档有待考察

**Comment by sczyh30** [comment]
The document has been updated.
