### ISSUE TITLE
Apollo FlowRule Json串不支持在gateway里SentinelConverter转换GatewayFlowRule

### ISSUE THREAD

**Issue by hooverhe** [alibaba/Sentinel#1921]
Apollo FlowRule Json串不支持在gateway里SentinelConverter转换GatewayFlowRule

因为sentinel集成到gateway，gateway启动时从apollo读过来的FlowRule string应该转换成GatewayFlowRule对象，但是默认转成了FlowRule。Dashboard是按GatewayFlowRuleEntity写到apollo。SentinelConverter源码里不支持GatewayFlowRule。Readable
DataSource也不支持。请看二楼的图。此问题怎么解决啊。

**Comment by hooverhe** [comment]
![image](https://user-images.githubusercontent.com/20389331/102712000-d0f56d80-42f8-11eb-8b1e-aa6cde7386d1.png)
我发现GatewayFlowRule和GatewayFlowRuleEntity的属性不一致。这样也会引起这个问题。

**Comment by brothelul** [comment]
Try to use `com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager` not the `com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager` to register you property from Apollo datasource.

**Comment by hooverhe** [comment]
> Try to use `com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager` instead of the `com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager` to register property which the GatewayFlowRule in the Apollo datasource.

这个问题上午搞定了。但我还有几个问题：
1. Gateway对于随便设置的api流控不起作用，对route流控起作用
