### ISSUE TITLE
Feign fallback target exceptions | Feign SentinelInvocationHandler fallback 逻辑问题

### ISSUE THREAD

**Issue by hillxm** [alibaba/Sentinel#1931]
在整合feign的代码中
![image](https://user-images.githubusercontent.com/51768696/102965116-2368a100-4528-11eb-812f-a8957272c8f1.png)
调的接口一有异常就会进去fallback，这和定义不符啊，不是应该SphU.entry抛出了BlockException才进入吗

**Comment by sczyh30** [comment]
The fallback is for all kinds of exceptions.
