### ISSUE TITLE
Wiki中写的适配web框架描述有点问题

### ISSUE THREAD

**Issue by kilowang** [alibaba/Sentinel#1932]
SpringBoot应用才可以像下面那样配置
@Configuration
public class FilterConfig {

    @Bean
    public FilterRegistrationBean sentinelFilterRegistration() {
        FilterRegistrationBean<Filter> registration = new FilterRegistrationBean<>();
        registration.setFilter(new CommonFilter());
        registration.addUrlPatterns("/*");
        registration.setName("sentinelFilter");
        registration.setOrder(1);

        return registration;
    }
}

servlet应用（包括SpringMVC），应该是直接在web.xml中配置。
所以是不是写错了？

**Comment by cdfive** [comment]
是的，`FilterRegistrationBean`类是SpringBoot应用才有的，感谢指出，文档已修正哈
