### ISSUE TITLE
企业用户登记：新课堂

### ISSUE THREAD

**Issue by FridayLove2015** [alibaba/Sentinel#1934]
组织：浙江新课堂教育股份有限公司
地点：中国杭州
联系方式：1768527366@qq.com
场景：前期内部压力测试，性能测试分析；后续内部系统流控，链路监控，报警

**Comment by sczyh30** [comment]
Please submit in https://github.com/alibaba/Sentinel/issues/18

**Comment by FridayLove2015** [comment]
> 请在[＃18中](https://github.com/alibaba/Sentinel/issues/18)提交[](https://github.com/alibaba/Sentinel/issues/18)

哦，sorry。请把该issue删除掉吧
