### ISSUE TITLE
1.8.0控制台降级规则添加失败，API 404

### ISSUE THREAD

**Issue by guoyeweishao6666** [alibaba/Sentinel#1938]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
<img width="956" alt="捕获" src="https://user-images.githubusercontent.com/65550808/103292292-7bbc0900-4a28-11eb-8434-4c63cb3c19cc.PNG">

2. 
3.

**Comment by guoyeweishao6666** [comment]
http://localhost:8080/degrade/new.json?app=service-order&count=1&grade=2&ip=192.168.0.101&limitApp=default&port=8721&resource=com.weishao.order.controller.OrderController:findProductById(java.lang.Integer)&timeWindow=2  添加降级规则时此链接报404  对比1.6.3的源码发现1.8.0版本的url路径为http://localhost:8080/degrade/rule

**Comment by sczyh30** [comment]
一般刷新下浏览器的缓存即可

**Comment by cdfive** [comment]
也可参考 #1810, #1872

**Comment by henuhaigang** [comment]
1.8有遇到这个错误的吗？
![image](https://user-images.githubusercontent.com/6754575/160974620-07ac9ac3-abe3-4114-a3e0-e596a8e76053.png)



![image](https://user-images.githubusercontent.com/6754575/160974709-7d28769e-6531-4b33-a9e4-bcc9df926e4f.png)


![image](https://user-images.githubusercontent.com/6754575/160974790-83bbb992-ab5a-4eda-a4bf-959be3a6ae2d.png)

**Comment by henuhaigang** [comment]
1.8.0 有遇到这个错误的吗
![image](https://user-images.githubusercontent.com/6754575/160974980-38dfcb09-334f-4c4a-96e2-45480cd41ee0.png)
![image](https://user-images.githubusercontent.com/6754575/160975031-ad7bad8a-06e4-48e5-8e19-15164d7a722e.png)
