### ISSUE TITLE
请问为什么目前sentinel 控制台只支持单机部署？如果想要集群部署，应该如何修改？

### ISSUE THREAD

**Issue by shangguansb** [alibaba/Sentinel#1941]
如题，我们想把sentinel控制台集成到我们的网关门户里，网关门户应用是类似于dubbo（非dubbo）的微服务集群，如何才能集成进门户？
感谢作者回答：）

**Comment by cdfive** [comment]
参考 #241, #363, #1567, #1698 有一些相关的讨论。
