### ISSUE TITLE
sentinel限流规则线程数不生效

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/Sentinel#1948]
版本：1.8
限流规则：使用线程数流控模式，线程数设置为1，设置对应的资源名等
跑一个对应的空接口，发现线程数模式不生效
![image](https://user-images.githubusercontent.com/33769220/103736421-2fc22300-502b-11eb-91a9-a52fa6466663.png)

![image](https://user-images.githubusercontent.com/33769220/103736339-03a6a200-502b-11eb-8304-cd43bf9466fe.png)

是因为空接口的话，接口处理时间太短吗？针对这种情况，可以忽略不计吗？
但是同一个接口，如果配置的限流模式是QPS，并设置为1的情况下，同样的空接口是可以被限制住的

**Comment by Astronaut-K** [comment]
Thread模式用来限制线程并发，你可以理解为Semaphore。

**Comment by sczyh30** [comment]
@HelloHaiNG Any further feedback?

**Comment by sczyh30** [comment]
Closing the issue due to no further feedback.
