### ISSUE TITLE
文档说明

### ISSUE THREAD

**Issue by legend9999** [alibaba/Sentinel#195]
平均响应时间 (DEGRADE_GRADE_RT)：当资源的平均响应时间超过阈值（DegradeRule 中的 count，以 ms 为单位）之后，资源进入准降级状态。接下来如果持续进入 5 个请求，它们的 RT 都持续超过这个阈值，那么在接下的时间窗口（DegradeRule 中的 timeWindow，以 s 为单位）之内，对这个方法的调用都会自动地返回。

这段描述中 如果把 “接下来如果持续进入 5 个请求” 改为 “如果连续进入的5个请求” 更容易理解。

**Comment by sczyh30** [comment]
Already updated.
