### ISSUE TITLE
Sentinel 1.8.0 规则持久化至Nacos后，热点规则不生效问题及原因定位

### ISSUE THREAD

**Issue by francisoyc** [alibaba/Sentinel#1955]
本人基于sentinel-dashboard源码修改，将各种规则持久化至Nacos，其中热点规则在Nacos上的配置如下：
`[{"app":"nacos-service-provider","gmtCreate":1610036605973,"gmtModified":1610037560593,"id":1,"ip":"192.168.3.4","port":8720,"rule":{"burstCount":0,"clusterConfig":{"fallbackToLocalWhenFail":true,"sampleCount":10,"thresholdType":0,"windowIntervalMs":1000},"clusterMode":false,"controlBehavior":0,"count":3.0,"durationInSec":1,"grade":1,"limitApp":"default","maxQueueingTimeMs":0,"paramFlowItemList":[],"paramIdx":0,"resource":"/user/info/{id}"}}]`

每次修改热点规则后，比如将阈值（count）由100改为3，这时候规则将失效，达不到限流作用，通过断点调试发现问题出在 NacosDataSource.java 中
`public NacosDataSource(final Properties properties, final String groupId, final String dataId, Converter<String, T> parser) {
        super(parser);
        this.pool = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, new ArrayBlockingQueue(1), new NamedThreadFactory("sentinel-nacos-ds-update"), new DiscardOldestPolicy());
        this.configService = null;
        if (!StringUtil.isBlank(groupId) && !StringUtil.isBlank(dataId)) {
            AssertUtil.notNull(properties, "Nacos properties must not be null, you could put some keys from PropertyKeyConst");
            this.groupId = groupId;
            this.dataId = dataId;
            this.properties = properties;
            this.configListener = new Listener() {
                public Executor getExecutor() {
                    return NacosDataSource.this.pool;
                }

                public void receiveConfigInfo(String configInfo) {
                    RecordLog.info(String.format("[NacosDataSource] New property value received for (properties: %s) (dataId: %s, groupId: %s): %s", properties, dataId, groupId, configInfo), new Object[0]);
                    // 问题出在这里，将Naocs上的配置转化成对应规则（此处为ParamFlowRule）时，转化失败。
                    // 这个方法会调用 com.alibaba.cloud.sentinel.datasource.converter.SentinelConverter#convert(String source)
                    T newValue = NacosDataSource.this.parser.convert(configInfo);
                    NacosDataSource.this.getProperty().updateValue(newValue);
                }
            };
            this.initNacosListener();
            this.loadInitialConfig();
        } else {
            throw new IllegalArgumentException(String.format("Bad argument: groupId=[%s], dataId=[%s]", groupId, dataId));
        }
    }
	
	
	com.alibaba.cloud.sentinel.datasource.converter.SentinelConverter#convert(String source) 问题代码如下：
	@Override
	public Collection<Object> convert(String source) {
		Collection<Object> ruleCollection;

		// hard code
		if (ruleClass == FlowRule.class || ruleClass == DegradeRule.class
				|| ruleClass == SystemRule.class || ruleClass == AuthorityRule.class
				|| ruleClass == ParamFlowRule.class) {
			ruleCollection = new ArrayList<>();
		}
		else {
			ruleCollection = new HashSet<>();
		}

		if (StringUtils.isEmpty(source)) {
			log.warn("converter can not convert rules because source is empty");
			return ruleCollection;
		}
		try {
			List sourceArray = objectMapper.readValue(source,
					new TypeReference<List<HashMap>>() {
					});

			for (Object obj : sourceArray) {
				String item = null;
				try {
                                        // 通过调试，item的值为： {"app":"nacos-service-provider","gmtModified":1610039724496,"port":8720,"ip":"192.168.3.4","rule":{"burstCount":0,"clusterConfig":{"fallbackToLocalWhenFail":true,"sampleCount":10,"thresholdType":0,"windowIntervalMs":1000},"clusterMode":false,"controlBehavior":0,"count":3.0,"durationInSec":1,"grade":1,"limitApp":"default","maxQueueingTimeMs":0,"paramFlowItemList":[],"paramIdx":0,"resource":"/user/info/{id}"},"id":1,"gmtCreate":1610036605973} 
					item = objectMapper.writeValueAsString(obj);
                                        // 这里调用 convertRule(item) 转化成 ParamFlowRule 时，转化出来的对象全部为默认值，
                                        // 正确做法应该是取 item 中的 rule 再转化为 ParamFlowRule
					Optional.ofNullable(convertRule(item))
							.ifPresent(convertRule -> ruleCollection.add(convertRule));
				}
				catch (IOException e) {
					log.error("sentinel rule convert error: " + e.getMessage(), e);
					throw new IllegalArgumentException(
							"sentinel rule convert error: " + e.getMessage(), e);
				}
			}
		}
		catch (Exception e) {
			if (e instanceof RuntimeException) {
				throw (RuntimeException) e;
			}
			else {
				throw new RuntimeException("convert error: " + e.getMessage(), e);
			}
		}
		return ruleCollection;
	}`

**Comment by brothelul** [comment]
I will try to check this issue, and fix it.

**Comment by brothelul** [comment]
@francisoyc  you should persist the `com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowRule` not the `com.alibaba.csp.sentinel.dashboard.datasource.entity.rule.ParamFlowRuleEntity` in Nacos. change your dashboard persist codes maybe can sovle the problem you meet.

**Comment by francisoyc** [comment]
Ok，thanks！I will try it

发自我的iPhone
