### ISSUE TITLE
[疑问]热点参数限流规则里参数类型(ParamFlowItem.object)限定为基本类型而不是Object的原因？

### ISSUE THREAD

**Issue by Astronaut-K** [alibaba/Sentinel#1958]
version：1.8.0

  尝试将com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowItem#object类型修改为Object，之后创建参数对象（覆盖equals和hashcode方法）并进行简单测试，参数限流功能是正常的。目前限定参数为基本类型的原因是避免其长期驻留在规则对象中占用额外内存吗？

**Comment by h4yin** [comment]
配置管理不好支持吧，对象下每个字段都得指定classType, value，再嵌套几层，用户也没法用吧
