### ISSUE TITLE
Sentinel支持泛化调用时降级吗？

### ISSUE THREAD

**Issue by galohuang** [alibaba/Sentinel#196]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
泛化调用只有一个Invoke入口，参数不同对应的下游服务不同，请问Sentinel是否支持参数级别的降级？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, for your scenario you can use the parameter as the resource (e.g. `SphU.entry(serviceName)`), then configure degrade rules for specific services.

**Comment by galohuang** [comment]
ok，thanks！
