### ISSUE TITLE
MetricExtension.increaseThreadNum/decreaseThreadNum如何统计当前线程数？

### ISSUE THREAD

**Issue by MrCoderYu** [alibaba/Sentinel#1962]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)
使用MetricExtension做扩展统计数据的时候，发现increaseThreadNum/decreaseThreadNum这两个方法如果想实现对线程数的统计是需要自己内部做个计数器针对每个resource做计数吗？方法入参是不是可以加上DefaultNode node？这样在方法内部就可以获取curThreadNum?

### Describe what you expected to happen
方法入参是不是可以加上DefaultNode node？这样在方法内部就可以获取curThreadNum?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1.8.0

**Comment by sczyh30** [comment]
`MetricExtension` is intended to be an event consumer of Sentinel statistics (e.g. onPass, onBlocked). You may consume the event and add the concurrency by yourself.
