### ISSUE TITLE
希望gateway adapter能支持设置降级熔断规则

### ISSUE THREAD

**Issue by Lawrence-Albet** [alibaba/Sentinel#1963]
## Issue Description

 *feature request*

### Describe what happened (or what feature you want)

gateway集成sentinel时GatewayRuleManager没有办法添加降级熔断规则

### Describe what you expected to happen

希望能加上这些规则的设置途径

**Comment by sczyh30** [comment]
You may add normal `DegradeRule` for API gateway (via data-source or `DegradeRuleManager`).
