### ISSUE TITLE
springcloud gateway 与sentinel，nacos整合后推送配置不生效

### ISSUE THREAD

**Issue by DanielGitHub123** [alibaba/Sentinel#1964]
使用springcloudgateway与sentinel，nacos整合，当资源未被访问时，从nacos控制台推送配置，gateway接后到配置后会报错，报错信息为空指针异常，报错位置如下图所示：
![image](https://user-images.githubusercontent.com/21676818/104692657-4c550e00-5743-11eb-9298-6ac50fce7b57.png)

红框所示位置为空
当所访问的资源被访问后，再推送配置，就正常了

在GatewayRuleManager中，如下方法：
private void applyToConvertedParamMap(Set<ParamFlowRule> paramFlowRules) {
            Map<String, List<ParamFlowRule>> newRuleMap = ParamFlowRuleUtil.buildParamRuleMap(
                new ArrayList<>(paramFlowRules));
            if (newRuleMap == null || newRuleMap.isEmpty()) {
                // No parameter flow rules, so clear all the metrics.
                for (String resource : CONVERTED_PARAM_RULE_MAP.keySet()) {
                    ParameterMetricStorage.clearParamMetricForResource(resource);
                }
                RecordLog.info("[GatewayRuleManager] No gateway rules, clearing parameter metrics of previous rules");
                CONVERTED_PARAM_RULE_MAP.clear();
                return;
            }

            // Clear unused parameter metrics.
            for (Map.Entry<String, List<ParamFlowRule>> entry : CONVERTED_PARAM_RULE_MAP.entrySet()) {
                String resource = entry.getKey();
                if (!newRuleMap.containsKey(resource)) {
                    ParameterMetricStorage.clearParamMetricForResource(resource);
                    continue;
                }
                List<ParamFlowRule> newRuleList = newRuleMap.get(resource);
                List<ParamFlowRule> oldRuleList = new ArrayList<>(entry.getValue());
                oldRuleList.removeAll(newRuleList);
                for (ParamFlowRule rule : oldRuleList) {
                    ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule);
                }
            }

            // Apply to converted rule map.
            CONVERTED_PARAM_RULE_MAP.clear();
            CONVERTED_PARAM_RULE_MAP.putAll(newRuleMap);

            RecordLog.info("[GatewayRuleManager] Converted internal param rules: " + CONVERTED_PARAM_RULE_MAP);
        }
    }
在for循环中，ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule)这句ParameterMetricStorage.getParamMetricForResource(resource)为空

**Comment by sczyh30** [comment]
Refer #1724. This will be fixed in 1.8.1.

**Comment by zhangxiangfeng** [comment]
> Refer #1724. This will be fixed in 1.8.1.

大约时间时候发布1.8.1 ?
