### ISSUE TITLE
建议LoginAuthenticationFilter 属性authFilterExcludeUrls配置支持uri: /xx/**

### ISSUE THREAD

**Issue by xiaoxb** [alibaba/Sentinel#1967]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
url只能精准匹配
if(authFilterExcludeUrls.contains(servletPath)) {
	chain.doFilter(request, response);
	return;
}
### Describe what you expected to happen

1. 

// Exclude the urls which needn't auth 
for (String authFilterExcludeUrl : authFilterExcludeUrls) {
	if (isMatch(authFilterExcludeUrl, servletPath)) {
		chain.doFilter(request, response);
		return;
	}
}

// 判断url是否与规则配置: ? 表示单个字符; * 表示一层路径内的任意字符串，不可跨层级; ** 表示任意层路径;
public Boolean isMatch(String pattern, String url) {
    AntPathMatcher matcher = new AntPathMatcher();
    return matcher.match(pattern, url);
}

2.
private static final AntPathMatcher PATH_MATCHER = new AntPathMatcher();

if (authFilterExcludeUrls.stream().anyMatch(s -> PATH_MATCHER.match(s, servletPath))) {
	chain.doFilter(request, response);
	return;
}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
master

**Comment by sczyh30** [comment]
Would you like to contribute a PR to fix it?

**Comment by brothelul** [comment]
I want to solve it If there's no one.

**Comment by xiaoxb** [comment]
Of course
















At 2021-01-18 09:54:22, "brothelul" <notifications@github.com> wrote:

I want to solve it If there's no one.

**Comment by sczyh30** [comment]
Resolved in #1971
