### ISSUE TITLE
Spring Cloud Alibaba Sentinel 1.7.1 读取 nacos1.2.1 配置 权限问题 : 403 

### ISSUE THREAD

**Issue by zhangluyang1995** [alibaba/Sentinel#1972]
异常描述 :

服务启动后狂刷错误信息 : [check-update] get changed dataId error, code: 403

nacos错误信息:

[19/Jan/2021:09:55:23 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.1" 403 299 2 Java/1.8.0_202
127.0.0.1 - - [19/Jan/2021:09:55:23 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.1" 403 299 2
不清楚是如何使用sentinel配置进行与nacos认证的.

sentinel 配置 :
sentinel:
transport:
dashboard: sentinel-client
eager: true
datasource:
ds:
nacos:
serverAddr: nacos-server
namespace: dev
# access-key: 不知道生成规则,故未配置
# usesrname: datasource-nacos 未存在对应属性
# password: datasource-nacos 未存在对应属性
groupId: DEFAULT_GROUP
dataId: sentinel.json
data-type: json
rule-type: gw-flow

若想使用此功能该如何配置sentinel 达到 nacos权限认证通过呢?

**Comment by sczyh30** [comment]
You may upgrade Spring Cloud Alibaba Sentinel to the latest version.

**Comment by zhangluyang1995** [comment]
> 您可以将Spring Cloud Alibaba Sentinel升级到最新版本。

我试试

**Comment by sczyh30** [comment]
Duplicate with #1517

**Comment by chenjianfei1989** [comment]
sentinel 做续约了吗？超过nacos配置 nacos.core.auth.default.token.expire.seconds的时间 一直报错

**Comment by Pengfei-Lu** [comment]
@sczyh30 

> sentinel 做续约了吗？超过nacos配置 nacos.core.auth.default.token.expire.seconds的时间 一直报错
> 
> spring-cloud-alibaba 1.8.0

@sczyh30 会有续约的问题存在吗？
