### ISSUE TITLE
当限流后，http status 会有两种返回，200或者 429

### ISSUE THREAD

**Issue by SeoYu** [alibaba/Sentinel#1977]
当限流后，我发现某些请求会走BlockExceptionHandler的 default，此时返回的是 429。部分请求会走@SentinelResource的blockHandler，此时返回的是 200。  
这个是否是一个 bug

**Comment by cdfive** [comment]
May refer to #1198

**Comment by SeoYu** [comment]
> May refer to #1198

ok，thanks，I will close it
