### ISSUE TITLE
sentinel 网关新增流程流控规则 API分组持久化到nacos，无法拦截.

### ISSUE THREAD

**Issue by wangdejian163** [alibaba/Sentinel#1978]
使用nacos作为数据源，，gw-api-group、gw-flow针对应用维度进行了规则配置；网关服务依赖如下：
`
    <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>
   <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.8.0</version>
        </dependency>
`
Sentinel 控制台中API管理和流控规则也按照官网添加。测试url发现GatewayRuleManager中GATEWAY_RULE_MAP这个map是空的。
`
   public static Set<GatewayFlowRule> getRulesForResource(String resourceName) {
        if (StringUtil.isBlank(resourceName)) {
            return new HashSet();
        } else {
            Set<GatewayFlowRule> set = (Set)GATEWAY_RULE_MAP.get(resourceName);
            return set == null ? new HashSet() : new HashSet(set);
        }
    }
`
去掉yml中的规则配置，手动加载配置发现能够正常拦截。不确定是代码问题，还是sentinel的bug。希望大佬能够指点下。

**Comment by rabbitloveLHF** [comment]
@wangdejian163 你好，我也遇到了一样的问题，你说的手动加载配置是怎么弄的呢

**Comment by wangdejian163** [comment]
搞不了，弄两天了不知道怎么解决掉。硬编码可以拦截。sentinel感觉不怎么维护了。很少人用

**Comment by rabbitloveLHF** [comment]
再研究一下吧，我也是研究的不深

**Comment by wangdejian163** [comment]
> 再研究一下吧，我也是研究的不深

加qq，解决了沟通下。172970621.

**Comment by rabbitloveLHF** [comment]
好

**Comment by shenmintao** [comment]
我可能解决了这个问题，通过在gateway加载sentinel配置的时候手动注册Nacos的datasource，能够获取到规则，拦截也能正常触发

**Comment by rabbitloveLHF** [comment]
@wangdejian163 方便的话能发个代码吗

**Comment by rabbitloveLHF** [comment]
> 我可能解决了这个问题，通过在gateway加载sentinel配置的时候手动注册Nacos的datasource，能够获取到规则，拦截也能正常触发
能详细说一下吗

**Comment by rabbitloveLHF** [comment]
这个问题是由于网关限流配置的rule-type区别于普通限流，必须配成gw-flow和gw-api-group

**Comment by lQIgithub** [comment]
已解决了，修改1.81版本源码，官网提供了两个接口DynamicRuleProvider，DynamicRulePublisher；自己实现一下就解决了
