### ISSUE TITLE
sentinel1.8 使用Nacos做动态存储的时候首次更新GatewayRule会出现nullpointexception

### ISSUE THREAD

**Issue by gjie1991** [alibaba/Sentinel#1981]
GatewayRuleManager.java
230行
ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule);

加载规则时，首次调用当前方法值为null
ParameterMetricStorage.getParamMetricForResource(resource) == null ?

**Comment by gjie1991** [comment]
ParameterMetric parameterMetric = ParameterMetricStorage.getParamMetricForResource(resource);
if (parameterMetric != null) {
    parameterMetric.clearForRule(rule);
}

**Comment by sczyh30** [comment]
Hi, this is a known bug and has been fixed in #1901 (which will be released with 1.8.1).
