### ISSUE TITLE
ErrorEntryFreeException: The order of entry exit can't be paired with the order of entry, current entry in context

### ISSUE THREAD

**Issue by longzhiwuing** [alibaba/Sentinel#1983]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

In the SpringBoot(2.1.7) context, when I use dubbo(2.7.8) rpc(injvm) request in controller.There is an exception happend. it says that "com.alibaba.csp.sentinel.ErrorEntryFreeException: The order of entry exit can't be paired with the order of entry, current entry in context: <com.xxx.IManageService:executeSql(java.lang.String,java.lang.String)>, but expected: <POST:/v1/manage/executeSql>"

### Describe what you expected to happen
when I call the Dubbo method which in the same module project (i.e. injvm) in controller.  it should be work well

### How to reproduce it (as minimally and precisely as possible)

1. In springboot context
2. autowire a dubbo proxy instance in a controller.java
3. In the requestmapping method invoke a dubbo method(injvm) 

![image](https://user-images.githubusercontent.com/5849090/105802970-54307000-5fd7-11eb-9dfc-5948bf3fb841.png)

### Tell us your environment
springboot：2.1.7
sentinel：1.7.2
dubbo：2.7.8

### Anything else we need to know?

In the same controller when i call the real rpc dubbo method(not in the same jvm) it works well

**Comment by sczyh30** [comment]
Could you please upgrade Sentinel to 1.8.0 and test whether it still exists in the latest version?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by cdfive** [comment]
Do you use `sentinel-spring-webmvc-adaptor`? Also refer to #1482, #1531, #1533
When upgrading you can refer to the release note of 1.8.0 [https://github.com/alibaba/Sentinel/releases/tag/v1.8.0](https://github.com/alibaba/Sentinel/releases/tag/v1.8.0)
Hope can provide more feedback.

**Comment by sczyh30** [comment]
Hi, any further feedback?
