### ISSUE TITLE
Whether  sentinel support ibm jdk?

### ISSUE THREAD

**Issue by 3838438abcd** [alibaba/Sentinel#1985]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

It occured the error that failed to get system metrics from JMX when I started the application whith ibm jdk.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please provide the detail of your environment?

**Comment by 3838438abcd** [comment]
> environment
Alibaba Dubbo 2.5.9,Spring boot 1.5.x,ibm jdk 3.12

The detail info is "“java.lang.illegalArgumentException: com.sun.management.OperatingSystemMXBean is not a valid MXBean interface”"

**Comment by sczyh30** [comment]
If so, maybe the IBM JDK is not supported yet.
