### ISSUE TITLE
DefaultBlockExceptionHandler中判断是否是GET方法的意义是？

### ISSUE THREAD

**Issue by zhouyongshen** [alibaba/Sentinel#1988]
https://github.com/alibaba/Sentinel/blob/4459ab2caf2029be2d48ed0bd8110757059a9a84/sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/callback/DefaultBlockExceptionHandler.java#L39

![image](https://user-images.githubusercontent.com/26317312/105955453-45b68700-60b1-11eb-85ea-6c832ae298ab.png)
请问DefaultBlockExceptionHandler中判断GET方法及获取请求参数的意义是什么呢？

**Comment by cdfive** [comment]
Maybe the author want to log or print the url and its queryString parameters. But at present, it's only a local variable, not really used, so is this `if` judgment. Would you like to contribute a PR to improve this?
