### ISSUE TITLE
How to use the latest version of Sentinel-Core 1.8.0 by spring-cloud-starter-alibaba-sentinel

### ISSUE THREAD

**Issue by pengtenghui** [alibaba/Sentinel#1989]
The sentinel-core version introduced via spring-cloud-starter-alibaba-sentinel is 1.7.1
How to use the latest version of Sentinel-Core 1.8.0 by spring-cloud-starter-alibaba-sentinel
![image](https://user-images.githubusercontent.com/28785423/106110857-39e8c480-6186-11eb-9055-5e11b8a633c5.png)

**Comment by sczyh30** [comment]
You may try the latest version of Spring Cloud Alibaba (maybe defined in spring-cloud-alibaba-dependencies).

**Comment by pengtenghui** [comment]
Thank you for sczyh30 !
I solved the problem in your way

> You may try the latest version of Spring Cloud Alibaba (maybe defined in spring-cloud-alibaba-dependencies).

Thank you !
I solved the problem in your way.

**Comment by sczyh30** [comment]
Cheers! I'll close the issue.
