### ISSUE TITLE
DegradeRule类型相同 为什么会创建新的熔断器

### ISSUE THREAD

**Issue by christophe-liwei** [alibaba/Sentinel#1990]
```
 private static CircuitBreaker getExistingSameCbOrNew(/*@Valid*/ DegradeRule rule) {
        List<CircuitBreaker> cbs = getCircuitBreakers(rule.getResource());
        if (cbs == null || cbs.isEmpty()) {
            return newCircuitBreakerFrom(rule);
        }
        for (CircuitBreaker cb : cbs) {
            if (rule.equals(cb.getRule())) {
                // Reuse the circuit breaker if the rule remains unchanged.
                return cb;
            }
        }
        return newCircuitBreakerFrom(rule);
    }
```

我认为`DegradeRule.grade`相同的情况应该是修改CircuitBreaker实例，而不是创建一个新的。这样导致同一一规则类型的熔断器创建了多个，这是不合理的。

**Comment by christophe-liwei** [comment]
@sczyh30

**Comment by cdfive** [comment]
```java
for (CircuitBreaker cb : cbs) {
    if (rule.equals(cb.getRule())) {
        // Reuse the circuit breaker if the rule remains unchanged.
        return cb;
    }
}
```
这里遍历通过`equals`判断，当熔断降级规则相同时会复用啊，没有创建新的。
`DegradeRule`类重写了`equals`方法：
```java
@Override
public boolean equals(Object o) {
    if (this == o) { return true; }
    if (o == null || getClass() != o.getClass()) { return false; }
    if (!super.equals(o)) { return false; }
    DegradeRule rule = (DegradeRule)o;
    return Double.compare(rule.count, count) == 0 &&
        timeWindow == rule.timeWindow &&
        grade == rule.grade &&
        minRequestAmount == rule.minRequestAmount &&
        Double.compare(rule.slowRatioThreshold, slowRatioThreshold) == 0 &&
        statIntervalMs == rule.statIntervalMs;
}
```
里面有`grade`相同的情况。

**Comment by christophe-liwei** [comment]
我说的场景是对同一种类型的熔断器进行修改，例如我先创建了一个基于异常数量的熔断器，exception=10，然后我修改exception=15。我想要修改触发熔遁的异常数量。但是这个时候会创建新的熔断器。
@cdfive

**Comment by brothelul** [comment]
equals方法在这里确实没有相等，因为exception的值不同，又不是同一个对象，所以返回为false，会去新建熔断器，因为规则的调整，对于值不同的rule会新建DegradeRule对象。

**Comment by christophe-liwei** [comment]
这是有问题的，调整规则后，旧的熔断器实例不销毁，并且一直生效。我理解同一类型的熔断器只能存在一个实例

**Comment by christophe-liwei** [comment]
@brothelul @cdfive

**Comment by cdfive** [comment]
@brothelul 确实没有相等，@christophe-liwei 说的对。

> 这是有问题的，调整规则后，旧的熔断器实例不销毁，并且一直生效

在`getExistingSameCbOrNew`方法的外层，`buildCircuitBreakers(List<DegradeRule> list)`方法，这里的`List<DegradeRule> list`参数是全量的降级规则，在控制台编辑修改规则后，比如一共3个规则，修改了某1个，进到这里的list里有3个规则。
虽然因为`equals`不同，`getExistingSameCbOrNew`里创建了新的熔断器，但在`buildCircuitBreakers`返回的`Map<String, List<CircuitBreaker>> cbMap`里，对于相同资源名称，它的熔断器是被新的熔断器替换了的，在`buildCircuitBreakers`的外层，
`DegradeRuleManager.circuitBreakers = cbs;`，因此原熔断器不会生效，生效的是新熔断器。

@sczyh30 帮忙看看理解对吗

**Comment by christophe-liwei** [comment]
@cdfive ok, thanks
