### ISSUE TITLE
新手指南 metric 日志输出格式

### ISSUE THREAD

**Issue by allankin** [alibaba/Sentinel#1993]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
按照 [“新手指南” ](https://github.com/alibaba/Sentinel/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97)，运行下面的代码：
```
public class Main {
    public static void main(String[] args) {
        // 配置规则.
        initFlowRules();

        while (true) {
            // 1.5.0 版本开始可以直接利用 try-with-resources 特性，自动 exit entry
            try (Entry entry = SphU.entry("HelloWorld")) {
                // 被保护的逻辑
                System.out.println("hello world");
            } catch (BlockException ex) {
                // 处理被流控的逻辑
                System.out.println("blocked!");
            }
        }
    }
    private static void initFlowRules(){
        List<FlowRule> rules = new ArrayList<>();
        FlowRule rule = new FlowRule();
        rule.setResource("HelloWorld");
        rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
        // Set limit QPS to 20.
        rule.setCount(20);
        rules.add(rule);
        FlowRuleManager.loadRules(rules);
    }
}
``` 
打开日志文件: C:\Users\kim\logs\csp\com-study-Main-metrics.log.2021-01-29 : 
  
```
1611928935000|2021-01-29 22:02:15|HelloWorld|20|1|20|0|1|0|0|0
1611928936000|2021-01-29 22:02:16|HelloWorld|20|7547|20|0|0|0|0|0
1611928937000|2021-01-29 22:02:17|HelloWorld|20|14748|20|0|0|0|0|0
1611928938000|2021-01-29 22:02:18|HelloWorld|20|26622|20|0|0|0|0|0
1611928939000|2021-01-29 22:02:19|HelloWorld|20|31882|20|0|0|0|0|0
1611928940000|2021-01-29 22:02:20|HelloWorld|20|47173|20|0|0|0|0|0
1611928941000|2021-01-29 22:02:21|HelloWorld|20|61301|20|0|0|0|0|0
1611928942000|2021-01-29 22:02:22|HelloWorld|20|71610|20|0|0|0|0|0
1611928943000|2021-01-29 22:02:23|HelloWorld|20|68487|20|0|0|0|0|0

```
发现|分隔的项更多，跟新手指南里面的根本对不上，不知道后面的那些分隔项到底啥意思？？？

### Describe what you expected to happen
但是文档描述的打印输出格式是这样的：
[4.检查效果](https://github.com/alibaba/Sentinel/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97#4-%E6%A3%80%E6%9F%A5%E6%95%88%E6%9E%9C)
```
Demo 运行之后，我们可以在日志 ~/logs/csp/${appName}-metrics.log.xxx 里看到下面的输出:

|--timestamp-|------date time----|--resource-|p |block|s |e|rt
1529998904000|2018-06-26 15:41:44|hello world|20|0    |20|0|0
1529998905000|2018-06-26 15:41:45|hello world|20|5579 |20|0|728
1529998906000|2018-06-26 15:41:46|hello world|20|15698|20|0|0
1529998907000|2018-06-26 15:41:47|hello world|20|19262|20|0|0
1529998908000|2018-06-26 15:41:48|hello world|20|19502|20|0|0
1529998909000|2018-06-26 15:41:49|hello world|20|18386|20|0|0

```

how can I understand ?????

请指教，是我文档没看清楚，还是文档没写清楚，这对我刚开始学习并打算使用sentinel 到公司项目中，却发现文档描述对不不上，这是很大的打击，而且是最基础的入门文档。 烦请多多指点，该怎么解读理解呢？？？？？？？？？？？

### How to reproduce it (as minimally and precisely as possible)
按照 [“新手指南” ](https://github.com/alibaba/Sentinel/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97) 运行入门示例代码。

**Comment by allankin** [comment]
[新手指南 ](https://github.com/alibaba/Sentinel/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97)  的文档跟1.8.0 输出日志结果不一样吗????  是不是文档没有及时更新？？？ 我该怎么去理解日志输出呢？？？？ 正在考虑公司技术选型，十分紧急，请高人指点，万分感激！！！！！！！！！
```
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-core</artifactId>
    <version>1.8.0</version>
</dependency>
```

**Comment by sczyh30** [comment]
参考下 https://github.com/alibaba/Sentinel/wiki/实时监控#资源的秒级日志

---

You may refer to https://sentinelguard.io/en-us/docs/logs.html

**Comment by allankin** [comment]
> 参考下 [https://github.com/alibaba/Sentinel/wiki/实时监控#资源的秒级日志](https://github.com/alibaba/Sentinel/wiki/%E5%AE%9E%E6%97%B6%E7%9B%91%E6%8E%A7#%E8%B5%84%E6%BA%90%E7%9A%84%E7%A7%92%E7%BA%A7%E6%97%A5%E5%BF%97)
> 
> You may refer to https://sentinelguard.io/en-us/docs/logs.html

非常感谢及时回复！！！ 但是不寒而栗的是，为啥官方文档没有更新呢？作为国内的知名开源软件，至少中文文档要及时完备吧！！！  我还是希望借助sentinel 好好的深入学习，希望能够引入到公司的技术体系中，但是这最基本的新人指南文档，我都碰壁了，需要提issue来咨询，这确实有点耗费时间呢？ 前不久了解过开源项目的相关知识内容，开源是个生态，不仅仅是代码，文档更是重要，而文档的及时更新，是开源生态中非常重要的一环.  说多了，请见谅
