### ISSUE TITLE
1.7.2针对fastjson1.2.8老版本兼容性问题

### ISSUE THREAD

**Issue by lhy030320999** [alibaba/Sentinel#1994]
sentinel dashboard1.7.2版本，客户端引用了fastjson1.2.8，导致限流，降级等操作后无反应。dashboard控制台也不提示任何错误信息。

**Comment by sczyh30** [comment]
It's highly not recommended to use old fastjson versions. This has been described in https://github.com/alibaba/Sentinel/wiki/FAQ

Besides, the community is making progress on replacing fastjson with a generic, simple implementation. Refer #1522
