### ISSUE TITLE
使用windows运行sentinel-dashboard，上面显示的时间和本机时间不一致，相差16小时是为什么呢？

### ISSUE THREAD

**Issue by RenYuaaa** [alibaba/Sentinel#2001]
![image](https://user-images.githubusercontent.com/51392341/106478387-0051db00-645e-11eb-9bca-f01c97981dfe.png)
请问出现这种时间不一致的原因是什么呢？我是本地启动的sentinel-dashboard，1.8的版本。

**Comment by sczyh30** [comment]
Please check whether you've set a different timezone when starting your service.

**Comment by sczyh30** [comment]
Any feedback?

**Comment by RenYuaaa** [comment]
> Please check whether you've set a different timezone when starting your service.

抱歉，最近比较忙忘记回复了。我是用的windows版的jar包直接运行的，没有设置时区。然后在使用的时候时间就和我本机相差16个小时。但是我前台晚上用的时候，启动jar包之后，在控制台看到的时间就和我本机是一样的了
