### ISSUE TITLE
Flow control for Netty channelActive | sentinel能否对  netty链接channelActive进行限流？

### ISSUE THREAD

**Issue by pengqingsong123** [alibaba/Sentinel#2005]
我使用netty作为服务器，很多机柜会链接服务器进行长连接，假如大面积断网后，机柜进行重连，sentinel能对 机柜的链接进行限流吗？防止大量机柜同时链接服务器
感谢阿里巴巴大佬

**Comment by sczyh30** [comment]
Sentinel 支持[自定义埋点](https://github.com/alibaba/Sentinel/wiki/如何使用#方式二抛出异常的方式定义资源)，可以在对应的地方埋点后配置流控规则或并发控制规则。
