### ISSUE TITLE
sentinel在与nacos集成使用中,降级规则和限流规则为何本地化保存

### ISSUE THREAD

**Issue by wangpeng1981** [alibaba/Sentinel#2007]
1.sentinel在与nacos集成使用中，流量规则可以使用配置中心，降级规则和限流规则为什么不使用配置中心，而是使用的本地机器保存规则的？现在dashboard中，降级规则和限流规则用的都是本地机器保存规则的。
如果需要兼容配置中心，是否需要贡献代码，我这边已实现。

**Comment by sczyh30** [comment]
Contributions are welcomed.
