### ISSUE TITLE
How to limit by HTTP request header (e.g. X-User-ID) based on existing rate limiting rules of resources?

### ISSUE THREAD

**Issue by reliveyy** [alibaba/Sentinel#2008]
## Issue Description

Type: a question

### Describe what happened (or what feature you want)

It's about how to implement a further rate limiting strategy based on user ID per resources in a "Sentinel" manner.

### Describe what you expected to happen

N/A

### How to reproduce it (as minimally and precisely as possible)

N/A

### Tell us your environment

N/A

### Anything else we need to know?

N/A

**Comment by sczyh30** [comment]
You may leverage https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-parameter-flow-control/README.md (carry header value as the "parameter")

**Comment by sczyh30** [comment]
For further discussion please go to #2014
