### ISSUE TITLE
sentinel-dashboard-1.8.0从【请求链页面】添加降级规则失败，提示【统计时长窗口需要大于0s】

### ISSUE THREAD

**Issue by fangqyou** [alibaba/Sentinel#2011]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

[如题：](url)

![image](https://user-images.githubusercontent.com/49676298/106863036-eedd2d00-6702-11eb-98a9-44be996fbe11.png)

**Comment by sczyh30** [comment]
Duplicate with #1950 and many more... Please use the latest 1.8.1 version.

**Comment by CMeetting** [comment]
如果是自己改造的话，要确保dashbord后台controller中确实接受了该参数并且保存了，有些可能是保存的时候没有把这个值设置到对象中，有些是接受参数不包含统计时长窗口对应的参数
