### ISSUE TITLE
Could you please consider renaming these classes? such as "Sph", "SphU", "SphO","CtSph" and so on.

### ISSUE THREAD

**Issue by ss-superman** [alibaba/Sentinel#2017]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

I am a newcomer who really eagers to learn Sentinel source code and be a contributor one day in the future. But what does "Sph", "SphU", "SphO", "CtSph" mean? Personally, I think the name of these classes can't express their purpose. And I can't find them in the code comment or Wiki. This make me lose a little of power to learn the source code.
Could you please consider optimizing the name of these important entrance classes?
Thanks a lot!
### Describe what you expected to happen
NONE

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

NONE
### Anything else we need to know?

NONE

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/issues/489#issuecomment-465487039

We may not be able to change the classes due to compatibility problems.

**Comment by ss-superman** [comment]
> Refer [#489 (comment)](https://github.com/alibaba/Sentinel/issues/489#issuecomment-465487039)
> 
> We may not be able to change the classes due to compatibility problems.

**Comment by ss-superman** [comment]
> Refer [#489 (comment)](https://github.com/alibaba/Sentinel/issues/489#issuecomment-465487039)
> 
> We may not be able to change the classes due to compatibility problems.

Thanks for your explanation!

**Comment by renxinlin** [comment]
> Refer [#489 (comment)](https://github.com/alibaba/Sentinel/issues/489#issuecomment-465487039)
> 
> We may not be able to change the classes due to compatibility problems.

could you  please give some description of these classes

**Comment by ralax123** [comment]
我也想知道这些奇怪的单词是什么意思
