### ISSUE TITLE
引入sentinel-web-servlet依赖后报错NoClassDefFoundError: com/alibaba/csp/sentinel/util/SpiLoader

### ISSUE THREAD

**Issue by ChenChuang-0215** [alibaba/Sentinel#2018]
因为需要CommonFilter这个类，所以引入sentinel-web-servlet依赖。
<dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-web-servlet</artifactId>
      <version>1.8.1</version>
</dependency>
引入该依赖后报错：java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/util/SpiLoader

其它sentinel相关依赖：
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
      <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-datasource-nacos</artifactId>
      <version>1.8.1</version>
</dependency>

**Comment by ChenChuang-0215** [comment]
引入sentinel-transport-simple-http依赖也会报java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/util/SpiLoader的错误
<dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-transport-simple-http</artifactId>
      <version>1.8.1</version>
</dependency>

**Comment by cdfive** [comment]
`mvn dependency:tree`看看sentinel-core包的版本，是否也是1.8.1

**Comment by cdfive** [comment]
sentinel 1.8.1几天前刚刚发布，spring-cloud-starter-alibaba-sentinel 2.2.5.RELEASE依赖的sentinel版本是1.8.0，
里面的sentinel-core也是1.8.0，可通过`<dependencyManagement>`指定sentinel的版本号。
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>1.8.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.8.1</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```
建议sentinel的core、transport-simple-http等依赖包版本都保存一致。

**Comment by OscarZJJ** [comment]
同样的问题，引入
       <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>1.8.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.8.1</version>
        </dependency>
或者1.8.0都出现SpiLoader
<img width="806" alt="截屏2021-02-08 下午4 47 45" src="https://user-images.githubusercontent.com/48616141/107196272-6249ac00-6a2d-11eb-8aae-658be50aaffa.png">
能帮看看吗，楼主解决了没

**Comment by cdfive** [comment]
@OscarZJJ 项目里`mvn dependency:tree`看看确定依赖的sentinel-core版本是1.8.1吗？
如果使用`spring-cloud-starter-alibaba-sentinel`，有依赖管理有可能包版本覆盖了。

或者执行`mvn dependency:copy-dependencies`导出依赖的jar，然后在target/dependency里看看sentinel相关jar具体的版本。

**Comment by ChenChuang-0215** [comment]
> 同样的问题，引入
> 
> com.alibaba.csp
> sentinel-core
> 1.8.1
> 
> 
> com.alibaba.csp
> sentinel-transport-simple-http
> 1.8.1
> 
> 或者1.8.0都出现SpiLoader
> <img alt="截屏2021-02-08 下午4 47 45" width="806" src="https://user-images.githubusercontent.com/48616141/107196272-6249ac00-6a2d-11eb-8aae-658be50aaffa.png">
> 能帮看看吗，楼主解决了没

我是把版本降到1.8.0
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-transport-simple-http</artifactId>
    <version>1.8.0</version>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-core</artifactId>
    <version>1.8.0</version>
</dependency>
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-web-servlet</artifactId>
    <version>1.8.0</version>
</dependency>

spring-cloud-starter-alibaba-sentinel 2.2.5.RELEASE 不支持 1.8.1

**Comment by sunuping** [comment]
引入以下包解决 
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.8.3</version>
        </dependency>

**Comment by Frank-97** [comment]
版本保持一致解决
 <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-web-servlet</artifactId>
            <version>1.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.8.0</version>
        </dependency>
