### ISSUE TITLE
Gateway整合Sentinel，怎样重写UrlBlockHandler、RequestOriginParser。

### ISSUE THREAD

**Issue by ChenChuang-0215** [alibaba/Sentinel#2022]
在Gateway网关中
A implements RequestOriginParser
B implements UrlBlockHandler
A类和B类都没有执行，Gateway整合Sentinel，不可以重写UrlBlockHandler、RequestOriginParser了吗？

**Comment by sczyh30** [comment]
网关流控扩展接口与 Web 扩展接口不同，参考文档 https://github.com/alibaba/Sentinel/wiki/网关限流
