### ISSUE TITLE
A neat way to view the project source code directly in the browser

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#2024]
Happy new year!
There's a neat way to view the project source code directly in the browser, and want to share with community.

That is:
By modifying the url of project in browser, add **1s** after **github**, like this:  
https://github.com/alibaba/Sentinel -> https://github1s.com/alibaba/Sentinel

Wait a moment and we can explore the source code as view in IDE(VS Code style), it's convenient and maybe useful.

Refer to:
[https://github.com/conwnet/github1s](https://github.com/conwnet/github1s)

**Comment by sczyh30** [comment]
Cool. Thanks for sharing with us and happy new year!

**Comment by sczyh30** [comment]
Further discussions can be opened in https://github.com/alibaba/Sentinel/discussions
