### ISSUE TITLE
Happy New Year! Can this code segment in ContextUtil.trueEntry() be simplified like this?

### ISSUE THREAD

**Issue by ss-superman** [alibaba/Sentinel#2025]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/16860171/107610664-142ae780-6c7d-11eb-88fe-2a6a3baa6daf.png)

The operation for  **contextNameNodeMap** is already in the thread-safe environment.
Personally, I think this code segment can be simplified like this.
**Did you designed it for avoiding map resize ? If so, I got it.**
![image](https://user-images.githubusercontent.com/16860171/107610606-f9587300-6c7c-11eb-9e70-47c8f151fb80.png)

### Describe what you expected to happen
If possible, I will submit a PR for it.
Looking forward to your reply.
Thanks!
Happy New Year!

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
感觉是有点像Copy On Write的思路，这里new了一个新的HashMap，把contextNameNodeMap里元素放进去，再放入新的node，最后修改引用指向，这样实现线程安全。因为contextNameNodeMap没有用`ConcurrentHashMap`类型，只是`HashMap`类型，通过加锁以及这样处理放元素的方式，性能更高。

不是很确定，帮忙看看这个理解对不哈 @ss-superman @sczyh30 @jasonjoo2010

**Comment by brothelul** [comment]
我的理解是这样的，`
/**
     * Holds all {@link EntranceNode}. Each {@link EntranceNode} is associated with a distinct context name.
     */
    private static volatile Map<String, DefaultNode> contextNameNodeMap = new HashMap<>();
` contextNameNodeMap是static修饰，那么是class共享，虽然此处加了lock是线程安全的，但是往contextNameNodeMap 中put一个元素，虽然有volatile修饰，但是由于内存地址没有发生变化，其他线程线程副本中的还是获取锁之前没有put元素的contextNameNodeMap，进而导致线程安全问题。不知道理解的正不正确？

**Comment by sczyh30** [comment]
> The operation for contextNameNodeMap is already in the thread-safe environment.

The read operations of the map are not (and should not be) guarded by the lock, so here copy-on-write mechanism is necessary.
