### ISSUE TITLE
Sentinel控制台修改规则，持久化怎么同步呢?

### ISSUE THREAD

**Issue by 985391294** [alibaba/Sentinel#2038]
使用Nacos作为持久化限流规则，在Nacos控制台更改完限流规则之后，Sentinel的dashboard立马刷新过来了。但是在Sentinel的dashboard更改限流规则的时候，Nacos持久化里面怎么才能同步呢？

![Uploading nacos.png…]()

**Comment by brothelul** [comment]
现在还没有这样的同步动作，Nacos只是作为一个数据源一样的存在。

**Comment by 985391294** [comment]
ok，后续的版本希望能更新出来同步的操作吧。

**Comment by sczyh30** [comment]
Refer: https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel and many other issues related to `area/dashboard`.
