### ISSUE TITLE
Sentinel的控制台部署在服务器，控制台一直读取不到本机的服务

### ISSUE THREAD

**Issue by 985391294** [alibaba/Sentinel#2039]
控制台一直报
2021-02-22 17:36:48.641 ERROR 7265 --- [pool-2-thread-1] c.a.c.s.dashboard.metric.MetricFetcher   : Failed to fetch metric from <http://192.168.111.19:8719/metric?startTime=1613986473000&endTime=1613986479000&refetch=false> (ConnectionException: Connection timed out)
这个错误。
而且在这个服务器部署的sentinel控制台上面拿不到远程服务器Nacos里面配置的限流规则，但是在本机启动一个dashboard项目就可以看到Nacos里面配置的。

**Comment by sczyh30** [comment]
You may check whether the network from the dashboard to the client side is accessible, and the client IP/network interface is correct.

Refer https://github.com/alibaba/Sentinel/issues?q=Failed+to+fetch+metric

**Comment by PKUcoldkeyboard** [comment]
这个坑我今天刚解决，原因是本机网络是局域网，sentinel部署在服务器的话是无法访问到本机网络的，所以要么sentinel和应用都部署上服务器，要么都在本地运行。

**Comment by 985391294** [comment]
> 这个坑我今天刚解决，原因是本机网络是局域网，sentinel部署在服务器的话是无法访问到本机网络的，所以要么sentinel和应用都部署上服务器，要么都在本地运行。



> 这个坑我今天刚解决，原因是本机网络是局域网，sentinel部署在服务器的话是无法访问到本机网络的，所以要么sentinel和应用都部署上服务器，要么都在本地运行。

是啊 都是本机就可以了

**Comment by zhengduoru** [comment]
> 这个坑我今天刚解决，原因是本机网络是局域网，sentinel部署在服务器的话是无法访问到本机网络的，所以要么sentinel和应用都部署上服务器，要么都在本地运行。

@PKUcoldkeyboard 请教下，我这边dashboard和sentinel的服务都是部署在本机的，也是报这个错，可能是什么配置问题呀？
