### ISSUE TITLE
Nacos添加了namespace，Sentinel获取不到该namespace里面的持久化规则

### ISSUE THREAD

**Issue by 985391294** [alibaba/Sentinel#2040]
使用Nacos作为Sentinel限流的持久化存储，Nacos添加了namespace，Sentinel获取不到该namespace里面的，好像是只会从public这个命名空间里面拉取。在SentinelProperties里面也没有namespace这个属性。但是在NacosDiscoveryProperties和NacosConfigProperties这两个里面都有namespace属性。

**Comment by sczyh30** [comment]
If you're using raw NacosDataSource, you may refer to https://github.com/alibaba/Sentinel/issues/1586#issuecomment-654169993
