### ISSUE TITLE
网关流控规则针对请求属性设置规则变为普通全局限流的问题

### ISSUE THREAD

**Issue by LingLingFeng** [alibaba/Sentinel#2042]
问题说明：
> 网关流控规则` 针对请求URL参数设置流控规则，URL参数未匹配上，结果触发了普通限流：FlowException

类型：错误报告

1.发生了什么
   --》 新建网关流控规则，针对请求属性Url参数进行设置规则 name=yzf，并1秒间隔内超过0次请求触发限流
2.期望发生
  --》当请求的url上未携带name=yzf时，应该不触发限流，结果触发了限流FlowException
3.如何重现：
![image](https://user-images.githubusercontent.com/32393778/108815129-e3d53880-75ee-11eb-9533-0aae07a819df.png)
    1）针对某一个路由设置一个如上图针对Url参数的网关流控规则
    2）请求Url上不要携带Url参数 name=yzf，然后点击发送测试
    3）会发现虽然是针对Url参数设置的流控规则，但是不带url参数的请求一样被限流

4.使用的环境：
spring boot 2.3.5、spring cloud gateway是2.2.6
![image](https://user-images.githubusercontent.com/32393778/108815509-87bee400-75ef-11eb-8882-153f1274cfb2.png)

**Comment by cdfive** [comment]
访问
`http://网关应用ip:网关应用机器列表里Sentinel的端口port/gateway/getRules`
`http://网关应用ip:网关应用机器列表里Sentinel的端口port/getRules?type=flow`
分别看看网关规则和普通流控规则

我用项目里的`sentinel-demo-spring-cloud-gateway`测试，连接控制台，设置跟截图一样的规则，结果是正常的。
多次访问：`http://localhost:8090/httpbin/json?name=yzf`，提示网关限流`Blocked by Sentinel: ParamFlowException`
而访问：`http://localhost:8090/httpbin/json`或`http://localhost:8090/httpbin/json?name=yzf1`没有出现限流。

参考该demo检查对比看看

**Comment by sczyh30** [comment]
检查下是否有地方配了普通的 FlowRule，可以结合日志看下。
