### ISSUE TITLE
规则推模式只有FlowRule的V2实现，没有其它类型规则的实现

### ISSUE THREAD

**Issue by summer9989** [alibaba/Sentinel#2044]
Describe the bug
Version: 1.8.1

前置情况：使用apollo推模式保存并推送流控规则，我司已成功走通，按照wiki描述的方案使用FlowControllerV2和前端改造。所以对整个改造方案是比较了解的。

现存问题：官方wiki包括到目前最新的1.8.1的sentinel-dashboard代码似乎也只有限流规则FlowRule配套有V2的Controller和前端代码，其它比如降级、热点、系统等规则并没有配套V2的Controller和前端代码。所以我们的疑问是：

降级、热点、系统等规则没有V2代码，是需要我们仿造FlowControllerV2自行实现吗？因为还包括前端几个文件的代码，如果自行实现可能后期同步官方新增的功能代码比较麻烦。

**Comment by zhuwei596177831** [comment]
不需要V2  直接在原来的controller基础上改造就行了，通过自定义DynamicRuleProvider和DynamicRulePublisher就行了
你可以看看我这个 https://github.com/zhuwei596177831/sentinel-dashboard-parent

**Comment by sczyh30** [comment]
It's not planned yet. You may refer to existing issues and PRs: https://github.com/alibaba/Sentinel/labels/area%2Fdashboard

**Comment by summer9989** [comment]
@sczyh30  看到您回复了，所以现在确实是未实现的功能是吧，只是还未有官方的实现计划
