### ISSUE TITLE
Dashboard config logging.file's value should not be resolved after maven package

### ISSUE THREAD

**Issue by Anilople** [alibaba/Sentinel#2045]
## Issue Description

Type: *bug report*

### Describe what happened

`application.properties` file in sentinel-dashboard value not correct after `mvn package`

In `sentinel-dashboard.jar`'s file `BOOT-INF/classes/application.properties`

The config `logging.file` in source code `sentinel-dashboard/src/main/resources/application.properties` is 

```properties
logging.file=${user.home}/logs/csp/sentinel-dashboard.log
```

But after `mvn clean package`, the content change.

The value of `${user.home}` is resolved to `C:\Users\bob`, `C:\Users\alice` or `/home/tom`, which base on user's home path.

### Describe what you expected to happen

`${user.home}` is not need to be resolve after maven package, wish it keep until runtime, i.e when dashboard running.

#### 1. package

```bash
cd sentinel-dashboard
mvn clean package -DskipTests
```

#### 2. check

Uncompress `sentinel-dashboard/target/sentinel-dashboard.jar`

Open file `BOOT-INF/classes/application.properties`

View the value of key `logging.file` , `${user.home}/logs/csp/sentinel-dashboard.log` now change to `user-absolute-path/logs/csp/sentinel-dashboard.log`

### Tell us your environment

Windows 10

### Anything else we need to know?

version: 1.8.1

**Comment by Anilople** [comment]
It is about maven-resources-plugin

Maybe we can change the delimiter from `${*}` to `@` in sentinel-dashboard module

And change content in `application.properties` to 

```properties
logging.file=${user.home}/logs/csp/sentinel-dashboard.log

# Inject the dashboard version. It's required to enable
# filtering in pom.xml for this resource file.
sentinel.dashboard.version=@project.version@
```

Then only `sentinel.dashboard.version` will be resolved after maven package

Reference:

* https://stackoverflow.com/questions/4056140/maven-resource-filtering-implications-of-the-symbol-in-resource-files
* https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#delimiters

**Comment by cdfive** [comment]
Thanks for detailed description and documentation! 
Keep the `${user.home}` until runtime is better, since we may package it in one place and run it in other place.
Would you like to contribute a PR to improve this?

**Comment by cdfive** [comment]
Thanks to author, this explains the strange log directory generated by feedback in sentinel discussion group, the user may package sentinel-dashboard.jar in local machine, and upload to develop/test/production environment and then run it.
@sczyh30 @jasonjoo2010

**Comment by Anilople** [comment]
> Thanks for detailed description and documentation!
> Keep the `${user.home}` until runtime is better, since we may package it in one place and run it in other place.
> Would you like to contribute a PR to improve this?

Sure. I will try. Please assign to me.
