### ISSUE TITLE
sentinel整合gateway限流失败

### ISSUE THREAD

**Issue by zhuwei596177831** [alibaba/Sentinel#2047]
这是本人gateway模块的依赖 ：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>
版本号：2.2.5.RELEASE

yml路由配置：
![image](https://user-images.githubusercontent.com/22312344/109093806-ee5d1280-7753-11eb-9eb6-7d148b185775.png)

![image](https://user-images.githubusercontent.com/22312344/109093871-0d5ba480-7754-11eb-9fd1-e13d863a66d3.png)

**Comment by jeesk** [comment]
确实与问题， 我将spring gateway 集成sentinel 后， 自己注册的限流规则不生效。 必须要dashboard里面推送才能生效， 并且推送还有一定几率异常。

**Comment by sczyh30** [comment]
可以对照 https://github.com/alibaba/Sentinel/wiki/FAQ 看看相关日志进行排查
