### ISSUE TITLE
是否支持 TimeUnit.XXX, count 这种规则的配置

### ISSUE THREAD

**Issue by paoyingshidai** [alibaba/Sentinel#2048]
## Issue Description

有时候我们想要的效果是 每个账户 每小时只能通过 count 个请求，这个规则怎么配置？

**Comment by sczyh30** [comment]
Currently Sentinel only supports second-level (QPS) limiting.

**Comment by paoyingshidai** [comment]
> Currently Sentinel only supports second-level (QPS) limiting. Discussions and contributions are welcomed!

感谢解惑，我发现 在热点规则配置中可以设置 检测窗口的时间大小，经过测试，这个配置可以实现这样的功能，但是又遇到了一个 adapter 的问题， 可以看 issues #2060
