### ISSUE TITLE
better document support

### ISSUE THREAD

**Issue by Anilople** [alibaba/Sentinel#2051]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

A document website make people get better document experience.

Maybe sentinel need a website (Use github page or an individual website) to manage document?

**Then anyone can contribute to document**.

Some tools can help to build document website:
* https://docsite.js.org/zh-cn/index.html
* https://docsify.js.org/#/
* https://gohugo.io/

Some examples of open source project's document website:
* http://seata.io/en-us/docs/user/quickstart.html
* https://arthas.aliyun.com/doc/en/quick-start.html
* https://ctripcorp.github.io/apollo/#/
* https://shardingsphere.apache.org/

### Describe what you expected to happen

Create `.md` files under folder `docs` in this repo, or create a new repo to save the document.

**Comment by sczyh30** [comment]
Thanks for your suggestion. We've had a website here: https://sentinelguard.io/

Repo: https://github.com/sentinel-group/sentinel-website

**Comment by Anilople** [comment]
What's the relationship between https://github.com/alibaba/Sentinel/wiki and https://sentinelguard.io/ ?

How about put https://sentinelguard.io/  to README.md?

It seems that https://sentinelguard.io/ is hard to search by google, bing or baidu, so people like me have trouble to know it's existence...

**Comment by cdfive** [comment]
Put [https://sentinelguard.io/](https://sentinelguard.io/) to README.md is a good suggestion, since the project home page may be the first to be seen or visited.
