### ISSUE TITLE
不用AHAS能把sentinel集成到nginx配置中吗

### ISSUE THREAD

**Issue by yazong** [alibaba/Sentinel#2052]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
AHAS Sentinel 支持快速接入 Nginx/Ingress: https://help.aliyun.com/document_detail/178827.html
Sentinel Java 版本目前没有计划支持这一块。

**Comment by yazong** [comment]
谢谢
