### ISSUE TITLE
UrlCleaner#clean(String originUrl) 建议入参增加 HttpServletRequest

### ISSUE THREAD

**Issue by paoyingshidai** [alibaba/Sentinel#2071]
我们在对 originUrl 进行清洗的时候发现，这个过程需要对 HttpServletReqeust 的依赖，但是原接口并没有提供足够的入参或者拓展。比如 我想要依赖 springMvc 中 RequestMappingHandlerMapping 的一些方法，这些方法是需要 HttpServletRequest 的，但是 UrlCleaner#clean(String orginUrl) 入参没有提供，所以就难拓展。希望可以完善这个

**Comment by cdfive** [comment]
可通过`RequestContextHolder`类直接获取`HttpServletReqeust`，公司项目里定制`UrlCleaner#clean(String orginUrl)`实现用到了该方法，用于支持热点商品相关接口的限流，已上线运行了几个月没有问题。

代码供参考：
```java
/**
 * 获取HttpServletRequest对象
 */
protected HttpServletRequest getHttpServletRequest() {
    try {
        return ((ServletRequestAttributes) (RequestContextHolder.currentRequestAttributes())).getRequest();
    } catch (Exception e) {
        log.error("get http servlet request error", e);
        return null;
    }
}
```

抽象类`RequestContextHolder`通过`ThreadLocal`保存的`ServletRequestAttributes`对象，里面有`HttpServletRequest`和
`HttpServletResponse`对象，在spring-webmvc模块里`FrameworkServlet`类的`buildRequestAttributes`,`initContextHolders`方法有设置，然后提供了`currentRequestAttributes`静态方法供使用。

这样不用改变api

关联issue：#2014
