### ISSUE TITLE
Gateway flow control for some specific IP | Spring Cloud Gateway 只针对某些 IP 限流

### ISSUE THREAD

**Issue by bruce12452002** [alibaba/Sentinel#2079]
你好！目前整合好了之后，用的是 ip 限流，有个需求是有些 ip 要限流、有些就不需要
目求有用 BlockRequesthandler 有截取到 ip 等的相关资料，如果合乎某些 ip 确实就限流了；但不合乎的不晓得要怎么放行，让这些 ip 继续访问？

**Comment by sczyh30** [comment]
可以参考[网关限流文档](https://github.com/alibaba/Sentinel/wiki/网关限流_，针对 IP 值进行匹配，规则只针对匹配的生效。

---

You may leverage `matchStrategy` and `pattern` in gateway flow rules.
