### ISSUE TITLE
控制台有显示服务实例，但是访问接口后实时监控和簇点链路都没有数据

### ISSUE THREAD

**Issue by he953481025-debug** [alibaba/Sentinel#2080]
最近公司微服务架构打算引入Sentinel，Sentinel版本是1.8.1，starter的版本是2.2.3.RELEASE。
遇到了两个问题：
1
  1.1配置如下:
![image](https://user-images.githubusercontent.com/67448461/110909145-b4426200-834a-11eb-9580-faee50f1e335.png)
  1.2访问服务地址后，控制台没有数据，查看sentinel-record.log如下
![image](https://user-images.githubusercontent.com/67448461/110909773-709c2800-834b-11eb-8281-c9dacca65143.png)
 1.3使用telnet 连接8721端口，发现连接失败
![image](https://user-images.githubusercontent.com/67448461/110909961-ac36f200-834b-11eb-8e0b-dc938e9e69cf.png)

最后，我怀疑是初始化的问题，所以修改了配置，出现了title中的现象
 
2
  2.1配置如下，在Spring容器启动成功后就发送心跳：
![image](https://user-images.githubusercontent.com/67448461/110910161-ebfdd980-834b-11eb-8ed8-7b43d79b6840.png)
  2.2 控制台有了服务数据，机器列表中的ip地址和端口都正常
![image](https://user-images.githubusercontent.com/67448461/110910516-69c1e500-834c-11eb-87f5-55478cdaa0cb.png)
  2.3 访问地址后，实时监控和簇点链路都没有数据
![image](https://user-images.githubusercontent.com/67448461/110911081-2d42b900-834d-11eb-80ee-400071a1d205.png)

**Comment by cdfive** [comment]
> 2.3 访问地址后，实时监控和簇点链路都没有数据

是通过feign访问的服务接口吗？

如果是，看看配置启用没：
```java
feign:
  sentinel:
    enabled: true
```

**Comment by he953481025-debug** [comment]
> > 2.3 访问地址后，实时监控和簇点链路都没有数据
> 
> 是通过feign访问的服务接口吗？
> 
> 如果是，看看配置启用没：
> 
> ```java
> feign:
>   sentinel:
>     enabled: true
> ```
目前是通过@SentinelResource注解解决了，但还是想不明白为啥要加spring.cloud.sentinel.eager=true才会发送心跳

**Comment by sczyh30** [comment]
See https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查
