### ISSUE TITLE
URL-level gateway circuit breaking | spring-cloud-gateway 网关熔断降级能设置到 URL 级别吗？

### ISSUE THREAD

**Issue by kdlqbz2020** [alibaba/Sentinel#2102]
sentinel1.6.3集成spring-cloud-gateway，网关熔断降级能设置到接口级别吗？ 如下图配置到接口级别熔断降级不生效。

<img width="947" alt="1" src="https://user-images.githubusercontent.com/81558069/112814702-238db500-90b2-11eb-95f4-09d0dae66d6b.png">

**Comment by sczyh30** [comment]
URL-level is not supported. You may create API groups for URL matching.

---

URL 级别的不支持。如有需要，可以创建自定义的 API 分组将 URL 模式匹配归组，然后针对 API 配置规则。

**Comment by kdlqbz2020** [comment]
1.6.3版本的控制台降级规则也没有按api分组来做降级的功能，最新版本的控制台有通过api分组来做熔断降级功能吗？还是需要自己代码实现？

**Comment by kdlqbz2020** [comment]
> URL-level is not supported. You may create API groups for URL matching.
> 
> URL 级别的不支持。如有需要，可以创建自定义的 API 分组将 URL 模式匹配归组，然后针对 API 配置规则。

1.6.3版本的控制台降级规则也没有按api分组来做降级的功能，最新版本的控制台有通过api分组来做熔断降级功能吗？还是需要自己代码实现？

**Comment by kdlqbz2020** [comment]
我看了下 只有  GatewayFlowRule 类，没有 GatewayDegradeRule类，通过针对 API分组 来配置熔断降级规则也不行吧，或者是要怎么实现，能否给下提示。

**Comment by sczyh30** [comment]
针对自定义的 API 分组名，配置普通的熔断规则 DegradeRule 即可。
