### ISSUE TITLE
FlowRuleManager类中flowRules不需要用AtomicReference

### ISSUE THREAD

**Issue by Moonergfp** [alibaba/Sentinel#2103]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
FlowRuleManager类中flowRules类型是使用AtomicReference，根本没有比较动作，直接用volatile修饰即可
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Would you like to contribute a PR to improve it?

**Comment by Moonergfp** [comment]
> Would you like to contribute a PR to improve it?

I give my advice

**Comment by JerryChin** [comment]
I'm interested, I will start a PR ASAP. @sczyh30

**Comment by Moonergfp** [comment]
> I think it has no any effect.

没影响是一回事儿，滥用是另一会儿事
