### ISSUE TITLE
Circuit breaker supports ignoring some exceptions | 希望定义降级规则时可配置忽略某种异常

### ISSUE THREAD

**Issue by Lawrence-Albet** [alibaba/Sentinel#2112]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

网关限流中,我抛出auth异常过多导致服务熔断,这个异常应该被忽略的
### Describe what you expected to happen

这个异常可以在我定义DegradeRule时被忽略
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
You may leverage `setExceptionsToIgnore` in `Tracer` to ignore some exceptions:

https://github.com/alibaba/Sentinel/blob/5ac112efaa0de247bc019e56e23e1b6402cae7aa/sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java#L144-L158

**Comment by Lawrence-Albet** [comment]
> You may leverage `setExceptionsToIgnore` in `Tracer` to ignore some exceptions:
> 
> https://github.com/alibaba/Sentinel/blob/5ac112efaa0de247bc019e56e23e1b6402cae7aa/sentinel-core/src/main/java/com/alibaba/csp/sentinel/Tracer.java#L144-L158

thank you,it works
