### ISSUE TITLE
期望8719端口和应用端口合并

### ISSUE THREAD

**Issue by walyuuc** [alibaba/Sentinel#2114]
## Issue Description

在k8s环境中再开通一个8719端口，有时是很困难的事，包括但不限于技术问题（8719被占用，如何往下顺延开通），环境问题，公司规范问题，历史问题等等
所以期望可以用应用端口代替8719端口的职责，提供全部端点，例如metric，getRules，setRules等等

### Describe what happened (or what feature you want)

公司k8s环境不能额外开通8719端口，导致dashboard收集不到metric，也不能和client通信

### Describe what you expected to happen

8719端口的端点能迁移到应用端口下，并且心跳应用端口和应用contextPath
查询规则和设置规则时，也能用应用端口和应用contextPath

我看到sentinel-transport-spring-mvc模块好像是要做这方面的事情，但是截至到1.8.1版本，还没有实现具体的代码

**Comment by sczyh30** [comment]
Hi, this has been implemented in [sentinel-transport-spring-mvc](https://github.com/alibaba/Sentinel/tree/master/sentinel-transport/sentinel-transport-spring-mvc), which will be released in 1.8.2.

**Comment by walyuuc** [comment]
> Hi, this has been implemented in [sentinel-transport-spring-mvc](https://github.com/alibaba/Sentinel/tree/master/sentinel-transport/sentinel-transport-spring-mvc), which will be released in 1.8.2.

看了下master sentinel-transport-spring-mvc目前的做法，也跑了下demo，是可以满足期望的，端点都在应用端口工作了，
两个想法
一、工作的路径是类似这样，localhost:20281/tree，没有contextPath，这块不一定强求满足，但可以考虑实现，毕竟有了contextPath在网关层看更规范些
二、端口必须通过 -Dcsp.sentinel.api.port=20281 启动参数指定，不指定就心跳 空端口，这会有个问题，容器中服务的端口是动态的怎么办，我也没法事先通过 -D 参数指定，都是启动时动态分配的，所以这块最好能自动获取服务端口，比如获取spring的server.port

**Comment by cdfive** [comment]
> 二、端口必须通过 -Dcsp.sentinel.api.port=20281 启动参数指定...

目前[sentinel-transport-spring-mvc](https://github.com/alibaba/Sentinel/tree/master/sentinel-transport/sentinel-transport-spring-mvc)里就是获取的springboot应用的server.port端口，不需要指定。
可参考demo运行起来看看：[sentinel-demo-transport-spring-mvc](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-transport-spring-mvc)

**Comment by walyuuc** [comment]
是的，确实不需要指定，是在SentinelApiHandlerMapping的onApplicationEvent设置的
我是之前摸索demo时没有初始化SentinelApiHandlerMapping和SentinelApiHandlerAdapter导致心跳端口空，先入为主了，初始化后是能自动获取端口的
1.8.2有大概的发布时间计划么？

**Comment by sczyh30** [comment]
> 是的，确实不需要指定，是在SentinelApiHandlerMapping的onApplicationEvent设置的
> 我是之前摸索demo时没有初始化SentinelApiHandlerMapping和SentinelApiHandlerAdapter导致心跳端口空，先入为主了，初始化后是能自动获取端口的
> 1.8.2有大概的发布时间计划么？

目前计划在4月底5月初发布
cc @cdfive @jasonjoo2010

**Comment by ulyn** [comment]
> 工作的路径是类似这样，localhost:20281/tree，没有contextPath，这块不一定强求满足，但可以考虑实现，毕竟有了contextPath在网关层看更规范些，最好contextPath之后还能指定一级路径，类似actuator这样

同样遇到类似问题，希望能够将客户端的请求加自定义前缀  如 localhost:20281/contextPath/public/sentinel/  目前貌似没找到方式，只能去修改dashboard？
