### ISSUE TITLE
配置集群限流没有生效

### ISSUE THREAD

**Issue by zhengxgs** [alibaba/Sentinel#2119]
规则配置
![image](https://user-images.githubusercontent.com/7812982/114146520-450c5d80-994a-11eb-854b-109b345aabbe.png)

集群连接情况: /cluster/server/info

![image](https://user-images.githubusercontent.com/7812982/114146697-7be27380-994a-11eb-8d1c-c2c50fc021ec.png)

token server日志
![image](https://user-images.githubusercontent.com/7812982/114146975-cb28a400-994a-11eb-9efc-67e888178fc7.png)

token client及删除规则重新加入规则的日志 (6个client节点日志一直 都能正常获取到规则)
![image](https://user-images.githubusercontent.com/7812982/114147152-fd3a0600-994a-11eb-99fe-1356c1fcfb6c.png)

显示效果(看起来像是用单机兜底了):
![image](https://user-images.githubusercontent.com/7812982/114147599-6caff580-994b-11eb-8109-facd4af7f403.png)

机器配置总共7个节点.  token server就是应用节点. 没有使用独立模式.
使用版本 1.8.1
目前看规则读取没有问题,在${user.home}/logs/csp/sentinel-record.log日志中.

希望帮忙看看这个问题解决一下.

**Comment by sczyh30** [comment]
可以 check 下 `~/logs/csp/sentinel-cluster-client.log` 看看有没有一些提示。

**Comment by zhengxgs** [comment]
> 可以 check 下 `~/logs/csp/sentinel-cluster-client.log` 看看有没有一些提示。

`~/logs/csp/sentinel-cluster-client.log` 有request time out的日志显示，可能是因为连接不上集群导致的？

**Comment by sczyh30** [comment]
request time out 代表请求超时，可以看下是否每次都有超时，是否网络延迟较高

**Comment by zhengxgs** [comment]
已对接运维查看运维情况，更换了其他机器现在使用正常了，谢谢

**Comment by 15988464357** [comment]
我也遇到这个问题 request time out
请问是
![9](https://user-images.githubusercontent.com/66710344/123606389-6dac4100-d82f-11eb-86bc-c7fb20e76800.png)
怎么解决的？
