### ISSUE TITLE
SentinelResourceAspect类继承问题

### ISSUE THREAD

**Issue by bitonly** [alibaba/Sentinel#212]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
特殊场景下 SentinelResourceAnnotation 类 与 SentinelResourceAspect类不能满足一些场景, 我们需要实现自己的切面类, 但SentinelResourceAspect类中的方法都是 private 的, 比如handleBlockException方法, 我们没有办法复用, 需要改成 protected, 方便用户继承SentinelResourceAspect

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, can you illustrate your scenarios that current annotation module cannot cover?

**Comment by bitonly** [comment]
> Hi, can you illustrate your scenarios that current annotation module cannot cover?

for example, i will create resource entry base the parameters's value, so sometime resource entry created, sometime not

**Comment by bitonly** [comment]
change some methods of SentinelResourceAspect class is a way, another way is create a base Aspect class, then SentinelResourceAspect  can extend it, my aspect can extend it also

**Comment by sczyh30** [comment]
> change some methods of SentinelResourceAspect class is a way, another way is create a base Aspect class, then SentinelResourceAspect can extend it, my aspect can extend it also

It seems that the latter one (make abstraction) is better.
