### ISSUE TITLE
【建议】当限流发生时，提供一个选项能够不抛出BlockException，而是返回方法的empty result，就像dubbo mock那样

### ISSUE THREAD

**Issue by yongdi** [alibaba/Sentinel#2126]
流控和降级时直接抛异常并不友好，如果消费者使用了guava cache等会导致异常。为何不像dubbo那样，提供一个mock="return empty"同样的mock方法，当限流或降级发生时？

**Comment by sczyh30** [comment]
可以参考 [FAQ 指引](https://github.com/alibaba/Sentinel/wiki/FAQ#q-规则生效后除了抛异常之外还有没有其它的处理方式) 来配置自定义的流控处理逻辑。
