### ISSUE TITLE
sentinel-demo-nacos-datasource 示例存在bug, 建议将 groupId 进行修改

### ISSUE THREAD

**Issue by zhangyunan1994** [alibaba/Sentinel#2128]
## Issue Description

Type: *bug report* or *feature request*

在测试用例中

其中设置了 groupId 为 

这样导致获取配置的请求为 xx/nacos/v1/cs/configs?dataId=com.alibaba.csp.sentinel.demo.flow.rule&group=Sentinel:Demo

这样会导致无法查询到配置，建议改成 SentinelDemo或者其他

### How to reproduce it (as minimally and precisely as possible)

1. 运行 sentinel-demo-nacos-datasource 示例即可发现

### Tell us your environment

- jdk: 1.8.0_281
- Nacos: 2.0.0

**Comment by sczyh30** [comment]
Would you like to contribute a PR to improve it?

**Comment by zhangyunan1994** [comment]
PR 已经提交
