### ISSUE TITLE
Docs for rule configuration of legacy versions

### ISSUE THREAD

**Issue by hhfdna** [alibaba/Sentinel#2140]
where to find flow rules and degrade rules for deferent sentinel version, if i using json format in nacos or any other outer storages

**Comment by hhfdna** [comment]
like with 1.7, json rule should be
```json
[{
  "resource":"com.bocsoft.demo.sentinel.publish.DemoService",
  "grade":0,
  "count":110,
  "timeWindow":3,
  "minRequestAmount":10,
  "rtSlowRequestAmount":4,
  "limitApp":"default"
}]
```
while with 1.8,should be
```json
[{
  "resource":"com.bocsoft.demo.sentinel.publish.DemoService",
  "grade":0,
  "count":110,
  "timeWindow":3,
  "minRequestAmount":10,
  "statIntervalMs":1000,
  "slowRatioThreshold":0.5
}]
```

is there some documents to define this for deferent versions and rules

**Comment by cdfive** [comment]
wiki里[熔断降级](https://github.com/alibaba/Sentinel/wiki/熔断降级)是1.8以上最新的，老版本文档wiki上没有保留需要完善。

通过[https://github.com/alibaba/Sentinel.wiki.git](https://github.com/alibaba/Sentinel.wiki.git)这个可以找wiki文档的历史版本。
刚找到了1.8以前的降级规则文档供参考：

### 熔断降级规则 (DegradeRule)

熔断降级规则包含下面几个重要的属性：

| Field | 说明 | 默认值 |
| :----: | :----| :----|
| resource | 资源名，即限流规则的作用对象 ||
| count | 阈值 ||
| grade | 熔断策略，支持秒级 RT/秒级异常比例/分钟级异常数 |秒级平均 RT|
| timeWindow | 降级的时间，单位为 s||
| rtSlowRequestAmount | RT 模式下 1 秒内连续多少个请求的平均 RT 超出阈值方可触发熔断（1.7.0 引入） | 5 |
| minRequestAmount | 异常熔断的触发最小请求数，请求数小于该值时即使异常比率超出阈值也不会熔断（1.7.0 引入） | 5 |

同一个资源可以同时有多个降级规则。

**Comment by sczyh30** [comment]
Hi, it's highly recommended to upgrade Sentinel to 1.8.x, as the circuit breaking feature has been refactored and improved.

**Comment by hhfdna** [comment]
ok， thx， but this link https://github.com/alibaba/Sentinel.wiki.git can't access.
