### ISSUE TITLE
@SentinelResource fallback will handle all exceptions even if there are no degrade rules | 删除降级规则，资源仍然被降级

### ISSUE THREAD

**Issue by yujun110** [alibaba/Sentinel#2149]
## Issue Description

Type: bug report

1.设置某一个资源的降级规则：异常数。在nacos配置了一个开关，
模拟异常数，开关开启，直接在接口里抛异常。验证，降级成功。

2.删除资源的降级规则，curl http://localhost:8719/getRules?type=degrade
发现规则为空，说明删除成功，此时nacos异常开关仍开启。

3.访问资源，仍然返回降级的数据

4.关闭nacos开关，访问成功。

5.开启开关，接口又被降级。

通过调用 http://localhost:8719/getRules?type=degrade
发现明明删除成功了，为什么仍然被降级了。之后把服务重启了，只要我把nacos异常开关开启，就会降级，和是不是本地有降级规则无关。

想知道为什么http://localhost:8719/getRules?type=degrade   的规则为空，服务仍然会被降级。

**Comment by sczyh30** [comment]
If you're using `fallback` and `defaultFallback` of `@SentinelResource` annotation, any kinds of exceptions will be handled in the fallback.

---

看下埋点方式。如果是注解方式埋点，并且配了 fallback/defaultFallback，那无论怎样的异常 都会进入 fallback，而无关是否被熔断。

**Comment by yujun110** [comment]
@sczyh30  是的，我用的注解，设计上就是这样，我还以为是个bug

**Comment by sczyh30** [comment]
> @sczyh30 是的，我用的注解，看了下SentinelResourceAspect好像是这么回事，我还以为是个bug。那注解形式的埋点，异常数 异常比例都没必要在控制台配置了吧

这个只是 fallback 的机制，和熔断策略应该分开来看
