### ISSUE TITLE
sentinel控制台 不显示 网关配置，本地windows可以，linux服务器不行

### ISSUE THREAD

**Issue by lianbitangjin** [alibaba/Sentinel#2152]
[

## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我在windows本地项目中集成了网关sentinel，本地的sentinel控制台显示是正确的，限流也起作用
当时发布到服务器，同样安装的是sentinel1.8.0，项目启动后，首先控制台仍然是普通的界面，没有显示网关特殊的菜单栏界面
并且加载不到nacos中的限流规则

我来来回回看了本地和linux的配置以及启动的控制台，没有任何区别，这是什么问题？能否给我指点一下解决该问题的方向？

### Tell us your environment

linux 

sentinel1.8.0 

Spring Cloud Version	 Spring Cloud Hoxton.SR8

Spring Cloud Alibaba Version	 2.2.5.RELEASE

Spring Boot Version  2.3.2.RELEASE

**Comment by sunzhen086** [comment]
i had the same question

**Comment by cdfive** [comment]
有几个思路供参考：
* 打包后的应用是否有`spring-cloud-alibaba-sentinel-gateway`依赖，因为`app_type`是通`SentinelSCGAutoConfiguration#initAppType`设置的
* 在Sentinel-record.log日志里搜`Application type resolved`，看看值是不是`11`，控制台收到心跳消息里的字段`app_type`值是`11`会标识为网关应用。
* 发到服务器的控制台，是否浏览器有缓存，比如chrome浏览器，可用Ctrl + Shift + N模式打开 或者 F12开发者工具勾选disable cache

**Comment by sunzhen086** [comment]
我清理了chrome的缓存，问题就解决了，我之前多次尝试过ctrl+f5刷新，看来还是太拿衣服了，谢谢
