### ISSUE TITLE
无法注入sentinelGatewayFilter的bean | sentinelGatewayFilter A bean with that name has already been defined in class path resource

### ISSUE THREAD

**Issue by fangweilong** [alibaba/Sentinel#2153]
sentinel：1.8.0
按照示例https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-spring-cloud-gateway/src/main/java/com/alibaba/csp/sentinel/demo/spring/sc/gateway/GatewayConfiguration.java，注入
```
@Bean
	@Order(-1)
	public GlobalFilter sentinelGatewayFilter() {
		return new SentinelGatewayFilter();
	}
```

报错信息：The bean 'sentinelGatewayFilter', defined in class path resource [com/alibaba/cloud/sentinel/gateway/scg/SentinelSCGAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [cn/o/gateway/config/GatewayConfig.class] and overriding is disabled.

查看源码得知，在这个bean上添加了@ConditionalOnMissingBean。请更新示例或者更新文档，是否必须要重写bean name？

**Comment by sczyh30** [comment]
若已通过 SCA `spring-cloud-alibaba-sentinel-gateway` 接入网关流控，则无需再单独加 Configuration。相关文档已更新。
