### ISSUE TITLE
The application in Gateway type，Dashboard request the wrong flow rules

### ISSUE THREAD

**Issue by brothelul** [alibaba/Sentinel#2157]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/25661357/115851934-174f0a80-a45a-11eb-8aef-95ae4524b0eb.png)

### Describe what you expected to happen

should request the gateway/flow/list.json

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
Has the JVM argument `-Dcsp.sentinel.app.type=1` added? 
It's commented in `GatewayDemoApplication` class.

**Comment by brothelul** [comment]
Thank you . I find that I miss the JVM argument. I will close this issue.
