### ISSUE TITLE
在自己的项目初始化时，调用IntervalProperty的updateIntervale方法，将INTERVAL变量值右1000ms修改为10000ms，请协助评估修改是否可行？

### ISSUE THREAD

**Issue by xinxingo** [alibaba/Sentinel#2164]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen
在自己的项目初始化时，调用IntervalProperty的更新Intervale方法，将InterVAL变量值右1000ms修改为10000ms，请协助评估修改是否可行？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
It's not recommended to modify the global attributes of the sliding window. Could you please illustrate your scenario?

---

一般不推荐调整滑动窗口的配置，可能会导致预期外的效果。可以描述下你们的场景。
