### ISSUE TITLE
SentinelWebTotalInterceptor如何使用，并没有看到相关文档(How to use sentinel webtotalinterceptor? I didn't see the relevant documents)

### ISSUE THREAD

**Issue by y934317258** [alibaba/Sentinel#2166]
## Issue Description

feature request

### Describe what happened (or what feature you want)
SentinelWebTotalInterceptor如何使用，并没有看到相关文档(How to use sentinel webtotalinterceptor? I didn't see the relevant documents)

### Describe what you expected to happen
web接口支持服务粒度限流(Web interface supports service granularity flow limiting)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Just like `SentinelWebInterceptor` (overriding `addInterceptors` and add it to InterceptorRegistry)
