### ISSUE TITLE
spring cloud web接口是否支持服务粒度限流 | Whether spring cloud web interface supports service granularity flow restriction

### ISSUE THREAD

**Issue by y934317258** [alibaba/Sentinel#2167]
## Issue Description

feature request

### Describe what happened (or what feature you want)
spring cloud web接口是否支持服务粒度限流 | Whether spring cloud web interface supports service granularity flow restriction

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
> Whether spring cloud web interface supports service granularity flow restriction

Could you please illustrate the meaning of "service granularity" under Web scenarios?

**Comment by y934317258** [comment]
> > Whether spring cloud web interface supports service granularity flow restriction
> 
> Could you please illustrate the meaning of "service granularity" under Web scenarios?


我想为sentinel_spring_web_context资源做流量控制，整个微服务的入口流量
I want to work for sentinel_spring_web_context resource is used for flow control, and the entrance flow of the whole microservice is controlled

![image](https://user-images.githubusercontent.com/68832358/116333622-59839d80-a806-11eb-8730-a29fa38f8957.png)

**Comment by y934317258** [comment]
@sczyh30

**Comment by sczyh30** [comment]
Hi, you may leverage `SentinelWebTotalInterceptor` or inbound QPS mode of system rule.

**Comment by JiCoM** [comment]
@sczyh30 请问我对于sentinel_spring_web_context这个进行流控规则设置为什么没有生效，其他的资源添加流控都是正常的，我已经按官方文档添加mvc intercept适配了
