### ISSUE TITLE
[feature request] make sentinel client close resources more easier and elegant

### ISSUE THREAD

**Issue by Anilople** [alibaba/Sentinel#2178]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

User can close sentinel client's resouces manually.

### Describe what you expected to happen

User can use `com.alibaba.csp.sentinel.init.InitExecutor.doInit()` to init sentinel client.

Sometimes user want to close all resources in it.

Because some InitFunc will start a thread executor, and user may don't know how to close them.

For example, if user use `sentinel-transport-simple-http`, `com.alibaba.csp.sentinel.transport.init.CommandCenterInitFunc` will use `com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter`, there are 2 `ExecutorService` in it, user must write code to close it 

```java
		CommandCenter commandCenter = CommandCenterProvider.getCommandCenter();
		commandCenter.stop();
```

To make it more easier, should sentinel's client support a method to do it?

Like `CloseExecutor.doClose()`.

### Tell us your environment

OS: Centos 7.8
Jdk: 8
Sentinel Version: 1.8.0

### Anything else we need to know?

When someone use [Spring Cloud Alibaba Sentinel](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel), 
shutdown in [actuator endpoint](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html) would be not working.

The reason is that `ExecutorService` in `com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter` prevents JVM to stop.

**Comment by Anilople** [comment]
It seems that infinite loops `while (true)` in

https://github.com/alibaba/Sentinel/blob/2c12b075340ac5058dc2c57b0e272048a6ba43f6/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/SimpleHttpCommandCenter.java#L184-L209

prevents JVM to stop.

**Comment by Anilople** [comment]
Maybe we can change those thread to daemon thread?

Change 
https://github.com/alibaba/Sentinel/blob/2c12b075340ac5058dc2c57b0e272048a6ba43f6/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/SimpleHttpCommandCenter.java#L60
to
```java
new NamedThreadFactory("sentinel-command-center-executor", true)); 
```

https://github.com/alibaba/Sentinel/blob/2c12b075340ac5058dc2c57b0e272048a6ba43f6/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/SimpleHttpCommandCenter.java#L78
to
```java
new NamedThreadFactory("sentinel-command-center-service-executor", true),
```

That will let jvm close when user thread finished.

**Comment by sczyh30** [comment]
Good idea. Fancy a PR to improve it?

**Comment by sczyh30** [comment]
> Maybe we can change those thread to daemon thread?
> 
> Change
> https://github.com/alibaba/Sentinel/blob/2c12b075340ac5058dc2c57b0e272048a6ba43f6/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/SimpleHttpCommandCenter.java#L60
> 
> 
> to
> ```java
> new NamedThreadFactory("sentinel-command-center-executor", true)); 
> ```
> 
> https://github.com/alibaba/Sentinel/blob/2c12b075340ac5058dc2c57b0e272048a6ba43f6/sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/SimpleHttpCommandCenter.java#L78
> 
> 
> to
> ```java
> new NamedThreadFactory("sentinel-command-center-service-executor", true),
> ```
> 
> That will let jvm close when user thread finished.

Good idea. Fancy a PR to improve it?

**Comment by wutingjia** [comment]
please assign to me for practicing PR ~~~~(>_<)~~~~
