### ISSUE TITLE
官方可以在sentinel-dashboard模块里面，直接集成redis，nacos，zookeeper，apollo持久化方案吗，然后通过变量取值来决定使用哪种持久化的方式吗？

### ISSUE THREAD

**Issue by hegphegp** [alibaba/Sentinel#2179]
* 官方可以在sentinel-dashboard模块里面，直接集成redis，nacos，zookeeper，apollo持久化方案吗，然后通过变量取值来决定使用哪种方式，而不是让使用者自己去实现，自己去改造。很多人只想用sentinel-dashboard配置限流规则，不是每一个人都能看得懂所有代码，不是每个人都知道怎么去改造，既然你们开源出了这个框架，为什么不做到开箱即用呢？

**Comment by sczyh30** [comment]
See #1759

**Comment by fengjx** [comment]
我 fork 了一个版本，支持了所有配置持久化到 apollo，不改动官方源码，方便滚动升级，支持 docker。大家可以看看。

https://github.com/fengjx/Sentinel/wiki

**Comment by bert82503** [comment]
> 我 fork 了一个版本，支持了所有配置持久化到 apollo，不改动官方源码，方便滚动升级，支持 docker。大家可以看看。
> 
> https://github.com/fengjx/Sentinel/wiki

微内核插件化方式，也是一种解法。
官方内部支持，做到开箱即用就更好。
对于持久化集成Apollo，建议官方与社区可以共建。
