### ISSUE TITLE
limitApp字段多个用 , 号分割不起作用

### ISSUE THREAD

**Issue by ilaotan** [alibaba/Sentinel#218]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

Comma separator (`,`) does not take effect in `limitApp` field of rules.

`limitApp` 字段多个用 , 号分割不起作用,但是看注释

```java
    /**
     * <p>
     * Application name that will be limited by origin.
     * Multiple application name can be separated with comma (',').
     * </p>
     * <p>The default limitApp is `default`, which means allowing all origin apps.</p>
     * <p>For example: limitApp = `appA,appB` will limit requests from appA and appB.</p>
     */
    private String limitApp;
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1.3.0-GA   1.4.0-SNAPSHOT
dubbo 2.6.4
springboot 2.0.6

**Comment by sczyh30** [comment]
Hi, the comma separator (`,`) only takes effect in `AuthorityRule`. For flow rules you have to create multiple rules for each single limitApp. We'll fix the incorrect comment. Thanks for reporting.

**Comment by sczyh30** [comment]
Fixed.
