### ISSUE TITLE
sentinel-dashboard 1.8.1 DegradeController应该是@RestController 

### ISSUE THREAD

**Issue by vipcolud** [alibaba/Sentinel#2186]

**Comment by sczyh30** [comment]
Would you like to contribute a PR to improve it?

**Comment by brotherlu-xcq** [comment]
I find it has been changed into @RestController in lasted version.
![image](https://user-images.githubusercontent.com/25661357/125763223-071d27ac-18d7-4579-a467-89ace70e3c7b.png)
