### ISSUE TITLE
sentinel控制台多个人先后编辑规则，会报错id不存在##因为持久化到nacos时缺失id

### ISSUE THREAD

**Issue by flyPig-li** [alibaba/Sentinel#2187]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by flyPig-li** [comment]
Issue Description
Type: bug report

Describe what happened (or what feature you want)
如果有两个浏览器或者两个人都去编辑某一个规则时，第一个浏览器可以成功提交，紧接着第二个浏览器再编辑，提交时报错：id xxx  dose not exist，必须第二个浏览器刷新一次才可以接着编辑

以流控规则为例，导致这个问题的原因是由于持久化到nacos时，缺失了规则id，控制台接收流控规则对象为FlowRuleEntity，持久化nacos时的对象为FlowRule，而FlowRule对象没有id属性，使用FlowRuleEntity.toRule()进行规则对象转换时id缺失了，而每次控制台从nacos拉取规则后（/v1/flow/rules接口）都会重新保存本地内存，并且生成新的id，代码如下：
**FlowControllerV1：**
entities = repository.saveAll(entities);

**InMemoryRuleRepositoryAdapter：**
public T save(T entity) {
  if (entity.getId() == null) {
            entity.setId(nextId());
   }
……
}
同理，每次编辑保存规则时也会重新保存本地内存，而编辑传下来的数据就是控制台从nacos拉取后的，没有id，所以第一个浏览器保存之后就会重新生成一个新的id，而第二个浏览器（不刷新的情况下）中的id还是之前老的id，保存时会根据id查，这时候本地内存的id已经被第一个浏览器改掉了，见/v1/flow/save.json接口代码：
FlowRuleEntity entity = repository.findById(id);
if (entity == null) {
    return Result.ofFail(-1, "id " + id + " dose not exist");
}

针对这个问题，我觉得可以这样解决：
1、在AbstractRule类增加id属性
2、FlowRuleEntity类需要修改两个方法：
public static FlowRuleEntity fromFlowRule(String app, String ip, Integer port, FlowRule rule){
    entity.setId(rule.getId()); //添加这句代码
    ……
}

public FlowRule toRule(){
    flowRule.setId(this.id); // 添加这句代码
}

其它类型的规则也类似

**Comment by cdfive** [comment]
Relate to #1346 #1868

**Comment by flyPig-li** [comment]
> Relate to #1346 #1868

Thank you
