### ISSUE TITLE
the sentinel client can register to sentinel-dashboard but dashboard cannot pull metric data from client

### ISSUE THREAD

**Issue by githubcheng2978** [alibaba/Sentinel#2189]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

the sentinel client can register to sentinel-dashboard but dashboard cannot pull metric data from client

the dashboard has been deployed in the container  where is network partition A
but sentinel client deployed in the container where is network partition B,

**Comment by githubcheng2978** [comment]
there is another problem when create a rule, the sentinel client cannot be get。

the long link should be good idea to resolve these  problem

**Comment by kaizi2009** [comment]
> the sentinel client can register to sentinel-dashboard but dashboard cannot pull metric data from client

Is the client's network unobstructed？

**Comment by githubcheng2978** [comment]
> > the sentinel client can register to sentinel-dashboard but dashboard cannot pull metric data from client
> 
> Is the client's network unobstructed？

应该不是的，是因为sentinel-core的注册到dashboard上是容器的地址，dashboard pull metric data的时候。 dashboard跟应用不在一个网络分区里面导致访问不通。 我已经将metric data  通过http 定时主动push了。
