### ISSUE TITLE
`SpiLoader` was broken from 1.8.0 to 1.8.1

### ISSUE THREAD

**Issue by JasonMing** [alibaba/Sentinel#2193]
According #1383, `SpiLoader` was moved from `util` to `spi`, this action breaks the user codes which contains direct accessing to `SpiLoader`.
And, this merging happened during a patch version upgrade? Has no one considered compatibility issues?

**Comment by cdfive** [comment]
Besides, Sentinel 1.8.1 requires JDK 1.8 or higher version, please see [release notes ](https://github.com/alibaba/Sentinel/wiki/Release-Notes)

**Comment by wuwen5** [comment]
请不要在第三位小版本号做这种更新

**Comment by JasonMing** [comment]
@wuwen5 我们现在做法是只能自己在私库发bom，搞个定时任务每天扫描相关组件生成对应的bom，用户直接import bom来定义版本。
maven的依赖仲裁基于nearest first规则，解释起来模型乱七八糟，没bom真的受不了。。。
