### ISSUE TITLE
how to use the dashboard in a cluster mode

### ISSUE THREAD

**Issue by wqan** [alibaba/Sentinel#2199]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

it is supported to configure more than one dashboard address, however, only the first address will be chosen to send hearbeat. How can I use dashboard in a cluster mode?
i find the field 'currentAddressIdx' of the class 'SimpleHttpHeartbeatSender' is always 0. Should it be auto increasement?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, multi-dashboard is not supported yet. You may refer existing issues to refactor if needed.
