### ISSUE TITLE
Sentinel簇点链路有testA的信息，添加流控规则后cmd也打印 setRules: success，但是页面不显示流控记录，也不生效，求助

### ISSUE THREAD

**Issue by 2366095032** [alibaba/Sentinel#2205]
sentinel能访问，并且项目的请求testA也进入了簇点链路，项目启动没有报错，sentinel启动的时候cmd也没有报错，但是添加流控规则有问题，成功后，并且cmd也打印了success，但是页面的流控依旧是空的，也没有生效，一直卡在这，试过1.7，1.8，1.8.1都没用，求助，救救孩子o(╥﹏╥)o。

**Comment by 2366095032** [comment]
![2](https://user-images.githubusercontent.com/54217250/118205306-9d2b0800-b492-11eb-967b-7958aeb4e718.PNG)
![捕获](https://user-images.githubusercontent.com/54217250/118205313-a0be8f00-b492-11eb-9e4d-3d12f63bc7be.PNG)

**Comment by cdfive** [comment]
可能是应用端fastjson版本问题，检查下是否是较新版本

可参考：[https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查)

* 若规则保存成功但未在控制台上出现，请确保接入端的 fastjson 的版本是较新版本。

**Comment by 2366095032** [comment]
我竟然没有引入fastjson，还以为内置了，都是阿里的，啊啊啊！！！超级感谢你，我爱你，ε=(´ο｀*)))

**Comment by cdfive** [comment]
应用端如果依赖了`sentinel-transport-simple-http`或`sentinel-transport-netty-http`，它们都依赖了`sentinel-transport-common`模块，它里面依赖了`fastjson`会自动引入的。只是应用端可能有自己的版本号和版本依赖，最终导致`fastjson`版本过低。

可通过`mvn dependency:tree`或者IDEA安装maven helper插件查看应用端的依赖版本哈
