### ISSUE TITLE
nacos配置的限流规则同步到sentinel部分属性未生效

### ISSUE THREAD

**Issue by LoranMEI** [alibaba/Sentinel#2208]
问题：

nacos配置的限流规则同步到sentinel部分属性未生效

详细描述：

在nacos配置中心配置限流规则如下

[{"app":"auth-gateway","burst":0,"clusterConfig":{"thresholdType":0},"clusterMode":false,"controlBehavior":0,"count":20,"gmtCreate":1621325252517,"gmtModified":1621325252517,"grade":1,"id":12,"intervalUnit":1,"inteval":2,"limitApp":"default","paramItem":{"fieldName":"ClientAuthority","matchStrategy":0,"parseStrategy":2,"pattern":"48718795202629"},"resource":"48715125211205","resourceMode":1,"strategy":"0"}]

其中inteval为2，或者使用intevalSec也同样问题
intervalUnit为1，分钟

哨兵中如下所示，时间间隔和单位始终是1秒，怎么设置都是不生效

![image](https://user-images.githubusercontent.com/27984075/118616131-fcbb4780-b7f3-11eb-9994-eb26b340ce19.png)

版本依赖：

nacos:2.0.1
哨兵:1.8.0
springboot:2.3.4
spring-cloud:Hoxton.SR8
spring-cloud-alibaba:2.2.5.RELEASE

**Comment by cdfive** [comment]
interval、intervalUnit是`GatewayFlowRuleEntity`里定义的字段，用于跟控制台配置规则的界面UI交互。
intervalSec是`GatewayFlowRule`里字段，从控制台保存规则后，`GatewayFlowRuleEntity`会转换成`GatewayFlowRule`储存。

如果直接从Nacos读取配置到应用端，json里可直接制定`intervalSec`，单位秒。

参考：#1398

**Comment by LoranMEI** [comment]
您好，感谢回答，用json进行配置的话是不是只支持1s多少次，其他时间单位必须都换算成秒然后设置每秒count值？

**Comment by sczyh30** [comment]
都支持，只不过把时间换算成秒（不是把通过量换成 QPS）配到 intervalSec 里面就好。

**Comment by 1327681842** [comment]
控制台保存到nacos中“间隔”是interval，所以不能从控制台保存？只能从nacos中手动配置intervalSec ？

**Comment by lanbabaJZS** [comment]
控制台有GatewayFlowRule这个类，且GatewayFlowRuleEntity中存在转到前者的方法 已经计算好了时间转换，自定义gateway规则保存发布逻辑的时候加上就可以了
