### ISSUE TITLE
metrics.log question

### ISSUE THREAD

**Issue by githubcheng2978** [alibaba/Sentinel#2210]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

 I  test sentinel, there was problem is  metric log 

i just set FlowRuler count  to 20， but when i see the metric log:

1621523929000|2021-05-20 23:18:49|abc|25|0|25|0|202|0|0|0
1621523930000|2021-05-20 23:18:50|abc|25|0|25|0|202|0|0|0
1621523931000|2021-05-20 23:18:51|abc|24|0|24|0|202|0|0|0
1621523932000|2021-05-20 23:18:52|abc|25|0|25|0|201|0|0|0
1621523933000|2021-05-20 23:18:53|abc|23|0|23|0|201|0|0|0
1621523934000|2021-05-20 23:18:54|abc|25|0|25|0|201|0|0|0
1621523935000|2021-05-20 23:18:55|abc|25|0|25|0|203|0|0|0
1621523936000|2021-05-20 23:18:56|abc|25|0|25|0|202|0|0|0
1621523937000|2021-05-20 23:18:57|abc|25|0|25|0|202|0|0|0
1621523938000|2021-05-20 23:18:58|abc|25|0|25|0|203|0|0|0
1621523939000|2021-05-20 23:18:59|abc|24|0|24|0|203|0|0|0
1621523940000|2021-05-20 23:19:00|abc|24|0|24|0|203|0|0|0
1621523941000|2021-05-20 23:19:01|abc|25|0|25|0|203|0|0|0
1621523942000|2021-05-20 23:19:02|abc|25|0|25|0|203|0|0|0

why is passQps equal to 25 or 24 continued 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

jdk1.8 mac os  sentinel.1.8.1 

code :
```java
public class Sentinel {

    private static final String KEY = "abc";

    private static void initFlowQpsRule() {
        List<FlowRule> rules = new ArrayList<FlowRule>();
        FlowRule rule1 = new FlowRule();
        rule1.setResource(KEY);
        rule1.setCount(20);
        rule1.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule1.setLimitApp("com.example.sentinel.Sentinel");
        rule1.setStrategy(1);
        rules.add(rule1);
        FlowRuleManager.loadRules(rules);
    }

    public static void main(String[] args) {
        initFlowQpsRule();
        for (int i = 0; i < 5; i++) {
            new Thread() {
                @Override
                public void run() {
                    while (true) {
                        Entry entry = null;
                        try {
                            entry = SphU.entry(KEY);
                            try {
                                sleep(200L);

                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        } catch (BlockException ex) {
                            ex.printStackTrace();
                        } finally {
                            if (entry != null) {
                                entry.exit();
                            }
                        }

                    }
                }
            }.start();
        }
    }
}

```

**Comment by cdfive** [comment]
第5列数值为0，说明没有发生限流。
代码里捕获了`BlockException`，看看有没有打印限流异常

**Comment by githubcheng2978** [comment]
> 第5列数值为0，说明没有发生限流。
> 代码里捕获了`BlockException`，看看有没有打印限流异常

控制台没有任何的异常～

**Comment by cdfive** [comment]
代码里配置限流模式是`rule1.setStrategy(1);`关联流量，但没有设置关联的资源`refResource`，并且demo里也只有一个资源key。
`rule1.setLimitApp("com.example.sentinel.Sentinel");` -> 注释掉
`rule1.setStrategy(1);` -> 改为`rule1.setStrategy(RuleConstant.STRATEGY_DIRECT);`
用直接模式运行再试试呢

**Comment by githubcheng2978** [comment]
> 代码里配置限流模式是`rule1.setStrategy(1);`关联流量，但没有设置关联的资源`refResource`，并且demo里也只有一个资源key。
> `rule1.setLimitApp("com.example.sentinel.Sentinel");` -> 注释掉
> `rule1.setStrategy(1);` -> 改为`rule1.setStrategy(RuleConstant.STRATEGY_DIRECT);`
> 用直接模式运行再试试呢

还是一样得 ，
```java
public class Sentinel {

    private static final String KEY = "abc";

    private static void initFlowQpsRule() {
        List<FlowRule> rules = new ArrayList<FlowRule>();
        FlowRule rule1 = new FlowRule();
        rule1.setResource(KEY);
        rule1.setCount(20);
        rule1.setGrade(RuleConstant.STRATEGY_DIRECT);
//        rule1.setLimitApp("com.example.sentinel.Sentinel");
        rule1.setStrategy(1);
        rules.add(rule1);
        FlowRuleManager.loadRules(rules);
    }

    public static void main(String[] args) {
        initFlowQpsRule();
        for (int i = 0; i < 5; i++) {
            new Thread() {
                @Override
                public void run() {
                    while (true) {
                        Entry entry = null;
                        try {
                            entry = SphU.entry(KEY);
                            try {
                                sleep(200L);

                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        } catch (BlockException ex) {
                            ex.printStackTrace();
                        } finally {
                            if (entry != null) {
                                entry.exit();
                            }
                        }

                    }
                }
            }.start();
        }
    }
}
```
log:

1621580362000|2021-05-21 14:59:22|abc|15|0|10|0|208|0|0|0
1621580363000|2021-05-21 14:59:23|abc|25|0|25|0|202|0|0|0
1621580364000|2021-05-21 14:59:24|abc|25|0|25|0|203|0|0|0
1621580365000|2021-05-21 14:59:25|abc|25|0|25|0|204|0|0|0
1621580366000|2021-05-21 14:59:26|abc|25|0|25|0|204|0|0|0
1621580367000|2021-05-21 14:59:27|abc|25|0|25|0|201|0|0|0
1621580368000|2021-05-21 14:59:28|abc|25|0|25|0|203|0|0|0
1621580369000|2021-05-21 14:59:29|abc|25|0|25|0|204|0|0|0
1621580370000|2021-05-21 14:59:30|abc|25|0|25|0|202|0|0|0
1621580371000|2021-05-21 14:59:31|abc|25|0|25|0|202|0|0|0
1621580372000|2021-05-21 14:59:32|abc|25|0|25|0|203|0|0|0
1621580373000|2021-05-21 14:59:33|abc|20|0|20|0|204|0|0|0
1621580374000|2021-05-21 14:59:34|abc|25|0|25|0|202|0|0|0
1621580375000|2021-05-21 14:59:35|abc|25|0|25|0|203|0|0|0
1621580376000|2021-05-21 14:59:36|abc|25|0|25|0|203|0|0|0
1621580377000|2021-05-21 14:59:37|abc|25|0|25|0|203|0|0|0
1621580378000|2021-05-21 14:59:38|abc|25|0|25|0|203|0|0|0
1621580379000|2021-05-21 14:59:39|abc|25|0|25|0|202|0|0|0
1621580380000|2021-05-21 14:59:40|abc|25|0|25|0|202|0|0|0
1621580381000|2021-05-21 14:59:41|abc|25|0|25|0|202|0|0|0
1621580382000|2021-05-21 14:59:42|abc|25|0|25|0|204|0|0|0
1621580383000|2021-05-21 14:59:43|abc|25|0|25|0|203|0|0|0
1621580384000|2021-05-21 14:59:44|abc|25|0|25|0|202|0|0|0
1621580385000|2021-05-21 14:59:45|abc|24|0|24|0|202|0|0|0
1621580386000|2021-05-21 14:59:46|abc|21|0|21|0|202|0|0|0
1621580387000|2021-05-21 14:59:47|abc|25|0|25|0|204|0|0|0

**Comment by githubcheng2978** [comment]
> 代码里配置限流模式是`rule1.setStrategy(1);`关联流量，但没有设置关联的资源`refResource`，并且demo里也只有一个资源key。
> `rule1.setLimitApp("com.example.sentinel.Sentinel");` -> 注释掉
> `rule1.setStrategy(1);` -> 改为`rule1.setStrategy(RuleConstant.STRATEGY_DIRECT);`
> 用直接模式运行再试试呢

按照这个方式改就可以了，metric.log: 
1621580952000|2021-05-21 15:09:12|abc|20|6071|20|0|203|0|0|0
1621580953000|2021-05-21 15:09:13|abc|20|6155|20|0|203|0|0|0
1621580954000|2021-05-21 15:09:14|abc|20|6564|20|0|203|0|0|0
1621580955000|2021-05-21 15:09:15|abc|20|6184|20|0|203|0|0|0
1621580956000|2021-05-21 15:09:16|abc|20|6162|20|0|203|0|0|0
1621580957000|2021-05-21 15:09:17|abc|20|6212|20|0|203|0|0|0
1621580958000|2021-05-21 15:09:18|abc|20|6478|20|0|204|0|0|0
1621580959000|2021-05-21 15:09:19|abc|20|6412|20|0|203|0|0|0
1621580960000|2021-05-21 15:09:20|abc|20|6495|20|0|204|0|0|0
1621580961000|2021-05-21 15:09:21|abc|20|6040|20|0|203|0|0|0
1621580962000|2021-05-21 15:09:22|abc|20|5893|20|0|203|0|0|0
1621580963000|2021-05-21 15:09:23|abc|20|6408|20|0|203|0|0|0
1621580964000|2021-05-21 15:09:24|abc|20|6248|20|0|203|0|0|0
1621580965000|2021-05-21 15:09:25|abc|20|6518|20|0|203|0|0|0
1621580966000|2021-05-21 15:09:26|abc|20|6224|20|0|203|0|0|0
1621580967000|2021-05-21 15:09:27|abc|20|6321|20|0|204|0|0|0
1621580968000|2021-05-21 15:09:28|abc|20|6167|20|0|204|0|0|0
1621580969000|2021-05-21 15:09:29|abc|20|6535|20|0|204|0|0|0
1621580970000|2021-05-21 15:09:30|abc|20|6244|20|0|204|0|0|0
1621580971000|2021-05-21 15:09:31|abc|20|6040|20|0|203|0|0|0
1621580972000|2021-05-21 15:09:32|abc|20|6408|20|0|204|0|0|0
1621580973000|2021-05-21 15:09:33|abc|20|6272|20|0|203|0|0|0
1621580974000|2021-05-21 15:09:34|abc|20|6376|20|0|204|0|0|0
1621580975000|2021-05-21 15:09:35|abc|20|6682|20|0|203|0|0|0
1621580976000|2021-05-21 15:09:36|abc|20|6485|20|0|203|0|0|0
1621580977000|2021-05-21 15:09:37|abc|20|6368|20|0|202|0|0|0
