### ISSUE TITLE
spring cloud gateway 集成sentinel,某些资源不记录metrices,不走GatewayFlowSlot这个。应用重启后又开始记录了

### ISSUE THREAD

**Issue by 123fuxiaohui** [alibaba/Sentinel#2224]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please illustrate your problem according to the issue template?

**Comment by sczyh30** [comment]
Any feedback?
