### ISSUE TITLE
请问可以将restful风格的post请求注册为资源吗？

### ISSUE THREAD

**Issue by JiCoM** [alibaba/Sentinel#2236]
@PostMapping("info")
    @SentinelResource(value = "info", blockHandler = "exceptionHandler")
public EpgInfoDTO getEpgInfoAll(@RequestBody @Validated DTO dTO) 
例如这种？我的service跟get请求都可以，但是这个post的失效了

**Comment by sczyh30** [comment]
无论用默认的 Spring Web adapter 还是注解方式自定义埋点均支持的，与 HTTP method 无关。
