### ISSUE TITLE
FlowRule中不能自定义时间窗口的长度吗？ParamFlowRule中不能对limitApp进行限流吗？

### ISSUE THREAD

**Issue by RuofeiSun** [alibaba/Sentinel#2238]
我们项目中需要对资源进行自定义的时间窗口限流，发现ParamFlowRule中的durationInSec参数可以实现。但是使用ParamFlowRule又无法对来源（limitApp）进行限制。如果想同时实现自定义窗口限流和来源限流这两种需求，有没有什么办法呀？

**Comment by sczyh30** [comment]
自定义埋点，将来源作为参数传入，再用热点规则即可。
