### ISSUE TITLE
sentinel 1.8控制台整合gateway无法显示nacos上配置的流控规则

### ISSUE THREAD

**Issue by CaiCaiXian** [alibaba/Sentinel#2239]
1、使用的版本：
<springboot.version>2.3.2.RELEASE</springboot.version>
<spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
sentinel-dashboard-1.8.0
2、问题描述：
dashboard中能读取到普通服务在nacos上配置的规则信息，但无法读取gateway模块的配置信息，且控制台中配置流控规则不生效，但nacos上配置的流控规则生效。猜测：sentinel dashboard整合gateway无效

3、配置信息

gateway中sentinel的配置信息
![image](https://user-images.githubusercontent.com/49951552/122367237-d6253380-cf8e-11eb-950d-986880dbe861.png)

控制台启动命令
java -Dserver.port=8718 -Dcsp.sentinel.dashboard.server=127.0.0.1:8718 -Dproject.name=cjx-sentinel-dashboard -Dcsp.sentinel.app.type=1 -jar sentinel-dashboard-1.8.0.jar

nacos上的流控规则（生效，在控制台配置则不生效）
![image](https://user-images.githubusercontent.com/49951552/122367491-0f5da380-cf8f-11eb-939d-a94fa6eeba72.png)

控制台内没有读取的规则
![image](https://user-images.githubusercontent.com/49951552/122367615-29978180-cf8f-11eb-8af3-7d793d75e7c3.png)
![image](https://user-images.githubusercontent.com/49951552/122367644-2f8d6280-cf8f-11eb-9d85-580aee6ad13f.png)

**Comment by CaiCaiXian** [comment]
加入了依然没有显示        
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-parameter-flow-control</artifactId>
        </dependency>

**Comment by CaiCaiXian** [comment]
尝试改造控制台实现推模式，然而只对普通服务生效，对网关无效

**Comment by CaiCaiXian** [comment]
急需帮助~

**Comment by EagleFlyInSky** [comment]
控制台界面是不一样的，网关项目得特殊配置

Sentinel 1.6.3 引入了网关流控控制台的支持，用户可以直接在 Sentinel 控制台上查看 API Gateway 实时的 route 和自定义 API 分组监控，管理网关规则和 API 分组配置。

在 API Gateway 端，用户只需要在原有启动参数的基础上添加如下启动参数即可标记应用为 API Gateway 类型：

# 注：通过 Spring Cloud Alibaba Sentinel 自动接入的 API Gateway 整合则无需此参数
```bash
-Dcsp.sentinel.app.type=1
```

添加正确的启动参数并有访问量后，我们就可以在 Sentinel 上面看到对应的 API Gateway 了。


也可以 classpath 添加  `sentinel.properties` 文件
```.properties
# 标记应用为 API Gateway 类型  网关类型
csp.sentinel.app.type=1
```

**Comment by CaiCaiXian** [comment]
> 控制台界面是不一样的，网关项目得特殊配置
> 
> Sentinel 1.6.3 引入了网关流控控制台的支持，用户可以直接在 Sentinel 控制台上查看 API Gateway 实时的 route 和自定义 API 分组监控，管理网关规则和 API 分组配置。
> 
> 在 API Gateway 端，用户只需要在原有启动参数的基础上添加如下启动参数即可标记应用为 API Gateway 类型：
> 
> # 注：通过 Spring Cloud Alibaba Sentinel 自动接入的 API Gateway 整合则无需此参数
> ```shell
> -Dcsp.sentinel.app.type=1
> ```
> 
> 添加正确的启动参数并有访问量后，我们就可以在 Sentinel 上面看到对应的 API Gateway 了。
> 
> 也可以 classpath 添加 `sentinel.properties` 文件
> 
> ```ini
> # 标记应用为 API Gateway 类型  网关类型
> csp.sentinel.app.type=1
> ```
不好意思沒有理解您的意思  

# 注：通过 Spring Cloud Alibaba Sentinel 自动接入的 API Gateway 整合则无需此参数 
意思是要去掉这个启动参数吗？尝试去掉后控制台就不是网关模式了

我目前使用的依赖是
 
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
 
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-parameter-flow-control</artifactId>
        </dependency>
可以再指导一下吗

**Comment by sczyh30** [comment]
Your rule-type is incorrect. You may refer to the document: https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel

**Comment by CaiCaiXian** [comment]
> Your rule-type is incorrect. You may refer to the document: https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel

我尝试将gw_flow改为gw-flow依然没有在控制台中读取，但使用接口
![image](https://user-images.githubusercontent.com/49951552/123209825-c14b2180-d4f3-11eb-8014-1b784561bf7e.png)
能获取到nacos中的值，猜测是因为8719为普通模块，8720才是网关模块所以没有显示出来，请问是我哪里配置错误了吗，导致网关模块显示了两个

**Comment by CaiCaiXian** [comment]
已解决，原来除了控制台需要加上Dcsp.sentinel.app.type=1，网关模块启动时也需要加上Dcsp.sentinel.app.type=1！
![image](https://user-images.githubusercontent.com/49951552/123224416-5eae5180-d504-11eb-90de-d29840c306a2.png)

**Comment by 1327681842** [comment]
又遇到这个问题吗？
我从控制台保存的网关限流规则，nacos中看到的“间隔”属性是interval而不是intervalSec，这个需要改页面吗？

**Comment by CaiCaiXian** [comment]
蔡已经收到了您的邮件，辛苦了。
