### ISSUE TITLE
为什么我设置了 statIntervalMs，熔断却没有等到一个统计周期呢？

### ISSUE THREAD

**Issue by xpwi** [alibaba/Sentinel#2240]
我运行了降级的 demo，我发现设置或修改 statIntervalMs 参数，没有到达一个统计时长就打开了熔断，是我对这个参数理解有误吗？
版本：1.8.2
DEMO：SlowRatioCircuitBreakerDemo

**Comment by sczyh30** [comment]
统计时长并非到达这个时长才会熔断，而是说最近统计时长内的统计 到达设置的阈值 就生效。
