### ISSUE TITLE
dashboard部署至k8s | Sentinel dashboard K8s deployment/Docker image

### ISSUE THREAD

**Issue by queenns** [alibaba/Sentinel#2244]
有官方的镜像及yaml文档吗(文档中没有找到)？需要私人自己做吗？

**Comment by sczyh30** [comment]
目前没有官方的 Docker 镜像，建议根据自己的需要改造 dashboard 后封装镜像。

---

Official Sentinel dashboard Docker image is not offered till now. You may refactor the dashboard according to your demand and build your own image.

**Comment by queenns** [comment]
> 目前没有官方的 Docker 镜像，建议根据自己的需要改造 dashboard 后封装镜像。
> 
> Official Sentinel dashboard Docker image is not offered till now. You may refactor the dashboard according to your demand and build your own image.

好的，多谢
