### ISSUE TITLE
如何关闭metrics文件存储 | How to disable metric logs?

### ISSUE THREAD

**Issue by luffy0223** [alibaba/Sentinel#2246]
sentinel-dashboard数据展示依赖于metrics文件，但sentinel-core核心功能并不需要metrics，并且metrics的落盘对磁盘资源消耗较大，是否将存储metrcis文件从sentinel-core模块中分离，或者增加开关支持开启/关闭metrics文件存储会更好？

**Comment by brotherlu-xcq** [comment]
现在可以在配置中设置metric的刷新频率控制，参数：`csp.sentinel.metric.flush.interval`，设置为0时不会进行metric的落盘。可以看具体的issue，#1867。
