### ISSUE TITLE
1.8.1中降级规则-慢调用比例中的参数设置异常

### ISSUE THREAD

**Issue by huchongwen** [alibaba/Sentinel#2249]
慢调用比例中的比例阈值不能设置为小数，设置为小数保存会自动置为1。
但是最大RT就可以设置为小数。
![image](https://user-images.githubusercontent.com/57609381/123063713-3e1cc380-d440-11eb-8e13-d4fc71aa38d3.png)

异常比例的比例阈值就可以设置小数并保存成功。
![image](https://user-images.githubusercontent.com/57609381/123064014-7de3ab00-d440-11eb-8206-490d1b28f1d8.png)

异常数的异常数设置居然也能设置为小数并且保存成功，是否有点不合理？
![image](https://user-images.githubusercontent.com/57609381/123064189-a23f8780-d440-11eb-9533-5d5de24d3351.png)

**Comment by sczyh30** [comment]
请确保应用侧的 Sentinel 版本 >= 1.8.0，否则新的一些字段无效。

**Comment by NevermoreToo** [comment]
我看到好几个人都遇到同样的问题了，其实不止这一个参数是这样，最小请求数和统计时长这2个参数设置后也没用，楼主你可以看看我的issue，https://github.com/alibaba/Sentinel/issues/2270

**Comment by FahaxikiLz** [comment]
> 请确保应用侧的 Sentinel 版本 >= 1.8.0，否则新的一些字段无效。

确认版本 >= 1.8.0，确实有此问题
