### ISSUE TITLE
sentinal是否支持rocketmq推的消费模式 | Does Sentinel support push mode for MQ?

### ISSUE THREAD

**Issue by sunwuxiang** [alibaba/Sentinel#2252]
sentinal是否支持rocketmq推的消费模式？

虽然rocketmq的推也是拉，但是我们之前的mq都是推的消费模式，再修改起来比较麻烦，而且担心推的改成拉的之后，没有队列预期效率会降低

想问一下，sentinal是否有支持rocketmq推的消费限流demo

**Comment by sczyh30** [comment]
无论是什么模式，什么类型的 MQ，都可以利用 Sentinel 的自定义埋点来实现希望的效果。
