### ISSUE TITLE
sentinel客户端打印大量日志，怎么屏蔽

### ISSUE THREAD

**Issue by westcows00481** [alibaba/Sentinel#2255]
sentinel客户端打印大量日志，怎么屏蔽

**Comment by sczyh30** [comment]
For metric logs, you may refer to https://github.com/alibaba/Sentinel/issues/2246
For other kinds of logs, it's not supported yet.

**Comment by westcows00481** [comment]
说的是sentinel-record日志， 阿里大神有点敬业精神啊， issue没解决不能直接关了啊。

**Comment by sczyh30** [comment]
sentinel-record.log 正常情况下不会打印很多，除非有错误的情况。如果你们 record log 日志量大，建议看下具体是哪些内容。

**Comment by westcows00481** [comment]
从目前来看，这里的日志对我们帮助不大， 没太大意义， 就希望直接屏蔽。

**Comment by westcows00481** [comment]
springcloud 都有设置OFF级别屏蔽日志能力， 这种特性不能搞丢了哈

**Comment by sczyh30** [comment]
目前的话可以自己搞个空的 Logger SPI 实现替代掉默认的，可以参考 https://github.com/alibaba/Sentinel/wiki/Logs#record-log
