### ISSUE TITLE
API Gateway flow control | Spring cloud gateway sentinel上如何进行集群限流

### ISSUE THREAD

**Issue by anryHan** [alibaba/Sentinel#2262]

**Comment by sczyh30** [comment]
Gateway cluster flow control is not supported yet.

**Comment by diaomaoblue** [comment]
> Gateway cluster flow control is not supported yet.

所以我用gateway整合sentinel时候界面上没有集群流控按钮，即使我修改了源码sidebar.html使它显示也没用，因为本身就不支持集群是吗？
