### ISSUE TITLE
sentinel客户端获取不到nacos规则文件怎么回事

### ISSUE THREAD

**Issue by mdxlCJ** [alibaba/Sentinel#2267]
本地环境
nacos1.4.1 
com.alibaba.cloud 系列版本2.2.3.RELEASE
spring.cloud Hoxton.SR8
集成sentinel，此刻版本1.8.0
sentinel客户端项目启动成功，但是启动日志总是警告：
 c.a.c.s.d.converter.SentinelConverter    : converter can not convert rules because source is empty
我都服了，我看其他博客说是jdk版本的问题，我真他么是醉了，求官方给我最准确答案

`server:
  port: 8084
spring:
  application:
    name: nacos-sentinel
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 127.0.0.1:8848
        group: dev
        namespace: 612669fb-68e3-4652-a0de-a658e350b897
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 612669fb-68e3-4652-a0de-a658e350b897
        group: dev
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        dashboard: localhost:8085
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        port: 8719
        # clientIp: 10.210.8.156
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            dataId: nacos-sentinel-flow-rules.json
            namespace: 612669fb-68e3-4652-a0de-a658e350b897
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow`
nacos配置规则也配置好了，就是不行，官方能简单一些么，搞得那么复杂，非得让买AHAS

**Comment by wangs0627** [comment]
Properties properties = new Properties();
        properties.put(PropertyKeyConst.SERVER_ADDR, remoteAddress);
        properties.put(PropertyKeyConst.NAMESPACE, NACOS_NAMESPACE_ID);

        ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>(properties, groupId, dataId,
                source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
                }));
        FlowRuleManager.register2Property(flowRuleDataSource.getProperty());

别用配置文件方式配置nacos持久化，采用这种方式搞，这是官方示例代码

**Comment by anryHan** [comment]
c.a.c.s.d.converter.SentinelConverter : converter can not convert rules because source is empty 
这是没找到文件啊，nacos-sentinel-flow-rules.json 你的nacos上有这文件吗？
