### ISSUE TITLE
sentinel1.8.1版本，Dashboad控制台设置并保存降级规则的参数无效

### ISSUE THREAD

**Issue by NevermoreToo** [alibaba/Sentinel#2270]
开发者大佬们你们好：

在sentinel1.8.1版本中，我以jar包的形式启动了sentinel的服务，在dashboad控制台中设置降级规则时，发现某些参数没有保存成功，具体情况如下：
1. 降级规则——新增降级规则，熔断策略选“慢调用比例”时，无论设置的值是多少，保存后并再次查看后，“比例阈值”、“最小请求数”、“统计时长”这三个参数的值都是“1”、“5”、“1000”
2. 降级规则——新增降级规则，熔断策略选“异常比例”时，无论设置的值是多少，保存后并再次查看后，“最小请求数”、“统计时长”的值都是“5”、“1000”
3. 降级规则——新增降级规则，熔断策略选“异常比例”时，无论设置的值是多少，保存后并再次查看后，“最小请求数”、“统计时长”的值都是“5”、“1000”

我在观看老版本的sentinel学习视频时，视频里的控制台中并不能配置这些参数，而且视频里对这些规则的描述的默认值都是上述情况的值。请问这是啥情况，这些参数是压根就配不了吗，只是能显式的让我们看到吗，官网相关的文档中也没有特别说明。

**Comment by sczyh30** [comment]
请确保应用端的 Sentinel 版本 >= 1.8.0。熔断规则部分配置仅在 1.8.0 及以上版本支持。

**Comment by NevermoreToo** [comment]
> 请确保应用端的 Sentinel 版本 >= 1.8.0。熔断规则部分配置仅在 1.8.0 及以上版本支持。

我就是启动的1.8.1版本的Sentinel的jar包呀 o(╥﹏╥)o

**Comment by NevermoreToo** [comment]
![image](https://user-images.githubusercontent.com/30260112/124124043-8d02d280-daaa-11eb-9039-05f4fda994d7.png)

**Comment by NevermoreToo** [comment]
![image](https://user-images.githubusercontent.com/30260112/124124341-e4a13e00-daaa-11eb-80a1-7d2fe9b151fa.png)
![image](https://user-images.githubusercontent.com/30260112/124124376-ee2aa600-daaa-11eb-97ce-f286c41cacc7.png)

**Comment by NevermoreToo** [comment]
如上楼图所示，图1新增了降级规则，点了“新增”保存后，再编辑该降级规则，显示就是图二了。
我一共就启动了3个节点的集群nacos，1个测试的微服务，以及这个sentinel的jar包

**Comment by zhanghan2585** [comment]
statIntervalMs  这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1

**Comment by NevermoreToo** [comment]
> statIntervalMs 这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1

还有最小请求数也一直都是5...你也是遇到了一样的问题吗，还是说在回答我o(╥﹏╥)o

**Comment by zhanghan2585** [comment]
> > statIntervalMs 这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1
> 
> 还有最小请求数也一直都是5...你也是遇到了一样的问题吗，还是说在回答我o(╥﹏╥)o

同问，等待大佬解决

**Comment by NevermoreToo** [comment]
> > > statIntervalMs 这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1
> > 
> > 
> > 还有最小请求数也一直都是5...你也是遇到了一样的问题吗，还是说在回答我o(╥﹏╥)o
> 
> 同问，等待大佬解决

找到原因了，原来开发者说的应用端版本保持在1.8.0以上指的是被sentinel监控的服务，而不仅仅是sentinel控制台本身。。。把引用sentinel的jar包的相关pom配置改成1.8.0以上版本就好了

**Comment by zhanghan2585** [comment]
> > > > statIntervalMs 这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1
> > > 
> > > 
> > > 还有最小请求数也一直都是5...你也是遇到了一样的问题吗，还是说在回答我o(╥﹏╥)o
> > 
> > 
> > 同问，等待大佬解决
> 
> 找到原因了，原来开发者说的应用端版本保持在1.8.0以上指的是被sentinel监控的服务，而不仅仅是sentinel控制台本身。。。把引用sentinel的jar包的相关pom配置改成1.8.0以上版本就好了

![image](https://user-images.githubusercontent.com/18066720/124527319-021e3100-de38-11eb-806d-5ffcd47e19f4.png)
是这个版本吗？

**Comment by sczyh30** [comment]
SCA 对应依赖版本可以参考版本说明：https://github.com/alibaba/spring-cloud-alibaba/wiki/版本说明

**Comment by NevermoreToo** [comment]
> > > > > statIntervalMs 这个参数 更改无效 永远都是1000 ms， slowRatioThreshold 这个也无效 一直都是1
> > > > 
> > > > 
> > > > 还有最小请求数也一直都是5...你也是遇到了一样的问题吗，还是说在回答我o(╥﹏╥)o
> > > 
> > > 
> > > 同问，等待大佬解决
> > 
> > 
> > 找到原因了，原来开发者说的应用端版本保持在1.8.0以上指的是被sentinel监控的服务，而不仅仅是sentinel控制台本身。。。把引用sentinel的jar包的相关pom配置改成1.8.0以上版本就好了
> 
> ![image](https://user-images.githubusercontent.com/18066720/124527319-021e3100-de38-11eb-806d-5ffcd47e19f4.png)
> 是这个版本吗？

不止是这个，这个只是sentinel来适配springCloud的jar包，我是通过引用spring-cloud-alibaba-dependencies来引用sentinel的相关jar包的，相关的版本可以参考楼下开发者给出的链接，比如我的springCloud版本是Hoxton的，就用如下的版本来引用sentinel
![image](https://user-images.githubusercontent.com/30260112/124563481-a624ce00-de72-11eb-93c4-62b80e7d1eba.png)
