### ISSUE TITLE
sentinel 控制台启动后，机器列表展示 客户端应用 ip 不对

### ISSUE THREAD

**Issue by hxlzpnyist** [alibaba/Sentinel#2273]
![image](https://user-images.githubusercontent.com/4377393/124074454-16e47880-da76-11eb-9217-12ad7e6f45c0.png)

本地控制台启动后，调用了下本地客户端应用，机器列表展示的 ip 地址为 172.22.29.98，但实际本机 ip 为 172.22.31.88

![image](https://user-images.githubusercontent.com/4377393/124074704-780c4c00-da76-11eb-93ba-baaf6c598e91.png)

没有开启虚拟网卡

![image](https://user-images.githubusercontent.com/4377393/124074799-970ade00-da76-11eb-87b3-646dcc8262ce.png)

没发现 172.22.29.98 这个ip 从哪来的

**Comment by hxlzpnyist** [comment]
已解决  本地机器名 不对，bogon 改为 localhost 就好了

**Comment by faraway12** [comment]
请教一下本地机器名如何影响到ip不一致。最近也遇到这个问题
