### ISSUE TITLE
sentinel-dashboard 什么时候推模式下能完全支持nacos持久化 并且只实现了flow的规则持久化，降级和其他规则======== 看源代码只实现了部分

### ISSUE THREAD

**Issue by xg704863664** [alibaba/Sentinel#2277]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by ZhuBobi** [comment]
这个持久化我做了，目前只实现了nacos下的flow,degrade,authority,paramflow,system，可以参考 https://github.com/ZhuBobi/sentinel-dashboard/tree/main/sentinel-dashboard

**Comment by sczyh30** [comment]
Hi, there are a few existing PRs and you may choose what you need: https://github.com/alibaba/Sentinel/pulls?q=is%3Apr+is%3Aopen+label%3Aarea%2Fdashboard
