### ISSUE TITLE
同一资源下 限流规则 和 熔断降级规则 同时存在吗

### ISSUE THREAD

**Issue by hxlzpnyist** [alibaba/Sentinel#2279]
如题

**Comment by sczyh30** [comment]
Sentinel 支持同个资源配置多条规则。

---

It's supported to add multiple different rules for a single resource.

**Comment by hxlzpnyist** [comment]
> Sentinel 支持同个资源配置多条规则。
> 
> It's supported to add multiple different rules for a single resource.

您好 在问下 ，同个资源的意思是指  定义多个规则时 resource 可以是相同值么 ？ 譬如

`List<DegradeRule> rules = new ArrayList<>();
        DegradeRule rule = new DegradeRule("test")
                .setGrade(CircuitBreakerStrategy.ERROR_RATIO.getType())
                // Set ratio threshold to 50%.
                // 异常比例 50%
                .setCount(0.3d)
                // 统计时长 10s
                .setStatIntervalMs(10000)
                // 最小请求数 10
                .setMinRequestAmount(10)
                // Retry timeout (in second)
                // 熔断时长
                .setTimeWindow(10);
        rules.add(rule);
        DegradeRuleManager.loadRules(rules);

        List<FlowRule> flowRules = new ArrayList<>();

        FlowRule flowRule = new FlowRule();

        flowRule.setResource("test");
        flowRule.setGrade(RuleConstant.FLOW_GRADE_QPS);
        flowRule.setCount(20);

        flowRules.add(flowRule);

        FlowRuleManager.loadRules(flowRules);`

**Comment by hxlzpnyist** [comment]
> > Sentinel 支持同个资源配置多条规则。
> > It's supported to add multiple different rules for a single resource.
> 
> 您好 在问下 ，同个资源的意思是指 定义多个规则时 resource 可以是相同值么 ？ 譬如
> 
> ```
> List<DegradeRule> rules = new ArrayList<>();
>         DegradeRule rule = new DegradeRule("test")
>                 .setGrade(CircuitBreakerStrategy.ERROR_RATIO.getType())
>                 // Set ratio threshold to 50%.
>                 // 异常比例 50%
>                 .setCount(0.3d)
>                 // 统计时长 10s
>                 .setStatIntervalMs(10000)
>                 // 最小请求数 10
>                 .setMinRequestAmount(10)
>                 // Retry timeout (in second)
>                 // 熔断时长
>                 .setTimeWindow(10);
>         rules.add(rule);
>         DegradeRuleManager.loadRules(rules);
> 
>         List<FlowRule> flowRules = new ArrayList<>();
> 
>         FlowRule flowRule = new FlowRule();
> 
>         flowRule.setResource("test");
>         flowRule.setGrade(RuleConstant.FLOW_GRADE_QPS);
>         flowRule.setCount(20);
> 
>         flowRules.add(flowRule);
> 
>         FlowRuleManager.loadRules(flowRules);
> ```
> 
> test resource 下配置了 一个限流规则也配了熔断降级规则

本地测试了 好使
