### ISSUE TITLE
Why metrics in StatisticNode are not reused in circuit breakers | 为何熔断器里面不使用StatisticsNode中的统计信息，而单独统计

### ISSUE THREAD

**Issue by woshioosm** [alibaba/Sentinel#2282]
在1.6.1版本中使用的StatisticsNode的统计信息，有分钟级的滚动窗口
而现在 ExceptionCircuitBreaker 为何要再次单独进行统计（LeapArray<SimpleErrorCounter> stat），而且窗口sampleCount为1
请问这样做的好处是什么？ 感觉升级后 测试熔断的准确性不如以前

**Comment by sczyh30** [comment]
单独统计是为了支持任意统计时长 (support arbitrary statistic duration)。
