### ISSUE TITLE
Customize IP parsing logic in gateway flow control | 请问gateway中参数限流设置策略parseStrategy可以自定义吗？

### ISSUE THREAD

**Issue by JiCoM** [alibaba/Sentinel#2283]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Could you please illustrate your demand?

**Comment by JiCoM** [comment]
我想在网关中自定义IP限流



---原始邮件---
发件人: "Eric ***@***.***&gt;
发送时间: 2021年7月8日(周四) 晚上7:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/Sentinel] 请问gateway中参数限流设置策略parseStrategy可以自定义吗？ (#2283)




 
Could you please illustrate your demand?

**Comment by JiCoM** [comment]
> Could you please illustrate your demand?

现在有的gateway限流的Client-IP获取IP方式getRomoteAddress与我的需求不符合，我想要用自己提供的IP，这个IP不是一个单一二点值，需要用一个函数来判断处理，所以希望重写ClientIP策略的实现

**Comment by sczyh30** [comment]
这种场景看一下 是不是可以处理后放到某个 header 中，用 header 模式来搞。

**Comment by JiCoM** [comment]
> 这种场景看一下 是不是可以处理后放到某个 header 中，用 header 模式来搞。
我们考虑过，header与url参数等，但我们的获取ip的逻辑不能仅通过单一参数获取，最终选择整体替换掉GatewayFilter，因为发现GateWayFIlter部分的代码里ParamParser是final的，所以只能整体替换，为什么ParamParser代码里当时设计是final，这样无法通过替换ParamParser添加自定义策略，减少了可扩展？

**Comment by JiCoM** [comment]
> 这种场景看一下 是不是可以处理后放到某个 header 中，用 header 模式来搞。

这个方案生效了，此issue可以close了
