### ISSUE TITLE
is sentinel console support spring boot application configuration?

### ISSUE THREAD

**Issue by anjia0532** [alibaba/Sentinel#229]
from https://github.com/alibaba/Sentinel/wiki/Dashboard#32-configure-dashboard-ip-address is only support jvm args.
and how to custom the log path?

**Comment by anjia0532** [comment]
英语太烂，可能描述的不太清楚，还是用中文再补充一下。
sentinel支持包括spring boot ,nacos等，出于兼容性考虑，使用jvm参数确实更通用，但是使用application配置方式，在基于spring boot的情景下会更方便管理（比如，配合nacos，apollo，spring config进行统一配置，管理），所以，是否可以保留jvm的情况下，增加application方式

另外，https://github.com/alibaba/Sentinel/wiki/%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9#%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F 说除了project.name外，其余参数支持从`${user_home}/logs/csp/${project.name}.properties` 配置，但是管理起来不太方便

而且，好像`${user_home}/logs/csp/`是硬编码的，不支持变更，后边会考虑改成可配置么？

**Comment by anjia0532** [comment]
ref https://github.com/alibaba/Sentinel/pull/72

**Comment by anjia0532** [comment]
@shuohao 目前官方的建议是用spring cloud alibaba或者你也可以参考spring cloud alibaba自己修改。

**Comment by shuohao** [comment]
> @shuohao 目前官方的建议是用spring cloud alibaba或者你也可以参考spring cloud alibaba自己修改。

目前cloud alibaba只是可配置project.name并不能配置日志目录，日志目录路径等spring加载完自定义配置设置System.setProperty前就可能已经被初始化了 再设置也没用了
