### ISSUE TITLE
源码编译后与开源二进制包运行结果不一致

### ISSUE THREAD

**Issue by bingSea** [alibaba/Sentinel#2294]
在release页面(https://github.com/alibaba/Sentinel/releases):
(https://github.com/alibaba/Sentinel/archive/refs/tags/1.8.2.zip) 这里下载的源码编译后运行，控制台无法看到运行的程序 ，(https://github.com/alibaba/Sentinel/releases/download/1.8.2/sentinel-dashboard-1.8.2.jar) 这里下载的二进制文件直接运行，控制台可以看到运行的程序，两者都是单机版，内存保存限流规则

两者都有设置参数(-Dcsp.sentinel.dashboard.server=xxx:xxx -Dproject.name=xxx)，且值不同

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查
