### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 它的git 源码地址是多少，我怎么搜索不到呢？

### ISSUE THREAD

**Issue by su787910081** [alibaba/Sentinel#2299]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by brotherlu-xcq** [comment]
可以参照这里https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme.md

**Comment by sczyh30** [comment]
https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel
