### ISSUE TITLE
Sentinel Dashboard page display problem

### ISSUE THREAD

**Issue by odbozhou** [alibaba/Sentinel#231]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
When resource name length is too long, The name will cover statistical data.
![sentinel proble](https://user-images.githubusercontent.com/14222167/47960104-cfd92780-e02f-11e8-9729-2d994930499b.png)

### Describe what you expected to happen
Resource names do not affect statistics

### How to reproduce it (as minimally and precisely as possible)

1. When package name is too long , The problem will reproduce.

### Tell us your environment
Firefox and Chrome have the same problem.

**Comment by sczyh30** [comment]
Thanks for reporting! We'll fix it.
