### ISSUE TITLE
流控规则持久化问题

### ISSUE THREAD

**Issue by aoen1213** [alibaba/Sentinel#2310]
我是将规则持久化到apollo上。
在流控规则进去->新增流控规则，这时候前端发送的请求是/v2/flow/rule，新增的规则可以实例化到apollo中。
但是如果从  簇点链路进去，然后点击流控规则，进去新增发送的请求是v1/flow/rule，这时候新增的规则不能实例化到apollo中。

**Comment by sczyh30** [comment]
可以自行进行改造，统一替换接口。

**Comment by a412576672** [comment]
同该问题，请问解决了吗？
