### ISSUE TITLE
官方能否提供一个seninel-dashboard-nacos项目

### ISSUE THREAD

**Issue by sundong1982** [alibaba/Sentinel#2312]
每次sentinel版本更新都要自己用源码去seninel-dashboard下改一个项目，挺麻烦的。

**Comment by sczyh30** [comment]
There are a few existing PRs and you may choose what you need: https://github.com/alibaba/Sentinel/pulls?q=is%3Apr+is%3Aopen+label%3Aarea%2Fdashboard

**Comment by sundong1982** [comment]
目前把整个github搜完了，只找到一些旧版本支持nacos储存限流规则的项目。官方添加一个支持nacos储存限流规则的项目，因为熟悉每次更新的细节并没有太大工作量。
