### ISSUE TITLE
sentinel自定义日志输出规则

### ISSUE THREAD

**Issue by bomlsy** [alibaba/Sentinel#2314]
sentinel能否通过在logback里配置的方式，自定义日志输出规则？
1.向下面这样配置logger节点似乎并不能获取到sentinel的日志？
```
    <logger name="com.alibaba.csp.sentinel" level="INFO" additivity="false">
        <appender-ref ref="FILE-sentinel"/>
    </logger>
```

2.或者参照 https://github.com/alibaba/Sentinel/wiki/Logs#record-log这个解决方案配置logger节点仍然不生效，打印出来的日志是空的，似乎是也没能获取到record类型的日志
```
    <logger name="com.alibaba.csp.sentinel.logging.slf4j.sentinelRecordLogger" level="INFO" additivity="false">
        <appender-ref ref="FILE-sentinel"/>
    </logger>
```

目前需要统一把项目的日志按照规则输出到指定地址，请问sentinel是否支持通过logback配置？
急急急！

**Comment by brotherlu-xcq** [comment]
现在内置的日志输出可以参考https://sentinelguard.io/zh-cn/docs/logs.html。但是如果你想要这种定制的输出的话，可以通过SPI的方式将内置的logger替换为logback的，然后再来配置对应的xml文件。

**Comment by bomlsy** [comment]
> 现在内置的日志输出可以参考[https://sentinelguard.io/zh-cn/docs/logs.html。但是如果你想要这种定制的输出的话，可以通过SPI的方式将内置的logger替换为logback的，然后再来配置对应的xml文件。](https://sentinelguard.io/zh-cn/docs/logs.html%E3%80%82%E4%BD%86%E6%98%AF%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E8%A6%81%E8%BF%99%E7%A7%8D%E5%AE%9A%E5%88%B6%E7%9A%84%E8%BE%93%E5%87%BA%E7%9A%84%E8%AF%9D%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87SPI%E7%9A%84%E6%96%B9%E5%BC%8F%E5%B0%86%E5%86%85%E7%BD%AE%E7%9A%84logger%E6%9B%BF%E6%8D%A2%E4%B8%BAlogback%E7%9A%84%EF%BC%8C%E7%84%B6%E5%90%8E%E5%86%8D%E6%9D%A5%E9%85%8D%E7%BD%AE%E5%AF%B9%E5%BA%94%E7%9A%84xml%E6%96%87%E4%BB%B6%E3%80%82)

你好，我已经通过官方给出的方案配置了我的logback，但似乎依然不能生效，不知道问题出在了哪里
我把我配置logger的代码更新到issue中了

**Comment by bomlsy** [comment]
> 现在内置的日志输出可以参考 https://sentinelguard.io/zh-cn/docs/logs.html 。但是如果你想要这种定制的输出的话，可以通过SPI的方式将内置的logger替换为logback的，然后再来配置对应的xml文件。

你好，请问这个要怎么替换啊？

**Comment by brotherlu-xcq** [comment]
你可以参照源码里面sentinel-logging的实现，继承sentinel-core里面logger用SPI的方式加载。
![image](https://user-images.githubusercontent.com/25661357/127975197-a83477c7-f064-4eca-9efa-d38a66a69f26.png)

**Comment by bomlsy** [comment]
> 你可以参照源码里面sentinel-logging的实现，继承sentinel-core里面logger用SPI的方式加载。
> ![image](https://user-images.githubusercontent.com/25661357/127975197-a83477c7-f064-4eca-9efa-d38a66a69f26.png)
你好，之前没有接触过SPI，查资料也没找到看起来靠谱的，想再请问一下，我目前是已经用maven把官方提供的这个包导入到我的项目里，我能直接在我项目的resource下像这样弄好META-INF，和com.alibaba.csp.sentinel.log.Logger那个文件，然后用官方提供的这个RecordLogLogger配置到logback里吗？

**Comment by bomlsy** [comment]
> 你可以参照源码里面sentinel-logging的实现，继承sentinel-core里面logger用SPI的方式加载。
> ![image](https://user-images.githubusercontent.com/25661357/127975197-a83477c7-f064-4eca-9efa-d38a66a69f26.png)

已经按照这个方案解决了我的问题了，太谢谢你啦！
