### ISSUE TITLE
Transport InitFunc SPI absent because of shade plugin | SPI文件同名导致maven-shade-plugin打包之后无法发送心跳

### ISSUE THREAD

**Issue by bingSea** [alibaba/Sentinel#2316]
该问题发生在我用maven打包之后调用请求不发送心跳，排查时发现两个jar包（com.alibaba.csp:sentinel-core:1.8.2与com.alibaba.csp:sentinel-transport-common:1.8.2）中出现了同样名字的spi services文件：com.alibaba.csp.sentinel.init.InitFunc，如下图所示：
![image](https://user-images.githubusercontent.com/12644274/128305317-e934484b-fb46-40ee-8c80-151b281ee4b3.png)

因为我mave用的是org.apache.maven.plugins:maven-shade-plugin:3.2.1方式打包，**打出来的是fat jar**，这样sentinel-core内的service文件加载完之后，sentinel-transport-common包中同名的文件就不加载了，这样SpiLoader就无法加载到心跳类（com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc），最后我采取的办法是把两个文件内的内容合并，然后创建一个同名的service文件com.alibaba.csp.sentinel.init.InitFunc，加到我项目的src/main/resources/META-INF/services目录下，利用项目class文件先于jar包class文件加载的原则，最后只保留我创建的文件，如下图所示：
![image](https://user-images.githubusercontent.com/12644274/128314152-56124eeb-19e1-48de-ab0b-eda619a25c2d.png)

经过上述操作之后，心跳就可以正常发送了，是不是考虑后续版本优化下，或者有没有其它更好的处理方式在此指引一下，感谢！

**Comment by cdfive** [comment]
maven-shade-plugin插件默认会覆盖同名文件，内容合并利用加载顺序是一种解决思路，
另外可考虑通过配置插件支持的`AppendingTransformer`属性来解决多个同名文件覆盖问题。
参考issue：#2215 
参考文档： [http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html](http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html)

**Comment by bingSea** [comment]
> maven-shade-plugin插件默认会覆盖同名文件，内容合并利用加载顺序是一种解决思路，
> 另外可考虑通过配置插件支持的`AppendingTransformer`属性来解决多个同名文件覆盖问题。
> 参考issue：#2215
> 参考文档： http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html

嗯，`AppendingTransformer`更专业！
