### ISSUE TITLE
热点参数中包含未被@SentinelResource注解标记的资源时，修改会空指针问题

### ISSUE THREAD

**Issue by zc521106** [alibaba/Sentinel#2317]
当热点参数中包含未被@SentinelResource注解标记的资源时，如果修改这个资源会包空指针异常，表现出来最大的问题就是，显示修改成功，但是热点参数的值还是显示原来的值，但是实际上这个值在后面持久化的逻辑中已经被生效了，内存里却未生效，如果热点参数规则列表中只要包含一个未被标记的资源，修改所有的规则都会出现这种问题

根源是下面代码中这个for循环：

com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowRuleManager.RulePropertyListener#aggregateAndPrepareParamRules：
```
         private Map<String, List<ParamFlowRule>> aggregateAndPrepareParamRules(List<ParamFlowRule> list) {
            ...
            for (Map.Entry<String, List<ParamFlowRule>> entry : PARAM_FLOW_RULES.entrySet()) {
                ...
                for (ParamFlowRule rule : oldRuleList) {
                     // 未被标记的资源 调用 getParamMetricForResource 方法返回null
                    ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule);
                }
            }
            return newRuleMap;
        }
```

**Comment by sczyh30** [comment]
https://github.com/alibaba/Sentinel/blob/436a88562ef3c475d32e38b9820fe1a43061f30b/sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowRuleManager.java#L121-L150

This has been fixed since Sentinel 1.8.1.

**Comment by zc521106** [comment]
ok thanks
