### ISSUE TITLE
Shared session is not supported | k8s集群下sentinel-dashboard多节点，单点登录无效。

### ISSUE THREAD

**Issue by sundong1982** [alibaba/Sentinel#2319]
k8s用的nodeport类型的service开放端口，浏览器用的ip+port打开，试过1.8.0  1.8.1 1.8.2，任意操作 一定几率退出到登录界面。

**Comment by sczyh30** [comment]
Shared session is not supported for the Sentinel dashboard. Contributions are welcomed.
