### ISSUE TITLE
控制台问题实时监控问题

### ISSUE THREAD

**Issue by dalianghe** [alibaba/Sentinel#232]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在测试sentinel时，控制台部署在一台机器上，客户端部署在另外一台集器上，控制台无法显示客户端的实时监控数据。
把控制台也注册为客户端的话，可以看控制台应用的监控数据，也就是说，控制台实时数据只能显示跟控制台在同一台机器上的数据？如何显示客户端的实时监控数据？

### Describe what you expected to happen
控制台程序能显示不同机器上客户端的实时数据

### How to reproduce it (as minimally and precisely as possible)

1. 控制台dashboard部署在一台服务器上，并同时注册自己为客户端，jvm_opts为：
-Dproject.name=dashboard-test -Dcsp.sentinel.dashboard.server=localhost:8080 -Dcsp.sentinel.api.port=8002
2. 客户端部署在另一台服务器上（本地），jvm_opts为：
-Dproject.name=dashboard-client -Dcsp.sentinel.dashboard.server=控制台IP:8080 -Dcsp.sentinel.api.port=8003

### Tell us your environment
服务器为本地虚拟机安装的centos7，客户端为开发IDE。

**Comment by sczyh30** [comment]
可以参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5) 进行排查。

**Comment by dalianghe** [comment]
应该是时间精度问题，控制台服务器时间比客户端机器快10多秒，导致控制台查询实时数据时查询不到客户端的实时数据。错略看了下代码，查询实时数据是按时间戳查询的。
有理解不对的地方还望指正，希望我遇到的问题对有类似问题的同学有帮助

**Comment by caizi12** [comment]
我也遇到这个问题了，最近迁移到k8s上出现的，客户端和服务端时间是一致的，网络也是通的，单独请求该接口也能拿到数据， /metric?startTime=1684203612000&endTime=1684203618000&refetch=false 但在控制台就是不显示
