### ISSUE TITLE
sentinel使用aliyun微服务引擎MSE时access_key不生效，导致访问nacos配置无权限

### ISSUE THREAD

**Issue by baijinhua** [alibaba/Sentinel#2321]
看了下NacosDataSourceFactoryBean.class的源码
<img width="777" alt="WX20210809-164214@2x" src="https://user-images.githubusercontent.com/57130812/128680091-0d4dbd3c-9d70-4f51-b831-2fe7e07f6256.png">
源码显示access_key只有serverAddr为空的情况下才能使用，但是serverAddr为空的话回默认set一个localhost:8848，所以access_key模式不能授权访问nacos

**Comment by baijinhua** [comment]
暂时是手写了一个datasource在项目启动的时候注册进去，没法使用spring cloud alibaba原始的NacosDataSource

**Comment by sczyh30** [comment]
The latest SCA version may have fixed it: https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.6.RELEASE
cc @yuhuangbin

**Comment by baijinhua** [comment]
@sczyh30 项目有版本要求，如果用老版本的jar,有什么解决这个问题的方案没？

**Comment by sczyh30** [comment]
若无法升级最新版本，则自己实现数据源即可。
