### ISSUE TITLE
线程数值不归零，导致无法使用线程数流控

### ISSUE THREAD

**Issue by wannianxianyu** [alibaba/Sentinel#2334]
## 同一个接口在多个API 分组中，设置了流控规则，在快速失败后，上层统计的线程数值不归零，导致无法使用线程数流控

Type: *bug report* 

### 我在把sentinel与gateway集成时发现，当我想把某个route下的某个接口单独进行流控时，route的线程数在所有请求结束后，不会重新重置为0，导致我无法在route中使用阈值为线程数，因为它会触发限流，一直拒绝我的请求

![企业微信截图_20210813108044](https://user-images.githubusercontent.com/24456816/129296051-751a9525-d532-4484-8dae-7ba2abfd2235.png)

![企业微信截图_20210813095946](https://user-images.githubusercontent.com/24456816/129296085-4622e935-ffcb-42bc-b46d-c83cde9c6cc0.png)

### 甚至我将/student/getOfficialStudentList接口，分别建立在两个api分组中时，其中一个api分组流控规则触发快速失败后，另一个api分组的线程数也不会重置为0

![企业微信截图_20210813100442](https://user-images.githubusercontent.com/24456816/129296243-60265ce7-68bb-453a-b62e-782be4d8223b.png)

### 
Sentinel dashboard 1.6.3
Sentinel 客户端版本 1.6.3
spring-cloud-alibaba-sentinel-gateway 2.1.0.RELEASE
spring-cloud-starter-alibaba-sentinel  2.1.0.RELEASE
spring-cloud-gateway 2.1.2.RELEASE

**Comment by sczyh30** [comment]
把 spring-cloud-alibaba-sentinel-gateway 和相关 Sentinel 依赖版本均升级至最新后试一下，应该还是依赖的问题。

**Comment by wannianxianyu** [comment]
> spring-cloud-alibaba-sentinel-gateway 和相关 Sentinel 依赖版本都升级至最新后试一下，应该还是依赖的问题。

谢谢，应该是版本1.6.3的问题，当我单独把sentinel-spring-cloud-gateway-adapter升级至1.8.0时，这个问题解决。

```
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
            <version>1.8.0</version>
        </dependency>
```
就是不知道这样做会不会引起其他的问题。

**Comment by sczyh30** [comment]
建议 SCA 版本和 Sentinel 版本都保持最新，以便享受最新的特性与 bug 修复。
