### ISSUE TITLE
dashboard上个别应用新增流控规则，无接入动态数据源，保存后规则数据丢失，是什么情况

### ISSUE THREAD

**Issue by zjritzirok123** [alibaba/Sentinel#2340]
漏上传截图，麻烦看看下面评论

**Comment by zjritzirok123** [comment]
配置规则然后保存
![1](https://user-images.githubusercontent.com/17312073/129659602-65484921-5799-4819-9135-0c8bdb578da3.png)
列表页空的
![2](https://user-images.githubusercontent.com/17312073/129659624-6300c0db-585a-43a0-a3bd-875ddd9ce956.png)

**Comment by zjritzirok123** [comment]
dubbo适配框架sentinel-dubbo-adapter，dashboard和适配均为1.6.3版本

**Comment by sczyh30** [comment]
https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到
