### ISSUE TITLE
簇点链路显示问题、流控规则异常-bug report

### ISSUE THREAD

**Issue by lijunyong** [alibaba/Sentinel#2348]
一个简单的demo项目
```
   @Autowired
    private IUserService userService;

    // 注入配置文件上下文
    @Autowired
    private ConfigurableApplicationContext applicationContext;


    @GetMapping(value = "/a")
    public String a() {
        return "Hello a " + applicationContext.getEnvironment().getProperty("user.name") + ", " + userService.getUser();
    }

    @GetMapping(value = "/b")
    public String b() {
        return "Hello b " + applicationContext.getEnvironment().getProperty("user.name") + ", " + userService.getUser();
    }

   @Service
public class UserServiceImpl implements IUserService {

    @SentinelResource("user")
    public String getUser() {
        return "lee";
    }
}
```
1、访问/a和/b，然后在sentinel dashboard可以看到族点链路，链路显示有问题
![image](https://user-images.githubusercontent.com/14291793/130736954-39d0a52d-2eba-4239-b6cc-824e59ba646a.png)
2、给/b设置流控规则，访问/b
![image](https://user-images.githubusercontent.com/14291793/130737101-5c856815-b0bf-4e8e-beca-03bb51defe54.png)
3、设置user流控规则
![image](https://user-images.githubusercontent.com/14291793/130737247-e0b9b260-ee11-4c11-aa38-a50b30b1c977.png)
4、然后删除2中设置的规则，访问/b
![image](https://user-images.githubusercontent.com/14291793/130737346-dfc8b0a1-91a4-4181-b448-8e33662119c8.png)

![image](https://user-images.githubusercontent.com/14291793/130737384-0329ecae-1eef-4271-9b4c-e9dffc69dd8b.png)

![image](https://user-images.githubusercontent.com/14291793/130737442-e734e21e-87fd-498d-8502-f7198e177290.png)

![image](https://user-images.githubusercontent.com/14291793/130738148-a084034d-28c6-4573-a868-62ac0ea1fddd.png)

**Comment by sczyh30** [comment]
Refer #1213, #1314

**Comment by lijunyong** [comment]
显示问题通过配置已经解决，流控还是异常

**Comment by startjava** [comment]
@lijunyong 我是spring cloud alibaba 2021.1版本，请问这个问题解决了吗，显示的问题我设置web-context-unify: false还是不行，全部变二层或三层了。

**Comment by xishenglx** [comment]
请问您显示问题是怎么解决的呢？
