### ISSUE TITLE
sentinel-datasource-zookeeper依赖curator-recipes<5.2.0>报错

### ISSUE THREAD

**Issue by yipixiaofeiyang** [alibaba/Sentinel#2352]
## Issue Description

今天在升级dubbo为3.0.2的途中, 发现curator-framework已经升级到5.2.0, 遂将全局的版本都改为5.2.0了, 但是问题出现了, 在启动过程中报错:
`org.apache.curator.framework.recipes.cache.NodeCache.getListenable()Lorg/apache/curator/framework/listen/ListenerContainer`

在查看4.2.0中 发现依赖了curator-recipes中的NodeCache已被@Deprecated并更改为CuratorCache了.
### Describe what happened (or what feature you want)

**Comment by yipixiaofeiyang** [comment]
已自定义实现

**Comment by HWliao** [comment]
如何自定义实现的?

**Comment by yipixiaofeiyang** [comment]
查看附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/Sentinel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 下午5:30
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [alibaba/Sentinel] sentinel-datasource-zookeeper依赖curator-recipes<5.2.0&gt;报错 (#2352)





 
如何自定义实现的?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
