### ISSUE TITLE
sentinel循环依赖

### ISSUE THREAD

**Issue by ryaninvoker** [alibaba/Sentinel#2353]
spring-cloud-alibaba-sentinel版本：2.1.0.RELEASE
sentinel-core版本：1.7.1
openfeign版本:2.1.1RELEASE
启动项目汇报循环依赖

**Comment by sczyh30** [comment]
Could you please provide the detailed error message?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by sczyh30** [comment]
Closing the issue due to no further feedback.
