### ISSUE TITLE
模块: sentinel-cluster-server-envoy-rls  缺少类RateLimitServiceGrpc

### ISSUE THREAD

**Issue by su787910081** [alibaba/Sentinel#2357]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

按文档，激活 profile(prod)

另外，使用proto 编译了proto中的文档生成了java 源文件

但是还是缺少一个类: RateLimitServiceGrpc，看样子应该也是proto 写的，但是写在哪里呢，没有找到。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
我这边是下载的1.8.1的版本的源码

**Comment by winjaychan** [comment]
可以查看 1.8.1分支的 sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/proto/envoy/service/ratelimit/v2/rls.proto

**Comment by winjaychan** [comment]
> ## Issue Description
> Type: _bug report_ or _feature request_
> 
> ### Describe what happened (or what feature you want)
> 按文档，激活 profile(prod)
> 
> 另外，使用proto 编译了proto中的文档生成了java 源文件
> 
> 但是还是缺少一个类: RateLimitServiceGrpc，看样子应该也是proto 写的，但是写在哪里呢，没有找到。
> 
> ### Describe what you expected to happen
> ### How to reproduce it (as minimally and precisely as possible)
> 
> ### Tell us your environment
> 我这边是下载的1.8.1的版本的源码
> 
> ### Anything else we need to know?

可以查看 1.8.1分支的 sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/proto/envoy/service/ratelimit/v2/rls.proto

**Comment by su787910081** [comment]
> > ## Issue Description
> > Type: _bug report_ or _feature request_
> > ### Describe what happened (or what feature you want)
> > 按文档，激活 profile(prod)
> > 另外，使用proto 编译了proto中的文档生成了java 源文件
> > 但是还是缺少一个类: RateLimitServiceGrpc，看样子应该也是proto 写的，但是写在哪里呢，没有找到。
> > ### Describe what you expected to happen
> > ### How to reproduce it (as minimally and precisely as possible)
> > ### Tell us your environment
> > 我这边是下载的1.8.1的版本的源码
> > ### Anything else we need to know?
> 
> 可以查看 1.8.1分支的 sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/proto/envoy/service/ratelimit/v2/rls.proto

这里面只有一个RateLimitService，而没有RateLimitServiceGrpc。用protoc.exe 没法编译出RateLimitServiceGrpc 这个类呀。
不过我在网上查了一下，添加了一个依赖直接就可以了。而不需要使用protoc.exe 进行编译先。
```xml
        <dependency>
            <groupId>io.envoyproxy.controlplane</groupId>
            <artifactId>server</artifactId>
            <version>0.1.28</version>
        </dependency>
```

**Comment by winjaychan** [comment]
> > > ## Issue Description
> > > Type: _bug report_ or _feature request_
> > > ### Describe what happened (or what feature you want)
> > > 按文档，激活 profile(prod)
> > > 另外，使用proto 编译了proto中的文档生成了java 源文件
> > > 但是还是缺少一个类: RateLimitServiceGrpc，看样子应该也是proto 写的，但是写在哪里呢，没有找到。
> > > ### Describe what you expected to happen
> > > ### How to reproduce it (as minimally and precisely as possible)
> > > ### Tell us your environment
> > > 我这边是下载的1.8.1的版本的源码
> > > ### Anything else we need to know?
> > 
> > 
> > 可以查看 1.8.1分支的 sentinel-cluster/sentinel-cluster-server-envoy-rls/src/main/proto/envoy/service/ratelimit/v2/rls.proto
> 
> 这里面只有一个RateLimitService，而没有RateLimitServiceGrpc。用protoc.exe 没法编译出RateLimitServiceGrpc 这个类呀。
> 不过我在网上查了一下，添加了一个依赖直接就可以了。而不需要使用protoc.exe 进行编译先。
> 
> ```
>         <dependency>
>             <groupId>io.envoyproxy.controlplane</groupId>
>             <artifactId>server</artifactId>
>             <version>0.1.28</version>
>         </dependency>
> ```

是的，RateLimitServiceGrp是由rls.proto中的RateLimitService这个生成的

**Comment by winjaychan** [comment]
@sczyh30 可以close这个issue了
