### ISSUE TITLE
可不可以设置总的 控制规则 比如流量控制的规则，现在我看只能设置单个资源的规则

### ISSUE THREAD

**Issue by wolaiye1010** [alibaba/Sentinel#237]
可不可以设置总的 控制规则 比如流量控制的规则，现在我看只能设置单个资源的规则

在单个资源规则不设置的时候走总的 默认规则

**Comment by sczyh30** [comment]
Hi, global rule is a good idea. We may support this in later version. Here are some discussions here: #66
