### ISSUE TITLE
热点规则编辑后提示保存成功，实际没有修改成功

### ISSUE THREAD

**Issue by muziyang527** [alibaba/Sentinel#2381]
问题：热点规则编辑后保存提示保存成功，实际没有修改成功
版本：1.8.2（通过docker-compose将jar文件部署的）

**Comment by brotherlu-xcq** [comment]
可以先检查一下sentinel-dashboard.log中的异常信息。

**Comment by sczyh30** [comment]
Refer FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ
