### ISSUE TITLE
sentinel-dashboard 是否可以分布式部署？

### ISSUE THREAD

**Issue by wolaiye1010** [alibaba/Sentinel#241]
1，sentinel-dashboard 是否可以分布式部署？
client上报的内容存在哪儿，控制台是否可以进行多机器分布式部署，

**Comment by jialianglinjl** [comment]
> 1，sentinel-dashboard 是否可以分布式部署？
> client上报的内容存在哪儿，控制台是否可以进行多机器分布式部署，

可以。Sentinel-Dashboard主要承接3个功能:
1. 监控 主动拉取聚合监控数据。这个必须要分布式部署
2. Push规则
3. 上报机器管理

具体例子可以看一下: https://github.com/alibaba/Sentinel/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97#%E5%85%AC%E7%BD%91-demo

**Comment by sczyh30** [comment]
See #363 for more discussion.

**Comment by westonlv** [comment]
多个dashboard Server通过逗号分隔

**Comment by wolaiye1010** [comment]
@mybug99 ,  我直接部署了两台，两台机器映射到一个域名，用nginx做负载均衡，暂时没有什么问题

**Comment by mybug99** [comment]
> @mybug99 , 我直接部署了两台，两台机器映射到一个域名，用nginx做负载均衡，暂时没有什么问题

那如何实现两台dashbody的数据共享呀，你这个只是做了负载均衡反向代理= =

**Comment by wolaiye1010** [comment]
@mybug99 ,我的理解是dashbody 只是一个接受上报的数据后台，后台不需要累计什么东西，每次上报都是新的数据，所以数据不会有问题

**Comment by mybug99** [comment]
> @mybug99 ,我的理解是dashbody 只是一个接受上报的数据后台，后台不需要累计什么东西，每次上报都是新的数据，所以数据不会有问题

能否留个联系方式交流一下，   因为咱们不都是在dashbody进行流控操作的吗，然后降级规则， 比如dash断了然后这些降级规则还有流控规则还存在吗

**Comment by wolaiye1010** [comment]
@mybug99  微信号：jugg1010

**Comment by chlsmile** [comment]
@wolaiye1010 【sentinel-dashboard 是否可以分布式部署】我也有同样的疑惑，你那边有解决么
