### ISSUE TITLE
Sentinel 在idea 中项目无法启动

### ISSUE THREAD

**Issue by Yan-minghao** [alibaba/Sentinel#2419]
![image](https://user-images.githubusercontent.com/33973209/137446113-3ced86c6-e0a8-4eeb-9b51-851e6b753cff.png)

**Comment by brotherlu-xcq** [comment]
这个看着像maven拉取依赖的问题，你重新拉一下依赖呢？

**Comment by Yan-minghao** [comment]
maven 拉取 还是不能用，在maven 的setting 中也配置了阿里云镜像

**Comment by sczyh30** [comment]
Has this been solved? @Yan-minghao

**Comment by Yan-minghao** [comment]
还没解决，现在还是不行

**Comment by Yan-minghao** [comment]
@sczyh30 还没解决

**Comment by cdfive** [comment]
@Yan-minghao 取消Toggle Offline Mode选中，点那排第一个按钮刷新了没？IDEA里的报错提示跟之前一样吗

**Comment by Yan-minghao** [comment]
是的，取消选中也还是无法启动

**Comment by Yan-minghao** [comment]
是的，取消选中也还是无法启动

**Comment by Yan-minghao** [comment]
![image](https://user-images.githubusercontent.com/33973209/139627369-b9e99bd6-4e28-4059-ae0f-08ed83a20010.png)
这是启动问题

**Comment by cdfive** [comment]
对sentinel-parent模块，执行mvn clean install，或者先mvn clean然后mvn install试试
可以在IDEA里执行，也可以不用IDEA在命令行里进sentinel-parent目录执行，看有没有啥报错提示

**Comment by Yan-minghao** [comment]
mvn clean install 时候，部分包无法下载下来Could not transfer artifact io.netty:netty-all:jar:4.1.32.Final from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/central/): Transfer failed for http://maven.aliyun.com/nexus/content/repositories/central/io/netty/netty-all/4.1.32.Final/netty-all-4.1.32.Final.jar

**Comment by cdfive** [comment]
浏览器里访问[http://maven.aliyun.com/nexus/content/repositories/central/io/netty/netty-all/4.1.32.Final/netty-all-4.1.32.Final.jar](http://maven.aliyun.com/nexus/content/repositories/central/io/netty/netty-all/4.1.32.Final/netty-all-4.1.32.Final.jar)看看能不能下载，验证网络有没有问题，我这边可以下载的

在你本地仓库的目录下找到这个jar的目录，看看是否有.lastUpdated后缀的文件，把它删掉然后重新mvn clean install

还可以试试在本地仓库目录中，批量搜索.lastUpdated后缀的文件，然后删除

**Comment by sczyh30** [comment]
Any feedback?
