### ISSUE TITLE
nacos 使用参数NACOS_AUTH_ENABLE=true之后，sentinel无法读取配置信息。请问这个怎么解决啊？

### ISSUE THREAD

**Issue by aitxiaogang** [alibaba/Sentinel#2425]
如题

**Comment by siriusxxk21** [comment]
sentinel 引用的nacos client 版本如果是1.3.x可能会有问题，手动升级到1.4即可
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-extension</artifactId>
            <version>1.8.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

       <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.4.1</version>
        </dependency>

**Comment by siriusxxk21** [comment]
sentinel 1.8.2 使用的nacos client 1.3版本，使用用户名密码认证会有问题，手动引入1.4版本的nacos client 应该可以解决这个问题。

**Comment by sczyh30** [comment]
Would you like to submit a PR to upgrade Nacos client version to the latest 1.x version?
