### ISSUE TITLE
Sentinel控制台没有应用信息

### ISSUE THREAD

**Issue by freelandforus** [alibaba/Sentinel#243]
## Issue Description
问题1：按照官网介绍，下载了 1.3.0-GA版本的sentinel-dashboard.jar ，设置好JVM参数，启动后，浏览器地址栏输入 localhosts:8080 ，控制台全是空白，没有如 “首页->sentinel-dashboard”信息。
问题2：客户端接入控制台的过程虽然看明白了，但是又没有示例，官网的sentinel-dashboard的demo里面是一个junit用例，不太 明白信息如何和控制台交换的。
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by freelandforus** [comment]
@sczyh30 ，有联系方式么，私聊下？

**Comment by MoPei** [comment]
按照官方文档操作是没有问题的，最有可能是你姿势不对

**Comment by freelandforus** [comment]
@MoPei ，我把代码拉到本地，运行DashboardApplication，访问localhost:8080 ，大约10秒后名为"sentinel-dashboard"的应用并没有出来。
-Dserver.port=8080
-Dcsp.sentinel.dashboard.server=localhost:8080
-Dproject.name=sentinel-dashboard

**Comment by MoPei** [comment]
@freelandforus 你可以先使用dashboard.jar文件本地命令行启动下，没有问题的:java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar，命令行启动都是有日志的，起不来就会有报错，另外你再本地启动个依赖了sentinel-core和sentinel-transport-simple-http应用，在启动参数里增加-Dcsp.sentinel.dashboard.server=127.0.0.1:8080,停一会在刷新dashboard页面就能看大你的流控规则了

**Comment by freelandforus** [comment]
@MoPei ，win10环境下本地有两种方式打开cmd：
第一种是cmd窗口下输入以下命令启动是正常的，可以看到sentinel-dashboard信息:
java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar
第二种是按住shift键+鼠标右键，打开Powershell窗口，在该窗口下输入第一种的命令，启动正常，但是sentinel-dashboard 信息一直是没有的。（由于之前习惯了shift+鼠标右键打开窗口敲命令，所以没有看到应用信息，具体原因未知）。

1.代码环境启动DashboardApplication还是看不到应用信息，IDE为IDEA. JVM参数同第一种设置。
2 另外官网上的 “Sentinel 客户端目前已可用于生产环境”，我还不太明白这里说的这个“Sentinel 客户端”具体是说代码里面的哪个工程示例？
