### ISSUE TITLE
设置全局默认配置

### ISSUE THREAD

**Issue by LoveVsLike** [alibaba/Sentinel#244]
在一个应用中，所以应用都是调用外部数据源，我想设置一个默认的降级策略供所有resource来使用，而不是每个都进行配置

**Comment by sczyh30** [comment]
Hi, we may support this in later version. You can go to discuss in #66.

Duplicated with #66 and #237.

**Comment by sczyh30** [comment]
Closing this as it's duplicated with #66. You can go to discuss in #66.
