### ISSUE TITLE
Token client single CPU footprint 100% | 集群限流下client 单核cpu近100%

### ISSUE THREAD

**Issue by Mararesliu** [alibaba/Sentinel#2444]
## Issue Description

Type: *bug report* 
集群限流下运行一段时间后client 单核cpu近100%
Token client's single cpu would tuning nearly 100% in Cluster Limiter mode, when run some days later.

### Describe what happened (or what feature you want)
在请求量极低的情况下，在运行一段时间后（一般几天后）多个client机器会有 XNIO-3 task-n （arthas查看）的线程持续占满cpu。再同时对比去除集群限流后cpu恢复正常。猜测可能性，client有锁影响性能操作，但是由于线程名称不明确，暂时还追踪不到影响来源
### Describe what you expected to happen
降低cpu消耗
### How to reproduce it (as minimally and precisely as possible)

1. 集群限流模式
2. nacos datasource 

### Tell us your environment
centos 7.9
sentinel 1.8.2
zk 3.6.2
nacos 1.4.1

**Comment by sczyh30** [comment]
可否提供下 profiler 信息（如火焰图）？

**Comment by Mararesliu** [comment]
已解决，谢谢。找到问题：使用 SentinelApiClient 里面的Reactor 方式进行client和token server定时通讯，未释放导致最终导致线程过多。

**Comment by sczyh30** [comment]
SentinelApiClient 这个是控制台相关的逻辑吗？
