### ISSUE TITLE
热点限流只能用于@SentinelResource标注的方法

### ISSUE THREAD

**Issue by Surrin1999** [alibaba/Sentinel#2446]
sentinel版本为1.7.1，dashboard版本为1.8.2

当配置热点规则时只有使用@SentinelResource标记的方法可以起作用，直接以`/xxx`这样的方式配置不起作用
如下图，这样配置是不起作用的
![image](https://user-images.githubusercontent.com/37960540/141083929-6313f838-ce17-477e-abb8-77006efb4cdf.png)

当配置了@SentinelResource，并在资源名处下sentinelresource的value才能起作用
![image](https://user-images.githubusercontent.com/37960540/141084017-98e15edc-d813-43e6-a075-969dffe272d1.png)
![image](https://user-images.githubusercontent.com/37960540/141084146-7207c6fc-61f8-44d0-a33b-ca6fb07a17cf.png)

**Comment by Surrin1999** [comment]
不知道是否是文档中这句话的意思。。说实话写的太隐蔽而且太不好理解了。。
![image](https://user-images.githubusercontent.com/37960540/141436601-3e0aaf74-a329-4b60-8d28-001e1d0dfaa0.png)

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/issues/1871
We'll improve the document later :)
