### ISSUE TITLE
怎么使用BlockExceptionHandler?

### ISSUE THREAD

**Issue by jmbkeyes** [alibaba/Sentinel#2452]
## Issue Description
定义了继承自BlockExceptionHandler的bean，然后对一个api进行了限流
![1637285057(1)](https://user-images.githubusercontent.com/12583734/142534419-d14fd961-f2fb-4036-91ac-f45336000d3a.png)
但是bean的handle没有触发，而是抛了UndeclaredThrowableException异常。
然后看了SentinelResourceAspect，里面抛异常时好像先按有blockHander就按blockHandler处理，否则按fallback处理， 如果两者都没时抛异常
```
@Component
public class SentinelExceptionHandler implements BlockExceptionHandler {
    @Override
    public void handle(HttpServletRequest request, HttpServletResponse response, BlockException e) throws Exception {
        Map<String, Object> resp = new HashMap<>();
        // 不同的异常返回不同的提示语
        String message = null;
        if (e instanceof FlowException) {
            message = "被限流了";
        } else if (e instanceof DegradeException) {
            message = "服务降级了";
        } else if (e instanceof ParamFlowException) {
            message = "被限流了";
        } else if (e instanceof SystemBlockException) {
            message = "被系统保护了";
        } else if (e instanceof AuthorityException) {
            message = "被授权了";
        }
        response.setCharacterEncoding("utf-8");
        response.setHeader("content-Type", "application/json");
        response.getWriter().print("{\"status\":\"1\", \"message\":\"" + message +"\"}");
    }
}
```

限流api
```
@RestController
@RequestMapping(value = "/api/test", produces = {"application/json"})
public class TestController {
    @GetMapping(value = "/hello/{name}")
    @SentinelResource(value = "sayHello")
    public String apiHello(@PathVariable String name) {
        return "hello, " + name;
    }
}
```
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
怎么使用BlockExceptionHandler?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
springboot2.4.0, com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2021.1

**Comment by sczyh30** [comment]
BlockExceptionHandler 仅对 Sentinel 自带的 Web 埋点生效（URL 维度）。对于注解方式埋点，参考注解埋点文档，配置 blockHandler。

**Comment by jmbkeyes** [comment]
@sczyh30 假如注解式埋点比较多(对应的参数都是不同的)，那不是要写好几个blockHandler？
