### ISSUE TITLE
sentinel2.2.6对应SpringCloud版本多少.监控页面总是没有数据。后台日志可以收到sentinel日志信息

### ISSUE THREAD

**Issue by jiejiedeai** [alibaba/Sentinel#2453]
sentinel2.2.6对应SpringCloud版本多少.监控页面总是没有数据。后台日志可以收到sentinel日志信息

**Comment by sczyh30** [comment]
可以参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) 进行排查
