### ISSUE TITLE
集群限流怎么使用？

### ISSUE THREAD

**Issue by jmbkeyes** [alibaba/Sentinel#2457]
## Issue Description
这边启动了两个demo应用，选择了其中一个应用作为内嵌tokenserver，然后配置集群限流规则，测试时发现集群限流没有生效，fallback到单机限流了。
![1637648163(1)](https://user-images.githubusercontent.com/12583734/142978605-699b3174-6ebd-4fa5-8280-c04da4ae19e5.png)
![1637648197(1)](https://user-images.githubusercontent.com/12583734/142978645-c89d9913-37c2-4558-9ad2-b70555a5fc92.png)
![1637648222(1)](https://user-images.githubusercontent.com/12583734/142978677-f9307b53-eaa6-4f05-a671-144c51a0ad87.png)

![1637648128(1)](https://user-images.githubusercontent.com/12583734/142978561-5b43b4a7-02c9-481b-a58e-af2e0fbdf1b3.png)

调试发现ClusterFlowRuleManager.FLOW_RULES是空map，还有sentinel-cluster-client.log里面有如下log
2021-11-23 13:48:15|1|no rules in token server|1,0
2021-11-23 13:48:16|1|no rules in token server|5,0
2021-11-23 13:48:17|1|no rules in token server|3,0

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
确保集群流控规则推送页面走的 v2 页面（配置中心推送）

**Comment by jmbkeyes** [comment]
@sczyh30 谢谢你的回复，这边看了sentinel-demo里的sentinel-demo-cluster-embedded， 实现了接口InitFunc的init方法加载cluster flow rule,并通过SPI加载实现类之后就可以限流了.
