### ISSUE TITLE
Spring cloud gateway sentinel上如何进行集群限流

### ISSUE THREAD

**Issue by songhaiyun** [alibaba/Sentinel#2458]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Duplicate with #2105

**Comment by diaomaoblue** [comment]
看来看去，怎么无限套娃，没有一个是讲怎么操作的。。。
