### ISSUE TITLE
System overload rule does not take effect for customized resource| 自定义埋点 配置了系统规则 入口qps阈值，但不起作用

### ISSUE THREAD

**Issue by DeBruyne2020** [alibaba/Sentinel#2459]
sentinel版本号1.8.1
springcloud版本号：Hoxton.RELEASE
springboot版本号：2.3.1.RELEASE
springCloudAlibaba版本号: 2.2.6.RELEASE

配置“系统规则”，配置阈值 入口qps=0，但没起作用 ，qps依然可以达到20
![image](https://user-images.githubusercontent.com/68886035/143420328-ff7aa380-e7ba-40df-9667-5c5c1f269e0f.png)
![image](https://user-images.githubusercontent.com/68886035/143420697-7d0e2bb9-d4ae-4136-be77-834e481f1cbe.png)

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wucheng1997** [comment]
https://github.com/alibaba/Sentinel/pull/2455 解决相关问题。

**Comment by DeBruyne2020** [comment]
> #2455 解决相关问题。

@wucheng1997 
您好   ，我debug发现和2455情况不一样，  我debug出来的原因是因为resourceWrapper.getEntryType()是OUT, 
走到了下面这个拦截
 if (resourceWrapper.getEntryType() != EntryType.IN) {
            return;
        }
        
        所以触发不到SystemRule的代码
        
        附debug截图：
        
![image](https://user-images.githubusercontent.com/68886035/147061568-c34bd633-a541-4065-b545-c28e8f7e52d3.png)

**Comment by sczyh30** [comment]
如果是自定义埋点的话，需要指定为 EntryType.IN，代表 inbound traffic；系统规则从设计上仅对 inbound traffic 生效。

**Comment by DeBruyne2020** [comment]
> 如果是自定义埋点的话，需要指定为 EntryType.IN，代表 inbound traffic；系统规则从设计上仅对 inbound traffic 生效。

@sczyh30 
大佬您好，  这个例子，奇怪的点在于我降低到sentinel1.7.2版本就可以触发SystemRule了，当时debug看得效果是降到sentinel1.7.2版本后，同样的请求，resourceWrapper.getEntryType() 就是EntryType.IN,

**Comment by sczyh30** [comment]
具体的 EntryType 都是由 SphU.entry 方式传入的（注解方式也类似），默认不传的话都为 OUT，若拿到的是 IN 则传入的就是 IN。Sentinel 自带的 Web 和 RPC provider 埋点都是自动标识为 inbound 的。
