### ISSUE TITLE
统计时长的限制与实际的警告信息不一致

### ISSUE THREAD

**Issue by Tank-zhu** [alibaba/Sentinel#2476]
### Describe what happened (or what feature you want)

![1638413761725_E8DC0D6C-0855-4C41-BFCA-B9D14B161A40](https://user-images.githubusercontent.com/10337065/144367373-e5e8f44b-dd7e-4b3c-a248-742743794b73.png)
<img width="1281" alt="1638416567624_46BFA5E0-F1E9-4403-897A-BFB89C56C83D" src="https://user-images.githubusercontent.com/10337065/144367392-2c09bafe-73b8-4ad2-93b2-eea936924459.png">
<img width="1164" alt="1638416824877_4BBA1EC8-B858-49C9-AA5C-2F358424485D" src="https://user-images.githubusercontent.com/10337065/144367413-14460ebd-92d1-4c64-b5d2-b84336186511.png">

**Comment by sczyh30** [comment]
这里的场景按照”最大120s“的语义一般足够，可以按照这个来进行统一，欢迎提交 PR
