### ISSUE TITLE
泛化调用，还有异步泛化调用的支持度

### ISSUE THREAD

**Issue by Wangwuquanff** [alibaba/Sentinel#248]
Sentinel对泛化调用和异步泛化调用的支持吗？有没有实战示例

**Comment by Wangwuquanff** [comment]
我现在在学习了解这个框架，就像异步调用支持一样，有没有泛化调用和异步泛化调用的学习示例文档。谢谢了

**Comment by sczyh30** [comment]
请问 泛化调用和异步泛化调用 指的是？

**Comment by Wangwuquanff** [comment]
泛化调用只有通过Invoke入口，参数不同对应的下游服务不同，应该怎样实现这种参数级别的降级？

**Comment by sczyh30** [comment]
See #196.

**Comment by Wangwuquanff** [comment]
thanks
