### ISSUE TITLE
网关自定义API分组流控未生效

### ISSUE THREAD

**Issue by ja-peng** [alibaba/Sentinel#2484]
按照官网在网关层代码中进行注入SentinelGatewayFilter ，以下为debug截图
1）网关流控规则；资源来源为API分组，时间间隔为1s，流控阈值为10的pqs流控规则(资源名为"GET-/sentinel/test/")
![@1WXX(YGFD2MJJ {Z)D)6_M](https://user-images.githubusercontent.com/48684182/144824073-da56fc7b-b6c7-485d-b7ee-00545c358e46.png)
2）分组名为"GET-/sentinel/test/"的匹配路径和匹配模式 
![J}PG~W8O1@FD0K_EFYVKNLF](https://user-images.githubusercontent.com/48684182/144824108-7f943f26-a321-4409-9067-0e9fb7f76a67.png)
测试：连续频繁点击postman调用此接口的结果都是成功，sentinel流控没有生效
![image](https://user-images.githubusercontent.com/48684182/144824133-c837bdc3-c230-4758-bed4-60ff4ff6e8c8.png)

**Comment by ja-peng** [comment]
GET-/sentinel/test/

**Comment by ja-peng** [comment]
本人小白一枚。。。

**Comment by wan19970127** [comment]
你好，这个问题同问，有解决吗
