### ISSUE TITLE
OOM occured with StringResourceWrapper linked CtEntry in Tomcat TaskThread ThreadLocal.

### ISSUE THREAD

**Issue by xuminwlt** [alibaba/Sentinel#2485]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

guess something happened in afterCompletion, Context or Entry not clean and exit.
TaskThread in tomcat is used in a pool, new request get a old Context from pre request.
of course this is a guess，because i can't get the code for debug.

```
public void afterCompletion(HttpServletRequest request, HttpServletResponse response,
                                Object handler, Exception ex) throws Exception {
        if (increaseReferece(request, this.baseWebMvcConfig.getRequestRefName(), -1) != 0) {
            return;
        }
        
        Entry entry = getEntryInRequest(request, baseWebMvcConfig.getRequestAttributeName());
        if (entry == null) {
            // should not happen
            RecordLog.warn("[{}] No entry found in request, key: {}",
                    getClass().getSimpleName(), baseWebMvcConfig.getRequestAttributeName());
            return;
        }
        
        traceExceptionAndExit(entry, ex);
        removeEntryInRequest(request);
        ContextUtil.exit();
    }
```

![image](https://user-images.githubusercontent.com/5835937/145181345-5d51a6db-3245-4d23-bd1a-a90beac70288.png)
![image](https://user-images.githubusercontent.com/5835937/145181399-1254ed5f-cd8e-4a33-9871-67d0c0536b8f.png)

![image](https://user-images.githubusercontent.com/5835937/145183525-3a643da0-3fc7-4e8d-a692-87dd1aceb1b5.png)

### Describe what you expected to happen

ContextUtil map contains 2 key（default、spring-sentinel）is no problem.
It maybe occured in interceptor which has no close action.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

version 1.8.2
pom:spring-cloud-alibaba
pom:webmvc-adapter
no rule used and default config

**Comment by xuminwlt** [comment]
maybe used async request  
dispatherType = Async
Need to test.

**Comment by Linzyoo** [comment]
Can assign this issue to me?  I want to fix it.
