### ISSUE TITLE
控制台怎么向规则中心通过推模式注册规则

### ISSUE THREAD

**Issue by Wangwuquanff** [alibaba/Sentinel#249]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen
控制台怎么实现不是系统态的规则修改，而是向zookeeper这样的规则中心去注册，控制台需要配置规则中心地址吗？怎么配置，现在的问题是控制台如何跟zookeeper或者其他中心建立联系的。动态注册不了。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, you have to manually refactor the dashboard for your configuration center. See [this blog post](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0) and [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#%E8%A7%84%E5%88%99%E5%AD%98%E5%82%A8%E4%B8%8E%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%95%B0%E6%8D%AE%E6%BA%90datasource) for guideline.
