### ISSUE TITLE
gateway重启后sentinel所有规则失效

### ISSUE THREAD

**Issue by kay07** [alibaba/Sentinel#2495]
## Issue Description

bug report？

### Describe what happened (or what feature you want)

when I restarted my spring-cloud-gateway,the sentinel rules won't work,but I can find the rules in nacos,why?

### Describe what you expected to happen

I hope gateway restarted the rules will work always,don't need to restart sentinel.(I have to restart sentinel to make it work -_-)

### How to reproduce it (as minimally and precisely as possible)

1. Restart spring-cloud-gateway

2. If don't restart sentinel ,it will not work.

### Tell us your environment

`    <parent>

        <groupId>org.springframework.boot</groupId>

        <artifactId>spring-boot-starter-parent</artifactId>

        <version>2.3.3.RELEASE</version>

        <relativePath/>

    </parent>`

**Comment by roy500** [comment]
What version is Spring-Cloud-Gateway ，Sentinel and Nacos

**Comment by sczyh30** [comment]
You may refer to [the document of Spring Cloud Alibaba Sentinel](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel) and check whether your data-source configruation is correct.

**Comment by 1327681842** [comment]
Excuse me，
how did you deal with this problem？ @kay07
