### ISSUE TITLE
限流规则之关联关系资源限流示例问题

### ISSUE THREAD

**Issue by ITBoyss** [alibaba/Sentinel#2498]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
设置 strategy 为 RuleConstant.STRATEGY_RELATE 同时设置 refResource 为 write_db。这样当写库操作过于频繁时，读数据的请求会被限流。
此处描述设置 refResource 为 write_db时，写操作频繁，读会被限流

### Describe what you expected to happen
设置 refResource 为 write_db时，读操作频繁，读会被限流

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
关联限流会根据指定的资源（refResource）的相关指标来限制当前资源（resource）的流量。
