### ISSUE TITLE
Add record log level configuration support | 支持配置 record 日志的输出级别配置

### ISSUE THREAD

**Issue by zhaoxinhu** [alibaba/Sentinel#2505]
我们的项目正在使用限流，并且配置了规则已生效，我们的规则基本上不变，但是限流相关的日志越来越大越来越多，我们需要花时间和精力来处理这些日志。是否可以添加一个打印日志的级别配置类似csp.sentinel.log.level=OFF的，这样我们可以直接进行关闭。我看了咱的应该是使用的默认的    private volatile Level logLevel = Level.ALL;

**Comment by sczyh30** [comment]
Contributions are welcomed.

**Comment by sczyh30** [comment]
Resolved by #2514
