### ISSUE TITLE
SCA sentinelWebInterceptorOptional circular-references error | Spring Boot 2.6.x循环依赖sentinelWebInterceptorOptional

### ISSUE THREAD

**Issue by 203579397** [alibaba/Sentinel#2509]
The dependencies of some of the beans in the application context form a cycle:

   sysLoginService (field private com.dfe.dfzh.smk.system.api.feign.LogFeignClient com.dfe.dfzh.smk.auth.service.SysLoginService.logFeignClient)
      ↓
   org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
┌─────┐
|  com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration (field private java.util.Optional com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration.sentinelWebInterceptorOptional)
└─────┘

**Comment by sczyh30** [comment]
Maybe related to https://github.com/alibaba/spring-cloud-alibaba/issues/2322
