### ISSUE TITLE
Circuit breaking for Spring WebClient and RestTemplate | 对于调用第三方的降级与熔断，是必须使用添加了拦截的`httpclient`与`okhttp` 才有效？

### ISSUE THREAD

**Issue by su787910081** [alibaba/Sentinel#2526]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我在控制台使用熔断与降级规则的时候发现，它并不是我们常规认为的熔断与降级，实际的效果只是限流。
另外，我在项目代码中有看到两个模块：`sentinel-apache-httpclient-adapter`与`sentinel-okhttp-adapter` ，这两个模块对调用第三方服务的http 请求进行拦截支持。
看了相关的代码与示例代码，我的一个问题就是如果想要得到正常的熔断与降级功能，只有使用像代码中提供的`SentinelOkHttpInterceptor` 或者`SentinelApacheHttpClientBuilder` 才能达到效果是吗？
如果是直接使用类似`WebClient`、`RestTemplate` 这类进行http 请求是无法进行熔断与降级的？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, you may refer to [Spring Cloud Alibaba Sentinel](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel) for support of Spring components like RestTemplate and Feign.

**Comment by su787910081** [comment]
看了https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel 文档，那我的这个理解是正确的了，必须要对相关的http client 进行拦截降级与熔断相关的功能才会生效。那我关了这个issue
