### ISSUE TITLE
基于sentinel-dubbo-demo泛化调用

### ISSUE THREAD

**Issue by Wangwuquanff** [alibaba/Sentinel#253]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen
我在sentinel-dubbo-demo工程普通调用的基础上，修改成泛化调用在控制台中显示只打印了10（正确）条其他抛出了异常，但是在sentinel-block中显示被阻止了15（total:总调用了15次全部为bloked）次不应该也是相同的5次，不知道哪里出错了，使用的限流规则还是示例中的规则。还是sentinel不支持泛化调用
日志：普通调用：2018-11-19 09:29:38|1|dubbo.FooService:sayHello(java.lang.String),FlowException,default,demo-consumer-config|5,0
          泛化调用：2018-11-19 09:36:04|1|dubbo.FooService:sayHello(java.lang.String),FlowException,default,demo-consumer-invoke|15,0

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Please refer to #196 and check whether your rule is correct.
