### ISSUE TITLE
nginx porxy /sentinel

### ISSUE THREAD

**Issue by billdegithub** [alibaba/Sentinel#2530]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
代理失败
java -Xms215m -Xmx215m -Dserver.port=8718 -Dcsp.sentinel.dashboard.server=127.0.0.1:8718 -Dproject.name=senti
nel-dashboard -Dcsp.sentinel.api.port=8719 -jar sentinel-dashboard-1.8.1.jar 
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

 location /sentinel {
       proxy_pass https://127.0.0.1:8718;
       proxy_set_header Host       $http_host;
       proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
       proxy_set_header X-Real-IP $remote_addr;
    }

### Anything else we need to know?
具体还需要配置哪里？怎么都实现不了。看之前的issuse根本没有解决啊。。。修改哪个文件参数？

**Comment by icodening** [comment]
nginx是可以正常代理dashboard的, 你这只是没有配置静态资源. 试试增加以下配置代理静态资源
`location / {
    proxy_pass http://127.0.0.1:8718/;
}`
