### ISSUE TITLE
springmvc  启动配置不支持properties方式

### ISSUE THREAD

**Issue by chenshanhai-mc** [alibaba/Sentinel#2532]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
springmvc  classpath添加sentinel.properties文件, 里面配置csp.sentinel.dashboard.server和project.name, 启动,  访问springmvc项目.  dashboard里面没有springmvc项目,  同样的springboot正常

### Tell us your environment
1. sentinel-dashboard 1.8.2
2. sentinel-core 1.8
3. spring-webmvc 5.2.12.RELEASE
4. jdk 1.8

**Comment by sczyh30** [comment]
You may refer to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-控制台没有显示我的应用或者没有监控展示如何排查) to check whether Sentinel has been configured and initialized correctly.

**Comment by roy500** [comment]
没有自动化注入，手动添加SentinelWebInterceptor拦截即可
![image](https://user-images.githubusercontent.com/24887350/149252031-16484f7f-7a02-4942-b1dc-44039d9eef5d.png)

**Comment by chenshanhai-mc** [comment]
配置问题

**Comment by chenshanhai-mc** [comment]
配置问题
