### ISSUE TITLE
Dashboard add rule API return 404 | 控制台降级规则添加失败

### ISSUE THREAD

**Issue by NoColor96** [alibaba/Sentinel#2541]
使用版本：sentinel-dashboard-1.8.3
复现场景：控制台添加降级规则弹窗提示“失败”
查看请求接口为:GET http://localhost:8080/degrade/new.json?app=xxxx，报错404
查sentinel-dashboard 1.8源码server端貌似已将接口更新为POST /degrade/rule，但控制台中仍然使用了1.7版本旧接口(sentinel 1.7可正常使用)

这问题为啥没人提，难道是我的操作方式不对？

**Comment by sczyh30** [comment]
一般刷新下浏览器缓存即可。
