### ISSUE TITLE
关联模式控流在资源QPS设置为0时，关联资源未达到触发条件依然会断流（设计成这样还是BUG？）

### ISSUE THREAD

**Issue by etfired1** [alibaba/Sentinel#2543]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
关联模式控流在资源QPS设置为0时，关联资源未达到触发条件依然会断流

### Describe what you expected to happen
系统内部有一个全局数据保存服务(GlobalService)，这个服务非常耗时，
同时另一个服务为数据写入服务（DataService）
为了保证(GlobalService)在调用过程中，DataService服务阻断调用
因此我将DataService控流模式设置为 QPS=0，模式为**关联** GlobalService。
GlobalService 设置为 线程控流模式 ，阈值为**1**
服务刚启动，GlobalService没调用过，DataService能够正常访问，但是只要调用一次GlobalService并成功后
DataService就无法访问了

环境：
OpenJDK 8
Sentinel 1.8.1

**Comment by sczyh30** [comment]
关联模式中，当关联规则的量达到阈值，会限制当前 resource 的访问。

> 保证(GlobalService)在调用过程中，DataService服务阻断调用

则应直接在关联规则配置并发数 1.
