### ISSUE TITLE
Spring Cloud Gateway 簇点链路路径错乱，没有展示为URL

### ISSUE THREAD

**Issue by feng1632009** [alibaba/Sentinel#2560]
你好，我想在gateway网关限流中添加限流自定义异常处理 当我添加 spring-cloud-alibaba-sentinel-gateway 添加这个依赖的时候，我未覆盖其中的任何方法，随便发起请求 查看dashboard 控制台 如下图所示

![1](https://user-images.githubusercontent.com/16715254/152948623-b8993dfc-302f-47e4-9965-e810250a92c5.png)

当我去掉这个依赖的时候又是正常的，如下图
![2](https://user-images.githubusercontent.com/16715254/152949102-7849a851-3fd7-4c65-96ca-4545c1690c2b.png)

请问此问题如何解决，此问题影响之前限流规则的定义，因簇点链路路径错乱，导致之前限流规则全部失效
环境信息：  spring cloud version  Hoxton.SR3 、  spring-cloud-alibaba-dependencies  2.2.7.RELEASE     spring-cloud-alibaba-sentinel-gateway    2.2.7.RELEASE   降低多次此依赖版本问题依旧

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-%E6%94%AF%E6%8C%81

> Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度。如需细化到 URL 粒度，请参考网关流控文档自定义 API 分组。

**Comment by feng1632009** [comment]
> Refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-%E6%94%AF%E6%8C%81
> 
> > Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度。如需细化到 URL 粒度，请参考网关流控文档自定义 API 分组。

你好，我看了看如果以网关项目启动，限流规则的设置是链路里面设置的 限流规则，这是设置到了内存里面，重启就消失了，我们之前已经做完源码的修改实现规则的双向同步如下图，但这里面的规则的设置是影响不到网关层面的，只能影响作为普通项目的限流，请问如果想让网关规则的持久化，并且实现双向同步的话 应该怎么做
![3](https://user-images.githubusercontent.com/16715254/153314379-6debe64d-40f6-4391-a44d-192891b9ab7e.png)

**Comment by sczyh30** [comment]
> > Refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-%E6%94%AF%E6%8C%81
> > > Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度。如需细化到 URL 粒度，请参考网关流控文档自定义 API 分组。
> 
> 你好，我看了看如果以网关项目启动，限流规则的设置是链路里面设置的 限流规则，这是设置到了内存里面，重启就消失了，我们之前已经做完源码的修改实现规则的双向同步如下图，但这里面的规则的设置是影响不到网关层面的，只能影响作为普通项目的限流，请问如果想让网关规则的持久化，并且实现双向同步的话 应该怎么做 ![3](https://user-images.githubusercontent.com/16715254/153314379-6debe64d-40f6-4391-a44d-192891b9ab7e.png)

可以参考流控规则 v2 页面的改造，改造网关流控页面及对应 controller，方式大同小异，注意推送格式即可。
