### ISSUE TITLE
spring项目,push模式客户端如何整合从nacos读取规则?

### ISSUE THREAD

**Issue by skyemin** [alibaba/Sentinel#2561]
只看到springboot的例子,有没有spring的?

**Comment by brotherlu-xcq** [comment]
例子里面的只是一个参考，至于你的业务上面如何使用，在什么时候注册规则变更的监听器，这个完全可以由你来定义。例如监听spring的容器事件，又或者直接放到@PostConstruct中，这些方式你可以参考spring的使用。

**Comment by skyemin** [comment]
> 

谢谢老哥指导
