### ISSUE TITLE
SCA Sentinel file data-source | SpringCloud Gateway集成sentinel，无法使用文件持久化

### ISSUE THREAD

**Issue by bolinzhang** [alibaba/Sentinel#2573]
sentinel版本：1.8.0
springcloud：Greenwich.SR4

我使用springcloud gateway集成sentinel之后，新增了类实现了InitFunc接口，并增加了SPI加载，文件数据源在WritableDataSourceRegistry中进行了注册。

但是在控制台保存之后无法更新文件。如果我把csp.sentinel.app.type设置为0，即为非网关的时候，是可以保存数据的。
代码查看后，gateway调用的和普通服务不是同一套接口，推送的为gateway/getApiDefinitions，
想请问一下网关如果我想使用文件来持久化，我应该实现哪一个接口

**Comment by bolinzhang** [comment]
或者说我需要注册哪些DataSource到哪里，有示例吗

**Comment by bolinzhang** [comment]
哦找到了
GatewayApiDefinitionManager、GatewayRuleManager
UpdateGatewayApiDefinitionGroupCommandHandler、UpdateGatewayRuleCommandHandler
是这四个类吧？

**Comment by sczyh30** [comment]
SCA 的话可以参考 https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#动态数据源支持
当然自己 InitFunc 注册数据源也 OK.
