### ISSUE TITLE
Feign timeout | 服务熔断降级超时规则不生效

### ISSUE THREAD

**Issue by BruceLidd** [alibaba/Sentinel#2574]
## Issue Description

服务熔断降级超时规则不生效

### Describe what happened (or what feature you want)
解决熔断降级超时时间不生效问题？

### Describe what you expected to happen

1.比如B服务执行时间需要1s，我用A服务调用B服务时设置超时规则为降级规则2s，但是此时一直时错误状态，而不是期待的正常状态，不管在A中设置规则的超时时间RT是大于1s的任何数都不生效，但是当B的执行时间小于900ms时，B服务才可用
2.超时的max RT在启动时可设置自定义时间，是否有类似于在yml文件中配置的全局最大RT超时时间
### How to reproduce it (as minimally and precisely as possible)

1. 熔断降级不生效
2. 全局最大超时RT是否可以通过yml配置进行配置

### Tell us your environment
测试环境

### Anything else we need to know?
sentinel 1.8.0 openfign 

配置规则如下:
![image](https://user-images.githubusercontent.com/95683511/154197018-8971ac6e-394d-4f48-9b6d-0ae1b7b37810.png)
被降级的服务的逻辑如下：
![image](https://user-images.githubusercontent.com/95683511/154197128-d937eee3-133d-40e9-9d0d-ec0311cf2bbd.png)

测试结果如下：
![image](https://user-images.githubusercontent.com/95683511/154197153-abb45810-7932-4c93-8a7a-b7277dceb547.png)
期待结果如下：
改完等待时间小于1s
![image](https://user-images.githubusercontent.com/95683511/154197235-92e7d9a7-41c4-45a8-850c-5daf5c6eac40.png)

期待结果：
![image](https://user-images.githubusercontent.com/95683511/154197270-eebfbaa1-c228-42c0-abc0-3ca3d127980a.png)

**Comment by sczyh30** [comment]
Sentinel 熔断规则的作用并不是超时直接掐断，参考相关文档：https://sentinelguard.io/zh-cn/docs/circuit-breaking.html
这里可能有其它超时机制生效。

**Comment by BruceLidd** [comment]
找到原因了，这个我用了openfeign调用，feign自己有个超时时间，如果这个超时时间范围外就可以触发熔断降级策略，感觉比较坑啊，最起码在官方文档里描述清楚点

**Comment by 1083** [comment]
> 



> 找到原因了，这个我用了openfeign调用，feign自己有个超时时间，如果这个超时时间范围外就可以触发熔断降级策略，感觉比较坑啊，最起码在官方文档里描述清楚点

求解，我这边无法熔断。
