### ISSUE TITLE
sentinel-transport-common HTTP security | sentinel-transport-common模块暴露的http接口没有访问验证，是否存在安全隐患问题

### ISSUE THREAD

**Issue by hezhaoye** [alibaba/Sentinel#2578]
Java服务在外网使用中，sentinel-transport-common模块暴露的http接口没有访问验证，是否存在安全隐患问题，例如攻击者直接通过构造请求调用修改限流规则？

**Comment by sczyh30** [comment]
Command HTTP port 不建议暴露到外网，仅供内网访问。如果有更强的安全性需求，可以自定义 transport 模块进行鉴权改造，欢迎贡献。
