### ISSUE TITLE
存储在nacos中AuthorityRuleEntity,再客户端启动时无法convert为AuthorityRule

### ISSUE THREAD

**Issue by catalpa-tree** [alibaba/Sentinel#2579]
第一步：sentinel_dashboard添加AuthorityRule规则，持久化至nacos中

    第二步：客户端启动加载时，定义convert的rule class为AuthorityRule

    covert为AuthorityRule后值为空，resource=null, limitApp=null, strategy=null

**Comment by panda0120** [comment]
同样的问题，交流群满了，能不能再开两个
