### ISSUE TITLE
统计问题

### ISSUE THREAD

**Issue by shuohao** [alibaba/Sentinel#258]
![image](https://user-images.githubusercontent.com/4637107/48878447-62583400-ee42-11e8-9798-71a4fbcca388.png)

像截图里的这种是什么原因呢

**Comment by tigerMoon** [comment]
can you provide more details. such as rule config? qps? and how these data produce?

**Comment by sczyh30** [comment]
> ![image](https://user-images.githubusercontent.com/4637107/48878447-62583400-ee42-11e8-9798-71a4fbcca388.png)
> 
> 像截图里的这种是什么原因呢

Hi, any more information on it?

**Comment by sczyh30** [comment]
Closing this since no feedback. You can reopen the issue if there are still problems.
