### ISSUE TITLE
Spring MVC 反射型文件下载漏洞

### ISSUE THREAD

**Issue by HBinLiu** [alibaba/Sentinel#2585]
## Issue Description

About the spring-web.jar version, the current version is 5.0.9.RELEASE, that have the issue; the issue have been found by the aliyun Cloud Security。 

在Spring Framework中，5.2.3之前的版本5.2.x，5.1.13之前的版本5.1.x，5.0.16之前的版本5.0.x，当应用程序在响应中设置“Content-Disposition”头时，当文件名属性来自用户提供的输入时，它容易受到反射文件下载(RFD)攻击。

### How to reproduce it (as minimally and precisely as possible)

1. please improve the spring-web.jar version

**Comment by sczyh30** [comment]
The `spring-web` dependency is in provided scope in adapters, so this is not affected. We've upgraded Spring Boot version of Sentinel dashboard. Thanks for reporting.
