### ISSUE TITLE
我的提供者路径就是test1，为什么在sentinel中出现嵌套结构了呢？2个流控按钮，点击哪一个呢

### ISSUE THREAD

**Issue by startjava** [alibaba/Sentinel#2592]
![image](https://user-images.githubusercontent.com/49554320/157562134-5e332ac3-bf57-4702-8ab6-c6349c457280.png)

显示嵌套结构的目的是什么呢？或者是bug呢？

**Comment by icodening** [comment]
我检查了Servlet、SpringMVC、WebFlux三个适配模块的代码，发现是WebFlux适配的代码的问题，并在测试后可以复现你描述的问题。该问题属于WebFlux适配的Bug

**Comment by startjava** [comment]
@icodening 是不是簇点链路就是这样的格式？？因为是链路，所以显示的是树形结构的？

**Comment by icodening** [comment]
@startjava 是树形结构，但根节点信息应该是不正确的。下图是我本地临时修改后的效果截图
<img width="3167" alt="image" src="https://user-images.githubusercontent.com/42876375/158966168-24b2c782-6ea5-421f-a239-b4f87704b598.png">

**Comment by startjava** [comment]
啊，好，期待速度PR，感谢感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/Sentinel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/Sentinel] 我的提供者路径就是test1，为什么在sentinel中出现嵌套结构了呢？2个流控按钮，点击哪一个呢 (Issue #2592)





 
@startjava 是树形结构，但根节点信息应该是不正确的。下图是我本地临时修改后的效果截图
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by icodening** [comment]
WebFlux下涉及到不少的线程上下文切换，而原Context用的是ThreadLocal进行维护很可能会出现丢失，上面的简单修改能覆盖到的场景不够全，暂时还提不了PR呢

**Comment by sczyh30** [comment]
调用链路最顶部的为该次调用的入口 context 名称，用于链路限流中区分不同调用入口链路，若使用统一的 context 则不支持链路流控。后续可参考 Spring Web adapter 中提供配置支持是否需要统一 context.
