### ISSUE TITLE
sentinel client可以配置profiles吗？

### ISSUE THREAD

**Issue by wangsenyan** [alibaba/Sentinel#2597]
目前情况：
    我使用sentinel-datasource-nacos(1.8.3),根据sentinel-dashboard中的指导,设置了持久化到nacos
    这时,生成的流控名称${spring.application.name}-flow-rules

但是，我使用nacos需要根据环境变量来请求flow-rule,
  请求的流控名称为${spring.application.name}-${server.profiles.active}-flow-rules

我想问下，当使用sentinel时候，如何传递给它环境变量，使得第一步的请求的流控规则包含环境变量，和第二步请求的dataId一致呢

**Comment by sczyh30** [comment]
Sentinel 不限定每个数据源对应的坐标，可以自行定制相关逻辑，传入期望的 dataId。
