### ISSUE TITLE
关于Sentinel无法实时监控的问题-@RequestMapping

### ISSUE THREAD

**Issue by MonsterGel** [alibaba/Sentinel#2599]
学习SpringCloud整合Sentinel，现阶段没有用gateway网关进行路由分发的模式来让sentinel进行实时监控。
而是单独将一个微服务注册到Sentinel并监听，在客户端的controller层使用了@RequestMapping注解，Sentinel无法进行实时监控。
当我去掉@RequestMapping注解时，Sentinel则可以正常监听接口请求。
刚开始上手Sentinel，不清楚官方文档是否有相关说明，导致我一直以为是我的配置文件出问题。（查了一大堆文档各种配置使用过还是不行，偶然间把@RequestMapping注解去掉之后就一切正常了）

**Comment by sczyh30** [comment]
可否提个一个可复现的 sample?

**Comment by MonsterGel** [comment]
> 
环境是win10本地跑的版本 1.8.3 Sentinel

1. 下图链接是controller带@RequestMapping注解的请求方式，浏览器多次请求接口，无实时监控显示
![3c577b578ff9bebbe2e72a7d6d8eda0](https://user-images.githubusercontent.com/26500583/157889345-c02bb538-8280-4ebe-a395-afb4b3d51b91.png)

2.下图链接是controller未带@RequestMapping注解的请求方式，浏览器多次请求接口，实时监控显示正常
![71a0ed895e7406f3c6b5c94ee0282bc](https://user-images.githubusercontent.com/26500583/157893147-66f5a263-eadc-4d48-9642-c260a4a8fa7f.png)

1.8.2版本sentinel我也尝试了存在同样情况，其他低版本尚不清楚。

**Comment by MonsterGel** [comment]
> > 
> 
> 环境是win10本地跑的版本 1.8.3 Sentinel
> 
> 1. 下图链接是controller带@RequestMapping注解的请求方式，浏览器多次请求接口，无实时监控显示
>    ![3c577b578ff9bebbe2e72a7d6d8eda0](https://user-images.githubusercontent.com/26500583/157889345-c02bb538-8280-4ebe-a395-afb4b3d51b91.png)
> 
> 2.下图链接是controller未带@RequestMapping注解的请求方式，浏览器多次请求接口，实时监控显示正常 ![71a0ed895e7406f3c6b5c94ee0282bc](https://user-images.githubusercontent.com/26500583/157893147-66f5a263-eadc-4d48-9642-c260a4a8fa7f.png)
> 
> 3.下图链接是pom.xml引入的依赖 ![723b77fd91825d1fd2b9b5646e80e99](https://user-images.githubusercontent.com/26500583/157896522-8d5e4bee-0112-4901-85e6-aef70c4acdef.png)
> 
> 1.8.2版本sentinel我也尝试了存在同样情况，其他低版本尚不清楚。

考虑到是不是存在pom依赖包冲突，也尝试了把openfeign和webflux依赖包去掉之后重新调用接口，但问题依旧存在。

**Comment by zhangzhongxing-sudo** [comment]
重启一下试试？不可复现

**Comment by MonsterGel** [comment]
> 
今天浏览了下wiki，看到了spring-cloud-alibaba官网wiki关于各组件版本关系说明,我引用的spring-cloud-alibaba版本依赖是2.2.0的,官方给出的sentinel推荐版本是1.7.1，换成1.7.1后显示正常了。问题已解决，是我个人版本选择错误导致，不好意思=。=

**Comment by MonsterGel** [comment]
> 重启一下试试？不可复现

今天浏览了下wiki，看到了spring-cloud-alibaba官网wiki关于各组件版本关系说明,我引用的spring-cloud-alibaba版本依赖是2.2.0的,官方给出的sentinel推荐版本是1.7.1，换成1.7.1后显示正常了。问题已解决，是我个人版本选择错误导致，不好意思=。=

**Comment by cscsccc** [comment]
检查是否在项目中配置 WebMvcConfigurationSupport 会有冲突
