### ISSUE TITLE
有大佬知道sentinel和gateway的区别吗，小弟感觉都可以限流，为什么用sentinel

### ISSUE THREAD

**Issue by sanhe-qigai** [alibaba/Sentinel#2606]
如题

**Comment by icodening** [comment]
两者定位不同，Gateway作为流量入口侧重于对“后端资源”进行流控，Sentinel作为一个嵌入到应用的SDK侧重于对“自身资源“的流控。由于Gateway只是入口控制而无法控制服务间的调用，所以依然是需要Sentinel保护的。
个人见解，如有不当请指出。

**Comment by Cherry93** [comment]
能详细解释下不

**Comment by sczyh30** [comment]
![image](https://user-images.githubusercontent.com/9434884/187145165-ea3a034a-a850-4f09-b329-92f88e9e3023.png)

Sentinel 关注微服务全链路、全方位的流控降级与容错，可以在任意点位进行容错保护。网关本身不是专门做流控的，流控只是其中一个能力，用于控制入口流量，但入口流量之后的稳定性 无法兜底。

**Comment by icodening** [comment]
> 但是仅仅做限流的话，也没有太大区别吧

这个疑问 `Eric Zhao`上面已经提到了，网关仅仅是控制入口流量，无法对进入网关后的流量(`即服务与服务之间的调用流量`)兜底。两者侧重点不一样，看你关注哪方面的限流
