### ISSUE TITLE
sentinel 整合nacos作为规则存储，当nacos设置权限后sentinel无法连接

### ISSUE THREAD

**Issue by zhutie8111** [alibaba/Sentinel#2619]
## Issue Description
 try {
            List<String> params = null;
            if (StringUtils.isBlank(tenant)) {
                params = Arrays.asList("dataId", dataId, "group", group);
            } else {
                params = Arrays.asList("dataId", dataId, "group", group, "tenant", tenant);
            }

            result = this.agent.httpGet("/v1/cs/configs", (List)null, params, this.agent.getEncode(), readTimeout);
        } catch (IOException var9) {

如上代码片段，请求nacos没有携带用户名密码，所以设置过权限的nacos无法连接，请问是否有其他设置的方法
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
对于直接使用 Nacos 数据源的方式，可通过带 Properties 的构造函数传入鉴权相关配置；若使用 SCA Sentinel，可以参考 Spring Cloud Alibaba 文档进行对应的配置。

**Comment by sczyh30** [comment]
See #2425

**Comment by zhutie8111** [comment]
> See #2425

 Make sense, great
