### ISSUE TITLE
网关与sentinel整合后是否支持网关内写的接口进行限流

### ISSUE THREAD

**Issue by mjgzy** [alibaba/Sentinel#2620]
被网关管理的其他服务可以正常限流,但是网关内自己写的接口不可以
![image](https://user-images.githubusercontent.com/55934340/160321845-4e41237b-cbba-4e1e-8853-d46f3151278d.png)
如上图是网关自己写的接口,目前sentinel不支持网关内限流吗

**Comment by sczyh30** [comment]
SC gateway/Zuul 网关内自己实现的接口目前不支持网关流控规则和自定义 API 分组。
