### ISSUE TITLE
How to configure log dir in Sentinel | Sentinel关于日志文件目录的参数太乱

### ISSUE THREAD

**Issue by brucelwl** [alibaba/Sentinel#2623]
sentinel关于日志文件目录的配置参数太乱, 如下几个根本就没有用到，还是简化一下吧！！！

<img width="653" alt="image" src="https://user-images.githubusercontent.com/13413715/160466777-c4fa0bc6-bc64-4b0d-a773-f3eb6e1b231b.png">

**Comment by sczyh30** [comment]
这些类可以做下精简。Sentinel 有统一的日志路径配置方式，参考 https://github.com/alibaba/Sentinel/wiki/日志
