### ISSUE TITLE
如果使用nacos作为数据源,想要更新规则时(并能持久化),是不是只能手动去nacos修改json?

### ISSUE THREAD

**Issue by light0x00** [alibaba/Sentinel#2657]
这样dashboard好像失去了意义

**Comment by SETETERNAL** [comment]
通过sentinel-dashboard同步nacos，客户端订阅nacos的配置中心实现配置更新。官方提供的sentinel-dashboard要自己修改源码才能实现同步nacos

**Comment by sczyh30** [comment]
可以参考 https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel
