### ISSUE TITLE
sentinel控制台浏览器兼容问题

### ISSUE THREAD

**Issue by huangcanhui2018** [alibaba/Sentinel#266]
（1）IE11，控制台首页无法正常显示
（2）Google chrome 版本 48.0.2564.116，控制台左边菜单栏无法正常显示

**Comment by sczyh30** [comment]
Hi, are there any errors in the frontend developer tool of your browser?

By the way, it's recommended to use the latest version of the browser. We do not guarantee the dashboard works well in deprecated (old) versions of the browser.
