### ISSUE TITLE
Sentinel-grpc-adapter不可用了吗？

### ISSUE THREAD

**Issue by huangtao2016** [alibaba/Sentinel#2662]
## Issue Description
Type: *feature request*

在maven仓库似乎没有找到sentinel-grpc-adapter依赖；
请问是不可用了吗？

**Comment by sczyh30** [comment]
https://search.maven.org/artifact/com.alibaba.csp/sentinel-grpc-adapter

**Comment by huangtao2016** [comment]
> https://search.maven.org/artifact/com.alibaba.csp/sentinel-grpc-adapter
thanks
