### ISSUE TITLE
How to disable logs | 如何关闭 Sentinel log base directory？

### ISSUE THREAD

**Issue by 2775468731** [alibaba/Sentinel#2665]
启动sentinel将会输出sentinel-record.log到默认文件夹下，是否有开关关闭此配置？或者指定文件位置？

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/issues/2623#issuecomment-1081316368 and https://github.com/alibaba/Sentinel/issues/2255
