### ISSUE TITLE
sentinel-dashboard docker 部署镜像

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/Sentinel#267]
<https://hub.docker.com> 上没有找到官方提供的 sentinel-dashboard docker 镜像安装包

**Comment by sczyh30** [comment]
Hi, currently we don't provide official Docker image for Sentinel dashboard. You can build your own based on the java Docker image.

**Comment by anjia0532** [comment]
my repo. https://hub.docker.com/r/anjia0532/sentinel-docker

**Comment by JackFe** [comment]
sentinel-dashboard安装、运行(docker)：https://www.cnblogs.com/wintersoft/p/11235192.html，自制验证好用

**Comment by gezhiwei8899** [comment]
when?
