### ISSUE TITLE
csp.sentinel.api authentication | csp.sentinel.api 是否可以设置使用认证访问

### ISSUE THREAD

**Issue by cxc3214** [alibaba/Sentinel#2677]
csp.sentinel.api 是否可以设置使用认证访问
本地项目 服务器被报漏洞 api 没有经过授权访问

**Comment by cxc3214** [comment]
![image](https://user-images.githubusercontent.com/4177562/163664674-9607a4c9-08dd-4119-899f-b5fefa84d454.png)
暴露的api

**Comment by icodening** [comment]
1.8.4版本中新增了``CommandHandlerInterceptor`` SPI接口，通过扩展该接口做授权认证，是否能满足你的需求呢？
