### ISSUE TITLE
Multiple circuit breakers for the same API gateway route | 网关熔断降级如何给一个resource绑定两条熔断规则

### ISSUE THREAD

**Issue by ja-peng** [alibaba/Sentinel#2680]
网关降级，需要给一个自定义API分组的资源绑定两条熔断规则。

加载熔断规则时如果已经有相同的资源名，后续加的同名的规则加不进
![$~N2KKQNI`$ZFHSWQ2`} ~8](https://user-images.githubusercontent.com/48684182/163748127-8f3a116d-99ef-4699-be74-076709545659.png)
![1RV9Q _S4%ECOO R69 K{7](https://user-images.githubusercontent.com/48684182/163748140-ead61c15-07d7-4ba4-ae98-1dcb2bbc1055.png)
但是我在控制台新增的话是ok的
![8`NR9U@T22{VYUG1T_ZS VD](https://user-images.githubusercontent.com/48684182/163748185-316576eb-28b5-4769-95dd-d7467f6ca9bc.png)

如何解决这个问题呢

**Comment by sczyh30** [comment]
可以参考日志看看是不是代码方式设置的字段不对。Refer https://github.com/alibaba/Sentinel/wiki/FAQ

**Comment by ja-peng** [comment]
> 可以参考日志看看是不是代码方式设置的字段不对。Refer https://github.com/alibaba/Sentinel/wiki/FAQ
> 
> Multiple circuit breakers for the same API gateway route are supported. You may check the sentinel-record.log to see whether your hard-coded rules has incorrect fields.

debug看了一下源码，是我配置的参数（count）超过阈值异常比例策略的最大值1.0了，修改之后就ok了
![1650436312](https://user-images.githubusercontent.com/48684182/164165140-f29e3351-ddfe-498e-8e87-d4535c2af285.png)
