### ISSUE TITLE
http://localhost:8719/getRules?type=degrade 始终只显示两个

### ISSUE THREAD

**Issue by wolaiye1010** [alibaba/Sentinel#269]
![image](https://user-images.githubusercontent.com/15831945/49136682-59c19b00-f325-11e8-9606-3a9ba0abda40.png)
![image](https://user-images.githubusercontent.com/15831945/49136785-ac9b5280-f325-11e8-9464-5187a1d2bc4c.png)

明明有多个资源 规则 
http://localhost:8719/getRules?type=degrade 始终只显示两个，Sentinel 控制台 点击降级规则也只能显示两个， 也只能看到两个，无法查看其他的降级规则

**Comment by sczyh30** [comment]
Only when the resource is configured with rules, they will be displayed in the rule page.
---

只有针对对应资源配置了规则，规则页面才会有对应的规则显示。请检查其他资源是否配置了降级规则。
