### ISSUE TITLE
sentinel流控规则里，填写针对来源(微服务名)，但一直不生效，这是为啥，有人遇到过相同问题吗？

### ISSUE THREAD

**Issue by Sh1nYu** [alibaba/Sentinel#2697]
![image](https://user-images.githubusercontent.com/45344556/165230793-2c5ea29f-2802-4e67-ae33-df117e2e3acf.png)
其他的流控都有用，就这一个针对来源没用

**Comment by Sh1nYu** [comment]
![image](https://user-images.githubusercontent.com/45344556/165231275-4a07c7b3-0d0d-46df-a441-999802b2c488.png)
![image](https://user-images.githubusercontent.com/45344556/165231339-0cac0710-4ab2-47c7-86cc-30a9bf874de0.png)
sentinel dashboard是1.8.1的，有哪位大哥知道为啥吗

**Comment by Sh1nYu** [comment]
已解决

**Comment by 201708024103** [comment]
请问你是怎么解决的？
