### ISSUE TITLE
spring cloud gateway 流程bug | SC gateway NPE in GatewayRuleManager

### ISSUE THREAD

**Issue by 992441831** [alibaba/Sentinel#2698]

**Comment by 992441831** [comment]
java.lang.NullPointerException: null
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.applyToConvertedParamMap(GatewayRuleManager.java:230) ~[sentinel-api-gateway-adapter-common-1.8.0.jar:na]
	

springcloudgateway定义了两个路由规则 id： path-route  path-route2
启动时先设置好path-route的流控规则（通过方式GatewayRuleManager.loadRules(rules)）
然后路由path-route2会一个局部过滤器，局部过滤器会更新path-route的流控规则
此时调用path-route2会出现上面错误，而先先用path-route两次后，再调用path-route2就不报错

**Comment by 992441831** [comment]
错误原因为  ParameterMetricStorage.getParamMetricForResource(resource) 为null
所以 ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule); 会抛空指针异常

**Comment by sczyh30** [comment]
This has been fixed in Sentinel 1.8.1 (via #1729)

**Comment by 992441831** [comment]
您好，您的邮件张强强已收到，正在查阅。谢谢！

**Comment by 992441831** [comment]
您好，您的邮件张强强已收到，正在查阅。谢谢！
