### ISSUE TITLE
受控应用以war包形式在tomcat中运行，在启动时如何添加JVM参数

### ISSUE THREAD

**Issue by huangcanhui2018** [alibaba/Sentinel#270]
受控应用打包成war包，以war包的形式部署到tomcat7/8中运行，应用启动时，如下的JVM参数如何在tomcat启动脚本中进行添加？
-Djava.net.preferIPv4Stack=true -Dcsp.sentinel.api.port=8719 -Dproject.name=sentinel-example -Dserver.port=18083 -Dcsp.sentinel.dashboard.server=localhost:8080

可否提供一个正确的配置示例以便参考？

**Comment by sczyh30** [comment]
Hi, you can search the topic about setting JVM parameters for Tomcat with search engine.

**Comment by yuanxy** [comment]
你这个问题解决了吗，可以交流下吗。

**Comment by yuanxy** [comment]
我已解决了这个问题  https://gitbook.cn/gitchat/activity/5d1ee987c9f89d57dd177f13

**Comment by jink2005** [comment]
在tomcat的catalina.sh中配置javaOpt就行了吧，这样就是所有的war包在sentinel里就是一个应用了吧？
