### ISSUE TITLE
ArrayMetric#pass 阅读源码时的疑惑

### ISSUE THREAD

**Issue by wmq930626** [alibaba/Sentinel#2707]
com.alibaba.csp.sentinel.slots.statistic.metric.ArrayMetric#pass这个方法的第一行是不是可以不要
![image](https://user-images.githubusercontent.com/38752290/167070344-5618af97-9b22-4b4f-9242-81dd7556812b.png)
com.alibaba.csp.sentinel.slots.statistic.metric.ArrayMetric#addPass在这个方法中会去处理

只是在阅读源码时的一点小疑惑，可能有其他的逻辑没有注意到。

**Comment by icodening** [comment]
currentWindow刷新当前窗口通行数，后续也没有重复操作
