### ISSUE TITLE
gateway使用sentinel限流，sentinel-dashboard将网关流控输入推入nacos,nacos中时间间隔属性是interval

### ISSUE THREAD

**Issue by 1327681842** [alibaba/Sentinel#2708]
控制台保存到nacos中“间隔”是interval，intervalSec是GatewayFlowRule里字段，从控制台保存规则后，网关中收到nacos推送的数据是interval，没有intervalSec， intervalSec等于默认值1L,导致从控制台提交的流控规则失效，手动将nacos配置中心的interval改为intervalSec，流控规则生效

**Comment by 1327681842** [comment]
测试了一下版本
sentinel-dashboard  1.8.1或者1.8.3
spring-cloud-starter-alibaba-sentinel 2.2.7或者2021.0.1.0
spring-cloud-alibaba-sentinel-gateway 2.2.7或者2021.0.1.0
sentinel-datasource-nacos  1.8.1或者1.8.3

**Comment by lengyue-ck** [comment]
```
    @Bean
    public Converter<List<GatewayFlowRuleEntity>, String> flowGatewayRuleEntityEncoder() {
        return s -> JSON.toJSONString(s).replaceAll("interval", "intervalSec");
    }

    @Bean
    public Converter<String, List<GatewayFlowRuleEntity>> flowGatewayeRuleEntityDecoder() {
        return s -> JSON.parseArray(s.replaceAll("intervalSec", "interval"), GatewayFlowRuleEntity.class);
    }
 ```
    自定义一下转换类型即可

**Comment by 1327681842** [comment]
调用GatewayFlowRule类中的toGatewayFlowRule，fromGatewayFlowRule方法进行转换，
