### ISSUE TITLE
可否针对fastjson <= 1.2.80 反序列化任意代码执行漏洞进行升级

### ISSUE THREAD

**Issue by edifangyi** [alibaba/Sentinel#2729]
检查发现以来的fastjson还是低版本的

**Comment by greydesolate** [comment]
当前还没看到新版本，打算启动jar的时候 添加  -Dfastjson.parser.safeMode=true 先试试了。
不知道这样是否会影响 sentinel 的正常运转。

**Comment by sczyh30** [comment]
Replaced with `fastjson:1.2.69_noneautotype` via https://github.com/alibaba/Sentinel/commit/855e3880a4f4e0b78d4e666737e409190f402416
