### ISSUE TITLE
Endpoint /actuator/sentinel 里面缺少 ParamRules 的配置显示

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/Sentinel#273]
**如图 =>> 缺少 `ParamRules` **

![image](https://user-images.githubusercontent.com/1057589/49205454-02393300-f3ea-11e8-818a-1c1ed4185374.png)

**Comment by sczyh30** [comment]
Related to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/115. It's expected to be supported in next version of Spring Cloud Alibaba.

**Comment by sczyh30** [comment]
Resolved in Spring Cloud Alibaba 0.2.1.
