### ISSUE TITLE
SphU.entry测试无效

### ISSUE THREAD

**Issue by wuhaoqiang1** [alibaba/Sentinel#2732]
## Issue Description

Type: *bug report*

maven版本
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    <version>2.2.6.RELEASE</version>
</dependency>

代码如下，简单demo测试限流无效

public class SentinelExample2 {

    private static void initFlowRules() {
        List<FlowRule> rules = new ArrayList<>();
        FlowRule rule = new FlowRule();
        rule.setResource("HelloWorld1");
        rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
        // Set limit QPS to 10.
        rule.setCount(10);
        rules.add(rule);
        FlowRuleManager.loadRules(rules);
    }

    public static void main(String[] args) {
        // 配置规则.
        initFlowRules();

        ExecutorService exec = Executors.newCachedThreadPool();
        CountDownLatch countDownLatch = new CountDownLatch(1);
        for (int i = 0; i < 500; i++) {
            Runnable run = () -> {
                try {
                    countDownLatch.await();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                Entry entry = null;
                // 务必保证finally会被执行
                try {
                    // 资源名可使用任意有业务语义的字符串
                    entry = SphU.entry("HelloWorld1");
                    // 被保护的业务逻辑
                    // do something...
                    System.out.println("hello world");
                } catch (BlockException e1) {
                    // 资源访问阻止，被限流或被降级
                    // 进行相应的处理操作
                    System.out.println("blocked!");
                } finally {
                    if (entry != null) {
                        entry.exit();
                    }
                }

            };
            exec.execute(run);
        }

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        countDownLatch.countDown();
    }

}

请问是哪里出问题了？麻烦解答，谢谢

**Comment by cdfive** [comment]
看运行后能打印`hello world`和`blocked!`，是说哪里问题呢
不过这个demo执行太快，效果看着不明显，建议参考工程里sentinel-demo-basic模块里的demo，例如：`FlowQpsDemo`

**Comment by wuhaoqiang1** [comment]
> FlowQpsDemo

我这个代码设置qps=10，我启动了500个线程同时跑，所以demo跑起来理论上应该同一时间只会出现10个'hello world'，但是跑起来几乎所有的线程都打印了'hello world'，给人的感觉是限流未生效，请问我这样写的有问题吗？

**Comment by cdfive** [comment]
限流是qps=10，每秒允许10个请求执行。
而这500个线程是立刻运行并马上执行完毕的，估计是整个时间窗口太短 + 单个执行时间太快的原因，来不及统计。

在`SphU.entry`之前，加上：
```java
try {
    Thread.sleep(ThreadLocalRandom.current().nextInt(300, 3000));
} catch (InterruptedException e) {
    e.printStackTrace();
}
```
在观察输出试试
