### ISSUE TITLE
打算贡献一个sentinel operator给社区, 看看大家的需求

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/Sentinel#2734]
看了一下社区sentinel的operator基本没有什么内容, 所以打算贡献一个operator以及相关helm chart, 大家有没有什么需求或需要讨论的内容?

**Comment by wilsonwu** [comment]
看来社区真的是非常不活跃, 连maintainer都没有讨论的医院, 我们只能自己维护自己的版本了.

**Comment by sczyh30** [comment]
咱们这边有哪些 ideas，可以发到社区里面，大家一起讨论一下

**Comment by halfrost** [comment]
@wilsonwu 非常有意愿一起讨论，你可以加入 https://gitter.im/alibaba/Sentinel 一起讨论。

**Comment by wilsonwu** [comment]
See: https://github.com/sentinel-group/sentinel-dashboard-k8s-operator

**Comment by 13567436138** [comment]
sentinel helm chart哪里有啊
