### ISSUE TITLE
dashboard 重新打包前端dist文件报错 | dashboard frontend gulp build error message: 'alert' is not defined

### ISSUE THREAD

**Issue by yujunchengg** [alibaba/Sentinel#2736]
我重写打包dist文件，然后执行gulp build，dist文件是生成了，但是控制台有报错，然后前端也没法访问
![image](https://user-images.githubusercontent.com/36986915/171104447-4f4448f5-bb05-4620-9056-4cdd1e69a8b4.png)
前端访问就报下面这个错误
![image](https://user-images.githubusercontent.com/36986915/171104602-9bbfe916-9add-4265-b3f0-a51f1ba1f36c.png)

**Comment by cdfive** [comment]
执行gulp build后，是通过运行`DashboardApplication`启动类，然后访问页面的吗
还有一种方式是执行cnpm run start

控制台这个报错对访问应该没影响的，它是因为项目里配置了jshint的js语法和风格检查，配置项在.jshintrc文件；
在gulpfile.js文件里`gulp.task('build', ['clean', 'jshint', 'lib', 'js', 'css']);`，如果把里面的'jshint'去掉，在build就没有报错信息了。
