### ISSUE TITLE
单位时间内统计异常次数统计功能逻辑问题

### ISSUE THREAD

**Issue by kelvin-cai** [alibaba/Sentinel#2741]
## Issue Description
使用情况：
```
       List<DegradeRule> rules = new ArrayList<>();
        DegradeRule rule = new DegradeRule();
        rule.setResource(KEY);
       // 80s内调用接口出现异常次数超过5的时候, 进行熔断
        rule.setCount(5);
        rule.setGrade(RuleConstant.DEGRADE_GRADE_EXCEPTION_COUNT);
        rule.setTimeWindow(80);
        rules.add(rule);
        DegradeRuleManager.loadRules(rules);
```

### Describe what happened (or what feature you want)
看到源码ExceptionCircuitBreaker.class中，创建的LeapArray<SimpleErrorCounter> stat是，只有一个窗口，并且intervalInMs是1000毫秒的。那么这个LeapArray就只能统计1秒内的数据了。

当在ExceptionCircuitBreaker类的handleStateChangeWhenThresholdExceeded方法中，判断错误数量是否大于threshold，那就变得只能1秒钟内有80次才会，进行熔断。

### Describe what you expected to happen

而需求是要80s内5次。这个时间维度是80秒，就没法用LeapArray<SimpleErrorCounter> stat的1秒时间维度统计出来

**Comment by drgnchan** [comment]
```Java
rule.setTimeWindow(80);
rule.setStatIntervalMs(80000);
```

要这么设置才有效。你少调用了`rule.setStatIntervalMs(80000);`
