### ISSUE TITLE
SentinelResource注解val 几个资源名称一样  时间窗口统计不就有问题吗 | Same resource name in different @ SentinelResource occurrence

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [alibaba/Sentinel#2742]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
@SentinelResource的val应该有唯一性校验 防止系统写错了

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/19928030/172608603-305775d2-9c6d-4f96-abab-b4e39aee8847.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
`@SentinelResource` 中资源名的正确性由使用者来保证。一些场景中可能需要多个埋点对应同个资源名，Sentinel 不对此类使用方式进行限制。

---

Sentinel does not restrict the "resourceName" in different `@SentinelResource` annotations.
