### ISSUE TITLE
sentinel-dashboard angular前端开发编译环境 Node.js 版本要求 | Dashboard frontend Node.js version restriction

### ISSUE THREAD

**Issue by jgzl** [alibaba/Sentinel#2744]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

相应的README.md和README_zh.MD中提示需要使用的node环境

### Describe what you expected to happen

使用node>=12的版本进行本地开发时会抛出 ReferenceError: primordials is not defined

**Comment by sczyh30** [comment]
Would you like to contribute a PR to improve it?

**Comment by qiujie8092916** [comment]
node 10可以运行

**Comment by jgzl** [comment]
@qiujie8092916 恩恩,我尝试过了,一旦到达node12会触发gulp的插件的问题,所以需要限制在node12之下
