### ISSUE TITLE
spring-cloud-gateway集成sentinel网关，控制台新增降级规则仍然调用普通 DegradeController 接口？

### ISSUE THREAD

**Issue by zhangkun25** [alibaba/Sentinel#2747]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
spring-cloud-gateway集成shentinel后端接口调用错误，sentinel版本1.8.1

### Anything else we need to know?
当在前台增加降级规则的时候，调用了后端的处理器为com.alibaba.csp.sentinel.dashboard.controller.DegradeController而并不是com.alibaba.csp.sentinel.dashboard.controller.gateway.GatewayFlowRuleController中的相关方法，请检查是否前端js编写错误
![规则编辑详情页](https://user-images.githubusercontent.com/61378996/173788091-b9e1acb6-b2e0-46ca-882b-4a9faf9f3bd8.png)
![后端调试图片](https://user-images.githubusercontent.com/61378996/173788100-d789a627-685c-49b8-ad2d-bc95e3815b45.png)
![前端规则编辑](https://user-images.githubusercontent.com/61378996/173788105-83c80598-4326-4a88-bd13-4b883cdbfb78.png)

**Comment by sczyh30** [comment]
熔断降级规则是通用的，不区分正常应用与网关。

---

Circuit breaking rule (i.e. DegradeRule) is a general rule for both normal service and API gateway.
