### ISSUE TITLE
客户端重启不生效，控制台修改配置成功

### ISSUE THREAD

**Issue by liu-miao** [alibaba/Sentinel#2756]
每次客户端 重启 后都需要在控制台 重新设置一遍  所有才生效
debug 时  nacos datasource bean  的数据是有的

我的yaml
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
        client-ip: ${spring.cloud.client.ip-address}
      datasource:
        # 名称随意
        ds1:
          nacos:
            server-addr: xxxx:8848
            username: nacos
            password: xxxx
            namespace: 98xxxxx
            dataId: fscp-gateway-gateway-rules
            groupId: SENTINEL_GROUP
            ruleType: GW_FLOW
            dataType: json
     我的pom
             <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>1.8.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-extension</artifactId>
            <version>1.8.3</version>
        </dependency>

**Comment by liu-miao** [comment]
我经过测试  发现   项目重启    sentinel 没有 将网关规则  加载   ，但是 普通配置 加载成功

**Comment by liu-miao** [comment]
翻了一宿的源码 自己修复了  阿里的大佬们  代码写好点

**Comment by selierlin** [comment]
请问一下如何修复的呢
