### ISSUE TITLE
Make the default max RT value TIME_DROP_VALVE configurable

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#276]
目前该阈值时4900且定义为final static，不能修改；
实际应用中可能有耗时超过5s的接口或方法，影响监控统计数据的准确性。

有2点疑问：
1. 为什么有这个阈值呢，可否去掉？保留原始的RT数据不是更真实么，钉钉群里提到5s超时，可是跟
4900ms也有100ms的误差啊，统计时是否可以忽略该误差；

2. 如果保留该阈值，请问推荐哪种修改方式好一些呢？
    (1)跟project.name、csp.sentinel.charset一样，提供配置文件或VM参数配置
    (2)跟Constants中全局开关ON一样，没有final限制并提供CommandHandler查询和修改
    或者(1)(2)都支持是否更好

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. As the max RT value may not be often changed, we can make it a property like `csp.sentinel.statistic.max.rt` and load when initializing.
