### ISSUE TITLE
直接启动sentinel-dashboard，登录undefined

### ISSUE THREAD

**Issue by dixtdf** [alibaba/Sentinel#2774]
sentinel-dashboard复制到我的项目里直接启动，登录undefined，直接在原有结构运行就可以，为什么在我的项目里不能直接使用
Start sentinel-Dashboard directly and log in to undefined
https://github.com/alibaba/Sentinel/tree/master/sentinel-dashboard
![image](https://user-images.githubusercontent.com/106577535/177257574-eb553a7f-5832-4682-96b1-615fda68e5c5.png)

**Comment by jgzl** [comment]
比对dashboard变更源码,改了其他问题,context path

**Comment by dixtdf** [comment]
> 比对dashboard改变了,改了其他问题,context path

没理解你的意思，我是单独抽dashboard模块直接运行的，没改任何东西

**Comment by jgzl** [comment]
我也单独抽取过,选择了改源码,单独抽取出现问题的代码如下所示
https://github.com/alibaba/Sentinel/blob/04e5047014f83a8b60e1e07d936dc0f2b37dab17/sentinel-dashboard/src/main/webapp/resources/app/scripts/app.js#L42

**Comment by jgzl** [comment]
#1839

**Comment by dixtdf** [comment]
了解了 谢谢 已经修改了😁
