### ISSUE TITLE
同一个接口，如何针对不同请求方来进行不同规则的限流

### ISSUE THREAD

**Issue by hlcen66** [alibaba/Sentinel#2777]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by lazyfighter** [comment]
可以为不同的调用方分配不同的channel，在参数中进行透传，然后按照channel进行限流
参考[基于调用关系的流量控制](https://sentinelguard.io/zh-cn/docs/flow-control.html#%E5%9F%BA%E4%BA%8E%E8%B0%83%E7%94%A8%E5%85%B3%E7%B3%BB%E7%9A%84%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6)

**Comment by hlcen66** [comment]
> 可以为不同的调用方分配不同的channel，在参数中进行透传，然后按照channel进行限流 参考[基于调用关系的流量控制](https://sentinelguard.io/zh-cn/docs/flow-control.html#%E5%9F%BA%E4%BA%8E%E8%B0%83%E7%94%A8%E5%85%B3%E7%B3%BB%E7%9A%84%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6)

我设定了origin，但是发现了一个问题：

假设我接口资源名为 testApi
现在配置3条规则：
testApi     default     qps1
testApi     user1        qps10
testapi     user2        qps20

现在传参  origin=user1，发现受到了default的限流。
可是：官方的解释明明是：同一个资源名可以配置多条规则，规则的生效顺序为：{some_origin_name} > other > default
-------------------------------------------------------------
如果不配置default的话，user1和user2是分别生效的，只要加上default就会失效其他规则。
![image](https://user-images.githubusercontent.com/81564338/177960432-74be2077-a4df-45a0-9a62-980374fdaac2.png)

求解

**Comment by eureka1986** [comment]
default代表不区分调用者，首先匹配user1的规则，小于10qps，继续匹配到default qps1，触发限流。

**Comment by liaomengge** [comment]
官方：所有配置的规则都会走一遍
