### ISSUE TITLE
 while ((second = indexIn.readLong()) < beginSecond)  出现 EOF异常 导致监控页面无数据

### ISSUE THREAD

**Issue by tooapi** [alibaba/Sentinel#278]
```java
long offset;
        try {
            long second;
            lastPosition.offsetInIndex = in.getChannel().position();
            while ((second = indexIn.readLong()) < beginSecond) {
                offset = indexIn.readLong();
                lastPosition.offsetInIndex = in.getChannel().position();
            }
            offset = indexIn.readLong();
            lastPosition.metricFileName = metricFileName;
            lastPosition.indexFileName = idxFileName;
            lastPosition.second = second;
            return offset;
        } catch (EOFException ignore) {
            return -1;
        } finally {
            indexIn.close();
        }

 while ((second = indexIn.readLong()) < beginSecond)
```
出现 EOF异常 导致监控页面无数据

**Comment by sczyh30** [comment]
Hi, can you give more information (e.g. code filename, exception you caught, your environment)? Please refer to [the issue template](https://github.com/alibaba/Sentinel/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by tooapi** [comment]
没有任何异常 就是 监控页面无数据 怀疑是while ((second = indexIn.readLong()) < beginSecond)  readLong的时候出现了异常   技术springboot+restful   使用的sentinel-web-servlet  win10  jdk 8  监控部署在远程linux上

**Comment by sczyh30** [comment]
Please check whether the system time of Sentinel dashboard matches the system time of the machines where your applications are deployed. Sentinel dashboard fetches the monitoring data by the timestamp of dashboard, so if the time doesn't match, the dashboard won't be able to get the monitoring data.

// 请检查 Sentinel 控制台所在机器的时间与服务部署机器的时间是否一致，不一致则无法正确拉取监控。
