### ISSUE TITLE
ClusterBuilderSlot null问题

### ISSUE THREAD

**Issue by shen12341234** [alibaba/Sentinel#279]
ClusterBuilderSlot实例化的时候未赋值，context.getOrigin()有值的情况下
node.getClusterNode().getOrCreateOriginNode会出现空指针

```java
 if (clusterNode == null)
        node.setClusterNode(clusterNode);

        /*
         * if context origin is set, we should get or create a new {@link Node} of
         * the specific origin.
         */
        if (!"".equals(context.getOrigin())) {
            Node originNode = node.getClusterNode().getOrCreateOriginNode(context.getOrigin());
            context.getCurEntry().setOriginNode(originNode);
        }
```

**Comment by sczyh30** [comment]
Hi, can you give more information (e.g. exception you caught, your environment, the version you use)? Please refer to the [the issue template](https://github.com/alibaba/Sentinel/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by shen12341234** [comment]
execute  this method
 public static void test03(){
        ContextUtil.enter("context1", "readHello,writeHello");
     
            Entry entry = null;
            try {
                entry = SphU.entry("aaa");
            } catch (BlockException e1) {
                e1.printStackTrace();   //直接将异常打出来
            } finally {
                if (entry != null) {
                    entry.exit();
                }
            }

    }

for error:  Sentinel unexpected exception java.lang.NullPointerException
