### ISSUE TITLE
集群限流如何防止单节点被压垮

### ISSUE THREAD

**Issue by lzhenglin** [alibaba/Sentinel#2792]
集群限流模式如果设置某接口支持最大tps 5000/s, 5个节点, 如果每个节点所能承受的最大TPS为1500/s,  sentinel集群限流模式会不会导致某个节点大于1500/s然后down机, 请问sentinel集群限流模式是不是额外要实现负载均衡才可以达到理想中的限流功能?

**Comment by sczyh30** [comment]
如果集群流控用于保护业务自身不被打垮，则仍需配合单机限流兜底规则进行配置。目前集群流控不改变流量的形态，只能够缓解由于流量不均导致的单机限流效果不佳的问题。
