### ISSUE TITLE
能不能开个钉钉群啊 

### ISSUE THREAD

**Issue by wanhuhou** [alibaba/Sentinel#28]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wanhuhou** [comment]
确定可以编译通过的吗

**Comment by sczyh30** [comment]
![image](https://user-images.githubusercontent.com/9434884/43624694-a286413a-971b-11e8-84c9-bc8e82c71ee1.png)
