### ISSUE TITLE
gateway全局控流后，某个接口想要单独控流怎么办

### ISSUE THREAD

**Issue by gz25k** [alibaba/Sentinel#2805]
[
    {
        "resource": "模块1",
        "count": 500,
        "grade": 1,
        "limitApp": "default",
        "strategy": 0,
        "controlBehavior": 0
    },
	{
        "resource": "模块2",
        "count": 1000,
        "grade": 1,
        "limitApp": "default",
        "strategy": 0,
        "controlBehavior": 0
    }
]
模块2中有个接口我想要单独控制流量怎么办？

**Comment by sczyh30** [comment]
可以针对单独的接口配置自定义 API 分组，针对自定义分组进行流控即可。参考 https://sentinelguard.io/zh-cn/docs/api-gateway-flow-control.html
