### ISSUE TITLE
Flow control by Dubbo group-version-interface level | Dubbo group+version+interface 细粒度流控支持

### ISSUE THREAD

**Issue by sq-young2** [alibaba/Sentinel#2811]
本身框架底层的所有RPC使用的dubbo interface都是同一个，有好的方案进行自定义熔断吗，目前只支持interface和method配置

---

Flow control by Dubbo group-version-interface level.

**Comment by sczyh30** [comment]
可否给个例子，详细描述一下使用场景？

**Comment by sq-young2** [comment]
好的，感谢回复哦。
我目前的调用链路是，前置->中心服务，因为底层是通过公司框架组成，前置通过dubbo调用中心服务时候，是统一使用一个接口类进行的，就像如图所示，

	<dubbo:reference id="U0001" group="U0001" interface="com.service.FlowService" version="${dubbo.registry.version}"/>	
 	<dubbo:reference id="U0002" group="U0002" interface="com.service.FlowService" version="${dubbo.registry.version}"/>
	<dubbo:reference id="U0003" group="U0003" interface="com.service.FlowService" version="${dubbo.registry.version}"/>
	<dubbo:reference id="U0004" group="U0004" interface="com.service.FlowService" version="${dubbo.registry.version}"/>

如果熔断时候通过这个interface进行，还会导致所有RPC接口出现异常，应该按照group进行熔断较好，所以想寻求下大神的建议

**Comment by sczyh30** [comment]
Dubbo 按 group 和 version 维度进行详细划分的流量治理，Sentinel 目前其实也是支持的，启动参数加上 `-Dcsp.sentinel.dubbo.interface.group.version.enabled=true` 即可让 Dubbo 埋点资源名带上 group 和 version。

---

Dubbo group+version+interface level is supported in Sentinel Dubbo adapter. You may just add `-Dcsp.sentinel.dubbo.interface.group.version.enabled=true` JVM property, then the resource name of the Dubbo interface and method will be prefixed with group and version info.

**Comment by sq-young2** [comment]
好的，那我测试下看看，也是刚看到getInterfaceName的时候看到了这个开关

**Comment by sq-young2** [comment]
您好，
    github上面有个问题，还没有收到回复，邮件打扰一下，链接https://github.com/alibaba/Sentinel/issues/2884，简单说就是，有没有全局默认的熔断配置，针对group，感谢您的回复哦！
| |
无黑色卡片
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Eric ***@***.***> |
| 发送日期 | 2022年08月29日 15:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [alibaba/Sentinel] Flow control by Dubbo group-version-interface level | Dubbo group+version+interface 细粒度流控支持 (Issue #2811) |

Closed #2811 as completed.
