### ISSUE TITLE
集群流量控制 文档说明错误

### ISSUE THREAD

**Issue by wangAhStar** [alibaba/Sentinel#2815]
当然也可以通过动态配置源进行配置。我们可以通过 ClusterClientConfigManager 的 register2Property 方法注册动态配置源。配置源注册的相关逻辑可以置于 InitFunc 实现类中，并通过 SPI 注册，在 Sentinel 初始化时即可自动进行配置源加载监听。

-------------------------

以上文档内容中，ClusterClientConfigManager  类是不存在 register2Property  方法的，只有 registerServerAssignProperty 和 registerClientConfigProperty

**Comment by sczyh30** [comment]
Would you like to contribute a PR to fix it?
https://github.com/sentinel-group/sentinel-website/blob/master/docs/zh-cn/cluster-flow-control.md

**Comment by sczyh30** [comment]
Fixed via https://github.com/sentinel-group/sentinel-website/pull/44
