### ISSUE TITLE
java.lang.NoSuchMethodError: com.alibaba.fastjson.JSON.parseArray(Ljava/lang/String;

### ISSUE THREAD

**Issue by IvesQing** [alibaba/Sentinel#2831]
![image](https://user-images.githubusercontent.com/26543986/184834631-564a4e1c-b5f6-48d6-90bc-82586d089682.png)

 #env
1. sentinel 1.8.3
2. springcloudalibaba 2021.0.1.0
3. Sentinel 控制台 1.8.5

### Anything else we need to know?
use fastjson2 or jackson

**Comment by narutom9527** [comment]
把fastjson切换成2.0以下的版本可以解决

**Comment by liyongios** [comment]
#env
sentinel 1.8.5
springcloudalibaba 2021.0.4.0
Sentinel 控制台 1.8.5

问题还在

**Comment by firstrong** [comment]
> 把fastjson切换成2.0以下的版本可以解决

w为什么非要切换到2.0以下？

**Comment by narutom9527** [comment]
> > 把fastjson切换成2.0以下的版本可以解决
> 
> w为什么非要切换到2.0以下？
sentinel 1.8.3、1.8.4默认引用的是fastjson1的jar包，如果项目用的是fastjson2的话会导致这个报错，也可以在引入此jar包的pom文件里面指定fastjson版本，然后其他项目继续用fastjson2，我这边是为了避免更严重的情况出现暂时选择先不用fastjson2

**Comment by narutom9527** [comment]
> > 把fastjson切换成2.0以下的版本可以解决
> 
> w为什么非要切换到2.0以下？

sentinel 1.8.3、1.8.4默认引用的是fastjson1的jar包，如果项目用的是fastjson2的话会导致这个报错，也可以在引入此jar包的pom文件里面指定fastjson版本，然后其他项目继续用fastjson2，我这边是为了避免更严重的情况出现暂时选择先不用fastjson2
