### ISSUE TITLE
sentinel集成nacos实现持久化后，热点规则和授权规则不生效

### ISSUE THREAD

**Issue by IvesQing** [alibaba/Sentinel#2836]
## Issue Description
1、如题：sentinel集成nacos实现持久化后，热点规则和授权规则不生效
2、查看dashboard源码发现，授权规则和热点规则Entity实现和其他不一样

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/26543986/185373744-e8563656-5989-4484-abd3-8d4ecef92b45.png)
![image](https://user-images.githubusercontent.com/26543986/185373807-d28acf16-a72d-481a-89f7-dac25e106b64.png)

### How to reproduce it (as minimally and precisely as possible)
1、是否2者的差别导致失效
2、为做持久化的时候，授权规则正常生效

**Comment by IvesQing** [comment]
自行解决了

**Comment by Kev1nExen** [comment]
@IvesQing 请问是咋解决的
