### ISSUE TITLE
sentinel-dashoard 集成zookeeper持久化的时候，新增流控规则，数据不能持久化到zookeeper

### ISSUE THREAD

**Issue by shuirouyan** [alibaba/Sentinel#2837]
## sentinel-dashoard 集成zookeeper持久化的时候，新增流控规则，数据不能持久化到zookeeper，我使用的spring-cloud-alibaba-dependencies版本是2.2.8

Type: *bug report*

**Comment by ilovedumplings** [comment]
对应页面也要改动

**Comment by ilovedumplings** [comment]
sidebar.html 
dashboard.flowV1({app: entry.app}) 改为 dashboard.flow({app: entry.app})

**Comment by shuirouyan** [comment]
> 
这里也改了，在新增流控规则的时候，调用的还是/v1/xxx这几个接口，我flowRuleZookeeperProvider这个的接口是/v2/xxx开始的

**Comment by shuirouyan** [comment]
> sidebar.html dashboard.flowV1({app: entry.app}) 改为 dashboard.flow({app: entry.app})

这里我也改了，但是在新增流控的时候，调用的还是/v1/xxxx这样的路径，我修改的flowRuleZookeeperPublisher，flowRuleZookeeperProvider的controller的路径是以/v2/xxx开头的，我不知道为什么会这样，你们用dashboard1.8.5，你们也是这样的吗？

**Comment by shuirouyan** [comment]
@ilovedumplings  sidebar.html dashboard.flowV1({app: entry.app}) 改为 dashboard.flow({app: entry.app})

这里我也改了，但是在新增流控的时候，调用的还是/v1/xxxx这样的路径，我修改的flowRuleZookeeperPublisher，flowRuleZookeeperProvider的controller的路径是以/v2/xxx开头的，我不知道为什么会这样，你们用dashboard1.8.5，你们也是这样的吗？
