### ISSUE TITLE
网关规则 UpdateGatewayApiDefinitionGroupCommandHandler parseJson 报错找不到 fastjson parseArray()

### ISSUE THREAD

**Issue by a-zhongzhongzhong** [alibaba/Sentinel#2838]
UpdateGatewayApiDefinitionGroupCommandHandler.java
method --> parseJson
出错代码 JSONArray array = JSON.parseArray(data); 
报错转换找不到 parseArray() 方法，但是我手动在我的项目中写一样的转换代码时可以转，
源码中转不了，报错截图如下：
![image](https://user-images.githubusercontent.com/50478874/185553953-f82fac8f-e6f9-4dc2-9852-04eab996f1dc.png)

**Comment by sczyh30** [comment]
参考 #2831 看看是否和 fastjson 版本有关

**Comment by firstrong** [comment]
> 参考 #2831 看看是否和 fastjson 版本有关

我好奇为什么 项目中写一样的转换代码时可以转， 为什么jar中却不行？
