### ISSUE TITLE
junit test fail 错误: 找不到或无法加载主类 @{argLine}

### ISSUE THREAD

**Issue by Squidyu** [alibaba/Sentinel#285]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
Junit测试无法获取@{argLine}
Junit test could not get @{argLine}
请问Sentinel源码根模块下的pom文件中maven-surefire-plugin配置的jvm参数argLine中 @{argLine}引用到的启动参数是什么？
What is the startup parameter @{argLine} in the JVM parameter argLine of the maven-surefire-plugin configuration in the POM file under Sentinel source module?

他是怎么引用的？
How @{argLine} work？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
The `@{argLine}` is used for automatically passing args to `maven-surefire-plugin` to generate code coverage report when running CI. You can remove this when you are testing in local.
