### ISSUE TITLE
sentinel压测真实流量和压测流量熔断分离

### ISSUE THREAD

**Issue by huangyiminghappy** [alibaba/Sentinel#2867]
用sentinel在线上进行压测，要求对压测流量和真实流量分离（对限流压测和真实流量一起统计，不分离），即即使压测流量发生熔断，如果真实流量没有到达熔断阀值则真实流量不进行熔断，这个场景，大家有遇到过吗，如果是限流和熔断都进行分离可以通过克隆资源名和规则名做到，但是只对熔断分离对限流不分离似乎改动很大，基于sentinel进行二次开发这个功能似乎会改很多统计相关的源码，请问大家有什么解决方案和建议吗？在真实场景下大家的解决方案是什么？

**Comment by liaomengge** [comment]
二开也遇到这个问题了，思路：当压测流量和真实流量大于配置规则的阈值时，优先禁止压测流量，保障正常流量运行（当然，正常流量大于阈值也会进行流控），可参考下。

**Comment by huangyiminghappy** [comment]
> 

感谢回复，主要是压测流量针对限流和熔断只处理一半，因为统计是一起统计的，但是判断只判断熔断，会对统这块的代码改动很大

**Comment by liaomengge** [comment]
你这意图很明显就是分开隔离统计压测流量和正常流量；但是实际压测流量是否存在统计的意义，而且分开隔离统计，会导致应用内存统计翻倍，主要看你的需要求是否强制需要统计隔离，如果这样的话二开源码是必然的，比如对对统一资源打标隔离等等。

**Comment by huangyiminghappy** [comment]
> 你这意图很明显就是分开隔离统计压测流量和正常流量；但是实际压测流量是否存在统计的意义，而且分开隔离统计，会导致应用内存统计翻倍，主要看你的需要求是否强制需要统计隔离，如果这样的话二开源码是必然的，比如对对统一资源打标隔离等等。

内存应该倒还好，不会占用太大，压测流量和真实流量熔断隔离是因为我们要真实的在线上进行压测，对仿真度要求高，本身我们内部全链路就已经支持压测和真实流量染色区分，就是sentinel这块只对熔断不对限流区分感觉改动比较大，改的面目全非后不方便后面和社区保持同步，似乎得不偿失

**Comment by liaomengge** [comment]
如果你对入口资源拼接染色标签，这样修改的改动最小啊

**Comment by huangyiminghappy** [comment]
> 如果你对入口资源拼接染色标签，这样修改的改动最小啊

当前需求是只对熔断隔离，进行分开统计，限流是压测和真实一起统计，如果是都分开统计，就可以不用改sentinel-core的代码只需要加listener就能解决了

**Comment by huangyiminghappy** [comment]
我们这边已经解决，谢谢
