### ISSUE TITLE
sentinel能否提供配置一个默认的熔断策略，使得所有的请求都能使用这个熔断策略

### ISSUE THREAD

**Issue by XW512** [alibaba/Sentinel#2880]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我现在如果有几十上百个微服务，如果每个微服务都需要手工配置sentinel的熔断策略的话，比较麻烦，能否配置一个默认的熔断策略，这个策略支持在这个微服务中的接口都能使用这个熔断策略，而不是一个一个去配置，有些熔断策略是一样的

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Refer #66, #2232

**Comment by XW512** [comment]
> Refer #66, #2232

我在最新的sentinel-core中没找到2232的issue中的代码呀，这个是没打上去吗？

**Comment by sczyh30** [comment]
resolved via https://github.com/alibaba/Sentinel/pull/2232 and https://github.com/alibaba/Sentinel/commit/bb281042cb25533a4b97f4618a391ac0a2f6b5d6

**Comment by XW512** [comment]
> resolved via #2232 and [bb28104](https://github.com/alibaba/Sentinel/commit/bb281042cb25533a4b97f4618a391ac0a2f6b5d6)

我这里有个疑问，controller层写了一个call2的url，但是在sentinel中会出现3个url，如下，如果采用 这个issue（2232）这样配置的话，会不会直接熔断在controller中的call2这层，实际上，是不是应该熔断在 GET:http://GIS-GRAY/say 这个里面更好一些
 /call2	
 GET:http://GIS-GRAY
GET:http://GIS-GRAY/say
