### ISSUE TITLE
dubbo3适配过滤器全路径名称中的包名和包结构中的包名不一致-1.8.5

### ISSUE THREAD

**Issue by ww530220264** [alibaba/Sentinel#2881]
![4d561da9c68777e600e80c73e3624cf](https://user-images.githubusercontent.com/37855177/190087070-96b97f6a-ab54-4720-9f1d-8f1bf8ea4ae5.jpg)

![image](https://user-images.githubusercontent.com/37855177/190087038-3177a8e7-730b-4ce8-b75c-d33036d5d1ab.png)

**Comment by sczyh30** [comment]
Fixed in https://github.com/alibaba/Sentinel/pull/2822, which will be released with 1.8.6.

**Comment by sczyh30** [comment]
Fixed in Sentinel 1.8.6
