### ISSUE TITLE
dubbo3适配的包sentinel-apache-dubbo3-adapter 1.8.5版本有BUG

### ISSUE THREAD

**Issue by guipengfei** [alibaba/Sentinel#2882]
sentinel-apache-dubbo3-adapter 1.8.5版本
自动装配路径有误！

META-INF/dubbo/org.apache.dubbo.rpc.Filter内容如下：
sentinel.dubbo.provider.filter=com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboProviderFilter

但代码中实际路径为：com/alibaba/csp/sentinel/adapter/dubbo3/SentinelDubboProviderFilter.java

META-INF/dubbo/org.apache.dubbo.rpc.cluster.filter.ClusterFilter存在同样错误

**Comment by sczyh30** [comment]
Fixed in Sentinel 1.8.6
