### ISSUE TITLE
请问下，有没有简单方式实现所有的group默认配置熔断策略的

### ISSUE THREAD

**Issue by sq-young2** [alibaba/Sentinel#2884]
因为RPC很多，每个都默认配置，比较繁琐，需要做一些默认的规则，正对所有接口支持，看到也有相关的Issues，但是貌似都没有结果，感谢回复哦！

**Comment by sczyh30** [comment]
如果是默认熔断规则，会在 Sentinel 2.0 中支持，可以参考 #66

**Comment by liuligang9527** [comment]
> 如果是默认熔断规则，会在 Sentinel 2.0 中支持，可以参考 #66

请问现在哪个版本支持全局熔断规则配置呢
