### ISSUE TITLE
Sentinel integration openFeign startup error problem ?

### ISSUE THREAD

**Issue by cheng-qiang** [alibaba/Sentinel#2894]
### 在aop中调用了feign 启动报错内容如下（Called feign in aop and started with the following error）
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-01 09:55:27.230 ERROR 29032 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'loginAdvice': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.btks.service.feign.LoginLogApiService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalAccessError: tried to access class org.springframework.cloud.openfeign.FeignClientFactoryBean from class com.alibaba.cloud.sentinel.feign.SentinelFeign$Builder$1

### 预期应该正常启动，因为把Sentinel关闭可以正常启动（It is expected that it should start normally, because turning Sentinel off will start normally）

```
feign:
  sentinel:
    enabled: false
```
### 

### 环境版本

```
spring clould Aalibaba 2021.1
spring boot 2.3.0.RELEASE 
spring clould Hoxton.SR5

```

**Comment by cheng-qiang** [comment]
有兄弟遇到过这种问题吗？

**Comment by cheng-qiang** [comment]
版本原因：
   spring clould Hoxton.SR5  升级为Hoxton.SR9
   spring clould Aalibaba 2021.1  降级为2.2.1.RELEASE
已解决！

**Comment by zhoushuai1119** [comment]
兄弟，我也是报这个错，feign.sentinel.enabled: false 正常启动，不改版本能解决这个问题嘛？
