### ISSUE TITLE
只用sentinel-core怎么动态添加规则

### ISSUE THREAD

**Issue by lt-dh** [alibaba/Sentinel#2910]
刚开始我使用FlowRuleManager.loadRules，但它会影响之前的设置的规则。
如何在不影响之前规则的前提下，添加规则。
感谢回答！

**Comment by lt-dh** [comment]
我看sentinel服务端调用客户端更新的时候用的也是FlowRuleManager.loadRules(rules);
意思是这样写不会影响之前的规则吗

**Comment by yanxianchao** [comment]
看了一圈代码，调用这个方法（FlowRuleManager.loadRules），入参必须是全量的规则。可以先调用FlowRuleManager.getRules，添加上新的规则，然后再调用这个全量方法（FlowRuleManager.loadRules）。

**Comment by lt-dh** [comment]
> 看了一圈代码，调用这个方法（FlowRuleManager.loadRules），入参必须是全量的规则。可以先调用FlowRuleManager.getRules，添加上新的规则，然后再调用这个全量方法（FlowRuleManager.loadRules）。

我就是在纠结，如果再次调用loadRules，会不会影响之前已经load的rules的窗口。
比如说第一次load了个名为“a”的100qps的规则，如果"a"资源在500ms内请求了100次。这时候我又load了一下名为“a”的规则，这时候这个“a"在前500ms还能再请求吗？正在看代码中……

**Comment by yanxianchao** [comment]
> > 看了一圈代码，调用这个方法（FlowRuleManager.loadRules），入参必须是全量的规则。可以先调用FlowRuleManager.getRules，添加上新的规则，然后再调用这个全量方法（FlowRuleManager.loadRules）。
> 
> 我就是在纠结，如果再次调用loadRules，会不会影响之前已经load的rules的窗口。 比如说第一次load了个名为“a”的100qps的规则，如果"a"资源在500ms内请求了100次。这时候我又load了一下名为“a”的规则，这时候这个“a"在前500ms还能再请求吗？正在看代码中……

不会影响，rule的身上存储的只有规则，qps存储在node上面，node又和slot关联，同一个资源使用同一组slot。例如存储全局qps是这个地方：com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterBuilderSlot#clusterNode

**Comment by lt-dh** [comment]
> 



> > > 看了一圈代码，调用这个方法（FlowRuleManager.loadRules），入参必须是全量的规则。可以先调用FlowRuleManager.getRules，添加上新的规则，然后再调用这个全量方法（FlowRuleManager.loadRules）。
> > 
> > 
> > 我就是在纠结，如果再次调用loadRules，会不会影响之前已经load的rules的窗口。 比如说第一次load了个名为“a”的100qps的规则，如果"a"资源在500ms内请求了100次。这时候我又load了一下名为“a”的规则，这时候这个“a"在前500ms还能再请求吗？正在看代码中……
> 
> 不会影响，rule的身上存储的只有规则，qps存储在node上面，node又和slot关联，同一个资源使用同一组slot。例如存储全局qps是这个地方：com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterBuilderSlot#clusterNode



> > > 看了一圈代码，调用这个方法（FlowRuleManager.loadRules），入参必须是全量的规则。可以先调用FlowRuleManager.getRules，添加上新的规则，然后再调用这个全量方法（FlowRuleManager.loadRules）。
> > 
> > 
> > 我就是在纠结，如果再次调用loadRules，会不会影响之前已经load的rules的窗口。 比如说第一次load了个名为“a”的100qps的规则，如果"a"资源在500ms内请求了100次。这时候我又load了一下名为“a”的规则，这时候这个“a"在前500ms还能再请求吗？正在看代码中……
> 
> 不会影响，rule的身上存储的只有规则，qps存储在node上面，node又和slot关联，同一个资源使用同一组slot。例如存储全局qps是这个地方：com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterBuilderSlot#clusterNode

**感谢**指点，刚才测试了一下，确实没影响。具体代码层次，我再看一下。
