### ISSUE TITLE
1.8.5版本控制台配置集群流控规则不生效

### ISSUE THREAD

**Issue by thylovepxm** [alibaba/Sentinel#2916]
1.8.5版本控制台配置集群不生效，配置了流控规则为集群

**Comment by sczyh30** [comment]
可以参考[文档](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89)改造并使用 V2 版本页面。

**Comment by thylovepxm** [comment]
看了源码需要在控制台配置如下才会进入集群限流逻辑
![image](https://user-images.githubusercontent.com/61415261/197126090-89fa34e8-8012-4e67-aab0-1d161353cd67.png)

clusterServer会根据client传入的flowId获取对应规则。如果是控制台如上配置，如何获取flowId并且配置在nacos呢

**Comment by sczyh30** [comment]
> 可以参考[文档](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89)改造并使用 V2 版本页面。

参考该文档改造控制台，通过控制台向 Nacos 推送规则，即会自带 flowId.
