### ISSUE TITLE
Deprecated dependency and code in ZK data-source | sentinel-datasource-zookeeper中有关于curator的过时代码

### ISSUE THREAD

**Issue by TQSsssss** [alibaba/Sentinel#2928]
版本： 
dubbo：2.7.16
            sentinel：1.8.5
            sentinel-datasource-zookeeper ：1.8.5
问题：
java.lang.NoSuchMethodError: org.apache.curator.framework.recipes.cache.NodeCache.getListenable()Lorg/apache/curator/framework/listen/ListenerContainer;
原因：
curator-recipes中的NodeCache在5.x版本已经更改为CuratorCache，sentinel源代码中仍为NodeCache，在监听数据源时报错。
期待有大神能给出解决方案

**Comment by TQSsssss** [comment]
已解决 解决方案：自定义实现ZookeeperDataSource类  修改内部NodeCache与NodeCacheListener相关方法，改为CuratorCache与CuratorCacheListener，修改相应逻辑

**Comment by sczyh30** [comment]
This has been resolved via #2963
