### ISSUE TITLE
About the spelling error in EagleEye.class   

### ISSUE THREAD

**Issue by JasmineXiaozzz** [alibaba/Sentinel#2930]
## Issue Description

Type: Code specification

 I think maybe it's a code specification problem? although the method is not being used.

Method name should probably be setEagleEyeSelfAppender, right?

 
```java
public final class EagleEye {
    ...
    // 
    static void setEagelEyeSelfAppender(EagleEyeAppender appender) {
        selfAppender = appender;
    }
}
```

If it needs to be modified, maybe I can submit a PR as the first PR for my participation in sentinel ^^

**Comment by sczyh30** [comment]
Hi, would you like to contribute a PR to fix it?
