### ISSUE TITLE
com.alibaba.cloud整合sentinel，都是最新RELEASE版本，SentinelResource埋点，但没有配置任何熔断规则，程序只要异常了，一直走fallback。是为什么？

### ISSUE THREAD

**Issue by zj5180** [alibaba/Sentinel#2938]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zj5180** [comment]
org.springframework.cloud整合sentinel，程序异常，只要没达到异常比例，是没有这个问题的。

**Comment by sczyh30** [comment]
`@SentinelResource` 注解的 fallback 及 defaultFallback 会处理所有的异常，而不仅只是熔断异常。参考文档：https://sentinelguard.io/zh-cn/docs/annotation-support.html

---

It's by-design. Refer https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj
