### ISSUE TITLE
Add support for OpenSergo ConcurrencyLimitStrategy in sentinel-datasource-opensergo

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#2942]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Add support for OpenSergo `ConcurrencyLimitStrategy` in [sentinel-datasource-opensergo](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-datasource-opensergo).

The `ConcurrencyLimitStrategy` should also be converted to `FlowRule`, with grade=0 (metricType=concurrency).

Umbrella issue: #2841

**Comment by selectbook** [comment]
Hello, I'm interested in contributing to this issue. can I hava a try?

**Comment by XW512** [comment]
I'm looking forward to the official release of this version

**Comment by sczyh30** [comment]
> Hello, I'm interested in contributing to this issue. can I have a try?

Hi, contributions are welcome! You may refer to existing implementation: https://github.com/alibaba/Sentinel/pull/2842
