### ISSUE TITLE
SentinelRpcException may not logged in dubbo provider'log 

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#295]
当BlockException产生时 SentinelDubboProviderFilter默认使用DefaultDubboFallback抛出了SentinelRpcException(继承至RuntimeException)；

线上环境某个应用(provider）某接口配置了降级规则，出现降级时日志中打印了如下异常信息：
[ERROR] com.alibaba.dubbo.rpc.filter.ExceptionFilter [90] -  [DUBBO] Got unchecked and undeclared exception which called by ...
exception: com.alibaba.csp.sentinel.slots.block.SentinelRpcException: com.alibaba.csp.sentinel.slots.block.degrade.DegradeException, dubbo version: 2.5.4.2, current host: 10.1.5.81
com.alibaba.csp.sentinel.slots.block.SentinelRpcException: com.alibaba.csp.sentinel.slots.block.degrade.DegradeException
Caused by: com.alibaba.csp.sentinel.slots.block.degrade.DegradeException: null

而在运行sentinel dubbo demo1时，出现BlockException时，consumer端有异常信息打印，provider端没有任何日志输出；

经排查发现是线上环境该应用用的jdk1.7，本机demo用的jdk1.8，dubbo应用启动ProtocolFilterWrapper#buildInvokerChain时，ExtensionLoader获取filters后排序的问题，
线上dubbo自带的ExceptionFilter排在SentinelDubboProviderFilter的前面；
demo1中的ExceptionFilter排在SentinelDubboProviderFilter后面，所以demo1中异常信息不打印；

排序方法：
Collections.sort(exts, ActivateComparator.COMPARATOR);

而在排序之前,List<T> exts是通过loadExtensionClasses加载的
loadFile(extensionClasses, DUBBO_INTERNAL_DIRECTORY);
loadFile(extensionClasses, DUBBO_DIRECTORY);
loadFile(extensionClasses, SERVICES_DIRECTORY);
Map<String, Activate> cachedActivates.put(names[0], activate);

推测是因为jdk1.7和jdk1.8的hash算法不同，导致cachedActivates put后filters顺序不同，
ActivateComparator.COMPARATOR中比较order了的大小，
SentinelDubboProviderFilter和ExceptionFilter均没有配置order，默认都为0，
排序结果不定，跟排序之前的顺序有关。

这里想讨论下在provider端是否有必要记录sentinel的限流异常？
个人觉得应该记录，否则provider端日志一切正常，用户查看日志时不知道发生了限流或降级；
不过sentinel控制台的监控数据以及sentinel-block.log中也有了记录。

如果使用dubbo的自带的ExceptionFilter记录日志，
可考虑：
1.用相对排序，SentinelDubboProviderFilter指定在ExceptionFilter后面
@Activate(group = "provider"， after="exception")
public class SentinelDubboProviderFilter
但是很奇怪，dubbo最新版该注解的before和after两个方法标注了deprecated，
实测这个两个方法是有效的，使用方便；
参考：https://github.com/apache/incubator-dubbo/issues/2180

2.用绝对排序，因ExceptionFilter没有指定order默认是0，
参考EchoFilter order=-110000、ContextFilter order = -10000，SentinelDubboProviderFilter用负数即可
@Activate(group = "provider"， order="-1000")
public class SentinelDubboProviderFilter

3.SentinelDubboProviderFilter不变，用户自己在dubbo应用配置中指定：
<dubbo:service filter="sentinel.dubbo.provider.filter,default" />
但这样需要每个应用都添加
参考：http://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html

**Comment by sczyh30** [comment]
Hi, all aggregated block logs are provided in `sentinel-block.log`, which is more clear than raw `BlockException`, so may be it's not necessary to enable block exception logging in Dubbo `ExceptionFilter`.

By the way, thanks for your explanation for the different sort order of the filters in different JDK version :)

**Comment by cdfive** [comment]
@sczyh30 是的，sentinel也有监控的日志记录。开始很纠结的原因有2个：
1.provider自己的应用日志里没有记录流控异常的话，用户可能忽略或者忘记sentinel-block.log，应用日志可以考虑搜集到ELK里，在界面方便查询；
2.ExceptionFilter里打印的异常堆栈信息更丰富一些，比如把调用方的ip也打印了的；

把ExceptionFilter放到SentinelDubboProviderFilter后面，打印异常也有它的问题：
try {
    Result result = invoker.invoke(invocation);
    ...
} catch (RuntimeException e) {
    logger.error("Got unchecked and undeclared exception...
    throw e;
}

ExceptionFilter注释里写了，它的设计初衷是尽可能保证consumer端不反序列化失败，
这里进到catch块，会将SentinelRpcException抛出
在HeaderExchangeHandler里StringUtils.toString(e)
consumer端也捕获不到SentinelRpcException，
ExceptionFilter这么做没问题，因为cosumer端可能没有sentinel的依赖包。

如果provider接口里抛的业务异常，比如checked或者在方法签名上，在ExceptionFilter里也走不到logger.error()分支的，日志里就没有log.error打印。

完全依赖ExceptionFilter在log日志里记录Provider所有异常也并不合适。
可能需要具体应用或者规范上，设计一个按分类记录异常的方法，比如自定义Filter或者改造ExceptionFilter。最佳实践还有待讨论了。

在ExceptionFilter记录流控异常确实不是必要的，用户需要也可以自己指定Filter顺序。
请关下这个issue哈，thx!
