### ISSUE TITLE
希望贡献一个sentinel-operator来控制dashboard的生命周期，不知社区是否接受？

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/Sentinel#2952]
## Issue Description

sentinel-operator

**Comment by sczyh30** [comment]
可否请具体描述一下你的设计？

**Comment by wilsonwu** [comment]
具体的实现是通过k8s operator机制来控制sentinel-dashboard的生命周期，其中实现CRD，通过自定义资源（CR）简单部署和维护dashboard的deployment和service，同时可以支持dashboard高可用，通过CR可以监测到dashboard运行状态等信息，方便用户基于k8s来统一和简化管理一个或多个sentinel-dashboard实例。

**Comment by sczyh30** [comment]
Good idea. 基于以上的思想，可否帮忙形成一份详细的设计文档 社区可以一起讨论下

**Comment by wilsonwu** [comment]
OK，我稍后基于CR贴出来描述一下功能，operator实现比较标准，就不拿出来讨论了。

**Comment by wilsonwu** [comment]
```
apiVersion: trafficflow.sentinel.io/v1alpha1
kind: Sentinel
metadata:
  creationTimestamp: '2022-11-16T08:15:41Z'
  generation: 1
  managedFields:
    - apiVersion: trafficflow.skoala.daocloud.io/v1alpha1
      ......
    - apiVersion: trafficflow.skoala.daocloud.io/v1alpha1
      ......
  name: test-sentinel1
  namespace: default
  resourceVersion: '133763902'
status:
  phase: Running
spec:
  env:
    - name: NACOS_ADDRESS
      value: nacos-test.default:8848
  image: sentinel:v0.3.4
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  replicas: 1
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: '1'
      memory: 1Gi
  type: NodePort
```
上面是最终的sentinel-dashboard CR，目前比较简单，可以简化配置各类参数，同时支持sentinel-dashboard的状态读取，目前我们内部使用已经实现了和nacos配置中心的配置管理联动（不过这部分非强制，完全可以使用社区版本的sentinel-dashboard程序对其生命周期进行管理），如果社区觉得这个模式可用的话我们愿意把全部代码贡献到社区，后续应该会给予此产生更多云原生化的需求和迭代，我们也愿意全面参与共建。

**Comment by sczyh30** [comment]
欢迎提交贡献（可以考虑单独放一个 repo）

**Comment by wilsonwu** [comment]
> 欢迎提交贡献（可以考虑单独放一个 repo）

是的，放一个独立repo会好一点，不会影响目前的流程，那么请帮忙建立一个repo，我把相关贡献者加入进来。

**Comment by wilsonwu** [comment]
I saw the repo: https://github.com/sentinel-group/sentinel-k8s-crd

So I close this issue and let's discuss in the new repo.

**Comment by sczyh30** [comment]
See https://github.com/sentinel-group/sentinel-dashboard-k8s-operator
