### ISSUE TITLE
集群模式下启动server，为什么要访问一次，才能在控制台看到？

### ISSUE THREAD

**Issue by weishiya** [alibaba/Sentinel#2959]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by weishiya** [comment]
transport模块SPI加载HeartbeatSenderInitFunc，加载完就有心跳线程了呀。为什么要访问一次才能在dashaboard看到呢？
`scheduleHeartbeatTask`

**Comment by wilsonwu** [comment]
![image](https://user-images.githubusercontent.com/1269496/203788497-1e5b15bb-5901-4cda-bee3-d13ad164f5e8.png)

加上这个参数就可以直接看到了。

**Comment by weishiya** [comment]
> ![image](https://user-images.githubusercontent.com/1269496/203788497-1e5b15bb-5901-4cda-bee3-d13ad164f5e8.png)
> 
> 加上这个参数就可以直接看到了。

为甚么呢？背后的原理是什么？

**Comment by wilsonwu** [comment]
> > ![image](https://user-images.githubusercontent.com/1269496/203788497-1e5b15bb-5901-4cda-bee3-d13ad164f5e8.png)
> > 加上这个参数就可以直接看到了。
> 
> 为甚么呢？背后的原理是什么？

就是这样设计的。

**Comment by wilsonwu** [comment]
So can we close this issue? @weishiya

**Comment by weishiya** [comment]
> So can we close this issue? @weishiya

我想知道背后的原理，因为SPI加载完HeartbeatSenderInitFunc类就有心跳线程了，为什么还要访问一次呢？

**Comment by sczyh30** [comment]
这个和是否集群流控无关，默认情况下首次访问才会触发 Sentinel 初始化，各个 InitFunc 才会执行到。

You may also refer to https://github.com/alibaba/Sentinel/wiki/FAQ
