### ISSUE TITLE
集群流控服务端无法接到客户端的任何请求

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [alibaba/Sentinel#2969]
## Issue Description
依赖1.8.6版本

尝试搭建独立服务端的集群流控，发现客户端与服务端建立连接后无法正常通信。请求永远超时。

测试代码如下：
客户端，不配置命名空间，直连服务端
```
public class ClusterClientInitFunc implements InitFunc {
    @Override
    public void init() throws Exception {
        ClusterStateManager.setToClient();
        ClusterClientConfig clusterClientConfig = new ClusterClientConfig();
        clusterClientConfig.setRequestTimeout(2000);

        ClusterClientConfigManager.applyNewConfig(clusterClientConfig);
        ClusterClientAssignConfig assignConfig = new ClusterClientAssignConfig();
        assignConfig.setServerHost("127.0.0.1");
        assignConfig.setServerPort(11111);
        ClusterClientConfigManager.applyNewAssignConfig(assignConfig);
    }
}
```
服务端配置，不需要任何数据源，直接启动
```
public class ClusterServerDemo {
    public static void main(String[] args) throws Exception {
        // Not embedded mode by default (alone mode).
        ClusterTokenServer tokenServer = new SentinelDefaultTokenServer();

        // A sample for manually load config for cluster server.
        // It's recommended to use dynamic data source to cluster manage config and rules.
        // See the sample in DemoClusterServerInitFunc for detail.
        ClusterServerConfigManager.loadGlobalTransportConfig(new ServerTransportConfig()
            .setIdleSeconds(60000)
            .setPort(11111));
        // Start the server.
        tokenServer.start();
    }
}
```

不知道原生的`sentinel-cluster-client-default`与`sentinel-cluster-server-default`是否对Namespace配置有强依赖，我在初步尝试的时候发现，服务端只能接到第一次建立连接的消息。并打印如下日志：
```
10:25:17.950 [nioEventLoopGroup-2-1] INFO io.netty.handler.logging.LoggingHandler - [id: 0xfc1b425d, L:/0:0:0:0:0:0:0:0:11111] READ: [id: 0x7a348cdc, L:/127.0.0.1:11111 - R:/127.0.0.1:57864]
10:25:17.951 [nioEventLoopGroup-2-1] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_TIMEOUT' for channel '[id: 0x7a348cdc, L:/127.0.0.1:11111 - R:/127.0.0.1:57864]'
10:25:17.952 [nioEventLoopGroup-2-1] INFO io.netty.handler.logging.LoggingHandler - [id: 0xfc1b425d, L:/0:0:0:0:0:0:0:0:11111] READ COMPLETE
```
而后无论集群流控客户端如何发送信息，Server端均无法接收Client端发送的消息。服务端Netty组件的根接口中的`fireChannelRead`方法从未触发。在关闭客户端时，服务端报远程主机关闭连接，我猜想源码在某个位置的连接就已经出问题了，导致后续requestToken操作都被认为是第一个请求未完成传输一直等待。。。
但问题在于，第一个请求追踪源码发现在ServerBootstrap设定过监听后连接建立，后续请求并没有走到相关`ByteToMessageDecoder`实现类的任何decode方法中。。。

同时通过源码追踪到服务端`NettyTransportServer`中注册的如下几个handler中的所有方法，除`channelActive`外从未被触发
`LengthFieldBasedFrameDecoder`
`NettyRequestDecoder`
`LengthFieldPrepender`
`NettyResponseEncoder`
`TokenServerHandler`

而追踪到`channelActive`也没有报错，不是很明白这里问题出在哪里。。。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Windows 10 开发环境

**Comment by WilliamChen-luckbob** [comment]
自己构建的Netty请求可以每次正确到达服务端，怀疑是客户端源码封装请求的时候出了什么奇怪的问题，导致终止位没判断到？直接复制客户端代码也是一定发送失败，怀疑为题出在客户端的一些Decoder或Encoder上，自己构建的简单请求是正常的

**Comment by udotekbjx** [comment]
你好，请问下这个问题解决了么？我也遇到类似的问题，客户端请求的数据发现长度过长了，导致服务端无法接口....
![image](https://github.com/alibaba/Sentinel/assets/28891087/ba9073a7-25bf-4359-b366-921fa7a495bb)

**Comment by WilliamChen-luckbob** [comment]
> 你好，请问下这个问题解决了么？我也遇到类似的问题，客户端请求的数据发现长度过长了，导致服务端无法接口.... ![image](https://user-images.githubusercontent.com/28891087/278274549-ba9073a7-25bf-4359-b366-921fa7a495bb.png)

已经解决了，最后是自己基于netty手敲的一整套集群流控客户端和服务端
