### ISSUE TITLE
Add support for Spring Boot 3.x (Spring 6.x)

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#2986]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Add support for Spring Boot 3.x (Spring 6.x). The following adapters might need to be checked or updated:

* [sentinel-spring-webmvc-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webmvc-adapter)
* [sentinel-zuul-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-zuul-adapter)
* [sentinel-spring-webflux-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webflux-adapter)
* [sentinel-spring-cloud-gateway-adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-cloud-gateway-adapter)

Also refer #2998 for raw Jakarta EE support.

**Comment by JavaLionLi** [comment]
期待啊

**Comment by LiYangSir** [comment]
I can try it

**Comment by Prince-1110** [comment]
If this issue is not resolved yet, can I work on it?

**Comment by SahanSamarakoon** [comment]
@sczyh30 Is this issue still open ?

**Comment by saikrishnasaski** [comment]
Is this issue still open?

**Comment by ilaotan** [comment]
Is this issue still open?

**Comment by mhraza95** [comment]
Hi @sczyh30 , If this issue still open, can i work on this?
