### ISSUE TITLE
[Feature] DataSource integration for etcd

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#30]
## Issue Description

Type: *feature request*

### Describe what feature you want

Add DataSource integration for etcd.

**Comment by ZhangShangyu** [comment]
support etcd2 or 3? 😊

**Comment by sczyh30** [comment]
> support etcd2 or 3? 😊

All can be supported if needed. Would you like to contribute？:)

**Comment by linlinisme** [comment]
I will fix this soon :)

**Comment by zhaoyuguang** [comment]
> I will fix this soon :)

Can i try it？

**Comment by zhaoyuguang** [comment]
> > I will fix this soon :)
> 
> Can i try it？
> 
> I had almost completed in my local, may be you offer some suggestions in my pr.

Okay, I was scared 😂, I was still thinking about how `I had almost completed in my local, may be you offer some suggestions in my pr.`  Later I found out that you have made my reply.
