### ISSUE TITLE
How can I connect redis with ssl on sentinel-datasource-redis | Redis 数据源支持 SSL

### ISSUE THREAD

**Issue by BooAndBoCai** [alibaba/Sentinel#3000]

**Comment by sczyh30** [comment]
It's not supported yet. Would you like to contribute a PR to improve it?

**Comment by z521598** [comment]
Can I try it? Please assigned it to me.

**Comment by z521598** [comment]
> It's not supported yet. Would you like to contribute a PR to improve it?


Can I try it? Please assigned it to me.

**Comment by sczyh30** [comment]
> > It's not supported yet. Would you like to contribute a PR to improve it?
> 
> Can I try it? Please assigned it to me.

@z521598  Contributions are welcome!
