### ISSUE TITLE
Sentinel控制台没有显示我的应用

### ISSUE THREAD

**Issue by chanfy333** [alibaba/Sentinel#301]
按照文档部署：
1、下载sentinel-dashboard-1.3.0.jar，执行命令运行：
$java_path -Dserver.port=$port -Dcsp.sentinel.dashboard.server=$ip:$port -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.3.0.jar
2、打开控制台是OK的：
![image](https://user-images.githubusercontent.com/28379229/49931674-5c65e800-ff02-11e8-9c0f-9056d9f5bc9d.png)

3、dubbo provider工程（spring版本：3.2.0，dubbo版本：2.5.3，JDK版本：1.6）的maven配置：
![image](https://user-images.githubusercontent.com/28379229/49931725-7acbe380-ff02-11e8-8a60-f1180995dfeb.png)

4、部署我的dubbo provider工程，并配置好JVM启动参数：
![image](https://user-images.githubusercontent.com/28379229/49931895-d8603000-ff02-11e8-9587-229c5e855cd5.png)

以上都配置OK，并且服务正常运行未报错，dubbo provider的dubbo接口有调用，但在 sentinel的控制台还是没发现我的dubbo provider服务

**Comment by sczyh30** [comment]
Can you use your IDE debugger in local to test whether the logic of Sentinel Dubbo filters have been executed?

---

可否本地 debug 一下看看是否进入了 Sentinel Dubbo Filter 的代码块内？请参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) 查看日志看看有无异常，并测试 transport API `<ip>:<port>`  是否可访问。
