### ISSUE TITLE
gateway and sentinel   Is displayed in the resource name of the cluster link  sentinel_gateway_context$$route$$application_name

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/Sentinel#3020]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Is displayed in the resource name of the cluster link sentinel_gateway_context$$route$$application_name

Illustrate by example

Service name: mall
Current limiting interface configuration /mall/test/1 The qps value is 10

Requests for other interfaces under this service (/mall/a) are also affected by this traffic limiting

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
springboot 2.3.12.RELEASE 
spring cloud Hoxton.SR12
spring cloud alibaba 2.2.9.RELEASE

### Anything else we need to know?
config is

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
#路由前缀配置
spring.cloud.gateway.discovery.locator.routeIdPrefix=wn_

#sentinel配置
spring.cloud.sentinel.eager=true
#dashboard配置
spring.cloud.sentinel.transport.dashboard=192.168.108.1:8888
spring.cloud.sentinel.filter.enabled=false

images is

![image](https://user-images.githubusercontent.com/21052733/212919518-bcd36674-9e1e-4e6a-906e-7ac185363938.png)

limit rule 

gateway.flow.rules=[{"resource":"mall-service","apiDefinitions":[{"matchStrategy":0,"pattern":"/mall-service/test"}],"count":10,"intervalSec":1,"controlBehavior":0}]

The other interface (/mall/a) that I use for mall service is also restricted

**Comment by silent-night-no-trace** [comment]
My local environment appears as a request link and becomes a cluster point link when deployed to the test environment
The resource name of the cluster link is sentinel_gateway_context$$route$$application-name

**Comment by silent-night-no-trace** [comment]
However, a new problem occurred when the resource name was changed to the interface name and the traffic limiting rule was specified and the traffic limiting failed

**Comment by silent-night-no-trace** [comment]
Now there are two cases: the first traffic limiting rule resource name is set to the name of the micro-service and the custom interface API interface can be successfully restricted but other undefined interfaces of the micro-service will also be affected by traffic limiting
The second traffic limiting rule, the resource name is configured as the interface name and watch as the cluster link in dashborad becomes such a structure as the first layer of sentinel_gateway_context$$route$$combo-service combo-service caused loss limit to take effect. Is there any solution to this problem 
@sczyh30   can you help me

**Comment by silent-night-no-trace** [comment]
Observe the source under the specific in com.alibaba.csp.sentinel.adapter.gateway.sc.SentinelGatewayFilter#filter 
The route is matched and then asyncResult.transform is executed
Next, a custom API match is performed to match asyncResult.transform

**Comment by silent-night-no-trace** [comment]
First, the gateway can limit traffic based on routes and customized urls

If the route matches but the interface is not in the custom URL, this will also be restricted whether it is a bug

Whether traffic limiting rules can be implemented with different user-defined urls for the same route

**Comment by silent-night-no-trace** [comment]
the end ...
Previously, dashboard deployed the gateway and other services separately on the test server were in k8s

Everything was fine when the dashboard was deployed in the same k8s environment

**Comment by silent-night-no-trace** [comment]
结论保证和 dashbaord和 gateway以及其他的应用 处于同一个环境中 要在k8s 环境就都部署在k8s环境

**Comment by silent-night-no-trace** [comment]
Conclusion Make sure you are in the same environment as dashbaord and gateway and other applications and deploy them in k8s

**Comment by silent-night-no-trace** [comment]
相关问题都整理到了 博文中  https://blog.csdn.net/a15835774652/article/details/128643458

**Comment by sczyh30** [comment]
针对这里面遇到的问题，如果有一些完善点或建议的话 欢迎提 issue 进行贡献哈~

**Comment by silent-night-no-trace** [comment]
好，感谢大佬回复
