### ISSUE TITLE
sentinel中文用户文档——系统自适应保护中介绍的修改建议

### ISSUE THREAD

**Issue by LG772EF** [alibaba/Sentinel#3034]
## Issue Description

介绍表述不通顺，理解容易产生歧义。
位置：用户文档 -> 使用文档 -> 系统自适应保护，原理部分介绍，推论二
原描述信息为：“推论二:　当保持入口的流量是水管出来的流量的最大的值的时候，可以最大利用水管的处理能力。”
修改建议：“推论二:　当保持入口的流量使水管出来的流量达到最大值的时候，可以最大利用水管的处理能力。”

对应网址：https://sentinelguard.io/zh-cn/docs/system-adaptive-protection.html

**Comment by jnan806** [comment]
@LG772EF  Are you interested in fixing this typo 😃
