### ISSUE TITLE
1.4.0版本控制台在集群视图下不能删除流控规则

### ISSUE THREAD

**Issue by foreveryang321** [alibaba/Sentinel#304]
版本：sentinel-dashboard-1.4.0.jar
问题：
在簇点链路下对资源新建流控规则，切换到集群视图下不能删除流控规则，切换到旧版（单机）可以删除规则

**Comment by sczyh30** [comment]
Hi, could you please illustrate how to reproduce the problem and related error information (e.g. frontend API response)?

**Comment by sczyh30** [comment]
Besides, the new flow rule page (v2) is designed for using dynamic rule data source. The default implementation is only a adaptor for legacy pushing API. For the detail of the new flow rule page, please refer to [document](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0---%E9%9B%86%E7%BE%A4%E9%99%90%E6%B5%81).
