### ISSUE TITLE
单独使用sentinel时可以给 Web api分组吗 | API group for normal Web app

### ISSUE THREAD

**Issue by learsea** [alibaba/Sentinel#3040]
## Issue Description
我现在在开发一个spring boot web项目需要用到sentinel，但是又不需要引入网关，我查阅了资料知道整合网关之后可以使用网关的路由或者api分组。如果不整合网关可以用到api分组的功能吗？因为单独给每一个接口设置限流确实有点麻烦

Type: feature request

### Describe what happened (or what feature you want)
在不引入网关的情况下给一批API设置同样的限流规则

**Comment by sczyh30** [comment]
这个暂不支持，如有需要可以 interceptor 自定义埋点来做哈.
