### ISSUE TITLE
从Hystrix迁移到Sentinel遇到一个问题，关于hystrix timeoutInMilliseconds 的迁移

### ISSUE THREAD

**Issue by edgar1170** [alibaba/Sentinel#3047]
请问hystrix针对命令的超时限制配置，有没有办法迁移到Sentinel对应功能？
比如配置了如下参数：
hystrix.command.default.execution.timeout.enabled  true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds   8000
代表在接口耗时超过8s的时候会被hytrix终止，然后判定为超时并报错
那么在Sentinel是否存在对应的配置呢，目前好像并未存在该功能？

**Comment by sczyh30** [comment]
超时掐断调用的模型目前未支持，可参考 https://github.com/alibaba/Sentinel/wiki/Sentinel-与-Hystrix-的对比
