### ISSUE TITLE
LogSlot处理BlockException异常问题 | LogSlot NPE when recording BlockException

### ISSUE THREAD

**Issue by liwen2555376** [alibaba/Sentinel#3057]
SystemRuleManager checkSystem 的时候会抛出 throw new SystemBlockException(resourceWrapper.getName(), "cpu"); 异常。然后在LogSlot 里会处理 BlockException 异常。但是抛出的SystemBlockException 并没有设置 rule 属性。导致空指针异常。
![image](https://user-images.githubusercontent.com/32069447/224520951-311caf5a-8eab-4257-a3a9-97508f128a62.png)
![image](https://user-images.githubusercontent.com/32069447/224521068-bd584f58-6384-462f-870b-f707509bea89.png)
![image](https://user-images.githubusercontent.com/32069447/224520980-58ee8fba-3dbb-40f7-b1e1-61e33cc9380b.png)

抛出的异常，并没有设置 rule 属性

**Comment by liwen2555376** [comment]
![image](https://user-images.githubusercontent.com/32069447/224520980-58ee8fba-3dbb-40f7-b1e1-61e33cc9380b.png)

抛出的异常，并没有设置 rule 属性

**Comment by bchengwang** [comment]
> 



> 这已经通过#2980修复，并将在2.0.0中发布。您可以尝试[v2.0.0-alpha](https://github.com/alibaba/Sentinel/releases/tag/2.0.0-alpha)。

请问这个补丁会在1.8.6的版本上合并吗？目前Spring Cloud Alibaba2022 和 2021使用的都是 1.8.6版本的Sentinel
