### ISSUE TITLE
为什么SphU类的entry方法要默认EntryType.OUT而不是EntryType.IN呢?

### ISSUE THREAD

**Issue by liwen2555376** [alibaba/Sentinel#3067]
![image](https://user-images.githubusercontent.com/32069447/225514112-bf095723-52c2-4f8a-8d83-abba95c68595.png)更多的情况 不是使用EntryType.IN 吗？默认EntryType.OUT 每次都需要显示指定EntryType.IN。这样设计是出于怎样的考虑？

**Comment by luffy0223** [comment]
EntryType用于区分流量类型，即入口流量与出口流量，默认流量类型为出口流量的目的是为了保障这部分资源不会因为SystemRule系统自适应限流所影响，系统自适应限流只对入口流量做流控。比如Dubbo的调用链路，Consumer与Provider两个节点的系统指标冲高时，Consumer无需对出口流量做流控，因为系统的消耗并不是因为出口流量导致的，而Provider需要对入口流量做流控，防止更多流量流入进一步冲高系统指标。
见方法签名注释中对trafficType的解释。
/**
     * Record statistics and perform rule checking for the given resource.
     *
     * @param name        the unique name for the protected resource
     * @param trafficType the traffic type (inbound, outbound or internal). This is used
     *                    to mark whether it can be blocked when the system is unstable,
     *                    only inbound traffic could be blocked by {@link SystemRule}
     * @param batchCount  the amount of calls within the invocation (e.g. batchCount=2 means request for 2 tokens)
     * @return the {@link Entry} of this invocation (used for mark the invocation complete and get context data).
     * @throws BlockException if the block criteria is met
     */
    Entry entry(String name, EntryType trafficType, int batchCount) throws BlockException;

**Comment by liwen2555376** [comment]
Thank you for your answer
