### ISSUE TITLE
how should i make a degrade rule work

### ISSUE THREAD

**Issue by jackchow621** [alibaba/Sentinel#307]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
i config a degrade rule of dubbo  provider service method on degrade rule page, and my dashboard has showed my real-time app data,but i don't know if the rule works on,and i don't know what does these parameter mean. Can someone explain that? if my rule didn't work,how should i do to let it work? here is my dashborad:
![image](https://user-images.githubusercontent.com/30717485/50062285-519ca300-01e1-11e9-87a4-c8e79fa1379d.png)

### Describe what you expected to happen
hope someone can explain how to let a degrade rule work on

**Comment by sczyh30** [comment]
Hi, please refer to the [degrade rule document](https://github.com/alibaba/Sentinel/wiki/%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7) for guideline.

**Comment by sczyh30** [comment]
> i use the provider filter for Dubbo services, Do I need to record the bussiness exception like the demo or configure anything?

Sentinel Dubbo Adapter can record the biz exception automatically. You can just configure degrade rules in the dashboard, then the rule will take effect.
