### ISSUE TITLE
sentinel有没有办法能够实现对慢接口进行监控，监控到某个接口响应超过N秒

### ISSUE THREAD

**Issue by heqs** [alibaba/Sentinel#3074]
当某个接口响应超过N秒时，发送通知消息或者记录日志等操作（并不希望马上进行限流或熔断降级等）

**Comment by huang-gz** [comment]
这个超时发送记录是不是可以放到监控系统里来做，sentinel 还是专注于限流相关的工作

**Comment by heqs** [comment]
> 

是否可以推荐几个监控框架

**Comment by huang-gz** [comment]
https://github.com/dianping/cat， https://github.com/apache/skywalking  我知道这些应该都可以设置告警的，你可以试试
，我们用的是 CAT，你可以把你的限流异常也加到告警配置里，这样只要触发限流了你也可以立刻知道
