### ISSUE TITLE
在sentinel dashboard控制台添加规则后不显示，控制台也没有输出

### ISSUE THREAD

**Issue by TStaoshuai** [alibaba/Sentinel#3081]
## Issue Description
我的一个服务已经注册在了sentinel控制台，但是添加流控规则后列表没有显示
Type: *bug report*

### Describe what happened
我用的是1.8.2版本，服务已经注册在了dashboard，并且可以看到簇点链路和实时监控，但是在添加流控规则后刷新不出来规则，并且nacos也没有同步，控制台日志也没有任何输出

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Refer https://sentinelguard.io/zh-cn/docs/faq.html
