### ISSUE TITLE
Nacos因为在docker部署没有开放9848和9849端口导致流控规则刷新不出来

### ISSUE THREAD

**Issue by TStaoshuai** [alibaba/Sentinel#3085]
如果在日志里面体现没有ping通这两个端口的话，给一个提示最好，不然页面添加成功但是列表没有刷新出来，

**Comment by sczyh30** [comment]
可以具体描述下，这个场景下 Sentinel 里面日志是什么样子，有没有相关提示。

**Comment by TStaoshuai** [comment]
我们生产中因为nacos的是用容器化docker部署，nacos的版本是2.0的&nbsp; 但是运维忘记开放9848和9849两个端口，导致我在sentinel dashboard新增流控规则失败（虽然当时显示添加成功，但是流控规则列表刷新不出来），这时候sentinel dashboard 的日志没有显示错误，导致排查问题很困难，后来对比了没有容器化部署的nacos，发现少开放了这两个端口，于是添加了就正常了，我想提个建议，如果这种情况的话，能不能在控制台有报错信息，不然很难排查出来问题。谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 下午4:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/Sentinel] Nacos因为在docker部署没有开放9848和9849端口导致流控规则刷新不出来 (Issue #3085)





 
可以具体描述下，这个场景下 Sentinel 里面日志是什么样子，有没有相关提示。

**Comment by jnan806** [comment]
@TStaoshuai  
你的场景是否是：sentinel-dashaboard 改造成 nacos 数据源，由于部署环境原因，sentinel-dashboard 无法与 nacos 的端口进行通讯，而dashboard客户端提示添加成功，实际上没有添加的 nacos 中，而你需要的是有类似`无法连接 nacos`的提示。

不知我理解的是否正确？

**Comment by TStaoshuai** [comment]
是的，确实是运维同学部署nacos错误的原因造成的。
我是希望看到有这种提示或者错误信息，因为我F12看了接口返回和日志，一切都是正常的，导致排查问题比较麻烦！
谢谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiangnan ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 中午1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/Sentinel] Nacos因为在docker部署没有开放9848和9849端口导致流控规则刷新不出来 (Issue #3085)





 
@TStaoshuai
 你的场景是否是：sentinel-dashaboard 改造成 nacos 数据源，由于部署环境原因，sentinel-dashboard 无法与 nacos 的端口进行通讯，而dashboard客户端提示添加成功，实际上没有添加的 nacos 中，而你需要的是有类似无法连接 nacos的提示。
 
不知我理解的是否正确？

**Comment by jnan806** [comment]
关于这一点，我的想法是： sentinel-dashboard 本身是基于实时与 sentinel-client 进行交互的，规则直接存储在内存。既然你们在业务中，将 dashboard 通过扩展接入到 nacos 了，那么 sentinel-dashboard 在实例化 nacos-client 的时候是否可以进行与nacos-server端口的连通性的验证，或者在 nacos-client 向 nacos-server 发送数据的时候进行验证。

**Comment by TStaoshuai** [comment]
你说的有道理，与nacos的通信扩展提示我这边需要处理一下。
如果在页面添加添加规则，显示成功，但是刷新不出来，就意味着没有存储在内存，这个地方的提示可以方便加一下吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiangnan ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/Sentinel] Nacos因为在docker部署没有开放9848和9849端口导致流控规则刷新不出来 (Issue #3085)





 
关于这一点，我的想法是： sentinel-dashboard 本身是基于实时与 sentinel-client 进行交互的，规则直接存储在内存。既然你们在业务中，将 dashboard 通过扩展接入到 nacos 了，那么 sentinel-dashboard 在实例化 nacos-client 的时候是否可以进行与nacos-server端口的连通性的验证，或者在 nacos-client 向 nacos-server 发送数据的时候进行验证。

**Comment by jnan806** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/43714056/231960593-7513452b-2b44-4897-bd23-8a719121aa87.png">

添加规则的方法是有`try-catch`的，你的 nacos-client 在 publish 异常时，往外抛出 Exception 是否就达到你的期望了呢 😃

**Comment by TStaoshuai** [comment]
哈哈哈哈 好吧&nbsp; 可以的。 

谢谢你的回复！





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiangnan ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/Sentinel] Nacos因为在docker部署没有开放9848和9849端口导致流控规则刷新不出来 (Issue #3085)





 

 
添加规则的方法是有try-catch的，你的 nacos-client 在 publish 异常时，往外抛出 Exception 是否就达到你的期望了呢 😃
