### ISSUE TITLE
Flow control for batch request/operation | 批量操作的业务场景，有没有办法一次扣除多个资源

### ISSUE THREAD

**Issue by lwtao** [alibaba/Sentinel#3089]
业务代码中是涉及批量操作的，比方说每次批量更新1-100条数据，但限流的规则是1000次/S，那每次处理请求时，可以直接根据批量的参数个数来扣除资源数吗？还是说之内循环N次来达到限流效果？

**Comment by LiYangSir** [comment]
可以的，Sentinel 埋点支持传入acquireCount，默认值为 1。代表这一次请求会请求 acquireCount 数量的资源
代码入口：com.alibaba.csp.sentinel.SphU#entry(java.lang.String, int)

**Comment by sczyh30** [comment]
埋点详细解释可以参考 https://help.aliyun.com/document_detail/102559.html
