### ISSUE TITLE
[Release Need] Shell we release a new version with #2976

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/Sentinel#3093]
## Issue Description

Type: *feature request*

### Describe what feature you want

https://github.com/alibaba/Sentinel/pull/2976
Need a new version with this PR changes.

**Comment by wilsonwu** [comment]
@sczyh30 could you please release 1.8.7 with this change #2976

**Comment by sczyh30** [comment]
> @sczyh30 could you please release 1.8.7 with this change #2976

Hi, you may use [2.0.0-alpha](https://github.com/alibaba/Sentinel/releases/tag/2.0.0-alpha), where it's already included.

**Comment by wilsonwu** [comment]
> > @sczyh30 could you please release 1.8.7 with this change #2976
> 
> Hi, you may use [2.0.0-alpha](https://github.com/alibaba/Sentinel/releases/tag/2.0.0-alpha), where it's already included.

Got it, thank you.
