### ISSUE TITLE
根据错误次数或者比例熔断例子错误，真实用的时候不生效 

### ISSUE THREAD

**Issue by zhenxiao07** [alibaba/Sentinel#3097]
需要在sentinel.TraceError(e, errors.New("biz error"))埋点的时候，增加e.Exit()，熔断配置才会生效

**Comment by sczyh30** [comment]
这个看起来是 Sentinel Go 相关的问题，可以在这里提 issue 详细描述下问题：https://github.com/alibaba/sentinel-golang/issues
