### ISSUE TITLE
dashboard不能正确显示请求链路

### ISSUE THREAD

**Issue by liiibpm** [alibaba/Sentinel#3099]
## Issue Description

Type: *bug report*

### Describe what happened
控制台中模式使用8719端口，但是返回一堆我用不到的默认的数据。
在使用获取请求链路的接口中，将port更改为8720就能正确返回  
这是什么原因，没法正常使用的   
1.8.5的

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/105549399/233560031-c95bd315-0cfe-4f00-b42d-1bbf13dae115.png)
![image](https://user-images.githubusercontent.com/105549399/233560175-431caa38-3ac0-4704-8393-bb3acbe7a3c4.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environmen
docker中部署

**Comment by LiYangSir** [comment]
看一下 8719 是不是被其他进程占用了，port 会逐步扩大直到找到可用的端口
