### ISSUE TITLE
sentinel1.8.6 dashboard 热点参数限流持久化到nacos，ParamFlowRuleEntity 序列化存在问题

### ISSUE THREAD

**Issue by albertcoolsea** [alibaba/Sentinel#3113]
1.sentinel1.8.6 dashboard 热点参数限流持久化到nacos，数据格式：
[
  {
    "app":"promise-service",
    "gmtCreate":1683127862800,
    "gmtModified":1683129314950,
    "id":3,
    "ip":"192.168.0.101",
    "port":8720,
    "rule":{
      "burstCount":0,
      "clusterConfig":{
        "fallbackToLocalWhenFail":true,
        "sampleCount":10,
        "thresholdType":0,
        "windowIntervalMs":1000
      },
      "clusterMode":false,
      "controlBehavior":0,
      "count":2.0,
      "durationInSec":5,
      "grade":1,
      "limitApp":"default",
      "maxQueueingTimeMs":0,
      "paramFlowItemList":[
      ],
      "paramIdx":0,
      "resource":"paramFlow1"
    }
  }]

2.sentinel-core 1.8.6版本对象DynamicSentinelProperty,方法nacosNacosDataSource.this.parser.convert(configInfo)对nacos配置数据解析，ParamFlowRule对象和dashboard配置的数据结构不一致，解析结果非预期，不会更新配置，
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/39090441/235977680-8f28829b-87cf-4ade-8cd8-e9ea2a575356.png">

手动在nacos去掉rule节点，修改后数据，可以正常解析，热点参数限流生效。
[
  {
    "app":"promise-service",
    "gmtCreate":1683127862800,
    "gmtModified":1683129314950,
    "id":3,
    "ip":"192.168.0.101",
    "port":8720,
      "burstCount":0,
      "clusterConfig":{
        "fallbackToLocalWhenFail":true,
        "sampleCount":10,
        "thresholdType":0,
        "windowIntervalMs":1000
      },
      "clusterMode":false,
      "controlBehavior":0,
      "count":2.0,
      "durationInSec":5,
      "grade":1,
      "limitApp":"default",
      "maxQueueingTimeMs":0,
      "paramFlowItemList":[
      ],
      "paramIdx":0,
      "resource":"paramFlow1"
  }]

**Comment by albertcoolsea** [comment]
if u knew what i was told,suggest that move the field "app" from outer to "rule",just like below:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/39090441/236682716-5527bc3a-f15e-4fda-932d-b9af41a1deeb.png">

Covert will more elegant，just like below:
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/39090441/236682794-800cd571-2041-45be-91cb-49c7da75aeac.png">

**Comment by sczyh30** [comment]
Refer existing issues: https://github.com/alibaba/Sentinel/issues?q=ParamFlowRuleEntity
You'll need to convert `ParamFlowRuleEntity` to ParamFlowRule and then push it to the data-source.
