### ISSUE TITLE
请问sentinel如何暴露接口监控的相应指标数据给prometheus呢，有教程吗？

### ISSUE THREAD

**Issue by heqs** [alibaba/Sentinel#3126]
请问sentinel如何暴露接口监控的相应指标数据给prometheus呢，有教程吗？

**Comment by goudai** [comment]
+1

**Comment by LearningGp** [comment]
在这个问题上社区有一些持续的讨论，可以参考https://github.com/alibaba/Sentinel/issues/211 。目前看大家好像有一些二次开发的成果https://github.com/alibaba/Sentinel/pull/1665 ，但似乎在社区中还没有通用且完善的方案:sweat_drops:，对可观测机制的进一步扩展与完善是Sentinel v2.0.0重要的部分，欢迎参与讨论与贡献:muscle:！

**Comment by noseew** [comment]
可以提前确定好Prometheus指标名称规范吗？当有具体实现之后在无缝衔接官方版本
