### ISSUE TITLE
Sentinel 控制台 1.8.6, 对接口熔断控制台配置比例阈值再次打开显示异常

### ISSUE THREAD

**Issue by 183773111** [alibaba/Sentinel#3135]
![image](https://github.com/alibaba/Sentinel/assets/44662623/cef4f125-d0b2-45e6-8794-b948b88560cc)

此后，保存再打开的时候显示如下

![image](https://github.com/alibaba/Sentinel/assets/44662623/a79881b2-50de-4016-b79f-8a212c2a232b)

**Comment by sczyh30** [comment]
确认下应用侧的 Sentinel 版本是否满足 >= 1.8.x，否则不支持慢调用比例模式。

**Comment by 183773111** [comment]
明白了，应用测的 sentinel 版本确实比较低，是 1.6.3
