### ISSUE TITLE
spring cloud gateway sentinel 熔断规则能根据指定接口进行熔断吗

### ISSUE THREAD

**Issue by Phoebus888** [alibaba/Sentinel#3142]
现在配置的熔断规则都是一个实例生效，相当于我一个接口出现异常，其他接口都会出现异常，现在想做的是指定接口进行熔断，这个接口出现异常就会进行熔断，其他接口不会受到限制

**Comment by Phoebus888** [comment]
现在有问题就是  我一个接口出现异常  其他接口都出现了问题   这个是不应该的   熔断也是指定接口进行熔断

**Comment by sczyh30** [comment]
网关上推荐的实践是针对 route 维度配置规则；若希望针对具体接口进行熔断，建议在应用侧配置或借助 API 请求分组。

**Comment by Phoebus888** [comment]
那这边比较麻烦    那就不再网关上做熔断了  在下层做   下层熔断  上层也是直接返回的

**Comment by liuligang9527** [comment]
咋样了，我发现在网关配置下游服务的熔断规则，对下游服务的接口不生效。得在下游服务单独集成sentinel
