### ISSUE TITLE
怎么样才能支持body区分进行熔断

### ISSUE THREAD

**Issue by Phoebus888** [alibaba/Sentinel#3144]
我们出口网关用的是一个接口，用于上层服务传过来的body区分调用哪个接口，sentinel如何基于上游传过来的body进行熔断，熔断的话只能熔断指定body过来的，其他外部接口不受到影响

**Comment by Phoebus888** [comment]
body确实有这个问题  那我们加一个header   header如何处理这个问题   就是和限流一样   header匹配指定值才进行熔断判断

**Comment by VAEAZE** [comment]
@Phoebus888 你怎么解决的
