### ISSUE TITLE
服务器是集群模式，架构是dubbo模式如何选择版本问题？

### ISSUE THREAD

**Issue by zhangxinyuan1** [alibaba/Sentinel#315]
服务器是集群的，架构是dubbo  我应该是引用集群版本还是适配dubbo框架版本呢？

**Comment by sczyh30** [comment]
These two are just different modules of Sentinel, which do not conflict. You can add the Sentinel Dubbo Adapter dependency to integrate with your Dubbo services. If you need cluster flow control, you can introduce the dependency of the cluster flow control additionally.

---

这两个不冲突。可以引入 Sentinel Dubbo Adapter 接入 Dubbo 适配；如果有集群流控的需要，可以再引入集群流控的相关依赖。

**Comment by zhangxinyuan1** [comment]
谢谢！
