### ISSUE TITLE
客户端接入控制台指的是消费者 还是服务提供者呢？

### ISSUE THREAD

**Issue by zhangxinyuan1** [alibaba/Sentinel#317]
1、系统架构使用的是dubbo ，文档描述：客户端接入控制台  是说消费者接入 还是服务提供者接入呢？
2、启动参数控制台本身就自带了， 意思是消费者接入的时候需要在消费方jvm中加入控制台的配置参数，服务提供者接入的时候也需要在提供方jvm中加入控制台配置参数？
3、sentinel-transport-simple-http 提供者和消费者都可以加入此包吗？

**Comment by sczyh30** [comment]
Hi, that depends on your requirement. Both Dubbo provider and consumer can leverage the dashboard. You have to add necessary JVM parameters for your services to connect to the dashboard. `sentinel-transport-simple-http`  dependency is needed.

See [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) and wiki for more information.
