### ISSUE TITLE
java.lang.IllegalStateException: Command server error

### ISSUE THREAD

**Issue by zhangxinyuan1** [alibaba/Sentinel#318]
ERROR c.t.c.s.d.v.ClusterConfigController - Error when fetching cluster state
java.lang.IllegalStateException: Command server error

服务端已引入： sentinel-cluster-server-default

**Comment by sczyh30** [comment]
Hi, could you please provide command center log (i.e. `command-center.log.xxx`) and `sentinel-record.log` of your services (located in `~/logs/csp`)? There should be exceptions in the log.

**Comment by sczyh30** [comment]
The log indicates that the fastjson version of your service does not match with the version Sentinel is using (1.2.54). Please update your fastjson version and try again.
