### ISSUE TITLE
Mock Support for dubbo

### ISSUE THREAD

**Issue by pwh19920920** [alibaba/Sentinel#319]
1. The fallback method of the SentinelResource annotation after adding the Mock to the dubbo interface does not work, but the blockHandler method is normal.

为dubbo的接口添加Mock以后SentinelResource注解的fallback方法不起作用，但是blockHandler方法是正常的。

2. Will the business anomaly be calculated by blowing? Hystrix is handled in such a way that the exception class is mainly a subclass of BadRequestException and will not be blown. I don't know how Sentinel handles it.

业务异常是否会被熔断计算？Hystrix的处理方式是异常类主要是BadRequestException的子类就不会被熔断计算，不知道Sentinel是如何处理的。

**Comment by sczyh30** [comment]
Hi, the fallback method of `@SentinelResource` is invoked only when the resource is degraded (throws `DegradeException), rather than biz exception is thrown.

Sentinel will regard all exceptions except `BlockException` as the biz exception.

---

`@SentinelResource` 的 `fallback` 方法仅会在资源被降级（自动抛出 `DegradeException`）时生效，对于业务异常会原样抛出，不会到 fallback 逻辑中。
熔断降级统计的就是业务异常，即非 `BlockException` 类型的异常都会被统计为业务异常。

**Comment by pwh19920920** [comment]
If I only set the downgrade strategy and use the local mock in dubbo, will it not enter the fallback logic of the @SentinelResource annotation?

如果我只设定了降级策略，并且在dubbo中使用了本地mock，也不会进入@ SentinelResource注解的fallback逻辑中么？

**Comment by pwh19920920** [comment]
The SentinelResource annotation seems to only support native methods and external static class methods. Is it considered to support Spring bean processing?

SentinelResource注解似乎只支持本地方法和外部静态类方法，是否考虑支持以Spring的Bean形式处理呢？

**Comment by sczyh30** [comment]
> The SentinelResource annotation seems to only support native methods and external static class methods. Is it considered to support Spring bean processing?
> 
> SentinelResource注解似乎只支持本地方法和外部静态类方法，是否考虑支持以Spring的Bean形式处理呢？

`@SentinelResource` 注解本身不与 Spring 强绑定，若有类似需求可以参考 `SentinelResourceAspect` 改造一下。

`@SentinelResource` annotation support is not strongly bound to Spring. You can refer to `SentinelResourceAspect` to refactor it.
