### ISSUE TITLE
Sentinel 什么时候可以支持 Spring 6 / spring-boot 3 ?

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/Sentinel#3191]
如题~

CommonFilter 继承的是 javax.servlet.Filter，但 Spring 6 用的是 jakarta.servlet.Filter，无法使用了。

**Comment by 903328615** [comment]
我也发现了，怕不是得自己重写一个，之前还有个 issue ，不会不维护了吧

**Comment by sczyh30** [comment]
Refer this PR: https://github.com/alibaba/Sentinel/pull/2997

目前针对 JDK 17 的 CI 还有些问题，测试用例与依赖需要做下完善（refer #3015），这一块没问题后会合并相关 PR.

**Comment by ruansheng8** [comment]
@sczyh30 CI 这块是否有计划修复，Sentinel 1.8.7 版本没有 `sentinel-spring-webmvc-6x-adapter` 这个模块。

之前 1.8.6 版本是本地直接 deploy 到远程仓库的

![image](https://github.com/alibaba/Sentinel/assets/24709538/85a437c0-e5ec-4403-b3a2-ec4f37f1f5cf)

**Comment by LearningGp** [comment]
我会尝试在近期修复这个问题

**Comment by ruansheng8** [comment]
> 我会尝试在近期修复这个问题

@LearningGp @sczyh30 我关注到最近有几个CI的PR被合并，是否意味着该问题已经被修复，可以准备合并 Spring 6 相关的支持PR

**Comment by lwx57280** [comment]
同问什么时候发布支持Spring Boot 3.0+
