### ISSUE TITLE
How to identify the request origin for HTTP requests in web servlet applications?

### ISSUE THREAD

**Issue by shuohao** [alibaba/Sentinel#320]
How to identify the request origin for HTTP requests in web servlet applications?

dubbo黑白名单可以设置dubbo的application name，对应http请求如何设置黑白名单调用？对于web servlet应用，如何标识调用方？

**Comment by sczyh30** [comment]
Hi, for web servlet adapter, you can implement your own `RequestOriginParser` to parse the origin from the `HttpServletRequest` manually, then register your implementation via `WebCallbackManager.setRequestOriginParser(parser)`.

You can refer to [the document](https://github.com/alibaba/Sentinel/wiki/Adapters-to-Popular-Framework#web-servlet) and [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%80%8E%E4%B9%88%E9%92%88%E5%AF%B9%E7%89%B9%E5%AE%9A%E8%B0%83%E7%94%A8%E7%AB%AF%E9%99%90%E6%B5%81%E6%AF%94%E5%A6%82%E6%88%91%E6%83%B3%E9%92%88%E5%AF%B9%E6%9F%90%E4%B8%AA-ip-%E6%88%96%E8%80%85%E6%9D%A5%E6%BA%90%E5%BA%94%E7%94%A8%E8%BF%9B%E8%A1%8C%E9%99%90%E6%B5%81%E8%A7%84%E5%88%99%E9%87%8C%E9%9D%A2-limitapp%E6%B5%81%E6%8E%A7%E5%BA%94%E7%94%A8%E7%9A%84%E4%BD%9C%E7%94%A8) for detail.
