### ISSUE TITLE
规则和集群数据如何动态读取与存储

### ISSUE THREAD

**Issue by zhangxinyuan1** [alibaba/Sentinel#323]
1、动态规则数据源 如果选择zookeeper， source 如何动态把规则数据注册到zookeeper 中呢？

// remoteAddress 代表 ZooKeeper 服务端的地址
// path 对应 ZK 中的数据路径
ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new ZookeeperDataSource<>(remoteAddress, path, source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {}));
FlowRuleManager.register2Property(flowRuleDataSource.getProperty());

2、集群限流控制台配置的数据 服务端重启 或者 控制台本身重启 数据会丢失， 如何持久化？如何动态获取？

**Comment by sczyh30** [comment]
Hi, you can refer to these documents:

- [动态规则源](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95)
- [Dashboard 集群限流](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0---%E9%9B%86%E7%BE%A4%E9%99%90%E6%B5%81)
- [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ)
