### ISSUE TITLE
springcloud+nacos+sentinel 直接流控不生效

### ISSUE THREAD

**Issue by S540J521** [alibaba/Sentinel#3242]
版本：spring-cloud-starter-alibaba-sentinel：2.2.6.RELEASE、nacos：1.4.2、sentinel：1.8.1或1.8.6、sentinel-datasource-nacos：1.8.1或者1.8.6
使用dashboard设置流控规则，自动push到了nacos中，使用jmeter请求发现流控未生效
**配置规则如下：**
![image](https://github.com/alibaba/Sentinel/assets/124575445/72093102-3306-4926-8d9e-8f1e042b821c)
**推到nacos中的配置如下：**
![image](https://github.com/alibaba/Sentinel/assets/124575445/2a6fcfd1-70a1-4413-9ec2-64cf035d04c8)
**微服务bootstrap.yml配置如下：**
![image](https://github.com/alibaba/Sentinel/assets/124575445/d35408e7-161e-40a7-8db5-d6b6b02e0af5)
**接口定义资源如下：**
![image](https://github.com/alibaba/Sentinel/assets/124575445/1ab8b00d-fdc3-43ac-be7a-4ef0e285701b)

**Comment by fancywus** [comment]
我也是一样的问题，nacos动态配置，发现限流不起作用，不知道是不是和后台界面没有放开nacos配置流控那一块有关系
