### ISSUE TITLE
[BUG] SphU.entry在高并发请求下，概率性出现慢请求，耗时在5s左右

### ISSUE THREAD

**Issue by cumtxzy** [alibaba/Sentinel#3249]
ContextUtil.enter("ndr-gateway", ak);
            Entry entry = null;
            try {
                long t1 = System.currentTimeMillis();
                entry = SphU.entry("global_resource");
                long t2 = System.currentTimeMillis();
                if(t2 - t1 > 1000){
                    System.out.println("time out:"+(t2 - t1));
                }
            } catch (BlockException e){
                throw new CommonException(ErrorCode.TOO_MANY_REQUESTS);
            }catch (Exception e) {
                //忽略异常
                log.error("sentinel error", e);
            } finally {
                if (entry != null) {
                    entry.exit();
                }
                ContextUtil.exit();
            }

**Comment by cumtxzy** [comment]
输出结果如下：
time out:5008
time out:5008
time out:5016
time out:5004
time out:5007
time out:5016
time out:5006
time out:5001
time out:5010
time out:5009
time out:5009
time out:5004
time out:5001
time out:5003
time out:5008

**Comment by cumtxzy** [comment]
sentinel使用1.8.6版本

**Comment by huangjinteng** [comment]
你用的啥那个版本

**Comment by cumtxzy** [comment]
问题已解决，还是这个bug导致，程序初始化时把连接的超时时间设定为5s
https://github.com/alibaba/Sentinel/pull/2861

**Comment by cumtxzy** [comment]
问题已解决，还是这个bug导致，程序初始化时把连接的超时时间设定为5s
https://github.com/alibaba/Sentinel/pull/2861
