### ISSUE TITLE
控制台自动剔除失联机器

### ISSUE THREAD

**Issue by johnnywong233** [alibaba/Sentinel#3256]
参考[976372](https://github.com/alibaba/Sentinel/issues/1432)
按照这里面给出的解决方案，可是根本就不行。
找了SentinelProperties配置类源码，里面也没有对配置项sentinel.dashboard.autoRemoveMachineMillis的处理逻辑。
这个功能真的实现了吗？
我使用的版本号：
```xml
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
	<version>2.1.4.RELEASE</version>
</dependency>
```

**Comment by johnnywong233** [comment]
之前的issue关了。网络上根本就搜不到相关文档。

**Comment by chj9** [comment]
直接关issues了吗，有解决方法吗
