### ISSUE TITLE
集群流控无法实现且dashboard存在BUG

### ISSUE THREAD

**Issue by Tank-zhu** [alibaba/Sentinel#329]
### 环境描述
JDK 1.8  应用框架 dubbo 2.5.6   部署两个节点

### 问题描述
想对两个节点做总流量 限流 但是测试下来只能对单机做限流

#### dashboard 内添加限流规则 且持久化至ZK上
![image](https://user-images.githubusercontent.com/10337065/50342838-b0ef1000-055f-11e9-9f95-74a3921492f4.png)

#### 需要被限流的应用上加入了注册规则源 ZK
![image](https://user-images.githubusercontent.com/10337065/50342891-ec89da00-055f-11e9-9202-dc24a08f27c3.png)

#### 在dashboard内扩展了 datasource
![tim 20181221203725](https://user-images.githubusercontent.com/10337065/50343011-63bf6e00-0560-11e9-9309-abd2e5ed7d07.png)
![tim 20181221203755](https://user-images.githubusercontent.com/10337065/50343015-66ba5e80-0560-11e9-8ee2-3ee6e1ddf0c0.png)

#### 在dashboard上指定集群模式
![image](https://user-images.githubusercontent.com/10337065/50343065-8ea9c200-0560-11e9-8fea-8bdfa543862c.png)
![image](https://user-images.githubusercontent.com/10337065/50343097-a2552880-0560-11e9-9935-a5e484dd0dfe.png)

#### 两个节点启动后日志
![image](https://user-images.githubusercontent.com/10337065/50343123-bef16080-0560-11e9-97f0-d3d81c6b437d.png)
![image](https://user-images.githubusercontent.com/10337065/50343129-c153ba80-0560-11e9-9aac-492ff25b47c6.png)

#### 测试结果发现 每到16个请求rg后会报错。
1545396260307
报错 16
75
1545396261382
报错 16
86
1545396262468
报错 16
90
1545396263558
报错 16
94
1545396264652
报错 16
75
1545396265727
报错 16

**Comment by Tank-zhu** [comment]
sentinel 版本是 1.4.0

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50390367-8eccdc00-0771-11e9-8a63-8f1f3159116e.png)
![image](https://user-images.githubusercontent.com/10337065/50390372-a0ae7f00-0771-11e9-98e5-1212fc39a1dc.png)
### 配置修改后。无效果。原本是16个请求时会被限流。现在是完全不限流了

**Comment by sczyh30** [comment]
命名空间集合是在 集群限流 页面配置（给 Token Server 配置），而不是 *流控应用*：
![image](https://user-images.githubusercontent.com/9434884/50390534-22eb7300-0773-11e9-9aac-2f28b8ab3c0a.png)

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50390655-e1f45e00-0774-11e9-978c-a096548ce5a7.png)
还是不行呢。。。。

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50392031-82eb1500-0785-11e9-9e3e-28dfef1d22fe.png)

 [{"app":"wf-platform","clusterConfig":{"fallbackToLocalWhenFail":true,"flowId":59,"strategy":0,"thresholdType":1},"clusterMode":true,"controlBehavior":0,"count":5.0,"gmtCreate":1545630300024,"gmtModified":1545630300024,"grade":1,"id":59,"ip":"10.33.80.148","limitApp":"default","port":8091,"resource":"com.wf.platform.rpc.CheckInRpcService:isLottery(java.lang.Long)","strategy":0}]  这个是原来生成的配置。现在保存在ZK上，可是解析时居然不能是个列表。。

**Comment by sczyh30** [comment]
> ![image](https://user-images.githubusercontent.com/10337065/50392031-82eb1500-0785-11e9-9e3e-28dfef1d22fe.png)
> 
> [{"app":"wf-platform","clusterConfig":{"fallbackToLocalWhenFail":true,"flowId":59,"strategy":0,"thresholdType":1},"clusterMode":true,"controlBehavior":0,"count":5.0,"gmtCreate":1545630300024,"gmtModified":1545630300024,"grade":1,"id":59,"ip":"10.33.80.148","limitApp":"default","port":8091,"resource":"com.wf.platform.rpc.CheckInRpcService:isLottery(java.lang.Long)","strategy":0}] 这个是原来生成的配置。现在保存在ZK上，可是解析时居然不能是个列表。。

这个是不应该的，你发的生成的规则是可以正确解析的：

```java
public class Test {
    public static void main(String[] args) {
      String a = "[{\"app\":\"wf-platform\",\"clusterConfig\":{\"fallbackToLocalWhenFail\":true,\"flowId\":59,"
          + "\"strategy\":0,\"thresholdType\":1},\"clusterMode\":true,\"controlBehavior\":0,\"count\":5.0,"
          + "\"gmtCreate\":1545630300024,\"gmtModified\":1545630300024,\"grade\":1,\"id\":59,\"ip\":\"10.33.80.148\","
          + "\"limitApp\":\"default\",\"port\":8091,\"resource\":\"com.wf.platform.rpc.CheckInRpcService:isLottery"
          + "(java.lang.Long)\",\"strategy\":0}]";
      System.out.println(JSON.parseObject(a, new TypeReference<List<FlowRule>>() {}));
    }
}
```

检查一下 fastjson 版本是否太低，检查一下数据格式是否正确。

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50392141-a1054500-0786-11e9-9623-763c58d45a8f.png)

版本是1.2.22    这个版本应该是没有问题的。因为单机的时候解析是没有问题的。

**Comment by sczyh30** [comment]
`namespaceDs`, `transportConfigDs` 配置均错误，这两个配置源都去掉，重启试一下。

- namespace set: 集群限流服务端服务的作用域（命名空间），可以设置为应用名
- transport config: 集群限流服务端通信相关配置，如 port
- flow config: 集群限流服务端限流相关配置，如滑动窗口统计时长、格子数目等

**Comment by Tank-zhu** [comment]
namespaceDs  transportconfigDs 配置确实有问题。 我删除重启后不再报错。
### 然后我修改了一下路径如下
![image](https://user-images.githubusercontent.com/10337065/50393742-36a6d180-0793-11e9-9733-2a6331ccf3df.png)

这个monitorconfig  是在我应用内的。这个时候，我是否应该在dashborad生成规则时，存入ZK

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50393886-2fcc8e80-0794-11e9-9b14-12589b4fa1f8.png)
![image](https://user-images.githubusercontent.com/10337065/50393891-32c77f00-0794-11e9-959f-5fac5dadec0d.png)
### 是否只需要再把这两个参数持久化到ZK呢。

**Comment by Tank-zhu** [comment]
![image](https://user-images.githubusercontent.com/10337065/50394774-99e83200-079a-11e9-8981-0a3acb8e753f.png)
依旧没有效果呢。。。

**Comment by Tank-zhu** [comment]
OK，，，已经好了。
