### ISSUE TITLE
支持请求的超时时间

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/Sentinel#3294]
## 介绍
我想在请求没有触发熔断或者降级的情况下也能指定请求的超时时间，而不是非要触发了才可以，hystrix是可以支持的，通过`hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`参数可以配置。但sentinel我并没有看到，目前支持这个功能码

**Comment by LearningGp** [comment]
目前 Sentinel 的结构是通过请求调用前后的切面实现的，暂时不支持超时这类功能，后续演进会探索新的调用模型，欢迎参与讨论和贡献。#2118
