### ISSUE TITLE
替换ThreadLocal<SimpleDateFormat>以适配Java21虚拟线程

### ISSUE THREAD

**Issue by shichaoyuan** [alibaba/Sentinel#3321]
## Issue Description

https://github.com/alibaba/Sentinel/blob/a524ab3bb3364818e292e1255480d20845e77c89/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java#L142-L148

https://github.com/alibaba/Sentinel/blob/a524ab3bb3364818e292e1255480d20845e77c89/sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/CspFormatter.java#L28-L34

https://github.com/alibaba/Sentinel/blob/a524ab3bb3364818e292e1255480d20845e77c89/sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/DateFileLogHandler.java#L36-L42

代码中的ThreadLocal对Java21中的 virtual thread 并不友好。

而且从Java8开始已经推荐使用 `java.time.format.DateTimeFormatter`，这是一个 "This class is immutable and thread-safe." 的实现。

### Describe your initial design

是否可以将这些地方换成 `java.time.format.DateTimeFormatter`？

如果可以的话，我愿意提PR

**Comment by robberphex** [comment]
是可以这样修改的，可以提交pr的。
