### ISSUE TITLE
dashboard编辑流控规则页面bug

### ISSUE THREAD

**Issue by tfdxl** [alibaba/Sentinel#334]
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)

bug位置：流控规则-编辑流控规则页面

### Describe what you expected to happen

点击编辑按钮，修改单机阈值，关闭弹框，不保存，列表页的单机阈值被修改了。

### How to reproduce it (as minimally and precisely as possible)

1. 编辑页面的对象和列表页不要公用

### Tell us your environment

sentinel-dashboard-1.4.0.jar

**Comment by Tank-zhu** [comment]
这里不是BUG呢。是如果你没有开启集群配置。就默认是单机呢。所以改了单机的。

**Comment by sczyh30** [comment]
Duplicate of #95. We'll fix it later.
