### ISSUE TITLE
Spi重复初始化资源问题

### ISSUE THREAD

**Issue by ZShUn** [alibaba/Sentinel#3376]
需求：
通过Agent下沉通用限流逻辑

问题复现步骤：
Agent中依赖sentinel，通过埋点实现通用资源限流，然后在微服务中继续依赖sentinel。当sentinel spi初始化时会加载出来两个文件路径，然后重复加载出现异常

agent中依赖：
![image](https://github.com/alibaba/Sentinel/assets/16457274/298b3a49-73c8-4eb0-a2c3-8c8618492e46)
![image](https://github.com/alibaba/Sentinel/assets/16457274/513efa3d-b19d-4138-9040-ede3a2938de2)

微服务中依赖：
![image](https://github.com/alibaba/Sentinel/assets/16457274/e867742f-4dda-45ee-b497-bb138beb40ec)

**Comment by ZShUn** [comment]
![940b06a6577435661df2e012d1fd1431](https://github.com/alibaba/Sentinel/assets/16457274/fd705b0a-4aa1-41f1-b25c-bc96523726cf)

**Comment by ZShUn** [comment]
应用服务 Sentinel文件路径：
jar:file:/D:/xxx/maven/localRepository/com/alibaba/csp/sentinel-core/1.8.7/sentinel-core-1.8.7.jar!/META-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot

Agent Sentinel 文件路径:
jar:file:/D:/project/xxx/agent/xxx-agent-0.0.1-SNAPSHOT.jar!/META-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot

**Comment by LearningGp** [comment]
初步看起来原因是 JVM 中存在两份 Sentinel ，我理解这是不太合理的，即便 spi 这边不抛出异常，后续功能也是未定义的可能存在很多问题，最好通过 Agent 来剔除应用服务中的依赖，使得JVM中只有一份 Sentinel。

**Comment by ZShUn** [comment]
SpiLoader中的异常实际是防止重复初始化，如果不在agent中依赖sentinel，那么就无法把通用限流功能下沉。比如根据CPU或内存进行限流

**Comment by ZShUn** [comment]
https://github.com/alibaba/Sentinel/pull/3377

**Comment by ZShUn** [comment]
https://github.com/alibaba/Sentinel/issues/3185
https://github.com/alibaba/Sentinel/issues/3181
此类问题有已经有多个issues了，因为在实际开发中，无法避免依赖包是否会传递sentinel依赖过来，如果按照你的说法，那么用户每次都需要把传递依赖排除

**Comment by ZShUn** [comment]
https://github.com/alibaba/Sentinel/issues/1379
https://github.com/alibaba/Sentinel/pull/1383

**Comment by cdfive** [comment]
@LearningGp @ZShUn

**Comment by cdfive** [comment]
> #3185 #3181 此类问题有已经有多个issues了，因为在实际开发中，无法避免依赖包是否会传递sentinel依赖过来，如果按照你的说法，那么用户每次都需要把传递依赖排除

确实，可能有依赖传递问题，实际开发中很常见。应修改SpiLoader处理方式，让用户体验更好。
