### ISSUE TITLE
[Bug] Dashboard 流控规则——编辑单机阈值保存后，再次访问被流控的接口，单机阈值恢复成旧值

### ISSUE THREAD

**Issue by bobo612** [alibaba/Sentinel#341]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
流控规则页面，例如原先阈值=20，编辑单机阈值修改成100保存成功后，页面显示100，当请求触发限流约束的接口后，阈值从100变回20，单机阈值规则没有在客户端生效

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, please check your log in `${user.home}/logs/csp/sentinel-record.log.xxx` to check whether the service has received the correct rules. [The FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ) may also be helpful for you.
