### ISSUE TITLE
Incorrectly described in the official document 官网文档描述有误

### ISSUE THREAD

**Issue by dowenliu-xyz** [alibaba/Sentinel#3413]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Incorrect document content in https://sentinelguard.io/zh-cn/docs/annotation-support.html :
```
value：资源名称，必需项（不能为空）
```
However, according to the source code, when value is null, the resource name is computed from the annotated method. The documentation should explain this here.

### Describe what you expected to happen

```
value: 资源名称。如果为空白，则根据被注解方法计算，格式为 ...
```

### How to reproduce it (as minimally and precisely as possible)
Nothing to reproduce
### Tell us your environment
No environment required, just visit the site with morden browsers.
### Anything else we need to know?

I can not find any website source repo, otherwise I may create a PR to correct the docs.

**Comment by LearningGp** [comment]
FYI, https://github.com/sentinel-group/sentinel-website

**Comment by dowenliu-xyz** [comment]
I'll try to make a PR on sentinel-group/sentinel-website. Close this issue.
