### ISSUE TITLE
suggest the fallbackToLocalWhenFail param of ClusterFlowConfig can be configured through dashboard UI

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#343]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

![image](https://user-images.githubusercontent.com/31885791/50466119-99d47600-09d6-11e9-9b98-ce5fc90b67da.png)

Now adding Cluser FlowRule in dashboard only the param thresholdType of ClusterFlowConfig
can be configured.

### Describe what you expected to happen

Expect the fallbackToLocalWhenFail param can be configured.
Since the default value is true, when setting to false, if the Cluser rule is not configured correctly, the b_pqs in the monitor page will be 0, which can be found easily.

It this way , it may be more convenient to debug.
Besides, the scene that only need CluserFlowRule controll in effect may needed.

**Comment by sczyh30** [comment]
Yes, it should be added to the dashboard dialog indeed, but we need to consider the text to make users understand what it means.

---

这一项确实是需要加到对话框的，只不过对应的显示文案需要让用户可以很好地理解。`fallbackToLocalWhenFail` 的意思是集群限流由于网络或请求失败时（token server 不可用），是否需要退化到单机限流。用户可能会理解为集群限流不通过时退化到单机。

**Comment by sczyh30** [comment]
文字显示可以叫“失败后是否退化”（或者更合理的表述，尽量简短），然后后面可以放个小问号 icon，鼠标移上去弹出个 balloon 里面放详细描述。

**Comment by cdfive** [comment]
嗯，icon+hover提示感觉也不错，还节约空间；
文字有**是否**确实比较好，突出true/false选择。

**Comment by sczyh30** [comment]
> 嗯，icon+hover提示感觉也不错，还节约空间；
> 文字有**是否**确实比较好，突出true/false选择。

Would you like to contribute a PR to add this?

**Comment by cdfive** [comment]
@sczyh30 白天事情太杂了T_T ！下来我去学习试试哈
