### ISSUE TITLE
CommandCenter providers stop method but we can not get instance and invoke it

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/Sentinel#345]
## Issue Description

Spring Boot expose `/shutdown` Endpoint to shutdown Application. Sentinel-Starter includes `sentinel-transport-simple-http` module and this module using SPI to trigger `SimpleHttpCommandCenter`.

After invoke `/shutdown` endpoint, the process will not exit because the `ServerSocket` created in `SimpleHttpCommandCenter` is alive.

So I can invoke `CommandCenter#stop` to shutdown ThreadPool if I can get `CommandCenter` instance.

Type: feature request

### Describe what feature you want

The single `CommandCenter` in `CommandCenterInitFunc` maybe should be hold in some where.

So we can get it and invoke `CommandCenter#stop` at any time.

**Comment by sczyh30** [comment]
Thanks for your suggestion. I think we can add a `CommandCenterProvider` to resolve the `CommandCenter` API and cache the instance so that users can get the instance from it.

**Comment by fangjian0423** [comment]
Cool.  I agree with you.

It is very easy to get cached `CommandCenter` from `CommandCenterProvider` and we can invoke any methods with it.

**Comment by cdfive** [comment]
@sczyh30 @fangjian0423 Thanks for discuss the detail, I learned and have a try.
