### ISSUE TITLE
关于FlowThreadDemo  第一为什么会有些间隔的1s内 没有任何线程通过. 第二,为什么睡眠时间减少后,通过了那么多线程.难道不是限制每秒只能有20个线程吗.

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#347]
关于FlowThreadDemo  第一为什么会有些间隔的1s内 没有任何线程通过. 第二,为什么睡眠时间减少后,通过了那么多线程.难道不是限制每秒只能有20个线程吗.

**Comment by huihui1112** [comment]
我突然想通了 麻烦关闭这个issues...

**Comment by sczyh30** [comment]
> 我突然想通了 麻烦关闭这个issues...

You can close the issue by yourself.
