### ISSUE TITLE
SCG网关限流里，热点参数是否支持配置多个？

### ISSUE THREAD

**Issue by zcz3313** [alibaba/Sentinel#3470]
SCG网关限流里，热点参数是否支持配置多个？

我看GatewayFlowRule的对应字段数据结构是一个参数，请问是否有办法设置多个参数。

例如，我希望，即判断请求头又同时希望判断源ip。

**Comment by LearningGp** [comment]
目前不支持哈，这种灵活的需求可以通过自定义埋点来支持，比如将请求头和ip拼成一个key

**Comment by zcz3313** [comment]
感谢回答，最终我通过继承GatewayFlowRule并增加了一个list类型的参数来实现了我的需求。

**Comment by Haolucifer** [comment]
> 感谢回答，最终我通过继承GatewayFlowRule并增加了一个list类型的参数来实现了我的需求。

请问你是重新实现了sentinel-api-gateway-adapter吗？修改rule涉及到GatewayFlowRule的加载等，想请教下你是如何改造的；
