### ISSUE TITLE
熔断降级描述中demo及代码使用规则中代码找不到

### ISSUE THREAD

**Issue by zhaoxp1** [alibaba/Sentinel#35]
图中的demo和代码找不到

![default](https://user-images.githubusercontent.com/23419810/43676407-4d609fda-9823-11e8-945b-491a4003349e.PNG)

**Comment by CarpenterLee** [comment]
该工具方法已重构到`BlockException`中，使用`BlockException.isBlockException()`。wiki现已更正。

**Comment by zhaoxp1** [comment]
也请将SentinelUtil.trace(t)修成Tracer.trace(t);
