### ISSUE TITLE
Rule ID counter will be reset after restarting Sentinel dashboard

### ISSUE THREAD

**Issue by foreveryang321** [alibaba/Sentinel#358]
## Issue Description

 *bug report*

```java
public class InMemFlowRuleStore extends InMemoryRuleRepositoryAdapter<FlowRuleEntity> {

    private static AtomicLong ids = new AtomicLong(0);

    @Override
    protected long nextId() {
        return ids.incrementAndGet();
    }
...
```

当规则持久化到zk、Nacos时，重启控制台后，Id 生成器会从 1 开始，会导致新建规则覆盖掉旧规则的情况

Translated from Google:
When the rule is persisted to zk, Nacos, after restarting the console, the Id generator will start at 1 and cause the new rule to overwrite the old rule.

### Tell us your environment

*sentinel-dashboard 1.4.0*

**Comment by sczyh30** [comment]
Hi, the `InMemXXXRuleStore` is only a sample in-memory store for rules. In production you can implement your own `RuleRepository` to save rules to DB and generate unique id using auto-increment key, or using a global counter to generate unique id.
