### ISSUE TITLE
关于AsyncEntryDemo 这个demo  里面有些资源名并没有被定义过.那么SphU.entry("")这样的操作的意义是?

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#359]
关于AsyncEntryDemo 这个demo  里面有些资源名并没有被定义过.那么SphU.entry("")这样的操作的意义是?
因为这个demo 只搞了两个rule 只针对两个资源名嘛. 就没看明白

---

Translation: what does the `AsyncEntryDemo` mainly demonstrate?

**Comment by sczyh30** [comment]
Hi, resource definition and rule configuration are separate. The `AsyncEntryDemo` is intended to show the ability of asynchronous invocation chain tracing and nested chain, where you can see in the `tree` API command.

**Comment by huihui1112** [comment]
@RestController
public class DemoController {

    @Autowired
    private TestService service;

    private static CountDownLatch countDownLatch = new CountDownLatch(500);


    private static volatile boolean flag = false;

    @GetMapping("/foo")
    public String foo() throws Exception {
        FlowRule flowRule = new FlowRule();
        flowRule.setResource("test");
        flowRule.setCount(1);
        flowRule.setStrategy(RuleConstant.FLOW_GRADE_QPS);
        ArrayList<FlowRule> list = new ArrayList<>(1);
        list.add(flowRule);
        FlowRuleManager.loadRules(list);
        for (int i = 0; i < 500 ; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    countDownLatch.countDown();
                    while (flag) {
                        service.test();
                    }
                }
            }).start();
        }
        countDownLatch.await();
        flag = true;
        return service.hello(System.currentTimeMillis());

    }
}
奇怪 我把你们DemoController修改了   很奇怪 这个service.test不是 已经用了注解了吗  为什么规则没有生效.

**Comment by huihui1112** [comment]
sentinel-demo-annotation-spring-aop/ 这里面demo

**Comment by sczyh30** [comment]
> um.... 虽然那demo我也看得懂 你这样解释我也明白了.总之就是不要在乎这些细节..不过国人之间 不是用英文提问的话... 我觉得可以回复中文..... 本身看源码 里面的英文注释就很头疼. 来这还要看英文...

It's encouraged to use English so that your issue can help more people from all over the world.

**Comment by sczyh30** [comment]
> @RestController
> public class DemoController {
> 
> ```
> @Autowired
> private TestService service;
> 
> private static CountDownLatch countDownLatch = new CountDownLatch(500);
> 
> 
> private static volatile boolean flag = false;
> 
> @GetMapping("/foo")
> public String foo() throws Exception {
>     FlowRule flowRule = new FlowRule();
>     flowRule.setResource("test");
>     flowRule.setCount(1);
>     flowRule.setStrategy(RuleConstant.FLOW_GRADE_QPS);
>     ArrayList<FlowRule> list = new ArrayList<>(1);
>     list.add(flowRule);
>     FlowRuleManager.loadRules(list);
>     for (int i = 0; i < 500 ; i++) {
>         new Thread(new Runnable() {
>             @Override
>             public void run() {
>                 countDownLatch.countDown();
>                 while (flag) {
>                     service.test();
>                 }
>             }
>         }).start();
>     }
>     countDownLatch.await();
>     flag = true;
>     return service.hello(System.currentTimeMillis());
> 
> }
> ```
> }
> 奇怪 我把你们DemoController修改了 很奇怪 这个service.test不是 已经用了注解了吗 为什么规则没有生效.

This is another question so maybe you can open another new issue.

**Comment by jialianglinjl** [comment]
> ... 我觉得可以回复中文.....

恩 回复中文没有问题的。
