### ISSUE TITLE
奇怪 我把你们DemoController修改了 很奇怪 这个service.test不是 已经用了注解了吗 为什么规则没有生效.

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#360]
```
@RestController
public class DemoController {

@Autowired
private TestService service;

private static CountDownLatch countDownLatch = new CountDownLatch(500);


private static volatile boolean flag = false;

@GetMapping("/foo")
public String foo() throws Exception {
    FlowRule flowRule = new FlowRule();
    flowRule.setResource("test");
    flowRule.setCount(1);
    flowRule.setStrategy(RuleConstant.FLOW_GRADE_QPS);
    ArrayList<FlowRule> list = new ArrayList<>(1);
    list.add(flowRule);
    FlowRuleManager.loadRules(list);
    for (int i = 0; i < 500 ; i++) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                countDownLatch.countDown();
                while (flag) {
                    service.test();
                }
            }
        }).start();
    }
    countDownLatch.await();
    flag = true;
    return service.hello(System.currentTimeMillis());

}
}
```

奇怪 我把你们DemoController修改了 很奇怪 这个service.test()不是 已经用了注解了吗 为什么规则没有生效.

---

The rules for `service.test()` method annotated with `@SentinelResource` will not take effect after modifying the `DemoController` of `sentinel-annotation-aop-demo`.

**Comment by sczyh30** [comment]
There's something wrong in your flow rule. You need to set `RuleConstant.FLOW_GRADE_QPS` using `setGrade`. See [here](https://github.com/alibaba/Sentinel/wiki/How-to-Use) for more information.

---

规则配的有问题，配置 QPS 模式（阈值类型）应该用 `setGrade`；`setStrategy` 用于设置流控方式（调用关系限流）。详情请参考 [使用文档](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6%E8%A7%84%E5%88%99-flowrule)。

**Comment by huihui1112** [comment]
谢谢
