### ISSUE TITLE
Deploy multiple Sentinel dashboard instances in the cluster?

### ISSUE THREAD

**Issue by TenYearsIn** [alibaba/Sentinel#363]
Sentinel-DashBoard 是否可集群化部署？DashBoard 是否考虑过高可用？

How to deploy multiple Sentinel dashboard instances in the cluster? How to guarantee the HA and reliability of the dashboard?

**Comment by jialianglinjl** [comment]
Sentinel-Dashboard应该是需要考虑集群化，高可用的。这里面主要考虑的因素有:
1. 当Sentinel客户端很多的时候，如何有效地拉取，聚合监控数据。1台肯定是不够的，需要多台
2. 规则的推模式。
3. 集群限流的高可用性(这个尤为重要)

**Comment by TenYearsIn** [comment]
老哥，和我想的一样，真的是用到了之后，就能更多的想到，看到阿里大佬们的代码，可读性很高，提出个愚见哈，看到里面代码，默认取-Dcsp.sentinel.server这个配置值的第一个，而没有适配到多个，感觉有点暴力哦~不然的话，真的一台DashBoard的机器是真的不可用的

**Comment by licheng-xd** [comment]
对啊，监控数据是通过控制台拉取的模式，这样导致无法部署多个节点，为什么数据部采用客户端上报的模式呢？这样可以水平部署多台节点，前面加个nginx代理就可以变成dashboard的集群部署了。
