### ISSUE TITLE
dashboard前端界面中，点击取消，界面上的数值会更新

### ISSUE THREAD

**Issue by XCXCXCXCX** [alibaba/Sentinel#365]
## Issue Description
Type: *bug report*

### Describe what happened (or what feature you want)
当使用dashboard进行界面控制时，编辑规则后点击取消，界面上的数值会更新
这样会存在一些误解，实际上规则没有更新，但界面上却显示了新的数值
版本1.4.0

### Describe what you expected to happen
编辑规则后点击保存，界面上的数值更新；编辑规则后点击取消，界面上的数值不应该更新。

### How to reproduce it (as minimally and precisely as possible)
必现问题，按照文档打包启动后，在界面上操作，对于每个规则都会出现这个问题
1. 
2. 
3. 

### Tell us your environment
windows10

**Comment by sczyh30** [comment]
Hi, thanks for reporting. This is an known issue and we'll fix it soon.

Duplicate of #95, #334.

**Comment by sczyh30** [comment]
Resolved in #370, will be released with next version.
