### ISSUE TITLE
中文文档-FAQ typo

### ISSUE THREAD

**Issue by twentyfour24** [alibaba/Sentinel#366]
**Describe what happened (or what feature you want)**
### 中文文档描述错误
FAQ->Sentinel 核心功能相关:

Q: 降级规则生效后，除了抛异常之外还有没有其它的处理方式？

A: 可以利用 Sentinel 注解来配置 fallback 函数，**在方法被资源时进行相应处理**。另外，对于 Dubbo 适配，**我们支持注册全局全局的 fallback 函数**，见 Dubbo 适配文档。

**Comment by sczyh30** [comment]
Thanks for reporting! We've fixed it.
