### ISSUE TITLE
[Feature] DataSource integration for Redis

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#37]
## Issue Description

Type: *feature request*

### Describe what feature you want

Add DataSource integration for Redis.

**Comment by tigerMoon** [comment]
so i want to begin with this good first feature implemented by push model  with [jedis client](https://github.com/xetorthio/jedis/tree/master/src/main/java/redis/clients/jedis) and  [redis pub/sub pattern](https://redis.io/topics/pubsub) .

**Comment by sczyh30** [comment]
Nice! It would be better if you can use [Lettuce](https://lettuce.io/) as the Redis client for better performance.
