### ISSUE TITLE
对限流规则里的线程数有疑问

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#375]
此处是FlowThreadDemo的关键代码. 

```java
Entry methodA = null;

                        try {
                            TimeUnit.MILLISECONDS.sleep(5);
                            methodA = SphU.entry("methodA");
                            activeThread.incrementAndGet();
                            Entry methodB = SphU.entry("methodB");
                            TimeUnit.MILLISECONDS.sleep(methodBRunningTime);
                            methodB.exit();
                            pass.addAndGet(1);
                        } catch (BlockException e1) {
                            block.incrementAndGet();
                        } catch (Exception e2) {
                            // biz exception
                        } finally {
                            total.incrementAndGet();
                            if (methodA != null) {
                                methodA.exit();
                                activeThread.decrementAndGet();
                            }
                        }

 private static void initFlowRule() {
        List<FlowRule> rules = new ArrayList<FlowRule>();
        FlowRule rule1 = new FlowRule();
        rule1.setResource("methodA");
        // set limit concurrent thread for 'methodA' to 20
        rule1.setCount(20);
        rule1.setGrade(RuleConstant.FLOW_GRADE_THREAD);
        rule1.setLimitApp("default");

        rules.add(rule1);
        FlowRuleManager.loadRules(rules);
    }
```

以下是打印的日志

我的疑问是这个限流规则 不是说每秒最多20个线程通过吗.  ..... 为什么后面当methodBRunningTime时间变短了后  突然一下子通过这么多.....

```
16 total qps is: 14069
1546419694446, total:14069, pass:801, block:13268 activeThread:21
15 total qps is: 14136
1546419695452, total:14136, pass:809, block:13326 activeThread:19
14 total qps is: 14249
1546419696455, total:14249, pass:808, block:13442 activeThread:20
13 total qps is: 14061
1546419697459, total:14061, pass:794, block:13266 activeThread:20
12 total qps is: 14092
```

**Comment by cdfive** [comment]
通过的800左右是**统计的qps**，设置的20是**线程数的阈值**。

`rule1.setGrade(RuleConstant.FLOW_GRADE_THREAD);`// 按线程数限流；
`rule1.setCount(20);`// 阈值是20，表示同时最大20个线程，超过则限流；

后面methodBRunningTime变短为20ms，试想：
方法耗时20ms，如果只有1个线程跑，那么1秒可以跑1000/20=50个；
最大20个线程，20*50=1000，也就是1秒内最大的qps为1000，
在程序中除了`TimeUnit.MILLISECONDS.sleep(methodBRunningTime);`20ms还有一些其它代码的执行消耗，加上实时统计的误差，所以看到pass在800-1000之间。

如果把阈值20改为1，那么这时1秒跑50个，可以看到后面的pass在50左右。

估计你是看前面几十秒pass出现了很多20，后面突然变大的原因，自己也曾有此疑惑。

最开始methodBRunningTime=2000ms，跟20ms不同，不能直接20*(1000/2000)=10来算，
因为大于1秒，而20个线程几乎是同时跑的，然后一起休眠2秒，所以输出的pass大概是
0 20 0 20 ...

**参考：**
[https://github.com/alibaba/Sentinel/wiki/如何使用#流量控制规则-flowrule](https://github.com/alibaba/Sentinel/wiki/如何使用#流量控制规则-flowrule)

**Comment by huihui1112** [comment]
> 通过的800左右是**统计的qps**，设置的20是**线程数的阈值**。
> 
> `rule1.setGrade(RuleConstant.FLOW_GRADE_THREAD);`// 按线程数限流；
> `rule1.setCount(20);`// 阈值是20，表示同时最大20个线程，超过则限流；
> 
> 后面methodBRunningTime变短为20ms，试想：
> 方法耗时20ms，如果只有1个线程跑，那么1秒可以跑1000/20=50个；
> 最大20个线程，20*50=1000，也就是1秒内最大的qps为1000，
> 在程序中除了`TimeUnit.MILLISECONDS.sleep(methodBRunningTime);`20ms还有一些其它代码的执行消耗，加上实时统计的误差，所以看到pass在800-1000之间。
> 
> 如果把阈值20改为1，那么这时1秒跑50个，可以看到后面的pass在50左右。
> 
> 估计你是看前面几十秒pass出现了很多20，后面突然变大的原因，自己也曾有此疑惑。
> 
> 最开始methodBRunningTime=2000ms，跟20ms不同，不能直接20*(1000/2000)=10来算，
> 因为大于1秒，而20个线程几乎是同时跑的，然后一起休眠2秒，所以输出的pass大概是
> 0 20 0 20 ...
> 
> **参考：**
> [https://github.com/alibaba/Sentinel/wiki/如何使用#流量控制规则-flowrule](https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6%E8%A7%84%E5%88%99-flowrule)

谢谢大佬!!! 明白了.
