### ISSUE TITLE
系统规则设置后无效

### ISSUE THREAD

**Issue by chenfei7357** [alibaba/Sentinel#378]
这是流控配置：
![image](https://user-images.githubusercontent.com/40679609/50630585-65cff680-0f7c-11e9-9fc2-981668f4cedf.png)
这是系统规则配置：

![_20190103172701](https://user-images.githubusercontent.com/40679609/50630877-5ef5b380-0f7d-11e9-8c96-25b8a30ece2c.png)

结果：
![image](https://user-images.githubusercontent.com/40679609/50630910-7634a100-0f7d-11e9-90e7-410a17d27cb1.png)

这个linux系统机子上就部署了一台应用，系统规则的qps设置为0，请求没有被拦截？是什么问题？

**Comment by sczyh30** [comment]
Hi, please ensure your resource entry is **inbound** (via API: `SphU.entry(resourceName, EntryType.IN)` or via annotation).

---

请检查资源是否定义为入口资源（通过 API 定义：`SphU.entry(resourceName, EntryType.IN)` 或通过注解配置），系统规则仅针对入口资源生效。更多信息可参考 [系统规则文档](https://github.com/alibaba/Sentinel/wiki/系统自适应限流#系统规则)。

**Comment by chenfei7357** [comment]
> Hi, please ensure your resource entry is **inbound** (via API: `SphU.entry(resourceName, EntryType.IN)` or via annotation).
> 
> 请检查资源是否定义为入口资源（通过 API 定义：`SphU.entry(resourceName, EntryType.IN)` 或通过注解配置），系统规则仅针对入口资源生效。更多信息可参考 [系统规则文档](https://github.com/alibaba/Sentinel/wiki/%E7%B3%BB%E7%BB%9F%E8%87%AA%E9%80%82%E5%BA%94%E9%99%90%E6%B5%81#%E7%B3%BB%E7%BB%9F%E8%A7%84%E5%88%99)。

通过注解，是有配置的
![image](https://user-images.githubusercontent.com/40679609/50631683-37ecb100-0f80-11e9-9550-0850c3a6e361.png)

**Comment by chenfei7357** [comment]
> Hi, please ensure your resource entry is **inbound** (via API: `SphU.entry(resourceName, EntryType.IN)` or via annotation).
> 
> 请检查资源是否定义为入口资源（通过 API 定义：`SphU.entry(resourceName, EntryType.IN)` 或通过注解配置），系统规则仅针对入口资源生效。更多信息可参考 [系统规则文档](https://github.com/alibaba/Sentinel/wiki/%E7%B3%BB%E7%BB%9F%E8%87%AA%E9%80%82%E5%BA%94%E9%99%90%E6%B5%81#%E7%B3%BB%E7%BB%9F%E8%A7%84%E5%88%99)。

找到问题了，谢谢

**Comment by wangyingwei001** [comment]
请问是什么问题导致的 我现在也是配置了不生效
