### ISSUE TITLE
配置dashboard参数，接口无法调通问题

### ISSUE THREAD

**Issue by Never12581** [alibaba/Sentinel#38]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
我配置了dashboard的参数，希望能够看到请求的可视化。此时调用其他服务的接口失败。
失败直接原因是：NoClassDefFoundError: Could not initialize class com.alibaba.csp.sentinel.Constants
出错行：master分支 com.alibaba.csp.sentinel.context.ContextUtil 的 113行 Constants.ROOT.addChild(node);

#33 33 ## Describe what you expected to happen
希望在配置了 dashboard 参数后能够调通接口（配置前，能够调通接口）

### How to reproduce it (as minimally and precisely as possible)
1、引入sentinel-dubbo-adapter，sentinel-transport-simple-http，dubbo
2、配置dashboard的参数   ##便可复现

#33 ## Tell us your environment
dubbo.version 2.6.0
sentinel.version  0.1.1-SNAPSHOT or 0.1.0
csp.sentinel.dashboard.server=http://localhost:8080
csp.sentinel.api.port=8878
csp.sentinel.heartbeat.interval.ms=20
csp.sentinel.metric.file.single.size=52428800
csp.sentinel.metric.file.total.count=6

### Anything else we need to know?
本人新手，希望验证这个issue的时候，大神先自己直接配置一遍走一遍，也许是我本身配置的问题。

**Comment by zhaoxp1** [comment]
可以使用JDK1.8试试，我这样配置没问题

**Comment by Never12581** [comment]
谢谢是我配置的问题
