### ISSUE TITLE
Flow control of minute/hour level

### ISSUE THREAD

**Issue by zhousiliang163** [alibaba/Sentinel#386]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by CodingSinger** [comment]
mark

**Comment by foreveryang321** [comment]
调用
```java
// 单位ms
IntervalProperty.updateInterval(int newInterval)
```

**Comment by zhousiliang163** [comment]
只修改这个并不能达到目的，修改这个值只是把把滑动窗口的时间拉长了，但其实限流的时候，用的平均值还是以每秒计算的

发自我的 iPhone

**Comment by hubuyt** [comment]
可以吧qps设置为小数吗

**Comment by phantomedc** [comment]
> 调用
> 
> ```java
> // 单位ms
> IntervalProperty.updateInterval(int newInterval)
> ```

I am also facing this problem, this method does not work.

**Comment by NaraLuwan** [comment]
有这种应用场景吗？一分钟甚至一小时一次还用限流？？？

**Comment by CalvinKirs** [comment]
> 有这种应用场景吗？一分钟甚至一小时一次还用限流？？？

有一种就是比如我们的黑名单，用户每天短线验证码不超过五词，最早的时候一些网站没有这东西，然后就有了所谓的短信轰炸机了

**Comment by NaraLuwan** [comment]
> > 有这种应用场景吗？一分钟甚至一小时一次还用限流？？？
> 
> 有一种就是比如我们的黑名单，用户每天短线验证码不超过五次，最早的时候一些网站没有这东西，然后就有了所谓的短信轰炸机了。不过也不一定要用sentinel

哦哦，我感觉这种场景并不适合用 sentinel，在极端竞争条件下并不能精准限流。

**Comment by sczyh30** [comment]
Currently Sentinel is designed for handling large burst traffic, not for limiting with the business logic. This could be improved later (after we support arbitrary statistic time span for different resources).
