### ISSUE TITLE
project.name后续是否可以考虑直接读取spring.applicaton.name

### ISSUE THREAD

**Issue by px-kelvin** [alibaba/Sentinel#389]
你好，我想问下project.name后续是否可以考虑直接读取spring.applicaton.name？或者读取properties文件也行，因为project.name是需要强制在jvm参数上添加的，这样子每个项目要引入，都需要让运维做对应的修改，对运维人员不是很友好。目前项目又不准备引入cloud-alibaba-sentinel，因为内部有一些引用我们是没用到的，比如说dubbo的集成。

**Comment by sczyh30** [comment]
`project.name` 需要在项目运行一开始就要读入。建议先参考 Spring Cloud Alibaba Sentinel 的方式在初始化阶段读取 `spring.application.name`:

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelAutoConfiguration.java#L78

我们后续也会改善配置的读取形式。See also #105, #64 and #62.
