### ISSUE TITLE
Code compilation error

### ISSUE THREAD

**Issue by berace** [alibaba/Sentinel#39]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
<artifactId>sentinel-dashboard</artifactId>
<version>0.1.0</version>
/sentinel-dashboard/src/main/java/com/taobao/csp/sentinel/dashboard/metric/MetricFetcher.java
line number 303 and 320
The method getResource() is undefined for the type MetricNode

### Tell us your environment

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by sczyh30** [comment]
Hi, could you please tell me your branch? We've test both `release-0.1` and `master`, all compiles successfully.

**Comment by berace** [comment]
release-0.1
i'll try again later
