### ISSUE TITLE
关于Sentinel客户端寻找本地IP的问题

### ISSUE THREAD

**Issue by TenYearsIn** [alibaba/Sentinel#395]
Sentinel-core jar包下的 com.alibaba.csp.sentinel.util.HostNameUtil 这个类，默认取的是本机的公网ip，在公司内部使用的话，IP是局域网中的地址，是否可将这个类当做配置文件参数暴露出来，简而言之，取本地服务的IP的代码太暴力。适配性不强~

**Comment by cdfive** [comment]
可以通过-Dcsp.sentinel.heartbeat.client.ip=xxx配置
参考PR #261

**Comment by sczyh30** [comment]
See also #246 for more information.

**Comment by pstree** [comment]
spring.cloud.inetutils.preferred-networks=172.   没有这样的参数支持多网卡吗

**Comment by sczyh30** [comment]
> spring.cloud.inetutils.preferred-networks=172. 没有这样的参数支持多网卡吗

You may open a new issue to discuss it. Contributions are welcomed!

**Comment by Young200808** [comment]
那如果部署到容器上
-Dcsp.sentinel.heartbeat.client.ip=xxx
要如何动态获取ip呢

**Comment by jasonjoo2010** [comment]
> 那如果部署到容器上
> -Dcsp.sentinel.heartbeat.client.ip=xxx
> 要如何动态获取ip呢

这个一般如果是容器的话，各编排系统都有对应的环境变量存放容器的ip地址的
实在不行，直接使用系统命令来获取也可以

**Comment by Young200808** [comment]
> > 那如果部署到容器上
> > -Dcsp.sentinel.heartbeat.client.ip=xxx
> > 要如何动态获取ip呢
> 
> 这个一般如果是容器的话，各编排系统都有对应的环境变量存放容器的ip地址的
> 实在不行，直接使用系统命令来获取也可以

你是指在代码里通过系统命令来获取？我也是公司内网使用，现在使用挺麻烦的，能否考虑一下支持一下呢

**Comment by jasonjoo2010** [comment]
> > > 那如果部署到容器上
> > > -Dcsp.sentinel.heartbeat.client.ip=xxx
> > > 要如何动态获取ip呢
> > 
> > 
> > 这个一般如果是容器的话，各编排系统都有对应的环境变量存放容器的ip地址的
> > 实在不行，直接使用系统命令来获取也可以
> 
> 你是指在代码里通过系统命令来获取？我也是公司内网使用，现在使用挺麻烦的，能否考虑一下支持一下呢

你们有编排吧？比如mesos/k8s/或其它，用编排启动一个简单容器，你登上去看一下export -a的输出就知道哪个环境变量存放了容器ip了（不过像我们这种用calico网络直接自动获取就行了）
如果用shell取的话，这个是不能在jvm内做的（系统安全策略）
