### ISSUE TITLE
关于熔断降级规则设置后，不按规则执行

### ISSUE THREAD

**Issue by chenfei7357** [alibaba/Sentinel#397]
应用内埋点和动态规则：
![image](https://user-images.githubusercontent.com/40679609/50830663-62c17580-1383-11e9-9d02-cc58e497f80d.png)
请求的接口：
![image](https://user-images.githubusercontent.com/40679609/50830695-78cf3600-1383-11e9-95f5-2bb3b23ae604.png)

控制台设置规则：
![image](https://user-images.githubusercontent.com/40679609/50824492-b5923180-1371-11e9-890f-1da77a3256cb.png)
结果：
![image](https://user-images.githubusercontent.com/40679609/50824524-c8a50180-1371-11e9-816f-2cc3d4e5380e.png)

本地模拟的代码：
![image](https://user-images.githubusercontent.com/40679609/50824952-cd1dea00-1372-11e9-825e-df41f496b3e1.png)
![image](https://user-images.githubusercontent.com/40679609/50824968-d60ebb80-1372-11e9-9403-b4c1ff3bc8cd.png)

异常数 (DEGRADE_GRADE_EXCEPTION_COUNT)：当资源近 1 分钟的异常数目超过阈值之后会进行熔断。
正常我设置这个规则，不是应该抛出一个异常，接下来全部降级吗？好像结果并不是这个。

**Comment by xiajunhust** [comment]
你时间窗口设置的是10S呢，不是一分钟。时间窗口改成60了再试试。

**Comment by sczyh30** [comment]
Please check your rules and the `~/logs/csp/xxx-metrics.log` log.
