### ISSUE TITLE
sentinel-core is absent in Maven Center Repository

### ISSUE THREAD

**Issue by pig4cloud** [alibaba/Sentinel#4]
![image](https://user-images.githubusercontent.com/12409311/43189660-a781e674-9029-11e8-85f3-43bed2d1d6c7.png)

1.  maven 厂库没有找到   sentinel-core  jar
2. 是需要手动 install吗

**Comment by sczyh30** [comment]
Hi, we'll publish the first version (0.1.0) these days.

Hi, 我们将在这几天向中心仓库发布第一个版本（0.1.0）。您可以先 clone 下来体验一波 :)

**Comment by pig4cloud** [comment]
thx .
