### ISSUE TITLE
Please don't sign people up for email subscriptions just because they starred a *similar* repository

### ISSUE THREAD

**Issue by flipcoder** [alibaba/Sentinel#402]
I received an email subscription from you guys that said this
:
> You are receiving this email because we noticed you stared Hystrix on GitHub. 

I'm fine with being contacted if it's something specific or maybe if I star the project specifically, but putting people on an email list just because they starred something *similar* once is not a good idea.  This is something that won't scale if more projects do this.  This may even qualify as spam.

Thanks

**Comment by sczyh30** [comment]
Hi, we are sorry that the email bothered you. You can choose whether to join the email subscription and we won't sent the email later unless you accept. We'll improve the approach and find a better way to contact with developers. Sorry for disturbance.
