### ISSUE TITLE
Fallback support for Dubbo

### ISSUE THREAD

**Issue by momsbaby** [alibaba/Sentinel#41]
目前从源码看到只是抛出Exception，不支持自定义fallback方法：
建议支持到方法级别的fallback，是否可以考虑约定大于配置的方式来定义fallback

**Comment by sczyh30** [comment]
可以使用 [Dubbo 的 Mock 功能](http://dubbo.apache.org/#!/docs/user/demos/local-mock.md?lang=zh-cn)

**Comment by momsbaby** [comment]
@sczyh30，mock只能针对客户端，没有服务端的么？

**Comment by sczyh30** [comment]
服务降级主要针对的是客户端的场景。
后续版本我们会考虑支持配置全局的 fallback 方法。
