### ISSUE TITLE
Redundant semicolon in com.alibaba.csp.sentinel.node.metric.MetricWriter class

### ISSUE THREAD

**Issue by kangyl** [alibaba/Sentinel#410]
// 在第349行多了为分号.位于方法closeAndNewFile内.

## Issue Description
In the 349th line, there is more a semicolon. It is located in the method closeAndNewFile.

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
find it in the code

### Describe what you expected to happen
Remove any extra semicolons

### How to reproduce it (as minimally and precisely as possible)

in the code

### Tell us your environment

win7 idea
### Anything else we need to know?
no

**Comment by kangyl** [comment]
![vdo0 198a1 k 0cayj0m](https://user-images.githubusercontent.com/3366349/51070657-d4e5d300-167f-11e9-81b6-39a5de564c92.png)

**Comment by Frankzhaopku** [comment]
You can try to fix this and give us a pull request.
