### ISSUE TITLE
How to do persistence for parameter flow rules and cluster config

### ISSUE THREAD

**Issue by Wizzercn** [alibaba/Sentinel#414]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

已经对流控规则、降级规则、系统规则、授权规则，进行读写持久化，不知道集群流控的配置和热点规则，如何进行持久化？

How to do persistence for parameter flow rules and cluster config?

### Describe what you expected to happen

源码见这里 (The source code is here)：
https://github.com/nutzam/nutzboot/blob/dev/nutzboot-starter/nutzboot-starter-sentinel-dubbo/src/main/java/org/nutz/boot/starter/sentinel/SentinelStarter.java

### Tell us your environment

Sentinel 1.4.1

**Comment by Wizzercn** [comment]
I want to store the cluster configuration info in redis,and from redis,how do it?

**Comment by Wizzercn** [comment]
```
FlowRuleManager.register2Property(redisDataSource.getProperty());
WritableDataSourceRegistry.registerFlowDataSource(wds);
```
for example FlowRule's read and write sources can be changed. How do you do Cluster ?

**Comment by sczyh30** [comment]
For reading configuration, you could register dynamic data sources. For publishing configurations you might need to refactor the Sentinel dashboard.
