### ISSUE TITLE
[Feature] DataSource integration for Apollo

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#42]
## Issue Description

Type: *feature request*

### Describe what feature you want

Add DataSource integration for [Apollo](https://github.com/ctripcorp/apollo).

**Comment by zhaoxp1** [comment]
相比阿里开源的diamond不知道有什么优势，是否也支持diamond？

**Comment by sczyh30** [comment]
[Nacos](https://nacos.io/#/?lang=zh-cn) 是 Diamond 的开源进化版本，Sentinel 支持 Nacos 作为动态配置源，可以参见[这里](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%8E%A8%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8-nacos-%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99)。
