### ISSUE TITLE
Clicking on the first-level menu will jump to the home page in dashboard

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#421]
## Issue Description
kind/enhancement
### Describe what happened (or what feature you want)
I found a small problem about the sidebar menu of dashboard.
When I was in "Machine Discovery" or "Monitoring" page of appA, click another appB's first-level menu, the second-level will be expanded as expected, but the right page jumped to the home page.
It's a little inconvenient.
### Describe what you expected to happen
The page should not jumped as the click only tend to expand the menu.
The home page may enrich more functions in the future, and we can jump it by clicking the "home page" menu on the top of sibar menus, not clicking the first-level menu.

In sidebar.html:
```
<li ng-class="{active: true}" ng-repeat="entry in apps | filter: { app: searchApp }">{{dropDown}}
        <a href="#" ng-click="click($event)" collapse="{{collpaseall == 1}}" style="font-size: 16px;word-break: break-word;">
          &nbsp;{{entry.app}}
          <span class="fa arrow"></span>
          <span class="arrow">({{entry.heathCount}}/{{entry.machines.length}})</span>
        </a>
...
```
The first-level menu use `<a href="#">`， which cause the jump.
We can use `<a href="javascript:void(0);">` 
or find a way to cancel the brower's default behavior of tag `<a href="#">` in click function.
### How to reproduce it (as minimally and precisely as possible)
Add one or more app in sentinel-dashboard，click "Machine Discovery",
and then click any first-level menu, the home page will be jumped.
### Tell us your environment
win7, chrome

**Comment by sczyh30** [comment]
Thanks for your suggestion. We can replace it with `<a href="javascript:void(0);">` to avoid jumping. Would you like to contribute a PR?

**Comment by cdfive** [comment]
Ok, I'm pleased to.
