### ISSUE TITLE
More information (e.g. triggered rules, real-time QPS) is needed to carry in BlockException

### ISSUE THREAD

**Issue by yikangfeng** [alibaba/Sentinel#424]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

在捕获到热点参数限流的异常 或者 其他限流形式的异常后 希望能够获取到一些信息，例如，当发生热点参数限流后，捕获到这个 ParamFlowException 后（其他异常也同样需要），希望能获取到 当前发生限流的方法信息，方法上打的RequestMapping 接口信息，当前触发限流的规则信息，当前的QPS值，配置的QPS值，资源名 等信息，方便在运行时拿到这些信息发送报警。

More information (e.g. triggered rules, real-time QPS) is needed to carry in `BlockException` so that we can leverage relevant info to send alarm messages.

### Describe what you expected to happen

希望能获取到 当前发生限流的方法信息，方法上打的RequestMapping 接口信息，当前触发限流的规则信息，当前的QPS值，配置的QPS值，资源名 等信息，方便在运行时拿到这些信息发送报警。

强烈需要在 1.4.2 版本就要支持。

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. We can put the triggered rule and maybe current metrics to the subclasses of `BlockException`. This is expected to be released in 1.4.2.

**Comment by sczyh30** [comment]
Sentinel 1.4.2 has been released and now we can get the triggered rule via the `BlockException#getRule` method. If you're going to add alarm listener, you can leverage callbacks in StatisticSlot. See here for instructions: https://github.com/alibaba/Sentinel/pull/418#issuecomment-458024816
