### ISSUE TITLE
ConcurrentHashMap used in methods?

### ISSUE THREAD

**Issue by zhanfengGh** [alibaba/Sentinel#426]
## Issue Description

bug report

### Describe what happened (or what feature you want)
When reading the source,I find several incorrect uses of ConcurrentHashMap where a HashMap can satisfy the need because we don't need the concurrency in the method.

### Describe what you expected to happen
Fix it maybe or explain why you use it anyway

### How to reproduce it (as minimally and precisely as possible)
1. line 88 in FlowRuleUtil.java
```java
 public static <K> Map<K, List<FlowRule>> buildFlowRuleMap(List<FlowRule> list, Function<FlowRule, K> groupFunction,
                                                              Predicate<FlowRule> filter, boolean shouldSort) {
        Map<K, List<FlowRule>> newRuleMap = new ConcurrentHashMap<K, List<FlowRule>>();
        if (list == null || list.isEmpty()) {
            return newRuleMap;
        }
...
}
```
1. line 125 in ParamFlowRuleManager.java
1. line 119 in StatisticNode.java
### Anything else we need to know?
none

**Comment by sczyh30** [comment]
Hi, though the Map was not operated concurrently in the method, as the return value it might be consumed concurrently by other callers. The contract can be described in the javadoc so let callers know.

**Comment by zhanfengGh** [comment]
Hi, first of all, thanks for you response. But you answer is not good enough, if the caller may consume the return value concurrently, is it better to return a ConcurrentMap than the Map?
