### ISSUE TITLE
Support adding prefix to Dubbo service resource name in Sentinel Dubbo Adapter

### ISSUE THREAD

**Issue by zhongxunking** [alibaba/Sentinel#427]
Dubbo适配器提供的资源名目前没有前缀，只是包路径+类名。导致在控制台看到时不能直观的看出是Dubbo调用。可否增加前缀以示区别。比如服务提供者使用dubbo-provider，服务消费者使用dubbo-consumer

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. For this, we need to consider compatibility with previous versions. Maybe we can add a property to control whether the resource name has a common prefix and define configure the common prefix.

**Comment by zhongxunking** [comment]
thanks, it is good. which version of sentinel will provide the feature?

**Comment by sczyh30** [comment]
Contribution is welcomed~

**Comment by linlinisme** [comment]
I have a question: If the dubbo service shows the prefix, then the configuration rules should be prefixed?

**Comment by sczyh30** [comment]
> I have a question: If the dubbo service shows the prefix, then the configuration rules should be prefixed?

If the Dubbo service resource is added with the prefix, then when we configure rules it should also be prefixed. This is not compatible with existing rules.

**Comment by linlinisme** [comment]
So is it necessary to add the prefix?

**Comment by sczyh30** [comment]
> thanks, it is good. which version of sentinel will provide the feature?

This will be introduced in 1.7.0. See #859 for details.
