### ISSUE TITLE
Sentinel introduces the jar package, which will initialize what content

### ISSUE THREAD

**Issue by luoye1989hzx** [alibaba/Sentinel#429]
你好

<img width="795" alt="default" src="https://user-images.githubusercontent.com/5382724/51365010-380cb500-1b19-11e9-9eb1-405356a68ccf.png">

<img width="599" alt="default" src="https://user-images.githubusercontent.com/5382724/51365217-2d065480-1b1a-11e9-8e08-0de13ceca336.png">

**Comment by sczyh30** [comment]
Hi, could you please illustrate your question? You can refer to the [issue template](https://github.com/alibaba/Sentinel/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by sczyh30** [comment]
For memory footprint, you can refer to the [Benchmark](https://github.com/alibaba/Sentinel/wiki/Benchmark#%E5%86%85%E5%AD%98%E5%8D%A0%E7%94%A8%E6%83%85%E5%86%B5).

Closing this issue due to no response. Feel free to reopen the issue if you have any other questions.
