### ISSUE TITLE
sentinel-dashboard version 1.4.1 can't add cluster flow rule to flow v2

### ISSUE THREAD

**Issue by pingan365** [alibaba/Sentinel#432]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
there is no way to add cluster flow rule in sentinel-dashboard version 1.4.1.
by default it open flow v1 view and add flow rule through v1 

### Describe what you expected to happen
choose flow rule v1 or flow rule v2 by cluster mode 
call FlowControllerV2 in cluster mode
### How to reproduce it (as minimally and precisely as possible)

1. in sentinel-dashboard version 1.4.1
2. add flow rule in cluster mode
3. flow_v1.js call FlowControllerV1

### Tell us your environment
jdk1.8, idea

**Comment by sczyh30** [comment]
Hi, the link to cluster page (/v2/flow) has been hidden and you can manually visit that page. You need to refactor the dashboard first. See [the document](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89#%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE) for more information.
