### ISSUE TITLE
There are some questions about the demo of the cluster.

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#439]
在com.alibaba.csp.sentinel.demo.cluster.init 包下
第一个问题: initClientServerAssignProperty  方法 具体是做什么的...  
然后参数 [{"clientSet":["112.12.88.66@8729","112.12.88.67@8727"],"ip":"112.12.88.68","machineId":"112.12.88.68@8728","port":11111}]  里的clientSet是客户端地址集合吗  那后面的ip和machineId 为什么又重复了 除了多了个端口号 是代表什么意义.   目前推测machineId是服务端地址.   还有port参数 是指项目启动的端口吗   比如8080这种?
第二个问题:initDynamicRuleProperty 和 registerClusterRuleSupplier 做的事感觉很像啊. 本地客户端初始化的流量规则 和 集群初始化的流量规则 一样  这样的意义是什么. 会有什么冲突吗.

**Comment by sczyh30** [comment]
1. `initClientServerAssignProperty` 根据推送的 token server/client 分配表解析 token client 的通信配置，仅在当前机器身份为 token client 时有效。分配表中 machineId (示例中的格式为 `ip@commandPort`) 用于标识某一台 token server，`ip` 和 `port` 为所属 token server 的 IP 和端口。
2. `initDynamicRuleProperty` 用于注册客户端的动态规则源，`registerClusterRuleSupplier` 用于注册 token server 的规则源生成器。详细信息可以参考 [集群限流规则配置](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7#%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F)。
