### ISSUE TITLE
sentinel支持springmvc dubbo tomcat下部署进行流控吗？

### ISSUE THREAD

**Issue by zzhignore1** [alibaba/Sentinel#44]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
请参考 [主流框架的适配](https://github.com/alibaba/Sentinel/wiki/%E4%B8%BB%E6%B5%81%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%82%E9%85%8D) 文档。

请在钉钉群（见 [README](https://github.com/alibaba/Sentinel/wiki/%E4%BB%8B%E7%BB%8D#%E8%B4%A1%E7%8C%AE)）、[Gitter](https://gitter.im/alibaba/Sentinel) 或 [User Group](https://groups.google.com/forum/#!forum/sentinel-users) 发起提问，GitHub Issue 仅用来 bug report / feature request.
