### ISSUE TITLE
The dashboard uses nacos as a data source

### ISSUE THREAD

**Issue by naturalyui** [alibaba/Sentinel#440]
## Issue Description
Type:  feature request
您好，我在阅读sentinel-dashboard1.4.1的源码时看到FlowControllerV2和test下以nacos作为数据源的例子，说实话我很喜欢，不过将nacos的groupId写死好像不太友好？

Hello, when I read the source code of sentinel-dashboard1.4.1, I saw the example of using nacos as the data source under FlowControllerV2 and test. To be honest, I like it very much, but it seems that it is not friendly to write nacos groupId?

### What feature you want
1、sentinel客户端像nacos一样提供一个groupId的属性
2、或者在添加限流规则时提供额外参数groupId

1. The sentinel client provides a groupId attribute like nacos
2. Or provides an additional parameter groupId when adding a current limit rule.

ps:现在nacos是否只支持持久化流控、降级、系统、授权规则中的一种？

Ps: Does nacos now only support one of the persistence of flow control, downgrade, system, and authorization rules?

**Comment by sczyh30** [comment]
Hi, the Nacos flow rule publisher in the dashboard is only a sample and you can refactor by yourself (provide the `groupId` and `dataId` pattern). You can use Nacos as the configuration center for any kind of rules, but you have to implement the publisher for yourself and refactor the corresponding web controller :)

**Comment by naturalyui** [comment]
Thanks for the reply, I am trying to do this
