### ISSUE TITLE
Support removing deprecated machines in Sentinel dashboard

### ISSUE THREAD

**Issue by naturalyui** [alibaba/Sentinel#446]
## Issue Description
When I debug locally, I change the list of the console of the port console to one more line of data. At present, I can only clean up the list of machines by restarting the console, but since I have not been able to persist the rules to naocs, so every time I do It takes a lot of difficulty to re-specify the rules.

**Comment by sczyh30** [comment]
Hi, it's necessary to provide functions for removing unused machines. We'll add interfaces and entries to it. Something to be considered:

- Support manually remove the machine in the machine list page
- Maybe it's necessary to support automatic removal after a machine has been marked as disconnected state for some time (this should be configurable)
- When an application has no connected machines in machine list, this application might not be displayed in the app list (sidebar). This should also be configurable.

For a temporary solution, you can refer to this PR: #168

**Comment by naturalyui** [comment]
ok
