### ISSUE TITLE
There are still some questions about the demo of the cluster.

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#447]
cluster demo里分embedded 和 server alone两个demo.  
问题: 我打包两个 embedded demo 在不同的服务器上启动 是否可以弄成 一个是token  一个是client.
因为我看到embedded的demo 里并没有 
  ReadableDataSource<String, Set<String>> namespaceDs = new NacosDataSource<>(remoteAddress, groupId,
            namespaceSetDataId, source -> JSON.parseObject(source, new TypeReference<Set<String>>() {}));
        ClusterServerConfigManager.registerNamespaceSetProperty(namespaceDs.getProperty());
 像 registerNamespaceSetProperty 这样的 代码出现.

**Comment by huihui1112** [comment]
然后再补充一个问题
ClusterFlowRuleManager.setPropertySupplier(namespace -> {
            ReadableDataSource<String, List<FlowRule>> ds = new NacosDataSource<>(remoteAddress, groupId,
                namespace + DemoConstants.FLOW_POSTFIX,
                source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {}));
            return ds.getProperty();
        });
ClusterFlowRuleManager.setPropertySupplier 里面的namespace参数哪来的...  
然后setPropertySupplier的规则源和 
贴下代码
 ReadableDataSource<String,List<FlowRule>> ruleSource = new ApolloDataSource<>("cluster", "clusterFlowRule",
                defaultRules, source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
        }));
  FlowRuleManager.register2Property(ruleSource.getProperty()); 
FlowRuleManage里面的规则源是否必须是同一个.

**Comment by sczyh30** [comment]
`ClusterFlowRuleManager#setPropertySupplier` 方法用于注册动态规则源生成器，根据动态配置的 namespace 来自动注册相应的动态规则源。默认 namespace 为应用名，可通过 namespace set 进行配置。

对于同一个应用而言，两个规则源应对应同一个配置中心路径。
