### ISSUE TITLE
Can you send sentinel-dashboard to private service?

### ISSUE THREAD

**Issue by ESPataPon** [alibaba/Sentinel#448]
能不能发sentinel-dashboard一个release版本到nexus上去,便于使用。公司不允许依赖snapshot 而且上传jar流程比较复杂

**Comment by sczyh30** [comment]
Hi, it makes no sense to deploy the Sentinel dashboard application jar to Maven Central. You can manually download the jar here: https://github.com/alibaba/Sentinel/releases
