### ISSUE TITLE
One minute exception number degradation policy failed

### ISSUE THREAD

**Issue by spilledyear** [alibaba/Sentinel#451]
## Issue Description

provider: 

```java
    @Override
    public User testDegrCount(Long userId) throws InterruptedException {
        Thread.sleep(500);
        if (userId % 10 == 0) {
            throw new RpcException("每500毫秒一个请求，一分钟可以处理120个请求，阈值设置为5，每10个请求抛出一个异常，50个请求之后异常数达到阈值，一分钟之内的请求将被降级");
        }
        return new User(100L, "三爷");
    }
```

consumer: 

```java
    public void testDegrCount() {
        for (int i = 1; i <= 300; i++) {
            try {
                log.info("{} : {} ", i, userService.testDegrCount(Long.valueOf(i)).getUserName());
            } catch (Exception e) {
                e.printStackTrace();
                log.error("第 {} 个限流失败", i);
            }
        }
    }
```

降级规则如下，这里的资源名称我做了特殊处理

```json
[{"app":"titans-provider3","count":5.0,"cut":false,"grade":2,"key":"1548378133752","limitApp":"titans-consumer","passCount":0,"resource":"@DUBBO@com.zto.sentinel.service.UserService","timeWindow":10}]
```

### Describe what happened (or what feature you want)

调用服务的时候，没有按照预期进行降级。服务一直都可以调用成功，`SentinelDubboProviderFilter` 中的 `Tracer.trace(result.getException())`  每10个请求会被执行一次

### Describe what you expected to happen

预期 50个请求之后异常数达到阈值，一分钟之内的请求将被降级

### How to reproduce it (as minimally and precisely as possible)

在我本地，按照这种方式调用，一直都可以重现

### Tell us your environment

- Windows 10
- JDK 1.8

**Comment by luoxn28** [comment]
你的provider中testDegrCount方法抛出异常是业务逻辑本身抛出的，是不会统计到sentinel内部exception number的，如果需要将这种异常统计到sentinel内部exception number中，可使用`Tracer.trace(Throwable e)`来做，也就是在你代码consumer中testDegrCount方法捕获异常后，使用`Tracer.trace(Throwable e)`就行了。可以参考sentinel demo中的`ExceptionCountDegradeDemo`.

**Comment by spilledyear** [comment]
> 你的provider中testDegrCount方法抛出异常是业务逻辑本身抛出的，是不会统计到sentinel内部exception number的，如果需要将这种异常统计到sentinel内部exception number中，可使用`Tracer.trace(Throwable e)`来做，也就是在你代码consumer中testDegrCount方法捕获异常后，使用`Tracer.trace(Throwable e)`就行了。可以参考sentinel demo中的`ExceptionCountDegradeDemo`.

我有在ProviderFilter中 trace 这个异常的，昨天问了群里得大佬，异常比例和一分钟异常数 只能对具体的方法生效，而我的规则是加在接口上的，所以没有生效，目前这个问题已经解决了
