### ISSUE TITLE
Question about average local threshold type in cluster flow control

### ISSUE THREAD

**Issue by huihui1112** [alibaba/Sentinel#455]
目前我已自己搭了一套这样的环境.
目前是三个应用使用内嵌式的 而不是独立的token server
所以情况如下
三台机器.
一台做token server
两台做 client.
然后我将单机均摊模式设为qps=1 
在其中一台client台 疯狂发出请求 然后看到的确被限流了 这个没毛病
但是另一台client 我去访问的时候 为什么也被限流了  我不是选的单机均摊模式 互相之间不影响吗...

**Comment by sczyh30** [comment]
单机均摊模式下配置的阈值等同于单机能够承受的限额，token server 会根据连接数来计算总的阈值（比如独立模式下有 3 个 client 连接到了 token server，然后配的单机均摊阈值为 10，则计算出的集群总量就为 30）；**单机均摊阈值模式仅为按连接数实时计算出总的集群阈值，最后还是按照算出的集群总量来限制，并不是说每台单机一定均摊到这个数值。**

---

In **average local threshold type**, Sentinel will calculate the total cluster threshold according to: `avg_local_threshold * real_connected_count`. That does not mean every instance will be limited as the average threshold.

**Comment by huihui1112** [comment]
> 单机均摊模式下配置的阈值等同于单机能够承受的限额，token server 会根据连接数来计算总的阈值（比如独立模式下有 3 个 client 连接到了 token server，然后配的单机均摊阈值为 10，则计算出的集群总量就为 30）；**单机均摊阈值模式仅为按连接数实时计算出总的集群阈值，最后还是按照算出的集群总量来限制，并不是说每台单机一定均摊到这个数值。**
> 
> In **average local threshold type**, Sentinel will calculate the total cluster threshold according to: `avg_local_threshold * real_connected_count`. That does not mean every instance will be limited as the average threshold.

问题一:那么假如我单机均摊设置为10   现在有三台client A B C.连上token server. 然后总qps是18  此时是 < 限流总qps30的. 
同时 某一台client A的qps 是12  超过了10. 此时clientA 会被限流吗.
问题二:emb模式下的token server的总qps 应该如何设置.  四台机器 Client A B C 和 Server D  
其中A B C 单机均摊限流10. 那么D的总qps应该如何设定呢.  因为我在demo里没看到setMaxAllowQps这类的方法.

**Comment by sczyh30** [comment]
> > 单机均摊模式下配置的阈值等同于单机能够承受的限额，token server 会根据连接数来计算总的阈值（比如独立模式下有 3 个 client 连接到了 token server，然后配的单机均摊阈值为 10，则计算出的集群总量就为 30）；**单机均摊阈值模式仅为按连接数实时计算出总的集群阈值，最后还是按照算出的集群总量来限制，并不是说每台单机一定均摊到这个数值。**
> > In **average local threshold type**, Sentinel will calculate the total cluster threshold according to: `avg_local_threshold * real_connected_count`. That does not mean every instance will be limited as the average threshold.
> 
> 问题一:那么假如我单机均摊设置为10 现在有三台client A B C.连上token server. 然后总qps是18 此时是 < 限流总qps30的.
> 同时 某一台client A的qps 是12 超过了10. 此时clientA 会被限流吗.
> 问题二:emb模式下的token server的总qps 应该如何设置. 四台机器 Client A B C 和 Server D
> 其中A B C 单机均摊限流10. 那么D的总qps应该如何设定呢. 因为我在demo里没看到setMaxAllowQps这类的方法.

- 针对问题 1，由于总量未超过 `10 * 3 = 30`，因此不限（单机均摊仅用于计算最终的集群总阈值）。
- 针对问题 2，embedded 模式下每个实例都是等价的，因此若希望使用单机均摊模式，只需要给出总量 Q 以及机器数 N，单机均摊阈值设置为 `Q / N` 即可。
