### ISSUE TITLE
Does Sentinel support link tracking?

### ISSUE THREAD

**Issue by naturalyui** [alibaba/Sentinel#475]
## Issue Description
Type: feature request

Hello, I didn't find out in the documentation whether sentinel supports link tracking, so I tried to use springcloud + feign myself and found that the console didn't show detailed links.

**Comment by sczyh30** [comment]
Hi, Sentinel support local invocation chain tracing and you can see it in the resource chain page like this:

![chain-en](https://user-images.githubusercontent.com/9434884/48124680-ded20b00-e2b7-11e8-9e16-382746316ce0.png)

---

Sentinel 支持单机的调用链路统计，可以在 Sentinel 控制台的[簇点链路页面](https://github.com/alibaba/Sentinel/wiki/%E6%8E%A7%E5%88%B6%E5%8F%B0#51-%E7%B0%87%E7%82%B9%E9%93%BE%E8%B7%AF%E4%B8%AD%E6%98%BE%E7%A4%BA%E5%88%9A%E5%88%9A%E8%B0%83%E7%94%A8%E7%9A%84%E8%B5%84%E6%BA%90%E5%8D%95%E6%9C%BA%E5%AE%9E%E6%97%B6)查看详情。
