### ISSUE TITLE
The problem that the client is not connected to the console

### ISSUE THREAD

**Issue by zgqyfj** [alibaba/Sentinel#477]
依照官方文档下载了1.4.1的dashboard
启动配置如下
`java -Dserver.port=8091 -Dcsp.sentinel.dashboard.server=localhost:8091 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar`
应用引入sentinel相关依赖以及dubbo的适配器
给tomcat设置启动参数
`-Djava.net.preferIPv4Stack=true -Dcsp.sentinel.api.port=8720 -Dcsp.sentinel.dashboard.server=localhost:8091 -Dproject.name=dubbo-provider-demo`

并没有在控制台看到相关应用信息,仔细阅读文档并核对配置项之后并没有发现错误
请问有可能是什么原因造成的

**Comment by sczyh30** [comment]
Hi, you can refer to the [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5) to check whether your application has been configured correctly.
