### ISSUE TITLE
DEGRADE_GRADE_RT模式的熔断规则，关于准降级状态后续request

### ISSUE THREAD

**Issue by cloud915** [alibaba/Sentinel#48]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
关于wiki中“准降级状态”后的描述是：

> 平均响应时间 (DEGRADE_GRADE_RT)：当资源的平均响应时间超过阈值（DegradeRule 中的 count，以 ms 为单位）之后，资源进入准降级状态。接下来如果持续进入 5 个请求，它们的 RT 都持续超过这个阈值，那么在接下的时间窗口（DegradeRule 中的 timeWindow，以 s 为单位）之内，对这个方法的调用都会自动地返回。

              
```

             if(this.grade == 0) {
                    exception = (double)clusterNode.avgRt();
                    if(exception < this.count) {
                        return true;
                    }

                    if(this.passCount.incrementAndGet() < 5L) {
                        return true;
                    }
                }

```

但是在验证该功能时，应该是后续的4个请求如果都超过阈值，接下来的时间窗口内，方法都会降级。
这里是否统一下？

**Comment by sczyh30** [comment]
此处已在 0.1.1 版本中修复并统一
