### ISSUE TITLE
Does Sentinel cluster flow control support uniform rate limiting (controlBehavior)?

### ISSUE THREAD

**Issue by linhaicai** [alibaba/Sentinel#485]
## Issue Description
sentinel 1.41版本
嵌入模式集群

### Describe what happened (or what feature you want)
昨天搭建完集群，流控拦截正常，但是一旦设置了流控效果为排队等待，则不起作用，仍然是拦截。
尝试了设置单台机器下的流控效果为排队等待，则正常。

**Comment by sczyh30** [comment]
Hi, Sentinel cluster flow control mode does not support other control effects now. By default the cluster control behavior is fast-fail.
