### ISSUE TITLE
What is the full name of Sph?

### ISSUE THREAD

**Issue by MoneyHacker** [alibaba/Sentinel#489]
概念理解 Sph 全称是什么？

**Comment by westonlv** [comment]
同问

**Comment by sczyh30** [comment]
Hi, `Sph` originated from "semaphore" initially (long long ago). It's regarded as a magic name in Sentinel and has been given more magic meanings :)

**Comment by qixiaobo** [comment]
You mean sph stands for semaphore?
Why O?Why U?
