### ISSUE TITLE
The flow control rule added in version 1.4.2 does not take effect.

### ISSUE THREAD

**Issue by chenhongbinbiti** [alibaba/Sentinel#490]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

添加流控规则没成功

### How to reproduce it (as minimally and precisely as possible)

1. 点簇点链路
2. 选一条
3. 点添加

### Tell us your environment

sentinel 1.4.2
dubbo 2.5.5
### Anything else we need to know?

本地跟断点，跟到ModifyRulesCommandHandler这个类里有一句
List<FlowRule> flowRules = JSONArray.parseArray(data, FlowRule.class)
这里的FlowRule的resouce = null
导致后面添加失败。

本地写了个测试用例，一样的data，一样的flowRule类
List<FlowRule> flowRules = JSONArray.parseArray(data, FlowRule.class)
resouce不为null

**Comment by sczyh30** [comment]
Hi, the fastjson version of your application might be deprecated. Please check the version of fastjson in your application and upgrade it to the latest version.

**Comment by chenhongbinbiti** [comment]
fastjson 我用的是1.2.55  而且本地测试和设断点跟用的同一个版本。

**Comment by chenhongbinbiti** [comment]
我在FlowRule的setResouce()方法里也设了断点，点添加规则，发现会先走setResouce，然后进走handle方法，再执行JSONArray.parseArray(data, FlowRule.class)的时候，并没有进setResouce方法。这个执行的顺序很怪。

**Comment by chenhongbinbiti** [comment]
我本地可以了，非常不好意思，可能是因为我之前用过1.4.0，所以导致我看到的和代码不一致。反复clean，install，突然就可以了。
