### ISSUE TITLE
How to solve the problem that Sentinel might take up too much memory?

### ISSUE THREAD

**Issue by z2468091508** [alibaba/Sentinel#492]
你好，Sentinel客户端在并发量很大的情况下有可能内存占用过大，这个应该如何解决？可以设置客户端的最大使用内存吗？

**Comment by sczyh30** [comment]
可以通过控制资源数目，减少不必要的资源定义，控制来源数目来保证内存占用不会占用太大。

--

Hi, you have to limit the number of resources by reducing unnecessary resources and origins to limit the memory footprint.
