### ISSUE TITLE
Circuit breaking based on RT does not take effect when the count > 5000 ms

### ISSUE THREAD

**Issue by ccb19880811** [alibaba/Sentinel#499]
### Describe what happened (or what feature you want)

熔断设置成RT，count设置成5000，线程超时是6秒，为何没熔断？貌似count大于等于5000(5秒）时都不行。

Circuit breaking based on RT does not take effect when the count > 5000 ms.

```java
//业务代码
@SentinelResource(value= Constant.SENTINEL_PAAS_RESOURCE,entryType = EntryType.IN,
blockHandler = "getTokenBlockHandler",blockHandlerClass = {SessionSentinelUtils.class},fallback = "getTokenDegrade")
@Override
public RPCResponse getToken() {
try {
  Thread.sleep(6000);
  String token = jwtService.getToken();
  return RPCResponseUtils.success(token);
} catch (CommonException e) {
return RPCResponseUtils.fail(e.getMsg());
} catch (Exception e) {
String msg = "paas服务获取token出错,识别码[" + UUIDUtils.getUUId() + "]";
logger.error(msg, e);
return RPCResponseUtils.fail(msg,logFlag,e);
}
}
//熔断规则
private void initDegradeRule() {
List<DegradeRule> rules = new ArrayList<>();
DegradeRule rule = new DegradeRule();
rule.setResource(Constant.SENTINEL_PAAS_RESOURCE);
// set threshold RT, 10 ms
rule.setCount(5000);
rule.setGrade(RuleConstant.DEGRADE_GRADE_RT);
rule.setTimeWindow(30);
rules.add(rule);
DegradeRuleManager.loadRules(rules);
}
```

**Comment by sczyh30** [comment]
Hi, the default max RT that Sentinel records is 4900 ms. RT that exceeds the threshold will be regarded as the maxRT (4900 ms, `Constants.TIME_DROP_VALVE` by default). You can modify this by adding a JVM parameter `-Dcsp.sentinel.statistic.max.rt=xxx` when starting your application.

---

Sentinel 默认统计的 RT 上限是 4900 ms，**超出此阈值的都会算作 4900 ms**，因此超出 4900 ms 的 RT 降级默认都不会生效。若需要变更此上限可以通过启动配置项 `-Dcsp.sentinel.statistic.max.rt=xxx` 来配置。

**Comment by westonlv** [comment]
StatisticSlot里面在统计RT的时候，如果RT>4900就会被设置成4900，没太明白为什么这么设计。
等待开发解释下

**Comment by sczyh30** [comment]
See #15 and #276
