### ISSUE TITLE
How to visit FlowControllerV2 in Sentinel dashboard

### ISSUE THREAD

**Issue by 188** [alibaba/Sentinel#500]
目前我这一直访问的FlowControllerV1
怎么切换到V2呀？
是需要手动改程序中的链接吗？
因为需要 实现 `@Qualifier("flowRuleApolloPublisher")` 把数据存到Apollo看说明需要用到V2
http://localhost:8080/#/dashboard/flow/usercenter

---

How to visit FlowControllerV2 in Sentinel dashboard?

**Comment by sczyh30** [comment]
Hi, the link to cluster page (/v2/flow) has been hidden and you can manually change the URL to visit that page, or modify the code of frontend router. The URL resembles:

http://localhost:8080/#/dashboard/v2/flow/usercenter

**Comment by 188** [comment]
谢谢，已经自已修改
