### ISSUE TITLE
RT is always 0 and circuit breaking does not take effect

### ISSUE THREAD

**Issue by Tzeross** [alibaba/Sentinel#504]
### Tell us your environment
sentinel   1.2.1  
java version "1.8.0_112"

![image](https://user-images.githubusercontent.com/33917408/53149674-56b70d80-35e9-11e9-8a15-71a8c0a22e6c.png)

**Comment by sczyh30** [comment]
Hi, could you please illustrate your question and give more information (e.g. code snippet, the rules you've configured)? If the RT ∈ (0ms, 1ms) then it will be displayed as 0.0.

**Comment by Tzeross** [comment]
> 嗨，您能否说明您的问题并提供更多信息（例如代码片段，您配置的规则）？如果RT∈（0ms，1ms）则它将显示为0.0。

就是这个原因了，谢谢
