### ISSUE TITLE
print resource name is incorrect

### ISSUE THREAD

**Issue by xburning** [alibaba/Sentinel#505]
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)
In README.md file，the resource name is incorrect :

|--timestamp-|------date time----|--resource-|p |block|s |e|rt
1529998904000|2018-06-26 15:41:44|hello world|20|0    |20|0|0

### Describe what you expected to happen
Should be :

|--timestamp-|------date time----|--resource-|p |block|s |e|rt
1529998904000|2018-06-26 15:41:44|HelloWorld|20|0    |20|0|0

**Comment by sczyh30** [comment]
Hi, thanks for reporting. Would you like to contribute a PR to fix it? You can refer to [the contribution guideline here](https://github.com/alibaba/Sentinel/wiki/%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97).

**Comment by xburning** [comment]
@sczyh30 PR is submit
