### ISSUE TITLE
How many apps can be displayed in the sidebar of the Sentinel dashboard?

### ISSUE THREAD

**Issue by 188** [alibaba/Sentinel#507]
请问左侧菜单最多支持显多少应用，如果应用很多，例如几百个或是上千个，每个应用下面有十台服务器的话是可以正常显示？
上面的想法是出于想对内部应用全局管理，以及增加权权等扩展，谢谢！

**Comment by sczyh30** [comment]
Hi, 左侧侧边栏理论上是没有展示限制的，并且可以利用搜索框来进行过滤。如果希望有一个全局的展示的话，可以改造一下主页以卡片的形式展示所有应用的基本信息。

---

Hi, there aren't limitations in the sidebar so all apps are expected to be listed in the sidebar. And you could refactor the index page as the overview page.
