### ISSUE TITLE
[BUG]Sentinel控制台新增系统规则提示失败

### ISSUE THREAD

**Issue by guonanjun** [alibaba/Sentinel#51]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
Sentinel控制台新增系统规则提示失败
![default](https://user-images.githubusercontent.com/29148151/43844423-44e3481c-9b5c-11e8-900a-17467ce8adf4.png)

### Describe what you expected to happen
期望在没有系统规则时，可以新增系统规则成功。

### Tell us your environment
任何环境

**Comment by sczyh30** [comment]
Thanks for reporting! We'll fix this .
