### ISSUE TITLE
Console real-time monitoring response time problem

### ISSUE THREAD

**Issue by jackchow621** [alibaba/Sentinel#512]
## Issue Description
我们的测试人员在做性能测试过程中发现，在调用dubbo接口方法的时候，得到的响应时间为下图：
![image](https://user-images.githubusercontent.com/30717485/53228517-63586600-36bc-11e9-9630-c8c41be5c7fa.png)
但是实际上控制台实时监控显示的响应时间却是下图这个结果：
![image](https://user-images.githubusercontent.com/30717485/53228549-7ec37100-36bc-11e9-9e2c-dac5e7333624.png)
### Describe what happened (or what feature you want)
我的疑问是为什么这两个响应时间会相差那么大，是不是这两个响应时间实际上是不同概念的时间，性能测试涉及的时间是包含网络，io等各因素得到的结果，而sentinel的这个响应时间只是方法从调用到获取结果的时间？？

### Describe what you expected to happen
如果真如我的猜测，那现在sentinel的这个响应时间是不是参考意义并不大？？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Sentinel 里面响应时间统计的是：从某个资源调用开始到结束的这段时间，即 `SphU.entry()` 到 `entry.exit()` 的这段时间，且被 block 的请求不计入。 平均 RT 为 每秒钟所有请求的 RT 之和 / 这一秒成功通过的请求数。

上面 Sentinel 控制台显示的 RT 是 provider 端还是 consumer 端？压测的图线显示的是哪一端？

---

The response time (RT) in Sentinel is the time duration between `SphU.entry()` and `entry.exit()` (during the invocation). The blocked request won't be counted for success count and RT.

**Comment by jackchow621** [comment]
sentinel控制台显示的是provider端，压测图形显示的也是provider端，我们这边压测是针对dubbo的provider端的接口进行压测，所以得到上面的图形

**Comment by jackchow621** [comment]
> Sentinel 里面响应时间统计的是：从某个资源调用开始到结束的这段时间，即 `SphU.entry()` 到 `entry.exit()` 的这段时间，且被 block 的请求不计入。 平均 RT 为 每秒钟所有请求的 RT 之和 / 这一秒成功通过的请求数。
> 
> 上面 Sentinel 控制台显示的 RT 是 provider 端还是 consumer 端？压测的图线显示的是哪一端？
> 
> The response time (RT) in Sentinel is the time duration between `SphU.entry()` and `entry.exit()` (during the invocation). The blocked request won't be counted for success count and RT.

sentinel控制台显示的是provider端，压测图形显示的也是provider端，我们这边压测是针对dubbo的provider端的接口进行压测，所以得到上面的图形
