### ISSUE TITLE
Test class loss in source code of sentinel-grpc-adapter

### ISSUE THREAD

**Issue by 188** [alibaba/Sentinel#514]
import com.alibaba.csp.sentinel.adapter.grpc.gen.FooRequest;
import com.alibaba.csp.sentinel.adapter.grpc.gen.FooResponse;
import com.alibaba.csp.sentinel.adapter.grpc.gen.FooServiceGrpc;
源源中找不到这三个，我看GIthub上也没有，请核实，谢谢

Test class loss in source code of sentinel-grpc-adapter

**Comment by sczyh30** [comment]
Hi, these stub classes are generated by `protoc-gen-grpc-java` plugin during the "test-compile" goal, so you can execute `mvn clean test` to generate the classes (located in `target/generated-test-sources/protobuf`, can be automatically identified by IDEA).

---

这些测试类是通过 `protoc-gen-grpc-java` 插件自动生成的，可以在此模块执行 `mvn clean test` 来生成，IDE 可以自动进行识别。

**Comment by ShZhengqin** [comment]
I run "mvn clean test", but get the error:  The method addService(ServerServiceDefinition) in the type ServerBuilder<capture#1-of ?> is not 
 applicable for the arguments (FooServiceImpl)

**Comment by ShZhengqin** [comment]
I run "mvn clean test",  success, but i get new error :  The method addService(ServerServiceDefinition) in the type ServerBuilder<capture#1-of ?> is not 
 applicable for the arguments (FooServiceImpl),  in the class "GrpcTestServer.java"
