### ISSUE TITLE
Support authentication/authorization in Sentinel dashboard

### ISSUE THREAD

**Issue by z2468091508** [alibaba/Sentinel#517]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, in next version we'll add interfaces for authentication/authorization in Sentinel dashboard and you can customize for your requirement. Feel free to give suggestions in this PR: #503 

Duplicate with #143.

**Comment by sczyh30** [comment]
This will be supported in 1.6.0 with a simple login page (thanks to @cdfive ). See #659 for details.
