### ISSUE TITLE
Does Sentinel support configuring startup parameters in application.yml?

### ISSUE THREAD

**Issue by wangchaoyu1992** [alibaba/Sentinel#518]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
这些可以初始化在application.yml中吗
-Dcsp.sentinel.dashboard.server=127.0.0.1:8088
-Dcsp.sentinel.log.dir=D:\Sentinel\log
-Dcsp.sentinel.api.port=8721
-Dproject.name=test
-Dcsp.sentinel.log.use.pid=true

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, it can be supported using [Spring Cloud Alibaba Sentinel](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Sentinel). You can refer to the document for details.
