### ISSUE TITLE
Port startup failed

### ISSUE THREAD

**Issue by wangchaoyu1992** [alibaba/Sentinel#520]
## Issue Description
linux系统
如下命令 启动之后 控制台首页没有testname,查看8722端口没有启动
nohup java -Dcsp.sentinel.api.port=8722 -Dcsp.sentinel.dashboard.server=ip:port -Dcsp.sentinel.log.dir=/data/logs/csp -Dcsp.sentinel.log.use.pid=true -Dproject.name=testname  -jar xxxxx.jar
且日志中有
INFO: log base dir is: /data/logs/csp/
INFO: log name use pid is: true
[控制台](https://github.com/wangchaoyu1992/First/blob/master/2223.png)
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wangchaoyu1992** [comment]
8722端口没有被占用

**Comment by sczyh30** [comment]
Hi, you can refer to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5) to check your configuration.

---

可以参考 [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5) 进行排查。请确保引入了 transport 相关依赖（如 `sentinel-transport-simple-http`）并确保应用有访问量。也可以根据日志进行排查：`${user.home}/logs/csp/sentinel-record.log.xxx`
