### ISSUE TITLE
Dashboard try to access Alipay domain 

### ISSUE THREAD

**Issue by MickMo** [alibaba/Sentinel#522]
when I try to modify Sentinel-Dashboard,I notice that it send a request to ```https://kcart.alipay.com/web/bi.do?BIProfile=merge&d=%5B%7B%22pg%22%3A%22http%3A%2F%2Flocalhost%3A8080%2F%23%2Fdashboard%2Fhome%22%2C%22r%22%3A1551171313469%2C%22g2%22%3Atrue%2C%22version%22%3A%223.3.2%22%2C%22page_type%22%3A%22syslog%22%7D%5D ```
What is this?

![image](https://user-images.githubusercontent.com/12163802/53400050-032d3100-39e8-11e9-8a30-a566b0514cbf.png)

**Comment by sczyh30** [comment]
Hi, it's the [G2 library](https://antvis.github.io/g2/doc/index.html#%E4%BD%93%E9%AA%8C%E6%94%B9%E8%BF%9B%E8%AE%A1%E5%88%92%E8%AF%B4%E6%98%8E) that sends the request. We've tried to disable this using `G2.track(false)` in `metrics.js` but it did not actually take effect. Would you like to contribute a PR to fix it?

**Comment by MickMo** [comment]
According to the newest announcement on
```https://github.com/antvis/g2/blob/master/README.zh-CN.md```.
By upgrade G2 Lib to version ```@antv/g2@3.4.7``` we can solve this problem

**Comment by MickMo** [comment]
Update by updating G2 lib to ```3.4.10```,problem solved.
![image](https://user-images.githubusercontent.com/12163802/53540379-3f7ba100-3b50-11e9-9781-60ed5d90d8b7.png)

I will make a PR later.

**Comment by sczyh30** [comment]
> Update by updating G2 lib to `3.4.10`,problem solved.
> ![image](https://user-images.githubusercontent.com/12163802/53540379-3f7ba100-3b50-11e9-9781-60ed5d90d8b7.png)
> 
> I will make a PR later.

👍
