### ISSUE TITLE
could I use origin field to limit rate by invocation Ip or appid

### ISSUE THREAD

**Issue by vio-lin** [alibaba/Sentinel#524]
I want to limit rate by two rule like this in dubbo
1. when clint ip = ip1 do flow rule A
2. when client appid = appid1 do flow ruleB

but when i set origin there can only set one "origin "
one request should only from ip1 or appid1.
And there is some describtion above method in ContextUtil.class
Context enter(String name, String origin) 
when origin is too many, memory efficiency should be carefully considered. 
so how  can I support this situation.

我想要在Dubbo中定义如下两条不相关的规则,
1. 当IP为 IPA的时候执行限流规则1
2. 当Application为App1时执行限流规则2
但是一个请求再进行处理的时候 contextUtil.entry(resource,origin) 只能设置一个来源,无法做到过滤.
并且origin 参数太多(ip的量会比较多)会影响性能.
针对这样的场景 怎么做会好一点

**Comment by sczyh30** [comment]
Hi, it's not encouraged to have too many resources and origins as the memory footprint would be large. For your scenario, you can leverage parameter flow control. You can define a resource with two parameters: `ip` and `app`, then configure parameter flow rules.

---

不建议 origin 和 resource 数目太多，否则内存占用会比较大。这种情况可以采用热点参数限流，将 ip 和 app 作为自定义资源的参数传递，然后在热点规则中配置例外项即可。
