### ISSUE TITLE
About dynamic rules and current limit processing

### ISSUE THREAD

**Issue by zgqyfj** [alibaba/Sentinel#526]
关于sentinel的使用有两个问题:
1 在限流之后,若请求超出规定的count,系统会抛出异常,如果我需要在成功限流之后加上自己的业务逻辑处理,是不是只能通过捕获异常来进行?
2 关于动态规则这一块,sentinel持久化规则到nacos配置中心,根据文档描述,dashboard,通过调用nacos提供的接口把规则注册到nacos.程序需要监听nacos的配置变化,调用ruleManager加载规则到内存.是否需要修改dashboard的代码,sentinel会提供相关功能么?

**Comment by sczyh30** [comment]
Hi, for 1 if you're using `SphU.entry(xxx)` API then you have to handle the `BlockException` by yourself. If you're using `@SentinelResource` annotation, you can configure the `blockHandler` and `fallback` in the annotation.

For 2, you have to refactor the dashboard to meet your requirement. Sentinel has provided a sample for pushing flow rules to Nacos via Sentinel dashboard. You can refer to the document:

- [Nacos publisher example](https://github.com/alibaba/Sentinel/wiki/Sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%88%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7%E7%AE%A1%E7%90%86%EF%BC%89#%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE)
- [Nacos dynamic data source](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%8E%A8%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8-nacos-%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99)

**Comment by zgqyfj** [comment]
@sczyh30 嗯,了解了,谢谢
