### ISSUE TITLE
NodeSelectorSlot adds child nodes in the context

### ISSUE THREAD

**Issue by yyalc** [alibaba/Sentinel#531]
NodeSelectorSlot维护和context和node的关系，负责将node添加进context，
((DefaultNode)context.getLastNode()).addChild(node);
这行代码是不是放如node为空的判断之内合适点，并发的时候没必要走多遍，虽然addChild中作了去重的判断，感觉没必要多走几步

**Comment by yyalc** [comment]
还有就是，如果节点在context中存在，就不会继续添加，这样会不会显示出来的就不是一个真正的节点调用关系了，比如 A->B->A->C 就会变成 A->B,C

**Comment by sczyh30** [comment]
> 还有就是，如果节点在context中存在，就不会继续添加，这样会不会显示出来的就不是一个真正的节点调用关系了，比如 A->B->A->C 就会变成 A->B,C

Yes, the node will be kept only once per context so that we can refrain from large memory footprint (especially for recursive resources).

**Comment by sczyh30** [comment]
> NodeSelectorSlot维护和context和node的关系，负责将node添加进context，
> ((DefaultNode)context.getLastNode()).addChild(node);
> 这行代码是不是放如node为空的判断之内合适点，并发的时候没必要走多遍，虽然addChild中作了去重的判断，感觉没必要多走几步

Would you like to contribute a PR?

**Comment by cdfive** [comment]
@yyalc @sczyh30 hi，
> A->B->A->C 就会变成 A->B,C

这里能不能不去重呢？链路就显示为A->B->A->C

即使是保持去重，目前`DefaultNode`中定义的`childList`是`HashSet<Node>`，顺序不能保证，
本机测试也发现，读取顺序跟添加顺序不一致。
可否考虑改为LinkedHashSet？

如果能支持显示完整准确的链路，在簇点链路页面里就能看得更直观，方便用户分析和调整流控规则。

以Dubbo为例，要实现链路跟踪可考虑用brave+zipkin等开源框架，但其UI不一定易用。
如果Sentinel对完整链路跟踪有很好的支持，比如单个应用看链路，以及提供接口和UI支持查看多个服务的从入口开始的完整链路，再加上本身已有的各资源的QPS、RT等统计信息，对用户应该有很大的吸引力。

影响到内存消耗(比如递归调用)可否考虑用其它方式来限制，比如限制层数，并且可配置。

**Comment by yyalc** [comment]
Sentinel最核心的是已流控为主，链路追踪不是罪本质的功能，目标是轻量级，如果不去重的话在循环调用的情况可能会对系统影响比较大，毕竟DefaultNode也需要维护很多统计，不知道是不是这个原因，个人见解

**Comment by cdfive** [comment]
@yyalc 是，核心功能是流控，但目前已支持建立链路了，完整准确的链路有助于分析和调整规则；
循环调用毕竟是少数，可能有的微服务所有的接口都没有循环调用。

**Comment by yyalc** [comment]
@cdfive我赞同你的观点，但是那样做那个涉及是否是处于性能考虑需要问下官方 @sczyh30 帮忙解惑下
