### ISSUE TITLE
Start sentinel-dashboard error in JDK11

### ISSUE THREAD

**Issue by hanyanghy** [alibaba/Sentinel#537]
在JDK11下不能使用，Striped64该类下的sun.misc.Unsafe不存在。在jdk9中已经移除sun.misc.Unsafe包。

**Comment by sczyh30** [comment]
Hi, we maintain code of `Striped64` and `LongAdder` in `sentinel-core` because we need to support JDK 7 and these classes are introduced in 1.8. This might be resolved as soon as `sentinel-core` requires JDK 8 or above. Any suggestions about this?

**Comment by sczyh30** [comment]
Maybe this has been resolved via #1996
