### ISSUE TITLE
Code comment and document refinement

### ISSUE THREAD

**Issue by chunericli** [alibaba/Sentinel#54]
## Issue Description
注释编写语言集中，中英文混合看的别扭，sentinel-core中的eagleeye没任何注释，理解费劲
Type: *bug report* or *feature request*
feature request
### Describe what happened (or what feature you want)
每个类加点注释说明

### Describe what you expected to happen
每个单独的java类注释规范统一下，最好是全英文或者全中文，很多带有感叹号的能处理下最好了，看着别扭

### How to reproduce it (as minimally and precisely as possible)

1. WarmUpController的coolDownTokens方法
2. ***Exception都存在感叹号
3. eagleeye中实现都没注释

### Tell us your environment
JDK8+Windows

### Anything else we need to know?
1.文档和Roadmap中的描述如果能更详细点，更有利于帮助参与建设

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. We'll refine the code comments continuously.

For roadmap, this is only a blueprint. Some of the details should be well discussed. You are welcomed to provide thoughts and advice to make our community better :)
