### ISSUE TITLE
LeapArrayTest.testGetValidHead fails randomly

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#541]
## Issue Description

LeapArrayTest.testGetValidHead fails randomly

### Describe what you expected to happen

A case should get the same result always.

### How to reproduce it (as minimally and precisely as possible)

Try to run it repeatedly.

**Comment by sczyh30** [comment]
Hi, this kind of time-sleep based tests are not accurate enough and may sometimes fail. Maybe we can optimize the original data structure to support passing arbitrary time so we don't have to control the time by sleeping.

**Comment by jasonjoo2010** [comment]
Yeah, just what i think about. Maybe we should add a method enabling change current time manually to TimeUtil or others
