### ISSUE TITLE
[question] cluster qps config not work

### ISSUE THREAD

**Issue by beck5293** [alibaba/Sentinel#551]
## Issue Description

Type: *question,cluster*

### Describe what happened (or what feature you want)
cluster qps config not work

### How to reproduce it (as minimally and precisely as possible)

1.  double app node, one is  EmbeddedClusterTokenServer
2.  FlowRuleManager.register2Property  and  ClusterFlowRuleManager.setPropertySupplier  use different FileRefreshableDataSource
3.  FlowRuleManager.register2Property
[{
	"clusterConfig": {
		"fallbackToLocalWhenFail": true,
		"sampleCount": 10,
		"strategy": 0,
		"thresholdType": 0,
		"windowIntervalMs": 1000
	},
	"clusterMode": false,
	"controlBehavior": 0,
	"count": 20.0,
	"grade": 1,
	"limitApp": "default",
	"maxQueueingTimeMs": 500,
	"resource": "demo",
	"strategy": 0,
	"warmUpPeriodSec": 10
}, {
	"clusterConfig": {
		"fallbackToLocalWhenFail": true,
		"flowId": 86,
		"sampleCount": 10,
		"strategy": 0,
		"thresholdType": 1,
		"windowIntervalMs": 1000
	},
	"clusterMode": true,
	"controlBehavior": 0,
	"count": 30.0,
	"grade": 1,
	"limitApp": "default",
	"maxQueueingTimeMs": 500,
	"resource": "demo",
	"strategy": 0,
	"warmUpPeriodSec": 10
}]

4. ClusterFlowRuleManager.setPropertySupplier
[{
	"clusterConfig": {
		"fallbackToLocalWhenFail": true,
		"flowId": 50,
		"sampleCount": 10,
		"strategy": 0,
		"thresholdType": 1,
		"windowIntervalMs": 1000
	},
	"clusterMode": true,
	"controlBehavior": 0,
	"count": 30.0,
	"grade": 1,
	"limitApp": "default",
	"maxQueueingTimeMs": 500,
	"resource": "demo",
	"strategy": 0,
	"warmUpPeriodSec": 10
}]
5. bind client to tokenServer  on dashboard

6. send all http request to the application node which is not EmbeddedClusterTokenServer

single node qps = 20 , cluster qps = 30 , two application node, dashboard show real qps = 40 
![xitzv8 py mf ujgq mky](https://user-images.githubusercontent.com/28086904/53903833-aa146b80-407f-11e9-816b-77b24ae14be7.png)
![k2x 7 _34i 4 s8mk1ghe](https://user-images.githubusercontent.com/28086904/53903837-ac76c580-407f-11e9-82cd-81614289367a.png)
![aef49r j dvpoq s mm](https://user-images.githubusercontent.com/28086904/53903839-ada7f280-407f-11e9-9c4c-a446f106ddc6.png)

### Tell us your environment
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
        <relativePath/> 
    </parent>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <sentinel.version>1.4.2</sentinel.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>${sentinel.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>${sentinel.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-cluster-client-default</artifactId>
            <version>${sentinel.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-cluster-server-default</artifactId>
            <version>${sentinel.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
    </dependencies>

dashboard 1.4.2
### Anything else we need to know?

when tokenServer config maxAllowQps < cluster config qps , token acq will pass or reject

**Comment by sczyh30** [comment]
Hi, please refer to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E9%9B%86%E7%BE%A4%E9%99%90%E6%B5%81%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88) to check whether the cluster config and rules have been configured correctly. If you are running multiple instances of **the same** `appName` in local, you need to add an additional parameter: `-Dcsp.sentinel.log.use.pid=true` when startup, or the monitoring page in the dashboard would be incorrect.

**Comment by beck5293** [comment]
`-Dcsp.sentinel.log.use.pid=true`  it's work, thanks
