### ISSUE TITLE
Dashboard distributed deployment problem

### ISSUE THREAD

**Issue by licheng-xd** [alibaba/Sentinel#554]
#241 #363 
这两个Issue中都没有给出dashboard具体的分布式部署方案，所以还是提出这个问题。
由于dashboard是通过上报的机器列表来主动fetch每个节点的流控数据的，因此如果部署多个dashboard节点，会导致多个节点重复的去fetch数据，数据合并和入库也会有冲突。
有没有具体的如何分布式部署dashboard的文档？或者有提供一种可行的思路。

**Comment by jasonjoo2010** [comment]
So is that necessary to support clustering in dashboard? @sczyh30 

I have a proposal that introducing DUBBO into dashboard and,

1. Reference NodeService in broadcasting when doing heartbeat
2. Fetching metrics from node should be distributed in dashboards(consistent hash maybe)
3. Using the same hashing algorithm when fetching data for rendering

When deployment changed, nodes list will be finally consistent while only one problem remained: Some metrics data will temporarily lose.

So it may not work so well if the deployment changed frequently.
