### ISSUE TITLE
HttpHeartbeatSender is not backwards compatible

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#558]
## Issue Description

In codes before commit#d3bbe290c2a89ba2b5c043c24f280daaac60d4c2 why you set `csp.sentinel.dashboard.server` to `http://a.com` that means `http://a.com`. But after that commit it means `http://a.com:8080`.

When your http server listens to `80` it's normally to drop port in address but when listening to non 80(http protocol) you should add it to address.

But now we must add the port specification to address when the port exactly is `80` but you don't need to do this when the port is 8080?

### Describe what you expected to happen

server=a.com means http://a.com
server=a.com:8080 means http://a.com:8080

**Comment by sczyh30** [comment]
It's not the expected behavior, maybe there's something wrong. Would you like to contribute a PR?
