### ISSUE TITLE
Separate rule action from rule definition

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#56]
## Issue Description

Type: *enhancement*

### Describe what feature you want

Separate rule action (`passCheck`) from rule definition (`Rule` entity).

- [x] FlowRule
- [x] DegradeRule (a temporary solution is to abstract a `CircuitBreaker`)
- [x] AuthorityRule
- [x] ParamFlowRule

**Comment by sczyh30** [comment]
Finally resolved in #1490 after two years... Cheers! 🍺

**Comment by jasonjoo2010** [comment]
> Finally resolved in #1490 after two years... Cheers! 🍺

😂
