### ISSUE TITLE
InitExecutor.doInit method log optimization

### ISSUE THREAD

**Issue by zhousiliang163** [alibaba/Sentinel#563]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
在初始化数据源时，会考虑使用异步的实现方式，所以如下代码，是否可以去掉？
 ```
RecordLog.info(String.format("[InitExecutor] Initialized: %s with order %d",
                    w.func.getClass().getCanonicalName(), w.order));
```
否则使用异步的方式，这个提示会让人产生错觉。
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. The log will be changed to:

```
[InitExecutor] Executing <class-name> with order <order-value>
```
