### ISSUE TITLE
When using the fallback function, the following exception occurs？

### ISSUE THREAD

**Issue by Mr-ZhangJ** [alibaba/Sentinel#565]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
限流规则和回调函数都设定到了自己的服务端，当有其它服务调用我服务接口且达到了限流规则设定的阀值，返回给调用方的信息是这样的：Caused by: com.alibaba.dubbo.remoting.RemotingException: com.alibaba.com.caucho.hessian.io.HessianProtocolException: expected map/object at java.lang.String ({"code":"120023","message":"QPS exceeded the threshold set by Sentinel"})

回调函数定制信息如下：
DubboFallbackRegistry.setProviderFallback(new DubboFallbackImpl4Producer());

public class DubboFallbackImpl4Producer implements DubboFallback {
    @Override
    public Result handle(Invoker<?> invoker, Invocation invocation, BlockException ex) {
        StringBuffer sb = new StringBuffer();
        sb.append(invoker.getInterface().toString());
        Map<String, String> map = new HashMap<>(2);
        map.put("code", "120023");
        map.put("message", "QPS exceeded the threshold set by Sentinel : " + sb);
        return new RpcResult(new JSONObject(map).toString());
    }
}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
The `HessianProtocolException` seems that something wrong in deserialization in a Dubbo RPC call.
Check if the dubbo and fastjson version are same in both provider and consumer side.

```
Map<String, String> map = new HashMap<>(2);
...
new JSONObject(map)
```

What the package is of `JSONObject ` in your project?
The constructor of `JSONObect` in fastjson is:
`JSONObject(Map<String, Object> map)`, not `JSONObject(Map<String, String>)`.

**Comment by Mr-ZhangJ** [comment]
1、JSONObect  package is fastjson-1.2.51.jar  
2、dubbo is dubbo-2.5.3.jar and fastjson  is fastjson-1.2.51.jar in provider and consumer versions are the same，but in sentinel-dubbo-adapter pack dubbo version is 2.5.8，Is that ok？

**Comment by sczyh30** [comment]
Dubbo 2.5.3 might have been deprecated. Maybe you can try to update Dubbo version. But from your error message, it seems to be related to the codec.

**Comment by cdfive** [comment]
I tried with dubbo-2.5.3 and fastjson-1.2.51 with same code, It's OK.

Use `mvn dependency:tree` can print the dependency info, since the dependency version may be overrided.

Could you please provide a small demo project to reproduce the Exception?

**Comment by cdfive** [comment]
Yes, Dubbo 2.5.3 is a old version, some annotations are not supported.
You can aslo try the custom fallback method in sentinel-demo-dubbo module
I tried in the module with dubbo 2.6.5 and 2.6.0, both are OK.
Info printed in console: 
`Success: {"message":"QPS exceeded the threshold set by Sentinel : interface com.alibaba.csp.sentinel.demo.dubbo.FooService","code":"120023"}`

**Comment by Mr-ZhangJ** [comment]
The problem has been solved. There is something wrong with my return result.Thank you
