### ISSUE TITLE
Are there any out-of-box Docker images and k8s yaml files of Sentinel?

### ISSUE THREAD

**Issue by planeo1105** [alibaba/Sentinel#566]
有没有docker镜像和k8s的yaml文件？

**Comment by sczyh30** [comment]
Hi, there are not out-of-box Docker images or Kubernetes solutions till now. You can refactor the dashboard for yourself to meet your demand, then build your own Docker images and Kubernetes deployment.

**Comment by anjia0532** [comment]
my repo https://hub.docker.com/r/anjia0532/sentinel-docker
