### ISSUE TITLE
add "resttemplate.sentinel.enabled=false" to config file, true as default

### ISSUE THREAD

**Issue by vipweihua** [alibaba/Sentinel#570]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, could you please illustrate the details of your question according to the issue template?

**Comment by fangjian0423** [comment]
@sczyh30 This is a switch property for the usage of `@SentinelRestTemplate`.

**Comment by vipweihua** [comment]
sorry for disturbance, it should be an enhancement for spring-cloud-alibaba-sentinel.
