### ISSUE TITLE
@SentinelResource throws FlowException,but blockHandler can just catch BlockException

### ISSUE THREAD

**Issue by dqing0** [alibaba/Sentinel#575]
## Issue Description
when i want to control qps, use the @SentinelResource,found blockHandler does not 
work,it just throws flowException,but not into blockHandler method.But ,
BlockException.isBlockException(e.getCause()) is useful.

**Comment by sczyh30** [comment]
Hi, could you please check the `${home}/logs/csp/sentinel-record.log` to find whether there are error logs? And please ensure your `blockHandler` function matches the restriction described in [the document](https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-annotation-aspectj/README.md#annotation).

**Comment by dqing0** [comment]
i check the sentinel-record.log , but no errors.this is my code:

    @SentinelResource(value = SentinelConstants.SENTINEL_ENTRANCE_RESOURCE, blockHandler = "exceptionHandler")
    @Override
    public void test() {
        try {
            System.out.println("-----------");
            Thread.sleep(3);
        } catch (InterruptedException e) {

        }
    }

public String exceptionHandler(long s, BlockException ex) {
        System.err.println(s + "++++");
        return "Oops, error occurred at " + s;
    }

the method is in same class

**Comment by sczyh30** [comment]
Your `exceptionHandler` does not match the restriction of the `blockHandler` function (see  [the document](https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-annotation-aspectj/README.md#annotation)). The signature should be: `public void exceptionHandler(BlockException ex)`. The parameter list (except the last additional `BlockException` parameter and return type of the `blockHandler` method should match the original method.

**Comment by dqing0** [comment]
holy shit,this is my fault! thanks very much! By the way,speaking english is tiring

**Comment by sczyh30** [comment]
> holy shit,this is my fault! thanks very much! By the way,speaking english is tiring

It's recommended to use English here, but you could choose to reply with Chinese or use Google Translate if you had difficulty :)

**Comment by dqing0** [comment]
ojbk
