### ISSUE TITLE
Dynamic DataSource Config problem

### ISSUE THREAD

**Issue by MickMo** [alibaba/Sentinel#577]
I try to config a Data Source according to this document 
```https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95```

in the section the following picture show,I get confused.

![image](https://user-images.githubusercontent.com/12163802/54415238-a4312100-4736-11e9-910d-2c0571d1fc48.png)

shouldn't it be ```spring.factories``` File under ```META-INF/services``` with key 
```com.alibaba.csp.sentinel.init.InitFunc```?

**Comment by sczyh30** [comment]
This is not related to Spring, but SPI provider-configuration file. For the SPI interface `com.alibaba.csp.sentinel.init.InitFunc`, the file name is `com.alibaba.csp.sentinel.init.InitFunc` which is located in `resource/META-INF/services` directory. The content of the file will contain concrete class name of implementations. See the javadoc for more information: https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html
