### ISSUE TITLE
Configure startup parameters of Sentinel using dynamic config center

### ISSUE THREAD

**Issue by MickMo** [alibaba/Sentinel#578]
I would like to config sentinel DashBoard's IP,port etc. using ```eureka```/```ZK```/```consul``` instead of writing configuration in ```properties``` or ```yml``` file.How can I do it?
Thanks.

**Comment by sczyh30** [comment]
Hi, you may have to implement the logic of retrieving the configuration from config center and then set the properties via `SentinelConfig.setConfig(key, value)`. Note that you have to set the properties before the initialization of Sentinel was triggered (during the first resource entry or call `InitExecutor.doInit()` manually).

---

这种情况需要开发者自行实现读取的逻辑，并且通过 `SentinelConfig.setConfig(key, value)` API 手动 set 到 Sentinel 中，注意配置必须在 Sentinel 初始化之前完成（初次调用资源或手动初始化之前），否则不会生效。

**Comment by MickMo** [comment]
I make a mistake ,problem solved thx
