### ISSUE TITLE
黑白名单 AuthorityRule 的场景考虑

### ISSUE THREAD

**Issue by haiyang1985** [alibaba/Sentinel#58]
对于黑白名单，是否考虑支持下面的几种场景，或许是否有必要考虑未来支持呢？
对于场景1~2可能比较简单，就是如何设置同级的App、IP黑名单/白名单
对于场景3也比较简单，就是不同级的黑名单如何设置。
对于场景4，主要是为了让用户简单，不知道是否可以支持，或者有必要支持。
对于场景5，主要就是一个配置可能要表达两种不同的意义，要么生效的是操作（覆盖服务级），要么就是生效操作+服务级，这个可能不太好弄。

场景1：
假如，服务有100个method，这100个method不允许App1和IP1访问。
场景2：
假如，服务有100个method，这100个method只允许App1和IP1访问。
场景3：
假如，服务有100个method，前99个method不允许App1访问，第100个不允许IP1访问。

场景4 ：
假如，服务有100个method，其中99个method只有App1和App2不能访问，第100个method只能被IP1（不属于App1和App2）访问。出于用户简单考虑，可能需要设置服务级的黑名单，操作级给第100个method设置白名单，是否需要考虑支持这种情况呢。
场景5：
假如，服务有100个method，其中99个method只有App1和App2才能访问，第100个method只有IP1才能访问。出于对用户简单的考虑，可能需要设置服务级的白名单，操作级给第100个method也是设置白名单？如果是的话，IP1属于App1的话，就应该是第100个method只有IP1才能访问。如果IP1属于App3的话，可能用户又是希望允许App1和App2和IP1访问？

**Comment by sczyh30** [comment]
场景 4 可以通过给 `AuthorityRule` 添加例外条件来支持；
场景 5 里面的情况，我们的限制的来源（`limitApp`）并不关心是应用名还是 IP，统一当做不同的来源名称。如果需要 appName 和 IP 之间进行映射应该是需要自己去实现的。
