### ISSUE TITLE
Fallback and flow control failures how to customize the global method strategy

### ISSUE THREAD

**Issue by maojx0630** [alibaba/Sentinel#584]
fallback和流控失败如何自定义全局的方法策略

**Comment by sczyh30** [comment]
Hi, for annotation support you can define `blockHandler` in `@SentinelResource` annotation. See the document: https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-annotation-aspectj/README.md

For Dubbo support you can register global fallback. For Servlet filter or Spring WebFlux adapter you can register your own block handler function.

---

- 注解方式 `blockHandler`：https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81
- Web Servlet Filter 可通过注册 `UrlBlockHandler` 的方式：https://github.com/alibaba/Sentinel/wiki/%E4%B8%BB%E6%B5%81%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%82%E9%85%8D#web-servlet
- Dubbo Adapter 可通过注册全局 fallback 函数的方式：https://github.com/alibaba/Sentinel/wiki/%E4%B8%BB%E6%B5%81%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%82%E9%85%8D#dubbo
