### ISSUE TITLE
QPS does not play a flow control that does not exceed multiple requests per second?

### ISSUE THREAD

**Issue by hzdavid** [alibaba/Sentinel#585]
直接上代码：

设置qps 20， 按大家的理解，一秒钟，不能超过20个请求。
`
public class HelloSentinel {

	private static void initFlowRules() {
		List<FlowRule> rules = new ArrayList<>();
		FlowRule rule = new FlowRule();
		rule.setResource("HelloWorld");
		rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
		// Set limit QPS to 20.
		rule.setCount(20);
		rules.add(rule);
		FlowRuleManager.loadRules(rules);
	}

	static {
		// 配置规则.
		initFlowRules();
	}

	public static String hello(String[] args) {
		Entry entry = null;
		try {
			entry = SphU.entry("HelloWorld");
			// 资源中的逻辑.
			return "hello world";
		} catch (BlockException e1) {
			return "blocked";
		} finally {
			if (entry != null) {
				entry.exit();
			}
		}

	}
}`

下面上测试程序
 

`
     public class HelloSentinelTest {
	@Test
	public void testHello() {
		// 假设30个线程同时调用HelloSentinel的hello方法
		int threadnum = 30;
		// 打印helloWorld次数
		final AtomicInteger helloWorldCount = new AtomicInteger(0);
		// 打印blocked次数
		final AtomicInteger blockedCount = new AtomicInteger(0);
		CountDownLatch latch = new CountDownLatch(threadnum);
		Runnable r = new Runnable() {
			public void run() {
				String result = HelloSentinel.hello(null);
				if ("hello world".equals(result)) {
					helloWorldCount.incrementAndGet();
				}
				if ("blocked".equals(result)) {
					blockedCount.incrementAndGet();
				}
				latch.countDown();
			}
		};

		for (int i = 0; i < threadnum; i++) {
			(new Thread(r)).start();
		}
		try {
			latch.await();
		} catch (InterruptedException e) { 
			e.printStackTrace();
		}
		// 断言
		Assert.isTrue(helloWorldCount.get() == 20, "helloWorldCount=" + helloWorldCount.get());
		Assert.isTrue(blockedCount.get() == 10, "blockedCount=" + blockedCount.get());

	}
   }

`

测试并没有按期望的通过， 期望：helloWorld打印了20次。blocked 打印了10次。

经多次测试， helloWorld打印了30次，这不是与大家理解的（设置qps 20， 一秒钟，不能超过20个请求。
）不一致吗？

![image](https://user-images.githubusercontent.com/4660219/54518679-dc876800-499f-11e9-99b1-0d971247f8c6.png)

**Comment by cdfive** [comment]
Maybe it's due to the lazy-loading resource.
I found 3 ways to get the expect result.

1. Change the code in for loop, don't use thread, just call the method
```java
for (int i = 0; i < threadnum; i++) {
   r.run();     
}
```

2. Change the code in for loop, join the thread
```java
for (int i = 0; i < threadnum; i++) {
    Thread thread = new Thread(r);
    thread.start();
    try {
	thread.join();
    } catch (InterruptedException e) {
	e.printStackTrace();
    }
}
```

3. Remain muti thread call, and add SphU.entry("HelloWorld")  at the beginning of the testHello method
```java
Entry entry = null;
try {
    entry = SphU.entry("HelloWorld");
} catch (BlockException e) {
    e.printStackTrace();
} finally {
    if (entry != null) {
	entry.exit();
    }
}
```

In these ways,  and add the print code to console:
```java
System.out.println("helloWorldCount=" + helloWorldCount.get());
System.out.println("blockedCount=" + blockedCount.get());
```

The result will be OK，maybe a little deviation if running the test many times.
> helloWorldCount=20
   blockedCount=10

**Comment by hzdavid** [comment]
我的意思是， QPS=20，并不是与大家理解的那样：设置qps=20， 一秒钟，不能超过20个请求。

**Comment by hzdavid** [comment]
![image](https://user-images.githubusercontent.com/4660219/54580718-638e1c00-4a44-11e9-9aff-bd9f8acab8a1.png)

**Comment by cdfive** [comment]
sentinel-demo-basic module provider demo for simulate QPS flow control.
@see
[https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/flow/FlowQpsDemo.java](https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/flow/FlowQpsDemo.java)

**Comment by hzdavid** [comment]
在我的例子中，是30个线程去访问 待保护的资源， 并没有达到控制qps=20以内的效果。

**Comment by hzdavid** [comment]
> sentinel-demo-basic module provide demo for simulate QPS flow control.
> @see
> https://github.com/alibaba/Sentinel/blob/master/sentinel-demo/sentinel-demo-basic/src/main/java/com/alibaba/csp/sentinel/demo/flow/FlowQpsDemo.java

你的例子没有问题，你是一个线程里循环去访问 待保护的资源，确实达到了 qps=20以内的效果，可是为啥我的例子不行。

**Comment by cdfive** [comment]
`FlowQpsDemo`里面是多个线程啊，`simulateTraffic`方法：
```java
private static void simulateTraffic() {
  for (int i = 0; i < threadCount; i++) {
    Thread t = new Thread(new RunTask());
    t.setName("simulate-traffic-Task");
    t.start();
  }
}
```
你的例子参考2楼的回复，可以试一下。

**Comment by hzdavid** [comment]
> `FlowQpsDemo`里面是多个线程啊，`simulateTraffic`方法：
> 
> ```java
> private static void simulateTraffic() {
>   for (int i = 0; i < threadCount; i++) {
>     Thread t = new Thread(new RunTask());
>     t.setName("simulate-traffic-Task");
>     t.start();
>   }
> }
> ```
> 
> 你的例子参考2楼的回复，可以试一下其中第3种方式。

你给的例子没有问题，你是一个线程里循环去访问 待保护的资源，确实达到了 qps=20以内的效果，可是为啥我的例子不行。

**Comment by cdfive** [comment]
```java
Entry entry = null;
try {
    entry = SphU.entry("HelloWorld");
} catch (BlockException e) {
    e.printStackTrace();
} finally {
    if (entry != null) {
	entry.exit();
    }
}
```
把这段代码加到你的例子前面试试。

还有`FlowQpsDemo`这个例子你可能没看仔细，里面new了多个Thread，不是一个线程循环。
