### ISSUE TITLE
LeapArray.currentWindow is less elegant than returning a new WindowWrap when the time is less than the time window obtained.

### ISSUE THREAD

**Issue by shxz130** [alibaba/Sentinel#586]
<!-- Here is for bug reports and feature requests ONLY! 
public WindowWrap<T> currentWindow(long timeMillis) {
 } else if (windowStart < old.windowStart()) {
                // Should not go through here, as the provided time is already behind.
                return new WindowWrap<T>(windowLengthInMs, windowStart, newEmptyBucket());
            }
}

**Comment by sczyh30** [comment]
Hi, we cannot just throw exceptions here as this would affect the running thread. And `windowStart < old.windowStart()` does not indicate error, but sometimes slow or specific scenarios. In these circumstances, the bucket should not be used so we just return an empty bucket.

PS: in 1.5.0 the `FutureBucketLeapArray` might go through this branch as it only calculates for the future.

**Comment by shxz130** [comment]
ok thanks
