### ISSUE TITLE
ZookeeperDataSource might not be initialized well unless the ZooKeeper server is active

### ISSUE THREAD

**Issue by zhousiliang163** [alibaba/Sentinel#588]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在初始化ZookeeperDataSource数据源时，如果zk server不能用或者因网络原因导致client与zk server连接超时等，会造成对znode节点数据的监听失败，如下图：
![图片](https://user-images.githubusercontent.com/7529190/54589659-3308ab00-4a61-11e9-82a2-4eba0614ba2c.png)
红色标注的地方，可能会执行报错，导致后面的监听器注册失败。

### Describe what you expected to happen
是否可以加个连接事件，等连接成功后，再去执行后面的NodeCacheListener注册

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. It's reasonable to deal with circumstances on connection error. Would you like to contribute a PR to improve this?

**Comment by zhousiliang163** [comment]
OK

发自我的 iPhone
