### ISSUE TITLE
When do you support Apache Dubbo 2.7.x?

### ISSUE THREAD

**Issue by mostcool** [alibaba/Sentinel#594]
When do you support Apache Dubbo?

**Comment by sczyh30** [comment]
Hi, Dubbo integration has already been supported. You can refer to the document:

- https://github.com/alibaba/Sentinel/wiki/Adapters-to-Popular-Framework#dubbo

**Comment by mostcool** [comment]
@sczyh30 我看到这个adapter是基于alibaba dubbo 2.5.8来实现的，但我现在想用apache dubbo 2.7.0，这个adapter应该不兼容。

**Comment by sczyh30** [comment]
> @sczyh30 我看到这个adapter是基于alibaba dubbo 2.5.8来实现的，但我现在想用apache dubbo 2.7.0，这个adapter应该不兼容。

Yes, we might need to release another compatible adapter module for Dubbo 2.7.x. We can discuss it in #496.

**Comment by sczyh30** [comment]
Closing this as it's duplicated with #496.

**Comment by sczyh30** [comment]
This will be supported in 1.5.1 (which will be released soon). See https://github.com/alibaba/Sentinel/issues/496#issuecomment-476989689
