### ISSUE TITLE
Is there any plan to suport  AuthoritySlot filter request by multi parameter

### ISSUE THREAD

**Issue by vio-lin** [alibaba/Sentinel#595]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
I want to filter requet both by Application Name and IP.But the AuthoritySlot can only 
filter request by origin.

### Describe what you expected to happen
I can submit parameters and create some AuthorityRule like ParamFlowRule to filter request by different 
parameters。

**Comment by sczyh30** [comment]
Hi, the origin statistic nodes won't be evicted once created, so too many origins might lead to large memory footprint. For `appName` and `ip` you can leverage parameter flow control. You can pass `appName` and `ip` as two parameters via `SphU.entry(res, entryType, 1, args)`, then add parameter flow control including exception items for these two parameters.

We might add mechanisms for evicting inactive origins in the future, then we can support passing multiple origins.

**Comment by shxz130** [comment]
we can use SphU.entry the last params Object... args，then define the self Slot，such as the demoSlot，and DemoSlotChainBuilder，the demoSlot where get args，do you what you want。

  public static Entry entry(Method method, EntryType type, int count, Object... args) throws BlockException {
        return Env.sph.entry(method, type, count, args);
    }
or
    public static Entry entry(String name, EntryType type, int count, Object... args) throws BlockException {
        return Env.sph.entry(name, type, count, args);
    }
