### ISSUE TITLE
The console adds the rule route to the v1/flow/rule

### ISSUE THREAD

**Issue by fanchangjifen** [alibaba/Sentinel#596]
控制台添加规则路由走的v1/flow/rule，所以在适配datasource-nacos的时候，通过修改FlowControllerV2走nacosPublisher不生效。。
版本:sentinel-dashboard 1.4.2

**Comment by sczyh30** [comment]
Hi, the dashboard routes to the v1 controller (per machine) by default. You can refactor the frontend router to use the v2 controller (per application) or directly jump to `/v2/flow/xxx` to meet your requirement.

**Comment by fanchangjifen** [comment]
yes! it's not only modify FlowControllerV2 to your DataSource，but you need modify sentinel-dashboard\src\main\webapp\resources\app\scripts\directives\sidebar\sidebar.html at line 37 , modify it to ui-sref="dashboard.flow({app: entry.app})"
