### ISSUE TITLE
Spring cloud + nacos +sentinel has invalid data source configuration

### ISSUE THREAD

**Issue by ShZhengqin** [alibaba/Sentinel#599]
## Issue Description

Type: *bug report*
项目基于spring cloud, 引用了spring-cloud-starter-alibaba-sentinel-0.2.1.RELEASE版本
配置了nacos数据源

--  内容

    sentinel:
     transport:
        port: 8719
        dashboard: localhost:8080
      log:
        dir: /home/logs/service-demo
      datasource:
        ds0:
          nacos:
            server-addr: dev-chaser-nacos-01.blz.netease.com:80
            data-id: sentinel-service-demo
            group-id: sentinel_group

然后在nacos上配置了一个配置文件
![图片](https://user-images.githubusercontent.com/28048110/54732074-beeb1600-4bcc-11e9-8f69-5f1adf217aaf.png)

内容是
![图片](https://user-images.githubusercontent.com/28048110/54732135-15585480-4bcd-11e9-894a-d7785cc3ccc0.png)

### Describe what happened (or what feature you want)
调用接口多次刷新，限流没有起效，不知道是哪里配置不对，望解答

### Tell us your environment
spring cloud 版本 2.0.6
sentinel-datasource-nacos 版本 1.4.2

**Comment by sczyh30** [comment]
Hi, please check your `~/logs/csp/sentinel-record.log` to see whether there are any error messages.

**Comment by ShZhengqin** [comment]
谢谢你 @sczyh30 ,  发现和group_id的大小写有关系，全大写就可以生效了，不知道是为什么？

**Comment by fangjian0423** [comment]
@ShZhengqin

The dataId and groupId in nacos should exists in 0.2.1.RELEASE version when you startup application.  We add a new property `rule-type` to fix this problem in the next version of spring-cloud-starter-alibaba-sentinel.

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel-datasource/src/main/java/org/springframework/cloud/alibaba/sentinel/datasource/config/AbstractDataSourceProperties.java
