### ISSUE TITLE
qps heartbeat info was lost when using sentinel-transport-simple-http

### ISSUE THREAD

**Issue by dengweisysu** [alibaba/Sentinel#60]
## Issue Description

Type: bug report 

### Describe what happened (or what feature you want)
当使用sentinel-transport-simple-http 模块进行适配时。
我设置qps限流为20，当使用Apache ab持续压测的时候，我得到了如下的图形
![image](https://user-images.githubusercontent.com/18375623/44092682-c81e1684-a003-11e8-880a-ec887fb79383.png)
请求是持续的，看metrics.log是上报出线了中断
![image](https://user-images.githubusercontent.com/18375623/44092738-fdb89b34-a003-11e8-9ae6-7f86149d6676.png)
如图，20:51:04 到20:51:17之间没有metrics信息

### Describe what you expected to happen
按正常情况应该是连续的曲线

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
这期间一直有持续的流量么？只有有访问的时候才会记录 metrics 信息。

**Comment by sczyh30** [comment]
Friendly ping :)

**Comment by dengweisysu** [comment]
期间一直有流量，我减少线程降低负载后好一点，但是还是不是一条比较稳定的曲线


在 2018-08-15 11:41:49，"Eric Zhao" <notifications@github.com> 写道：


这期间一直有持续的流量么？只有有访问的时候才会记录 metrics 信息。

**Comment by sczyh30** [comment]
Closing this. Reopen the issue if it still happens.
