### ISSUE TITLE
RT fault tolerant when downgrading AOP When RT is adjusted, sleep is completely ineffective, but my debug card owner will have it. Need to ask if it is wrong.

### ISSUE THREAD

**Issue by liuhao940826** [alibaba/Sentinel#602]
/**
 * @Author: liuhao
 * @Description:
 * @Date: Create in 6:06 PM 2019/3/18
 */
@Service
public class FallBackService {

    /**
     * Exception Count
     * @param num
     * @return
     */
    @SentinelResource(value = "fallbackEC",entryType= EntryType.OUT, fallback = "FallbackEC")
    public String fallbackEC(long num){
        //self expection
        if(num%2==0){
            int i= 1/0;
        }

        return String.format("success! %d", num);
    }

    // 
    public String FallbackEC(long num) {
        return String.format("EC degrade:%d", num);
    }

    /**
     * Exception RATIO
     * @param num
     * @return
     */
    @SentinelResource(value = "fallbackER",entryType= EntryType.OUT, fallback = "FallbackER")
    public String fallbackER(long num){
        //self Exception
        if(num%2==0){
            int i= 1/0;
        }

        return String.format("success! :%d", num);
    }

    public String FallbackER(long num) {
        return String.format("ER degrade :%d", num);
    }

    /**
     * RT degrade
     * @return
     */
    @SentinelResource(value = "fallbackRT",entryType= EntryType.OUT, fallback = "FallbackRT")
    public String fallbackRT(){
        try {
            //sleep 200ms
            TimeUnit.MILLISECONDS.sleep(2000);
        } catch (Exception e) {

        }

        return String.format("success!");
    }

    
    public String FallbackRT() {
        return String.format("RT degrade");
    }

}

/**
 * @Author: liuhao
 * @Description:
 * @Date: Create in 11:39 AM 2019/3/20
 */
@RestController
public class FallBackController {

    @Autowired
    private FallBackService fallbackservice;

    private static volatile int totalCount=0;
    private static volatile int degradeCount=0;
    private static volatile int flockCount=0;
    private static volatile int sysCount=0;

    @GetMapping("/fallbackEC")
    public String fallbackEC(long num) {

        long startTime = System.currentTimeMillis();

        String result = fallbackservice.fallbackEC(num);

        long endTime = System.currentTimeMillis();

        System.out.println("execution time:" + (endTime - startTime)+"result:"+result);

        return result;
    }

    @GetMapping("/fallbackER")
    public String fallbackER(long num) {
        long startTime = System.currentTimeMillis();

        String result = fallbackservice.fallbackER(num);

        long endTime = System.currentTimeMillis();

        System.out.println("execution time:" + (endTime - startTime)+"result:"+result);

        return result;
    }

    @GetMapping("/fallbackRT")
    public String fallbackRT() {
        long startTime = System.currentTimeMillis();

        String result = fallbackservice.fallbackRT();

        long endTime = System.currentTimeMillis();

        System.out.println("execution time:" + (endTime - startTime)+"result:"+result);

        return result;
    }

}

/**
 * @Author: liuhao
 * @Description: AOP CONFIG
 * @Date: Create in 11:39 AM 2019/3/20
 */
@Configuration
public class AopConfiguration {

    @Bean
    public SentinelResourceAspect sentinelResourceAspect() {

        return new SentinelResourceAspect();
    }
}

/**
 * @Author: liuhao
 * @Description:   INIT RULES
 * @Date: Create in 6:43 PM 2019/3/18
 */
public class FileDataSourceInit implements InitFunc {

    private Converter<String, List<FlowRule>> flowRuleListParser = source -> JSON.parseObject(source,
            new TypeReference<List<FlowRule>>() {});
    private Converter<String, List<DegradeRule>> degradeRuleListParser = source -> JSON.parseObject(source,
            new TypeReference<List<DegradeRule>>() {});
    private Converter<String, List<SystemRule>> systemRuleListParser = source -> JSON.parseObject(source,
            new TypeReference<List<SystemRule>>() {});
    @Override
    public void init() throws Exception {
        ClassLoader classLoader = getClass().getClassLoader();
        String flowRulePath = URLDecoder.decode(classLoader.getResource("FlowRule.json").getFile(), "UTF-8");
        String degradeRulePath = URLDecoder.decode(classLoader.getResource("DegradeRule.json").getFile(), "UTF-8");
//        String systemRulePath = URLDecoder.decode(classLoader.getResource("SystemRule.json").getFile(), "UTF-8");

        // Data source for FlowRule 
        FileRefreshableDataSource<List<FlowRule>> flowRuleDataSource = new FileRefreshableDataSource<>(
                flowRulePath, flowRuleListParser);
        FlowRuleManager.register2Property(flowRuleDataSource.getProperty());

        // Data source for DegradeRule 
        FileRefreshableDataSource<List<DegradeRule>> degradeRuleDataSource
                = new FileRefreshableDataSource<>(
                degradeRulePath, degradeRuleListParser);
        DegradeRuleManager.register2Property(degradeRuleDataSource.getProperty());

//        // Data source for SystemRule 
//        FileRefreshableDataSource<List<SystemRule>> systemRuleDataSource
//                = new FileRefreshableDataSource<>(
//                systemRulePath, systemRuleListParser);
//        SystemRuleManager.register2Property(systemRuleDataSource.getProperty());
    }

}

local  Degrade Specific rules JSON

[
  {
    "resource": "fallbackEC",
   "count": 10,
    "grade": 2,
    "timeWindow": 10
  },
  {
    "resource": "fallbackER",
    "count": 0.3,
    "grade": 1,
    "timeWindow": 10
  },
  {
    "resource": "fallbackRT",
    "count": 1,
    "grade": 0,
    "timeWindow": 100
  }
]

**Comment by liuhao940826** [comment]
someone  could checkout from https://github.com/liuhao940826/sentinel-self-demo.git  branch: fallback

**Comment by sczyh30** [comment]
Hi, please ensure that your QPS >= 5 or RT mode won't take effect.
