### ISSUE TITLE
Consult the RateLimiterController thread safety dispute

### ISSUE THREAD

**Issue by fg546300040** [alibaba/Sentinel#604]
long currentTime = TimeUtil.currentTimeMillis();
        // Calculate the interval between every two requests.
        long costTime = Math.round(1.0 * (acquireCount) / count * 1000);

        // Expected pass time of this request.
        long expectedTime = costTime + latestPassedTime.get();

        if (expectedTime <= currentTime) {
            // Contention may exist here, but it's okay.
            latestPassedTime.set(currentTime);
            return true;
        } 

## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

            // Contention may exist here, but it's okay.
            latestPassedTime.set(currentTime);
咨询下：这里写着有争议， 但是确实出现了线程安全的问题，为啥是okay的？

### Describe what you expected to happen

期望严格匀速限流

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
As for `RateLimiterController`, it is designed as a not strictly thread-safe implementation for performance (as well as in other traffic controllers). In Sentinel, we need to consider both correctness and performance.

**Comment by fg546300040** [comment]
> As for `RateLimiterController`, it is designed as a not strictly thread-safe implementation for performance (as well as in other traffic controllers). In Sentinel, we need to consider both correctness and performance.

Ok， performance first
