### ISSUE TITLE
Degrade design

### ISSUE THREAD

**Issue by CalvinKirs** [alibaba/Sentinel#606]
目前来看，Sentinel这块其实只是做了熔断，命名为降级是不合理的。熔断与降级结果是一样的，但是目的不一样，一个属于主动，一个属于被动。被熔断后采用备用方案属于业务方的补偿机制。这个不能称之为降级，降级应该是说当我有预感会有较大的流量的还好，我的负载比较高，那么我会梳理依赖关系，关闭一些次要服务，让出资源来给核心服务用。而且Sentinel这里的话也完全可以把降级给做出来，用户可以主动的在控制台做降级操作，自定义时间窗口大小。我最早看58那边的应该是有这么一个降级操作。就是说大促期间，会关闭一些非核心的业务，这块尽可能把资源让给核心业务

**Comment by CalvinKirs** [comment]
或许降级这块并没有一个很好的界线，但是这个新的建议（按照我的理解的降级）亦是可以做的。希望大家可以给一些建议意见亦或可行性分析

**Comment by fg546300040** [comment]
可以在指定的范围时间内根据系统流量进行降级么？ 比如在大促期间，相关指标线程数，负载，qps达到一定的阈值则相关的资源自动降级

**Comment by CalvinKirs** [comment]
> 可以在指定的范围时间内根据系统流量进行降级么？ 比如在大促期间，相关指标线程数，负载，qps达到一定的阈值则相关的资源自动降级

自定义时间窗口的降级宿何大佬说是后续也在做。更多系统指标作为熔断依据或许也会加进来，qps线程数这块属于限流的行为，降级是系统不健康的时候的行为。

**Comment by cdfive** [comment]
> 而且Sentinel这里的话也完全可以把降级给做出来，用户可以主动的在控制台做降级操作，自定义时间窗口大小。我最早看58那边的应该是有这么一个降级操作。就是说大促期间，会关闭一些非核心的业务，这块尽可能把资源让给核心业务

目前Sentinel的降级规则，是完全支持说的这个呀。在控制台某个资源添加降级规则，可选RT/异常比例/异常数类型，时间创建是用户自定义的。去年双十一刚好用过这个功能，时间窗口随时可调很方便。

> 降级应该是说当我有预感会有较大的流量的还好，我的负载比较高，那么我会梳理依赖关系，关闭一些次要服务，让出资源来给核心服务用

我赞同这句，这里降级规则是支持的，因为降级后走备选方案(比如不走数据库/缓存等)，这样数据库/缓存等资源就让给了核心业务。

**Comment by fg546300040** [comment]
> > 可以在指定的范围时间内根据系统流量进行降级么？ 比如在大促期间，相关指标线程数，负载，qps达到一定的阈值则相关的资源自动降级
> 
> 自定义时间窗口的降级宿何大佬说是后续也会做。更多系统指标作为熔断依据或许也会加进来，qps线程数这块属于限流的行为，目前已经有了，可以参照wiki，降级是系统不健康的时候的行为。

嗯嗯，把主动行为和被动行为区分开来。

**Comment by CalvinKirs** [comment]
> > 而且Sentinel这里的话也完全可以把降级给做出来，用户可以主动的在控制台做降级操作，自定义时间窗口大小。我最早看58那边的应该是有这么一个降级操作。就是说大促期间，会关闭一些非核心的业务，这块尽可能把资源让给核心业务
> 
> 目前Sentinel的降级规则，是完全支持说的这个呀。在控制台某个资源添加降级规则，可选RT/异常比例/异常数类型，时间创建是用户自定义的。去年双十一刚好用过这个功能，时间窗口随时可调很方便。
> 
> > 降级应该是说当我有预感会有较大的流量的还好，我的负载比较高，那么我会梳理依赖关系，关闭一些次要服务，让出资源来给核心服务用
> 
> 我赞同这句，这里降级规则是支持的，因为降级后走备选方案(比如不走数据库/缓存等)，这样数据库/缓存等资源就让给了核心业务。

熔断时间是支持的，就是说统计的时间窗口，但是我觉得这里的话没必要。秒或者分钟已经足够了

**Comment by CalvinKirs** [comment]
> > 而且Sentinel这里的话也完全可以把降级给做出来，用户可以主动的在控制台做降级操作，自定义时间窗口大小。我最早看58那边的应该是有这么一个降级操作。就是说大促期间，会关闭一些非核心的业务，这块尽可能把资源让给核心业务
> 
> 目前Sentinel的降级规则，是完全支持说的这个呀。在控制台某个资源添加降级规则，可选RT/异常比例/异常数类型，时间创建是用户自定义的。去年双十一刚好用过这个功能，时间窗口随时可调很方便。

这里说的是统计的时间窗口，用户不再局限与秒或者分钟，但是我觉得没必要。
> 
> > 降级应该是说当我有预感会有较大的流量的还好，我的负载比较高，那么我会梳理依赖关系，关闭一些次要服务，让出资源来给核心服务用
> 
> 我赞同这句，这里降级规则是支持的，因为降级后走备选方案(比如不走数据库/缓存等)，这样数据库/缓存等资源就让给了其它核心业务。

**Comment by ct2080** [comment]
提出我的理解
1. Sentinel、Hystrix、Resilience4j 都叫做熔断器
2.熔断器里面三个功能限流、熔断、降级
3.每个功能里都可以写补偿方法

ps：sentinel目前只有限流和熔断的功能；控制台上的降级命名按我理解实则是熔断命名！

**Comment by linlinisme** [comment]
降级和熔断本质是不一样的，作用场景也不一样。熔断可以理解为服务不可用，这时服务提供方已经不堪重负，再增加负载可能会压垮整个系统，这个时候拒绝服务，这个叫做熔断，更像是一种被动防御。降级指的是服务依然可用，但是质量会下降，好比五星级服务降成了三星级，目的为了分配更好多的资源给核心关键的业务，这是一种主动性的调整。

**Comment by CalvinKirs** [comment]
> 降级和熔断本质是不一样的，作用场景也不一样。熔断可以理解为服务不可用，这时服务提供方已经不堪重负，再增加负载可能会压垮整个系统，这个时候拒绝服务，这个叫做熔断，更像是一种被动防御。降级指的是服务依然可用，但是质量会下降，好比五星级服务降成了三星级，目的为了分配更好多的资源给核心关键的业务，这是一种主动性的调整。

I agree with you。The most fundamental judgment is whether the service is available or not available.
