### ISSUE TITLE
[Bug]Deadlock may happen in Env static code block

### ISSUE THREAD

**Issue by CarpenterLee** [alibaba/Sentinel#609]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

`Env` static code block may cause a deadlock.

### Describe what you expected to happen

`Env` static code block initialize successfully.

### How to reproduce it (as minimally and precisely as possible)

It's not really easy to cause a deadlock when init `Env`, but java static code block does have the possibility to cause a deadlock. For example, the following code will always lead a deadlock:

```java
public class Main {
    public static void main(String[] args) throws Exception {
        System.out.println("Main begin...");
        new Thread(() -> {
            System.out.println(Env.EVN_STR);
        }).start();
        System.out.println(Constants.CONSTANTS_STR);
        System.out.println("Main end");
    }

    public static final class Env {
        static final StringBuilder EVN_STR = new StringBuilder("env str");

        static {
            System.out.println("Env static block begin, " + Thread.currentThread());
            // deadlock by Constants
            System.out.println("Env refer -> " + Constants.CONSTANTS_STR);
            System.out.println("Env static block end");
        }
    }

    public static class Constants {
        static final StringBuilder CONSTANTS_STR = new StringBuilder("constants str");

        static {
            System.out.println("Constants static block begin, " + Thread.currentThread());
            // deadlock by Env
            System.out.println("Constants refer -> " + Env.EVN_STR);
            System.out.println("Constants static block end");
        }
    }
}
```
The above code is simple, but clearly explain how deadlock happens in static initialization:

1. two classes' static code block refer to each other(circular reference, here is `Env` and `Constants`).
2. the two classes' static initialization are triggered at the same time in diffenert threads. Each thread holds static lock of one class and wait the other.

It's what Sentinel did in `com.alibaba.csp.sentinel.Env` and `com.alibaba.csp.sentinel.Constants`. They have a circular reference in static code block (1) and may both be triggered at the same time in different threads (2). More precisely, it's `FlowRuleManager` who starts the other thread.

Destroying any condition of the two can prevent deadlocks. Condition (2) can hardly be destroyed because Sentinel initialization is quite complex. But we can carefully **eliminate circular references in any static code block**, it's what we should do all the time.

### Tell us your environment

Sentinel SDK 1.5.0

**Comment by tigerMoon** [comment]
the static block is executed when a class needs isloaded , so it`s sychornized.

The code in a static block should be such that it doesn’t trigger class loading events for another class that also has a static block that, in turn, depends on this class. This may introduce the possibility of deadlock.

it`s cool, how did you find it?

**Comment by sczyh30** [comment]
Since 1.5.0 there is a reference chain: `DegradeRuleManager -> Constant`. When `Constant` class is being initialized, it requires `Env` to be initialized first. When we register a dynamic data source to `DegradeRuleManager` in customized `InitFunc`, since init functions are invoked in static block of `Env` class, an implicit chain formed: `Env -> DataSourceInitFunc -> DegradeRuleManager -(LOCKED) -> Constant -> Env`, which will trigger this bug.
