### ISSUE TITLE
Support more kinds of exception types when tracing exception count in Sentinel Dubbo Adapter

### ISSUE THREAD

**Issue by guonanjun** [alibaba/Sentinel#61]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
使用sentinel-dubbo-adapter后，为资源设置熔断降级时，根据异常比例降级只支持RpcException，不支持其他RuntimeException。
![default](https://user-images.githubusercontent.com/29148151/44095479-836a389e-a00b-11e8-9db8-d36cbf6cb0c5.png)

### Describe what you expected to happen
期望支持其他RuntimeException。

**Comment by sczyh30** [comment]
Thanks for reporting! We'll fix this in 0.2.0.
