### ISSUE TITLE
How to do rate limiting in uniform gateway?

### ISSUE THREAD

**Issue by Fxdemon** [alibaba/Sentinel#611]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Fxdemon** [comment]
统一限流入口 如Gataway 怎么做？  求方法？？

**Comment by sczyh30** [comment]
Hi, you can refer to [Sentinel Zuul Adapter](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-zuul-adapter). Discussions about Spring Cloud Gateway is here: #86
