### ISSUE TITLE
The difference between SphU and SphO when using FlowRule Thread current limiting mode

### ISSUE THREAD

**Issue by WindyDovs** [alibaba/Sentinel#614]
@Test
	public void boolThread() throws InterruptedException {
		// 配置规则.
		initFlowRules();
		while (true) {
			if (SphO.entry("HelloWorld")) {
				System.out.println("hello world");
			} else {
				System.out.println("blocked!");
			}
			Thread.sleep(10);
		}
	}

	@Test
	public void exThread() throws InterruptedException {
		// 配置规则.
		initFlowRules();

		while (true) {
			Entry entry = null;
			try {
				entry = SphU.entry("HelloWorld");
				// 资源中的逻辑.
				System.out.println("hello world");
			} catch (BlockException e1) {
				System.out.println("blocked!");
			} finally {
				if (entry != null) {
					entry.exit();
				}
			}
			Thread.sleep(10);
		}
	}

	/**
	 * 线程数与QPS控制
	 */
	private static void initFlowRules() {
		FlowRule rule = new FlowRule();
		rule.setResource("HelloWorld");
		rule.setGrade(RuleConstant.FLOW_GRADE_THREAD);
		rule.setCount(5);// 限制QPS
		rules.add(rule);
		FlowRuleManager.loadRules(rules);
	}

当执行 boolThread() 的时候，打印5个"hello world"后，就无限 blocked 了，而exThread()方法是表现正常的（其实就一个线程在跑），对比代码发现唯一区别就是 SphO.entry 里面，不会执行 entry.exit()，导致执行完毕后线程数不会减一，请问这是一个BUG吗？还是说规则上，线程流控不允许使用SphO这个类？
在文档上没发现说明，有劳多多指教，多谢了。

**Comment by sczyh30** [comment]
The way you're using `SphO` is incorrect. `SphO` also requires exit. Example:

```java
if (SphO.entry(resourceName)) {
  try {
     // Your code logic here.
  } finally {
      SphO.exit();
  }
} else {
    // Resource is rejected.
    // Your logic to handle blocking here.
  }
}
```

---

代码中使用 `SphO` 的方式错误，`SphO` 同样需要 exit，示例：

```java
  // 资源名可使用任意有业务语义的字符串
  if (SphO.entry("自定义资源名")) {
    // 务必保证finally会被执行
    try {
      /**
      * 被保护的业务逻辑
      */
    } finally {
      // 务必保证 exit
      SphO.exit();
    }
  } else {
    // 资源访问阻止，被限流或被降级
    // 进行相应的处理操作
  }
```

**Comment by WindyDovs** [comment]
太大意了，谢谢。
