### ISSUE TITLE
Are there any interfaces and examples about authentication for Sentinel Dashboard?

### ISSUE THREAD

**Issue by z2468091508** [alibaba/Sentinel#616]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, you can refer to the [`AuthService`](https://github.com/alibaba/Sentinel/blob/master/sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/auth/AuthService.java) interface introduced in 1.5.0.
