### ISSUE TITLE
[bug][transport-netty-http]setRules will not receive rules correctly when rules is longer then url's limitation

### ISSUE THREAD

**Issue by jasonjoo2010** [alibaba/Sentinel#618]
## Issue Description

When rules grow modification requests through transport module will fail.

### Describe what happened (or what feature you want)
HTTP 400 occurred

### Describe what you expected to happen
Rules can be saved successfully.

### How to reproduce it (as minimally and precisely as possible)
Increasing the rules to the number 18 or more may reproduce the issue.

**Comment by sczyh30** [comment]
Resolved in #620 and #667 by @jasonjoo2010
