### ISSUE TITLE
Support customized log directory and configuration properties directory

### ISSUE THREAD

**Issue by cookieka** [alibaba/Sentinel#62]
目前启动配置项如果走配置文件只能${home}/logs/csp/${project.name}.properties路径下，log文件输出也是在${home}/logs/csp/下面
1.看是否可以整合到具体项目配置文件中去
2.看是否支持自定义路径，配置文件和log文件路径等。
主要由于当前公司环境部署集中化部署，且多个环境在一个服务器。

**Comment by sczyh30** [comment]
Hi, since Sentinel 1.3.0-GA we've supported custom log base directory via `csp.sentinel.log.dir` property. We might support customized properties directory in later versions.

**Comment by linlinisme** [comment]
hey,  i will provide the feature in the next version.
