### ISSUE TITLE
About Sentinel blockHandler , optimization of blockHandlerClass

### ISSUE THREAD

**Issue by mail6562** [alibaba/Sentinel#624]
// 对应的 `handleException` 函数需要位于 `ExceptionUtil` 类中，并且必须为 static 函数.
    @SentinelResource(value = "test", blockHandler = "handleException", blockHandlerClass = {ExceptionUtil.class})
    public void test() {
        System.out.println("Test");
    }
Sentinel  注解 SentinelResource ，内部的blockHandler ，   blockHandlerClass  能不能支持到通用的定义，在方法上加了SentinelResource 的注解就会触发的限流处理，只需要在限流处理里面增加一个标识码或者标注位就可以在一个地方处理限流了。现在需要在每个方法都增加blockHandler ，   blockHandlerClass，而且blockHandler 的参数要跟这个方法的参数一致，其实方法上的注解是可以获取到方法的参数和返回对象的。

**Comment by sczyh30** [comment]
Hi, you can extend the `AbstractSentinelAspectSupport` and implement your own aspect logic so you can customize.
