### ISSUE TITLE
Unable to use Sentinel's downgrade flow control

### ISSUE THREAD

**Issue by mybug99** [alibaba/Sentinel#625]
这是我配置好的
![image](https://user-images.githubusercontent.com/43434812/55138416-5e308000-516e-11e9-9834-b84b72ba79ce.png)

以下是代码
![image](https://user-images.githubusercontent.com/43434812/55138434-6e485f80-516e-11e9-8927-7d1f2e31567e.png)

会出现这个并不会进入我的代码降级也是有问题
![image](https://user-images.githubusercontent.com/43434812/55138456-7dc7a880-516e-11e9-922d-51214fe07410.png)

**Comment by sczyh30** [comment]
blockHandler 函数签名不符合注解的要求（参数列表最后多一个 BlockException，其余与原函数一致），详见：[注解支持文档](https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81#sentinelresource-%E6%B3%A8%E8%A7%A3)。

---

Your `blockHandler` function does not match the requirement of Sentinel annotation support. See [the document](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj) for the details.

**Comment by mybug99** [comment]
> blockHandler 函数签名不符合注解的要求（参数列表最后多一个 BlockException，其余与原函数一致），详见：[注解支持文档](https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81#sentinelresource-%E6%B3%A8%E8%A7%A3)。
> 
> Your `blockHandler` function does not match the requirement of Sentinel annotation support. See [the document](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj) for the details.

好的谢谢，好了
