### ISSUE TITLE
[RFC] Flow control for Netflix Zuul

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#63]
## Issue Description

Type: *feature request*

### Describe or what feature you want

Integrate Sentinel with Netflix Zuul so that we can provide out-of-box flow control ability for Zuul (1.x and 2.x). Moreover, we may support more open-source API Gateways.

**Comment by kimmking** [comment]
good idea

**Comment by tigerMoon** [comment]
Here is my suggestion to integrate with Netflix Zuul:

[Netflix Zuul](https://github.com/Netflix/zuul/wiki/How-it-Works) just uses `Servlet` filters to chain the request. and has three stages `pre` `route` and `post`

just add `CommonFilter`  in `pre` stage. it is same to `Sentinel Servlet Adapter`. 

the difference is the error handler. so just add another filer to trace error config like this:
```
Tracer.trace(e3);
```

if used in Spring Cloud familiy. [Sentinel Spring Cloud Starter](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/readme-zh.md) may be a good choice

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. Here are some of my considerations:

- Flow control for API gateway is different from web requests. Users often care about flow control for service (e.g. `/serviceA/*` pattern in API gateway), not for a specific URL.
- **Distributed flow control** is often required for API gateway.
- Zuul 2.x has breaking changes and is totally different from Zuul 1.x. Zuul 2.x leverages reactor pattern of Netty, so the implementation will be different (may depend on async support in Sentinel 0.2.0).

**Comment by zuonidelaowang** [comment]
zuul网关限流, 我们这边的实现方式, 欢迎大家交流沟通.



--------------------------------------
网关限流zuulFilter实现部分
--------------------------------------
public class AccessFilter extends ZuulFilter {
    @Override
    public String filterType() {
        return FilterConstants.PRE_TYPE;
    }

    @Override
    public int filterOrder() {
        return 1;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();
       // 统计API访问时间
        ctx.set("startTime", System.currentTimeMillis());
      // IP限流
        if (!sentinelIp(ctx)) {
            return null;
        }
      // 访问频率限流
        if (!sentinelApi(ctx)) {
            return null;
        }
        return null;
    }

    /**
     * @Author: ---
     * @Date: 2018/9/10 17:32
     * @Description: 限流IP
     **/
    private boolean sentinelIp(RequestContext ctx) {
        HttpServletRequest request = ctx.getRequest();
        // 获取用户IP地址，将用户IP地址当做限流key
        String ip = IpTool.getIp(request);
        Entry entry = null;
        try {
            entry = SphU.entry(ip);
        } catch (BlockException e1) {
            log.info("API -> 限流ip：" + ip);
            // 过滤该请求，不往下级服务去转发请求，到此结束
            ctx.setSendZuulResponse(false);
            ctx.setResponseStatusCode(429);
            ctx.setResponseBody("{\"result\":\"IP访问次数超限!\"}");
            ctx.getResponse().setContentType("application/json;charset=UTF-8");
            return false;
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
        return true;
    }

    /**
     * @Author: ---
     * @Date: 2018/9/10 17:32
     * @Description: 限流
     **/
    private boolean sentinelApi(RequestContext ctx) {
        HttpServletRequest request = ctx.getRequest();
        //获取用户请求地址，将用户请求地址当做限流key
        String url = request.getServletPath();
        Entry entry = null;
        try {
            entry = SphU.entry(url);
        } catch (BlockException e1) {
            log.info("API -> api限流地址：" + url);
            ctx.setSendZuulResponse(false);
            ctx.setResponseStatusCode(429);
            ctx.setResponseBody("{\"result\":\"API访问次数超限!\"}");
            ctx.getResponse().setContentType("application/json;charset=UTF-8");
            return false;
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
        return true;
    }
}


--------------------------------------
网关限流规则
--------------------------------------

public class ZuulLimitInit {

    @Resource(name = "redisTemplate")
    private RedisTemplate redisTemplate;

    /**
     * @Author: --------
     * @Date: 2018/9/11 13:15
     * @Description: 初始化限流规则
     **/
    public void init() {
        // 从redis读取限流规则
        if (!RedisTool.exists(redisTemplate, ZuulLimitEnum.ZUUL_LIMIT.getKey())) {
            log.info("API -> 限流规则为空,直接返回");
            return;
        }
        // 把限流规则配置在redis
        List<String> list = RedisTool.hget(redisTemplate, ZuulLimitEnum.ZUUL_LIMIT.getKey());
        List<FlowRule> rules = new ArrayList<>();
        list.forEach(s -> {
            JSONObject jsonObject = JSONObject.parseObject(s);
            // 初始化限流规则
            FlowRule rule = new FlowRule();
            rule.setResource(jsonObject.getString("resource"));
            rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
            // 每秒钟多少个QPS
            rule.setCount(jsonObject.getInteger("count"));
            rules.add(rule);
        });
        log.info("API -> 初始化限流规则：{}", rules);
        //加载限流规则
        FlowRuleManager.loadRules(rules);
    }
}


--------------------------------------
启动项目后, 初始化限流规则
--------------------------------------

@EnableZuulProxy
@EnableDiscoveryClient
//@EnableFeignClients
@SpringBootApplication
public class CommonGatewayApplication implements CommandLineRunner {

    @Autowired
    private ZuulLimitInit zuulLimitInit;

    public static void main(String[] args) {
        SpringApplication.run(CommonGatewayApplication.class, args);
    }

    @Override
    public void run(String... strings) throws Exception {
        zuulLimitInit.init();
    }
}

**Comment by tigerMoon** [comment]
Here give a sample for the integration of zuul1. 
https://github.com/tigerMoon/sentinel-zuul-sample

**Comment by tigerMoon** [comment]
Finally.   I know what does Zuul need. Zuul lack of rate limit or flow control what does Sentinel provide. We can give an adapter for Zuul. include `Service` `API path` and `Authority` features. 

The user may use like this:

```xml

<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>spring-cloud-zuul-sentinel-adapter</artifactId>
 </dependency>

// set property.
zuul.sentinel.enabled =true.

```
