### ISSUE TITLE
Does sentinel support Thrift?

### ISSUE THREAD

**Issue by Force-King** [alibaba/Sentinel#650]
@sczyh30 
Hi,我们公司的RPC服务用的是 thrift ，请问 sentinel 目前支持 thrift 吗？ 需要我自己实现呢?
还是已经有了像 Dubbo 那样的自适应配置？

**Comment by sczyh30** [comment]
Hi, there are not integrations for Thrift yet. You have to wrap your code by yourself. Contributions are welcomed :)

**Comment by Force-King** [comment]
Ok, I see. Thank you.

**Comment by teaho2015** [comment]
Does Sentinel support Thrift now？
