### ISSUE TITLE
com.alibaba.csp.sentinel.adapter.grpc.gen can not find

### ISSUE THREAD

**Issue by service-kit** [alibaba/Sentinel#661]
Error:(18, 49) java: 程序包com.alibaba.csp.sentinel.adapter.grpc.gen不存在

**Comment by sczyh30** [comment]
Hi, these stub classes are generated by `protoc-gen-grpc-java` plugin during the "test-compile" period, so you can execute `mvn clean test` to generate the classes (located in `target/generated-test-sources/protobuf` directory, can be automatically identified by IDEA).

**Comment by service-kit** [comment]
ok, thankyou very much发自我的iPhone------------------ Original ------------------From: Eric Zhao  <notifications@github.com>Date: Tue,Apr 9,2019 11:11 AMTo: alibaba/Sentinel <Sentinel@noreply.github.com>Cc: service-kit <seaofstars.developer@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [alibaba/Sentinel] com.alibaba.csp.sentinel.adapter.grpc.gen cannot find (#661)Hi, these stub classes are generated by protoc-gen-grpc-java plugin during the "test-compile" period, so you can execute mvn clean test to generate the classes (located in target/generated-test-sources/protobuf directory, can be automatically identified by IDEA).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/Sentinel","title":"alibaba/Sentinel","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/Sentinel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sczyh30 in #661: Hi, these stub classes are generated by `protoc-gen-grpc-java` plugin during the \"test-compile\" period, so you can execute `mvn clean test` to generate the classes (located in `target/generated-test-sources/protobuf` directory, can be automatically identified by IDEA)."}],"action":{"name":"View Issue","url":"https://github.com/alibaba/Sentinel/issues/661#issuecomment-481084724"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/Sentinel/issues/661#issuecomment-481084724",
"url": "https://github.com/alibaba/Sentinel/issues/661#issuecomment-481084724",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
