### ISSUE TITLE
The ClusterClientConfigManager class mentioned in the cluster flow control documentation does not have the register2Property method described in the documentation.

### ISSUE THREAD

**Issue by ccyacc** [alibaba/Sentinel#663]
## Issue Description

Type: *bug report* or *feature request*

**Comment by sczyh30** [comment]
Hi, I've updated the document and you can refer to the document [here](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7#%E9%9B%86%E7%BE%A4%E9%99%90%E6%B5%81%E5%AE%A2%E6%88%B7%E7%AB%AF).

- Client assign config (`ClusterClientAssignConfig`): including peer token server ip and port. We can register via `ClusterClientConfigManager#registerServerAssignProperty` method.
- Client transport config (`ClusterClientConfig`): including config related to transport (e.g. request timeout). We can register via `ClusterClientConfigManager#registerClientConfigProperty ` method.
