### ISSUE TITLE
Console mode selection

### ISSUE THREAD

**Issue by yfh0918** [alibaba/Sentinel#664]
通过系统参数来决定起动控制台的支持模式，比如nacos或者其它

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Good idea. Maybe we can refer to the approach in #660?

**Comment by yfh0918** [comment]
是否可以简单采用spi方式通过启动参数来决定控制台模式
