### ISSUE TITLE
Implement Envoy global rate limiting gRPC service with Sentinel cluster flow control

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#666]
## Issue Description

Type: *feature request*

### Describe what feature you want

Envoy provides a [global rate limiting gRPC service definition](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/ratelimit/v2/rls.proto). We can implement the RLS with Sentinel cluster flow control (in Java) so service mesh that uses Envoy as data plane could take advantage of Sentinel.

Some design and refactor of cluster module might need be taken to adapt to service mesh and cloud native infrastructure. Discussions are welcomed.

Related to #200

**Comment by fg546300040** [comment]
目前同步请求ClusterTokenServer申请token，虚拟机会有C10K的瓶颈，只能适用于少量并发的场景。在高并发的场景应该采用起异步线程跟ClusterTokenServer通信，在保证高性能的条件下实现集群流控。

总之，在原有的基础上，增加异步跟ClusterTokenServer通信可以满足高性能的集群流控了。

**Comment by sczyh30** [comment]
> 目前同步请求ClusterTokenServer申请token，虚拟机会有C10K的瓶颈，只能适用于少量并发的场景。在高并发的场景应该采用起异步线程跟ClusterTokenServer通信，在保证高性能的条件下实现集群流控。
> 
> 总之，在原有的基础上，增加异步跟ClusterTokenServer通信可以满足高性能的集群流控了。

Token client 和 token server 的通信过程是异步的，只不过由于上层 `SphU.entry(xxx)` 调用模型是同步的所以在上层转成同步的了，这种情况下具体的吞吐量取决于通信的 RT 和调用端的并发线程数。

PS: we can discuss it in #200. This issue is for Envoy RLS integration :)

**Comment by fg546300040** [comment]
> > 目前同步请求ClusterTokenServer申请token，虚拟机会有C10K的瓶颈，只能适用于少量并发的场景。在高并发的场景应该采用起异步线程跟ClusterTokenServer通信，在保证高性能的条件下实现集群流控。
> > 总之，在原有的基础上，增加异步跟ClusterTokenServer通信可以满足高性能的集群流控了。
> 
> Token client 和 token server 的通信过程是异步的，只不过由于上层 `SphU.entry(xxx)` 调用模型是同步的所以在上层转成同步的了，这种情况下具体的吞吐量取决于通信的 RT 和调用端的并发线程数。
> 
> PS: we can discuss it in #200. This issue is for Envoy RLS integration :)


嗯嗯， 每隔一个周期（比如100ms）跟server通信就基本满足高并发的集群流控的场景了。当然 如果有protocol序列化会更好。所以，我觉得重点是要周期性的跟server通信。

**Comment by rohanjulka19** [comment]
Hi, I want to work on this issue, I have already read about sentinel flow control, service mesh and envoy. I am still unable to understand how will this be implemented can you help me better understand it. Thank you

**Comment by rohanjulka19** [comment]
Thank you

**Comment by sczyh30** [comment]
Architecture overview:

![image](https://user-images.githubusercontent.com/9434884/68201478-cd236080-fffc-11e9-9e8e-f06a09e12642.png)

The initial version will include the Envoy RLS gRPC server implementation using the existing token server module. The RLS service implementation will leverage the existing flow rule managing and checking logic. To adapt to Envoy's "rate limit action", we propose the `EnvoyRlsRule` representation like this:

```yaml
domain: example1
descriptors:
  - resources:
    - key: "destination_cluster"
      value: "svc-foo"
    count: 10
```

The `domain` and `descriptor` will match the counterpart in `RateLimitRequest` of RLS. Note that the first version can only support the exact "key-value" pair (i.e. exact resource name without params). We'll add support for "key-matching" scheme (i.e. parameter flow control) in next versions.

We need a converter to convert the `EnvoyRlsRule` to `FlowRule`. For cluster flow rule, we need to generate the ruleId for each FlowRule, which should be unique and consistent. We may use the *hash code + offset* by default.

As for configuration, we could support dynamic configuration from YAML file first. In the future, we could design K8S CRDs for rules so that we could update the rules via `kubectl` or other dashboards.
