### ISSUE TITLE
dubbo adapter show resource name incorrect

### ISSUE THREAD

**Issue by YoungHu** [alibaba/Sentinel#67]
### Describe what happened (or what feature you want)
dubbo resource combine with interface and method(args...), interface combine with `group_name/interface_name:version_id`, but dubbo adapter only extract the `interface_name`, it's not correct.

### Describe what you expected to happen
show dubbo resource with `group_name/interface_name:version_id`

### How to reproduce it (as minimally and precisely as possible)
1. check the resource name from dashboard

### Tell us your environment
environment make no sense.

### Anything else we need to know?
no

**Comment by sczyh30** [comment]
Some considerations that should be resolved:

- Users may want to do flow control by group, interface, version, or their combination, like this:
  - `entry(dubbo:groupName)`
  - `entry(dubbo:interfaceName)`
  - `entry(dubbo:serviceVersion)`
  - `entry(dubbo:groupName/interfaceName)` (Especially this circumstance: If users upgraded their services, the old rules will be deprecated.)
  - `entry(dubbo:groupName/interfaceName/serviceVersion)`

**Comment by sczyh30** [comment]
@kimmking What do you think of this issue?

**Comment by kimmking** [comment]
1. groupName may be a condition.
2. dubbo adapter is simple component, in complex usage scenarios users could implement providerFilter&consumerFilter.
3. see also: https://github.com/alibaba/Sentinel/issues/90

**Comment by YoungHu** [comment]
@kimmking @sczyh30 
1. we impossible to limit the user how to use dubbo group feature, if multi group used in one application sentinel can't control correct.
2. in my opinion, since the official provides the dubbo adapter, it should consider all the scenarios. sentinel should keep the original resource definition style of dubbo and make the adapter become a powerful tool instead of positioning it as a simple tool.
