### ISSUE TITLE
Make the value of RT_MAX_EXCEED_N in DegradeRule configurable

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#673]
## Issue Description

In the process of degrade,  when resource enters a quasi-degraded state, the max count (the value of `RT_MAX_EXCEED_N` in `DegradeRule` class) which statistics the next coming requests passed now is fixed value: **5**.

Users in community are wondering that why the value is fixed.

### Describe what happened (or what feature you want)

Users may expect that the `RT_MAX_EXCEED_N` can be configured in different scenes.

How about  adding a property like `csp.sentinel.degrade.rt.max.exceed.count`? 
and does it need to be modified dynamically?

### Anything else we need to know?

Related to #154

**Comment by sczyh30** [comment]
I think this can be different per rules. We may need to add a new field for this, but this should be carefully designed, as this `RT_MAX_EXCEED_N` has multiple usages actually. In exception ratio mode, if total QPS < `RT_MAX_EXCEED_N`, even if the exception ratio exceeded the threshold, the request would pass.

**Comment by sczyh30** [comment]
Resolved in #789. It's now configurable as two attributes:

- `rtSlowRequestAmount` for the minimum number of consecutive slow requests that can trigger RT circuit breaking.
- `minRequestAmount` for the minimum number of requests (in an active statistic time span) that can trigger circuit breaking.
