### ISSUE TITLE
Dubbo SentinelRpcException Unable to catch exception

### ISSUE THREAD

**Issue by CjqDy** [alibaba/Sentinel#674]
在示例中
catch (SentinelRpcException ex) {
          System.out.println("blocked");
  }
没有捕获到SentinelRpcException ，而是打印出了异常信息
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.orange.service.DemoService. Tried 3 times of the providers [192.168.121.110:20880] (1/1) from the registry 127.0.0.1:8848 on the consumer 192.168.121.110 using the dubbo version 2.6.6. Last error is: Failed to invoke remote method: sayHello, provider: dubbo://192.168.121.110:20880/com.orange.service.DemoService?anyhost=true&application=exueyun-bussiness-sit-consumer&bean.name=com.orange.service.DemoService&category=providers&check=false&dubbo=2.0.2&generic=false&interface=com.orange.service.DemoService&methods=sayHello&pid=66416&protocol=dubbo&register.ip=192.168.121.110&remote.timestamp=1555470996198&side=consumer&timeout=60000&timestamp=1555471008919, cause: com.alibaba.csp.sentinel.slots.block.SentinelRpcException: com.alibaba.csp.sentinel.slots.block.flow.FlowException
com.alibaba.csp.sentinel.slots.block.SentinelRpcException: com.alibaba.csp.sentinel.slots.block.flow.FlowException
Caused by: com.alibaba.csp.sentinel.slots.block.flow.FlowException

这是怎么回事

**Comment by oawang** [comment]
me too

**Comment by sczyh30** [comment]
Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.

**Comment by CjqDy** [comment]
> Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.

dubbo 2.6.6 
ok i will try the demo later

**Comment by oawang** [comment]
dubbo 2.7.1 also

**Comment by CjqDy** [comment]
> Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.

  RpcException 可以捕获  但是 SentinelRpcException无法捕获

**Comment by zdhuangelephant** [comment]
> > Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.
> > 在dubbo 2.6.6环境下
> > dubbo 下的 RpcException 可以捕获  但是 SentinelRpcException无法捕获
Have you fixed ? if donw, how did you work out?

**Comment by zdhuangelephant** [comment]
> > Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.
> > 在dubbo 2.6.6环境下
> > dubbo 下的 RpcException 可以捕获  但是 SentinelRpcException无法捕获

Have you fixed ?  how did you figure out if you had fixed

**Comment by elvislou** [comment]
> > > Could you please provide more information (e.g. your Dubbo version, code snippet of consumer and provider)? And you can try the demo in `sentinel-demo-dubbo` and see whether it works well.
> > > 在dubbo 2.6.6环境下
> > > dubbo 下的 RpcException 可以捕获  但是 SentinelRpcException无法捕获
> 
> Have you fixed ? how did you figure out if you had fixed

这个地方有一个workaround，可以参考一下BlockException.isBlockException的实现，往下找cause，并且比较cause里的detailMessage里是否contains SentinelRpcException，就可以了。
