### ISSUE TITLE
Resource chain page is empty while real-time monitoring statistics page is correct

### ISSUE THREAD

**Issue by newWSmile** [alibaba/Sentinel#679]
我的是springboot项目，按照spring cloud alibaba 体系生态加入了依赖，启动控制台接入客户端后在控制台页面只能看到实时监控统计，但是没有簇点链路信息，而且机器也是失联的但是能用
![image](https://user-images.githubusercontent.com/18049520/56333428-c7803d80-61c6-11e9-928c-f273f0298bcc.png)
![image](https://user-images.githubusercontent.com/18049520/56333439-cd761e80-61c6-11e9-9bae-b6feb1e03f18.png)
![image](https://user-images.githubusercontent.com/18049520/56333451-d36bff80-61c6-11e9-8694-eb746e04c9cc.png)

**Comment by newWSmile** [comment]
配置了流量规则 ，生效了 但是还是没有簇点链路信息 机器还是失联状态
![image](https://user-images.githubusercontent.com/18049520/56333544-2cd42e80-61c7-11e9-9b1c-0c0329d56e67.png)
![image](https://user-images.githubusercontent.com/18049520/56333567-437a8580-61c7-11e9-92f1-ea3ccb826fbc.png)

![image](https://user-images.githubusercontent.com/18049520/56333552-33fb3c80-61c7-11e9-8448-7a016047ce42.png)
![image](https://user-images.githubusercontent.com/18049520/56333561-3bbae100-61c7-11e9-950a-de05892934f8.png)

**Comment by sczyh30** [comment]
Could you please provide the dependencies you've added to your project about Sentinel? It seems the Sentinel version is not compatible with that in Spring Cloud Alibaba.

---

请提供一下添加的 Sentinel 相关的依赖，并在簇点链路页面 打开开发者模式看看 API 返回什么，检查一下接入端的 `~/logs/csp/command-center.log` 看看有没有错误信息。

**Comment by newWSmile** [comment]
我加入了spring-boot-starter-actuator 并且在配置中加入management.endpoints.web.exposure.include=* 后正常显示了
