### ISSUE TITLE
The BUG of OccupiableBucketLeapArrayTest.testWindowAfterOneInterval()

### ISSUE THREAD

**Issue by zhaixiaoxiang** [alibaba/Sentinel#685]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

The BUG is occasional.

I wrote the analysis in the following blog:
https://www.yuque.com/zhaixiaoxiang/cwrx8f/zzy18c

### How to reproduce it (as minimally and precisely as possible)

Execute testWindowAfterOneInterval() many times, we will eventually get failure. (may be 5 times is enough)

**Comment by sczyh30** [comment]
Maybe we can refer to #546 to fix the time-based unstable test cases.
