### ISSUE TITLE
sentinel-dashboard拉取信息的持久化(Pull the persistence of information)

### ISSUE THREAD

**Issue by yfh0918** [alibaba/Sentinel#69]
目前采用全内存 + 过期方式，无法查看历史信息，是否考虑信息的持久化
至少保留接口可以让用户自己选择持久化方式
At present, the use of full memory + expired mode can not view historical information, and consider the persistence of information.
At least retaining interfaces allows users to choose their own persistence mode.

**Comment by sczyh30** [comment]
Some considerations can be found in comments of #50.
