### ISSUE TITLE
The interface cannot be called normally after the dubbo project is accessed.

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#691]
我用了Dubbo2.7.1版本，没有接入Sentinel是可以正常调用的，只要引用了Sentinel的maven包后客户端调用就异常了。

<dependencies>
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
   </dependency>

   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
   </dependency>
   
   <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>2.7.1</version>
   </dependency>

   <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
      <version>0.2.1.RELEASE</version>
   </dependency>

   <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo</artifactId>
      <version>2.7.1</version>
   </dependency>

   
   <dependency>
      <groupId>org.apache.zookeeper</groupId>
      <artifactId>zookeeper</artifactId>
      <version>3.4.14</version>
   </dependency>
   <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-framework</artifactId>
      <version>4.2.0</version>
   </dependency>
   <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-recipes</artifactId>
      <version>4.2.0</version>
   </dependency>
   <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-web-servlet</artifactId>
      <version>1.5.1</version>
   </dependency>
   <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-transport-simple-http</artifactId>
      <version>1.5.1</version>
   </dependency>
   <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-dubbo-adapter</artifactId>
      <version>1.5.1</version>
   </dependency>
   <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-annotation-aspectj</artifactId>
      <version>1.5.1</version>
   </dependency>
   <dependency>
      <groupId>com.alibaba.csp</group

**Comment by cookiejoo** [comment]
2019-04-19 18:26:32.416 ERROR 45480 --- [nio-8086-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.demo.provider.service.IMyService. Tried 3 times of the providers [10.254.115.204:20881] (1/4) from the registry 10.94.30.167:2181 on the consumer 10.254.115.204 using the dubbo version 2.7.1. Last error is: com.alibaba.dubbo.rpc.RpcContext.getContext()Lcom/alibaba/dubbo/rpc/RpcContext;] with root cause

**Comment by sczyh30** [comment]
Hi, for Dubbo 2.7.x you need to use `sentinel-apache-dubbo-adapter` instead of `sentinel-dubbo-adapter`. You can refer to the document: https://github.com/alibaba/Sentinel/wiki/Adapters-to-Popular-Framework#dubbo

Duplicate with #669

**Comment by cookiejoo** [comment]
> Hi, for Dubbo 2.7.x you need to use `sentinel-apache-dubbo-adapter` instead of `sentinel-dubbo-adapter`. You can refer to the document: https://github.com/alibaba/Sentinel/wiki/Adapters-to-Popular-Framework#dubbo
> 
> Duplicate with #669

thank you very mush
