### ISSUE TITLE
Is there an API to get metrics for other apps?

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#694]
我有一个需求是想在Dubbo中扩展路由策略，前提是根据Sentinel的Node实时报告选择最优的那个IP去调用。

所以请教一下是否有这种API？

盼复，谢谢。

**Comment by sczyh30** [comment]
Hi, Sentinel Duubo Adapter does not provide such kind of API for a specific IP instance. Sentinel Dubbo Adapter just records metrics for services and service methods.
