### ISSUE TITLE
Pass request parameters and headers to the entry of customized ProcessorSlot

### ISSUE THREAD

**Issue by ericql** [alibaba/Sentinel#697]
I want to implement custom rules，According to their own business needs. so have Sentinel provide？

**Comment by sczyh30** [comment]
Could you please illustrate your demands? Maybe you can implement a customized `ProcessorSlot` and add it to the Sentinel slot chain using SPI mechanism.

**Comment by ericql** [comment]
I want get request parameters from entry of customized ProcessorSlot

**Comment by ericql** [comment]
Not only the request parameters, but also the request header；but now I only gey sentinel context

**Comment by sczyh30** [comment]
Maybe you can pass them as parameters via `SphU.entry(name, entryType, 1, args)`, then get the parameters from `args` in your customized slot.

**Comment by ericql** [comment]
Thx，that's what I'm doing.and packaged in local repository
