### ISSUE TITLE
Support managing gateway flow rules in Sentinel dashboard

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#699]
## Issue Description

Type: *feature request*

### Describe what feature you want

Since 1.6.0, Sentinel has provided the `sentinel-api-gateway-adapter-common` module, which abstracts entity and management for gateway flow rules and customized API group definitions. It's necessary to support managing gateway flow rules and customized API group definitions via dashboard.

Note: since 1.6.0 an `appType` property field is added to identify the type of application (0 by default, gateway is 1). The heartbeat client will carry the `appType` field in the heartbeat message. The dashboard can identify the field and the "gateway rules" page is only available to the gateway services.

Discussions and contributions are welcomed~

**Comment by cdfive** [comment]
Learned from wiki and demo these days, I'd like to try it.

**Comment by sczyh30** [comment]
> Learned from wiki and demo these days, I'd like to try it.

Nice. You could refer to the pages in the cloud: https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台

Looking forward to your work!
