### ISSUE TITLE
Support Sentinel through Java agent

### ISSUE THREAD

**Issue by zhousiliang163** [alibaba/Sentinel#701]
## Issue Description

 *feature request*

### Describe what happened (or what feature you want)

Implementing code non-intrusive

**Comment by tigerMoon** [comment]
hi, can you give more details about the usage or scenarios

**Comment by ZShUn** [comment]
https://github.com/flowsphere-projects/flowsphere 可以关注一下这个项目，实现了Sentinel用Agent方式接入，近期会开源出来
