### ISSUE TITLE
Increase dashborad startup mode

### ISSUE THREAD

**Issue by shadowpriest** [alibaba/Sentinel#703]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
dashborad现在启动只能通过下载jar包，然后java -jar xx.jar的方式启动。现在许多公司走code pipline，没法直接把一个jar部署到生产环境，必须通过源码编译、生成可运行jar、生成docker镜像、部署等步骤，一步一步的才会最终部署到生产。当然，我们可以使用Sentinel的源码编译。但是这种方式还需要关注分支，有时还会有编译报错，而且每个公司的发布系统使用的项目模块都不一样。这里存在很大的障碍。

### Describe what you expected to happen

能否添加一种新的方式：maven的pom加个dashborad的依赖，然后写个main函数，就可以通过这个main函数启动dashborad了？
就类似于启动eureka server一样。

```
   <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
    </dependencies>

@SpringBootApplication
@EnableEurekaServer
public class EurekaServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(EurekaServerApplication.class, args);
    }
}

同时，也要能够做到dashborad的配置可以通过applicaton.properties文件来配置
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by shadowpriest** [comment]
现在dashboard的项目，deploy skip了：https://github.com/alibaba/Sentinel/blob/master/sentinel-dashboard/pom.xml#L160

**Comment by sczyh30** [comment]
Hi, Sentinel dashboard itself is an application so we didn't deploy it. It's recommended to clone and refactor the dashboard to meet your requirements in production. You can refer to: https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel

**Comment by jasonjoo2010** [comment]
Indeed we have such deploy pipelines for containers. And we place the repo in our internal `GitLab` as mirror. So we can synchronize it any time we want to and make any changes on new branch to generate new images. Which can be used to deploy (refresh containers) manually. So there should not be any problem joining `dashboard` to your pipelines.

**Comment by anjia0532** [comment]
my repo https://hub.docker.com/r/anjia0532/sentinel-docker
