### ISSUE TITLE
an optimize about config of rule in nacos

### ISSUE THREAD

**Issue by naah69** [alibaba/Sentinel#704]
## Issue Description
i save rules in nacos.
but when i use them.
i think it is not easy to use.
there are too many repeated config.
it should be optimized.
```properties
spring.cloud.sentinel.datasource.ds1.nacos.server-addr=172.16.9.205:32065
spring.cloud.sentinel.datasource.ds1.nacos.dataId=${spring.application.name}-sentinel-flow
spring.cloud.sentinel.datasource.ds1.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=flow

spring.cloud.sentinel.datasource.ds2.nacos.server-addr=172.16.9.205:32065
spring.cloud.sentinel.datasource.ds2.nacos.dataId=${spring.application.name}-sentinel-degrade
spring.cloud.sentinel.datasource.ds2.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade
```

### Describe what happened (or what feature you want)
it can be optimized.
for example：

#### ignore the repeated config
```properties
spring.cloud.sentinel.datasource.ds1.nacos.server-addr=172.16.9.205:32065
spring.cloud.sentinel.datasource.ds1.nacos.dataId=${spring.application.name}-sentinel-flow
spring.cloud.sentinel.datasource.ds1.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=flow

spring.cloud.sentinel.datasource.ds2.nacos.dataId=${spring.application.name}-sentinel-degrade
spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade
```
or

#### change the the way of config,make all types can be in the same json
```properties
spring.cloud.sentinel.datasource.ds1.nacos.server-addr=172.16.9.205:32065
spring.cloud.sentinel.datasource.ds1.nacos.dataId=${spring.application.name}-sentinel-flow
spring.cloud.sentinel.datasource.ds1.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=all
```

### Describe what you expected to happen

optimize

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. We'll improve this in next version of Spring Cloud Alibaba Sentinel. @fangjian0423

**Comment by fangjian0423** [comment]
hi @naah69 

Now `groupId` is optional, default value is `DEFAULT_GROUP`. It seems the `server-addr` can use the common configuration item, like this:

```

spring.cloud.sentinel.datasource.nacos.server-addr=172.16.9.205:32065

spring.cloud.sentinel.datasource.ds1.nacos.dataId=${spring.application.name}-sentinel-flow
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=flow

spring.cloud.sentinel.datasource.ds2.nacos.dataId=${spring.application.name}-sentinel-degrade
spring.cloud.sentinel.dtasource.ds2.nacos.rule-type=degrade

```

**Comment by naah69** [comment]
@fangjian0423 thanks for reply

**Comment by fangjian0423** [comment]
> @fangjian0423 thanks for reply

The rule-type for all rules can not be supported because it is restricted in Sentinel, how @sczyh30 think about this?

**Comment by naah69** [comment]
> > @fangjian0423 thanks for reply
> 
> The rule-type for all rules can not be supported because it is restricted in Sentinel, how @sczyh30 think about this?

the syntax format of Sentinel is JSON.
what i want just is made all kinds of rule-type can be in the single file.
can it be implemented?

**Comment by sczyh30** [comment]
Sentinel does not restrict the approach of parsing rules from JSON string, so you can implement the `Converter` that parse the flow rule from the single JSON. However, it's recommended to store different rules in different path.

**Comment by CarpenterLee** [comment]
Dynamic rules config will take effect when we invoke `register2Property()` method in `FlowRuleManager` or `DegradeRuleManager`. So whether storing multi kinds of rules in the same file is not relevant, only if `ReadableDataSource` and related `Converter` is properly implemented.

If you like, you could store all kinds of rules in one nacos dataId, and provide multi `Converter` for different RuleManager, each converter parses the part that cares.

**Comment by fangjian0423** [comment]
> Dynamic rules config will take effect when we invoke `register2Property()` method in `FlowRuleManager` or `DegradeRuleManager`. So whether storing multi kinds of rules in the same file is not relevant, only if `ReadableDataSource` and related `Converter` is properly implemented.
> 
> If you like, you could store all kinds of rules in one nacos dataId, and provide multi `Converter` for different RuleManager, each converter parses the part that cares.

As @CarpenterLee said, if we saved rules in same dataId in nacos, the configurations will be like this:

```
spring.cloud.sentinel.datasource.nacos.server-addr=172.16.9.205:32065

spring.cloud.sentinel.datasource.ds1.nacos.dataId=${spring.application.name}-sentinel-rules
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=flow

spring.cloud.sentinel.datasource.ds2.nacos.dataId=${spring.application.name}-sentinel-rules
spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade
```

But now in spring-cloud-alibaba-sentinel, the default `Converter` will throw exception when the size of json array is not equals with the size of converted rules array. So you could using your custom `Converter`.

It's recommended to store different rules in different dataId. It's easy to maintain and clearly to watch.
