### ISSUE TITLE
Can we integrate multiple data sources in dashboard?

### ISSUE THREAD

**Issue by finefuture** [alibaba/Sentinel#707]
## Issue Description

feature request

### Describe what happened (or what feature you want)

I want to integrate multiple data sources in dashboard, if we have some projects using apollo, some projects using nacos, or some other data sources. It would be easier to manage if they were all integrated, rather than being able to perceive changes in project rules only through SentinelApiClient as it is now, and how to push them to these configuration centers after dashboard changed the rules, all of which need to be improved.

**Comment by CarpenterLee** [comment]
We recommend persisting rules to some configuration center in the production environment. Which configuration center to use depends on your best practice.
Correspondingly, the client also needs to be modified to listen to the specific configuration center.
Refer to [在生产环境中使用-Sentinel](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel) for more detail.

**Comment by finefuture** [comment]
How do you persist to the configuration center? Can the rules modified by the console be persisted to the configuration center? If I use apollo, I can only modify it manually by apollo, but not by console.
