### ISSUE TITLE
Production environment console deployment issues

### ISSUE THREAD

**Issue by jayslife0** [alibaba/Sentinel#711]
配置中心控制台生产部署的话，如果要部署多台服务器集群，部署方案是怎样？多台服务器控制台之间是怎样协同呢？

**Comment by CarpenterLee** [comment]
You can refer to this wiki [在生产环境中使用-Sentinel](https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel) for more detail.

**Comment by sczyh30** [comment]
You can also refer to #241 and #363
