### ISSUE TITLE
spring-cloud-starter-alibaba-sentine support  is too old for 1.6

### ISSUE THREAD

**Issue by helei810304** [alibaba/Sentinel#713]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.1.1.RELEASE</version>
        </dependency>

项目依赖这个starter，但是这个东西，sentienl只支持到 1.4.2，并且和1.6 的控制台不兼容。

springboot的项目，如果不用 starter，能否有文档

**Comment by sczyh30** [comment]
Hi, you can try to upgrade to `0.1.2.RELEASE` according to the document [here](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).

**Comment by helei810304** [comment]
i wanna to user sentinel without  springboot-sentinel-starter ,is any way to config ?

**Comment by helei810304** [comment]
我们需要对sentinel 做二次开发，所以不能依赖 starter的封装（封装的太死了），基于springCloud  的。。
能否有文档说明下，不依赖starter如何部署

**Comment by sczyh30** [comment]
- For annotation support, you can refer to: https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-annotation-aspectj
- For web servlet support, Spring WebFlux support and Spring Cloud Gateway support, you can refer to: https://github.com/alibaba/Sentinel/wiki/主流框架的适配
- For Spring RestTemplate and Feign integration, you can refer to the implementation in Spring Cloud Alibaba.
