### ISSUE TITLE
choose the priority of flow-control local mode and cluster mode

### ISSUE THREAD

**Issue by pingan365** [alibaba/Sentinel#715]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

i can use command below to find flow control rule in use
http://ip:port/getRules?type=flow

how can i know which mode is in using now

how can i decide flow-control priority of local mode or cluster mode

### Describe what you expected to happen
there need a way to choose priority of flow control cluster mode or local mode 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

jdk 1.8
sentinel 1.4.2

**Comment by sczyh30** [comment]
Sentinel support multiple rules for the same resource. When there are both cluster and normal flow rules, the normal flow rules will be checked before the cluster flow rules.
