### ISSUE TITLE
Why is this used ？ Map.put

### ISSUE THREAD

**Issue by smallh0a1n1d0s** [alibaba/Sentinel#717]
```java
    
CtSph:

ProcessorSlot<Object> lookProcessChain(ResourceWrapper resourceWrapper) {
        ProcessorSlotChain chain = chainMap.get(resourceWrapper);
        if (chain == null) {
            synchronized (LOCK) {
                chain = chainMap.get(resourceWrapper);
                if (chain == null) {
                    // Entry size limit.
                    if (chainMap.size() >= Constants.MAX_SLOT_CHAIN_SIZE) {
                        return null;
                    }

                    chain = SlotChainProvider.newSlotChain();
                    Map<ResourceWrapper, ProcessorSlotChain> newMap = new HashMap<ResourceWrapper, ProcessorSlotChain>(
                        chainMap.size() + 1);
                    newMap.putAll(chainMap);
                    newMap.put(resourceWrapper, chain);
                    chainMap = newMap;
                }
            }
        }
        return chain;
    }

AbstractMap :

public void putAll(Map<? extends K, ? extends V> m) {
        for (Map.Entry<? extends K, ? extends V> e : m.entrySet())
            put(e.getKey(), e.getValue());
    }
```

**Comment by sczyh30** [comment]
Hi, could you please illustrate your question?

**Comment by smallh0a1n1d0s** [comment]
No problem yet . But I think this is a performance issue, especially since sentinel has a large number of **Map** that are global and each additional child element is too much work

**Comment by sczyh30** [comment]
Sentinel will only update the slot chain map at the first invocation of one resource, which will not happen frequently (read operations >> update operations). So we replace the volatile `HashMap` here instead of using `ConcurrentHashMap` directly.

**Comment by smallh0a1n1d0s** [comment]
That is clever to replace volatile HashMap instead of using ConcurrentHashMap  directly  for more read opers.
But, Why  do we need to put in a new HashMap recursively  by **newMap.putAll**  ?  How about to put new element in old volatile HashMap synchronously ?

**Comment by codePlanter** [comment]
If you still feel confused, check this article [A technique that improves performance for applications with infrequently updated read-write maps](https://www.ibm.com/developerworks/library/j-hashmap/index.html)
btw, if you want to find more, try to search "volatile-read, synchronized-write technique", which is described by Brian Goetz
