### ISSUE TITLE
Can I use pull-based dynamic data source for rule management in cluster flow control?

### ISSUE THREAD

**Issue by xiaominger** [alibaba/Sentinel#720]
can  I use **pull mode**  when cluster flow control

**Comment by sczyh30** [comment]
Hi, Sentinel does not restrict the implementation of dynamic data source, but it's recommended to use **push-based** data source (like ZooKeeper, Nacos) to receive changes in real-time.

**Comment by xiaominger** [comment]
now it's only a small zuul gateway, push based mode is a little complicated, I should have to implement the zookeeper client, or redis client, to push the rule data to config center.

**Comment by sczyh30** [comment]
You can refactor the dashboard to support pushing rules via the dashboard. You could refer to this document (CN): https://github.com/alibaba/Sentinel/wiki/控制台#62-规则推送
