### ISSUE TITLE
How to use FileDataSource  for rule management in cluster flow control?

### ISSUE THREAD

**Issue by xiaominger** [alibaba/Sentinel#721]
How to use FileDataSource  for rule management in cluster flow control?

**Comment by sczyh30** [comment]
Hi, there's no difference for cluster flow control. You can just refer to the document:

- [FileDataSource](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%8B%89%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99)
- [Rule management for cluster flow rules](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7#%E9%9B%86%E7%BE%A4%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F)

If you're not using the dashboard to push the rules, be sure to take care of the `flowId` in cluster flow rule.

**Comment by xiaominger** [comment]
> Hi, there's no difference for cluster flow control. You can just refer to the document:
> 
> * [FileDataSource](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%8B%89%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99)
> * [Rule management for cluster flow rules](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7#%E9%9B%86%E7%BE%A4%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F)
> 
>

**Comment by sczyh30** [comment]
You should register rule data source for `FlowRuleManager` at client side and `ClusterFlowRuleManager` at token server side. You can refer to the document I've provided before: [Rule management for cluster flow rules](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7#%E9%9B%86%E7%BE%A4%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F)
