### ISSUE TITLE
SphU & SphO means?

### ISSUE THREAD

**Issue by zhangwanly** [alibaba/Sentinel#722]
What SphU & SphO exactly mean?
I don't think it's a friendly class name.
O 0 0 O 00 OO
interesting！

**Comment by sczyh30** [comment]
Hi, it's a (legacy) magic name. You can refer to #489.

**Comment by WineChord** [comment]
Let's see what GPT4 says:

> "SphU" in Sentinel stands for "Sentinel Protect Hub Utils". It's a utility class that provides static methods to enter a protected resource. The name "SphU" is likely chosen for its brevity and the fact that it represents the main functionality of the class, which is to provide a hub for Sentinel's protection mechanisms.

> "SphO" in Sentinel stands for "Sentinel Protect Hub Object". Similar to "SphU", it's a utility class that provides static methods to enter a protected resource. However, the difference lies in the way exceptions are handled.

> While "SphU" throws a BlockException when a resource is blocked, "SphO" returns a result object (Entry) which can be used to check whether the resource is blocked or not. This allows for a different way of handling blocked resources, where instead of dealing with exceptions, you can check the status of the Entry object and decide what to do next.

> So, the naming "SphO" is likely chosen to represent its role as an Object-oriented hub for Sentinel's protection mechanisms, providing a different way of handling resource entries compared to "SphU".
