### ISSUE TITLE
Feign uses inheritance, SentinelInvocationHandler 93 lines MethodMetadata gets empty

### ISSUE THREAD

**Issue by george510257** [alibaba/Sentinel#724]
当spring cloud 中使用 openfeign方式调用时，使用feign的继承特性。在使用Sentinel作为熔断限流时会导致MethodMetadata获取值为null。

详细代码参见：https://gitee.com/george510257/csg-parent.git

继承结构
![image](https://user-images.githubusercontent.com/4056671/57065265-78282a00-6cfb-11e9-8a38-898b1a2691c0.png)

报错信息
![image](https://user-images.githubusercontent.com/4056671/57065304-9726bc00-6cfb-11e9-94d3-71ee3fc9fd61.png)

![image](https://user-images.githubusercontent.com/4056671/57065380-cd643b80-6cfb-11e9-8bb3-9a65870f9644.png)

版本是用的0.9.0.RELEASE

**Comment by sczyh30** [comment]
@fangjian0423 Could you please take a look on it?

**Comment by george510257** [comment]
抱歉，我这边已经在spring-cloud-incubator/spring-cloud-alibaba提交了issues。这边属于重复了。建议关闭。

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/626
