### ISSUE TITLE
Add version info in dashboard

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/Sentinel#728]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

Add version info in the left top of dashboard, like this:

Sentinel 控制台 1.6.0

Then i can know which version i am using in dashboard and don't need to get it with other ways.

**Comment by sczyh30** [comment]
Hi, thanks for your suggestion. Maybe we can add the version info in the index page.

**Comment by hisenyuan** [comment]
hello,i will add sentinel version in the index page.

**Comment by sczyh30** [comment]
> hello,i will add sentinel version in the index page.

Nice, looking forward to your pull request!

**Comment by hisenyuan** [comment]
`sentinel-dashboard/pom.xml`
I think sentinel dashboard version is the same as sentinel-parent, so I'll get it.
Do you agree with me?

**Comment by sczyh30** [comment]
> `sentinel-dashboard/pom.xml`
> I think sentinel dashboard version is the same as sentinel-parent, so I'll get it.
> Do you agree with me?

That's okay.

**Comment by hisenyuan** [comment]
> > `sentinel-dashboard/pom.xml`
> > I think sentinel dashboard version is the same as sentinel-parent, so I'll get it.
> > Do you agree with me?
> 
> That's okay.

https://github.com/alibaba/Sentinel/pull/800

**Comment by sczyh30** [comment]
The backend API (GET `/version`) has been added by @hisenyuan via #800. Contributions for frontend are welcomed!

**Comment by zhaoyuguang** [comment]
Hi will try to finish `the frontend part`

**Comment by sczyh30** [comment]
Frontend resolved by #1015
