### ISSUE TITLE
Sentinel needs to support streaming by IP.

### ISSUE THREAD

**Issue by yikangfeng** [alibaba/Sentinel#729]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by yikangfeng** [comment]
> > Hi @yikangfeng, we detect non-English characters in the issue. This comment is an auto translation from @sentinel-bot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # Sentinel needs to support streaming by IP.
> ## Issue Description
> Type: _bug report_ or _feature request_
> 
> ### Describe what happened (or what feature you want)
> ### Describe what you expected to happen

1. 有一些老的上游服务，是比较核心的服务，调用下游服务，不会传递任何参数，也没人敢重构老的服务，这个时候下游服务要限流，需要按照IP进行限流，这样上游服务不用任何修改，下游服务也可以很好的进行限流。
2.作为一个通用的限流框架来说，还是需要灵活的支持多种限流场景。

> ### How to reproduce it (as minimally and precisely as possible)
> 
> ### Tell us your environment
> ### Anything else we need to know?

**Comment by CarpenterLee** [comment]
Could you please describe more clearly? What kind of resource do you want to protect, Dubbo or Web service? 
By now if you want to distinguish IP as flow control field, you may first parse the IP address by hand, then define resource by [Sentinel API](https://github.com/alibaba/Sentinel#2-define-resource), and pass the IP as params of the entry. And use `ParamFlowRule` to limit each distinct IP. Refer [热点参数限流](https://github.com/alibaba/Sentinel/wiki/%E7%83%AD%E7%82%B9%E5%8F%82%E6%95%B0%E9%99%90%E6%B5%81) for detail.

**Comment by linlinisme** [comment]
如果单对IP限流，粒度太粗，效果难以保证，并且应用情景应该不多。
有一种方案就是对下游服务再做一层简单的封装，以便区分出不同的服务。然后再套用现有的限流规则

**Comment by sczyh30** [comment]
For API gateway you can leverage the API gateway flow control. For customized web applications you could imitate the implementations of API gateway flow control and implement your own filter.
