### ISSUE TITLE
加强 Sentinel Dashboard UI 建设

### ISSUE THREAD

**Issue by chunericli** [alibaba/Sentinel#73]
## Issue Description
![image](https://user-images.githubusercontent.com/14007925/44305513-db5f6f80-a3ab-11e8-9287-b8138228ee34.png)

Type: *bug report*

### Describe what happened (or what feature you want)

- Wrong representation for long app name in left sidebar
- Wrong offset for QPS graph in monitoring page

眼睛鼻子挤在一起，全限定名称看不到，内容展示不够饱满

虽然本地开启多个应用，但是机子是一台，是否考虑可以一条记录即可，然后根据类型选择区分；
可以多弄些维度选择

### Describe what you expected to happen
能灵活配置就灵活配置吧，不能就算了

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jasonjoo2010** [comment]
fixed on #172 

项目个数是通过appName来进行分组的

**Comment by sczyh30** [comment]
Closing this as this has been fixed in #172.
