### ISSUE TITLE
delete all rules，NodeCacheListener can not listen

### ISSUE THREAD

**Issue by haofangyuan** [alibaba/Sentinel#731]
### delete all rules，NodeCacheListener can not listen

[FlowRuleZookeeperPublisher.java](https://github.com/alibaba/Sentinel/blob/master/sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/rule/zookeeper/FlowRuleZookeeperPublisher.java)：
   add a flow control rule to the dashboard , NodeCacheListener can listen, but after deleting the flow control rule, because there are no rules, write an empty string into zk, NodeCacheListener can not listen.

### code

```java
byte[] data = CollectionUtils.isEmpty(rules) ? "".getBytes() : converter.convert(rules).getBytes();
```

### Tell us your environment

zookeeper version：3.4.14
curator-recipes：2.9.0

### Anything else we need to know?

`"[]".getBytes()`  is OK

**Comment by sczyh30** [comment]
Hi, thanks for reporting. Would you like to contribute a PR? You can refer to the contribution guidelines [here](https://github.com/alibaba/Sentinel/wiki/开源贡献指南).

**Comment by haofangyuan** [comment]
> Hi, thanks for reporting. Would you like to contribute a PR? You can refer to the contribution guidelines [here](https://github.com/alibaba/Sentinel/wiki/%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97).
Of course I would, thanks
