### ISSUE TITLE
ZuulBlockFallbackProvider ResponseBody Chinese garbled

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/Sentinel#733]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

ZuulBlockFallbackProvider ResponseBody 中文乱码

### Describe what you expected to happen

支持中文message

### How to reproduce it (as minimally and precisely as possible)

1. 增加一行 ctx.getResponse().setContentType("application/json; charset=utf-8");即可
![image](https://user-images.githubusercontent.com/17271895/57205996-0c90d600-6ff5-11e9-9267-7133c40e834e.png)

### Tell us your environment

sentinel-zuul-adapter 1.6.0版本

**Comment by sczyh30** [comment]
Hi, thanks for reporting. It's a bug. Would you like to contribute a PR?

**Comment by yinjihuan** [comment]
Can you reply in Chinese? English is not very good

**Comment by sczyh30** [comment]
> Can you reply in Chinese? English is not very good

欢迎参与贡献，提交一个 PR 修复此 bug。可以参考贡献指南：https://github.com/alibaba/Sentinel/wiki/开源贡献指南

**Comment by yinjihuan** [comment]
可以的，我晚点处理下

**Comment by yinjihuan** [comment]
请问下CLA怎么签署? 是下载个人贡献那个pdf，打印成纸质的，签完拍照发邮箱吗？

**Comment by yinjihuan** [comment]
提交了PR  https://github.com/alibaba/Sentinel/pull/737
