### ISSUE TITLE
[Bug]Entry auto close will lead wrong biz Exception tracing

### ISSUE THREAD

**Issue by CarpenterLee** [alibaba/Sentinel#734]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Since 1.5.0 Sentinel supports try-with-resources of `Entry`, this will lead wrong biz Exception tracing. As the flowing code shows: 
```java
try (Entry entry = SphU.entry("HelloWorld")) {
    // Your business logic here.
    System.out.println("hello world");
    throw new RuntimeException("bizException");
} catch (BlockException e) {
    // Handle rejected request.
    e.printStackTrace();
} catch (Exception e2) {
    // biz exception
    Tracer.trace(e2); // can't trace the e2 properly, because entry has already exited here.
}
```
In the above code, `e2` can't be traced properly, because `entry.close()` will be invoked prior to the catch block, this will lead wrong biz Exception tracing.

### How to reproduce it (as minimally and precisely as possible)
Run the above code, you will see `Tracer.trace(e2)` did not take effect.

**Comment by linlinisme** [comment]
我这边试了，Tracer可以捕捉到Exception e2
![image](https://user-images.githubusercontent.com/8200692/57509002-aa5a0d00-7335-11e9-90ce-478559abc068.png)

**Comment by CarpenterLee** [comment]
> 我这边试了，Tracer可以捕捉到Exception e2
> 
> ![image](https://user-images.githubusercontent.com/8200692/57509036-c52c8180-7335-11e9-9813-6277c2ad95c0.png)

Emm, bizException will be caught by try-catch block, but the catch block is executed behind auto closable `entry.close()`, this will lead `e2` being traced in the wrong context.

**Comment by linlinisme** [comment]
你说的错误上下文是指entry的上下文还是资源的上下文？

**Comment by 1522140840** [comment]
good

**Comment by cdfive** [comment]
@linlinisme 
一个entry对应一个资源。
```
In a try-with-resources statement, any catch or finally block is run after the resources declared have been closed.
```
这里因为JDK机制，`entry.close()`在`Tracer.trace(e2)`之前执行，demo中当前context就是null了，
这个断点进去后判断context为null的话就返回了。


@CarpenterLee 
想到个思路：
外面申明个临时变量entry1，用它保存entry，然后用
`traceEntry(Throwable e, Entry entry)`来trace
```java
Entry entry1 = null;
try (Entry entry = SphU.entry("HelloWorld")) {
    entry1 = entry;
    // Your business logic here.
    System.out.println("hello world");
    throw new RuntimeException("bizException");
} catch (BlockException e) {
    // Handle rejected request.
    e.printStackTrace();
} catch (Exception e2) {
    // biz exception
    // Tracer.trace(e2); // can't trace the e2 properly, because entry has already exited here.
    Tracer.traceEntry(e2, entry1); // use traceEntry method to trace
}
```

不知这样是否可行，但这个写法确实太繁琐了。。暂时没找到好的方法。
有点奇怪为什么JDK的`try-with-resource`采取这样的顺序机制，为何不catch后再执行close
JDK9支持`try-with-resource`中不用定义新变量了，但是好像顺序还是这样的。
如果这顺序机制没法改变的话，Sentinel这里trace的场景用这个语法就得注意了。
如果不用trace的场景，比如qps限流，应该没问题。

这是学习查找的资料: 
* [https://docs.oracle.com/javase/8/docs/technotes/guides/language/try-with-resources.html](https://docs.oracle.com/javase/8/docs/technotes/guides/language/try-with-resources.html)

* 在 JDK 9 中更简洁使用 try-with-resources 语句
[http://www.importnew.com/21544.html](http://www.importnew.com/21544.html)

**Comment by sczyh30** [comment]
Yes, for this kind of scenarios, try-with-resources Entry won't work as expected and should not be used. The try-with-resources sugar is only useful for basic scenarios (without tracing biz exceptions and parameters).

**Comment by sczyh30** [comment]
This can't be resolved well so we should add more notes in the document to inform users.
