### ISSUE TITLE
2019 Alibaba Summer of Code

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#738]
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

**Alibaba Summer of Code** is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world. Alibaba Summer of code will begin between June 28th and September 20th. Students can use the summer time to participate in the open source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open source project!

## Our Mentor

- Jialiang Lin ([@jialianglinjl](https://github.com/jialianglinjl)), Alibaba Cloud Staff Engineer, Sentinel PMC, the leader of Sentinel project
- Eric Zhao ([@sczyh30](https://github.com/sczyh30)), Sentinel PMC
- Carpenter Lee ([@CarpenterLee](https://github.com/CarpenterLee)), Sentinel PMC

## Apply Now!

Idea list:

https://github.com/alibaba/Sentinel/labels/SoC2019

You can click on this link to apply directly:

- English: https://developer.aliyun.com/special/summerofcode2019en
- Chinese: https://developer.aliyun.com/special/summerofcode2019

## Timeline⏳

![image](https://user-images.githubusercontent.com/9434884/57374623-e4a89a80-71cd-11e9-90a3-90e55b80da60.png)

## Contact us!

Email Address: aliopensource@alibabacloud.com

**Comment by prondubuisi** [comment]
@sczyh30 does this internship have a one stop homepage/wepage? where I can get every information about it?

**Comment by radicalswetank** [comment]
@prondubuisi 
https://developer.aliyun.com/summerofcode2019

**Comment by sczyh30** [comment]
@prondubuisi @radicalswetank Hi, for idea list about Sentinel you can refer to: https://github.com/alibaba/Sentinel/labels/SoC2019
The official website of Alibaba Summer of Code: https://developer.aliyun.com/summerofcode2019
Feel free to contact us via aliopensource@alibabacloud.com

**Comment by prondubuisi** [comment]
Thanks @sczyh30  @radicalswetank

**Comment by sczyh30** [comment]
👏Hi community, for students who are planning to take part in Alibaba Summer of Code 2019, please keep in mind the deadline of proposal submission is this Friday (**June 14th**). You can submit the proposal via the official website: https://developer.aliyun.com/special/summerofcode2019en

**Comment by sczyh30** [comment]
Hi community, our ASoC'19 student Li Yudong(@P01son6415) and Liu Yiming(@lym-ifae) have accomplished their ASoC task about adaptive flow control. See #1003 and #1007 for details. Further discussions are welcomed :)

**Comment by Super-long** [comment]
Haha, that looks so interseting! come on!
