### ISSUE TITLE
[RFC] Sentinel Golang version

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#739]
## Issue Description

Type: *feature request*

### Describe what feature you want

Implement Golang version of Sentinel, including basic statistic and flow functions. Some expected features:

- Basic statistic structure (sliding window that can achieve high concurrency and accuracy)
- Rate limiting (based on token bucket algorithm, maybe we can leverage `golang.org/x/time/rate.Limiter`)
- Logging
- Metrics interface that can pump real-time metrics to outside consumer
- Embedded API server
- Integrate with Sentinel dashboard (machine discovery)

Discussions are welcomed!

**Comment by TG1999** [comment]
Hi @sczyh30  I will like to work on this project in this summers under Alibaba summer of code. Can you tell me how to get started. How can I show my pro efficiency for getting selected in this project.

**Comment by louyuting** [comment]
If I want to participate in this ISSUE, What should I do?

**Comment by sczyh30** [comment]
> If I want to participate in this ISSUE, What should I do?

@louyuting Hi, it's recommended to get familiar with Sentinel first. You may refer to the [wiki](https://github.com/alibaba/Sentinel/wiki) to learn the features of Sentinel and how it works. If you have any problems, feel free to submit issues or ask in [Gitter](https://gitter.im/alibaba/Sentinel).

For Sentinel Golang native version we can first implement the basic **statistic** and **flow control** features, including the sliding window structure and token bucket algorithm (not limited). Then work with metrics log, integration with Sentinel dashboard and token client for cluster flow control. You may refer to the following wikis to get more information:

- [How to use](https://github.com/alibaba/Sentinel/wiki/How-to-Use)
- [How it works](https://github.com/alibaba/Sentinel/wiki/How-it-works)
- [Flow Control](https://github.com/alibaba/Sentinel/wiki/Flow-Control)
- [Metrics](https://github.com/alibaba/Sentinel/wiki/Metrics)
- [Dashboard](https://github.com/alibaba/Sentinel/wiki/Dashboard)

Discussions and contributions are welcomed.

**Comment by louyuting** [comment]
Ok, In recent weeks I've learned a little bit about how sentinel's local throttling works. Especially with the statistics and flow control part of the sentinel. So, completing the Sentinel Golang native version  should not be a problem.

Does I open the PR directly after I implement it?

**Comment by sczyh30** [comment]
> Ok, In recent weeks I've learned a little bit about how sentinel's local throttling works. Especially with the statistics and flow control part of the sentinel. I will try to implement it
> 
> Does I open the PR directly after I implement it?

Nice. We can first discuss your design here (or open a new issue in [sentinel-golang repo](https://github.com/sentinel-group/sentinel-golang)), then you can work on it and submit PRs to [sentinel-group/sentinel-golang](https://github.com/sentinel-group/sentinel-golang).

**Comment by louyuting** [comment]
OK~I have opened a new Issue in the [sentinel-group/sentinel-golang.](https://github.com/sentinel-group/sentinel-golang/issues/1)

**Comment by sczyh30** [comment]
See related issues in https://github.com/sentinel-group/sentinel-golang
