### ISSUE TITLE
Wrong state for SentinelResource annotation

### ISSUE THREAD

**Issue by zhoujinpen** [alibaba/Sentinel#74]
我项目中引入sentinel，通过@SentinelResource注解的方式去监控接口的，但是调用该接口时报java.lang.IllegalStateException: Wrong state for SentinelResource annotation这个错误，请问这是什么原因引起的？

**Comment by sczyh30** [comment]
Hi, can you provide a code snippet where you used `@SentinelResource` annotation?

**Comment by sczyh30** [comment]
And which version of Spring Boot your project is using?

**Comment by zhoujinpen** [comment]
springboot 1.5.3   sentinel-core 0.2.0

**Comment by sczyh30** [comment]
This may be related to #79 (occurs with Spring Boot 1.x). We'll check it.

**Comment by guyulong** [comment]
> > 目前还是报java.lang.IllegalStateException: Wrong state for SentinelResource annotation错误
> > 版本号：sentinel-annotation-aspectj-1.7.1.jar
> > spring-boot-2.2.5.RELEASE.jar
> 
> hi
> 能提供一个重现的演示项目地址吗？
springboot 2.1.11.RELEASE
springcloud Greenwich.SR4
alibaba.cloud nacos-discovery 2.1.2.RELEASE
sentinel-annotation-aspectj 1.7.2 1.8.0 都试过 也是出现了这个问题 获取注解为null
![image](https://user-images.githubusercontent.com/47616757/92450662-49bf3680-f1ee-11ea-83e4-75c4f66c4727.png)
![image](https://user-images.githubusercontent.com/47616757/92450738-5f346080-f1ee-11ea-8f85-5c504c599173.png)

**Comment by guyulong** [comment]
通过feign调用会这样， 如果直接写controller的话不会出现null的情况
