### ISSUE TITLE
Does Sentinel support default FlowRule for all resources?

### ISSUE THREAD

**Issue by shanzhaigegeyml** [alibaba/Sentinel#746]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?
Does Sentinel support default FlowRule for all resources?

**Comment by sczyh30** [comment]
Hi, Sentinel does not support default (global) rules till now. We may support this in later versions.

For more information, you can refer to #66. Discussions are welcomed.
