### ISSUE TITLE
Logging SPI for various logging libraries

### ISSUE THREAD

**Issue by shxz130** [alibaba/Sentinel#757]
the log is bad implement by  write String to assign log file，cannot we use slf4j or other implements such as we support event(EventBus or SpringApplicationEvent) to log，
is it more scalable？zhe sentinel‘s user can feel comfortable。

such as：
  EventBus.post(LogEvent log);

new  Listener(){
   doLog(){
    log.info();
  }
}

**Comment by sczyh30** [comment]
Sentinel is a fundamental component so `sentinel-core` should not depend on any third-party logging libraries (which might bring dependency conflicit).

Maybe we can make the logging interface as SPI and provide different implementations (based on JUL or slf4j). Discussions are welcomed.

**Comment by shxz130** [comment]
i'm every agree to support making the logging interface as SPI and provide different implementations

**Comment by Warkeeper** [comment]
I think Logging SPI is pretty important since I find it's impossible to control the size and the count of log file "sentinel-block.log","sentinel-record.log" and "command-center.log".(They are all hard coded in codes)

**Comment by sczyh30** [comment]
> I think Logging SPI is pretty important since I find it's impossible to control the size and the count of log file "sentinel-block.log", "sentinel-record.log" and "command-center.log".(They are all hardcoded in codes)

This can be improved. We might need more configuration items to control the different logs (e.g. record log, metric log and block log). For logging SPI we need more discussion (whether to support and how to support). @cdfive @jasonjoo2010 @linlinisme Any suggestions?

**Comment by jasonjoo2010** [comment]
Indeed it's a meaningful feature for most users. We can provide it as an SPI protocol and make several implementations in separated modules including slf4j/log4j/jcl logging system forwarder, standard console output, etc.

Certainly it will also enable users to implement it themselves.

**Comment by goudai** [comment]
能否支持采用slf4j做了日志记录框架API？

**Comment by sczyh30** [comment]
Since the logger SPI has been introduced via #1265 and #1338, we may implement extension modules for popular logging libraries. Contributions are welcomed!

Umbrella issue: #1295
