### ISSUE TITLE
Support result caching and retrying in Sentinel annotation support

### ISSUE THREAD

**Issue by Godhuu** [alibaba/Sentinel#760]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, could you please illustrate the details of your requirement?

**Comment by Godhuu** [comment]
如果我要对资源（SentinelResource）的返回结果进行缓存和对失败重试的话，应该如何配置？

**Comment by sczyh30** [comment]
Result caching and automatic retrying have not been supported in Sentinel annotation support till now. That's a good idea. Discussions and contributions are welcomed!

**Comment by jasonjoo2010** [comment]
I think it's a RPC framework's problem like DUBBO/gRPC.
Especially for caching. Or sentinel will become another MVC/RPC framework including guarding functions.

**Comment by sczyh30** [comment]
Retrying might be needed for resilience design. Result caching should not be the responsibility of Sentinel.

**Comment by jasonjoo2010** [comment]
@shxz130 
I think the discussion is complete and should be closed.
