### ISSUE TITLE
Support inclusive or exclusive Exception types in exception tracing

### ISSUE THREAD

**Issue by CarpenterLee** [alibaba/Sentinel#761]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Exception statistics are the basis for degradation or circuit breaker, and `Tracer.trace()` will trace any exception besides `BlockException`, this means any kinds of exception except for BlockException will have an effect on degradation. 

Sometimes we may want to ignore some kind of exceptions in the statistics.

### Describe what you expected to happen

Support inclusive or exclusive Exception types in exception tracing.

**Comment by sczyh30** [comment]
Good idea. We need a universal property for the list of exceptions that will not be traced as *exception count*.

For annotation users, since 1.6.0 Sentinel has provided `exceptionsToIgnore` and `exceptionsToTrace` attribute in `@SentinelResource`, which we can leverage to achieve this.

**Comment by duwei54** [comment]
Is there a global configuration for set exceptions that will not be traced as exception count?

**Comment by sczyh30** [comment]
> Is there a global configuration for set exceptions that will not be traced as exception count?

A pending PR is here: #766

**Comment by duwei54** [comment]
@sczyh30 thanks! :smile:
I just thought of a scene:  I want skip some response http status like 400, 403 and so on.
Can this feature be supported?
