### ISSUE TITLE
Sentinel-dashboard cluster flow add token server save failed

### ISSUE THREAD

**Issue by wuxiantian** [alibaba/Sentinel#762]
## Issue Description

![image](https://user-images.githubusercontent.com/10464435/57766569-27bcbd80-773a-11e9-9057-0641ba13340b.png)
Sentinel-dashboard version is 1.6.0 
sentinel-dashboard console:
![image](https://user-images.githubusercontent.com/10464435/57766684-65b9e180-773a-11e9-8f5f-6e3517d1072a.png)
I started the test application locally and started it with 2 ports: 8001 and 8002
![image](https://user-images.githubusercontent.com/10464435/57768095-77e94f00-773d-11e9-9303-0e6238945d9b.png)
POM.xml
![image](https://user-images.githubusercontent.com/10464435/57767275-86cf0200-773b-11e9-9447-028dcf6cead7.png)

Excuse me, is there any configuration missing?

**Comment by sczyh30** [comment]
@wuxiantian Hi, is this problem resolved?

**Comment by wuxiantian** [comment]
> @wuxiantian Hi, is this problem resolved?

Yes, it has been solved

**Comment by wuxiantian** [comment]
> @wuxiantian Hi, is this problem resolved?

Yes, it has been solved. Version problem

**Comment by Yisaki** [comment]
@wuxiantian hi,I meet the same problem as you,can you share the solution of the problem?
