### ISSUE TITLE
Question about the order of SentinelGatewayFilter in Spring Cloud Gateway

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/Sentinel#764]
## Issue Description

Type: bug report

### Describe what happened

```java
// LoadBalancerClientFilter#filter
if (instance == null) {
    throw NotFoundException.create(properties.isUse404(),
        "Unable to find instance for " + url.getHost());
}
```
The order of `LoadBalancerClientFilter` is higher than `SentinelGatewayFilter`. So it won't invoke `SentinelGatewayFilter` after `LoadBalancerClientFilter` throw `NotFoundException` if there is no healthy instance.

![image](https://user-images.githubusercontent.com/5254035/57821838-96def400-77c4-11e9-9358-eb2d00d6ecfc.png)

Is it necessary to set the higher order for `SentinelGatewayFilter`?

There is another case:

![image](https://user-images.githubusercontent.com/5254035/57821896-d86f9f00-77c4-11e9-8edd-32926a9121b9.png)

Spring Cloud Gateway will using `NoLoadBalancerClientFilter` to replace of `LoadBalancerClientFilter` if there is no xx-discovery-starter in pom.

This case has the same problem.

**Comment by sczyh30** [comment]
Yes, the order of the filters should be well arranged. In the [demo](https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-spring-cloud-gateway) we set the order of `SentinelGatewayFilter` to -1. Maybe we can put it ahead (the highest precedence?).

**Comment by fangjian0423** [comment]
@sczyh30 

It seems we should implement `org.springframework.core.Ordered` interface, not the `org.springframework.core.annotation.Order` annotation.

**Comment by cui1100** [comment]
@sczyh30
I copy the SentinelGatewayFilter and Ordered before my filters,bu even though the sentinel limit the flow ,my filters would excute ,then it throws exception of Blocked by Sentinel?
How could i modify the SentinelGatewayFilter.java ?

**Comment by evilester** [comment]
spring-cloud-gateway-starter-ahas-sentinel:1.0.1

SentinelGatewayAutoConfiguration.java 
    @Bean
    @Order(-1)
    public GlobalFilter sentinelGatewayFilter() {
        return new SentinelGatewayFilter();
}

Odrer is invalid here

FilteringWebHandler.java
	public Mono<Void> handle(ServerWebExchange exchange) {
		Route route = exchange.getRequiredAttribute(GATEWAY_ROUTE_ATTR);
		List<GatewayFilter> gatewayFilters = route.getFilters();

		List<GatewayFilter> combined = new ArrayList<>(this.globalFilters);
		combined.addAll(gatewayFilters);
		// TODO: needed or cached?
		AnnotationAwareOrderComparator.sort(combined); //Here not 

		if (logger.isDebugEnabled()) {
			logger.debug("Sorted gatewayFilterFactories: " + combined);
		}

![image](https://user-images.githubusercontent.com/4954490/60170785-c78e6080-983b-11e9-84f6-c05458d8074d.png)

Maybe SentinelGatewayFilter need the delegation of OrderedGatewayFilter and SentinelGatewayFilter should implement org.springframework.core.Ordered
