### ISSUE TITLE
[Optimal] Replacing the threadlocal for performance

### ISSUE THREAD

**Issue by zdhuangelephant** [alibaba/Sentinel#767]
First it's not a issue what i say, i think it's a ptimal point that provide an alternative to performance，
the code below:

org.apache.dubbo.common.threadlocal.InternalThreadLocal to replace ThreadLocal
and it reference from {@see io.netty.util.concurrent.FastThreadLocal} which is in Netty.

`public class ContextUtil {

    /**
     * Store the context in ThreadLocal for easy access.
     */
    private static ThreadLocal<Context> contextHolder = new ThreadLocal<>();
.....
}`

as you know , dubbo it just do it

**Comment by sczyh30** [comment]
Good idea, but maybe this is not the bottleneck :)
