### ISSUE TITLE
When the system current limit occurs, the current CPU usage value cannot be obtained when sending a custom alarm.

### ISSUE THREAD

**Issue by yikangfeng** [alibaba/Sentinel#769]
## Issue Description

Type: feature request

When the system current limit occurs, the current CPU usage value cannot be obtained when sending a custom alarm.

### Describe what happened (or what feature you want)

When the system current limit occurs, the current CPU usage value cannot be obtained when sending a custom alarm.

### Describe what you expected to happen

When the system current limit occurs, send a custom alarm to get the current CPU usage value.

### How to reproduce it (as minimally and precisely as possible)

1. The getHighest CpuUsage method is added to the SystemRuleManager class
2. 
3. 

### Tell us your environment
1.6.0

**Comment by sczyh30** [comment]
I think if you're going to retrieve the current CPU usage and load of your system, you may get them via:

```java
SystemRuleManager.getCurrentCpuUsage();
SystemRuleManager.getCurrentSystemAvgLoad()
```

The `highestCpuUsage` is only the threshold of the `SystemRule`, not the real-time value.
