### ISSUE TITLE
我的Sentinel项目启动后，并没有8719这个端口。怎么设置呢？

### ISSUE THREAD

**Issue by aBreaking** [alibaba/Sentinel#77]

**Comment by sczyh30** [comment]
Hi, please check whether you've added `sentinel-transport-simple-http` or `sentinel-transport-netty-http` dependency. Please refer to the document [here](https://github.com/alibaba/Sentinel/wiki/%E6%8E%A7%E5%88%B6%E5%8F%B0#3-%E5%BA%94%E7%94%A8%E6%8E%A5%E5%85%A5%E6%8E%A7%E5%88%B6%E5%8F%B0).

**Comment by aBreaking** [comment]
Thank you! I got it。
