### ISSUE TITLE
Can not use json file define apiDefination

### ISSUE THREAD

**Issue by tianbing0729** [alibaba/Sentinel#772]
Customize API definitions through the Nacos registry.
GatewayApiDefinitionManager cannot parse JSON and cannot recognize predicateItems content

"sentinel.api.define" :
[
    {
        "apiName": "csii",
        "predicateItems": 
            [
                {
                    "pattern": "/bb/csii/**",
                    "matchStrategy": 1
                }
            ]
    }
]

code：
ReadableDataSource<String, Set<ApiDefinition>> apiDefinitionDataSource = new NacosDataSource<>(properties, "GATEWAY", "sentinel.api.define",
                source -> JSON.parseObject(source, new TypeReference<Set<ApiDefinition>>() {}));

GatewayApiDefinitionManager.register2Property(apiDefinitionDataSource.getProperty());

logs：
2019-05-17 10:30:13 [DynamicSentinelProperty] Config will be updated to: [ApiDefinition{apiName='csii', predicateItems=[{}, {}]}]
2019-05-17 10:30:13 [GatewayApiDefinitionManager] Api definition updated: {csii=ApiDefinition{apiName='csii', predicateItems=[{}, {}]}}

**Comment by yanjuning** [comment]
- reason

  The fields of  class `ApiDefinition`  are as follows. Because `ApiPredicateItem` is a generic type, FastJson resolves field `predicateItems` to `NULL` value by default. 

  ```java
  public class ApiDefinition {
      private String apiName;
      private Set<ApiPredicateItem> predicateItems;
      /** getters and setters **/   
  }
  ```

- Solution

  Use `@type` to specify the actual type
  > refer  to https://github.com/alibaba/fastjson/wiki/JSONType_seeAlso_cn

  ```json
  [
      {
          "apiName": "csii",
          "predicateItems":
              [
                  {
                      "@type": "com.alibaba.csp.sentinel.adapter.gateway.common.api.ApiPathPredicateItem",
                      "pattern": "/bb/csii/**",
                      "matchStrategy": 1
                  }
              ]
      }
  ]
  
  ```
  You would get the following `ApiDefinition`
  ```
  [ApiDefinition{apiName='csii', predicateItems=[ApiPathPredicateItem{pattern='/bb/csii/**', matchStrategy=1}]}]
  ```
  hope it helps.

**Comment by sczyh30** [comment]
This could be a problem. We could improve the design later.

**Comment by cdfive** [comment]
> Use @type to specify the actual type

@yanjuning Thanks for your trick. I think the document of **fastjson** is not very friendly to user, though it's very fast.

**Comment by jasonjoo2010** [comment]
If generic type is necessary an annotation of `JSONType` is required specifying `deserializer` property.

**Comment by cdfive** [comment]
@jasonjoo2010 Use annotation `@JSONField(deserializeUsing = Xxx.class)`,  but the annotation added in Bean means that the module must rely on fastjson, wonder if there is a better way.

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 Use annotation `@JSONField(deserializeUsing = Xxx.class)`, but the annotation added in Bean means that the module must rely on fastjson, wonder if there is a better way.

Generally speaking the JSON serializing library should be specified but not pluggable for most projects. Because there are so many differences between libraries. I think it's okay if it can make it simple but using other ways are also okay. (Still I think even through other ways it's hard to be pluggable)
