### ISSUE TITLE
throw UndeclaredThrowableException instead of Subclass of BlockException

### ISSUE THREAD

**Issue by duwei54** [alibaba/Sentinel#776]
I integrate `spring-cloud-alibaba-sentinel` with version `0.9.0.RELEASE`.
I use `@SentinelResource("myResource")` without `blockHandler` or `fallback` properties.
I defined some rules and trigger throws the `DegradeException` or `FlowException`.

### I try to catch and deal these Exception with `@ExceptionHandler`.but I found the type of Exception is UndeclaredThrowableException.

According to the [document](https://github.com/alibaba/Sentinel/wiki/%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81)
> 特别地，若 blockHandler 和 fallback 都进行了配置，则被限流降级而抛出 BlockException 时只会进入 blockHandler 处理逻辑。若未配置 blockHandler、fallback 和 defaultFallback，则被限流降级时会将 BlockException 直接抛出。

Is it that I understand it wrong?

**Comment by sczyh30** [comment]
Hi, the [`UndeclaredThrowableException`](https://docs.oracle.com/javase/10/docs/api/java/lang/reflect/UndeclaredThrowableException.html) indicates that the `BlockException` is absent in your method signature. You'll need to add `throws BlockException` to your method, or add `blockHandler` to handle the exception.

**Comment by duwei54** [comment]
@sczyh30 Thanks. When I add the `throws BlockException` to the method.It work!!! 😄
