### ISSUE TITLE
repository of FlowControllerV2 has data problem

### ISSUE THREAD

**Issue by threedr3am** [alibaba/Sentinel#777]
## Issue Description

Type: *bug report* or *feature request*
In FlowControllerV2 use repository add or delete rule,maybe happen data overide problem.I add a rule,it id is 1 when sentinel-dashboard reload and zookeeper or nacos or apollo have rule,but the rule id of data source is 1.Then the again add rule will overide the  rule of  data source.

### Describe what happened (or what feature you want)
This data coverage problem stems from ```com.alibaba.csp.sentinel.dashboard.repository.rule.InMemoryRuleRepositoryAdapter#nextId```
 see 
```com/alibaba/csp/sentinel/dashboard/repository/rule/InMemParamFlowRuleStore.java:36 ```
each time it gets The id starts with 1 each time you restart the sentinel-dashboard, so the data loaded from the data source is overwritten.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by threedr3am** [comment]
I hope fix this problem,and add more degrade、param flow...,make it adapt zookeeper、nacos、apollo...
out-of-the-box feature

**Comment by sczyh30** [comment]
Hi, the in-memory repository implementation is trivial and has this kind of issue indeed. In production env you may need to implement your rule repository implementation based on DB (as storage), then use dynamic configuration center to push rules.

> I hope fix this problem,and add more degrade、param flow...,make it adapt zookeeper、nacos、apollo...
out-of-the-box feature

Nice, contributions are welcomed!
