### ISSUE TITLE
May I ask if there is a python lib out?

### ISSUE THREAD

**Issue by xixikaikai** [alibaba/Sentinel#779]
## Issue Description
目前都是jar包引用的方式，
能不能提供py lib方式调用  或者go的package呢？
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, there is no Python or Golong version of Sentinel till now. Could you please illustrate the functions you're requiring? Discussions and contributions are welcomed.

**Comment by xixikaikai** [comment]
将一些核心接口 库化如何呢？
I use py or go more now, but this jar LGTM

**Comment by sczyh30** [comment]
This requires Python or Golong implementation of Sentinel. Contributions are welcomed. Related issues: https://github.com/alibaba/Sentinel/labels/area%2Fmulti-language
