### ISSUE TITLE
Sentinel Pigeon Adapter

### ISSUE THREAD

**Issue by wchswchs** [alibaba/Sentinel#780]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
add rpc framework pigeon integration

### Anything else we need to know?
pigeon github：https://github.com/dianping/pigeon

**Comment by sczyh30** [comment]
Hi, would you like to contribute a PR?

**Comment by wchswchs** [comment]
> Hi, would you like to contribute a PR?

yeah

**Comment by sczyh30** [comment]
Added to Awesome Sentinel list via #781. Available in https://github.com/sentinel-group/sentinel-pigeon.
