### ISSUE TITLE
I hope to add the data source selection configuration to the sentinel-dashboard and directly persist the rules.

### ISSUE THREAD

**Issue by guxiaoyuuuuuu** [alibaba/Sentinel#783]
希望能在dashboard修改规则就能持久化，而且不需要去实现拉取和推送数据的接口，希望官方直接在页面或者配置文件集成好，用户只需要配置一下数据源即可。

**Comment by finefuture** [comment]
You can refer to my implementation： https://github.com/finefuture/sentinel-dashboard-X , and here is some example:  https://github.com/finefuture/Sentinel-Apollo-demo 、 https://github.com/finefuture/Sentinel-Nacos-demo

**Comment by sczyh30** [comment]
Hi, as there're many kinds of dynamic config center, we cannot integrate with all of them, so we provided interfaces of publishing and retrieving rules. You may refactor the dashboard to meet your requirement in production. Besides, you can also refer to implementations by community developers :)

**Comment by sczyh30** [comment]
> You can refer to my implementation： https://github.com/finefuture/sentinel-dashboard-X , and here is some example: https://github.com/finefuture/Sentinel-Apollo-demo 、 https://github.com/finefuture/Sentinel-Nacos-demo

@finefuture Would you like to add your implementation in [Awesome Sentinel list](https://github.com/alibaba/Sentinel/blob/master/doc/awesome-sentinel.md)?

**Comment by finefuture** [comment]
@sczyh30 ok,I agree with you
