### ISSUE TITLE
RT_MAX_EXCEED_N should be configurable

### ISSUE THREAD

**Issue by 1522140840** [alibaba/Sentinel#784]
降级规则直接写死个5不合适吧？如果应用QPS 50以下都算低峰期，理论上这时是不需要降级的，但是使用sentinel却被熔断、降级了。。。认为这个参数应该做成可配置的。
private static final int RT_MAX_EXCEED_N = 5;

![image](https://user-images.githubusercontent.com/27505826/58168291-792bf600-7cc0-11e9-8295-adc9de08aae6.png)

version:1.6.0

**Comment by 1522140840** [comment]
like this
![image](https://user-images.githubusercontent.com/27505826/58172741-f7da6080-7ccb-11e9-9769-494b25b4c187.png)

**Comment by sczyh30** [comment]
Yes, it should be configurable. Contributions are welcomed. There's already an issue and we can discuss here: https://github.com/alibaba/Sentinel/issues/673

Closing this issue due to duplication.
