### ISSUE TITLE
The version of sentinel-datasource-apollo and spring-cloud-starter-alibaba-sentinel does not correspond?

### ISSUE THREAD

**Issue by zuowenmou** [alibaba/Sentinel#792]
1.最新报错版本
     <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.9.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-apollo</artifactId>
            <version>1.5.2</version>
        </dependency>
2.报错信息：
         ***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties:

    Reason: Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties

Action:

Update your application's configuration

3.降低版本后，运行正常

            <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.2.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-apollo</artifactId>
            <version>1.5.2</version>
        </dependency>

 希望作者帮助分析一下

**Comment by sczyh30** [comment]
Hi, is there any detail information about the error?

**Comment by sczyh30** [comment]
cc @fangjian0423

**Comment by fangjian0423** [comment]
@zuowenmou Could you please provide your configurations in application.properties or application.yaml?

**Comment by zuowenmou** [comment]
> @zuowenmou您能否在application.properties或application.yaml中提供您的配置？

spring.application.name=sentinel-datasource-apollo

# apollo config
app.id=${spring.application.name}

apollo.meta=http://192.168.20.20:8080

# sentinel dashboard
spring.cloud.sentinel.transport.dashboard=${apollo.meta}
spring.cloud.sentinel.eager=true
spring.cloud.sentinel.transport.port=30160
# sentinel datasource apollo
spring.cloud.sentinel.datasource.ds.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey=sentinel.flowRules

spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=sentinel.degrades

**Comment by zuowenmou** [comment]
- 

1. 

- [ ] `spring.application.name=sentinel-datasource-apollo

# apollo config
app.id=${spring.application.name}

apollo.meta=http://192.168.20.20:8080

# sentinel dashboard
spring.cloud.sentinel.transport.dashboard=${apollo.meta}
spring.cloud.sentinel.eager=true
spring.cloud.sentinel.transport.port=30160
# sentinel datasource apollo
spring.cloud.sentinel.datasource.ds.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey=sentinel.flowRules

spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=sentinel.degrades
`

**Comment by fangjian0423** [comment]
@zuowenmou need `rule-type` property.

```properties
spring.cloud.sentinel.datasource.ds.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey=sentinel.flowRules
spring.cloud.sentinel.datasource.ds.apollo.rule-type=flow

spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=application
spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=sentinel.degrades
spring.cloud.sentinel.datasource.ds2.apollo.rule-type=degrade
```

**Comment by zuowenmou** [comment]
> @zuowenmou need `rule-type` property.
> 
> ```ini
> spring.cloud.sentinel.datasource.ds.apollo.namespaceName=application
> spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey=sentinel.flowRules
> spring.cloud.sentinel.datasource.ds.apollo.rule-type=flow
> 
> spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=application
> spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=sentinel.degrades
> spring.cloud.sentinel.datasource.ds2.apollo.rule-type=degrade
> ```

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties:

    Property: spring.cloud.sentinel.datasource.ds.apollo.rule-type
    Value: flow
    Origin: class path resource [application.properties]:48:54
    Reason: Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties

Action:

Update your application's configuration

修改后的新错误。还麻烦帮着看一下

**Comment by zuowenmou** [comment]
> @zuowenmou需要`rule-type`财产。
> 
> ```ini
> spring.cloud.sentinel.datasource.ds.apollo.namespaceName = application
>  spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey = sentinel.flowRules
>  spring.cloud.sentinel.datasource.ds.apollo.rule-type = flow
> 
> spring.cloud.sentinel.datasource.ds2.apollo.namespaceName = application
>  spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey = sentinel.degrades
>  spring.cloud.sentinel.datasource.ds2.apollo.rule-type = degrade
> ```



> @zuowenmou need `rule-type` property.
> 
> ```ini
> spring.cloud.sentinel.datasource.ds.apollo.namespaceName=application
> spring.cloud.sentinel.datasource.ds.apollo.flowRulesKey=sentinel.flowRules
> spring.cloud.sentinel.datasource.ds.apollo.rule-type=flow
> 
> spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=application
> spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=sentinel.degrades
> spring.cloud.sentinel.datasource.ds2.apollo.rule-type=degrade
> ```

是不是与spring-boot版本有关系呢

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E and http://blog.didispace.com/spring-cloud-alibaba-sentinel-2-2/

**Comment by zuowenmou** [comment]
> 嗨，有关于错误的详细信息吗？



> refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E and http://blog.didispace.com/spring-cloud-alibaba-sentinel-2-2/
好的，正在尝试修改

**Comment by zuowenmou** [comment]
> refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E and http://blog.didispace.com/spring-cloud-alibaba-sentinel-2-2/
重新整理一下

1.现在的改动
     1.升级了项目的springboot的版本：2.1.3.RELEASE
     2.升级了spring-cloud-starter-alibaba-sentinel： 0.9.0.RELEASE
     2.在application.properties中添加rule-type

此时启动，会报错：
***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to 

- org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties:

   Property: spring.cloud.sentinel.datasource.ds.apollo.rule-type
    Value: flow
    Origin: class path resource [application.properties]:45:54
    Reason: Failed to bind properties under 'spring.cloud.sentinel.datasource.ds.apollo' to org.springframework.cloud.alibaba.sentinel.datasource.config.ApolloDataSourceProperties
Action:
Update your application's configuration

2.回退版本，启动正常，流控生效
    1. 回退 spring-cloud-starter-alibaba-sentinel版本到 ： 0.2.1.RELEASE
    2.删除application.properties中的rule-type
 然后启动正常。

经对比apollo使用方案（http://blog.didispace.com/spring-cloud-alibaba-sentinel-2-2/），是一致的

此时的猜想：sentinel-datasource-apollo的1.5.2和 spring-cloud-starter-alibaba-sentinel 的0.9.0.RELEASE版本是否兼容？

**Comment by fangjian0423** [comment]
version is right, refer bom:

https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-alibaba-dependencies/0.9.0.RELEASE/spring-cloud-alibaba-dependencies-0.9.0.RELEASE.pom

**Comment by zuowenmou** [comment]
您好，我们这里sentinel 版本升不上去了，是否是我表达不够完善呢？造成了您分析不够全面
我还需要提供些什么呢，麻烦了
谢谢

**Comment by fangjian0423** [comment]
> 您好，我们这里sentinel 版本升不上去了，是否是我表达不够完善，造成了您分析不够全面
> 我还需要提供些什么呢，麻烦了
> 谢谢

Could you provide a project that reproduces the issue?

**Comment by sczyh30** [comment]
Is this problem resolved?

**Comment by zuowenmou** [comment]
> Is this problem resolved?
嗯。。
此问题还没有解决，
但换了个思路
我们不再用starter方式了。
换成了自己引用sentinel用到的包

**Comment by bert82503** [comment]
亲测有效😄

- [Spring Cloud Alibaba基础教程：Sentinel使用Apollo存储规则](https://blog.didispace.com/spring-cloud-alibaba-sentinel-2-2/)
- [Spring Cloud Alibaba基础教程：Sentinel使用Apollo存储规则](https://developer.aliyun.com/article/699190)

```xml
    <dependencies>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-apollo</artifactId>
            <version>1.8.8</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.2.10</version>
        </dependency>
    </dependencies>
```

**Comment by bert82503** [comment]
这两个插件的实现，本质上还是通过Apollo配置中心读取Sentinel的流控规则配置，而不是通过Sentinel Dashboard的API获取。
这样设计很奇怪，让用户感知到Apollo配置中心的存在，本质上可以对用户完全透明，用户只需要感知Sentinel Dashboard和其地址即可。 @sczyh30
