### ISSUE TITLE
Spring Cloud Gateway circuit breaker with Sentinel

### ISSUE THREAD

**Issue by tuser4198** [alibaba/Sentinel#793]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
I only found GatewayFlowRule in sentinel-api-gateway-adapter-common.jar and SentinelGatewayFilter.java only processes flowRule.
But now I want to use Sentinel circuit breaker with Spring Cloud Gateway. What should I do?

### Describe what you expected to happen
Use Sentinel circuit breaker with Spring Cloud Gateway

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tuser4198** [comment]
Hi ,does it has a plan?

**Comment by sczyh30** [comment]
Hi, you can configure normal `DegradeRule`s (for routes or customized API groups) to enable circuit breaking for Spring Cloud Gateway.
