### ISSUE TITLE
The sentinel-dashboard's real-time monitoring module is  showing difference between graph and table，maybe the graph is showing wrong data

### ISSUE THREAD

**Issue by qtwang** [alibaba/Sentinel#799]
dashboard实时监控模块数据的图展示与表展示不一致，示意图如下：
![微信图片_20190529162347](https://user-images.githubusercontent.com/20967092/58552104-2617ed00-8244-11e9-81f0-3b590c176870.png)
请帮忙查看一下是否图表展示部分有bug，thx！

**Comment by qtwang** [comment]
值得注意的是：这里面应用了sentinel-zuul-adapter包，不知道是否是zuul包的问题？

**Comment by sczyh30** [comment]
右侧图表对应实时的数据，会展现在图线的最右部分。
