### ISSUE TITLE
[Feature] Integration with Netflix Zuul2

### ISSUE THREAD

**Issue by kimmking** [alibaba/Sentinel#80]
## Issue Description

Integration with Netflix Zuul2

### Describe what happened (or what feature you want)

The version of Netflix Zuul2 is 2.1.3 now, Zuul2 use netty and ribon to make a non-blocking and asynchronous gateway.
Community can Integrate it.

**Comment by liangyuanpeng** [comment]
so this issue have any update?

**Comment by sczyh30** [comment]
Contributions are welcomed!

**Comment by wavesZh** [comment]
I want to try

**Comment by sczyh30** [comment]
> I want to try

👍 Looking forward to your PR~ Note that Zuul 2 is asynchronous so you may need to use `AsyncEntry`. You could refer to the implementation of Zuul 1.x adapter.
