### ISSUE TITLE
The fuse type selects an abnormal number, and the blow cycle can only be one minute.

### ISSUE THREAD

**Issue by fg546300040** [alibaba/Sentinel#805]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
  `     else if (grade == RuleConstant.DEGRADE_GRADE_EXCEPTION_COUNT) {
            double exception = clusterNode.totalException();
            if (exception < count) {
                return true;
            }
        }
`
熔断类型选择异常数量取的是total的异常，也就是最近一分钟的异常。那么熔断周期设置的周期是无效的。因为只要异常数量达到了阈值，那么后面一分钟都是满足条件的。 这个能否改成exceptionQps。 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, it's a good idea, but a better solution is to support arbitrary statistic time span for different circuit breaking rules. We can discuss this in: #606

**Comment by laofuguang** [comment]
> Hi, it's a good idea, but a better solution is to support arbitrary statistic time span for different circuit breaking rules. We can discuss this in: #606

@sczyh30  嗯， 统计的周期也都支持在rule设置呀   另外我参考TCP拥塞实现了一个slot。 主要满足性能较差的接口按照时延进行限流。 不知道你有没有兴趣，可以的话也提上来。

**Comment by sczyh30** [comment]
> > Hi, it's a good idea, but a better solution is to support arbitrary statistic time span for different circuit breaking rules. We can discuss this in: #606
> 
> @sczyh30 嗯， 统计的周期也都支持在rule设置呀 另外我参考TCP拥塞实现了一个slot。 主要满足性能较差的接口按照时延进行限流。 不知道你有没有兴趣，可以的话也提上来。

Nice, contributions are welcomed. You could illustrate your design in your pull request :)
