### ISSUE TITLE
SystemRuleManager does not haveConfig

### ISSUE THREAD

**Issue by woshioosm** [alibaba/Sentinel#808]
FlowRuleManager
DegradeRuleManager
AuthorityRuleManager
都有hasCofig 
为何 SystemRuleManager 没有

除了这种方法 还有什么方法判断当前resource是有规则加载的？

**Comment by sczyh30** [comment]
Hi, `SystemRuleManager` does not have a `hasConfig` method for resource as the system rule is global rather than per resource.
