### ISSUE TITLE
文档错别字

### ISSUE THREAD

**Issue by cdfive** [alibaba/Sentinel#81]
第一次看到Sentinel，看介绍非常有吸引力，想好好学习和应用到项目中^_^!
阅读文档中发现两处：

http://dubbo.incubator.apache.org/zh-cn/blog/sentinel-introduction-for-dubbo.html
一种用书状结构展示资源的调用链路=>树状

https://github.com/alibaba/Sentinel/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
private static void initDegradeRule() {
	List<SystemRule> rules = new ArrayList<>();
	SystemRule rule = new SystemRule();
	rule.setHighestSystemLoad(10);
	rules.add(rule);
	DegradeRuleManager.loadRules(rules);
}
DegradeRuleManager.loadRules(rules);=>SystemRuleManager.loadRules(rules);

**Comment by sczyh30** [comment]
Thanks for reporting! We'll fix them.
