### ISSUE TITLE
cannot  access cluster flow rule information from http:ip:port/cluster/server/flowRules

### ISSUE THREAD

**Issue by hone-liu** [alibaba/Sentinel#810]
<!-- Here is for bug reports and feature requests ONLY! 

HttpServerHandler.parseTarget这块代码可能是个bug, 由于只截取了第二个string，
导致访问 http://ip:port/cluster/server/info 提示“Unknown command "cluster/server/info"

因为 而HttpServer.handlerMap 里面存放CommandHandler 的key是  /cluster/server/info 而不是cluster

private String parseTarget(String uri) {
        if (StringUtil.isEmpty(uri)) {
            return "";
        }
        String[] arr = uri.split("/");
        if (arr.length < 2) {
            return "";
        }
        return arr[1];
    }

**Comment by sczyh30** [comment]
Hi, could you please provide more information here?

**Comment by sczyh30** [comment]
Friendly ping :)

**Comment by hone-liu** [comment]
> Hi, could you please provide more information here?

当访问 http://ip:port/cluster/server/flowRules 去获取 机器规则的时候
系统会通过 key 去到HttpServer.handlerMap 获取CommandHandler去执行业务，
HttpServer.handlerMap 里面存放的key是cluster/server/flowRules
而这里通过下面parseTarget方法获取的key 是cluster ，导致找不到对应的CommandHandler从而出错

    private String parseTarget(String uri) {
        if (StringUtil.isEmpty(uri)) {
            return "";
        }
        String[] arr = uri.split("/");
        if (arr.length < 2) {
            return "";
        }
        return arr[1];
    }

**Comment by sczyh30** [comment]
Thanks for reporting. It's a logic bug of `sentinel-transport-netty-http` module. Would you like to contribute a PR to fix it?
