### ISSUE TITLE
Adding a flow control rule to the sentinel console, after clicking Confirm, the list is not displayed, and the machine is offline from time to time.

### ISSUE THREAD

**Issue by authorXiao** [alibaba/Sentinel#811]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, could you please describe the details in the issue description?

**Comment by sczyh30** [comment]
For adding rules, you may need to check whether the fastjson version in your service side is too low. For machine discovery, please ensure your network is stable.
