### ISSUE TITLE
Configuring csp.sentinel.log.dir through the configuration file does not work

### ISSUE THREAD

**Issue by threedr3am** [alibaba/Sentinel#812]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
当我根据[wiki文档](https://github.com/alibaba/Sentinel/wiki/%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9)使用`${user_home}/logs/csp/${project.name}.properties`配置文件的方式配置csp.sentinel.log.dir时，该配置不会生效。

### Describe what you expected to happen
首先，可以看到SentinelConfig这个class的源码，在类被加载后执行static代码块的时候，会执行`com/alibaba/csp/sentinel/config/SentinelConfig.java:65`处对，配置文件和jvm参数中的配置读取，并且设置进`com.alibaba.csp.sentinel.config.SentinelConfig#props`中，但是注意`com/alibaba/csp/sentinel/config/SentinelConfig.java:109`获取配置文件的fileName时，是调用`com.alibaba.csp.sentinel.log.LogBase#getLogBaseDir`获取配置文件的目录，而查看类LogBase在执行static代码块的时候，会执行`com.alibaba.csp.sentinel.log.LogBase#init`，其中`com.alibaba.csp.sentinel.log.LogBase#logBaseDir`的值只会使用两种方式得到：
```
String logDir = System.getProperty(LOG_DIR);

 if (logDir == null || logDir.isEmpty()) {
       logDir = System.getProperty(USER_HOME);
       logDir = addSeparator(logDir) + DIR_NAME + File.separator;
 }
```
所以，该配置必然不会生效，所以，在`com.alibaba.csp.sentinel.config.SentinelConfig#loadProps`中直接调用LogBase.getLogBaseDir()获取log dir必然是有问题的。

### How to reproduce it (as minimally and precisely as possible)

1. 使用`${user_home}/logs/csp/${project.name}.properties`配置文件的方式配置csp.sentinel.log.dir
2. 启动项目
3. 观察日志输出目录，还是默认的${user_home}/logs/csp/

### Tell us your environment
最新master（2019-06-05）

**Comment by sczyh30** [comment]
Hi，目前 `${user_home}/logs/csp/${project.name}.properties` 方式暂时不支持配置日志目录，可以先采用 JVM -D 参数形式配置。未来会增强 properties 文件方式配置的支持，可以参考 #804 

---
It's not supported to configure the log directory via `${user_home}/logs/csp/${project.name}.properties` file till now.

**Comment by threedr3am** [comment]
👌，我看wiki文档可以update一下，上面描述只是project.name不支持。

**Comment by sczyh30** [comment]
> 👌，我看wiki文档可以update一下，上面描述只是project.name不支持。

Thanks for your suggestion. I've updated the wiki document :)
