### ISSUE TITLE
sentinel-annotation-aspectj Incompatible spring-cloud-starter-alibaba-sentinel

### ISSUE THREAD

**Issue by a120610114** [alibaba/Sentinel#819]
When I used spring-cloud-starter-alibaba-sentinel and then used the @SentinelResource annotation, it was found to be invalid. Then when I use the demo example provided, I find it is usable! But when the dependency was changed to spring-cloud-starter-alibaba-sentinel, it was found that it failed again. (当我使用 spring-cloud-starter-alibaba-sentinely 依赖时再使用 @SentinelResource 注解时发现是失效的。 然后我再使用提供的demo示例时，发现@SentinelResource 是可以使用的！但是将依赖改成spring-cloud-starter-alibaba-sentinel 时发现又失效)

**Comment by a120610114** [comment]
When I use the spring-cloud-starter-alibaba-sentinely dependency, I found that it is invalid when I use the @SentinelResource annotation. Then I use the provided demo again. In the example, @SentinelResource was found to be usable! But it was found to be invalid when I changed the dependency to spring-cloud-starter-alibaba-sentinel.

**Comment by sczyh30** [comment]
Hi, you could try to restrict the version of `sentinel-annotation-aspectj` to 1.6.1 in `dependencyManagement` of your `pom.xml` and see whether it could work.

**Comment by a120610114** [comment]
Thanks problem solved

> 
> 
> Hi, you could try to restrict the version of `sentinel-annotation-aspectj` to 1.6.1 in `dependencyManagement` of your `pom.xml` and see whether it could work.

Thanks problem solved

**Comment by Amitbhave** [comment]
@sczyh30 , is there any update about the fix? sentinel-aspect still doesn't seem to work with  spring-cloud-starter-alibaba-sentinel dependency.
