### ISSUE TITLE
error register client to dashboard when there are multiple virtual network on the client.

### ISSUE THREAD

**Issue by flyceek** [alibaba/Sentinel#820]
error register client to dashboard when there are multiple virtual network on the client.
error message:
ERROR c.t.c.s.d.metric.MetricFetcher - fetch metric http://0.0.0.0:8719

can specify ip at registration?

thank you!!
:-)

**Comment by sczyh30** [comment]
Hi, you could configure it via the `-Dcsp.sentinel.heartbeat.client.ip=xxx` property. See #261 for discussions.

**Comment by flyceek** [comment]
thank you !
:-)
