### ISSUE TITLE
An enhancement requirement for global black/white list for all interfaces of one service

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/Sentinel#826]
Currently the black/white list must specify the 'resource' for an interface, but if i have 100 interfaces I must set for those 100 times. 

我有个需求，resource可否不配置？比如我有100个接口，按照Sentinel思路，我要配置100个resource，我现在想通过Sentinel全部对100个接口做黑白名单，即全局对服务（该服务所有接口实现黑/白名单控制）。同理，流控最好也能支持该功能。

**Comment by sczyh30** [comment]
It's actually "global rule". For whitelist/blacklist rule it's easy to work on, but for other rules (e.g. flow rules) we need more discussions. We can discuss the design here: #66

**Comment by vipweihua** [comment]
Let me clarify the feature: Actually, we want blocking one **SERVICE** to access another one, means that we need to block all the APIs, not only the APIs with @Resource, but also those without @Resource.

**Comment by sczyh30** [comment]
> Let me clarify the feature: Actually, we want blocking one **SERVICE** to access another one, means that we need to block all the APIs, not only the APIs with @resource, but also those without @resource.

Could you please describe what "those without `@resource`" means?

**Comment by vipweihua** [comment]
> > Let me clarify the feature: Actually, we want blocking one **SERVICE** to access another one, means that we need to block all the APIs, not only the APIs with @resource, but also those without @resource.
> 
> Could you please describe what "those without `@resource`" means?
Any sentinel resource is defined by @Resource annotation, could sentinel provide the feature to block all the APIs including those which not defined as a sentinel resource.

**Comment by sczyh30** [comment]
> Any sentinel resource is defined by `@SentinelResource` annotation, could sentinel provide the feature to block all the APIs including those which not defined as a sentinel resource.

Sentinel could only manage those APIs defined with Sentinel API (`SphU`, `@SentinelResource` annotation or via framework integrations). For other free APIs Sentinel is not able to know their existence.

**Comment by cdfive** [comment]
使用@Resource注解，这样Sentinel才能感知这是它要保护的资源。

可能主流框架适配会用得多一些吧，因为更加方便。

[https://github.com/alibaba/Sentinel/wiki/主流框架的适配#dubbo](https://github.com/alibaba/Sentinel/wiki/主流框架的适配#dubbo)

> 限流粒度可以是服务接口和服务方法两种粒度：
* 服务接口：resourceName 为 接口全限定名，如 com.alibaba.csp.sentinel.demo.dubbo.FooService
* 服务方法：resourceName 为 接口全限定名:方法签名，如 com.alibaba.csp.sentinel.demo.dubbo.FooService:sayHello(java.lang.String)

参考Sentinel对Dubbo的适配，服务接口的粒度(即接口类)，一个接口类下就包含批量的资源了，相当于该接口类下的所有方法。比如100个接口，如果用接口类的粒度，配置的resource就会少很多。

其次，就算是配100个resource，调用http接口批量设置即可，工作量也不大，也实现了需求。

我们能否转换下思路：批量设置等价于全局。
这样的话可以考虑，在控制台增加给批量(或所有)资源设置相同规则的功能。
