### ISSUE TITLE
Support data-source extension Spring Cloud Config

### ISSUE THREAD

**Issue by hgccode** [alibaba/Sentinel#831]
## Issue Description
sentinel-datasource suport spring cloud config？
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Now, main support nacos,zeepkeeper and so on. I want to support spring-cloud-config and eureka.  make su

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
Hi, Sentinel data-source extension does not have Eureka and Spring Cloud Config integration. Would you like to contribute? :)

**Comment by wchswchs** [comment]
I think I can do it.

**Comment by sczyh30** [comment]
> I think I can do it. :)

Nice! You could refer to existing data source implementations like [sentinel-datasource-zookeeper](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-datasource-zookeeper). Looking forward to your PR :)

**Comment by wchswchs** [comment]
ok

**Comment by sczyh30** [comment]
Hi, any progress? :)

**Comment by linlinisme** [comment]
I have an idea about spring-config

**Comment by wchswchs** [comment]
I'm so busy on work these days. @linlinisme, if you have time, are you willing to implement this?

**Comment by linlinisme** [comment]
@sczyh30 @wchswchs that is my proposal https://github.com/alibaba/Sentinel/pull/899,  May be you two can give me some good suggestion.

**Comment by sczyh30** [comment]
👍 I'll have a look these days.

**Comment by sczyh30** [comment]
Spring Cloud Config data-source has been supported via #899, which will be released in 1.7.0.

**Comment by complone** [comment]
@sczyh30 Hello, I want to contribute dynamic rule source extension support for Eureka

**Comment by sczyh30** [comment]
> @sczyh30 Hello, I want to contribute dynamic rule source extension support for Eureka

Nice! I've opened a new issue #1197. You could reply in the issue, then contribute a PR for it :)
