### ISSUE TITLE
Using npm run build in sentinel-dashboard failed

### ISSUE THREAD

**Issue by buguniao** [alibaba/Sentinel#832]
## Issue Description

拉取master分支，在sentinel-dashboard子工程下运行
 npm i
npm run build 
报错：
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN sentinel-dashboard@1.0.0 No repository field.
 
 
### Tell us your environment
npm 版本：6.4.1
node 版本： v11.4.0

**Comment by sczyh30** [comment]
Could you please provide some details (e.g. error message, your environment)?

**Comment by sczyh30** [comment]
Please ensure you're in the correct directory of the frontend project: `sentinel-dashboard/src/main/webapp/resources`

And I didn't see any ERROR log?

**Comment by buguniao** [comment]
该问题是有npm升级到 6.4.1 之后导致的，
需要升级
npm update natives
