### ISSUE TITLE
ParamFlowChecker has an int overflow risk

### ISSUE THREAD

**Issue by chixuan777** [alibaba/Sentinel#837]
ParamFlowChecker基于sentinel-parameter-flow-control1.6.1
int toAddCount = (int)((passTime * tokenCount) / (rule.getDurationInSec() * 1000));
这部分代码，如果出现，流量极小(or脉冲)，但是tokenCount配置又很大的情况，出现int溢出的问题

**Comment by sczyh30** [comment]
Thanks for reporting! We'll fix it in the next version (maybe 1.6.2).
