### ISSUE TITLE
convert 0 rules but there are 1 rules from datasource . RuleCLass: FlowRule

### ISSUE THREAD

**Issue by cxk502401673** [alibaba/Sentinel#846]
sentinel convert 0 rules but there are 1 rules from datasource . RuleCLass: FlowRule

这是什么原因导致的？

**Comment by sczyh30** [comment]
Could you please provide some detail information (e.g. your Sentinel version and use case)?

And please check whether your fastjson version is too low.

**Comment by fangjian0423** [comment]
And provider your flow rule json, maybe the json is invalid.

**Comment by dingdongliang** [comment]
convert error: convert 0 rules but there are 2 rules from datasource. RuleClass: FlowRule

**Comment by fangjian0423** [comment]
@dingdongliang @cxk502401673 refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/569

**Comment by dingdongliang** [comment]
> @dingdongliang @cxk502401673 refer [spring-cloud-incubator/spring-cloud-alibaba#569](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/569)

搞定了，多谢@fangjian0423
