### ISSUE TITLE
Sentinel dashboard fetch metric failed: ConnectionException

### ISSUE THREAD

**Issue by tonfay** [alibaba/Sentinel#847]
控制台无法正常监控，机器列表里面健康状态正常，但是没有监控数据。
![image](https://user-images.githubusercontent.com/19604131/59755210-18410f00-92ba-11e9-82d8-1141ec808a81.png)

实现类:
TransportConfig.getHeartbeatClientIp()->HostNameUtil.resolveHost()
两种实现方式:
1.修改对应hostname与ip地址的映射关系即可
2.可指定-Dcsp.sentinel.heartbeat.client.ip=xxx 配置

**Comment by Douyu123456** [comment]
The application throws this exception:
![image](https://user-images.githubusercontent.com/43698412/88500926-80801b00-cfb9-11ea-81e6-69c1af5b08f5.png)

For ".yml" or ".properties",add this configuration property about "spring.cloud.sentinel.transport.clientIp".And the value is your Sentinel Controller's address.I test it myself,and pass!
