### ISSUE TITLE
DegradeRule cannot degrade resources corresponding to response time longer than 1s

### ISSUE THREAD

**Issue by kangyl** [alibaba/Sentinel#851]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
DegradeRule 对应响应时间超过1s的资源无法降级,我某个接口平均响应时间2s左右,我想针对该接口做熔断限制,看了下代码发现avgRt的数据来源为StatisticNode.rollingCounterInSecond.该属性的统计时间窗口为1s而已,如果资源请求超过1s永远不会触发熔断降级的情况

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jasonjoo2010** [comment]
Hi, have you try it out?

Basically the request is calculated into the window when finished and the rt can be greater than 1 second.
