### ISSUE TITLE
OOM caused by unexpected stack of Sentinel

### ISSUE THREAD

**Issue by wu-sheng** [alibaba/Sentinel#856]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
OOM reported in Apache SkyWalking, https://github.com/apache/skywalking/issues/2926

### Describe what you expected to happen
In the agent, we try to get the exception stack with limit length.
But from this issue(https://github.com/apache/skywalking/issues/2926) and PR(https://github.com/apache/skywalking/pull/2928), the stack length is 0, which is not expected, and don't face it in any other popular frameworks

Quote from the discussion
> because e.getStackTrace().length>0 in you code,but the com.alibaba.csp.sentinel.slots.block.flow.FlowException.getStackTrace().length=0

Could we discuss why this happens and why Sentinel implements error stack in this way?

**Comment by sczyh30** [comment]
Hi, the [`BlockException`](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/BlockException.java) (and all its subclasses, including `FlowException`) indicates the request is blocked. It's only an indication so the stack trace of it makes no sense. Besides, when the QPS is large, the redundant stack trace will bring overhead to the performance, so we purged the stack trace (override the `fillInStackTrace` method). 

PS: The HotSpot JVM also provides similar optimization mechanisms like [this scenario](https://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace).

**Comment by wu-sheng** [comment]
OK. I will add fail-safe in SkyWalking
