### ISSUE TITLE
The passCount in DegradeRule from AtomicLong to LongAdder

### ISSUE THREAD

**Issue by wchswchs** [alibaba/Sentinel#861]
Issue Description
Type: enhancement

Describe what happened (or what feature you want)
Because counting passCount when degrade is a high concurrency scenario, change `passCount` in `DegradeRule` to improve the performance.

**Comment by wchswchs** [comment]
I have contributed.

**Comment by sczyh30** [comment]
Closing the issue as the implementation of circuit breaker will be refactored.
