### ISSUE TITLE
Does client support dashborad cluster?

### ISSUE THREAD

**Issue by Yisaki** [alibaba/Sentinel#865]
## Issue Description

 *feature request*

### Describe what happened (or what feature you want)
we want to dashborad is a HA application,so we deploy more than one,and assign a domain and a nginx in front of it.

because we do not persistent the resource metrics data to mysql through modify dashborad code, 
and here is the question,how to make it happen that the client can connect the cluster 
like 
-Dcsp.sentinel.dashboard.server=ip1:port1,ip2:port2 
or
-Dcsp.sentinel.dashboard.server=ngxin.domain.com

if not support ,can it be a new feature in next version?
thx
### Tell us your environment
v1.6.1

**Comment by sczyh30** [comment]
Hi, it's not supported yet. You may refer to #241 and #363

**Comment by Yisaki** [comment]
谢谢
