### ISSUE TITLE
The rule vanished after adding via the dashboard

### ISSUE THREAD

**Issue by N1cer** [alibaba/Sentinel#867]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by cdfive** [comment]
Hi，不清楚你使用的Sentinel版本，应用类型。
建议参考**FAQ**排查：
[https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到](https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到)
可能是应用依赖的**fastjson**版本的原因，建议升级到1.2.56及以上。
${home}/logs/csp/sentinel-record.log 检查日志是否有异常输出也能帮助排查。

**Comment by N1cer** [comment]
> 
> 
> Hi，不清楚你使用的Sentinel版本，应用类型。
> 建议参考**FAQ**排查：
> [https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81%E5%90%8E%E7%9C%8B%E4%B8%8D%E5%88%B0)
> 可能是应用依赖的**fastjson**版本的原因，建议升级到1.2.56及以上。
> ${home}/logs/csp/sentinel-record.log 检查日志是否有异常输出也能帮助排查。

**Comment by N1cer** [comment]
> 
> 
> Hi，不清楚你使用的Sentinel版本，应用类型。
> 建议参考**FAQ**排查：
> [https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81%E5%90%8E%E7%9C%8B%E4%B8%8D%E5%88%B0)
> 可能是应用依赖的**fastjson**版本的原因，建议升级到1.2.56及以上。
> ${home}/logs/csp/sentinel-record.log 检查日志是否有异常输出也能帮助排查。
我的sentinel是1.6.0；第一次连接服务是成功的，显示我应用中初始化的服务

> 
> 
> Hi，不清楚你使用的Sentinel版本，应用类型。
> 建议参考**FAQ**排查：
> [https://github.com/alibaba/Sentinel/wiki/FAQ#q-控制台正确的规则推送后看不到](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81%E5%90%8E%E7%9C%8B%E4%B8%8D%E5%88%B0)
> 可能是应用依赖的**fastjson**版本的原因，建议升级到1.2.56及以上。
> ${home}/logs/csp/sentinel-record.log 检查日志是否有异常输出也能帮助排查。

**Comment by N1cer** [comment]
我的sentinel版本是1.6.0；第一次连接应用是成功的，控制台显示应用初始化的规则，但是再次编辑或者提交就会全部消失；
我更改了应用fastjson的版本，和sentinel同步，解决了这个问题。
