### ISSUE TITLE
DataSource integration for Consul

### ISSUE THREAD

**Issue by N1cer** [alibaba/Sentinel#870]
我现在使用的配置中心是consul，但是文档中只找到了zk,nacos,apollo做push模式，那么我该如何做规则的持久化？

**Comment by sczyh30** [comment]
Hi, Consul data-source is not supported yet. Would you like to contribute?

**Comment by N1cer** [comment]
I think I can give it a try.

**Comment by sczyh30** [comment]
Nice, looking forward to your pull request! You could refer to existing implementations like [sentinel-datasource-zookeeper](https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-datasource-zookeeper).

**Comment by sczyh30** [comment]
Hi, any progress? :)

**Comment by N1cer** [comment]
so sorry,I can‘t do this.

**Comment by wavesZh** [comment]
I want to try it!

**Comment by sczyh30** [comment]
> I want to try it!

@wavesZh Nice, looking forward to your PR~

**Comment by sczyh30** [comment]
Resolved in #979
