### ISSUE TITLE
What if we synchronize the rules to Apollo?

### ISSUE THREAD

**Issue by tonfay** [alibaba/Sentinel#875]
如何把sentinel 控制台保存的规则 同步给apollo 并发布?
当前现状 需要手动在apollo控制台中编辑规则json并再次发布嘛?

**Comment by tonfay** [comment]
是否已经支持 自动同步给apollo?

**Comment by sczyh30** [comment]
Hi, you have to refactor the dashboard. You could refer to the following samples:

- https://github.com/alibaba/Sentinel/wiki/控制台#62-规则推送
- https://github.com/alibaba/Sentinel/tree/master/sentinel-dashboard/src/test/java/com/alibaba/csp/sentinel/dashboard/rule/apollo

**Comment by tonfay** [comment]
tks
