### ISSUE TITLE
persistent metrics data with mysql DB

### ISSUE THREAD

**Issue by YoungHu** [alibaba/Sentinel#88]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
persistent the application metric with mysql DB, then user can use grafana to monitor the application by fetching data from mysql.

**Comment by kimmking** [comment]
good job

**Comment by sczyh30** [comment]
See #69

**Comment by sczyh30** [comment]
Closing this issue as the solution has been added to Awesome Sentinel.
