### ISSUE TITLE
remove the tmpLog  dir

### ISSUE THREAD

**Issue by linlinisme** [alibaba/Sentinel#881]
## Issue Description

 *bug report* 

### Describe what happened (or what feature you want)

every time I install Sentinel my /user/home will add several junk files like
```
tmpLogDir1562036016836
tmpLogDir1562036596518
tmpLogDir1562037419434
```
I found it is created by some test cases. 
It can be remove when the cases run over?
It is annoying to see this junk files, because I have to remove it  manually.

**Comment by sczyh30** [comment]
Hi, could you please investigate which test cases generated the temporary directories?

**Comment by linlinisme** [comment]
`com.alibaba.csp.sentinel.RecordLogTest`
```
@Test
    public void testChangeLogBase() {
        String userHome = System.getProperty("user.home");
        String newLogBase = userHome + File.separator + "tmpLogDir" + System.currentTimeMillis();
        System.setProperty(LogBase.LOG_DIR, newLogBase);

        RecordLog.info("testChangeLogBase");
        String logFileName = RecordLog.getLogBaseDir();
        File[] files = new File(logFileName).listFiles();
        assertTrue(files != null && files.length > 0);
    }

    @Test
    public void testLogBaseDir() {
        RecordLog.info("testLogBaseDir");
        assertTrue(RecordLog.getLogBaseDir().startsWith(System.getProperty("user.home")));
    }
```
`com.alibaba.csp.sentinel.slots.logger.EagleEyeLogUtilTest
`
 ```
@Test
    public void testWriteLog() throws Exception {
        EagleEyeLogUtil.log("resourceName", "BlockException", "app1", "origin", 1);

        final File file = new File(RecordLog.getLogBaseDir() + EagleEyeLogUtil.FILE_NAME);
        await().timeout(2, TimeUnit.SECONDS)
            .until(new Callable<File>() {
                @Override
                public File call() throws Exception {
                    return file;
                }
            }, FileMatchers.anExistingFile());
    }

    @Test
    public void testChangeLogBase() throws Exception {
        String userHome = System.getProperty("user.home");
        String newLogBase = userHome + File.separator + "tmpLogDir" + System.currentTimeMillis();
        System.setProperty(LogBase.LOG_DIR, newLogBase);

        EagleEyeLogUtil.log("resourceName", "BlockException", "app1", "origin", 1);

        final File file = new File(RecordLog.getLogBaseDir() + EagleEyeLogUtil.FILE_NAME);
        await().timeout(2, TimeUnit.SECONDS)
            .until(new Callable<File>() {
                @Override
                public File call() throws Exception {
                    return file;
                }
            }, FileMatchers.anExistingFile());
    }
```

**Comment by sczyh30** [comment]
Maybe it's better to use the temporary directory (`System.getProperty("java.io.tmpdir")`) or remove the directory on the end of the test. Would you like to contribute a PR to fix it?

**Comment by linlinisme** [comment]
ok， I have a try.

**Comment by linlinisme** [comment]
@sczyh30  Actually, I think the  `com.alibaba.csp.sentinel.RecordLogTest#testChangeLogBase` is not necessarily, Instead it is misleading.  First, `RecordLog`  has not the changeLogBase function at all, It just get from `LogBase`.  Maybe we just promise the `LogBase` can retrieve `logBaseDir` correctly. 
 Second, when you install the whole project, the test check seem is ok. Actually It is wrong, 
```
@Test
    public void testChangeLogBase() {
        String userHome = System.getProperty("user.home");
        String newLogBase = userHome + File.separator + "tmpLogDir" + System.currentTimeMillis();
        System.setProperty(LogBase.LOG_DIR, newLogBase);

        RecordLog.info("testChangeLogBase");
        String logFileName = RecordLog.getLogBaseDir();
        File[] files = new File(logFileName).listFiles();
        assertTrue(files != null && files.length > 0);
    }
```
the `RecordLog.getLogBaseDir()` is not `userHome + File.separator + "tmpLogDir" + System.currentTimeMillis()`.  Actually, it is ` addSeparator(logDir) + DIR_NAME + File.separator`. Because `LogBase` can be static init for only once.

` com.alibaba.csp.sentinel.slots.logger.EagleEyeLogUtilTest#testChangeLogBase` exist same problem.

Yet, may be `RecordLog、EagleEyeLog` should check whether they can correct record log when change a file path， but decide file path is not their job. What they should focus on  May be is when give them a file path(they don't care what it is), they can record the log correctly.

My suggestion is we can remove the test code or the `@Test`. What do you think?

**Comment by linlinisme** [comment]
the `RecordLog.getLogBaseDir()` is not `userHome + File.separator + "tmpLogDir" + System.currentTimeMillis()`. Actually, it is `addSeparator(logDir) + DIR_NAME + File.separator`. Because LogBase can be static init for only once.  Because of this, If we delete the RecordLog.getLogBaseDir(), it will also effect other test or code which dependency on Log print.

**Comment by cdfive** [comment]
Maybe we can just remove `@Test` , as `testLogNameNotUsePid()` does in `RecordLogTest` class.

By the way, in aliyun server, when I start sentinel dashboard, I found `C:\Users\` or `C:\Users\Administrator` folder are created in the same folder of sentinel-dashboard.jar, have you met ?
