### ISSUE TITLE
How does the client customize the rule interceptor that the client receives?

### ISSUE THREAD

**Issue by tonfay** [alibaba/Sentinel#882]
控制台推送到客户端的规则,在客户端如何拦截接收规则之后的逻辑?

**Comment by jasonjoo2010** [comment]
Can you illustrate the scenario?

Generally there are two ways or more to do it:

1. Implement a new read/write pair of datasource.
2. Use point cut like AOP or AspectJ

**Comment by tonfay** [comment]
> Can you illustrate the scenario?
> 
> Generally there are two ways or more to do it:
> 
> 1. Implement a new read/write pair of datasource.
> 2. Use point cut like AOP or AspectJ

我尝试过loadRule 进行AspectJ, 他并不是spring容器中的类 ,这并不是一个可取的方案.

**Comment by sczyh30** [comment]
Could you please elaborate your scenario?

**Comment by tonfay** [comment]
公司内部有上百个项目,每个项目使用的redis 不是同一个.
如果选中redis作为注册中心的情况下, dashboard 修改注册中心,客户端监听注册中心的改动,当有变化时 ,客户端修改本地的规则.
dashboard只能对应一个redis ,但是客户端有很多项目不一定连接的都是同一个redis ,这种情况下,会导致客户端监听注册中心改动失效问题.
我认为:
redis这里应该是dashboard 推送规则到客户端,客户端接收后 持久化到redis中,如果重启 也从redis再次读取即可

**Comment by jasonjoo2010** [comment]
> 公司内部有上百个项目,每个项目使用的redis 不是同一个.
> 如果选中redis作为注册中心的情况下, dashboard 修改注册中心,客户端监听注册中心的改动,当有变化时 ,客户端修改本地的规则.
> dashboard只能对应一个redis ,但是客户端有很多项目不一定连接的都是同一个redis ,这种情况下,会导致客户端监听注册中心改动失效问题.
> 我认为:
> redis这里应该是dashboard 推送规则到客户端,客户端接收后 持久化到redis中,如果重启 也从redis再次读取即可

你这个问题其实很简单

你能保证dashboard连对正确的节点吗？那么你只需要在节点注册好对应的读数据源和写数据源（redis的写数据源需要你按照读数据源来简单实现下），也就是节点既负责读入又负责写回，那么你在dashboard只要操作了任何一个节点，这个节点自己就会回写数据源，然后同一组的所有业务节点均会订阅到更新了，dashboard不需要了解内部细节，从而实现写1推N

**Comment by tonfay** [comment]
> > 公司内部有上百个项目,每个项目使用的redis 不是同一个.
> > 如果选中redis作为注册中心的情况下, dashboard 修改注册中心,客户端监听注册中心的改动,当有变化时 ,客户端修改本地的规则.
> > dashboard只能对应一个redis ,但是客户端有很多项目不一定连接的都是同一个redis ,这种情况下,会导致客户端监听注册中心改动失效问题.
> > 我认为:
> > redis这里应该是dashboard 推送规则到客户端,客户端接收后 持久化到redis中,如果重启 也从redis再次读取即可
> 
> 你这个问题其实很简单
> 
> 你能保证dashboard连对正确的节点吗？那么你只需要在节点注册好对应的读数据源和写数据源（redis的写数据源需要你按照读数据源来简单实现下），也就是节点既负责读入又负责写回，那么你在dashboard只要操作了任何一个节点，这个节点自己就会回写数据源，然后同一组的所有业务节点均会订阅到更新了，dashboard不需要了解内部细节，从而实现写1推N

这种思路是否有问题?
dashboard操作一组中的其中一个节点,这个节点回写数据到redis ,这一组中的所有节点都会订阅到更新.但是更新后又会更新到redis ,  这种情况会出现没有闭环的流程.

如何实现节点订阅到更新时,更新本地缓存  不再次向redis发布呢?

**Comment by jasonjoo2010** [comment]
> 但是更新后又会更新到redis , 这种情况会出现没有闭环的流程

没有这个过程

**Comment by tonfay** [comment]
我现在不是很清楚,应该是dashboard修改注册中心的值 ,还是应该由dashboard 推送规则到节点,然后由节点写入注册中心

**Comment by jasonjoo2010** [comment]
> 我现在不是很清楚,应该是dashboard修改注册中心的值 ,还是应该由dashboard 推送规则到节点,然后由节点写入注册中心

<img width="819" alt="Screen Shot 2019-05-07 at 10 30 38" src="https://user-images.githubusercontent.com/17573073/60562746-6dd1ed00-9d8b-11e9-803b-ac4f0c61b053.png">

**Comment by jasonjoo2010** [comment]
dashboard推送注册中心你得改dashboard，而且必须知道每一组应用的配置

节点自己来处理，dashboard就对于多应用组无状态了

**Comment by tonfay** [comment]
> dashboard推送注册中心你得改dashboard，而且必须知道每一组应用的配置
> 
> 节点自己来处理，dashboard就对于多应用组无状态了

tks.I think we can close it
