### ISSUE TITLE
dash board can create repeatable resource rules

### ISSUE THREAD

**Issue by linlinisme** [alibaba/Sentinel#883]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

When develop dashboard code in my IDE,  I found that  one resource can create serval same type rule in one machine. Look at bellow picture. Is this a bug? 
![image](https://user-images.githubusercontent.com/8200692/60561613-b3d88200-9d86-11e9-83d3-65ebe8dc5750.png)
 
 
### Describe what you expected to happen

May be one resource on a machine has the same type of rule only one

**Comment by sczyh30** [comment]
It's not a bug, but a feature. For a single resource, it's allowed (and necessary) to create multiple rules of the same type.

**Comment by linlinisme** [comment]
even though the rules  in the same machine and same application?

**Comment by sczyh30** [comment]
> even though the rules in the same machine and same application?

A simple example: flow rules for different limit origin (of a single resource)

**Comment by linlinisme** [comment]
What I mentioned the original is same, even though it is `default`.

**Comment by sczyh30** [comment]
It's allowed (no matter limit origin, control behavior, metric type, relation strategy are same or different). It all depends on the user.
