### ISSUE TITLE
AuthorityRuleEntity is missing method toAuthorityRule

### ISSUE THREAD

**Issue by tonfay** [alibaba/Sentinel#884]
Type: *feature request*

AuthorityRuleEntity is missing toAuthorityRule method
ParamFlowRuleEntity  is missing toParamFlowRulemethod

```
public AuthorityRule toAuthorityRule() {
    	AuthorityRule authorityRule = new AuthorityRule();
    	authorityRule.setLimitApp(this.getLimitApp());
    	authorityRule.setResource(this.getResource());
    	authorityRule.setStrategy(this.getStrategy());
    	return authorityRule;
}


public ParamFlowRule toParamFlowRule() {
    	ParamFlowRule paramFlowRule = new ParamFlowRule();
    	paramFlowRule.setCount(rule.getCount());
    	paramFlowRule.setGrade(rule.getGrade());
    	paramFlowRule.setLimitApp(rule.getLimitApp());
    	paramFlowRule.setParamFlowItemList(rule.getParamFlowItemList());
    	paramFlowRule.setParamIdx(rule.getParamIdx());
    	paramFlowRule.setResource(rule.getResource());
    	
    	paramFlowRule.setClusterConfig(this.getClusterConfig());
    	paramFlowRule.setClusterMode(this.isClusterMode());
    	return paramFlowRule;
}
```

**Comment by sczyh30** [comment]
Hi, you could get the rule with `toRule()` method (defined in `AbstractRuleEntity`).

**Comment by sczyh30** [comment]
Some legacy rule entity classes do not derive from `AbstractRuleEntity` so they have the `toXxxRule()` method respectively. We could unify the entity classes in the future.

**Comment by tonfay** [comment]
AuthorityRuleEntity and ParamFlowRuleEntity  Whether to add the corresponding toXXXRule() in the new version?

**Comment by sczyh30** [comment]
> AuthorityRuleEntity and ParamFlowRuleEntity Whether to add the corresponding toXXXRule() in the new version?

I don't think it's needed to add the `toXXXRule()` method. Just use `toRule()` method is okay.
