### ISSUE TITLE
Sentinel Rules Not Obtained After Client Restart

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#888]
我按照demo完成了apollo的配置持久化。
但客户端重启后未主动获取到Sentinel的规则，限流失效。
![image](https://user-images.githubusercontent.com/3397316/60636394-df23a580-9e48-11e9-9f71-c7a1f4f0af67.png)

**Comment by linlinisme** [comment]
would you please show your ruleProvider and rulePublisher code?

**Comment by cookiejoo** [comment]
> would you please show your ruleProvider and rulePublisher code?

![image](https://user-images.githubusercontent.com/3397316/60642773-94635700-9e63-11e9-975e-f73e5db7c46d.png)
![image](https://user-images.githubusercontent.com/3397316/60642809-b1982580-9e63-11e9-84fc-8365477bb4c4.png)
![image](https://user-images.githubusercontent.com/3397316/60642841-c5dc2280-9e63-11e9-9920-38a2de7dc78a.png)
![image](https://user-images.githubusercontent.com/3397316/60642856-d2607b00-9e63-11e9-8068-67b21b94a50a.png)

**Comment by linlinisme** [comment]
The FlowCotrollerV1 mainly for single machine configure.  The V2 is for the whole application.  Your code seem to used com.alibaba.csp.sentinel.dashboard.rule.DynamicRuleProvider#getRules to store and publish rules for single machine.  It's not a recommend way

**Comment by cookiejoo** [comment]
i don't know how to do，I tried many ways without success. Once my client restarted, the rules disappeared.
![image](https://user-images.githubusercontent.com/3397316/60645951-af869480-9e6c-11e9-9857-4fc7ce66db40.png)
![image](https://user-images.githubusercontent.com/3397316/60645980-bf05dd80-9e6c-11e9-96d6-bf98594dc36c.png)

**Comment by linlinisme** [comment]
May be you can refer to my PR https://github.com/alibaba/Sentinel/pull/891

**Comment by cdfive** [comment]
@cookiejoo 
It seems that `sentinel-datasource-apollo` dependency and corresponding configurations are not added.
You publish rule to apllo, but when the client restarts, it needs a approach to read rules from apllo(as the rules are stored on it, not dashboard), that can be done with `sentinel-datasource-apollo` extension,  which implements `ReadableDataSource` of Sentinel.

pom.xml
```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-apollo</artifactId>
    <version>1.5.2</version>
</dependency>
```
application.properties
```
spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=xxx
spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=xxx
spring.cloud.sentinel.datasource.ds2.apollo.rule-type=flow
spring.cloud.sentinel.datasource.ds2.apollo.data-type=json
```

Refer: 
- [https://github.com/alibaba/Sentinel/wiki/动态规则扩展](https://github.com/alibaba/Sentinel/wiki/动态规则扩展)
- [https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md#readabledatasource-支持](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md#readabledatasource-支持)

**Comment by cookiejoo** [comment]
> @cookiejoo
> It seems that `sentinel-datasource-apollo` dependency and corresponding configurations are not added.
> You publish rule to apllo, but when the client restarts, it needs a approach to read rules from apllo(as the rules are stored on it, not dashboard), that can be done with `sentinel-datasource-apollo` extension, which implements `ReadableDataSource` of Sentinel.
> 
> pom.xml
> 
> ```
> <dependency>
>     <groupId>com.alibaba.csp</groupId>
>     <artifactId>sentinel-datasource-apollo</artifactId>
>     <version>1.5.2</version>
> </dependency>
> ```
> 
> application.properties
> 
> ```
> spring.cloud.sentinel.datasource.ds2.apollo.namespaceName=xxx
> spring.cloud.sentinel.datasource.ds2.apollo.flowRulesKey=xxx
> spring.cloud.sentinel.datasource.ds2.apollo.rule-type=flow
> spring.cloud.sentinel.datasource.ds2.apollo.data-type=json
> ```
> 
> Refer:
> 
> * [https://github.com/alibaba/Sentinel/wiki/动态规则扩展](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95)
> * [https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md#readabledatasource-支持](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md#readabledatasource-%E6%94%AF%E6%8C%81)



> May be you can refer to my PR #891

guys，thank you very mush 。I know how to do it。
In the sentinel-dashboard，Just responsible for storing the rules in Apollo。
And the client has to pull the rules by itself，So I registered 【InitFunc】 on the client side.
![image](https://user-images.githubusercontent.com/3397316/60695898-17dd8080-9f16-11e9-933e-5c0f4941ec74.png)
succeeded！
