### ISSUE TITLE
Sentinel automatically disconnects

### ISSUE THREAD

**Issue by w77996** [alibaba/Sentinel#895]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
线上项目接入sentinel,在运行几天后client会自动与server断开连接，client日志中只找到图片中的问题，数据传输超出长度，请问下是什么情况引起的？
![image](https://user-images.githubusercontent.com/20549246/60709436-fe9ef900-9f42-11e9-9e69-b1aaac32fc5f.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
jdk8
tomcat6

**Comment by jasonjoo2010** [comment]
Is the port number right?

8719 is the default port of transport implementation.

**Comment by w77996** [comment]
> Is the port number right?
> 
> 8719 is the default port of transport implementation.

port  number is right

**Comment by sczyh30** [comment]
> The data transmission exceeds the length

That exception may indicate that your parameter (in `SphU.entry(res, args)`) is too large and exceeds the max allowed size. But this won't cause the token server disconnect. Are there any more error information? @w77996
