### ISSUE TITLE
Introducing SpringCloud Alibaba Sentinel, the first request will become very slow after startup

### ISSUE THREAD

**Issue by yiming33** [alibaba/Sentinel#896]
引入SpringCloud Alibaba Sentinel，启动后第一次请求 响应速度会非常慢 大概四五秒之后请求才能路由到Controller  是第一次请求sentinel做了初始化操作吗？ 是否有饥饿加载？

**Comment by sczyh30** [comment]
You could manually trigger the initialization with `InitExecutor.doInit()`, or leverage this property item of Spring Cloud Alibaba Sentinel: `spring.cloud.sentinel.eager`. You could refer to this wiki: https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#more

**Comment by yiming33** [comment]
> You could manually trigger the initialization with `InitExecutor.doInit()`, or leverage this property item of Spring Cloud Alibaba Sentinel: `spring.cloud.sentinel.eager`. You could refer to this wiki: https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#more

这个我尝试过了，确实能饥饿加载，但第一次请求仍然很慢，所以才想问问是否还有别的办法
