### ISSUE TITLE
Sentinel-block.log Why are there multiple current limit logs in one second?

### ISSUE THREAD

**Issue by yehuali** [alibaba/Sentinel#898]
![image](https://user-images.githubusercontent.com/17173469/60853953-e4119c00-a230-11e9-8e4a-ec05aba9eb48.png)
问题:从日志上看觉得一个请求同时被两个规则同时拦住
期望:一个请求只会被一个规则拦截住
重现：在ParamFlowQpsDemo的initParamFlowRules方法中加入一条流控规则
 List<FlowRule> rules = new ArrayList<FlowRule>();
        FlowRule rule1 = new FlowRule();
        rule1.setResource(RESOURCE_KEY);
        // set limit qps to 20
        rule1.setCount(8);
        rule1.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule1.setLimitApp("default");
        rules.add(rule1);
        FlowRuleManager.loadRules(rules);

**Comment by yehuali** [comment]
推测是那个日志记录类，把限流的信息聚合后，按秒记录了

**Comment by cdfive** [comment]
参考：[https://github.com/alibaba/Sentinel/wiki/Metrics#history-resource-metrics](https://github.com/alibaba/Sentinel/wiki/Metrics#history-resource-metrics)
如果有block出现，`${home}\logs\csp\sentinel-block.log`会按秒把不同的异常的block数等记录下来。

这里理解日志可能需要注意，它是聚合后的指标数据，不是每次请求同时被两个规则拦住产生了两个不同的异常。
