### ISSUE TITLE
Thread pools should be created with NamedThreadFactory for identification

### ISSUE THREAD

**Issue by CodeIngL** [alibaba/Sentinel#9]
里面看到了NamedThreadFactory。为了更好区分线程信息，应该

    Executors.newScheduledThreadPool(x)

进行修改

 new ScheduledThreadPoolExecutor(X, new NamedThreadFactory("stl-${something}"));

**Comment by sczyh30** [comment]
Yes, the thread pools should be created with `NamedThreadFactory` for clear identification. We'll fix this. Thanks for your suggestion!
