### ISSUE TITLE
sentinel dashboard deployed in ecs cannot get metric data from local dev machine

### ISSUE THREAD

**Issue by li-deyu** [alibaba/Sentinel#900]
### Issue Description
I deployed sentinel dashboard in ecs and create a spring clond sentinel application in my local dev machine.
In sentinel dashboard web pages, i can see data in machine list,but cannot see data in monitor list and resource chain list.
if i deployed sentinel dashboard in my local dev machine too,it works well.

### exception message
bellow is the error log from sentinel-dashboard.log（192.168.1.105 is my local dev machine ip）：
`
2019-07-09 22:17:54 [pool-2-thread-1] ERROR c.a.c.s.d.metric.MetricFetcher - Failed to fetch metric from <http://192.168.1.105:8719/metric?startTime=1562681845000&endTime=1562681851000&refetch=false> (ConnectionException: Connection timed out: no further information)
`

### environment

- spring-cloud-dependencies：Greenwich.SR2

- spring-cloud-alibaba-dependencies：0.9.0.RELEASE

- sentinel dashboard：1.6.2

**Comment by jasonjoo2010** [comment]
Because the data in monitor board is fetched from the application node. Dashboard is deployed on ECS while the application is deployed on you local machine. Maybe your local machine can communicate to the dashboard through VPN or similar ways but Dashboard cannot do the same thing (To your local machine).

**Comment by sczyh30** [comment]
Yes, the network `ECS --> your localhost` is not accessible (in the pull-based model). You could try the out-of-box dashboard in the cloud: https://github.com/alibaba/Sentinel/wiki/AHAS-Sentinel-控制台 or deploy your demo to the ECS.

**Comment by li-deyu** [comment]
@jasonjoo2010 @sczyh30 ,thanks,i should correct some of my preconceived notions,i think sentinel work like nacos before.
