### ISSUE TITLE
ConfigUtil incompatible with Microsoft Windows

### ISSUE THREAD

**Issue by colinWaq** [alibaba/Sentinel#901]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

mvn clean package faild
### Describe what you expected to happen

mvn clean package success
### How to reproduce it (as minimally and precisely as possible)

PS G:\service\Sentinel-master> mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[WARNING] The project com.alibaba.csp:sentinel-benchmark:jar:1.7.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] sentinel-parent                                                    [pom]
[INFO] sentinel-core                                                      [jar]
[INFO] sentinel-extension                                                 [pom]
[INFO] sentinel-datasource-extension                                      [jar]
[INFO] sentinel-datasource-nacos                                          [jar]
[INFO] sentinel-datasource-zookeeper                                      [jar]
[INFO] sentinel-datasource-apollo                                         [jar]
[INFO] sentinel-datasource-redis                                          [jar]
[INFO] sentinel-annotation-aspectj                                        [jar]
[INFO] sentinel-transport                                                 [pom]
[INFO] sentinel-transport-common                                          [jar]
[INFO] sentinel-parameter-flow-control                                    [jar]
[INFO] sentinel-transport-simple-http                                     [jar]
[INFO] sentinel-transport-netty-http                                      [jar]
[INFO] sentinel-adapter                                                   [pom]
[INFO] sentinel-web-servlet                                               [jar]
[INFO] sentinel-dubbo-adapter                                             [jar]
[INFO] sentinel-apache-dubbo-adapter                                      [jar]
[INFO] sentinel-grpc-adapter                                              [jar]
[INFO] sentinel-api-gateway-adapter-common                                [jar]
[INFO] sentinel-zuul-adapter                                              [jar]
[INFO] sentinel-reactor-adapter                                           [jar]
[INFO] sentinel-spring-webflux-adapter                                    [jar]
[INFO] sentinel-spring-cloud-gateway-adapter                              [jar]
[INFO] sentinel-dashboard                                                 [jar]
[INFO] sentinel-demo                                                      [pom]
[INFO] sentinel-demo-basic                                                [jar]
[INFO] sentinel-demo-dynamic-file-rule                                    [jar]
[INFO] sentinel-demo-rocketmq                                             [jar]
[INFO] sentinel-demo-dubbo                                                [jar]
[INFO] sentinel-demo-nacos-datasource                                     [jar]
[INFO] sentinel-demo-zookeeper-datasource                                 [jar]
[INFO] sentinel-demo-apollo-datasource                                    [jar]
[INFO] sentinel-demo-annotation-spring-aop                                [jar]
[INFO] sentinel-demo-parameter-flow-control                               [jar]
[INFO] sentinel-demo-slot-chain-spi                                       [jar]
[INFO] sentinel-cluster                                                   [pom]
[INFO] sentinel-cluster-common-default                                    [jar]
[INFO] sentinel-cluster-client-default                                    [jar]
[INFO] sentinel-cluster-server-default                                    [jar]
[INFO] sentinel-demo-cluster                                              [pom]
[INFO] sentinel-demo-cluster-embedded                                     [jar]
[INFO] sentinel-demo-cluster-server-alone                                 [jar]
[INFO] sentinel-demo-command-handler                                      [jar]
[INFO] sentinel-demo-spring-webflux                                       [jar]
[INFO] sentinel-demo-apache-dubbo                                         [jar]
[INFO] sentinel-demo-spring-cloud-gateway                                 [jar]
[INFO] sentinel-demo-zuul-gateway                                         [jar]
[INFO] Sentinel JMH benchmark                                             [jar]
[INFO]
[INFO] ------------------< com.alibaba.csp:sentinel-parent >-------------------
[INFO] Building sentinel-parent 1.7.0-SNAPSHOT                           [1/49]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sentinel-parent ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.3:prepare-agent (default) @ sentinel-parent ---
[INFO] argLine set to -javaagent:C:\\Users\\Administrator\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.3\\org.jacoco.agent-0.8.3-runtime.jar=destfile=G:\\service\\Sentinel-master\\target\\jacoco.exec
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.3:report (report) @ sentinel-parent ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO]
[INFO] -------------------< com.alibaba.csp:sentinel-core >--------------------
[INFO] Building sentinel-core 1.7.0-SNAPSHOT                             [2/49]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sentinel-core ---
[INFO] Deleting G:\service\Sentinel-master\sentinel-core\target
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.3:prepare-agent (default) @ sentinel-core ---
[INFO] argLine set to -javaagent:C:\\Users\\Administrator\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.3\\org.jacoco.agent-0.8.3-runtime.jar=destfile=G:\\service\\Sentinel-master\\sentinel-core\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sentinel-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ sentinel-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 165 source files to G:\service\Sentinel-master\sentinel-core\target\classes
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[105,38] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[301,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[325,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[327,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[332,60] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[333,40] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[335,33] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/Striped64.java:[337,45] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[199,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[202,27] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[214,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[216,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[221,83] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[223,36] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[224,39] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java:[224,60] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[INFO] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/AbstractRule.java:  某些输入文件使用了未经检查或不安全的操作。
[INFO] /G:/service/Sentinel-master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/AbstractRule.java:  有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sentinel-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\service\Sentinel-master\sentinel-core\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ sentinel-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 53 source files to G:\service\Sentinel-master\sentinel-core\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ sentinel-core ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.alibaba.csp.sentinel.AsyncEntryIntegrationTest
INFO: log output type is: file
INFO: log charset is: utf-8
INFO: log base dir is: C:\Users\Administrator\logs\csp\
INFO: log name use pid is: false
abc: 1562727355143
Async result: 666
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.822 s - in com.alibaba.csp.sentinel.AsyncEntryIntegrationTest
[INFO] Running com.alibaba.csp.sentinel.AsyncEntryTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in com.alibaba.csp.sentinel.AsyncEntryTest
[INFO] Running com.alibaba.csp.sentinel.config.SentinelConfigTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in com.alibaba.csp.sentinel.config.SentinelConfigTest
[INFO] Running com.alibaba.csp.sentinel.ConstantsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.ConstantsTest
[INFO] Running com.alibaba.csp.sentinel.context.ContextTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.906 s - in com.alibaba.csp.sentinel.context.ContextTest
[INFO] Running com.alibaba.csp.sentinel.CtEntryTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.729 s - in com.alibaba.csp.sentinel.CtEntryTest
[INFO] Running com.alibaba.csp.sentinel.CtSphTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.587 s - in com.alibaba.csp.sentinel.CtSphTest
[INFO] Running com.alibaba.csp.sentinel.eagleeye.EagleEyeCoreUtilsTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in com.alibaba.csp.sentinel.eagleeye.EagleEyeCoreUtilsTest
[INFO] Running com.alibaba.csp.sentinel.EntryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.EntryTest
[INFO] Running com.alibaba.csp.sentinel.log.ConsoleHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.log.ConsoleHandlerTest
[INFO] Running com.alibaba.csp.sentinel.metric.extension.callback.MetricEntryCallbackTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in com.alibaba.csp.sentinel.metric.extension.callback.MetricEntryCallbackTest
[INFO] Running com.alibaba.csp.sentinel.metric.extension.callback.MetricExitCallbackTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in com.alibaba.csp.sentinel.metric.extension.callback.MetricExitCallbackTest
[INFO] Running com.alibaba.csp.sentinel.node.ClusterNodeTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.node.ClusterNodeTest
[INFO] Running com.alibaba.csp.sentinel.node.metric.MetricWriterTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.node.metric.MetricWriterTest
[INFO] Running com.alibaba.csp.sentinel.node.StatisticNodeTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.198 s - in com.alibaba.csp.sentinel.node.StatisticNodeTest
[INFO] Running com.alibaba.csp.sentinel.RecordLogTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.085 s - in com.alibaba.csp.sentinel.RecordLogTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.authority.AuthorityRuleCheckerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in com.alibaba.csp.sentinel.slots.block.authority.AuthorityRuleCheckerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.authority.AuthorityRuleManagerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in com.alibaba.csp.sentinel.slots.block.authority.AuthorityRuleManagerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.authority.AuthoritySlotTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.slots.block.authority.AuthoritySlotTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManagerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManagerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.degrade.DegradeTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.582 s - in com.alibaba.csp.sentinel.slots.block.degrade.DegradeTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.controller.DefaultControllerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in com.alibaba.csp.sentinel.slots.block.flow.controller.DefaultControllerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.controller.RateLimiterControllerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.976 s - in com.alibaba.csp.sentinel.slots.block.flow.controller.RateLimiterControllerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.controller.WarmUpControllerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.412 s - in com.alibaba.csp.sentinel.slots.block.flow.controller.WarmUpControllerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.controller.WarmUpRateLimiterControllerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.998 s - in com.alibaba.csp.sentinel.slots.block.flow.controller.WarmUpRateLimiterControllerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.FlowPartialIntegrationTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s - in com.alibaba.csp.sentinel.slots.block.flow.FlowPartialIntegrationTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.FlowRuleCheckerTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.slots.block.flow.FlowRuleCheckerTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.FlowRuleComparatorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.slots.block.flow.FlowRuleComparatorTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.FlowRuleTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.005 s - in com.alibaba.csp.sentinel.slots.block.flow.FlowRuleTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.flow.FlowSlotTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.slots.block.flow.FlowSlotTest
[INFO] Running com.alibaba.csp.sentinel.slots.block.system.SystemRuleTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.slots.block.system.SystemRuleTest
[INFO] Running com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterNodeBuilderTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterNodeBuilderTest
[INFO] Running com.alibaba.csp.sentinel.slots.logger.EagleEyeLogUtilTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.137 s - in com.alibaba.csp.sentinel.slots.logger.EagleEyeLogUtilTest
[INFO] Running com.alibaba.csp.sentinel.slots.nodeselector.NodeSelectorTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in com.alibaba.csp.sentinel.slots.nodeselector.NodeSelectorTest
[INFO] Running com.alibaba.csp.sentinel.slots.statistic.base.LeapArrayTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.891 s - in com.alibaba.csp.sentinel.slots.statistic.base.LeapArrayTest
[INFO] Running com.alibaba.csp.sentinel.slots.statistic.metric.ArrayMetricTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 s - in com.alibaba.csp.sentinel.slots.statistic.metric.ArrayMetricTest
[INFO] Running com.alibaba.csp.sentinel.slots.statistic.metric.BucketLeapArrayTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.406 s - in com.alibaba.csp.sentinel.slots.statistic.metric.BucketLeapArrayTest
[INFO] Running com.alibaba.csp.sentinel.slots.statistic.metric.FutureBucketLeapArrayTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in com.alibaba.csp.sentinel.slots.statistic.metric.FutureBucketLeapArrayTest
[INFO] Running com.alibaba.csp.sentinel.slots.statistic.metric.OccupiableBucketLeapArrayTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.837 s - in com.alibaba.csp.sentinel.slots.statistic.metric.OccupiableBucketLeapArrayTest
[INFO] Running com.alibaba.csp.sentinel.SphOTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.SphOTest
[INFO] Running com.alibaba.csp.sentinel.SphUTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.SphUTest
[INFO] Running com.alibaba.csp.sentinel.TracerTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.TracerTest
[INFO] Running com.alibaba.csp.sentinel.util.ConfigUtilTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.alibaba.csp.sentinel.util.ConfigUtilTest
[ERROR] testLoadProperties(com.alibaba.csp.sentinel.util.ConfigUtilTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
        at com.alibaba.csp.sentinel.util.ConfigUtilTest.testLoadProperties(ConfigUtilTest.java:59)

[INFO] Running com.alibaba.csp.sentinel.util.IdUtilTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.alibaba.csp.sentinel.util.IdUtilTest
[INFO] Running com.alibaba.csp.sentinel.util.MethodUtilTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in com.alibaba.csp.sentinel.util.MethodUtilTest
[INFO] Running com.alibaba.csp.sentinel.util.StringUtilTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.util.StringUtilTest
[INFO] Running com.alibaba.csp.sentinel.util.VersionUtilTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.alibaba.csp.sentinel.util.VersionUtilTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ConfigUtilTest.testLoadProperties:59 NullPointer
[INFO]
[ERROR] Tests run: 167, Failures: 0, Errors: 1, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for sentinel-parent 1.7.0-SNAPSHOT:
[INFO]
[INFO] sentinel-parent .................................... SUCCESS [  0.746 s]
[INFO] sentinel-core ...................................... FAILURE [ 49.272 s]
[INFO] sentinel-extension ................................. SKIPPED
[INFO] sentinel-datasource-extension ...................... SKIPPED
[INFO] sentinel-datasource-nacos .......................... SKIPPED
[INFO] sentinel-datasource-zookeeper ...................... SKIPPED
[INFO] sentinel-datasource-apollo ......................... SKIPPED
[INFO] sentinel-datasource-redis .......................... SKIPPED
[INFO] sentinel-annotation-aspectj ........................ SKIPPED
[INFO] sentinel-transport ................................. SKIPPED
[INFO] sentinel-transport-common .......................... SKIPPED
[INFO] sentinel-parameter-flow-control .................... SKIPPED
[INFO] sentinel-transport-simple-http ..................... SKIPPED
[INFO] sentinel-transport-netty-http ...................... SKIPPED
[INFO] sentinel-adapter ................................... SKIPPED
[INFO] sentinel-web-servlet ............................... SKIPPED
[INFO] sentinel-dubbo-adapter ............................. SKIPPED
[INFO] sentinel-apache-dubbo-adapter ...................... SKIPPED
[INFO] sentinel-grpc-adapter .............................. SKIPPED
[INFO] sentinel-api-gateway-adapter-common ................ SKIPPED
[INFO] sentinel-zuul-adapter .............................. SKIPPED
[INFO] sentinel-reactor-adapter ........................... SKIPPED
[INFO] sentinel-spring-webflux-adapter .................... SKIPPED
[INFO] sentinel-spring-cloud-gateway-adapter .............. SKIPPED
[INFO] sentinel-dashboard ................................. SKIPPED
[INFO] sentinel-demo ...................................... SKIPPED
[INFO] sentinel-demo-basic ................................ SKIPPED
[INFO] sentinel-demo-dynamic-file-rule .................... SKIPPED
[INFO] sentinel-demo-rocketmq ............................. SKIPPED
[INFO] sentinel-demo-dubbo ................................ SKIPPED
[INFO] sentinel-demo-nacos-datasource ..................... SKIPPED
[INFO] sentinel-demo-zookeeper-datasource ................. SKIPPED
[INFO] sentinel-demo-apollo-datasource .................... SKIPPED
[INFO] sentinel-demo-annotation-spring-aop ................ SKIPPED
[INFO] sentinel-demo-parameter-flow-control ............... SKIPPED
[INFO] sentinel-demo-slot-chain-spi ....................... SKIPPED
[INFO] sentinel-cluster ................................... SKIPPED
[INFO] sentinel-cluster-common-default .................... SKIPPED
[INFO] sentinel-cluster-client-default .................... SKIPPED
[INFO] sentinel-cluster-server-default .................... SKIPPED
[INFO] sentinel-demo-cluster .............................. SKIPPED
[INFO] sentinel-demo-cluster-embedded ..................... SKIPPED
[INFO] sentinel-demo-cluster-server-alone ................. SKIPPED
[INFO] sentinel-demo-command-handler ...................... SKIPPED
[INFO] sentinel-demo-spring-webflux ....................... SKIPPED
[INFO] sentinel-demo-apache-dubbo ......................... SKIPPED
[INFO] sentinel-demo-spring-cloud-gateway ................. SKIPPED
[INFO] sentinel-demo-zuul-gateway ......................... SKIPPED
[INFO] Sentinel JMH benchmark ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.853 s
[INFO] Finished at: 2019-07-10T10:56:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project sentinel-core: There are test failures.
[ERROR]
[ERROR] Please refer to G:\service\Sentinel-master\sentinel-core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sentinel-core
PS G:\service\Sentinel-master>

### Tell us your environment
win 10, jdk1.8  maven 10.0

**Comment by sczyh30** [comment]
cc @linlinisme

**Comment by linlinisme** [comment]
@colinWaq hey, I also operate the `mvn clean pacakage` in my local, it is fine. But my local env is 
mac and my maven is 3.3.9 version. I think the npe problem is because:
`            Properties properties = ConfigUtil.loadProperties(file.getAbsolutePath());
` 
**the return properties is null**. In this case, the reason may be 
```
String userDir = System.getProperty("user.dir");
            file = new File(addSeparator(userDir) + "target/classes/" + fileName);
            if (!file.exists()) {
                file.createNewFile();
            }
            BufferedWriter out = new BufferedWriter(new FileWriter(file));
            out.write(LOG_OUTPUT_TYPE + "=" + logOutputType);
            out.write("\n");
            out.write(LOG_DIR + "=" + dir);
            out.flush();
            out.close();
```
`propertiesTest.properties` don't create correctly or don't  write success. Would you please check your local file?

**Comment by linlinisme** [comment]
I had found the reason. The line break  is different between mac/linux and windows. I will fixed soon

**Comment by linlinisme** [comment]
I had found out the reason, a PR will be later :)

**Comment by colinWaq** [comment]
> I had found out the reason, a PR will be later :)

ok    i will try again later
