### ISSUE TITLE
Stand-alone flowrule limitAPP fills in values other than default does not take effect

### ISSUE THREAD

**Issue by Crazy10552** [alibaba/Sentinel#902]
## Issue Description

Type: *bug report* or *feature request*

### now i do flow_rule test,while i set limitApp with everything but default,this rule do not work，how to fix it

>flow_rule data
flowrule规则信息
[
	{
		"clusterMode": false,
		"controlBehavior": 0,
		"count": 1.0,
		"createTime": 1561360295000,
		"flowRuleId": 5,
		"grade": 1,
		"isDeleted": "N",
		"limitApp": "sentinel-dubbo-service-demo",
		"resource": "com.sentinel.learning.datasource.api.EnumServiceDubbo",
		"strategy": 0,
		"updateTime": 1562729567000
	},
	{
		"clusterMode": false,
		"controlBehavior": 0,
		"count": 1.0,
		"createTime": 1561360295000,
		"flowRuleId": 6,
		"grade": 1,
		"isDeleted": "N",
		"limitApp": "default",
		"resource": "com.sentinel.learning.datasource.api.EnumServiceDubbo2",
		"strategy": 0,
		"updateTime": 1562729570000
	}
]

### dash-board flow_rule配置信息
![image](https://user-images.githubusercontent.com/8501490/60938799-f4e11100-a307-11e9-919d-164f5143adc2.png)

### dash-board实时监控信息
![image](https://user-images.githubusercontent.com/8501490/60938944-83ee2900-a308-11e9-957e-d9e1686ca0d0.png)

### Tell us your environment
dubbo 2.5.3
sentinel-version 1.6.1

### Anything else we need to know?
how to set

**Comment by sczyh30** [comment]
可以参考 [FAQ 里面相关内容](https://github.com/alibaba/Sentinel/wiki/FAQ#q-怎么针对特定调用端限流比如我想针对某个-ip-或者来源应用进行限流规则里面-limitapp流控应用的作用)，`limitApp` 需填 Dubbo 调用方的 application name（注意是 Dubbo 里配置的应用名而不是 Sentinel 的 `project.name`）。

---

You could refer to the document of Dubbo Adapter: https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-dubbo-adapter/README.md#flow-control-based-on-caller

**Comment by Crazy10552** [comment]
> 可以参考 [FAQ 里面相关内容](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E6%80%8E%E4%B9%88%E9%92%88%E5%AF%B9%E7%89%B9%E5%AE%9A%E8%B0%83%E7%94%A8%E7%AB%AF%E9%99%90%E6%B5%81%E6%AF%94%E5%A6%82%E6%88%91%E6%83%B3%E9%92%88%E5%AF%B9%E6%9F%90%E4%B8%AA-ip-%E6%88%96%E8%80%85%E6%9D%A5%E6%BA%90%E5%BA%94%E7%94%A8%E8%BF%9B%E8%A1%8C%E9%99%90%E6%B5%81%E8%A7%84%E5%88%99%E9%87%8C%E9%9D%A2-limitapp%E6%B5%81%E6%8E%A7%E5%BA%94%E7%94%A8%E7%9A%84%E4%BD%9C%E7%94%A8)，`limitApp` 需填 Dubbo 调用方的 application name（注意是 Dubbo 里配置的应用名而不是 Sentinel 的 `project.name`）。
> 
> You could refer to the document of Dubbo Adapter: https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-dubbo-adapter/README.md#flow-control-based-on-caller

zk注册中心上看到的服务注册信息
![image](https://user-images.githubusercontent.com/8501490/60943600-0a126b80-a319-11e9-817d-f80238f6cb70.png)

另外，sentinel dash board 这个控制页面上也已经显示了APP name的属性，和我配置的是一样的
![image](https://user-images.githubusercontent.com/8501490/60943743-6e352f80-a319-11e9-9762-6f3bb843a651.png)

**Comment by cdfive** [comment]
dubbo服务`sentinel-dubbo-service-demo`：
资源`com.sentinel.learning.datasource.api.EnumServiceDubbo`
"limitApp": "sentinel-dubbo-service-demo"

这里的`limitApp`，如果不是的`default`的话，是需要配置为**调用方**(consumer)的应用名。
不知道你是如何调用接口测试的。
比如是通过另一个dubbo服务`sentinel-dubbo-service-demo2`，来调用这个接口，
`limitApp`就可以配置为`sentinel-dubbo-service-demo2`。

具体原理还是上面的参考链接，**Flow control based on caller**这个章节可能需要再看看，特别是里面的**Note**。

大概描述就是：
1. 比如`sentinel-dubbo-service-demo2`作为调用方，调用了`sentinel-dubbo-service-demo`应用的接口，
资源名称是`com.sentinel.learning.datasource.api.EnumServiceDubbo`；

2. Sentinel的`DubboAppContextFilter`会把调用方(`sentinel-dubbo-service-demo2`)的**应用名称**(`sentinel-dubbo-service-demo2`)通过附件的方式传递到提供方(`sentinel-dubbo-service-demo`)这里，然后提供方就知道了它的调用来源是`sentinel-dubbo-service-demo2`。

前提是调用方和提供方都使用了`sentinel-dubbo-adaptor`。

所以**规则**里配置"limitApp": "sentinel-dubbo-service-demo"是**不生效的**，因为现在提供方没有来源于`sentinel-dubbo-service-demo`的调用，所以全部通过。

**Comment by Crazy10552** [comment]
> dubbo服务`sentinel-dubbo-service-demo`：
> 资源`com.sentinel.learning.datasource.api.EnumServiceDubbo`
> "limitApp": "sentinel-dubbo-service-demo"
> 
> 这里的`limitApp`，如果不是的`default`的话，是需要配置为**调用方**(consumer)的应用名。
> 不知道你是如何调用接口测试的。
> 比如是通过另一个dubbo服务`sentinel-dubbo-service-demo2`，来调用这个接口，
> `limitApp`就可以配置为`sentinel-dubbo-service-demo2`。
> 
> 具体原理还是上面的参考链接，**Flow control based on caller**这个章节可能需要再看看，特别是里面的**Note**。
> 
> 大概描述就是：
> 
> 1. 比如`sentinel-dubbo-service-demo2`作为调用方，调用了`sentinel-dubbo-service-demo`应用的接口，
>    资源名称是`com.sentinel.learning.datasource.api.EnumServiceDubbo`；
> 2. Sentinel的`DubboAppContextFilter`会把调用方(`sentinel-dubbo-service-demo2`)的**应用名称**(`sentinel-dubbo-service-demo2`)通过附件的方式传递到提供方(`sentinel-dubbo-service-demo`)这里，然后提供方就知道了它的调用来源是`sentinel-dubbo-service-demo2`。
> 
> 前提是调用方和提供方都使用了`sentinel-dubbo-adaptor`。
> 
> 所以**规则**里配置"limitApp": "sentinel-dubbo-service-demo"是**不生效的**，因为现在提供方没有来源于`sentinel-dubbo-service-demo`的调用，所以全部通过。

ok，这么一说我就彻底明白了，之前进入误区了，thanks
