### ISSUE TITLE
SystemRule usage

### ISSUE THREAD

**Issue by Crazy10552** [alibaba/Sentinel#905]
## Issue Description
rule do not work all and the olny rule which works but it do not set as i want 
Type: *bug report* 

> I set five system rule,use zookeeperdatasource,now receive system rule update data
![image](https://user-images.githubusercontent.com/8501490/61094946-0f3ff980-a484-11e9-8311-740a1b420950.png)

>then i use  curl http://127.0.0.1:8720/getRules?type=system to get my rule

>debug find  [SystemRuleManager ](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/system/SystemRuleManager.java)  code like that
![image](https://user-images.githubusercontent.com/8501490/61095370-d43ec580-a485-11e9-950a-a247b2e8b427.png)
>only first rule can seem to be seen, someone like the first rule,but the only rule become five rule
![image](https://user-images.githubusercontent.com/8501490/61095534-6777fb00-a486-11e9-9e07-36cb7bb428e1.png)

>also dashboard can not show system which i set highestCpuUsage
![image](https://user-images.githubusercontent.com/8501490/61095627-d0f80980-a486-11e9-8df3-39e0c8635947.png)

![image](https://user-images.githubusercontent.com/8501490/61095646-e3724300-a486-11e9-9777-e783f9e12013.png)

### Tell us your environment
dubbo 2.5.3
sentinel version 1.6.2

**Comment by sczyh30** [comment]
> then i use curl http://127.0.0.1:8720/getRules?type=system to get my rule

What rules did you get? Could you please provide the rules that you are actually setting, and the rules that the `SystemRuleManager actually` loaded?

> also dashboard can not show system which i set highestCpuUsage

That's not updated in the dashboard. Would you like to contribute?

**Comment by Crazy10552** [comment]
> > then i use curl http://127.0.0.1:8720/getRules?type=system to get my rule
> 
> What rules did you get? Could you please provide the rules that you are actually setting, and the rules that the `SystemRuleManager actually` loaded?
> 
> > also dashboard can not show system which i set highestCpuUsage
> 
> That's not updated in the dashboard. Would you like to contribute?



> > then i use curl http://127.0.0.1:8720/getRules?type=system to get my rule
> 
> What rules did you get? Could you please provide the rules that you are actually setting, and the rules that the `SystemRuleManager actually` loaded?
> 
> > also dashboard can not show system which i set highestCpuUsage
> 
> That's not updated in the dashboard. Would you like to contribute?

**Comment by Crazy10552** [comment]
> > then i use curl http://127.0.0.1:8720/getRules?type=system to get my rule
> 
> What rules did you get? Could you please provide the rules that you are actually setting, and the rules that the `SystemRuleManager actually` loaded?

### my original system_rule data
     >[{"avgRt":1,"createTime":1563240045000,"highestCpuUsage":0.1,"highestSystemLoad":100.0,"isDeleted":"N","limitApp":"default","maxThread":100,"qps":100.0,"resource":"sentinel-dubbo-web-demo","systemRuleId":7,"updateTime":1563240134000},{"avgRt":2,"createTime":1563240083000,"highestCpuUsage":0.2,"highestSystemLoad":200.0,"isDeleted":"N","limitApp":"default","maxThread":200,"qps":200.0,"resource":"sentinel-dubbo-web-demo","systemRuleId":9,"updateTime":1563240083000},{"avgRt":3,"createTime":1563240094000,"highestCpuUsage":0.3,"highestSystemLoad":300.0,"isDeleted":"N","limitApp":"default","maxThread":300,"qps":300.0,"resource":"sentinel-dubbo-web-demo","systemRuleId":11,"updateTime":1563240094000}]

###  system_rule i got with curl http://127.0.0.1:8720/getRules?type=system (SystemRuleManager actually loaded)
>[{"avgRt":-1,"highestCpuUsage":-1.0,"highestSystemLoad":100.0,"maxThread":-1,"qps":-1.0},{"avgRt":-1,"highestCpuUsage":0.1,"highestSystemLoad":-1.0,"maxThread":-1,"qps":-1.0},{"avgRt":1,"highestCpuUsage":-1.0,"highestSystemLoad":-1.0,"maxThread":-1,"qps":-1.0},{"avgRt":-1,"highestCpuUsage":-1.0,"highestSystemLoad":-1.0,"maxThread":100,"qps":-1.0},{"avgRt":-1,"highestCpuUsage":-1.0,"highestSystemLoad":-1.0,"maxThread":-1,"qps":100.0}]

> 
> > also dashboard can not show system which i set highestCpuUsage
> 
> That's not updated in the dashboard. Would you like to contribute?
   i fix it on my local ,but  i have no authority to push my request,how to do it

**Comment by sczyh30** [comment]
You can only create at most one `SystemRule` of each type. The `getRules` command will convert each type to individual rules.

系统规则每种只能创建一条，多条的话会以几条中的最小阈值为准。`getRules` API 会进行转换，每种策略转换成一条单独的规则。

> I fix it on my local, but I have no authority to push my request, how to do it

You could refer to https://github.com/alibaba/Sentinel/wiki/开源贡献指南
The related issue: #916
