### ISSUE TITLE
Queueing mode does not take effect in cluster flow control

### ISSUE THREAD

**Issue by zhangzl0119** [alibaba/Sentinel#906]
选择独立模式的集群限流，选择的是排队等待模式，超时时间是50000ms，但是还是会直接拒绝，限流无效。
如图：
![TIM截图20190712110240](https://user-images.githubusercontent.com/32055976/61099511-2b986200-a495-11e9-8c68-1205a0d28794.png)
![TIM截图20190712110309](https://user-images.githubusercontent.com/32055976/61099578-67332c00-a495-11e9-9ab2-eeb06a1944ba.png)
![TIM截图20190712110128](https://user-images.githubusercontent.com/32055976/61099583-6b5f4980-a495-11e9-87a5-1885d918fc1f.png)
![TIM截图20190712110145](https://user-images.githubusercontent.com/32055976/61099585-6d290d00-a495-11e9-998d-1007a96f348b.png)

**Comment by sczyh30** [comment]
集群限流目前不支持排队等待模式。

---

Uniform rate limiting (queueing) is not supported in cluster flow control.

**Comment by zhangzl0119** [comment]
现在集群只支持什么模式？ 后续会有计划支持吗？

**Comment by sczyh30** [comment]
Would you like to illustrate your scenario? Why the cluster uniform rate limiting mode is needed?

**Comment by zhangzl0119** [comment]
我们想限制集群总的qps， 比如集群总的qps为1，太大可能造成系统崩溃。但又不想立马失败，排队等待一段时间，等流量过去以后，再慢慢处理。
