### ISSUE TITLE
A problem about using Sentinel as a circuit breaker of Feign

### ISSUE THREAD

**Issue by wudgaby** [alibaba/Sentinel#909]
问题描述
如果post提交的content-type 为 x-www-form-urlencoded  
而后调用feign时,content-type会变为x-www-form-urlencoded .  
而feign接收方为application/json.从而导致以下异常

`org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported`

**Comment by sczyh30** [comment]
I don't think it's related to Sentinel Feign integration. cc @fangjian0423

**Comment by fangjian0423** [comment]
we don't modify content-type in sentinel feign.

if you use hystrix, i think the result is same.

**Comment by wudgaby** [comment]
OK.I checked it.
It was my configuration that caused the problem

**Comment by qiaojiang2** [comment]
>  It was my configuration that caused the problem

What configuration causes it? I had the same problem.
I'm using feign to call a dependency interface defined as
```
 "@requestmapping ("/decrypt")
Public ResponseResult decryptNotifyMsg(@requestbody OrderMsgReqDto OrderMsgReqDto);"
```
An error occurs when the call is made. If I change the configuration to "feign.sentinel.enabled=false", that's fine.

if I use this definition, I'll be fine
`@RequestMapping(value = "/internal/pay/checkNotify", method = RequestMethod.POST)
    boolean checkNotify(@RequestParam(value = "paymentId") String paymentId,
            @RequestParam(value = "tradeNo") String tradeNo, @RequestParam(value = "status") int status,
            @RequestParam(value = "platform") String platform, @RequestParam(value = "platformtag") String platformtag,
            @RequestParam(value = "tradeTime") String tradeTime,
            @RequestParam(value = "notifyOrignMsg") String notifyOrignMsg,
            @RequestParam(value = "tradeStatus") String tradeStatus);`
