### ISSUE TITLE
Question about Sentinel DegradeRule

### ISSUE THREAD

**Issue by eacdy** [alibaba/Sentinel#910]
Wiki：<[https://github.com/alibaba/Sentinel/wiki/%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7#%E9%99%8D%E7%BA%A7%E7%AD%96%E7%95%A5](https://github.com/alibaba/Sentinel/wiki/熔断降级#降级策略)>

里面说：

> - 平均响应时间 (`DEGRADE_GRADE_RT`)：当资源的平均响应时间超过阈值（`DegradeRule` 中的 `count`，以 ms 为单位）之后，资源进入准降级状态。如果接下来 1s 内持续进入 5 个请求（即 QPS >= 5），它们的 RT 都持续超过这个阈值，那么在接下的时间窗口（`DegradeRule` 中的 `timeWindow`，以 s 为单位）之内，对这个方法的调用都会自动地熔断（抛出 `DegradeException`）。注意 Sentinel 默认统计的 RT 上限是 4900 ms，**超出此阈值的都会算作 4900 ms**，若需要变更此上限可以通过启动配置项 `-Dcsp.sentinel.statistic.max.rt=xxx` 来配置。

我觉得这里描述不太对，我看了代码，找到 `com.alibaba.csp.sentinel.slots.block.degrade.DegradeRule#passCheck` 发现和Wiki描述不大一致。

代码的意思，我的理解是这样的：

> 如果平均响应时间（秒级统计）超过阈值，并且在时间窗口内进入的请求 >= 5，就会触发降级。
>
> 根本不会计算
>
> > 如果接下来 1s 内持续进入 5 个请求（即 QPS >= 5），它们的 RT 都持续超过这个阈值，那么在接下的时间窗口（`DegradeRule` 中的 `timeWindow`，以 s 为单位）之内，对这个方法的调用都会自动地熔断（抛出 `DegradeException`）。

```java
// com.alibaba.csp.sentinel.slots.block.degrade.DegradeRule#passCheck

@Override
public boolean passCheck(Context context, DefaultNode node, int acquireCount, Object... args) {
  if (cut.get()) {
    return false;
  }

  ClusterNode clusterNode = ClusterBuilderSlot.getClusterNode(this.getResource());
  if (clusterNode == null) {
    return true;
  }

  if (grade == RuleConstant.DEGRADE_GRADE_RT) {
    double rt = clusterNode.avgRt();
    if (rt < this.count) {
      passCount.set(0);
      return true;
    }

    // Sentinel will degrade the service only if count exceeds.
    if (passCount.incrementAndGet() < RT_MAX_EXCEED_N) {
      return true;
    }
  } 
  // ...
}
```

**Comment by eacdy** [comment]
@sczyh30 @CarpenterLee

**Comment by sczyh30** [comment]
Thanks for reporting! I'll refine the document later.
