### ISSUE TITLE
Does ParamFlowRule and cluster FlowRule in token server support persistence via WritableDataSource?

### ISSUE THREAD

**Issue by eacdy** [alibaba/Sentinel#912]
如题，热点参数流控规则、集群流控规则不支持持久化吗？

我尝试用拉模式实现规则的持久化，相关代码在这里：
<http://www.itmuch.com/spring-cloud-alibaba/sentinel-rules-persistence-pull-mode/>

举个例子：
```java
// 流控规则
        ReadableDataSource<String, List<FlowRule>> flowRuleRDS = new FileRefreshableDataSource<>(
            flowRulePath,
            flowRuleListParser
        );
        FlowRuleManager.register2Property(flowRuleRDS.getProperty());
        WritableDataSource<List<FlowRule>> flowRuleWDS = new FileWritableDataSource<>(
            flowRulePath,
            this::encodeJson
        );
        WritableDataSourceRegistry.registerFlowDataSource(flowRuleWDS);
```

但 `com.alibaba.csp.sentinel.transport.util.WritableDataSourceRegistry` 里面只支持
```
    private static WritableDataSource<List<FlowRule>> flowDataSource = null;
    private static WritableDataSource<List<AuthorityRule>> authorityDataSource = null;
    private static WritableDataSource<List<DegradeRule>> degradeDataSource = null;
    private static WritableDataSource<List<SystemRule>> systemSource = null;
```

没有ParamFlowRule等等其他规则。
所以，ParamFlowRule是不支持用拉模式持久化吗？

我找到了这个Issue，里面有一些讨论：<https://github.com/alibaba/Sentinel/issues/414>
但没有找到示例代码，能否帮忙解答：
1. 是否支持拉模式持久化？
2. 如果支持，是否能够帮忙提供一下示例代码？

**Comment by sczyh30** [comment]
For parameter flow control, you could register the `WritableDataSource` via `ModifyParamFlowRulesCommandHandler#setWritableDataSource` method.

For cluster flow control (rules of the token server), it's not supported (and not recommended) with the `WritableDataSource`.

**Comment by eacdy** [comment]
@sczyh30 Thanks a lot.
> For cluster flow control (rules of the token server), it's not supported (and not recommended) with the WritableDataSource.

So, How to persist the rules of the token server?

**Comment by eacdy** [comment]
@sczyh30 
我觉得官方是否能提供一个完整的Demo，每种规则用拉模式是怎么持久化的；
用推模式是怎么持久化的。

目前感觉使用的心智负担挺重的……

**Comment by sczyh30** [comment]
持久化的话 pull 模式可以参考：https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-dynamic-file-rule

push 模式是我们推荐的方式，push 模式改造控制台的文档可以完善一下，欢迎一起来改进文档~

**Comment by songxianjia** [comment]
@sczyh30 push模式可以一次把规则push到所有的节点吗?
