### ISSUE TITLE
Sentry current limit is invalid

### ISSUE THREAD

**Issue by helei810304** [alibaba/Sentinel#915]
List<FlowRule> rules = new ArrayList<>();
                FlowRule rule = new FlowRule();
                rule.setCount(10);
                rule.setResource("lcn");
                rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
                rules.add(rule);

        FlowRuleManager.loadRules(rules);
        for(int i=0;i<5000;i++){
            com.alibaba.csp.sentinel.Entry entry = null;
            try {
                System.out.println(i);
                entry = SphU.entry("lcn");
            }catch (BlockException e){
               throw e ;
            }finally {
                if(entry != null){
                    entry.close();
                }
            }
        }

我写了个main 函数，来跑这个东西，但是在第10个，被限流了，求解释
每个finally都有释放啊

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
根据 issue template 详细描述一下问题以及预期效果？

**Comment by sczyh30** [comment]
Closing this due to no response.
