### ISSUE TITLE
How to provide args in parameter flow control

### ISSUE THREAD

**Issue by liran0705** [alibaba/Sentinel#917]
### Describe what happened (or what feature you want)
How to configure PARAMS with Apollo to configure hotspot parameter current limiting? Now rules include resource, count, grade, durationInSec, control Behavior, and

Max Queueing TimeMs, paramIdx, paramFlowItemList, clusterMode, clusterConfig can be configured, but how to configure the hot parameters?

### Describe what you expected to happen

Does current limiting of hot spot parameters need to be combined with hard coding (SphU. entry method)? Can you configure it only with Apollo?
### How to reproduce it (as minimally and precisely as possible)

1. Apollo configure:
{
        "resource": "paramFlowUid",
        "count": 50,
        "grade": 1,
        "controlBehavior": 0,
        "paramIdx": 0
    }
2.  code :
/**
     * 热点参数限流--热点参数为uid
     */
    @ApiOperation(value = "热点参数限流api", notes = "热点参数限流api")
    @SentinelResource(value = "paramFlowUid")
    @SuppressWarnings("all")
    @PostMapping("freqParamFlowUid.do")
    public @ResponseBody String freqParamFlowUid(@RequestParam("uid") Long uid,@RequestParam("goodsId") Long goodsId) {
    	Entry entry = null;
        String retVal;
        try{
            // 只对参数uid进行限流，参数goodsId不进行限制
            entry = SphU.entry("paramFlowUid", EntryType.IN, 1, uid);
            retVal = "passed";
        }catch(BlockException e){
            retVal = "blocked";
        }finally {
            if(entry!=null){
                entry.exit();
            }
        }
        return retVal + "=====uid: " + uid + ", goodsId: " + goodsId;
    }
3.  result 
![image](https://user-images.githubusercontent.com/45581895/61342699-aee2fa80-a87d-11e9-94d1-2cd0333def15.png)

### Tell us your environment
springcloud、Apollo

**Comment by liran0705** [comment]
please help me, thanks.

**Comment by sczyh30** [comment]
You may refer to: https://github.com/alibaba/Sentinel/wiki/热点参数限流#基本使用

The parameters are dynamic so it's not supported to provide via Apollo.

**Comment by liran0705** [comment]
> You may refer to: [https://github.com/alibaba/Sentinel/wiki/热点参数限流#基本使用](https://github.com/alibaba/Sentinel/wiki/%E7%83%AD%E7%82%B9%E5%8F%82%E6%95%B0%E9%99%90%E6%B5%81#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8)
> 
> The parameters are dynamic so it's not supported to provide via Apollo.

So how should we use the hot spot parameter rule? I tried to configure the rules with Apollo, using the code SphU. entry  transfer point parameter, which is problematic. So, hot parameter rules can only be implemented by code, can't they be configured with Apollo?

**Comment by liran0705** [comment]
> You may refer to: [https://github.com/alibaba/Sentinel/wiki/热点参数限流#基本使用](https://github.com/alibaba/Sentinel/wiki/%E7%83%AD%E7%82%B9%E5%8F%82%E6%95%B0%E9%99%90%E6%B5%81#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8)
> 
> The parameters are dynamic so it's not supported to provide via Apollo.

Apollo configuration, code, and results are all above. Thanks

**Comment by sczyh30** [comment]
热点参数传入参数的方式参考：https://github.com/alibaba/Sentinel/wiki/热点参数限流#基本使用
规则配置可通过动态规则源、控制台或 ParamFlowRuleManager 的形式手动加载。
