### ISSUE TITLE
Black and White List Configuration

### ISSUE THREAD

**Issue by liran0705** [alibaba/Sentinel#918]
### Describe what happened (or what feature you want)

How to configure limitApp in black-and-white list control with Apollo and how to define limitApp in code
### Describe what you expected to happen
Using Apollo to configure limitApp in black-and-white list control can achieve the desired control effect.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
springcloud、Apollo

**Comment by liran0705** [comment]
please help me, thanks.

**Comment by sczyh30** [comment]
You may refer to:

- FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ
