### ISSUE TITLE
dubbo接入dashboard，实时监控将consumer和provider的指标都汇总，导致监控数据为实际值的两倍。

### ISSUE THREAD

**Issue by berockguo** [alibaba/Sentinel#92]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

dubbo接入dashboard，实时监控将consumer和provider的指标都汇总，导致监控数据为实际值的两倍。

### How to reproduce it (as minimally and precisely as possible)

1. dubbo-consumer接入dubbo-adaptor和dashboard
2. dubbo-provider接入dubbo-adaptor和dashboard
3. dashboard显示的实时监控为consumer和provider合并值

**Comment by CarpenterLee** [comment]
Dashboard will aggregate metrics with the same appName. To solve your problem, just use `-Dproject.name=xxx` to assign different app name of Dubbo provider and Dubbo consumer.
