### ISSUE TITLE
Controller to Service,Service Unable to limit current.

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/Sentinel#923]
sentinel-version : 1.4.1
![image](https://user-images.githubusercontent.com/3397316/61294606-c92ec100-a808-11e9-80d1-d8d1e7799b78.png)

Controller:
![image](https://user-images.githubusercontent.com/3397316/61294563-aef4e300-a808-11e9-89e5-26472926f66f.png)
Service:
![image](https://user-images.githubusercontent.com/3397316/61294632-d8ae0a00-a808-11e9-997b-e6974c80ed12.png)

dashboard no view service:
![image](https://user-images.githubusercontent.com/3397316/61294647-e5326280-a808-11e9-8e6b-05791f7b43ca.png)

all that pass
![image](https://user-images.githubusercontent.com/3397316/61294737-127f1080-a809-11e9-9ced-2539f6903959.png)

that is way? can you help me......

**Comment by cdfive** [comment]
Has the `SentinelResourceAspect` bean registered?

```java
@Configuration
public class SentinelAspectConfiguration {
    @Bean
    public SentinelResourceAspect sentinelResourceAspect() {
        return new SentinelResourceAspect();
    }
}
```

**Comment by cookiejoo** [comment]
> Has the `SentinelResourceAspect` bean registered?
> 
> ```java
> @Configuration
> public class SentinelAspectConfiguration {
>     @Bean
>     public SentinelResourceAspect sentinelResourceAspect() {
>         return new SentinelResourceAspect();
>     }
> }
> ```

oh yes,thank you very mush.
