### ISSUE TITLE
provide extension for metrics

### ISSUE THREAD

**Issue by FS1360472174** [alibaba/Sentinel#931]
## Issue Description

 *feature request*

### Describe what happened (or what feature you want)
user can extend Metrics. now metrics is limited and calcuted by sentinel.
how about to provide SPI. so user can implement their own metrics.like prometheus.

**Comment by sczyh30** [comment]
The `MetricExtension` has been added since 1.6.1. See #730 for more information.

For Prometheus extension, you may refer to #735.

**Comment by FS1360472174** [comment]
it's good.but a little different .

#730 provide callback for sentinel internal metrics.

#735 send sentineal to prometheus.

what i want is to provide an extension of metrics and metrics calcute.
and it can work well with these flow controll strategy.

for example, now sentinel provide the qps metrics.but i need a uv metrics.
so i need to extend sentinel metrics,define a new `uv` metrics,and extend metrics calcute logic。
then i can define a flow controll rule for the new metrics.

**Comment by sczyh30** [comment]
Sentinel has provided callback support for `StatisticSlot`:

- `ProcessorSlotEntryCallback`: callback when resource entry passed (`onPass`) or blocked (`onBlocked`)
- `ProcessorSlotExitCallback`: callback when resource entry successfully exited (`onExit`)

Maybe you could leverage these callbacks to implement your customized metrics. You could register your own callback via `StatisticSlotCallbackRegistry`.
