### ISSUE TITLE
Configurations such as flow control rules that use nacos to persist sentinel can be persisted, but the configuration does not take effect after restarting the service.

### ISSUE THREAD

**Issue by wangyingwei001** [alibaba/Sentinel#934]
使用nacos持久化sentinel的流控规则等配置 可以实现持久化 但是重启服务后之前的配置就不生效了 还得删了重新创建，麻烦看下是什么问题

**Comment by wangyingwei001** [comment]
You mean it's correct that the service doesn't take effect after restart, right?

**Comment by sczyh30** [comment]
You may need to check whether you've registered the data-source correctly. See ttps://github.com/alibaba/Sentinel/wiki/动态规则扩展#datasource-扩展

**Comment by wangyingwei001** [comment]
I'm just referring to the push pattern extension. It's really only a persistence rule. After every service restart, the rule still doesn't work.

**Comment by sczyh30** [comment]
Could you please check the logs in `~/logs/csp/sentinel-record.log.xx`?

**Comment by sczyh30** [comment]
Any feedback?

**Comment by wangyingwei001** [comment]
I'll try it tomorrow.




| |
柠七
|
|
邮箱：svip66666666666@126.com
|

签名由 网易邮箱大师 定制

On 07/31/2019 23:09, Eric Zhao wrote:

Any feedback?

**Comment by wangyingwei001** [comment]
Do you have your own well-integrated code that works perfectly?




| |
柠七
|
|
邮箱：svip66666666666@126.com
|

签名由 网易邮箱大师 定制

On 07/31/2019 23:31, wangyingwei001 wrote:
I'll try it tomorrow.




| |
柠七
|
|
邮箱：svip66666666666@126.com
|

签名由 网易邮箱大师 定制

On 07/31/2019 23:09, Eric Zhao wrote:

Any feedback?

**Comment by wangyingwei001** [comment]
Look at the log is not abnormal

**Comment by sczyh30** [comment]
You may check:

- whether the data source in your client side is correctly configured
- whether the pushing provider in the dashboard works well
