### ISSUE TITLE
Sentinel spit

### ISSUE THREAD

**Issue by mobile664042** [alibaba/Sentinel#935]
当前使用版本: 1.6.2
槽点一：ZookeeperDataSource 、NacosDataSource、ZookeeperDataSource实现了数据读取操作，写操作(持久化)就不能再完善一下么，还得自己去写。。。。。

槽点二： sentinel-dashboard(**控制台**) 去**接入方**拉取《**实时监控**》数据时，使用的控制台服务器时间做为参数;  如果当前**控制台服务器时间**大于**接入方服务器时间**，可能就永远拿不到数据，报表就永远为空， 已做了简单粗暴的修改, com.alibaba.csp.sentinel.dashboard.metric.MetricFetcher.doFetchAppMetric(String app) 中的 now 减去20秒。

**Comment by jasonjoo2010** [comment]
Related to #904 

You can join the discussion (Is there a discussion?) to decide whether we should add this kind of standard implementation into the datasource modules.

**Comment by mobile664042** [comment]
肯定需要一个标准的实现啊，你这读都已实现了，干脆送佛到西，把datasource 事情做完。

**Comment by sczyh30** [comment]
For 1, we don't recommend pushing rules at the client side in the push-based model. See https://github.com/alibaba/Sentinel/wiki/动态规则扩展#datasource-扩展 for more information.

For 2, we've illustrated this in the document of Sentinel dashboard. But it's might be a problem when the time zone of the dashboard and the application is different. Maybe we need a property for offset configuration, or any other suggestions?
