### ISSUE TITLE
The misspelling in wiki (part : API mode: Configuring rules using the client-side rules API)

### ISSUE THREAD

**Issue by alenX** [alibaba/Sentinel#938]
the detail url is 
https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#api-%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%A7%84%E5%88%99-api-%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99

```sh
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentienl-http-simple-transport</artifactId>
    <version>x.y.z</version>
</dependency>
```
the **sentienl-http-simple-transport** is misspelling,it should be** sentinel-http-simple-transport**
thanks

**Comment by sczyh30** [comment]
We've fixed the typo. Thanks for reporting!
