### ISSUE TITLE
Some questions about Sentinel

### ISSUE THREAD

**Issue by mobile664042** [alibaba/Sentinel#940]
bug1:   同一个类中(或同一级别, 例如: CommonFilter 与 controller层)调中被@SentinelResource修饰的方法a 调用另外被@SentinelResource修饰的方法b, b的@SentinelResource注解不生效.

bug2:  热点参数限流只针对@SentinelResource注解的资源才生效(通过CommonFilter 或 dubbo统一配置的资源不生效)。

bug3:   各种资源名不能重名(没有命名空间概念?)，不然无法有效定位资源(只会有一种情况生效).

**Comment by sczyh30** [comment]
For 1, you may refer to #349.

For 2, the web servlet `CommonFilter` does not pass any parameters so it does not support parameter flow control. For Dubbo services, the parameter flow control is supported if your service method contains regular parameters.

For 3, Sentinel let users decide their resource name so you can group your resources by yourself.

**Comment by mobile664042** [comment]
> For 1, you may refer to #349.
> 
> For 2, the web servlet `CommonFilter` does not pass any parameters so it does not support parameter flow control. For Dubbo services, the parameter flow control is supported if your service method contains regular parameters.
> 
> For 3, Sentinel let users decide their resource name so you can group your resources by yourself.

对于第2点，我这边用dubbo 服务 热点参数不生效啊， 主只SentinelResource注解的才生效啊，我的势不对，你们的demo中有样例？

**Comment by cdfive** [comment]
有例子的，在sentinel-demo-apache-dubbo工程。
`FooProviderBootstrap`里的`initFlowRule`初始化了普通流控规则，可以改成热点参数规则：
```java
ParamFlowRule rule = new ParamFlowRule(RES_KEY)
	.setParamIdx(0)
	.setGrade(RuleConstant.FLOW_GRADE_QPS)
	.setCount(5);
ParamFlowRuleManager.loadRules(Collections.singletonList(rule));
```
注意热点参数规则资源名在**方法**(RES_KEY))上不是**接口**(INTERFACE_RES_KEY)，因为方法上才有参数。

pom.xml把`sentinel-parameter-flow-control`依赖加上：
```xml
<dependency>
	<groupId>com.alibaba.csp</groupId>
	<artifactId>sentinel-parameter-flow-control</artifactId>
	<version>${project.version}</version>
</dependency>
```
然后启动`FooProviderBootstrap`、`FooConsumerBootstrap`就能看到效果，在控制台里**ParamFlowException**.

dubbo的demo有2个，sentinel-demo-apache-dubbo用的dubbo2.7.1，还有个sentinel-demo-dubbo用的dubbo2.6.6，测试方法跟上面一样。

**Comment by sczyh30** [comment]
注意要在 provider 端配置热点参数限流规则，consumer 端配置不生效.

---

Parameter flow control is not activated in Dubbo consumer filter.
