### ISSUE TITLE
Spring cloud gateway does not support dashboard

### ISSUE THREAD

**Issue by coderDylan** [alibaba/Sentinel#941]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 通过GatewayRuleManager.register2Property从nacos动态限流规则，限流规则生效的
2. dashbord中可以看到机器信息，心跳正常，但是dashboard中"实时监控"和"流控规则"均无法正常展示。检查csp目录的日志正常
3. 使用的最新的1.62版本

**Comment by sczyh30** [comment]
检查一下 ~/logs/csp/sentinel-record.log 和 command-center.log 里面有没有异常信息
实时监控 需要持续有访问量方可显示。
网关规则不会显示在普通流控规则中，下个版本（`master` 分支）控制台会支持网关规则的配置。

**Comment by coderDylan** [comment]
> 检查一下 ~/logs/csp/sentinel-record.log 和 command-center.log 里面有没有异常信息
> 实时监控 需要持续有访问量方可显示。
> 网关规则不会显示在普通流控规则中，下个版本（`master` 分支）控制台会支持网关规则的配置。

sentinel-record.log  command-center.log没有异常信息的，到响应结果中很多『"Blocked by Sentinel: ParamFlowException"』的，而且后端应用也有监控qps是在限流阈值范围内的，说明流控规则是生效的。
并且我仔细检查了metrics.log的内容，格式是和普通应用流控打的格式一致的，说明摘要和统计信息是ok的。从Dashboard中看到的心跳是OK的，说明启动参数是OK的，gateway连接到Dashboard了。我trace了com.alibaba.csp.sentinel.command.handler.SendMetricCommandHandler#handle，发现未执行，是不是说明metrics信息根本没有上报？

**Comment by coderDylan** [comment]
> 检查一下 ~/logs/csp/sentinel-record.log 和 command-center.log 里面有没有异常信息
> 实时监控 需要持续有访问量方可显示。
> 网关规则不会显示在普通流控规则中，下个版本（`master` 分支）控制台会支持网关规则的配置。

sentinel-record.log command-center.log没有异常信息的，到响应结果中很多『"Blocked by Sentinel: ParamFlowException"』的，而且后端应用也有监控qps是在限流阈值范围内的，说明流控规则是生效的。
并且我仔细检查了metrics.log的内容，格式是和普通应用流控打的格式一致的，说明摘要和统计信息是ok的。从Dashboard中看到的心跳是正常的，说明启动参数是OK的，gateway成功连接到Dashboard了。我trace了com.alibaba.csp.sentinel.command.handler.SendMetricCommandHandler#handle，发现未执行，是不是说明metrics信息根本没有上报？
并且我又检查了一下command-center.log，普通应用会不断刷SimpleHttpCommandCenter
 GET /metric?startTime=1564017055000&endTime=1564017061000&refetch的日志，
而gateway的应用除了Begin listening at port，根本没有，说明统计信息未上报

**Comment by coderDylan** [comment]
> > 检查一下 ~/logs/csp/sentinel-record.log 和 command-center.log 里面有没有异常信息
> > 实时监控 需要持续有访问量方可显示。
> > 网关规则不会显示在普通流控规则中，下个版本（`master` 分支）控制台会支持网关规则的配置。
> 
> sentinel-record.log command-center.log没有异常信息的，到响应结果中很多『"Blocked by Sentinel: ParamFlowException"』的，而且后端应用也有监控qps是在限流阈值范围内的，说明流控规则是生效的。
> 并且我仔细检查了metrics.log的内容，格式是和普通应用流控打的格式一致的，说明摘要和统计信息是ok的。从Dashboard中看到的心跳是正常的，说明启动参数是OK的，gateway成功连接到Dashboard了。我trace了com.alibaba.csp.sentinel.command.handler.SendMetricCommandHandler#handle，发现未执行，是不是说明metrics信息根本没有上报？
> 并且我又检查了一下command-center.log，普通应用会不断刷SimpleHttpCommandCenter
> GET /metric?startTime=1564017055000&endTime=1564017061000&refetch的日志，
> 而gateway的应用除了Begin listening at port，根本没有，说明统计信息未上报

正常的可以用arthas神器trace到 com.alibaba.csp.sentinel.transport.command.http.HttpEventTask run，gateway的应用trace时No class or method is affected  ，说明这个业务线城池中的任务没有。
问题就出在 Socket socket = null;
                try {
                    socket = this.serverSocket.accept();
                    setSocketSoTimeout(socket);
                    HttpEventTask eventTask = new HttpEventTask(socket);
                    bizExecutor.submit(eventTask);

我没有debug，但是可以推断accept这里一直阻塞着，说明client端（dashbord）那边一直没有请求过来。
最后我查到真实原因了，是因为多网卡，dashbord那边获取到的ip地址是其他虚拟网卡的，网络不通造成的accept阻塞，从而HttpEventTask无法在业务线程池中执行，哈哈

**Comment by coderDylan** [comment]
准确来讲，是gateway在上报心跳的时候获取到了虚拟网卡的ip地址（dev服务器比较乱，被人装了docker），导致Dashboard无法连接，socket = this.serverSocket.accept();这一行自然就会一直阻塞，
从而HttpEventTask无法在业务线程池中执行...所以最终无法在限流大盘展示准备好的metrics信息。

请问为啥要设计成这种『http+tcp的类双工通信』的模式呢？

**Comment by sczyh30** [comment]
The dashboard metrics is pull-based (from local metric log).
