### ISSUE TITLE
Console add rules Chinese garbled Console add rules Chinese garbled

### ISSUE THREAD

**Issue by tzxylao** [alibaba/Sentinel#943]
## Issue Description
控制台添加规则中文乱码
Console add rules Chinese garbled

### Describe what happened (or what feature you want)
从控制台添加修改规则传到客户端的规则乱码
Adding a modification rule from the console to the client's rules garbled

### Describe what you expected to happen
期望可以兼容中文，在控制台流量监控时可以用中文来描述服务名
Expect to be compatible with Chinese. In console traffic monitoring, you can use Chinese to describe the service name.

### How to reproduce it (as minimally and precisely as possible)

1. 控制台添加中文规则名就可重现
1. The console can be reproduced by adding the Chinese rule name.

### Tell us your environment
windows和liunx皆是如此
Both windows and liunx are like this

### Anything else we need to know?
我在分支已经提交编码设置，是否还需要改动请看一下
版本号：d4df668300799ea6f19e12352769275eca4890ae

I have already submitted the encoding settings in the branch. Do you still need to change it? Please take a look.
Version number: d4df668300799ea6f19e12352769275eca4890ae

**Comment by sczyh30** [comment]
Thanks for reporting! Would you like to contribute a PR? You may refer to https://github.com/alibaba/Sentinel/wiki/开源贡献指南

**Comment by sczyh30** [comment]
@tzxylao Any progress? :)

**Comment by zhaoyuguang** [comment]
I wanna finish this issue, please give me some suggestion @sczyh30 @cdfive @linlinisme

**Comment by sczyh30** [comment]
> I wanna try to finish this issue, please give me some suggestion @sczyh30 @cdfive @linlinisme

Maybe we could refer to https://github.com/alibaba/Sentinel/commit/d4df668300799ea6f19e12352769275eca4890ae. Any other suggestions?

**Comment by sczyh30** [comment]
Is there anyone working on this issue?

**Comment by zhenxianyimeng** [comment]
@sczyh30  I have tried to fix it,  please help me review it
