### ISSUE TITLE
Interface inheritance leads to error in Sentinel Feign integration

### ISSUE THREAD

**Issue by wangjihong-china** [alibaba/Sentinel#946]
定义了一个MsgApi接口类，然后定义了MsgFeignClient实现MsgApi接口,  调用方DataCenterMessageServiceImpl 代码注入MsgApi类调用时，Sentinel代理无法自动适配出MsgApi的实现类MsgFeignClient来调用导致错误，不使用Sentinel时feignclient可以根据MsgApi自动适配出MsgFeignClient类来调用。
请大神帮看看哈，应该是没有自动获取接口Bean来调用，直接使用了接口调用。
备注: 没有把@FeignClient放在MsgCenterApi接口类上是因为我们MsgCenterApi接口还有controller层的实现类。

**重现问题代码：**

消息服务：
**MsgApi接口类：**

```java
/**
 * @description 消息中心API接口
 */
public interface MsgCenterApi {
	/**
	 * 保存一条推送到消息中心的消息
	 */
	@PostMapping( "api/msgcenter/v1/push")
	BusinessResponseEntity<Boolean> saveSubmit(@RequestBody MsgVO requestVO);
}
```

**MsgFeignclient实现类：**

```java
@FeignClient(name = CommonConst.ServiceNameConst.MESSAGE_SERVICE_NAME, url = CommonConst.ServiceNameConst.MESSAGE_SERVICE_URL, fallbackFactory = MsgCenterFeignClientFallBackFactory.class)
@RefreshScope
public interface MsgCenterFeignClient extends MsgCenterApi {
}
```

合并服务调用类：

```java
@Service
public class DataCenterMessageServiceImpl ｛
        @Autowired
	private MsgCenterApi msgCenterApi;
        
        private void sendMsgToMsgCenter(MsgVO msgVO) {
		 msgCenterApi.saveSubmit(msgVO);
	}
｝
```

**Comment by sczyh30** [comment]
cc @fangjian0423

**Comment by fangjian0423** [comment]
It works well in my local.

Could you please provide a project that reproduces the issue?

**Comment by wangjihong-china** [comment]
我写了个重现demo代码库，请查收执行下哈。
https://github.com/wangjihong-china/sentinel-bug-20190730.git
你可以启动两个服务使用 Postman 工具模拟调用请求，即可重现。
http://localhost:9199/api/datacenter/v1/pushMsg

出问题的地方是在org.springframework.cloud.alibaba.sentinel.feign.SentinelInvocationHandler.invoke(Object, Method, Object[]) 93行代码。

**Comment by fangjian0423** [comment]
@wangjihong-china 

refer https://github.com/alibaba/spring-cloud-alibaba/issues/626.

It has been fixed and spring-cloud-alibaba graduate this week. welcome to use graduation version.

**Comment by wangjihong-china** [comment]
@fangjian0423 好哒，多谢大佬！
