### ISSUE TITLE
[Bug] 流控规则列表页 > 编辑按钮 > "编辑流控规则"弹出窗口 取消编辑无效

### ISSUE THREAD

**Issue by konglz** [alibaba/Sentinel#95]
## Issue Description

Type: *bug report* 

### 1. Describe what happened (or what feature you want)

* bug位置：流控规则列表页 > 编辑按钮 > "编辑流控规则"弹出窗口

* bug特征：修改“单机阈值”，点击“取消按钮”，修改过的值依然被保存了

### 2. Describe what you expected to happen

* 点击“取消按钮”后，修改过的值不被保存

### 3. How to reproduce it (as minimally and precisely as possible)

按照1的描述即可

**Comment by CarpenterLee** [comment]
It's a view bug. When form changed, the rule related to it will change too, because they share the same model, but no request will be send until save button clicked.  Refresh the page, you will see real rules in the client.
