### ISSUE TITLE
Support event listener of circuit breaker state change event

### ISSUE THREAD

**Issue by huangxfchn** [alibaba/Sentinel#951]
For example, if sentinel start to switch off, then can call back an interface to notify the application. The same is true when sentinel is out of circuit breaker mode.

**Comment by sczyh30** [comment]
In fact, Sentinel has provided callback support for `StatisticSlot`:

- `ProcessorSlotEntryCallback`: callback when resource entry passed (`onPass`) or has been blocked (`onBlocked`)
- `ProcessorSlotExitCallback`: callback when resource entry successfully exited (`onExit`)

We can register your own callback via `StatisticSlotCallbackRegistry`. Maybe here we can just leverage the `onBlocked` callback to handle the rule trigger alarm. You could get the triggered rule from the `BlockException`.

You may also refer to #418

**Comment by huangxfchn** [comment]
Looks a bit like.

I need to catch `DegradeException`, and determine the `count = = 1` representative to downgrade strategy, but `onBlocked` method should be invoked after the circuit breaker mode, this method was invoked every time during until out of fusing time window. Is that right?

So, what if I knew when to jump out of the circuit breaker mode.

**Comment by sczyh30** [comment]
You mean notification for circuit breaker `CLOSE` event? This hasn't been supported yet, but it seems helpful. Maybe we could provide a listener registry for circuit breaker state change events. We could discuss the design here.

**Comment by huangxfchn** [comment]
Yeah,  circuit breaker `START` and `CLOSE` event.

**Comment by linlinisme** [comment]
I am doing something like that, may be it can assign to me.

**Comment by sczyh30** [comment]
> I am doing something like that, maybe it can assign to me.

Nice, looking forward to your PR~

**Comment by sczyh30** [comment]
The `CircuitBreakerStateChangeObserver` will be available in 1.8.0.
