### ISSUE TITLE
When restart Application(not sentinel dashboard) Loss Sentinel configed rules

### ISSUE THREAD

**Issue by yuxiao97** [alibaba/Sentinel#954]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
1、When restart Application(not sentinel dashboard) Loss Sentinel configed rules.

### Describe what you expected to happen
1、I hope when restart my application, the rules confied by Sentinel dashboard always exists.

### How to reproduce it (as minimally and precisely as possible)
1. Start Sentinel dashboard;
2. Start my Application;
3. Set some rules for my Application, it's worked;
4. Restart my Application;

### Tell us your environment
OS: windows10
Sentinel dashboard: 1.6.3
Dependendy:
`
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
	<version>0.2.0.RELEASE</version>
</dependency>
`

**Comment by sczyh30** [comment]
Hi, by default the rules are stored in the cache of Sentinel client side, so when you start your application, the rules will be lost. You may refer to the FAQ: https://github.com/alibaba/Sentinel/wiki/FAQ#q-在控制台配置的规则存在哪里为什么应用重启规则就消失了

**Comment by yuxiao97** [comment]
> Hi, by default the rules are stored in the cache of Sentinel client side, so when you start your application, the rules will be lost. You may refer to the FAQ: [https://github.com/alibaba/Sentinel/wiki/FAQ#q-在控制台配置的规则存在哪里为什么应用重启规则就消失了](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E5%9C%A8%E6%8E%A7%E5%88%B6%E5%8F%B0%E9%85%8D%E7%BD%AE%E7%9A%84%E8%A7%84%E5%88%99%E5%AD%98%E5%9C%A8%E5%93%AA%E9%87%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BA%94%E7%94%A8%E9%87%8D%E5%90%AF%E8%A7%84%E5%88%99%E5%B0%B1%E6%B6%88%E5%A4%B1%E4%BA%86)

OK，thanks
