### ISSUE TITLE
Is it limited to the number of threads supported by http requests? Do not let the request consume the http connection pool

### ISSUE THREAD

**Issue by shuohao** [alibaba/Sentinel#958]
对http请求支持按线程数限流吗？ 不让请求耗光http连接池

**Comment by cdfive** [comment]
流控规则支持QPS/线程两种模式的。
参考：[https://github.com/alibaba/Sentinel/wiki/流量控制#21-并发线程数流量控制](https://github.com/alibaba/Sentinel/wiki/流量控制#21-并发线程数流量控制)

http请求可以考虑用`sentinel-web-servlet`：
[https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-servlet](https://github.com/alibaba/Sentinel/wiki/主流框架的适配#web-servlet)
或者使用`@SentinelResource`注解：
[https://github.com/alibaba/Sentinel/wiki/注解支持](https://github.com/alibaba/Sentinel/wiki/注解支持)

**Comment by sczyh30** [comment]
You may leverage the concurrency limiting rule (thread count mode).
