### ISSUE TITLE
Why need so many threads in DegradeRule.java,only 1 is enough?

### ISSUE THREAD

**Issue by 0704681032** [alibaba/Sentinel#968]
```
//DegradeRule.java
private static ScheduledExecutorService pool = Executors.newScheduledThreadPool(
        Runtime.getRuntime().availableProcessors(), new NamedThreadFactory("sentinel-degrade-reset-task", true));
```

**Comment by linlinisme** [comment]
This is a global quantity, which is still good for the entire application. If there is only one thread, there is a risk that the blocked state will not be cleared in time. Many requests that could be processed are blocked
