### ISSUE TITLE
FlowRuleManager  update flowRules.when between clear and putAll,getRules is empty.

### ISSUE THREAD

**Issue by zhuyou1234** [alibaba/Sentinel#969]
orgin:
private static final Map<String, List<FlowRule>> flowRules = new ConcurrentHashMap<String, List<FlowRule>>();

public void configUpdate(List<FlowRule> value) {
            Map<String, List<FlowRule>> rules = FlowRuleUtil.buildFlowRuleMap(value);
            if (rules != null) {
                flowRules.clear();
                flowRules.putAll(rules);
            }
            RecordLog.info("[FlowRuleManager] Flow rules received: " + flowRules);
 }

this should be optimize.

private static Map<String, List<FlowRule>> flowRules = new ConcurrentHashMap<String, List<FlowRule>>();

 @Override
        public void configUpdate(List<FlowRule> value) {
            Map<String, List<FlowRule>> rules = FlowRuleUtil.buildFlowRuleMap(value);
            if (rules != null) {
                flowRules = new ConcurrentHashMap<>(rules);
            }
            RecordLog.info("[FlowRuleManager] Flow rules received: " + flowRules);
        }

**Comment by sczyh30** [comment]
Refer https://github.com/alibaba/Sentinel/issues/1141#issuecomment-828074340
