### ISSUE TITLE
can't print log to sentinel-record.log file with log4j JDK logging adapter

### ISSUE THREAD

**Issue by RojerAlone** [alibaba/Sentinel#975]
### Describe what happened (or what feature you want)

I use nacos as dynamic rule center, and change rule in nacos console, i also receive the new rule, but can't see anything in `sentinel-record.log` file, is there some special config params?

There are 2 record log file, they are empty all:
```
-rw-r--r-- 1 work work    0 Aug  8 13:27 sentinel-record.log.2019-08-08.0
-rw-r--r-- 1 work work    0 Aug  8 13:27 sentinel-record.log.2019-08-08.0.lck
```
But the metrics.log is right.

And more, I run the code on my computer, and can see log, but deploy it to server, it will not.

### Tell us your environment

Nacos client version is 1.0.0
Sentinel version is 1.6.2

**Comment by sczyh30** [comment]
Hi, are there any error messages in your stderr?

**Comment by RojerAlone** [comment]
> Hi, are there any error messages in your stderr?

No.

Besides, I set the log home by `-Dcsp.sentinel.log.dir=/loghome`, and only got below logs in my stdout:
```
INFO: log base dir is: /loghome
INFO: log name use pid is: false
```

**Comment by RojerAlone** [comment]
> Besides, I set the log home by `-Dcsp.sentinel.log.dir=/loghome`, and only got below logs in my stdout:
> 
> ```
> INFO: log base dir is: /loghome
> INFO: log name use pid is: false
> ```

It's unrelated. I test it by setting log home on my computer and don't set it on server.

**Comment by linlinisme** [comment]
You mean on your computer you can see the log, and on server can not see? If so, it seems your application has not the write permission for the log dir.

**Comment by RojerAlone** [comment]
@linlinisme I checked it, my application has permission, the metrics log is normal, and metrics log is in same directory with record log.

**Comment by sczyh30** [comment]
Could you please try to add this JVM parameter: `-Dcsp.sentinel.log.output.type=console` and see whether the log appears in stdout

**Comment by RojerAlone** [comment]
It seems there are some bad configuration in my code, record log is ok when I run my code in IDE, but it will not appear if I package my code and run it on server.
I'm looking for it.

**Comment by RojerAlone** [comment]
> Could you please try to add this JVM parameter: `-Dcsp.sentinel.log.output.type=console` and see whether the log appears in stdout

What means if the log doesn't appear in stdout? It does.

**Comment by sczyh30** [comment]
> It seems there are some bad configuration in my code, record log is ok when I run my code in IDE, but it will not appear if I package my code and run it on server.
> I'm looking for it.

Any progress?

**Comment by RojerAlone** [comment]
Maybe not. I use log4j in my service and I try to remove the `log4j2.xml` file or redirect all log to console, but can only see the other logs besides sentinel log.
I plan to debug it later.

**Comment by jasonjoo2010** [comment]
> Maybe not. I use log4j in my service and I try to remove the `log4j2.xml` file or redirect all log to console, but can only see the other logs besides sentinel log.
> I plan to debug it later.

If you just want to redirect all logs into console under log4j2 I have an easier way to achieve that.

reference in pom.xml:
```xml
      <dependency>
        <groupId>com.yoloho.enhanced</groupId>
        <artifactId>enhanced-common</artifactId>
        <version>1.0.2</version>
      </dependency>
```

And you can just remove the `log4j2.xml` in your project and add following code in initializing block:

```java
// enable console, disable file logging
Logging.initLogging(true, false);
```

If you want do it more elegant you can refer to `@InitDefaults` in 

https://github.com/yoloho/enhanced-spring

**Comment by cdfive** [comment]
> > Could you please try to add this JVM parameter: `-Dcsp.sentinel.log.output.type=console` and see whether the log appears in stdout
> 
> What means if the log doesn't appear in stdout? It does.

Sentinel provide a VM argument to choose output of biz log.

`-Dcsp.sentinel.log.output.type` default is file, print log to `sentinel-record.log` and `command-center.log`.

If set `-Dcsp.sentinel.log.output.type=console`, the log can be printed to stdout console.
You can have a try to test if the log is ok.

**Comment by sczyh30** [comment]
Has this been resolved?

**Comment by RojerAlone** [comment]
Sorry, I'm busy recently and I'll find time to do it.

**Comment by RojerAlone** [comment]
@sczyh30 
I debug it today, and found that the different of my computer with server is log framework. It will use `java.util.logging.Logger` when i run it on my computer, and it use log4j on server.

I add this to my `log4j2.xml` file and can see the log in `Main` appender log:
```xml
<Logger name="cspSentinelRecordLog" level="DEBUG" additivity="false">
    <AppenderRef ref="Main"/>
</Logger>
```
I'm not familiar with log framework, does log framework cause this?
And I think it will append to the root logger if not configure `cspSentinelRecordLog` logger, is it?

**Comment by sczyh30** [comment]
You may check whether the content of Sentinel record log appeared in the log4j-configured log file.

**Comment by RojerAlone** [comment]
There's not, only appeared when I add a logger named `cspSentinelRecordLog`.

**Comment by sczyh30** [comment]
Has this been solved?

**Comment by RojerAlone** [comment]
no, I think there's something wrong in the log framework properties, and had other people report the same question?

**Comment by RojerAlone** [comment]
I debug it again, and find the root cause is that there's not any `AppenderRef` in the `LoggerConfig` object for sentinel log, then the `logParent` method would be called, but the `additive` field is false, so there are nothing in log file.
These are code and object info:

![code from org.apache.logging.log4j.core.config.LoggerConfig class](https://user-images.githubusercontent.com/20370513/69508697-74971180-0f71-11ea-8ef4-62f252fff322.png)

![LoggerConfig object](https://user-images.githubusercontent.com/20370513/69508843-e53e2e00-0f71-11ea-8f31-1f62abed030a.png)

Is there somethint wrong in sentinel `RecordLog` class?

**Comment by RojerAlone** [comment]
@sczyh30  I maybe have found the reason from the [log4j official website](https://logging.apache.org/log4j/2.0/log4j-jul/index.html):

> The use of java.util.logging.Handler classes is NOT supported. Custom Handlers should instead use an appropriate Appender or code their own Appender plugin.

**Comment by sczyh30** [comment]
Since 1.7.2 you may leverage the `Logger` SPI.
