### ISSUE TITLE
中文文档错字

### ISSUE THREAD

**Issue by pengminxuan** [alibaba/Sentinel#98]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
[https://github.com/alibaba/Sentinel/wiki/%E4%BB%8B%E7%BB%8D#4%E6%A3%80%E6%9F%A5%E6%95%88%E6%9E%9C](url) 链接对应中文文档中存在错字.

### Describe what you expected to happen
"rt代表平均相应时长"中的"相应"应该替换为"响应"

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jialianglinjl** [comment]
Thanks for your issue!
