### ISSUE TITLE
does sentinel-zuul-adapter support cluster flow control

### ISSUE THREAD

**Issue by yugj** [alibaba/Sentinel#981]
Type: question

It seem sentinel does not support zuul cluster flow control ?

question:

1,does sentinel-zuul-adapter support clusters flow control now？

2,if not ,are there any suggestions on how to do it?

**Comment by sczyh30** [comment]
The gateway cluster flow control (`GatewayFlowRule`) is not supported yet, but you could leverage the normal cluster flow rule and parameter flow rule.
