### ISSUE TITLE
Misspelling of Words（exeption） in Official Documents

### ISSUE THREAD

**Issue by liran0705** [alibaba/Sentinel#983]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
Misspelling of Words（exeption） in Official Documents
![image](https://user-images.githubusercontent.com/45581895/62924142-083d3b80-bde2-11e9-9c5b-995ad347f345.png)

### Describe what you expected to happen
exeption --> exception

### How to reproduce it (as minimally and precisely as possible)

1. https://github.com/alibaba/Sentinel/wiki/%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6

**Comment by sczyh30** [comment]
Thanks for reporting! I've fixed it :)
