### ISSUE TITLE
Wrong IP reported to the dashboard (host IP expected, but actually VM ip resolved)

### ISSUE THREAD

**Issue by kinbod** [alibaba/Sentinel#987]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

sentinel-apache-dubbo-adapter给sentinel-dashboard注册了虚拟机的IP，本地安装了虚拟机，而不是真实的主机IP

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sczyh30** [comment]
You may refer to #395 

And you can describe your issue in the issue description.
