### ISSUE TITLE
Add authorization rule

### ISSUE THREAD

**Issue by bobqiu** [alibaba/Sentinel#988]
In product environment，api must be under token or secret key protection.

**Comment by sczyh30** [comment]
Could you please illustrate the detail of your requirement?

**Comment by bobqiu** [comment]
Set a  token or secret key for each service，when consumer use the service ,they can pass after through verify use the token or secret key

**Comment by sczyh30** [comment]
You may implement your own slot based on the [slot chain SPI mechanism](https://github.com/alibaba/Sentinel/wiki/Sentinel工作主流程#overview).
