### ISSUE TITLE
Does the console not support the GatewayFlowRule rule?

### ISSUE THREAD

**Issue by se7enfly** [alibaba/Sentinel#989]
集成 cloud-gateway和 sentinel，控制台没有地方显示GatewayRuleManager 添加的规则

1. pom用的 sentinel-spring-cloud-gateway-adapter
2. 按照wiki推荐的方式，在configuration中添加规则
Set<GatewayFlowRule> rules = new HashSet<>();
        rules.add(new GatewayFlowRule("tms_waybill_wms")
                .setCount(1)
                .setIntervalSec(1)
        );
GatewayRuleManager.loadRules(rules);
3. 控制台，没有显示这个规则，（已经调用过这个服务）。而且在控制台配置同样的流控规则("tms_waybill_wms")，不会生效。

猜测，控制台现在支持了FlowRuleManager 这种流控，针对GatewayRuleManager的没有支持。

**Comment by sczyh30** [comment]
This has been supported in 1.6.3. You may refer to https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台

**Comment by se7enfly** [comment]
tks。 but,i just had done as the  https://github.com/alibaba/Sentinel/wiki/网关限流#网关流控控制台

I will down the sentinel-dashboard-1.6.3.jar ,and try agin. Now,my local dashboard is from master(i had downed the sentinel-dashboard-1.6.3.jar some times,but it always time out), and it has not the column “API类型” in the page of “请求链路”.

By the way,in above environment。Some method add @SentinelResource,another does not. The server cannot find by dashboard,it shows "失联" in dashboard.
When you also add @SentinelResource to the method of "hello2", it will show "健康" in dashboard.
That is so cool

@RestController
    public class TestController {

        @GetMapping(value = "/hello")
        @SentinelResource("hello")
        public String hello() throws  Exception{
           throw new Exception("");
        }
        @GetMapping(value = "/hello2")
       // @SentinelResource("hello2")
        public String hello2(String name) throws  Exception{
            return name;
        }
    }

**Comment by se7enfly** [comment]
sorry,i make a mistake . I put "-Dcsp.sentinel.app.type=1" on the gateway server, should put on the dashboard.   a stupid mistake

**Comment by se7enfly** [comment]
应用端加上 -Dcsp.sentinel.app.type=1 后，需要重启控制台

**Comment by michael-m-pro** [comment]
> 应用端加上 -Dcsp.sentinel.app.type=1 后，需要重启控制台

我在整合spring cloud gateway 与sentinel时，应用不加-Dcsp.sentinel.app.type=1,控制台添加的网关流控有效，应用添加后，控制台添加的网关流控无效(版本都是2.2.1.release)
