### ISSUE TITLE
流控规则页面BUG

### ISSUE THREAD

**Issue by pengminxuan** [alibaba/Sentinel#99]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

- bug位置: 控制台 > 流控规则
- bug发生条件: 修改"超时时间"时, 如果多次点击保存, 会导致:

1. 实时监控无法正常显示, 需要重启控制台后才能显示.
2. 簇点链路新增流控规则后无法显示新增规则, 需要重启控制台后才能显示.
3. 多次刷新页面之后会使簇点链路内的资源和流控规则内的规则会消失.
4. 重新修改规则时会卡住无法保存, 弹窗不会自动关闭, 顶部的进度条会卡在最后一段.
5. 等待一段时间之后控制台会卡住无法刷新,长时间处于等待响应的状态.

### How to reproduce it (as minimally and precisely as possible)

1. 参照描述

### Tell us your environment
0.2.0-SNAPSHOT版本的sentinel-dashboard

**Comment by CarpenterLee** [comment]
Thanks for your contribution. This bug is caused by missing comparison of `FlowRule.maxQueueingTimeMs`, and we will fix it right away.
