### ISSUE TITLE
Support registering writable data-source for GatewayFlowRule and customized ApiDefinition

### ISSUE THREAD

**Issue by fuzhanwei** [alibaba/Sentinel#992]
WritableDataSourceRegistry 和 GatewayRuleManager不支持GatewayFlowRule注册写数据源

**Comment by sczyh30** [comment]
Maybe we could just support registering the WritableDataSource in their respective command handler (e.g. [`UpdateGatewayApiDefinitionGroupCommandHandler`](https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayApiDefinitionGroupCommandHandler.java) and [`UpdateGatewayRuleCommandHandler`](https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/command/UpdateGatewayRuleCommandHandler.java)).

An example is [`ModifyParamFlowRulesCommandHandler`](https://github.com/alibaba/Sentinel/blob/master/sentinel-extension/sentinel-parameter-flow-control/src/main/java/com/alibaba/csp/sentinel/command/handler/ModifyParamFlowRulesCommandHandler.java). Contributions are welcomed!

**Comment by zhaoyuguang** [comment]
I wanna try to finish this issue~

**Comment by zhangyide** [comment]
I had finished this issue~.

**Comment by sczyh30** [comment]
👍 Looking forward to your PR!

**Comment by yjygalb** [comment]
@zhangyide I have  pushed gateway rules and apidefinition to zookeeper,but I can not read them from the client side using ZookeeperDataSource, can you show me hao to read them from the client side,thx.
