### ISSUE TITLE
Does sentinel support the ribbon retry mechanism? I didn't find this feature.

### ISSUE THREAD

**Issue by wang271724646** [alibaba/Sentinel#993]
ribbon与hystrix的整合的时候有配置超时时间，在hystrix熔断时间内可以重试。
sentinel支持ribbon重试机制吗?

**Comment by sczyh30** [comment]
cc @fangjian0423

**Comment by fangjian0423** [comment]
Could you provider a sample to describe hystrix & ribbon retry mechanism?

**Comment by sczyh30** [comment]
@wang271724646 Any references about the feature?

**Comment by sczyh30** [comment]
Closing this issue due to no response.
