### ISSUE TITLE
Login problem in sentinel cluster environment

### ISSUE THREAD

**Issue by lzq2357** [alibaba/Sentinel#996]
## Issue Description

Type: *bug report*
sentinel如果是两台机器以上，经过扩展后后端可以session共享实现统一登录。但是前端页面会有判断逻辑，限制登录。
resources/app/scripts/directives/header/header.js: 第14行

### Describe what happened (or what feature you want)
A、B两台机器，用户访问A登录后，再通过B访问其他接口数据。前端页面会自动跳转到登录页

### Describe what you expected to happen
通过后端扩展后，可以SSO

### How to reproduce it (as minimally and precisely as possible)

1. 本地模拟端口两台机器。port1, port2
2. 通过port1端口登录后，
3. 通过port2访问 /dashboard 

### Tell us your environment
单机环境，通过两个端口，启动了两个 sentinel实例
通过把 session信息写入 第三方服务器，比如redis即可

**Comment by jasonjoo2010** [comment]
Do you mean the dashboard? Session problem is not the only one.

Please refer to the discussion #554

**Comment by lzq2357** [comment]
@jasonjoo2010 
看了下，应该是 localStorage  作用域问题，同一个域名下不同端口不能共享。如果使用niginx同一个域名的话，应该是可以解决这个问题的。
