### ISSUE TITLE
service is deployed in docker, sentinel responses with docker ip.

### ISSUE THREAD

**Issue by stockwyz** [alibaba/Sentinel#998]
micro service is deployed in docker, it  depend on spring-cloud-starter-alibaba-sentinel (artifactid) and monitored by sentinel. I found that sentinel server visited (http://172.17.0.2:8719/metric?startTime=XXXX&...... ). But 172.17.0.2 is not true ip, so the call is failed and I don't see any statistic data from sentinel dashboard. How can I do with the problem?
                                       thanks guys

**Comment by sczyh30** [comment]
Hi, for this scenario there's a temporary solution: you can set the real client ip via the `-Dcsp.sentinel.heartbeat.client.ip` system property. See #246 for more information.
