### ISSUE TITLE
Document about PropertyUrlCleaner

### ISSUE THREAD

**Issue by eacdy** [alibaba/Sentinel#999]
I use Ahas and I find that It offers a PropertyUrlCleaner.
Could we add some DOCUMENT about PropertyUrlCleaner TELLING us how to use it?
Thanks a looooooooooooooooot.

B.T.W, I don't think it's a good approach to add a PropertyUrlCleaner. I think it Should be optional so that We Can config lately.

翻译一下需求：
我用Spring Cloud Alibaba。
1. 提供默认的UrlCleaner可以，但应该以自己创建的为主吧……或者建议默认关闭PropertyUrlCleaner，允许用户自己配置。
2. 至少应该具备说明文档……Ahas是商用产品，但没有找到相应文档。一个内置的UrlCleaner默认嵌入在一个商业化的JAR包里，还不写任何文档……使用者会很懵的。
3. 目前设计，要用Ahas自带的Cleaner，还得额外创建一个ahas-sentinel-url-clean.properties；或者用csp.sentinel.url.clean.config.path指定目录。

**Comment by sczyh30** [comment]
Thanks for your suggestion.

> Could we add some DOCUMENT about PropertyUrlCleaner TELLING us how to use it?

We'll add the instruction for this later.

The format of the properties is `prefix=unified resource`. For example:

```
/foo/=/foo/*
```

Then the URL pattern `/foo/{id}` will be unified as the resource `/foo/*`. This is not the best way, but a basic choice for those who do not want to work on customized `UrlCleaner`.

> B.T.W, I don't think it's a good approach to add a PropertyUrlCleaner. I think it Should be optional so that We Can config lately.

Good idea. We'll improve this in the next version. Only when there is no customized `UrlCleaner` registered, the `PropertyUrlCleaner` will be used as default.

**Comment by eacdy** [comment]
@sczyh30 Thanks a lot. Should we keep this issue open until we solved this issue?
